# Non-first `delta_prev_seconds == 0` examples

This notebook shows session examples where `event_idx > 0` and `delta_prev_seconds == 0`, so the event is not the first event but has the same timestamp as the previous event.

In [1]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path('data/processed/bpi2012_complete_only/events_encoded_time_features.csv')
df = pd.read_csv(DATA_PATH)
print('rows:', len(df))
print('columns:', df.columns.tolist())

rows: 164506
columns: ['case_id', 'activity', 'lifecycle', 'timestamp', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'user_id', 'item_id']

In [2]:
zero_gap_nonfirst = df[(df['event_idx'] > 0) & (df['delta_prev_seconds'] == 0)].copy()
print('non-first zero-gap count:', len(zero_gap_nonfirst))
zero_gap_nonfirst[['case_id', 'event_idx', 'activity', 'lifecycle', 'timestamp', 'delta_prev_seconds', 'delta_start_seconds']].head(10)

non-first zero-gap count: 13993

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
5,173688,5,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,0.0,39984.697
14,173688,14,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.680
15,173688,15,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.680
16,173688,16,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.680
24,173691,6,O_SELECTED,COMPLETE,2011-10-01 12:35:46.016000+00:00,0.0,23207.760
30,173691,12,O_SELECTED,COMPLETE,2011-10-03 14:56:17.731000+00:00,0.0,204439.475
41,173691,23,A_APPROVED,COMPLETE,2011-10-10 12:17:26.307000+00:00,0.0,799708.051
42,173691,24,A_REGISTERED,COMPLETE,2011-10-10 12:17:26.307000+00:00,0.0,799708.051
52,173694,8,O_SELECTED,COMPLETE,2011-10-03 11:40:14.632000+00:00,0.0,192584.345
57,173694,13,O_SELECTED,COMPLETE,2011-10-03 11:44:17.619000+00:00,0.0,192827.332

In [3]:
sample_case_ids = zero_gap_nonfirst['case_id'].drop_duplicates().head(5).tolist()
sample_case_ids

[173688, 173691, 173694, 173715, 173718]

In [4]:
for case_id in sample_case_ids:
    print('=' * 100)
    print('case_id:', case_id)
    case_df = df[df['case_id'] == case_id].copy()
    case_df = case_df[['case_id', 'event_idx', 'activity', 'lifecycle', 'timestamp', 'delta_prev_seconds', 'delta_start_seconds']]
    display(case_df)
    print('zero-gap non-first rows in this case:')
    display(case_df[(case_df['event_idx'] > 0) & (case_df['delta_prev_seconds'] == 0)])

====================================================================================================
case_id: 173688

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
0,173688,0,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0.000,0.000
1,173688,1,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,0.334,0.334
2,173688,2,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,53.026,53.360
3,173688,3,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,39785.402,39838.762
4,173688,4,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,145.935,39984.697
5,173688,5,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,0.000,39984.697
6,173688,6,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,1.954,39986.651
7,173688,7,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,0.183,39986.834
8,173688,8,W_Completeren aanvraag,COMPLETE,2011-10-01 09:45:13.917000+00:00,2.537,39989.371
9,173688,9,W_Nabellen offertes,COMPLETE,2011-10-01 10:17:08.924000+00:00,1915.007,41904.378
10,173688,10,W_Nabellen offertes,COMPLETE,2011-10-08 14:32:00.886000+00:00,620091.962,661996.340
11,173688,11,O_SENT_BACK,COMPLETE,2011-10-10 09:33:03.668000+00:00,154862.782,816859.122
12,173688,12,W_Nabellen offertes,COMPLETE,2011-10-10 09:33:05.791000+00:00,2.123,816861.245
13,173688,13,A_ACTIVATED,COMPLETE,2011-10-13 08:37:29.226000+00:00,255863.435,1072724.680
14,173688,14,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.680
15,173688,15,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.680
16,173688,16,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.680
17,173688,17,W_Valideren aanvraag,COMPLETE,2011-10-13 08:37:37.026000+00:00,7.800,1072732.480

zero-gap non-first rows in this case:

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
5,173688,5,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,0.0,39984.697
14,173688,14,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.680
15,173688,15,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.680
16,173688,16,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.680

====================================================================================================
case_id: 173691

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
18,173691,0,A_SUBMITTED,COMPLETE,2011-10-01 06:08:58.256000+00:00,0.000,0.000
19,173691,1,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 06:09:02.195000+00:00,3.939,3.939
20,173691,2,A_PREACCEPTED,COMPLETE,2011-10-01 06:09:56.648000+00:00,54.453,58.392
21,173691,3,W_Completeren aanvraag,COMPLETE,2011-10-01 09:43:13.178000+00:00,12796.530,12854.922
22,173691,4,A_ACCEPTED,COMPLETE,2011-10-01 12:33:54.614000+00:00,10241.436,23096.358
23,173691,5,A_FINALIZED,COMPLETE,2011-10-01 12:35:46.016000+00:00,111.402,23207.760
24,173691,6,O_SELECTED,COMPLETE,2011-10-01 12:35:46.016000+00:00,0.000,23207.760
25,173691,7,O_CREATED,COMPLETE,2011-10-01 12:35:47.488000+00:00,1.472,23209.232
26,173691,8,O_SENT,COMPLETE,2011-10-01 12:35:47.583000+00:00,0.095,23209.327
27,173691,9,W_Completeren aanvraag,COMPLETE,2011-10-01 12:35:48.791000+00:00,1.208,23210.535
28,173691,10,W_Nabellen offertes,COMPLETE,2011-10-01 12:36:25.794000+00:00,37.003,23247.538
29,173691,11,O_CANCELLED,COMPLETE,2011-10-03 14:56:17.731000+00:00,181191.937,204439.475
30,173691,12,O_SELECTED,COMPLETE,2011-10-03 14:56:17.731000+00:00,0.000,204439.475
31,173691,13,O_CREATED,COMPLETE,2011-10-03 14:56:19.613000+00:00,1.882,204441.357
32,173691,14,O_SENT,COMPLETE,2011-10-03 14:56:19.645000+00:00,0.032,204441.389
33,173691,15,W_Nabellen offertes,COMPLETE,2011-10-03 14:56:21.195000+00:00,1.550,204442.939
34,173691,16,W_Nabellen offertes,COMPLETE,2011-10-03 14:57:16.563000+00:00,55.368,204498.307
35,173691,17,O_SENT_BACK,COMPLETE,2011-10-10 08:14:43.775000+00:00,580647.212,785145.519
36,173691,18,W_Nabellen offertes,COMPLETE,2011-10-10 08:14:45.514000+00:00,1.739,785147.258
37,173691,19,W_Valideren aanvraag,COMPLETE,2011-10-10 09:30:54.893000+00:00,4569.379,789716.637
38,173691,20,W_Valideren aanvraag,COMPLETE,2011-10-10 12:14:13.394000+00:00,9798.501,799515.138
39,173691,21,O_ACCEPTED,COMPLETE,2011-10-10 12:17:26.306000+00:00,192.912,799708.050
40,173691,22,A_ACTIVATED,COMPLETE,2011-10-10 12:17:26.307000+00:00,0.001,799708.051
41,173691,23,A_APPROVED,COMPLETE,2011-10-10 12:17:26.307000+00:00,0.000,799708.051
42,173691,24,A_REGISTERED,COMPLETE,2011-10-10 12:17:26.307000+00:00,0.000,799708.051
43,173691,25,W_Valideren aanvraag,COMPLETE,2011-10-10 12:17:34.633000+00:00,8.326,799716.377

zero-gap non-first rows in this case:

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
24,173691,6,O_SELECTED,COMPLETE,2011-10-01 12:35:46.016000+00:00,0.0,23207.760
30,173691,12,O_SELECTED,COMPLETE,2011-10-03 14:56:17.731000+00:00,0.0,204439.475
41,173691,23,A_APPROVED,COMPLETE,2011-10-10 12:17:26.307000+00:00,0.0,799708.051
42,173691,24,A_REGISTERED,COMPLETE,2011-10-10 12:17:26.307000+00:00,0.0,799708.051

====================================================================================================
case_id: 173694

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
44,173694,0,A_SUBMITTED,COMPLETE,2011-10-01 06:10:30.287000+00:00,0.000,0.000
45,173694,1,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 06:10:30.591000+00:00,0.304,0.304
46,173694,2,A_PREACCEPTED,COMPLETE,2011-10-01 06:11:13.026000+00:00,42.435,42.739
47,173694,3,W_Completeren aanvraag,COMPLETE,2011-10-01 09:35:59.637000+00:00,12286.611,12329.350
48,173694,4,W_Completeren aanvraag,COMPLETE,2011-10-03 09:21:22.417000+00:00,171922.780,184252.130
49,173694,5,W_Completeren aanvraag,COMPLETE,2011-10-03 11:32:43.313000+00:00,7880.896,192133.026
50,173694,6,A_ACCEPTED,COMPLETE,2011-10-03 11:34:25.421000+00:00,102.108,192235.134
51,173694,7,A_FINALIZED,COMPLETE,2011-10-03 11:40:14.632000+00:00,349.211,192584.345
52,173694,8,O_SELECTED,COMPLETE,2011-10-03 11:40:14.632000+00:00,0.000,192584.345
53,173694,9,O_CREATED,COMPLETE,2011-10-03 11:40:15.605000+00:00,0.973,192585.318
54,173694,10,O_SENT,COMPLETE,2011-10-03 11:40:15.651000+00:00,0.046,192585.364
55,173694,11,W_Completeren aanvraag,COMPLETE,2011-10-03 11:40:17.062000+00:00,1.411,192586.775
56,173694,12,O_CANCELLED,COMPLETE,2011-10-03 11:44:17.619000+00:00,240.557,192827.332
57,173694,13,O_SELECTED,COMPLETE,2011-10-03 11:44:17.619000+00:00,0.000,192827.332
58,173694,14,O_CREATED,COMPLETE,2011-10-03 11:44:19.671000+00:00,2.052,192829.384
59,173694,15,O_SENT,COMPLETE,2011-10-03 11:44:19.719000+00:00,0.048,192829.432
60,173694,16,W_Nabellen offertes,COMPLETE,2011-10-03 11:44:21.261000+00:00,1.542,192830.974
61,173694,17,W_Nabellen offertes,COMPLETE,2011-10-10 14:47:18.803000+00:00,615777.542,808608.516
62,173694,18,W_Nabellen offertes,COMPLETE,2011-10-10 17:34:36.027000+00:00,10037.224,818645.740
63,173694,19,W_Nabellen offertes,COMPLETE,2011-10-14 16:16:42.245000+00:00,340926.218,1159571.958
64,173694,20,O_CANCELLED,COMPLETE,2011-10-17 17:43:53.587000+00:00,264431.342,1424003.300
65,173694,21,O_SELECTED,COMPLETE,2011-10-17 17:43:53.587000+00:00,0.000,1424003.300
66,173694,22,O_CREATED,COMPLETE,2011-10-17 17:43:55.219000+00:00,1.632,1424004.932
67,173694,23,O_SENT,COMPLETE,2011-10-17 17:43:55.387000+00:00,0.168,1424005.100
68,173694,24,W_Nabellen offertes,COMPLETE,2011-10-17 17:43:57.774000+00:00,2.387,1424007.487
69,173694,25,W_Nabellen offertes,COMPLETE,2011-10-25 08:50:48.186000+00:00,659210.412,2083217.899
70,173694,26,W_Nabellen offertes,COMPLETE,2011-10-26 16:50:22.004000+00:00,115173.818,2198391.717
71,173694,27,W_Nabellen offertes,COMPLETE,2011-10-29 10:41:29.569000+00:00,237067.565,2435459.282
72,173694,28,W_Nabellen offertes,COMPLETE,2011-11-01 13:55:35.020000+00:00,270845.451,2706304.733
73,173694,29,W_Nabellen offertes,COMPLETE,2011-11-01 16:21:02.356000+00:00,8727.336,2715032.069
74,173694,30,O_SENT_BACK,COMPLETE,2011-11-02 08:15:16.203000+00:00,57253.847,2772285.916
75,173694,31,W_Nabellen offertes,COMPLETE,2011-11-02 08:15:18.683000+00:00,2.480,2772288.396
76,173694,32,O_ACCEPTED,COMPLETE,2011-11-04 15:04:52.611000+00:00,197373.928,2969662.324
77,173694,33,A_ACTIVATED,COMPLETE,2011-11-04 15:04:52.612000+00:00,0.001,2969662.325
78,173694,34,A_APPROVED,COMPLETE,2011-11-04 15:04:52.612000+00:00,0.000,2969662.325
79,173694,35,A_REGISTERED,COMPLETE,2011-11-04 15:04:52.612000+00:00,0.000,2969662.325
80,173694,36,W_Valideren aanvraag,COMPLETE,2011-11-04 15:05:01.532000+00:00,8.920,2969671.245

zero-gap non-first rows in this case:

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
52,173694,8,O_SELECTED,COMPLETE,2011-10-03 11:40:14.632000+00:00,0.0,192584.345
57,173694,13,O_SELECTED,COMPLETE,2011-10-03 11:44:17.619000+00:00,0.0,192827.332
65,173694,21,O_SELECTED,COMPLETE,2011-10-17 17:43:53.587000+00:00,0.0,1424003.300
78,173694,34,A_APPROVED,COMPLETE,2011-11-04 15:04:52.612000+00:00,0.0,2969662.325
79,173694,35,A_REGISTERED,COMPLETE,2011-11-04 15:04:52.612000+00:00,0.0,2969662.325

====================================================================================================
case_id: 173715

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
117,173715,0,A_SUBMITTED,COMPLETE,2011-10-01 07:59:10.501000+00:00,0.000,0.000
118,173715,1,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 07:59:10.789000+00:00,0.288,0.288
119,173715,2,A_PREACCEPTED,COMPLETE,2011-10-01 07:59:42.704000+00:00,31.915,32.203
120,173715,3,W_Completeren aanvraag,COMPLETE,2011-10-01 09:46:06.342000+00:00,6383.638,6415.841
121,173715,4,A_ACCEPTED,COMPLETE,2011-10-01 10:24:32.787000+00:00,2306.445,8722.286
122,173715,5,A_FINALIZED,COMPLETE,2011-10-01 10:30:20.556000+00:00,347.769,9070.055
123,173715,6,O_SELECTED,COMPLETE,2011-10-01 10:30:20.556000+00:00,0.000,9070.055
124,173715,7,O_CREATED,COMPLETE,2011-10-01 10:30:21.780000+00:00,1.224,9071.279
125,173715,8,O_SENT,COMPLETE,2011-10-01 10:30:21.806000+00:00,0.026,9071.305
126,173715,9,W_Completeren aanvraag,COMPLETE,2011-10-01 10:30:24.155000+00:00,2.349,9073.654
127,173715,10,W_Nabellen offertes,COMPLETE,2011-10-08 14:38:17.372000+00:00,619673.217,628746.871
128,173715,11,O_SENT_BACK,COMPLETE,2011-10-10 10:54:03.401000+00:00,159346.029,788092.900
129,173715,12,W_Nabellen offertes,COMPLETE,2011-10-10 10:54:04.785000+00:00,1.384,788094.284
130,173715,13,A_DECLINED,COMPLETE,2011-10-13 09:05:24.620000+00:00,252679.835,1040774.119
131,173715,14,O_DECLINED,COMPLETE,2011-10-13 09:05:24.620000+00:00,0.000,1040774.119
132,173715,15,W_Valideren aanvraag,COMPLETE,2011-10-13 09:05:28.082000+00:00,3.462,1040777.581

zero-gap non-first rows in this case:

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
123,173715,6,O_SELECTED,COMPLETE,2011-10-01 10:30:20.556000+00:00,0.0,9070.055
131,173715,14,O_DECLINED,COMPLETE,2011-10-13 09:05:24.620000+00:00,0.0,1040774.119

====================================================================================================
case_id: 173718

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
133,173718,0,A_SUBMITTED,COMPLETE,2011-10-01 08:37:39.363000+00:00,0.000,0.000
134,173718,1,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 08:37:39.657000+00:00,0.294,0.294
135,173718,2,A_PREACCEPTED,COMPLETE,2011-10-01 08:38:20.967000+00:00,41.310,41.604
136,173718,3,A_ACCEPTED,COMPLETE,2011-10-01 08:42:21.977000+00:00,241.010,282.614
137,173718,4,A_FINALIZED,COMPLETE,2011-10-01 08:44:40.725000+00:00,138.748,421.362
138,173718,5,O_SELECTED,COMPLETE,2011-10-01 08:44:40.725000+00:00,0.000,421.362
139,173718,6,O_CREATED,COMPLETE,2011-10-01 08:44:42.707000+00:00,1.982,423.344
140,173718,7,O_SENT,COMPLETE,2011-10-01 08:44:42.734000+00:00,0.027,423.371
141,173718,8,W_Completeren aanvraag,COMPLETE,2011-10-01 08:44:43.954000+00:00,1.220,424.591
142,173718,9,W_Nabellen offertes,COMPLETE,2011-10-01 08:44:58.974000+00:00,15.020,439.611
143,173718,10,O_CANCELLED,COMPLETE,2011-10-01 08:46:52.915000+00:00,113.941,553.552
144,173718,11,O_SELECTED,COMPLETE,2011-10-01 08:46:52.915000+00:00,0.000,553.552
145,173718,12,O_CREATED,COMPLETE,2011-10-01 08:46:54.210000+00:00,1.295,554.847
146,173718,13,O_SENT,COMPLETE,2011-10-01 08:46:54.233000+00:00,0.023,554.870
147,173718,14,W_Nabellen offertes,COMPLETE,2011-10-01 08:46:56.631000+00:00,2.398,557.268
148,173718,15,W_Nabellen offertes,COMPLETE,2011-10-01 08:50:20.533000+00:00,203.902,761.170
149,173718,16,W_Nabellen offertes,COMPLETE,2011-10-01 08:50:34.704000+00:00,14.171,775.341
150,173718,17,W_Nabellen offertes,COMPLETE,2011-10-08 14:31:37.972000+00:00,625263.268,626038.609
151,173718,18,O_SENT_BACK,COMPLETE,2011-10-10 08:55:04.984000+00:00,152607.012,778645.621
152,173718,19,W_Nabellen offertes,COMPLETE,2011-10-10 08:55:07.452000+00:00,2.468,778648.089
153,173718,20,W_Valideren aanvraag,COMPLETE,2011-10-13 10:36:12.529000+00:00,265265.077,1043913.166
154,173718,21,W_Nabellen incomplete dossiers,COMPLETE,2011-10-13 11:05:42.290000+00:00,1769.761,1045682.927
155,173718,22,W_Nabellen incomplete dossiers,COMPLETE,2011-10-13 11:53:16.314000+00:00,2854.024,1048536.951
156,173718,23,W_Nabellen incomplete dossiers,COMPLETE,2011-10-13 15:12:01.909000+00:00,11925.595,1060462.546
157,173718,24,W_Nabellen incomplete dossiers,COMPLETE,2011-10-13 15:14:13.926000+00:00,132.017,1060594.563
158,173718,25,W_Nabellen incomplete dossiers,COMPLETE,2011-10-13 15:14:26.112000+00:00,12.186,1060606.749
159,173718,26,W_Nabellen incomplete dossiers,COMPLETE,2011-10-15 13:17:31.488000+00:00,165785.376,1226392.125
160,173718,27,W_Nabellen incomplete dossiers,COMPLETE,2011-10-15 14:56:14.624000+00:00,5923.136,1232315.261
161,173718,28,W_Nabellen incomplete dossiers,COMPLETE,2011-10-17 11:32:51.911000+00:00,160597.287,1392912.548
162,173718,29,W_Nabellen incomplete dossiers,COMPLETE,2011-10-17 12:28:36.881000+00:00,3344.970,1396257.518
163,173718,30,W_Nabellen incomplete dossiers,COMPLETE,2011-10-18 14:46:24.246000+00:00,94667.365,1490924.883
164,173718,31,W_Nabellen incomplete dossiers,COMPLETE,2011-10-18 15:46:34.802000+00:00,3610.556,1494535.439
165,173718,32,W_Valideren aanvraag,COMPLETE,2011-10-19 06:53:21.372000+00:00,54406.570,1548942.009
166,173718,33,W_Nabellen incomplete dossiers,COMPLETE,2011-10-19 07:17:01.695000+00:00,1420.323,1550362.332
167,173718,34,W_Nabellen incomplete dossiers,COMPLETE,2011-10-19 07:24:19.095000+00:00,437.400,1550799.732
168,173718,35,W_Nabellen incomplete dossiers,COMPLETE,2011-10-20 07:30:32.963000+00:00,86773.868,1637573.600
169,173718,36,W_Nabellen incomplete dossiers,COMPLETE,2011-10-24 13:24:55.532000+00:00,366862.569,2004436.169
170,173718,37,W_Nabellen incomplete dossiers,COMPLETE,2011-10-26 06:12:38.415000+00:00,146862.883,2151299.052
171,173718,38,A_APPROVED,COMPLETE,2011-10-27 07:17:53.327000+00:00,90314.912,2241613.964
172,173718,39,O_ACCEPTED,COMPLETE,2011-10-27 07:17:53.327000+00:00,0.000,2241613.964
173,173718,40,A_ACTIVATED,COMPLETE,2011-10-27 07:17:53.328000+00:00,0.001,2241613.965
174,173718,41,A_REGISTERED,COMPLETE,2011-10-27 07:17:53.328000+00:00,0.000,2241613.965
175,173718,42,W_Valideren aanvraag,COMPLETE,2011-10-27 07:18:01.790000+00:00,8.462,2241622.427

zero-gap non-first rows in this case:

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
138,173718,5,O_SELECTED,COMPLETE,2011-10-01 08:44:40.725000+00:00,0.0,421.362
144,173718,11,O_SELECTED,COMPLETE,2011-10-01 08:46:52.915000+00:00,0.0,553.552
172,173718,39,O_ACCEPTED,COMPLETE,2011-10-27 07:17:53.327000+00:00,0.0,2241613.964
174,173718,41,A_REGISTERED,COMPLETE,2011-10-27 07:17:53.328000+00:00,0.0,2241613.965

In [5]:
case_id = sample_case_ids[0]
case_df = df[df['case_id'] == case_id].copy()
idxs = case_df[(case_df['event_idx'] > 0) & (case_df['delta_prev_seconds'] == 0)]['event_idx'].tolist()
print('focus case_id:', case_id)
print('zero-gap non-first event_idx:', idxs)
for idx in idxs:
    print('-' * 100)
    print('window around event_idx =', idx)
    window = case_df[(case_df['event_idx'] >= idx - 2) & (case_df['event_idx'] <= idx + 2)].copy()
    display(window[['case_id', 'event_idx', 'activity', 'lifecycle', 'timestamp', 'delta_prev_seconds', 'delta_start_seconds']])

focus case_id: 173688
zero-gap non-first event_idx: [5, 14, 15, 16]
----------------------------------------------------------------------------------------------------
window around event_idx = 5

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
3,173688,3,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,39785.402,39838.762
4,173688,4,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,145.935,39984.697
5,173688,5,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,0.000,39984.697
6,173688,6,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,1.954,39986.651
7,173688,7,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,0.183,39986.834

----------------------------------------------------------------------------------------------------
window around event_idx = 14

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
12,173688,12,W_Nabellen offertes,COMPLETE,2011-10-10 09:33:05.791000+00:00,2.123,816861.245
13,173688,13,A_ACTIVATED,COMPLETE,2011-10-13 08:37:29.226000+00:00,255863.435,1072724.680
14,173688,14,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.680
15,173688,15,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.680
16,173688,16,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.680

----------------------------------------------------------------------------------------------------
window around event_idx = 15

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
13,173688,13,A_ACTIVATED,COMPLETE,2011-10-13 08:37:29.226000+00:00,255863.435,1072724.68
14,173688,14,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.68
15,173688,15,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.68
16,173688,16,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.000,1072724.68
17,173688,17,W_Valideren aanvraag,COMPLETE,2011-10-13 08:37:37.026000+00:00,7.800,1072732.48

----------------------------------------------------------------------------------------------------
window around event_idx = 16

,case_id,event_idx,activity,lifecycle,timestamp,delta_prev_seconds,delta_start_seconds
14,173688,14,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.68
15,173688,15,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.68
16,173688,16,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,0.0,1072724.68
17,173688,17,W_Valideren aanvraag,COMPLETE,2011-10-13 08:37:37.026000+00:00,7.8,1072732.48