# BPI 2012 local preprocessing test

This notebook covers the first two steps:
1. Convert the XES log into an event table.
2. Extract a small subset of cases for local VSCode development.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve().parent if Path.cwd().name == 'notebooks' else Path.cwd().resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

C:\Users\hyewoo choi\Documents\99. 대학원\0. 논문\git\time-aware-behavior-prediction

In [2]:
from src.preprocess_bpi2012 import load_bpi2012_events, sample_cases, save_event_table, summarize_event_table

In [5]:
XES_PATH = PROJECT_ROOT / 'data' / 'BPIC2012' / 'BPI_Challenge_2012.xes'
INTERIM_DIR = PROJECT_ROOT / 'data' / 'interim'
LOCAL_DIR = PROJECT_ROOT / 'sample_data' / 'bpi2012_local'

log_df = load_bpi2012_events(
    xes_path=XES_PATH,
    include_lifecycle=False,
    # lifecycle_filter='COMPLETE',
)

summary = summarize_event_table(log_df)
summary

EventTableSummary(num_cases=13087, num_events=262200, num_activities=24, min_case_length=3, median_case_length=11.0, max_case_length=175)

In [6]:
type(log_df)

pandas.DataFrame

In [7]:
log_df.shape

(262200, 5)

In [8]:
log_df.head(10)

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,W_Completeren aanvraag,SCHEDULE,2011-09-30 22:39:38.875000+00:00,3
4,173688,W_Completeren aanvraag,START,2011-10-01 09:36:46.437000+00:00,4
5,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,5
6,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,6
7,173688,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,7
8,173688,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,8
9,173688,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,9

In [10]:
log_df.iloc[30:40,]

,case_id,activity,lifecycle,timestamp,event_idx
30,173691,W_Completeren aanvraag,START,2011-10-01 09:37:32.393000+00:00,4
31,173691,W_Completeren aanvraag,COMPLETE,2011-10-01 09:43:13.178000+00:00,5
32,173691,W_Completeren aanvraag,START,2011-10-01 12:27:57.775000+00:00,6
33,173691,A_ACCEPTED,COMPLETE,2011-10-01 12:33:54.614000+00:00,7
34,173691,A_FINALIZED,COMPLETE,2011-10-01 12:35:46.016000+00:00,8
35,173691,O_SELECTED,COMPLETE,2011-10-01 12:35:46.016000+00:00,9
36,173691,O_CREATED,COMPLETE,2011-10-01 12:35:47.488000+00:00,10
37,173691,O_SENT,COMPLETE,2011-10-01 12:35:47.583000+00:00,11
38,173691,W_Nabellen offertes,SCHEDULE,2011-10-01 12:35:47.682000+00:00,12
39,173691,W_Completeren aanvraag,COMPLETE,2011-10-01 12:35:48.791000+00:00,13

In [ ]:
log_df[log_df['case_id']=='173688']

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,W_Completeren aanvraag,SCHEDULE,2011-09-30 22:39:38.875000+00:00,3
4,173688,W_Completeren aanvraag,START,2011-10-01 09:36:46.437000+00:00,4
5,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,5
6,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,6
7,173688,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,7
8,173688,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,8
9,173688,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,9
10,173688,W_Nabellen offertes,SCHEDULE,2011-10-01 09:45:11.554000+00:00,10
11,173688,W_Completeren aanvraag,COMPLETE,2011-10-01 09:45:13.917000+00:00,11
12,173688,W_Nabellen offertes,START,2011-10-01 10:15:41.290000+00:00,12
13,173688,W_Nabellen offertes,COMPLETE,2011-10-01 10:17:08.924000+00:00,13
14,173688,W_Nabellen offertes,START,2011-10-08 14:26:57.720000+00:00,14
15,173688,W_Nabellen offertes,COMPLETE,2011-10-08 14:32:00.886000+00:00,15
16,173688,W_Nabellen offertes,START,2011-10-10 09:32:22.495000+00:00,16
17,173688,O_SENT_BACK,COMPLETE,2011-10-10 09:33:03.668000+00:00,17
18,173688,W_Valideren aanvraag,SCHEDULE,2011-10-10 09:33:04.560000+00:00,18
19,173688,W_Nabellen offertes,COMPLETE,2011-10-10 09:33:05.791000+00:00,19
20,173688,W_Valideren aanvraag,START,2011-10-13 08:05:26.925000+00:00,20
21,173688,A_ACTIVATED,COMPLETE,2011-10-13 08:37:29.226000+00:00,21
22,173688,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,22
23,173688,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,23
24,173688,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,24
25,173688,W_Valideren aanvraag,COMPLETE,2011-10-13 08:37:37.026000+00:00,25

In [11]:
log_df[log_df['case_id']=='173691']

,case_id,activity,lifecycle,timestamp,event_idx
26,173691,A_SUBMITTED,COMPLETE,2011-10-01 06:08:58.256000+00:00,0
27,173691,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 06:09:02.195000+00:00,1
28,173691,A_PREACCEPTED,COMPLETE,2011-10-01 06:09:56.648000+00:00,2
29,173691,W_Completeren aanvraag,SCHEDULE,2011-10-01 06:09:59.578000+00:00,3
30,173691,W_Completeren aanvraag,START,2011-10-01 09:37:32.393000+00:00,4
31,173691,W_Completeren aanvraag,COMPLETE,2011-10-01 09:43:13.178000+00:00,5
32,173691,W_Completeren aanvraag,START,2011-10-01 12:27:57.775000+00:00,6
33,173691,A_ACCEPTED,COMPLETE,2011-10-01 12:33:54.614000+00:00,7
34,173691,A_FINALIZED,COMPLETE,2011-10-01 12:35:46.016000+00:00,8
35,173691,O_SELECTED,COMPLETE,2011-10-01 12:35:46.016000+00:00,9
36,173691,O_CREATED,COMPLETE,2011-10-01 12:35:47.488000+00:00,10
37,173691,O_SENT,COMPLETE,2011-10-01 12:35:47.583000+00:00,11
38,173691,W_Nabellen offertes,SCHEDULE,2011-10-01 12:35:47.682000+00:00,12
39,173691,W_Completeren aanvraag,COMPLETE,2011-10-01 12:35:48.791000+00:00,13
40,173691,W_Nabellen offertes,START,2011-10-01 12:36:13.443000+00:00,14
41,173691,W_Nabellen offertes,COMPLETE,2011-10-01 12:36:25.794000+00:00,15
42,173691,W_Nabellen offertes,START,2011-10-03 14:54:43.257000+00:00,16
43,173691,O_CANCELLED,COMPLETE,2011-10-03 14:56:17.731000+00:00,17
44,173691,O_SELECTED,COMPLETE,2011-10-03 14:56:17.731000+00:00,18
45,173691,O_CREATED,COMPLETE,2011-10-03 14:56:19.613000+00:00,19
46,173691,O_SENT,COMPLETE,2011-10-03 14:56:19.645000+00:00,20
47,173691,W_Nabellen offertes,SCHEDULE,2011-10-03 14:56:19.941000+00:00,21
48,173691,W_Nabellen offertes,COMPLETE,2011-10-03 14:56:21.195000+00:00,22
49,173691,W_Nabellen offertes,START,2011-10-03 14:56:34.792000+00:00,23
50,173691,W_Nabellen offertes,COMPLETE,2011-10-03 14:57:16.563000+00:00,24
51,173691,W_Nabellen offertes,START,2011-10-10 08:13:44.827000+00:00,25
52,173691,O_SENT_BACK,COMPLETE,2011-10-10 08:14:43.775000+00:00,26
53,173691,W_Valideren aanvraag,SCHEDULE,2011-10-10 08:14:44.052000+00:00,27
54,173691,W_Nabellen offertes,COMPLETE,2011-10-10 08:14:45.514000+00:00,28
55,173691,W_Valideren aanvraag,START,2011-10-10 09:12:36.612000+00:00,29
56,173691,W_Valideren aanvraag,COMPLETE,2011-10-10 09:30:54.893000+00:00,30
57,173691,W_Valideren aanvraag,START,2011-10-10 12:11:42.124000+00:00,31
58,173691,W_Valideren aanvraag,COMPLETE,2011-10-10 12:14:13.394000+00:00,32
59,173691,W_Valideren aanvraag,START,2011-10-10 12:14:52.842000+00:00,33
60,173691,O_ACCEPTED,COMPLETE,2011-10-10 12:17:26.306000+00:00,34
61,173691,A_ACTIVATED,COMPLETE,2011-10-10 12:17:26.307000+00:00,35
62,173691,A_APPROVED,COMPLETE,2011-10-10 12:17:26.307000+00:00,36
63,173691,A_REGISTERED,COMPLETE,2011-10-10 12:17:26.307000+00:00,37
64,173691,W_Valideren aanvraag,COMPLETE,2011-10-10 12:17:34.633000+00:00,38

In [ ]:
import pandas as pd

print(log_df['activity'].nunique())

temp = pd.DataFrame({
    "count": log_df['activity'].value_counts(dropna=False),
    "ratio": log_df['activity'].value_counts(dropna=False, normalize=True)
})
temp["percent"] = (temp["ratio"] * 100).round(2)
temp

In [ ]:
# summary의 각 항목들의 의미
# log_df의 각 컬럼값들과 얼마나 되는지.. .분포는....

In [ ]:
full_log_path = save_event_table(log_df, INTERIM_DIR / 'bpi2012_events_complete_only.csv')
print(full_log_path)

In [ ]:
N_LOCAL_CASES = 500
local_log_df = sample_cases(log_df, n_cases=N_LOCAL_CASES, strategy='earliest')
local_summary = summarize_event_table(local_log_df)
local_summary

In [ ]:
local_log_df.shape

In [ ]:
local_log_df.head(10)

In [ ]:
local_log_path = save_event_table(local_log_df, LOCAL_DIR / 'bpi2012_events_complete_only_500_cases.csv')
print(local_log_path)