# BPI 2012 SASRec preprocessing - 500 cases

Builds a local 500-case sample for VSCode development and saves SASRec plus time-aware preprocessing outputs.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve().parent if Path.cwd().name == 'notebooks' else Path.cwd().resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

C:\Users\hyewoo choi\Documents\99. 대학원\0. 논문\git\time-aware-behavior-prediction

In [2]:
from src.preprocess_bpi2012 import (
    case_length_distribution,
    load_bpi2012_events,
    prepare_sasrec_dataset,
    sample_cases,
    save_preprocess_result,
    summarize_event_table,
)

In [3]:
XES_PATH = PROJECT_ROOT / 'data' / 'BPIC2012' / 'BPI_Challenge_2012.xes'
OUT_DIR = PROJECT_ROOT / 'sample_data' / 'bpi2012_500_cases'
MIN_CASE_LENGTH = 3
N_LOCAL_CASES = 500

In [4]:
log_df = load_bpi2012_events(
    xes_path=XES_PATH,
    include_lifecycle=False,
    lifecycle_filter='COMPLETE',
)

summarize_event_table(log_df)

EventTableSummary(num_cases=13087, num_events=164506, num_activities=23, min_case_length=3, median_case_length=7.0, max_case_length=96)

In [5]:
log_df.head(5)

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4

In [18]:
sample_df = sample_cases(log_df, n_cases=N_LOCAL_CASES, strategy='earliest')
result = prepare_sasrec_dataset(sample_df, min_case_length=MIN_CASE_LENGTH)

summarize_event_table(result.events), result.encoding_summary

(EventTableSummary(num_cases=500, num_events=7070, num_activities=23, min_case_length=3, median_case_length=10.5, max_case_length=75),
 EncodingSummary(num_users=500, num_items=23, num_interactions=7070))

In [19]:
sample_df.head(5)

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4

In [20]:
type(sample_df), type(result)

(pandas.DataFrame, src.preprocess_bpi2012.PreprocessResult)

In [21]:
result

PreprocessResult(events=     case_id                activity lifecycle  \
0     173688             A_SUBMITTED  COMPLETE
1     173688       A_PARTLYSUBMITTED  COMPLETE
2     173688           A_PREACCEPTED  COMPLETE
3     173688              A_ACCEPTED  COMPLETE
4     173688             A_FINALIZED  COMPLETE
...      ...                     ...       ...
7065  175260  W_Completeren aanvraag  COMPLETE
7066  175260  W_Completeren aanvraag  COMPLETE
7067  175260  W_Completeren aanvraag  COMPLETE
7068  175260             A_CANCELLED  COMPLETE
7069  175260  W_Completeren aanvraag  COMPLETE

                            timestamp  event_idx
0    2011-09-30 22:38:44.546000+00:00          0
1    2011-09-30 22:38:44.880000+00:00          1
2    2011-09-30 22:39:37.906000+00:00          2
3    2011-10-01 09:42:43.308000+00:00          3
4    2011-10-01 09:45:09.243000+00:00          4
...                               ...        ...
7065 2011-10-07 10:18:47.538000+00:00          7
7066 2011-10-07 10:39:07.945000+00:00          8
7067 2011-10-10 07:50:14.098000+00:00          9
7068 2011-10-10 15:10:41.585000+00:00         10
7069 2011-10-10 15:10:43.355000+00:00         11

[7070 rows x 5 columns], encoded_events=     case_id                activity lifecycle  \
0     173688             A_SUBMITTED  COMPLETE
1     173688       A_PARTLYSUBMITTED  COMPLETE
2     173688           A_PREACCEPTED  COMPLETE
3     173688              A_ACCEPTED  COMPLETE
4     173688             A_FINALIZED  COMPLETE
...      ...                     ...       ...
7065  175260  W_Completeren aanvraag  COMPLETE
7066  175260  W_Completeren aanvraag  COMPLETE
7067  175260  W_Completeren aanvraag  COMPLETE
7068  175260             A_CANCELLED  COMPLETE
7069  175260  W_Completeren aanvraag  COMPLETE

                            timestamp  event_idx  delta_prev_seconds  \
0    2011-09-30 22:38:44.546000+00:00          0               0.000
1    2011-09-30 22:38:44.880000+00:00          1               0.334
2    2011-09-30 22:39:37.906000+00:00          2              53.026
3    2011-10-01 09:42:43.308000+00:00          3           39785.402
4    2011-10-01 09:45:09.243000+00:00          4             145.935
...                               ...        ...                 ...
7065 2011-10-07 10:18:47.538000+00:00          7             592.409
7066 2011-10-07 10:39:07.945000+00:00          8            1220.407
7067 2011-10-10 07:50:14.098000+00:00          9          249066.153
7068 2011-10-10 15:10:41.585000+00:00         10           26427.487
7069 2011-10-10 15:10:43.355000+00:00         11               1.770

      delta_start_seconds  user_id  item_id
0                   0.000        1       10
1                   0.334        1        7
2                  53.360        1        8
3               39838.762        1        1
4               39984.697        1        6
...                   ...      ...      ...
7065             8476.150      500       20
7066             9696.557      500       20
7067           258762.710      500       20
7068           285190.197      500        4
7069           285191.967      500       20

[7070 rows x 9 columns], user_map=    case_id  user_id
0    173688        1
1    173691        2
2    173694        3
3    173697        4
4    173700        5
..      ...      ...
495  175248      496
496  175251      497
497  175254      498
498  175257      499
499  175260      500

[500 rows x 2 columns], item_map=                          activity  item_id
0                       A_ACCEPTED        1
1                      A_ACTIVATED        2
2                       A_APPROVED        3
3                      A_CANCELLED        4
4                       A_DECLINED        5
5                      A_FINALIZED        6
6                A_PARTLYSUBMITTED        7
7                    A_PREACCEPTED        8
8                     A_REGISTERED        9
9                      A_SUBMITTED       10
10                      O_ACCEPTED       11
11                     O_CANCELLED       12
12                       O_CREATED       13
13                      O_DECLINED       14
14                      O_SELECTED       15
15                          O_SENT       16
16                     O_SENT_BACK       17
17              W_Afhandelen leads       18
18             W_Beoordelen fraude       19
19          W_Completeren aanvraag       20
20  W_Nabellen incomplete dossiers       21
21             W_Nabellen offertes       22
22            W_Valideren aanvraag       23, sasrec_interactions=      user_id  item_id
0           1       10
1           1        7
2           1        8
3           1        1
4           1        6
...       ...      ...
7065      500       20
7066      500       20
7067      500       20
7068      500        4
7069      500       20

[7070 rows x 2 columns], encoding_summary=EncodingSummary(num_users=500, num_items=23, num_interactions=7070))

In [22]:
result.events

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4
...,...,...,...,...,...
7065,175260,W_Completeren aanvraag,COMPLETE,2011-10-07 10:18:47.538000+00:00,7
7066,175260,W_Completeren aanvraag,COMPLETE,2011-10-07 10:39:07.945000+00:00,8
7067,175260,W_Completeren aanvraag,COMPLETE,2011-10-10 07:50:14.098000+00:00,9
7068,175260,A_CANCELLED,COMPLETE,2011-10-10 15:10:41.585000+00:00,10
7069,175260,W_Completeren aanvraag,COMPLETE,2011-10-10 15:10:43.355000+00:00,11

In [23]:
result.encoded_events

,case_id,activity,lifecycle,timestamp,event_idx,delta_prev_seconds,delta_start_seconds,user_id,item_id
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0,0.000,0.000,1,10
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1,0.334,0.334,1,7
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2,53.026,53.360,1,8
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3,39785.402,39838.762,1,1
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4,145.935,39984.697,1,6
...,...,...,...,...,...,...,...,...,...
7065,175260,W_Completeren aanvraag,COMPLETE,2011-10-07 10:18:47.538000+00:00,7,592.409,8476.150,500,20
7066,175260,W_Completeren aanvraag,COMPLETE,2011-10-07 10:39:07.945000+00:00,8,1220.407,9696.557,500,20
7067,175260,W_Completeren aanvraag,COMPLETE,2011-10-10 07:50:14.098000+00:00,9,249066.153,258762.710,500,20
7068,175260,A_CANCELLED,COMPLETE,2011-10-10 15:10:41.585000+00:00,10,26427.487,285190.197,500,4
7069,175260,W_Completeren aanvraag,COMPLETE,2011-10-10 15:10:43.355000+00:00,11,1.770,285191.967,500,20

In [24]:
result.user_map

    case_id  user_id
0    173688        1
1    173691        2
2    173694        3
3    173697        4
4    173700        5
..      ...      ...
495  175248      496
496  175251      497
497  175254      498
498  175257      499
499  175260      500

[500 rows x 2 columns]

In [25]:
result.item_map

                          activity  item_id
0                       A_ACCEPTED        1
1                      A_ACTIVATED        2
2                       A_APPROVED        3
3                      A_CANCELLED        4
4                       A_DECLINED        5
5                      A_FINALIZED        6
6                A_PARTLYSUBMITTED        7
7                    A_PREACCEPTED        8
8                     A_REGISTERED        9
9                      A_SUBMITTED       10
10                      O_ACCEPTED       11
11                     O_CANCELLED       12
12                       O_CREATED       13
13                      O_DECLINED       14
14                      O_SELECTED       15
15                          O_SENT       16
16                     O_SENT_BACK       17
17              W_Afhandelen leads       18
18             W_Beoordelen fraude       19
19          W_Completeren aanvraag       20
20  W_Nabellen incomplete dossiers       21
21             W_Nabellen offertes       22
22            W_Valideren aanvraag       23

In [26]:
result.sasrec_interactions

      user_id  item_id
0           1       10
1           1        7
2           1        8
3           1        1
4           1        6
...       ...      ...
7065      500       20
7066      500       20
7067      500       20
7068      500        4
7069      500       20

[7070 rows x 2 columns]

In [27]:
result.encoding_summary

EncodingSummary(num_users=500, num_items=23, num_interactions=7070)

In [29]:
case_length_distribution(sample_df)

    case_length  num_cases
0             3        107
1             4         67
2             5         18
3             6         23
4             7         16
5             8         10
6             9          6
7            10          3
8            11          5
9            12          6
10           13          8
11           14          9
12           15          7
13           16         16
14           17         19
15           18         15
16           19         14
17           20         12
18           21         12
19           22         12
20           23         14
21           24          8
22           25          8
23           26          4
24           27         11
25           28          8
26           29          8
27           30          5
28           31          7
29           32          4
30           33          2
31           34          3
32           35          2
33           36          7
34           37          2
35           38          5
36           39          2
37           40          3
38           41          1
39           42          1
40           43          2
41           47          1
42           49          2
43           52          1
44           56          1
45           62          1
46           67          1
47           75          1

In [30]:
result.encoded_events.head(10)

,case_id,activity,lifecycle,timestamp,event_idx,delta_prev_seconds,delta_start_seconds,user_id,item_id
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0,0.000,0.000,1,10
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1,0.334,0.334,1,7
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2,53.026,53.360,1,8
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3,39785.402,39838.762,1,1
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4,145.935,39984.697,1,6
5,173688,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,5,0.000,39984.697,1,15
6,173688,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,6,1.954,39986.651,1,13
7,173688,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,7,0.183,39986.834,1,16
8,173688,W_Completeren aanvraag,COMPLETE,2011-10-01 09:45:13.917000+00:00,8,2.537,39989.371,1,20
9,173688,W_Nabellen offertes,COMPLETE,2011-10-01 10:17:08.924000+00:00,9,1915.007,41904.378,1,22

In [31]:
paths = save_preprocess_result(result, OUT_DIR)
paths

{'events': WindowsPath('C:/Users/hyewoo choi/Documents/99. 대학원/0. 논문/git/time-aware-behavior-prediction/sample_data/bpi2012_500_cases/events_complete_only_filtered.csv'),
 'time_features': WindowsPath('C:/Users/hyewoo choi/Documents/99. 대학원/0. 논문/git/time-aware-behavior-prediction/sample_data/bpi2012_500_cases/events_encoded_time_features.csv'),
 'user_map': WindowsPath('C:/Users/hyewoo choi/Documents/99. 대학원/0. 논문/git/time-aware-behavior-prediction/sample_data/bpi2012_500_cases/user_map.csv'),
 'item_map': WindowsPath('C:/Users/hyewoo choi/Documents/99. 대학원/0. 논문/git/time-aware-behavior-prediction/sample_data/bpi2012_500_cases/item_map.csv'),
 'sasrec_txt': WindowsPath('C:/Users/hyewoo choi/Documents/99. 대학원/0. 논문/git/time-aware-behavior-prediction/sample_data/bpi2012_500_cases/sasrec_interactions.txt'),
 'sasrec_csv': WindowsPath('C:/Users/hyewoo choi/Documents/99. 대학원/0. 논문/git/time-aware-behavior-prediction/sample_data/bpi2012_500_cases/sasrec_interactions.csv')}

In [32]:
print('SASRec rows:', len(result.sasrec_interactions))
print('Users:', result.user_map['user_id'].nunique())
print('Items:', result.item_map['item_id'].nunique())
print('Min case length after filtering:', result.encoded_events.groupby('user_id').size().min())

SASRec rows: 7070
Users: 500
Items: 23
Min case length after filtering: 3