# BPI 2012 local preprocessing test

This notebook covers the first two steps:
1. Convert the XES log into an event table.
2. Extract a small subset of cases for local VSCode development.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve().parent if Path.cwd().name == 'notebooks' else Path.cwd().resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

C:\Users\hyewoo choi\Documents\99. 대학원\0. 논문\git\time-aware-behavior-prediction

In [2]:
from src.preprocess_bpi2012 import load_bpi2012_events, sample_cases, save_event_table, summarize_event_table

In [3]:
XES_PATH = PROJECT_ROOT / 'data' / 'BPIC2012' / 'BPI_Challenge_2012.xes'
INTERIM_DIR = PROJECT_ROOT / 'data' / 'interim'
LOCAL_DIR = PROJECT_ROOT / 'sample_data' / 'bpi2012_local'

log_df = load_bpi2012_events(
    xes_path=XES_PATH,
    include_lifecycle=False,
    lifecycle_filter='COMPLETE',
)

summary = summarize_event_table(log_df)
summary

EventTableSummary(num_cases=13087, num_events=164506, num_activities=23, min_case_length=3, median_case_length=7.0, max_case_length=96)

In [4]:
type(log_df)

pandas.DataFrame

In [5]:
log_df.shape

(164506, 5)

In [6]:
log_df.head(10)

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4
5,173688,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,5
6,173688,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,6
7,173688,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,7
8,173688,W_Completeren aanvraag,COMPLETE,2011-10-01 09:45:13.917000+00:00,8
9,173688,W_Nabellen offertes,COMPLETE,2011-10-01 10:17:08.924000+00:00,9

In [7]:
log_df[log_df['case_id']=='173688']

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4
5,173688,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,5
6,173688,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,6
7,173688,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,7
8,173688,W_Completeren aanvraag,COMPLETE,2011-10-01 09:45:13.917000+00:00,8
9,173688,W_Nabellen offertes,COMPLETE,2011-10-01 10:17:08.924000+00:00,9
10,173688,W_Nabellen offertes,COMPLETE,2011-10-08 14:32:00.886000+00:00,10
11,173688,O_SENT_BACK,COMPLETE,2011-10-10 09:33:03.668000+00:00,11
12,173688,W_Nabellen offertes,COMPLETE,2011-10-10 09:33:05.791000+00:00,12
13,173688,A_ACTIVATED,COMPLETE,2011-10-13 08:37:29.226000+00:00,13
14,173688,A_APPROVED,COMPLETE,2011-10-13 08:37:29.226000+00:00,14
15,173688,A_REGISTERED,COMPLETE,2011-10-13 08:37:29.226000+00:00,15
16,173688,O_ACCEPTED,COMPLETE,2011-10-13 08:37:29.226000+00:00,16
17,173688,W_Valideren aanvraag,COMPLETE,2011-10-13 08:37:37.026000+00:00,17

In [8]:
log_df[log_df['case_id']=='173691']

,case_id,activity,lifecycle,timestamp,event_idx
18,173691,A_SUBMITTED,COMPLETE,2011-10-01 06:08:58.256000+00:00,0
19,173691,A_PARTLYSUBMITTED,COMPLETE,2011-10-01 06:09:02.195000+00:00,1
20,173691,A_PREACCEPTED,COMPLETE,2011-10-01 06:09:56.648000+00:00,2
21,173691,W_Completeren aanvraag,COMPLETE,2011-10-01 09:43:13.178000+00:00,3
22,173691,A_ACCEPTED,COMPLETE,2011-10-01 12:33:54.614000+00:00,4
23,173691,A_FINALIZED,COMPLETE,2011-10-01 12:35:46.016000+00:00,5
24,173691,O_SELECTED,COMPLETE,2011-10-01 12:35:46.016000+00:00,6
25,173691,O_CREATED,COMPLETE,2011-10-01 12:35:47.488000+00:00,7
26,173691,O_SENT,COMPLETE,2011-10-01 12:35:47.583000+00:00,8
27,173691,W_Completeren aanvraag,COMPLETE,2011-10-01 12:35:48.791000+00:00,9
28,173691,W_Nabellen offertes,COMPLETE,2011-10-01 12:36:25.794000+00:00,10
29,173691,O_CANCELLED,COMPLETE,2011-10-03 14:56:17.731000+00:00,11
30,173691,O_SELECTED,COMPLETE,2011-10-03 14:56:17.731000+00:00,12
31,173691,O_CREATED,COMPLETE,2011-10-03 14:56:19.613000+00:00,13
32,173691,O_SENT,COMPLETE,2011-10-03 14:56:19.645000+00:00,14
33,173691,W_Nabellen offertes,COMPLETE,2011-10-03 14:56:21.195000+00:00,15
34,173691,W_Nabellen offertes,COMPLETE,2011-10-03 14:57:16.563000+00:00,16
35,173691,O_SENT_BACK,COMPLETE,2011-10-10 08:14:43.775000+00:00,17
36,173691,W_Nabellen offertes,COMPLETE,2011-10-10 08:14:45.514000+00:00,18
37,173691,W_Valideren aanvraag,COMPLETE,2011-10-10 09:30:54.893000+00:00,19
38,173691,W_Valideren aanvraag,COMPLETE,2011-10-10 12:14:13.394000+00:00,20
39,173691,O_ACCEPTED,COMPLETE,2011-10-10 12:17:26.306000+00:00,21
40,173691,A_ACTIVATED,COMPLETE,2011-10-10 12:17:26.307000+00:00,22
41,173691,A_APPROVED,COMPLETE,2011-10-10 12:17:26.307000+00:00,23
42,173691,A_REGISTERED,COMPLETE,2011-10-10 12:17:26.307000+00:00,24
43,173691,W_Valideren aanvraag,COMPLETE,2011-10-10 12:17:34.633000+00:00,25

In [9]:
import pandas as pd

print(log_df['activity'].nunique())

temp = pd.DataFrame({
    "count": log_df['activity'].value_counts(dropna=False),
    "ratio": log_df['activity'].value_counts(dropna=False, normalize=True)
})
temp["percent"] = (temp["ratio"] * 100).round(2)
temp

23

                                count     ratio  percent
activity
W_Completeren aanvraag          23967  0.145691    14.57
W_Nabellen offertes             22976  0.139667    13.97
A_SUBMITTED                     13087  0.079553     7.96
A_PARTLYSUBMITTED               13087  0.079553     7.96
W_Nabellen incomplete dossiers  11407  0.069341     6.93
W_Valideren aanvraag             7895  0.047992     4.80
A_DECLINED                       7635  0.046412     4.64
A_PREACCEPTED                    7367  0.044783     4.48
O_SELECTED                       7030  0.042734     4.27
O_CREATED                        7030  0.042734     4.27
O_SENT                           7030  0.042734     4.27
W_Afhandelen leads               5898  0.035853     3.59
A_ACCEPTED                       5113  0.031081     3.11
A_FINALIZED                      5015  0.030485     3.05
O_CANCELLED                      3655  0.022218     2.22
O_SENT_BACK                      3454  0.020996     2.10
A_CANCELLED                      2807  0.017063     1.71
A_ACTIVATED                      2246  0.013653     1.37
A_APPROVED                       2246  0.013653     1.37
A_REGISTERED                     2246  0.013653     1.37
O_ACCEPTED                       2243  0.013635     1.36
O_DECLINED                        802  0.004875     0.49
W_Beoordelen fraude               270  0.001641     0.16

In [10]:
full_log_path = save_event_table(log_df, INTERIM_DIR / 'bpi2012_events_complete_only.csv')
print(full_log_path)

C:\Users\hyewoo choi\Documents\99. 대학원\0. 논문\git\time-aware-behavior-prediction\data\interim\bpi2012_events_complete_only.csv

In [11]:
N_LOCAL_CASES = 500
local_log_df = sample_cases(log_df, n_cases=N_LOCAL_CASES, strategy='earliest')
local_summary = summarize_event_table(local_log_df)
local_summary

EventTableSummary(num_cases=500, num_events=7070, num_activities=23, min_case_length=3, median_case_length=10.5, max_case_length=75)

In [12]:
local_log_df.shape

(7070, 5)

In [13]:
local_log_df.head(10)

,case_id,activity,lifecycle,timestamp,event_idx
0,173688,A_SUBMITTED,COMPLETE,2011-09-30 22:38:44.546000+00:00,0
1,173688,A_PARTLYSUBMITTED,COMPLETE,2011-09-30 22:38:44.880000+00:00,1
2,173688,A_PREACCEPTED,COMPLETE,2011-09-30 22:39:37.906000+00:00,2
3,173688,A_ACCEPTED,COMPLETE,2011-10-01 09:42:43.308000+00:00,3
4,173688,A_FINALIZED,COMPLETE,2011-10-01 09:45:09.243000+00:00,4
5,173688,O_SELECTED,COMPLETE,2011-10-01 09:45:09.243000+00:00,5
6,173688,O_CREATED,COMPLETE,2011-10-01 09:45:11.197000+00:00,6
7,173688,O_SENT,COMPLETE,2011-10-01 09:45:11.380000+00:00,7
8,173688,W_Completeren aanvraag,COMPLETE,2011-10-01 09:45:13.917000+00:00,8
9,173688,W_Nabellen offertes,COMPLETE,2011-10-01 10:17:08.924000+00:00,9

In [14]:
local_log_path = save_event_table(local_log_df, LOCAL_DIR / 'bpi2012_events_complete_only_500_cases.csv')
print(local_log_path)

C:\Users\hyewoo choi\Documents\99. 대학원\0. 논문\git\time-aware-behavior-prediction\sample_data\bpi2012_local\bpi2012_events_complete_only_500_cases.csv