# SASRec Continuous Time-Aware BPI2012 Colab Train (`refine_ml50_do035` baseline)

Colab notebook for the continuous/log-delta time-aware SASRec experiment using `refine_ml50_do035` as the fixed baseline.

Goals:
- reuse the completed `refine_ml50_do035` baseline results
- train only the new continuous time-aware runs
- compare baseline vs `continuous` time encoding
- evaluate under both `NDCG@10` and `NDCG@5` model-selection criteria

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
TIMEAWARE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10'
TIMEAWARE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('TIMEAWARE_NDCG10_OUTPUT_DIR:', TIMEAWARE_NDCG10_OUTPUT_DIR)
print('TIMEAWARE_NDCG5_OUTPUT_DIR:', TIMEAWARE_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
TIMEAWARE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10
TIMEAWARE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG10_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `refine_ml50_do035`
- `hidden_units=50, num_blocks=2, num_heads=1, maxlen=50, lr=0.001, dropout=0.35`
- seeds: `42`, `2024`, `7`

Comparison targets:
- baseline (reuse existing completed runs)
- time-aware `continuous/log-delta`

Time-aware design:
- `x = item_embedding + positional_embedding + time_embedding`
- time source: `delta_prev_seconds`
- time encoding: `[log1p(delta_prev_seconds), is_first_event] -> Linear(2, hidden_units)`

## Check existing baseline runs

These baseline runs should already exist and must not be retrained.

In [10]:
from pathlib import Path

baseline_ndcg10_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
baseline_ndcg5_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

for label, output_dir, run_names in [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR), baseline_ndcg10_runs),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR), baseline_ndcg5_runs),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS
================================================================================
Baseline NDCG@5
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS

## Check planned continuous runs

Only train runs that are still missing.

In [11]:
planned_ndcg10 = [
    'timeaware_conti_refine_ml50_do035_s42',
    'timeaware_conti_refine_ml50_do035_s2024',
    'timeaware_conti_refine_ml50_do035_s7',
]
planned_ndcg5 = [
    'timeaware_conti_refine_ml50_do035_s42',
    'timeaware_conti_refine_ml50_do035_s2024',
    'timeaware_conti_refine_ml50_do035_s7',
]

for label, output_dir, run_names in [
    ('Continuous NDCG@10', Path(TIMEAWARE_NDCG10_OUTPUT_DIR), planned_ndcg10),
    ('Continuous NDCG@5', Path(TIMEAWARE_NDCG5_OUTPUT_DIR), planned_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Continuous NDCG@10
timeaware_conti_refine_ml50_do035_s42 OK
timeaware_conti_refine_ml50_do035_s2024 OK
timeaware_conti_refine_ml50_do035_s7 OK
================================================================================
Continuous NDCG@5
timeaware_conti_refine_ml50_do035_s42 OK
timeaware_conti_refine_ml50_do035_s2024 OK
timeaware_conti_refine_ml50_do035_s7 OK

## Train continuous time-aware runs for `NDCG@10`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_conti_refine_ml50_do035_s42

In [12]:
!python src/train_sasrec.py \
  --run_name timeaware_conti_refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42
epoch=1, loss=0.6162
epoch=2, loss=0.2829
epoch=3, loss=0.2114
epoch=4, loss=0.1745
epoch=5, loss=0.1501
valid [full], NDCG@5: 0.6166, HR@5: 0.7019, NDCG@10: 0.6822, HR@10: 0.9171, MRR: 0.6211
valid [sampled], NDCG@5: 0.5460, HR@5: 0.5482, NDCG@10: 0.5555, HR@10: 0.5788, MRR: 0.5611
test [full], NDCG@5: 0.6189, HR@5: 0.7512, NDCG@10: 0.6578, HR@10: 0.8828, MRR: 0.5960
test [sampled], NDCG@5: 0.2139, HR@5: 0.2196, NDCG@10: 0.2613, HR@10: 0.3728, MRR: 0.2602
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1328
epoch=7, loss=0.1223
epoch=8, loss=0.1112
epoch=9, loss=0.1060
epoch=10, loss=0.1033
valid [full], NDCG@5: 0.6553, HR@5: 0.7701, NDCG@10: 0.7187, HR@10: 0.9666, MRR: 0.6472
valid [sampled], NDCG@5: 0.5624, HR@5: 0.5768, NDCG@10: 0.5757, HR@10: 0.6175, MRR: 0.5760
test [full], NDCG@5: 0.7106, HR@5: 0.9549, NDCG@10: 0.7255, HR@10: 1.0000, MRR: 0.6330
test [sampled], NDCG@5: 0.1592, HR@5: 0.1753, NDCG@10: 0.2238, HR@10: 0.3829, MRR: 0.2172
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=0.0997
epoch=12, loss=0.0967
epoch=13, loss=0.0932
epoch=14, loss=0.0923
epoch=15, loss=0.0913
valid [full], NDCG@5: 0.6956, HR@5: 0.8471, NDCG@10: 0.7345, HR@10: 0.9726, MRR: 0.6640
valid [sampled], NDCG@5: 0.5710, HR@5: 0.5844, NDCG@10: 0.5905, HR@10: 0.6453, MRR: 0.5879
test [full], NDCG@5: 0.6697, HR@5: 0.9881, NDCG@10: 0.6740, HR@10: 1.0000, MRR: 0.5635
test [sampled], NDCG@5: 0.0990, HR@5: 0.1157, NDCG@10: 0.1577, HR@10: 0.3035, MRR: 0.1586
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0883
epoch=17, loss=0.0852
epoch=18, loss=0.0851
epoch=19, loss=0.0846
epoch=20, loss=0.0843
valid [full], NDCG@5: 0.6691, HR@5: 0.7910, NDCG@10: 0.7287, HR@10: 0.9721, MRR: 0.6575
valid [sampled], NDCG@5: 0.5608, HR@5: 0.5694, NDCG@10: 0.5738, HR@10: 0.6099, MRR: 0.5775
test [full], NDCG@5: 0.6739, HR@5: 0.9785, NDCG@10: 0.6814, HR@10: 1.0000, MRR: 0.5745
test [sampled], NDCG@5: 0.0862, HR@5: 0.0927, NDCG@10: 0.1363, HR@10: 0.2542, MRR: 0.1495
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0813
epoch=22, loss=0.0819
epoch=23, loss=0.0815
epoch=24, loss=0.0796
epoch=25, loss=0.0802
valid [full], NDCG@5: 0.6845, HR@5: 0.8105, NDCG@10: 0.7357, HR@10: 0.9698, MRR: 0.6669
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5684, NDCG@10: 0.5812, HR@10: 0.6400, MRR: 0.5778
test [full], NDCG@5: 0.6660, HR@5: 0.9835, NDCG@10: 0.6719, HR@10: 1.0000, MRR: 0.5613
test [sampled], NDCG@5: 0.0627, HR@5: 0.0707, NDCG@10: 0.1155, HR@10: 0.2414, MRR: 0.1276
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=26, loss=0.0784
epoch=27, loss=0.0810
epoch=28, loss=0.0788
epoch=29, loss=0.0800
epoch=30, loss=0.0786
valid [full], NDCG@5: 0.6931, HR@5: 0.8323, NDCG@10: 0.7304, HR@10: 0.9492, MRR: 0.6675
valid [sampled], NDCG@5: 0.5616, HR@5: 0.5672, NDCG@10: 0.5773, HR@10: 0.6166, MRR: 0.5813
test [full], NDCG@5: 0.6945, HR@5: 0.9996, NDCG@10: 0.6946, HR@10: 1.0000, MRR: 0.5914
test [sampled], NDCG@5: 0.0757, HR@5: 0.0893, NDCG@10: 0.1351, HR@10: 0.2807, MRR: 0.1395
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0785
epoch=32, loss=0.0771
epoch=33, loss=0.0783
epoch=34, loss=0.0769
epoch=35, loss=0.0766
valid [full], NDCG@5: 0.6910, HR@5: 0.8467, NDCG@10: 0.7237, HR@10: 0.9508, MRR: 0.6578
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5651, NDCG@10: 0.5756, HR@10: 0.6218, MRR: 0.5775
test [full], NDCG@5: 0.7942, HR@5: 0.9986, NDCG@10: 0.7947, HR@10: 1.0000, MRR: 0.7266
test [sampled], NDCG@5: 0.1607, HR@5: 0.2301, NDCG@10: 0.2338, HR@10: 0.4570, MRR: 0.1996
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0762
epoch=37, loss=0.0754
epoch=38, loss=0.0748
epoch=39, loss=0.0760
epoch=40, loss=0.0765
valid [full], NDCG@5: 0.6894, HR@5: 0.8352, NDCG@10: 0.7259, HR@10: 0.9505, MRR: 0.6611
valid [sampled], NDCG@5: 0.5647, HR@5: 0.5717, NDCG@10: 0.5826, HR@10: 0.6282, MRR: 0.5838
test [full], NDCG@5: 0.7080, HR@5: 0.9985, NDCG@10: 0.7085, HR@10: 1.0000, MRR: 0.6114
test [sampled], NDCG@5: 0.1507, HR@5: 0.1617, NDCG@10: 0.1937, HR@10: 0.3001, MRR: 0.2057
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0756
epoch=42, loss=0.0765
epoch=43, loss=0.0774
epoch=44, loss=0.0750
epoch=45, loss=0.0753
valid [full], NDCG@5: 0.6900, HR@5: 0.8518, NDCG@10: 0.7285, HR@10: 0.9752, MRR: 0.6559
valid [sampled], NDCG@5: 0.5619, HR@5: 0.5678, NDCG@10: 0.5746, HR@10: 0.6080, MRR: 0.5794
test [full], NDCG@5: 0.8245, HR@5: 0.9984, NDCG@10: 0.8251, HR@10: 1.0000, MRR: 0.7679
test [sampled], NDCG@5: 0.3122, HR@5: 0.3803, NDCG@10: 0.3692, HR@10: 0.5543, MRR: 0.3389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0734
epoch=47, loss=0.0734
epoch=48, loss=0.0734
epoch=49, loss=0.0735
epoch=50, loss=0.0743
valid [full], NDCG@5: 0.6775, HR@5: 0.8058, NDCG@10: 0.7242, HR@10: 0.9490, MRR: 0.6600
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5662, NDCG@10: 0.5728, HR@10: 0.6109, MRR: 0.5755
test [full], NDCG@5: 0.8429, HR@5: 0.9967, NDCG@10: 0.8441, HR@10: 1.0000, MRR: 0.7930
test [sampled], NDCG@5: 0.2609, HR@5: 0.3285, NDCG@10: 0.3212, HR@10: 0.5145, MRR: 0.2920
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s42/sasrec_last.pth

### timeaware_conti_refine_ml50_do035_s2024

In [13]:
!python src/train_sasrec.py \
  --run_name timeaware_conti_refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024
epoch=1, loss=0.6394
epoch=2, loss=0.2888
epoch=3, loss=0.2095
epoch=4, loss=0.1695
epoch=5, loss=0.1449
valid [full], NDCG@5: 0.6595, HR@5: 0.7914, NDCG@10: 0.7272, HR@10: 0.9930, MRR: 0.6474
valid [sampled], NDCG@5: 0.5548, HR@5: 0.5619, NDCG@10: 0.5669, HR@10: 0.6003, MRR: 0.5715
test [full], NDCG@5: 0.7886, HR@5: 0.9749, NDCG@10: 0.7974, HR@10: 1.0000, MRR: 0.7327
test [sampled], NDCG@5: 0.2162, HR@5: 0.2785, NDCG@10: 0.2735, HR@10: 0.4546, MRR: 0.2488
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1255
epoch=7, loss=0.1166
epoch=8, loss=0.1101
epoch=9, loss=0.1026
epoch=10, loss=0.1004
valid [full], NDCG@5: 0.6895, HR@5: 0.8599, NDCG@10: 0.7243, HR@10: 0.9702, MRR: 0.6521
valid [sampled], NDCG@5: 0.5529, HR@5: 0.5615, NDCG@10: 0.5649, HR@10: 0.5987, MRR: 0.5696
test [full], NDCG@5: 0.8230, HR@5: 0.9993, NDCG@10: 0.8233, HR@10: 1.0000, MRR: 0.7645
test [sampled], NDCG@5: 0.2178, HR@5: 0.2872, NDCG@10: 0.2856, HR@10: 0.4985, MRR: 0.2535
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0979
epoch=12, loss=0.0926
epoch=13, loss=0.0908
epoch=14, loss=0.0902
epoch=15, loss=0.0904
valid [full], NDCG@5: 0.6851, HR@5: 0.8452, NDCG@10: 0.7252, HR@10: 0.9702, MRR: 0.6533
valid [sampled], NDCG@5: 0.5646, HR@5: 0.5757, NDCG@10: 0.5757, HR@10: 0.6096, MRR: 0.5797
test [full], NDCG@5: 0.8438, HR@5: 0.9817, NDCG@10: 0.8503, HR@10: 1.0000, MRR: 0.8002
test [sampled], NDCG@5: 0.1500, HR@5: 0.2227, NDCG@10: 0.2461, HR@10: 0.5230, MRR: 0.1953
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0864
epoch=17, loss=0.0857
epoch=18, loss=0.0865
epoch=19, loss=0.0846
epoch=20, loss=0.0854
valid [full], NDCG@5: 0.6669, HR@5: 0.7968, NDCG@10: 0.7250, HR@10: 0.9716, MRR: 0.6528
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5627, NDCG@10: 0.5689, HR@10: 0.6087, MRR: 0.5714
test [full], NDCG@5: 0.8035, HR@5: 0.9641, NDCG@10: 0.8163, HR@10: 1.0000, MRR: 0.7546
test [sampled], NDCG@5: 0.2526, HR@5: 0.2935, NDCG@10: 0.3239, HR@10: 0.5179, MRR: 0.2976
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0830
epoch=22, loss=0.0812
epoch=23, loss=0.0819
epoch=24, loss=0.0827
epoch=25, loss=0.0816
valid [full], NDCG@5: 0.7106, HR@5: 0.8934, NDCG@10: 0.7344, HR@10: 0.9703, MRR: 0.6630
valid [sampled], NDCG@5: 0.5410, HR@5: 0.5560, NDCG@10: 0.5597, HR@10: 0.6143, MRR: 0.5606
test [full], NDCG@5: 0.8060, HR@5: 0.9982, NDCG@10: 0.8065, HR@10: 1.0000, MRR: 0.7399
test [sampled], NDCG@5: 0.1146, HR@5: 0.1626, NDCG@10: 0.2112, HR@10: 0.4677, MRR: 0.1722
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=26, loss=0.0786
epoch=27, loss=0.0786
epoch=28, loss=0.0790
epoch=29, loss=0.0816
epoch=30, loss=0.0776
valid [full], NDCG@5: 0.7215, HR@5: 0.9023, NDCG@10: 0.7421, HR@10: 0.9699, MRR: 0.6734
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5713, NDCG@10: 0.5775, HR@10: 0.6294, MRR: 0.5781
test [full], NDCG@5: 0.7667, HR@5: 0.9938, NDCG@10: 0.7688, HR@10: 1.0000, MRR: 0.6909
test [sampled], NDCG@5: 0.2057, HR@5: 0.2309, NDCG@10: 0.2650, HR@10: 0.4196, MRR: 0.2559
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=31, loss=0.0781
epoch=32, loss=0.0780
epoch=33, loss=0.0762
epoch=34, loss=0.0779
epoch=35, loss=0.0761
valid [full], NDCG@5: 0.7306, HR@5: 0.9051, NDCG@10: 0.7503, HR@10: 0.9704, MRR: 0.6827
valid [sampled], NDCG@5: 0.5499, HR@5: 0.5656, NDCG@10: 0.5821, HR@10: 0.6675, MRR: 0.5739
test [full], NDCG@5: 0.7779, HR@5: 0.9991, NDCG@10: 0.7782, HR@10: 1.0000, MRR: 0.7034
test [sampled], NDCG@5: 0.2733, HR@5: 0.2914, NDCG@10: 0.3127, HR@10: 0.4171, MRR: 0.3188
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=36, loss=0.0770
epoch=37, loss=0.0758
epoch=38, loss=0.0751
epoch=39, loss=0.0771
epoch=40, loss=0.0750
valid [full], NDCG@5: 0.7321, HR@5: 0.9048, NDCG@10: 0.7518, HR@10: 0.9694, MRR: 0.6857
valid [sampled], NDCG@5: 0.5625, HR@5: 0.5780, NDCG@10: 0.5914, HR@10: 0.6691, MRR: 0.5841
test [full], NDCG@5: 0.7463, HR@5: 0.9954, NDCG@10: 0.7479, HR@10: 0.9999, MRR: 0.6643
test [sampled], NDCG@5: 0.2546, HR@5: 0.2703, NDCG@10: 0.2932, HR@10: 0.3936, MRR: 0.3004
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=41, loss=0.0760
epoch=42, loss=0.0757
epoch=43, loss=0.0759
epoch=44, loss=0.0737
epoch=45, loss=0.0745
valid [full], NDCG@5: 0.7380, HR@5: 0.9083, NDCG@10: 0.7581, HR@10: 0.9749, MRR: 0.6915
valid [sampled], NDCG@5: 0.5634, HR@5: 0.5774, NDCG@10: 0.5954, HR@10: 0.6791, MRR: 0.5871
test [full], NDCG@5: 0.8295, HR@5: 0.9982, NDCG@10: 0.8301, HR@10: 1.0000, MRR: 0.7720
test [sampled], NDCG@5: 0.3441, HR@5: 0.3621, NDCG@10: 0.3960, HR@10: 0.5277, MRR: 0.3881
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=46, loss=0.0734
epoch=47, loss=0.0749
epoch=48, loss=0.0741
epoch=49, loss=0.0727
epoch=50, loss=0.0753
valid [full], NDCG@5: 0.7290, HR@5: 0.9062, NDCG@10: 0.7491, HR@10: 0.9721, MRR: 0.6810
valid [sampled], NDCG@5: 0.5553, HR@5: 0.5669, NDCG@10: 0.5827, HR@10: 0.6540, MRR: 0.5787
test [full], NDCG@5: 0.8240, HR@5: 0.9993, NDCG@10: 0.8242, HR@10: 0.9999, MRR: 0.7639
test [sampled], NDCG@5: 0.3279, HR@5: 0.3547, NDCG@10: 0.3859, HR@10: 0.5388, MRR: 0.3708
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s2024/sasrec_last.pth

### timeaware_conti_refine_ml50_do035_s7

In [14]:
!python src/train_sasrec.py \
  --run_name timeaware_conti_refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7
epoch=1, loss=0.6094
epoch=2, loss=0.2957
epoch=3, loss=0.2156
epoch=4, loss=0.1749
epoch=5, loss=0.1504
valid [full], NDCG@5: 0.6836, HR@5: 0.8441, NDCG@10: 0.7274, HR@10: 0.9780, MRR: 0.6526
valid [sampled], NDCG@5: 0.5638, HR@5: 0.5646, NDCG@10: 0.5699, HR@10: 0.5842, MRR: 0.5823
test [full], NDCG@5: 0.6657, HR@5: 0.8923, NDCG@10: 0.6890, HR@10: 0.9626, MRR: 0.6041
test [sampled], NDCG@5: 0.2493, HR@5: 0.2523, NDCG@10: 0.2738, HR@10: 0.3321, MRR: 0.2932
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1306
epoch=7, loss=0.1183
epoch=8, loss=0.1112
epoch=9, loss=0.1069
epoch=10, loss=0.1011
valid [full], NDCG@5: 0.6872, HR@5: 0.8381, NDCG@10: 0.7175, HR@10: 0.9342, MRR: 0.6565
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5655, NDCG@10: 0.5703, HR@10: 0.6017, MRR: 0.5758
test [full], NDCG@5: 0.7653, HR@5: 0.9997, NDCG@10: 0.7654, HR@10: 1.0000, MRR: 0.6846
test [sampled], NDCG@5: 0.1848, HR@5: 0.1972, NDCG@10: 0.2594, HR@10: 0.4376, MRR: 0.2468
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0985
epoch=12, loss=0.0958
epoch=13, loss=0.0933
epoch=14, loss=0.0899
epoch=15, loss=0.0898
valid [full], NDCG@5: 0.6911, HR@5: 0.8402, NDCG@10: 0.7198, HR@10: 0.9323, MRR: 0.6591
valid [sampled], NDCG@5: 0.5565, HR@5: 0.5651, NDCG@10: 0.5760, HR@10: 0.6267, MRR: 0.5759
test [full], NDCG@5: 0.7767, HR@5: 0.9999, NDCG@10: 0.7768, HR@10: 1.0000, MRR: 0.6989
test [sampled], NDCG@5: 0.1399, HR@5: 0.1539, NDCG@10: 0.2244, HR@10: 0.4260, MRR: 0.2076
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0889
epoch=17, loss=0.0859
epoch=18, loss=0.0841
epoch=19, loss=0.0842
epoch=20, loss=0.0833
valid [full], NDCG@5: 0.6845, HR@5: 0.8347, NDCG@10: 0.7153, HR@10: 0.9330, MRR: 0.6527
valid [sampled], NDCG@5: 0.5413, HR@5: 0.5493, NDCG@10: 0.5616, HR@10: 0.6138, MRR: 0.5626
test [full], NDCG@5: 0.8386, HR@5: 0.9999, NDCG@10: 0.8386, HR@10: 1.0000, MRR: 0.7827
test [sampled], NDCG@5: 0.2773, HR@5: 0.3100, NDCG@10: 0.3591, HR@10: 0.5699, MRR: 0.3283
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0838
epoch=22, loss=0.0802
epoch=23, loss=0.0820
epoch=24, loss=0.0818
epoch=25, loss=0.0785
valid [full], NDCG@5: 0.6937, HR@5: 0.8293, NDCG@10: 0.7266, HR@10: 0.9335, MRR: 0.6676
valid [sampled], NDCG@5: 0.5649, HR@5: 0.5779, NDCG@10: 0.5857, HR@10: 0.6431, MRR: 0.5823
test [full], NDCG@5: 0.8960, HR@5: 0.9997, NDCG@10: 0.8961, HR@10: 1.0000, MRR: 0.8605
test [sampled], NDCG@5: 0.2712, HR@5: 0.3599, NDCG@10: 0.3516, HR@10: 0.6074, MRR: 0.3009
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0799
epoch=27, loss=0.0788
epoch=28, loss=0.0789
epoch=29, loss=0.0780
epoch=30, loss=0.0761
valid [full], NDCG@5: 0.6920, HR@5: 0.8447, NDCG@10: 0.7208, HR@10: 0.9377, MRR: 0.6585
valid [sampled], NDCG@5: 0.5334, HR@5: 0.5376, NDCG@10: 0.5533, HR@10: 0.6014, MRR: 0.5569
test [full], NDCG@5: 0.9003, HR@5: 0.9996, NDCG@10: 0.9005, HR@10: 1.0000, MRR: 0.8672
test [sampled], NDCG@5: 0.4106, HR@5: 0.4751, NDCG@10: 0.4648, HR@10: 0.6424, MRR: 0.4341
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0790
epoch=32, loss=0.0768
epoch=33, loss=0.0765
epoch=34, loss=0.0755
epoch=35, loss=0.0774
valid [full], NDCG@5: 0.6784, HR@5: 0.8067, NDCG@10: 0.7138, HR@10: 0.9196, MRR: 0.6564
valid [sampled], NDCG@5: 0.5535, HR@5: 0.5674, NDCG@10: 0.5752, HR@10: 0.6350, MRR: 0.5704
test [full], NDCG@5: 0.9085, HR@5: 0.9996, NDCG@10: 0.9086, HR@10: 1.0000, MRR: 0.8776
test [sampled], NDCG@5: 0.4029, HR@5: 0.4749, NDCG@10: 0.4654, HR@10: 0.6675, MRR: 0.4258
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0756
epoch=37, loss=0.0763
epoch=38, loss=0.0764
epoch=39, loss=0.0765
epoch=40, loss=0.0761
valid [full], NDCG@5: 0.7051, HR@5: 0.8538, NDCG@10: 0.7307, HR@10: 0.9368, MRR: 0.6708
valid [sampled], NDCG@5: 0.5397, HR@5: 0.5509, NDCG@10: 0.5707, HR@10: 0.6498, MRR: 0.5633
test [full], NDCG@5: 0.9273, HR@5: 0.9997, NDCG@10: 0.9274, HR@10: 1.0000, MRR: 0.9029
test [sampled], NDCG@5: 0.4433, HR@5: 0.5016, NDCG@10: 0.4985, HR@10: 0.6712, MRR: 0.4683
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=41, loss=0.0782
epoch=42, loss=0.0745
epoch=43, loss=0.0755
epoch=44, loss=0.0742
epoch=45, loss=0.0747
valid [full], NDCG@5: 0.7024, HR@5: 0.8279, NDCG@10: 0.7361, HR@10: 0.9357, MRR: 0.6786
valid [sampled], NDCG@5: 0.5632, HR@5: 0.5780, NDCG@10: 0.5914, HR@10: 0.6666, MRR: 0.5825
test [full], NDCG@5: 0.9269, HR@5: 0.9999, NDCG@10: 0.9270, HR@10: 1.0000, MRR: 0.9020
test [sampled], NDCG@5: 0.4470, HR@5: 0.5152, NDCG@10: 0.5030, HR@10: 0.6869, MRR: 0.4679
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=46, loss=0.0743
epoch=47, loss=0.0738
epoch=48, loss=0.0731
epoch=49, loss=0.0737
epoch=50, loss=0.0734
valid [full], NDCG@5: 0.7094, HR@5: 0.8490, NDCG@10: 0.7429, HR@10: 0.9580, MRR: 0.6793
valid [sampled], NDCG@5: 0.5652, HR@5: 0.5803, NDCG@10: 0.5951, HR@10: 0.6747, MRR: 0.5854
test [full], NDCG@5: 0.9194, HR@5: 0.9997, NDCG@10: 0.9195, HR@10: 1.0000, MRR: 0.8922
test [sampled], NDCG@5: 0.3898, HR@5: 0.4588, NDCG@10: 0.4501, HR@10: 0.6444, MRR: 0.4144
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg10/timeaware_conti_refine_ml50_do035_s7/sasrec_last.pth

## Train continuous time-aware runs for `NDCG@5`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_conti_refine_ml50_do035_s42

In [15]:
!python src/train_sasrec.py \
  --run_name timeaware_conti_refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42
epoch=1, loss=0.6162
epoch=2, loss=0.2829
epoch=3, loss=0.2114
epoch=4, loss=0.1745
epoch=5, loss=0.1501
valid [full], NDCG@5: 0.6166, HR@5: 0.7019, NDCG@10: 0.6822, HR@10: 0.9171, MRR: 0.6211
valid [sampled], NDCG@5: 0.5460, HR@5: 0.5482, NDCG@10: 0.5555, HR@10: 0.5788, MRR: 0.5611
test [full], NDCG@5: 0.6189, HR@5: 0.7512, NDCG@10: 0.6578, HR@10: 0.8828, MRR: 0.5960
test [sampled], NDCG@5: 0.2139, HR@5: 0.2196, NDCG@10: 0.2613, HR@10: 0.3728, MRR: 0.2602
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1328
epoch=7, loss=0.1223
epoch=8, loss=0.1112
epoch=9, loss=0.1060
epoch=10, loss=0.1033
valid [full], NDCG@5: 0.6553, HR@5: 0.7701, NDCG@10: 0.7187, HR@10: 0.9666, MRR: 0.6472
valid [sampled], NDCG@5: 0.5624, HR@5: 0.5768, NDCG@10: 0.5757, HR@10: 0.6175, MRR: 0.5760
test [full], NDCG@5: 0.7106, HR@5: 0.9549, NDCG@10: 0.7255, HR@10: 1.0000, MRR: 0.6330
test [sampled], NDCG@5: 0.1592, HR@5: 0.1753, NDCG@10: 0.2238, HR@10: 0.3829, MRR: 0.2172
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=0.0997
epoch=12, loss=0.0967
epoch=13, loss=0.0932
epoch=14, loss=0.0923
epoch=15, loss=0.0913
valid [full], NDCG@5: 0.6956, HR@5: 0.8471, NDCG@10: 0.7345, HR@10: 0.9726, MRR: 0.6640
valid [sampled], NDCG@5: 0.5710, HR@5: 0.5844, NDCG@10: 0.5905, HR@10: 0.6453, MRR: 0.5879
test [full], NDCG@5: 0.6697, HR@5: 0.9881, NDCG@10: 0.6740, HR@10: 1.0000, MRR: 0.5635
test [sampled], NDCG@5: 0.0990, HR@5: 0.1157, NDCG@10: 0.1577, HR@10: 0.3035, MRR: 0.1586
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0883
epoch=17, loss=0.0852
epoch=18, loss=0.0851
epoch=19, loss=0.0846
epoch=20, loss=0.0843
valid [full], NDCG@5: 0.6691, HR@5: 0.7910, NDCG@10: 0.7287, HR@10: 0.9721, MRR: 0.6575
valid [sampled], NDCG@5: 0.5608, HR@5: 0.5694, NDCG@10: 0.5738, HR@10: 0.6099, MRR: 0.5775
test [full], NDCG@5: 0.6739, HR@5: 0.9785, NDCG@10: 0.6814, HR@10: 1.0000, MRR: 0.5745
test [sampled], NDCG@5: 0.0862, HR@5: 0.0927, NDCG@10: 0.1363, HR@10: 0.2542, MRR: 0.1495
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0813
epoch=22, loss=0.0819
epoch=23, loss=0.0815
epoch=24, loss=0.0796
epoch=25, loss=0.0802
valid [full], NDCG@5: 0.6845, HR@5: 0.8105, NDCG@10: 0.7357, HR@10: 0.9698, MRR: 0.6669
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5684, NDCG@10: 0.5812, HR@10: 0.6400, MRR: 0.5778
test [full], NDCG@5: 0.6660, HR@5: 0.9835, NDCG@10: 0.6719, HR@10: 1.0000, MRR: 0.5613
test [sampled], NDCG@5: 0.0627, HR@5: 0.0707, NDCG@10: 0.1155, HR@10: 0.2414, MRR: 0.1276
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0784
epoch=27, loss=0.0810
epoch=28, loss=0.0788
epoch=29, loss=0.0800
epoch=30, loss=0.0786
valid [full], NDCG@5: 0.6931, HR@5: 0.8323, NDCG@10: 0.7304, HR@10: 0.9492, MRR: 0.6675
valid [sampled], NDCG@5: 0.5616, HR@5: 0.5672, NDCG@10: 0.5773, HR@10: 0.6166, MRR: 0.5813
test [full], NDCG@5: 0.6945, HR@5: 0.9996, NDCG@10: 0.6946, HR@10: 1.0000, MRR: 0.5914
test [sampled], NDCG@5: 0.0757, HR@5: 0.0893, NDCG@10: 0.1351, HR@10: 0.2807, MRR: 0.1395
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0785
epoch=32, loss=0.0771
epoch=33, loss=0.0783
epoch=34, loss=0.0769
epoch=35, loss=0.0766
valid [full], NDCG@5: 0.6910, HR@5: 0.8467, NDCG@10: 0.7237, HR@10: 0.9508, MRR: 0.6578
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5651, NDCG@10: 0.5756, HR@10: 0.6218, MRR: 0.5775
test [full], NDCG@5: 0.7942, HR@5: 0.9986, NDCG@10: 0.7947, HR@10: 1.0000, MRR: 0.7266
test [sampled], NDCG@5: 0.1607, HR@5: 0.2301, NDCG@10: 0.2338, HR@10: 0.4570, MRR: 0.1996
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0762
epoch=37, loss=0.0754
epoch=38, loss=0.0748
epoch=39, loss=0.0760
epoch=40, loss=0.0765
valid [full], NDCG@5: 0.6894, HR@5: 0.8352, NDCG@10: 0.7259, HR@10: 0.9505, MRR: 0.6611
valid [sampled], NDCG@5: 0.5647, HR@5: 0.5717, NDCG@10: 0.5826, HR@10: 0.6282, MRR: 0.5838
test [full], NDCG@5: 0.7080, HR@5: 0.9985, NDCG@10: 0.7085, HR@10: 1.0000, MRR: 0.6114
test [sampled], NDCG@5: 0.1507, HR@5: 0.1617, NDCG@10: 0.1937, HR@10: 0.3001, MRR: 0.2057
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0756
epoch=42, loss=0.0765
epoch=43, loss=0.0774
epoch=44, loss=0.0750
epoch=45, loss=0.0753
valid [full], NDCG@5: 0.6900, HR@5: 0.8518, NDCG@10: 0.7285, HR@10: 0.9752, MRR: 0.6559
valid [sampled], NDCG@5: 0.5619, HR@5: 0.5678, NDCG@10: 0.5746, HR@10: 0.6080, MRR: 0.5794
test [full], NDCG@5: 0.8245, HR@5: 0.9984, NDCG@10: 0.8251, HR@10: 1.0000, MRR: 0.7679
test [sampled], NDCG@5: 0.3122, HR@5: 0.3803, NDCG@10: 0.3692, HR@10: 0.5543, MRR: 0.3389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0734
epoch=47, loss=0.0734
epoch=48, loss=0.0734
epoch=49, loss=0.0735
epoch=50, loss=0.0743
valid [full], NDCG@5: 0.6775, HR@5: 0.8058, NDCG@10: 0.7242, HR@10: 0.9490, MRR: 0.6600
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5662, NDCG@10: 0.5728, HR@10: 0.6109, MRR: 0.5755
test [full], NDCG@5: 0.8429, HR@5: 0.9967, NDCG@10: 0.8441, HR@10: 1.0000, MRR: 0.7930
test [sampled], NDCG@5: 0.2609, HR@5: 0.3285, NDCG@10: 0.3212, HR@10: 0.5145, MRR: 0.2920
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s42/sasrec_last.pth

### timeaware_conti_refine_ml50_do035_s2024

In [16]:
!python src/train_sasrec.py \
  --run_name timeaware_conti_refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024
epoch=1, loss=0.6394
epoch=2, loss=0.2888
epoch=3, loss=0.2095
epoch=4, loss=0.1695
epoch=5, loss=0.1449
valid [full], NDCG@5: 0.6595, HR@5: 0.7914, NDCG@10: 0.7272, HR@10: 0.9930, MRR: 0.6474
valid [sampled], NDCG@5: 0.5548, HR@5: 0.5619, NDCG@10: 0.5669, HR@10: 0.6003, MRR: 0.5715
test [full], NDCG@5: 0.7886, HR@5: 0.9749, NDCG@10: 0.7974, HR@10: 1.0000, MRR: 0.7327
test [sampled], NDCG@5: 0.2162, HR@5: 0.2785, NDCG@10: 0.2735, HR@10: 0.4546, MRR: 0.2488
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1255
epoch=7, loss=0.1166
epoch=8, loss=0.1101
epoch=9, loss=0.1026
epoch=10, loss=0.1004
valid [full], NDCG@5: 0.6895, HR@5: 0.8599, NDCG@10: 0.7243, HR@10: 0.9702, MRR: 0.6521
valid [sampled], NDCG@5: 0.5529, HR@5: 0.5615, NDCG@10: 0.5649, HR@10: 0.5987, MRR: 0.5696
test [full], NDCG@5: 0.8230, HR@5: 0.9993, NDCG@10: 0.8233, HR@10: 1.0000, MRR: 0.7645
test [sampled], NDCG@5: 0.2178, HR@5: 0.2872, NDCG@10: 0.2856, HR@10: 0.4985, MRR: 0.2535
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=11, loss=0.0979
epoch=12, loss=0.0926
epoch=13, loss=0.0908
epoch=14, loss=0.0902
epoch=15, loss=0.0904
valid [full], NDCG@5: 0.6851, HR@5: 0.8452, NDCG@10: 0.7252, HR@10: 0.9702, MRR: 0.6533
valid [sampled], NDCG@5: 0.5646, HR@5: 0.5757, NDCG@10: 0.5757, HR@10: 0.6096, MRR: 0.5797
test [full], NDCG@5: 0.8438, HR@5: 0.9817, NDCG@10: 0.8503, HR@10: 1.0000, MRR: 0.8002
test [sampled], NDCG@5: 0.1500, HR@5: 0.2227, NDCG@10: 0.2461, HR@10: 0.5230, MRR: 0.1953
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0864
epoch=17, loss=0.0857
epoch=18, loss=0.0865
epoch=19, loss=0.0846
epoch=20, loss=0.0854
valid [full], NDCG@5: 0.6669, HR@5: 0.7968, NDCG@10: 0.7250, HR@10: 0.9716, MRR: 0.6528
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5627, NDCG@10: 0.5689, HR@10: 0.6087, MRR: 0.5714
test [full], NDCG@5: 0.8035, HR@5: 0.9641, NDCG@10: 0.8163, HR@10: 1.0000, MRR: 0.7546
test [sampled], NDCG@5: 0.2526, HR@5: 0.2935, NDCG@10: 0.3239, HR@10: 0.5179, MRR: 0.2976
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0830
epoch=22, loss=0.0812
epoch=23, loss=0.0819
epoch=24, loss=0.0827
epoch=25, loss=0.0816
valid [full], NDCG@5: 0.7106, HR@5: 0.8934, NDCG@10: 0.7344, HR@10: 0.9703, MRR: 0.6630
valid [sampled], NDCG@5: 0.5410, HR@5: 0.5560, NDCG@10: 0.5597, HR@10: 0.6143, MRR: 0.5606
test [full], NDCG@5: 0.8060, HR@5: 0.9982, NDCG@10: 0.8065, HR@10: 1.0000, MRR: 0.7399
test [sampled], NDCG@5: 0.1146, HR@5: 0.1626, NDCG@10: 0.2112, HR@10: 0.4677, MRR: 0.1722
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=26, loss=0.0786
epoch=27, loss=0.0786
epoch=28, loss=0.0790
epoch=29, loss=0.0816
epoch=30, loss=0.0776
valid [full], NDCG@5: 0.7215, HR@5: 0.9023, NDCG@10: 0.7421, HR@10: 0.9699, MRR: 0.6734
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5713, NDCG@10: 0.5775, HR@10: 0.6294, MRR: 0.5781
test [full], NDCG@5: 0.7667, HR@5: 0.9938, NDCG@10: 0.7688, HR@10: 1.0000, MRR: 0.6909
test [sampled], NDCG@5: 0.2057, HR@5: 0.2309, NDCG@10: 0.2650, HR@10: 0.4196, MRR: 0.2559
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=31, loss=0.0781
epoch=32, loss=0.0780
epoch=33, loss=0.0762
epoch=34, loss=0.0779
epoch=35, loss=0.0761
valid [full], NDCG@5: 0.7306, HR@5: 0.9051, NDCG@10: 0.7503, HR@10: 0.9704, MRR: 0.6827
valid [sampled], NDCG@5: 0.5499, HR@5: 0.5656, NDCG@10: 0.5821, HR@10: 0.6675, MRR: 0.5739
test [full], NDCG@5: 0.7779, HR@5: 0.9991, NDCG@10: 0.7782, HR@10: 1.0000, MRR: 0.7034
test [sampled], NDCG@5: 0.2733, HR@5: 0.2914, NDCG@10: 0.3127, HR@10: 0.4171, MRR: 0.3188
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=36, loss=0.0770
epoch=37, loss=0.0758
epoch=38, loss=0.0751
epoch=39, loss=0.0771
epoch=40, loss=0.0750
valid [full], NDCG@5: 0.7321, HR@5: 0.9048, NDCG@10: 0.7518, HR@10: 0.9694, MRR: 0.6857
valid [sampled], NDCG@5: 0.5625, HR@5: 0.5780, NDCG@10: 0.5914, HR@10: 0.6691, MRR: 0.5841
test [full], NDCG@5: 0.7463, HR@5: 0.9954, NDCG@10: 0.7479, HR@10: 0.9999, MRR: 0.6643
test [sampled], NDCG@5: 0.2546, HR@5: 0.2703, NDCG@10: 0.2932, HR@10: 0.3936, MRR: 0.3004
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=41, loss=0.0760
epoch=42, loss=0.0757
epoch=43, loss=0.0759
epoch=44, loss=0.0737
epoch=45, loss=0.0745
valid [full], NDCG@5: 0.7380, HR@5: 0.9083, NDCG@10: 0.7581, HR@10: 0.9749, MRR: 0.6915
valid [sampled], NDCG@5: 0.5634, HR@5: 0.5774, NDCG@10: 0.5954, HR@10: 0.6791, MRR: 0.5871
test [full], NDCG@5: 0.8295, HR@5: 0.9982, NDCG@10: 0.8301, HR@10: 1.0000, MRR: 0.7720
test [sampled], NDCG@5: 0.3441, HR@5: 0.3621, NDCG@10: 0.3960, HR@10: 0.5277, MRR: 0.3881
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=46, loss=0.0734
epoch=47, loss=0.0749
epoch=48, loss=0.0741
epoch=49, loss=0.0727
epoch=50, loss=0.0753
valid [full], NDCG@5: 0.7290, HR@5: 0.9062, NDCG@10: 0.7491, HR@10: 0.9721, MRR: 0.6810
valid [sampled], NDCG@5: 0.5553, HR@5: 0.5669, NDCG@10: 0.5827, HR@10: 0.6540, MRR: 0.5787
test [full], NDCG@5: 0.8240, HR@5: 0.9993, NDCG@10: 0.8242, HR@10: 0.9999, MRR: 0.7639
test [sampled], NDCG@5: 0.3279, HR@5: 0.3547, NDCG@10: 0.3859, HR@10: 0.5388, MRR: 0.3708
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s2024/sasrec_last.pth

### timeaware_conti_refine_ml50_do035_s7

In [17]:
!python src/train_sasrec.py \
  --run_name timeaware_conti_refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7
epoch=1, loss=0.6094
epoch=2, loss=0.2957
epoch=3, loss=0.2156
epoch=4, loss=0.1749
epoch=5, loss=0.1504
valid [full], NDCG@5: 0.6836, HR@5: 0.8441, NDCG@10: 0.7274, HR@10: 0.9780, MRR: 0.6526
valid [sampled], NDCG@5: 0.5638, HR@5: 0.5646, NDCG@10: 0.5699, HR@10: 0.5842, MRR: 0.5823
test [full], NDCG@5: 0.6657, HR@5: 0.8923, NDCG@10: 0.6890, HR@10: 0.9626, MRR: 0.6041
test [sampled], NDCG@5: 0.2493, HR@5: 0.2523, NDCG@10: 0.2738, HR@10: 0.3321, MRR: 0.2932
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1306
epoch=7, loss=0.1183
epoch=8, loss=0.1112
epoch=9, loss=0.1069
epoch=10, loss=0.1011
valid [full], NDCG@5: 0.6872, HR@5: 0.8381, NDCG@10: 0.7175, HR@10: 0.9342, MRR: 0.6565
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5655, NDCG@10: 0.5703, HR@10: 0.6017, MRR: 0.5758
test [full], NDCG@5: 0.7653, HR@5: 0.9997, NDCG@10: 0.7654, HR@10: 1.0000, MRR: 0.6846
test [sampled], NDCG@5: 0.1848, HR@5: 0.1972, NDCG@10: 0.2594, HR@10: 0.4376, MRR: 0.2468
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=0.0985
epoch=12, loss=0.0958
epoch=13, loss=0.0933
epoch=14, loss=0.0899
epoch=15, loss=0.0898
valid [full], NDCG@5: 0.6911, HR@5: 0.8402, NDCG@10: 0.7198, HR@10: 0.9323, MRR: 0.6591
valid [sampled], NDCG@5: 0.5565, HR@5: 0.5651, NDCG@10: 0.5760, HR@10: 0.6267, MRR: 0.5759
test [full], NDCG@5: 0.7767, HR@5: 0.9999, NDCG@10: 0.7768, HR@10: 1.0000, MRR: 0.6989
test [sampled], NDCG@5: 0.1399, HR@5: 0.1539, NDCG@10: 0.2244, HR@10: 0.4260, MRR: 0.2076
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=0.0889
epoch=17, loss=0.0859
epoch=18, loss=0.0841
epoch=19, loss=0.0842
epoch=20, loss=0.0833
valid [full], NDCG@5: 0.6845, HR@5: 0.8347, NDCG@10: 0.7153, HR@10: 0.9330, MRR: 0.6527
valid [sampled], NDCG@5: 0.5413, HR@5: 0.5493, NDCG@10: 0.5616, HR@10: 0.6138, MRR: 0.5626
test [full], NDCG@5: 0.8386, HR@5: 0.9999, NDCG@10: 0.8386, HR@10: 1.0000, MRR: 0.7827
test [sampled], NDCG@5: 0.2773, HR@5: 0.3100, NDCG@10: 0.3591, HR@10: 0.5699, MRR: 0.3283
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0838
epoch=22, loss=0.0802
epoch=23, loss=0.0820
epoch=24, loss=0.0818
epoch=25, loss=0.0785
valid [full], NDCG@5: 0.6937, HR@5: 0.8293, NDCG@10: 0.7266, HR@10: 0.9335, MRR: 0.6676
valid [sampled], NDCG@5: 0.5649, HR@5: 0.5779, NDCG@10: 0.5857, HR@10: 0.6431, MRR: 0.5823
test [full], NDCG@5: 0.8960, HR@5: 0.9997, NDCG@10: 0.8961, HR@10: 1.0000, MRR: 0.8605
test [sampled], NDCG@5: 0.2712, HR@5: 0.3599, NDCG@10: 0.3516, HR@10: 0.6074, MRR: 0.3009
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=26, loss=0.0799
epoch=27, loss=0.0788
epoch=28, loss=0.0789
epoch=29, loss=0.0780
epoch=30, loss=0.0761
valid [full], NDCG@5: 0.6920, HR@5: 0.8447, NDCG@10: 0.7208, HR@10: 0.9377, MRR: 0.6585
valid [sampled], NDCG@5: 0.5334, HR@5: 0.5376, NDCG@10: 0.5533, HR@10: 0.6014, MRR: 0.5569
test [full], NDCG@5: 0.9003, HR@5: 0.9996, NDCG@10: 0.9005, HR@10: 1.0000, MRR: 0.8672
test [sampled], NDCG@5: 0.4106, HR@5: 0.4751, NDCG@10: 0.4648, HR@10: 0.6424, MRR: 0.4341
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0790
epoch=32, loss=0.0768
epoch=33, loss=0.0765
epoch=34, loss=0.0755
epoch=35, loss=0.0774
valid [full], NDCG@5: 0.6784, HR@5: 0.8067, NDCG@10: 0.7138, HR@10: 0.9196, MRR: 0.6564
valid [sampled], NDCG@5: 0.5535, HR@5: 0.5674, NDCG@10: 0.5752, HR@10: 0.6350, MRR: 0.5704
test [full], NDCG@5: 0.9085, HR@5: 0.9996, NDCG@10: 0.9086, HR@10: 1.0000, MRR: 0.8776
test [sampled], NDCG@5: 0.4029, HR@5: 0.4749, NDCG@10: 0.4654, HR@10: 0.6675, MRR: 0.4258
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0756
epoch=37, loss=0.0763
epoch=38, loss=0.0764
epoch=39, loss=0.0765
epoch=40, loss=0.0761
valid [full], NDCG@5: 0.7051, HR@5: 0.8538, NDCG@10: 0.7307, HR@10: 0.9368, MRR: 0.6708
valid [sampled], NDCG@5: 0.5397, HR@5: 0.5509, NDCG@10: 0.5707, HR@10: 0.6498, MRR: 0.5633
test [full], NDCG@5: 0.9273, HR@5: 0.9997, NDCG@10: 0.9274, HR@10: 1.0000, MRR: 0.9029
test [sampled], NDCG@5: 0.4433, HR@5: 0.5016, NDCG@10: 0.4985, HR@10: 0.6712, MRR: 0.4683
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=41, loss=0.0782
epoch=42, loss=0.0745
epoch=43, loss=0.0755
epoch=44, loss=0.0742
epoch=45, loss=0.0747
valid [full], NDCG@5: 0.7024, HR@5: 0.8279, NDCG@10: 0.7361, HR@10: 0.9357, MRR: 0.6786
valid [sampled], NDCG@5: 0.5632, HR@5: 0.5780, NDCG@10: 0.5914, HR@10: 0.6666, MRR: 0.5825
test [full], NDCG@5: 0.9269, HR@5: 0.9999, NDCG@10: 0.9270, HR@10: 1.0000, MRR: 0.9020
test [sampled], NDCG@5: 0.4470, HR@5: 0.5152, NDCG@10: 0.5030, HR@10: 0.6869, MRR: 0.4679
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0743
epoch=47, loss=0.0738
epoch=48, loss=0.0731
epoch=49, loss=0.0737
epoch=50, loss=0.0734
valid [full], NDCG@5: 0.7094, HR@5: 0.8490, NDCG@10: 0.7429, HR@10: 0.9580, MRR: 0.6793
valid [sampled], NDCG@5: 0.5652, HR@5: 0.5803, NDCG@10: 0.5951, HR@10: 0.6747, MRR: 0.5854
test [full], NDCG@5: 0.9194, HR@5: 0.9997, NDCG@10: 0.9195, HR@10: 1.0000, MRR: 0.8922
test [sampled], NDCG@5: 0.3898, HR@5: 0.4588, NDCG@10: 0.4501, HR@10: 0.6444, MRR: 0.4144
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_continuous_refine_ml50_do035_ndcg5/timeaware_conti_refine_ml50_do035_s7/sasrec_last.pth

## Rebuild result tables from run folders

This avoids schema issues and lets us combine existing baseline runs with new continuous runs safely.

In [6]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()

    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue

        summary_path = run_dir / "metrics_summary.json"
        config_path = run_dir / "config.json"
        if not summary_path.exists() or not config_path.exists():
            continue

        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        config = json.loads(config_path.read_text(encoding="utf-8"))

        row = {
            "run_name": summary.get("run_name"),
            "run_dir": str(run_dir),
            "completed_at": summary.get("completed_at"),
            "best_epoch": summary.get("best_epoch"),
            "checkpoint_best": summary.get("checkpoint_best"),
            "checkpoint_last": summary.get("checkpoint_last"),
            "metrics_history": summary.get("metrics_history"),
            "config_path": str(config_path),
            "metrics_summary": str(summary_path),
            "maxlen": config.get("maxlen"),
            "dropout_rate": config.get("dropout_rate"),
            "hidden_units": config.get("hidden_units"),
            "seed": config.get("seed"),
            "selection_metric": config.get("selection_metric"),
            "use_time_embedding": config.get("use_time_embedding", False),
            "time_encoding": config.get("time_encoding"),
            "time_feature_dim": config.get("time_feature_dim"),
        }

        best_valid = summary.get("best_valid", {})
        best_test = summary.get("best_test_at_best_valid", {})

        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)

        row.update({
            "best_valid_full_ndcg@10": pick(best_valid, "full", "ndcg@10"),
            "best_valid_full_hr@10": pick(best_valid, "full", "hr@10"),
            "best_valid_full_ndcg@5": pick(best_valid, "full", "ndcg@5"),
            "best_valid_full_hr@5": pick(best_valid, "full", "hr@5"),
            "best_valid_full_mrr": pick(best_valid, "full", "mrr"),

            "best_test_full_ndcg@10": pick(best_test, "full", "ndcg@10"),
            "best_test_full_hr@10": pick(best_test, "full", "hr@10"),
            "best_test_full_ndcg@5": pick(best_test, "full", "ndcg@5"),
            "best_test_full_hr@5": pick(best_test, "full", "hr@5"),
            "best_test_full_mrr": pick(best_test, "full", "mrr"),

            "best_valid_sampled_ndcg@10": pick(best_valid, "sampled", "ndcg@10"),
            "best_valid_sampled_hr@10": pick(best_valid, "sampled", "hr@10"),
            "best_valid_sampled_ndcg@5": pick(best_valid, "sampled", "ndcg@5"),
            "best_valid_sampled_hr@5": pick(best_valid, "sampled", "hr@5"),
            "best_valid_sampled_mrr": pick(best_valid, "sampled", "mrr"),

            "best_test_sampled_ndcg@10": pick(best_test, "sampled", "ndcg@10"),
            "best_test_sampled_hr@10": pick(best_test, "sampled", "hr@10"),
            "best_test_sampled_ndcg@5": pick(best_test, "sampled", "ndcg@5"),
            "best_test_sampled_hr@5": pick(best_test, "sampled", "hr@5"),
            "best_test_sampled_mrr": pick(best_test, "sampled", "mrr"),
        })

        rows.append(row)

    return pd.DataFrame(rows)

In [7]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## NDCG@10 comparison summary

In [8]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
timeaware_runs = [
    'timeaware_conti_refine_ml50_do035_s42',
    'timeaware_conti_refine_ml50_do035_s2024',
    'timeaware_conti_refine_ml50_do035_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['time_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['time_variant'] = 'continuous'

df_ndcg10 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'time_variant', 'use_time_embedding', 'time_encoding', 'time_feature_dim',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                                  run_name  seed time_variant  use_time_embedding time_encoding time_feature_dim  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0                     refine_ml50_do035_s7     7     baseline               False          None             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416                   1.0               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
1                    refine_ml50_do035_s42    42     baseline               False          None             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774                   1.0               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
2                  refine_ml50_do035_s2024  2024     baseline               False          None             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861                   1.0               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183
3     timeaware_conti_refine_ml50_do035_s7     7   continuous                True    continuous                2                 0.742856               0.957962                0.709444              0.849013             0.679322                0.919483                   1.0               0.919392             0.999729            0.892217                    0.595109                  0.674728                   0.565226                 0.580299                0.585420                   0.450081                 0.644405                  0.389823                0.458819               0.414366
4    timeaware_conti_refine_ml50_do035_s42    42   continuous                True    continuous                2                 0.735692               0.969771                0.684508              0.810492             0.666913                0.671893                   1.0               0.666020             0.983502            0.561349                    0.581198                  0.640022                   0.558554                 0.568380                0.577778                   0.115456                 0.241412                  0.062731                0.070733               0.127650
5  timeaware_conti_refine_ml50_do035_s2024  2024   continuous                True    continuous                2                 0.758122               0.974855                0.737981              0.908341             0.691520                0.830097                   1.0               0.829480             0.998243            0.772035                    0.595450                  0.679092                   0.563381                 0.577391                0.587073                   0.396034                 0.527692                  0.344150                0.362081               0.388127

In [9]:
summary_ndcg10 = df_ndcg10.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

             best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10      best_test_full_ndcg@5           best_test_full_hr@5          best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean  std                  mean       std                mean      std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
time_variant
baseline                    0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093                  1.0  0.0              0.818405  0.078916            0.911416  0.05528           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175
continuous                  0.745557  0.011456              0.967529  0.008667               0.710644  0.026757             0.855949  0.049292            0.679252  0.012303               0.807158  0.125379                  1.0  0.0              0.804964  0.128453            0.993825  0.00897           0.741867  0.167484                   0.590585  0.008132                 0.664614  0.021409                  0.562387  0.003445                0.575356  0.006215               0.583424  0.004959                  0.320524  0.179638                0.471170  0.207357                 0.265568  0.177140               0.297211  0.202012              0.310048  0.158505

Interpretation guide for NDCG@10:
- compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` first
- then check whether sampled metrics and MRR show a similar trend
- baseline is reused; only continuous time-aware runs are newly trained here

## NDCG@5 comparison summary

In [10]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
timeaware_runs = [
    'timeaware_conti_refine_ml50_do035_s42',
    'timeaware_conti_refine_ml50_do035_s2024',
    'timeaware_conti_refine_ml50_do035_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['time_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['time_variant'] = 'continuous'

df_ndcg5 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'time_variant', 'use_time_embedding', 'time_encoding', 'time_feature_dim',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                                  run_name  seed time_variant  use_time_embedding time_encoding time_feature_dim  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0                     refine_ml50_do035_s7     7     baseline               False          None             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416                   1.0               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
1                    refine_ml50_do035_s42    42     baseline               False          None             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774                   1.0               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
2                  refine_ml50_do035_s2024  2024     baseline               False          None             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861                   1.0               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183
3     timeaware_conti_refine_ml50_do035_s7     7   continuous                True    continuous                2                 0.742856               0.957962                0.709444              0.849013             0.679322                0.919483                   1.0               0.919392             0.999729            0.892217                    0.595109                  0.674728                   0.565226                 0.580299                0.585420                   0.450081                 0.644405                  0.389823                0.458819               0.414366
4    timeaware_conti_refine_ml50_do035_s42    42   continuous                True    continuous                2                 0.734529               0.972588                0.695617              0.847062             0.664040                0.673986                   1.0               0.669747             0.988100            0.563469                    0.590503                  0.645318                   0.570988                 0.584380                0.587901                   0.157738                 0.303520                  0.098997                0.115672               0.158573
5  timeaware_conti_refine_ml50_do035_s2024  2024   continuous                True    continuous                2                 0.758122               0.974855                0.737981              0.908341             0.691520                0.830097                   1.0               0.829480             0.998243            0.772035                    0.595450                  0.679092                   0.563381                 0.577391                0.587073                   0.396034                 0.527692                  0.344150                0.362081               0.388127

In [11]:
summary_ndcg5 = df_ndcg5.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

             best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10      best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean  std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
time_variant
baseline                    0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093                  1.0  0.0              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175
continuous                  0.745169  0.011965              0.968468  0.009169               0.714347  0.021603             0.868139  0.034830            0.678294  0.013769               0.807855  0.124251                  1.0  0.0              0.806206  0.126440            0.995357  0.006329           0.742574  0.166343                   0.593687  0.002763                 0.666380  0.018370                  0.566532  0.003968                0.580690  0.003511               0.586798  0.001263                  0.334618  0.155548                0.491872  0.173242                 0.277656  0.156400               0.312190  0.176930              0.320355  0.140721

Interpretation guide for NDCG@5:
- compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` first
- then check whether sampled metrics and MRR show a similar trend
- baseline is reused; only continuous time-aware runs are newly trained here