# SASRec Stage 3 Baseline Multi-Task BPI2012 Colab Train 02

This notebook is the Stage 3 follow-up version.

Main changes from `01`:
- reuse all available single-task baseline seeds (`42`, `2024`, `7`)
- compare multi-task runs with the same 3 seeds
- inspect mean/std instead of only `s42`
- show task metrics with the final metric names used in later experiments

Main comparison metric:
- `full ranking + NDCG@10`

In [ ]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.11.0+cu128
cuda available: True
gpu name: Tesla T4

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only_stage3_v2'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
MULTITASK_BASELINE_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('MULTITASK_BASELINE_OUTPUT_DIR:', MULTITASK_BASELINE_OUTPUT_DIR)
print('NOTEBOOK_DIR:', NOTEBOOK_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
MULTITASK_BASELINE_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2
NOTEBOOK_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/notebooks

In [ ]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$MULTITASK_BASELINE_OUTPUT_DIR"

In [ ]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [ ]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [ ]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.11.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.4)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

## Prepare Stage 3 processed dataset

This notebook regenerates the Stage 3 dataset into the versioned Drive folder
before training, so the run does not depend on any stale local processed files.

In [ ]:
%cd /content/time-aware-behavior-prediction
!python scripts/regenerate_stage3_processed_dataset.py --output-dir "$DATA_DIR" --backup-existing
!ls "$DATA_DIR"

/content/time-aware-behavior-prediction
[info] moved existing output to backup: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2__backup_20260601_071949
[ok] regenerated Stage 3 processed dataset at: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2
[ok] metadata written to: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2/stage3_dataset_metadata.json
{
  "timestamp": 0,
  "delta_prev_seconds": 0,
  "delta_start_seconds": 0,
  "delta_next_seconds": 0
}
events_complete_only_filtered.csv  sasrec_interactions.csv	 user_map.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   stage3_dataset_metadata.json

In [ ]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!rm -rf data/processed/bpi2012_complete_only_stage3_v2
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only_stage3_v2

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv	 user_map.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   stage3_dataset_metadata.json

## Verify Stage 3 processed file

Stage 3 next-time prediction uses the processed time-feature CSV.
This check confirms that `delta_next_seconds` already exists.

In [ ]:
import pandas as pd

time_features_path = 'data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv'
df = pd.read_csv(time_features_path)
required_cols = [
    'delta_prev_seconds',
    'delta_start_seconds',
    'delta_next_seconds',
]
missing = [c for c in required_cols if c not in df.columns]

if missing:
    raise ValueError(f'Missing required Stage 3 columns: {missing}')

print('Stage 3 processed file is ready.')
print(df.columns.tolist())
df[['user_id', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds']].head()

Stage 3 processed file is ready.
['case_id', 'activity', 'lifecycle', 'timestamp', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds', 'user_id', 'item_id']

,user_id,event_idx,delta_prev_seconds,delta_start_seconds,delta_next_seconds
0,1,0,0.000,0.000,0.334
1,1,1,0.334,0.334,53.026
2,1,2,53.026,53.360,39785.402
3,1,3,39785.402,39838.762,145.935
4,1,4,145.935,39984.697,-0.000

## Experiment design

Stage 3 baseline multi-task runs:

- backbone 1: `anchor_ml20`
- backbone 2: `refine_ml50_do035`
- multi-task outputs: `next activity + next time`
- time target: `delta_next_seconds`
- time target transform: `log1p`
- time loss: `huber`
- time loss weight: `1.0`
- best epoch criterion: `full_valid_ndcg@10`
- final comparison should use all 3 seeds when available: `42`, `2024`, `7`

## Check prerequisite baseline runs (all 3 seeds)

In [ ]:
from pathlib import Path

baseline_required_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

output_dir = Path(BASELINE_NDCG10_OUTPUT_DIR)
print('=' * 80)
print('Baseline NDCG@10 prerequisite runs')
for run_name in baseline_required_runs:
    run_dir = output_dir / run_name
    print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10 prerequisite runs
anchor_ml20_s42 EXISTS
anchor_ml20_s2024 EXISTS
anchor_ml20_s7 EXISTS
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS

## Check planned multi-task runs

In [ ]:
planned_multitask_runs = [
    'multitask_anchor_ml20_s42',
    'multitask_anchor_ml20_s2024',
    'multitask_anchor_ml20_s7',
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]

output_dir = Path(MULTITASK_BASELINE_OUTPUT_DIR)
print('=' * 80)
print('Stage 3 baseline multi-task runs')
for run_name in planned_multitask_runs:
    run_dir = output_dir / run_name
    print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Stage 3 baseline multi-task runs
multitask_anchor_ml20_s42 OK
multitask_anchor_ml20_s2024 OK
multitask_anchor_ml20_s7 OK
multitask_refine_ml50_do035_s42 OK
multitask_refine_ml50_do035_s2024 OK
multitask_refine_ml50_do035_s7 OK

## Train multi-task runs

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_anchor_ml20_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42
epoch=1, loss=2.5741
epoch=2, loss=1.5377
epoch=3, loss=1.4230
epoch=4, loss=1.3542
epoch=5, loss=1.3119
valid [task], Top5Acc: 0.4070, Top10Acc: 0.7690, Acc: 0.0551, MacroF1: 0.0988, TimeMAE: 70134.1216, TimeRMSE: 275756.8323, TimeMedAE: 904.5147
valid [full], NDCG@5: 0.6219, HR@5: 0.7527, NDCG@10: 0.6832, HR@10: 0.9487, MRR: 0.6093
valid [sampled], NDCG@5: 0.5208, HR@5: 0.5212, NDCG@10: 0.5236, HR@10: 0.5301, MRR: 0.5364
test [task], Top5Acc: 0.0436, Top10Acc: 0.5369, Acc: 0.0141, MacroF1: 0.0150, TimeMAE: 11858.8850, TimeRMSE: 80605.3214, TimeMedAE: 18.5728
test [full], NDCG@5: 0.5072, HR@5: 0.7868, NDCG@10: 0.5762, HR@10: 0.9944, MRR: 0.4478
test [sampled], NDCG@5: 0.1488, HR@5: 0.1493, NDCG@10: 0.1515, HR@10: 0.1580, MRR: 0.1815
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/sasrec_best.pth
epoch=6, loss=1.2729
epoch=7, loss=1.2403
epoch=8, loss=1.2250
epoch=9, loss=1.2155
epoch=10, loss=1.1885
valid [task], Top5Acc: 0.4303, Top10Acc: 0.7248, Acc: 0.0575, MacroF1: 0.1046, TimeMAE: 73701.8151, TimeRMSE: 280275.3285, TimeMedAE: 3465.5719
valid [full], NDCG@5: 0.6478, HR@5: 0.7135, NDCG@10: 0.7291, HR@10: 0.9714, MRR: 0.6615
valid [sampled], NDCG@5: 0.5920, HR@5: 0.5929, NDCG@10: 0.5959, HR@10: 0.6053, MRR: 0.6040
test [task], Top5Acc: 0.2828, Top10Acc: 0.5945, Acc: 0.0161, MacroF1: 0.0171, TimeMAE: 13193.6724, TimeRMSE: 76676.3756, TimeMedAE: 20.0621
test [full], NDCG@5: 0.6244, HR@5: 0.8872, NDCG@10: 0.6604, HR@10: 1.0000, MRR: 0.5482
test [sampled], NDCG@5: 0.1062, HR@5: 0.1097, NDCG@10: 0.1412, HR@10: 0.2219, MRR: 0.1584
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/sasrec_best.pth
epoch=11, loss=1.1827
epoch=12, loss=1.1828
epoch=13, loss=1.1683
epoch=14, loss=1.1783
epoch=15, loss=1.1617
valid [task], Top5Acc: 0.3939, Top10Acc: 0.7251, Acc: 0.0584, MacroF1: 0.0948, TimeMAE: 74681.4861, TimeRMSE: 282671.5775, TimeMedAE: 6105.0494
valid [full], NDCG@5: 0.6618, HR@5: 0.7868, NDCG@10: 0.7220, HR@10: 0.9727, MRR: 0.6491
valid [sampled], NDCG@5: 0.5549, HR@5: 0.5586, NDCG@10: 0.5646, HR@10: 0.5887, MRR: 0.5709
test [task], Top5Acc: 0.4401, Top10Acc: 0.6415, Acc: 0.0188, MacroF1: 0.0178, TimeMAE: 12688.1513, TimeRMSE: 73896.5111, TimeMedAE: 32.6938
test [full], NDCG@5: 0.7175, HR@5: 0.9216, NDCG@10: 0.7433, HR@10: 1.0000, MRR: 0.6574
test [sampled], NDCG@5: 0.1529, HR@5: 0.1700, NDCG@10: 0.1987, HR@10: 0.3159, MRR: 0.2044
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=1.1527
epoch=17, loss=1.1492
epoch=18, loss=1.1525
epoch=19, loss=1.1500
epoch=20, loss=1.1404
valid [task], Top5Acc: 0.4210, Top10Acc: 0.7065, Acc: 0.0556, MacroF1: 0.0432, TimeMAE: 77652.4830, TimeRMSE: 285126.7354, TimeMedAE: 3316.1731
valid [full], NDCG@5: 0.6766, HR@5: 0.7931, NDCG@10: 0.7327, HR@10: 0.9709, MRR: 0.6638
valid [sampled], NDCG@5: 0.5709, HR@5: 0.5745, NDCG@10: 0.5805, HR@10: 0.6051, MRR: 0.5864
test [task], Top5Acc: 0.4772, Top10Acc: 0.6319, Acc: 0.0158, MacroF1: 0.0104, TimeMAE: 13918.5694, TimeRMSE: 72962.4702, TimeMedAE: 63.6170
test [full], NDCG@5: 0.8299, HR@5: 0.9132, NDCG@10: 0.8585, HR@10: 1.0000, MRR: 0.8137
test [sampled], NDCG@5: 0.2138, HR@5: 0.2718, NDCG@10: 0.2893, HR@10: 0.5067, MRR: 0.2509
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/sasrec_best.pth
epoch=21, loss=1.1466
epoch=22, loss=1.1475
epoch=23, loss=1.1337
epoch=24, loss=1.1328
epoch=25, loss=1.1287
valid [task], Top5Acc: 0.3980, Top10Acc: 0.5785, Acc: 0.0558, MacroF1: 0.0383, TimeMAE: 75348.1270, TimeRMSE: 291189.7704, TimeMedAE: 1688.0121
valid [full], NDCG@5: 0.6790, HR@5: 0.8514, NDCG@10: 0.7167, HR@10: 0.9752, MRR: 0.6398
valid [sampled], NDCG@5: 0.5242, HR@5: 0.5280, NDCG@10: 0.5335, HR@10: 0.5573, MRR: 0.5427
test [task], Top5Acc: 0.4602, Top10Acc: 0.6201, Acc: 0.0118, MacroF1: 0.0072, TimeMAE: 12167.7174, TimeRMSE: 69444.5348, TimeMedAE: 8.6180
test [full], NDCG@5: 0.7525, HR@5: 0.9393, NDCG@10: 0.7727, HR@10: 1.0000, MRR: 0.6976
test [sampled], NDCG@5: 0.2010, HR@5: 0.2301, NDCG@10: 0.2554, HR@10: 0.4009, MRR: 0.2464
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1225
epoch=27, loss=1.1240
epoch=28, loss=1.1292
epoch=29, loss=1.1240
epoch=30, loss=1.1263
valid [task], Top5Acc: 0.4061, Top10Acc: 0.6746, Acc: 0.0541, MacroF1: 0.0619, TimeMAE: 74326.7404, TimeRMSE: 281978.2024, TimeMedAE: 7959.6644
valid [full], NDCG@5: 0.7062, HR@5: 0.8581, NDCG@10: 0.7432, HR@10: 0.9778, MRR: 0.6717
valid [sampled], NDCG@5: 0.5371, HR@5: 0.5446, NDCG@10: 0.5539, HR@10: 0.5974, MRR: 0.5582
test [task], Top5Acc: 0.4752, Top10Acc: 0.6689, Acc: 0.0150, MacroF1: 0.0131, TimeMAE: 14103.7886, TimeRMSE: 78650.5340, TimeMedAE: 97.5815
test [full], NDCG@5: 0.7871, HR@5: 0.9392, NDCG@10: 0.8075, HR@10: 1.0000, MRR: 0.7432
test [sampled], NDCG@5: 0.2479, HR@5: 0.2738, NDCG@10: 0.2993, HR@10: 0.4344, MRR: 0.2918
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/sasrec_best.pth
epoch=31, loss=1.1149
epoch=32, loss=1.1169
epoch=33, loss=1.1216
epoch=34, loss=1.1133
epoch=35, loss=1.1172
valid [task], Top5Acc: 0.3992, Top10Acc: 0.6076, Acc: 0.0540, MacroF1: 0.0318, TimeMAE: 73025.8546, TimeRMSE: 278828.3266, TimeMedAE: 1660.8126
valid [full], NDCG@5: 0.7027, HR@5: 0.8530, NDCG@10: 0.7316, HR@10: 0.9457, MRR: 0.6691
valid [sampled], NDCG@5: 0.5565, HR@5: 0.5616, NDCG@10: 0.5686, HR@10: 0.5998, MRR: 0.5751
test [task], Top5Acc: 0.4773, Top10Acc: 0.6419, Acc: 0.0122, MacroF1: 0.0075, TimeMAE: 13255.5619, TimeRMSE: 69489.2778, TimeMedAE: 23.3123
test [full], NDCG@5: 0.8756, HR@5: 0.9389, NDCG@10: 0.8962, HR@10: 1.0000, MRR: 0.8630
test [sampled], NDCG@5: 0.3102, HR@5: 0.3644, NDCG@10: 0.3817, HR@10: 0.5857, MRR: 0.3436
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1208
epoch=37, loss=1.1059
epoch=38, loss=1.1010
epoch=39, loss=1.1114
epoch=40, loss=1.1088
valid [task], Top5Acc: 0.4093, Top10Acc: 0.6196, Acc: 0.0518, MacroF1: 0.0546, TimeMAE: 68995.9157, TimeRMSE: 267980.6288, TimeMedAE: 1183.9539
valid [full], NDCG@5: 0.6961, HR@5: 0.8509, NDCG@10: 0.7353, HR@10: 0.9736, MRR: 0.6633
valid [sampled], NDCG@5: 0.5394, HR@5: 0.5438, NDCG@10: 0.5509, HR@10: 0.5797, MRR: 0.5593
test [task], Top5Acc: 0.5002, Top10Acc: 0.6246, Acc: 0.0902, MacroF1: 0.0409, TimeMAE: 12309.5408, TimeRMSE: 67332.7118, TimeMedAE: 84.2770
test [full], NDCG@5: 0.7848, HR@5: 0.9391, NDCG@10: 0.8054, HR@10: 1.0000, MRR: 0.7407
test [sampled], NDCG@5: 0.3512, HR@5: 0.3562, NDCG@10: 0.3763, HR@10: 0.4367, MRR: 0.3893
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.1107
epoch=42, loss=1.1120
epoch=43, loss=1.1158
epoch=44, loss=1.1178
epoch=45, loss=1.1137
valid [task], Top5Acc: 0.3687, Top10Acc: 0.6134, Acc: 0.0606, MacroF1: 0.0478, TimeMAE: 78307.6551, TimeRMSE: 282107.0360, TimeMedAE: 4092.2839
valid [full], NDCG@5: 0.7102, HR@5: 0.8525, NDCG@10: 0.7393, HR@10: 0.9451, MRR: 0.6790
valid [sampled], NDCG@5: 0.5567, HR@5: 0.5605, NDCG@10: 0.5689, HR@10: 0.5990, MRR: 0.5767
test [task], Top5Acc: 0.5067, Top10Acc: 0.6414, Acc: 0.1264, MacroF1: 0.0494, TimeMAE: 15111.4427, TimeRMSE: 73421.6453, TimeMedAE: 193.9738
test [full], NDCG@5: 0.8854, HR@5: 0.9447, NDCG@10: 0.9047, HR@10: 1.0000, MRR: 0.8743
test [sampled], NDCG@5: 0.3680, HR@5: 0.4141, NDCG@10: 0.4258, HR@10: 0.5934, MRR: 0.3972
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1042
epoch=47, loss=1.1046
epoch=48, loss=1.1006
epoch=49, loss=1.1077
epoch=50, loss=1.0978
valid [task], Top5Acc: 0.3934, Top10Acc: 0.6142, Acc: 0.0521, MacroF1: 0.0516, TimeMAE: 71862.8149, TimeRMSE: 279634.1011, TimeMedAE: 4491.2482
valid [full], NDCG@5: 0.7003, HR@5: 0.8600, NDCG@10: 0.7267, HR@10: 0.9450, MRR: 0.6618
valid [sampled], NDCG@5: 0.5293, HR@5: 0.5364, NDCG@10: 0.5466, HR@10: 0.5908, MRR: 0.5503
test [task], Top5Acc: 0.4707, Top10Acc: 0.6509, Acc: 0.0560, MacroF1: 0.0259, TimeMAE: 13106.4544, TimeRMSE: 68593.5753, TimeMedAE: 191.4039
test [full], NDCG@5: 0.8659, HR@5: 0.9454, NDCG@10: 0.8853, HR@10: 1.0000, MRR: 0.8480
test [sampled], NDCG@5: 0.2875, HR@5: 0.3449, NDCG@10: 0.3599, HR@10: 0.5695, MRR: 0.3209
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s42/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_anchor_ml20_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024
epoch=1, loss=2.8037
epoch=2, loss=1.5874
epoch=3, loss=1.4188
epoch=4, loss=1.3484
epoch=5, loss=1.3018
valid [task], Top5Acc: 0.4684, Top10Acc: 0.7286, Acc: 0.0876, MacroF1: 0.1517, TimeMAE: 76872.8673, TimeRMSE: 292023.3924, TimeMedAE: 1244.3507
valid [full], NDCG@5: 0.6227, HR@5: 0.7291, NDCG@10: 0.6933, HR@10: 0.9546, MRR: 0.6205
valid [sampled], NDCG@5: 0.5291, HR@5: 0.5297, NDCG@10: 0.5344, HR@10: 0.5465, MRR: 0.5452
test [task], Top5Acc: 0.0589, Top10Acc: 0.4974, Acc: 0.0362, MacroF1: 0.0326, TimeMAE: 12709.6705, TimeRMSE: 78704.8211, TimeMedAE: 8.9110
test [full], NDCG@5: 0.5350, HR@5: 0.7525, NDCG@10: 0.6127, HR@10: 1.0000, MRR: 0.4962
test [sampled], NDCG@5: 0.1460, HR@5: 0.1466, NDCG@10: 0.1535, HR@10: 0.1710, MRR: 0.1822
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=6, loss=1.2604
epoch=7, loss=1.2356
epoch=8, loss=1.2291
epoch=9, loss=1.2070
epoch=10, loss=1.2092
valid [task], Top5Acc: 0.4032, Top10Acc: 0.7132, Acc: 0.0828, MacroF1: 0.1186, TimeMAE: 69494.8155, TimeRMSE: 272967.3968, TimeMedAE: 1272.0646
valid [full], NDCG@5: 0.6301, HR@5: 0.7205, NDCG@10: 0.7058, HR@10: 0.9561, MRR: 0.6360
valid [sampled], NDCG@5: 0.5587, HR@5: 0.5602, NDCG@10: 0.5623, HR@10: 0.5714, MRR: 0.5720
test [task], Top5Acc: 0.2902, Top10Acc: 0.6625, Acc: 0.0321, MacroF1: 0.0271, TimeMAE: 12175.8547, TimeRMSE: 72101.5298, TimeMedAE: 80.6765
test [full], NDCG@5: 0.6708, HR@5: 0.9348, NDCG@10: 0.6930, HR@10: 1.0000, MRR: 0.5914
test [sampled], NDCG@5: 0.1230, HR@5: 0.1260, NDCG@10: 0.1564, HR@10: 0.2335, MRR: 0.1770
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=11, loss=1.1989
epoch=12, loss=1.1929
epoch=13, loss=1.1849
epoch=14, loss=1.1725
epoch=15, loss=1.1728
valid [task], Top5Acc: 0.4021, Top10Acc: 0.6374, Acc: 0.0877, MacroF1: 0.1583, TimeMAE: 70381.9273, TimeRMSE: 281743.4775, TimeMedAE: 1223.3948
valid [full], NDCG@5: 0.6306, HR@5: 0.7099, NDCG@10: 0.7097, HR@10: 0.9568, MRR: 0.6407
valid [sampled], NDCG@5: 0.5600, HR@5: 0.5625, NDCG@10: 0.5660, HR@10: 0.5814, MRR: 0.5736
test [task], Top5Acc: 0.1621, Top10Acc: 0.6651, Acc: 0.0309, MacroF1: 0.0283, TimeMAE: 11583.8596, TimeRMSE: 75551.5893, TimeMedAE: 56.2553
test [full], NDCG@5: 0.7281, HR@5: 0.9805, NDCG@10: 0.7350, HR@10: 1.0000, MRR: 0.6466
test [sampled], NDCG@5: 0.1897, HR@5: 0.1990, NDCG@10: 0.2193, HR@10: 0.2934, MRR: 0.2373
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=16, loss=1.1601
epoch=17, loss=1.1645
epoch=18, loss=1.1595
epoch=19, loss=1.1645
epoch=20, loss=1.1576
valid [task], Top5Acc: 0.4053, Top10Acc: 0.6973, Acc: 0.0826, MacroF1: 0.1244, TimeMAE: 71879.9276, TimeRMSE: 290850.2102, TimeMedAE: 1439.3201
valid [full], NDCG@5: 0.6443, HR@5: 0.7599, NDCG@10: 0.7061, HR@10: 0.9597, MRR: 0.6347
valid [sampled], NDCG@5: 0.5500, HR@5: 0.5519, NDCG@10: 0.5566, HR@10: 0.5730, MRR: 0.5649
test [task], Top5Acc: 0.3552, Top10Acc: 0.6382, Acc: 0.0236, MacroF1: 0.0255, TimeMAE: 12441.9258, TimeRMSE: 74362.7401, TimeMedAE: 33.5827
test [full], NDCG@5: 0.7123, HR@5: 0.9722, NDCG@10: 0.7212, HR@10: 1.0000, MRR: 0.6276
test [sampled], NDCG@5: 0.1695, HR@5: 0.1746, NDCG@10: 0.2084, HR@10: 0.2998, MRR: 0.2220
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.1534
epoch=22, loss=1.1493
epoch=23, loss=1.1487
epoch=24, loss=1.1552
epoch=25, loss=1.1490
valid [task], Top5Acc: 0.4037, Top10Acc: 0.5892, Acc: 0.0844, MacroF1: 0.1323, TimeMAE: 74418.3574, TimeRMSE: 284443.2809, TimeMedAE: 1781.1175
valid [full], NDCG@5: 0.6351, HR@5: 0.7515, NDCG@10: 0.7010, HR@10: 0.9582, MRR: 0.6277
valid [sampled], NDCG@5: 0.5263, HR@5: 0.5284, NDCG@10: 0.5360, HR@10: 0.5592, MRR: 0.5432
test [task], Top5Acc: 0.3835, Top10Acc: 0.6860, Acc: 0.0846, MacroF1: 0.0508, TimeMAE: 13719.9065, TimeRMSE: 75492.4511, TimeMedAE: 51.8257
test [full], NDCG@5: 0.7833, HR@5: 0.9936, NDCG@10: 0.7855, HR@10: 1.0000, MRR: 0.7114
test [sampled], NDCG@5: 0.2347, HR@5: 0.2415, NDCG@10: 0.2742, HR@10: 0.3679, MRR: 0.2861
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1417
epoch=27, loss=1.1401
epoch=28, loss=1.1432
epoch=29, loss=1.1498
epoch=30, loss=1.1261
valid [task], Top5Acc: 0.4041, Top10Acc: 0.6235, Acc: 0.0668, MacroF1: 0.0910, TimeMAE: 76198.0503, TimeRMSE: 292017.1139, TimeMedAE: 2921.8021
valid [full], NDCG@5: 0.6577, HR@5: 0.7674, NDCG@10: 0.7147, HR@10: 0.9476, MRR: 0.6493
valid [sampled], NDCG@5: 0.5606, HR@5: 0.5627, NDCG@10: 0.5671, HR@10: 0.5834, MRR: 0.5759
test [task], Top5Acc: 0.4595, Top10Acc: 0.6623, Acc: 0.0884, MacroF1: 0.0512, TimeMAE: 12966.4555, TimeRMSE: 74360.7240, TimeMedAE: 122.2183
test [full], NDCG@5: 0.7798, HR@5: 0.9969, NDCG@10: 0.7808, HR@10: 0.9999, MRR: 0.7062
test [sampled], NDCG@5: 0.2175, HR@5: 0.2271, NDCG@10: 0.2576, HR@10: 0.3552, MRR: 0.2684
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=31, loss=1.1474
epoch=32, loss=1.1221
epoch=33, loss=1.1427
epoch=34, loss=1.1320
epoch=35, loss=1.1379
valid [task], Top5Acc: 0.4067, Top10Acc: 0.6203, Acc: 0.0606, MacroF1: 0.0857, TimeMAE: 70992.1075, TimeRMSE: 286370.2710, TimeMedAE: 2412.1630
valid [full], NDCG@5: 0.6516, HR@5: 0.7821, NDCG@10: 0.7055, HR@10: 0.9468, MRR: 0.6359
valid [sampled], NDCG@5: 0.5237, HR@5: 0.5255, NDCG@10: 0.5335, HR@10: 0.5564, MRR: 0.5429
test [task], Top5Acc: 0.1991, Top10Acc: 0.6824, Acc: 0.0830, MacroF1: 0.0485, TimeMAE: 13232.1453, TimeRMSE: 80081.8093, TimeMedAE: 175.3983
test [full], NDCG@5: 0.7340, HR@5: 0.9627, NDCG@10: 0.7472, HR@10: 1.0000, MRR: 0.6634
test [sampled], NDCG@5: 0.2373, HR@5: 0.2443, NDCG@10: 0.2606, HR@10: 0.3190, MRR: 0.2819
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1302
epoch=37, loss=1.1325
epoch=38, loss=1.1316
epoch=39, loss=1.1218
epoch=40, loss=1.1235
valid [task], Top5Acc: 0.4025, Top10Acc: 0.6830, Acc: 0.0703, MacroF1: 0.0840, TimeMAE: 75091.4830, TimeRMSE: 295137.2195, TimeMedAE: 1279.7971
valid [full], NDCG@5: 0.6787, HR@5: 0.8083, NDCG@10: 0.7226, HR@10: 0.9456, MRR: 0.6588
valid [sampled], NDCG@5: 0.5627, HR@5: 0.5663, NDCG@10: 0.5709, HR@10: 0.5922, MRR: 0.5789
test [task], Top5Acc: 0.2438, Top10Acc: 0.6637, Acc: 0.1199, MacroF1: 0.0542, TimeMAE: 12525.3806, TimeRMSE: 72469.9648, TimeMedAE: 111.3361
test [full], NDCG@5: 0.7977, HR@5: 0.9954, NDCG@10: 0.7993, HR@10: 1.0000, MRR: 0.7328
test [sampled], NDCG@5: 0.2801, HR@5: 0.2973, NDCG@10: 0.3103, HR@10: 0.3923, MRR: 0.3208
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=41, loss=1.1176
epoch=42, loss=1.1246
epoch=43, loss=1.1330
epoch=44, loss=1.1205
epoch=45, loss=1.1197
valid [task], Top5Acc: 0.4046, Top10Acc: 0.5817, Acc: 0.0614, MacroF1: 0.0696, TimeMAE: 75666.0152, TimeRMSE: 287729.1512, TimeMedAE: 2415.7169
valid [full], NDCG@5: 0.6537, HR@5: 0.7647, NDCG@10: 0.7119, HR@10: 0.9462, MRR: 0.6457
valid [sampled], NDCG@5: 0.5520, HR@5: 0.5561, NDCG@10: 0.5623, HR@10: 0.5888, MRR: 0.5678
test [task], Top5Acc: 0.4723, Top10Acc: 0.6877, Acc: 0.0833, MacroF1: 0.0435, TimeMAE: 13056.2256, TimeRMSE: 73374.7544, TimeMedAE: 56.8899
test [full], NDCG@5: 0.7743, HR@5: 0.9904, NDCG@10: 0.7776, HR@10: 1.0000, MRR: 0.7009
test [sampled], NDCG@5: 0.2227, HR@5: 0.2314, NDCG@10: 0.2641, HR@10: 0.3642, MRR: 0.2746
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1162
epoch=47, loss=1.1118
epoch=48, loss=1.1181
epoch=49, loss=1.1080
epoch=50, loss=1.1118
valid [task], Top5Acc: 0.4002, Top10Acc: 0.6721, Acc: 0.0672, MacroF1: 0.0850, TimeMAE: 71988.7418, TimeRMSE: 287294.4375, TimeMedAE: 3264.9897
valid [full], NDCG@5: 0.6786, HR@5: 0.8354, NDCG@10: 0.7143, HR@10: 0.9463, MRR: 0.6460
valid [sampled], NDCG@5: 0.5246, HR@5: 0.5268, NDCG@10: 0.5333, HR@10: 0.5544, MRR: 0.5447
test [task], Top5Acc: 0.5832, Top10Acc: 0.7341, Acc: 0.0938, MacroF1: 0.0519, TimeMAE: 13455.9934, TimeRMSE: 71729.4703, TimeMedAE: 207.6866
test [full], NDCG@5: 0.7911, HR@5: 0.9867, NDCG@10: 0.7958, HR@10: 1.0000, MRR: 0.7253
test [sampled], NDCG@5: 0.2528, HR@5: 0.2609, NDCG@10: 0.2930, HR@10: 0.3892, MRR: 0.3033
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s2024/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_anchor_ml20_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7
epoch=1, loss=2.5119
epoch=2, loss=1.5382
epoch=3, loss=1.4147
epoch=4, loss=1.3497
epoch=5, loss=1.3049
valid [task], Top5Acc: 0.3614, Top10Acc: 0.7069, Acc: 0.0718, MacroF1: 0.1195, TimeMAE: 71392.0500, TimeRMSE: 288796.0744, TimeMedAE: 727.5317
valid [full], NDCG@5: 0.6093, HR@5: 0.7076, NDCG@10: 0.6958, HR@10: 0.9838, MRR: 0.6129
valid [sampled], NDCG@5: 0.5138, HR@5: 0.5159, NDCG@10: 0.5241, HR@10: 0.5483, MRR: 0.5308
test [task], Top5Acc: 0.3111, Top10Acc: 0.4077, Acc: 0.0461, MacroF1: 0.0348, TimeMAE: 12707.4961, TimeRMSE: 84381.6845, TimeMedAE: 2.4793
test [full], NDCG@5: 0.6467, HR@5: 0.7497, NDCG@10: 0.6850, HR@10: 0.8726, MRR: 0.6375
test [sampled], NDCG@5: 0.1069, HR@5: 0.1436, NDCG@10: 0.1628, HR@10: 0.3179, MRR: 0.1463
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=6, loss=1.2621
epoch=7, loss=1.2542
epoch=8, loss=1.2270
epoch=9, loss=1.2156
epoch=10, loss=1.2071
valid [task], Top5Acc: 0.4045, Top10Acc: 0.7233, Acc: 0.0850, MacroF1: 0.1384, TimeMAE: 73321.8601, TimeRMSE: 289647.5795, TimeMedAE: 685.7305
valid [full], NDCG@5: 0.6665, HR@5: 0.7931, NDCG@10: 0.7182, HR@10: 0.9555, MRR: 0.6501
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5613, NDCG@10: 0.5664, HR@10: 0.5842, MRR: 0.5742
test [task], Top5Acc: 0.2897, Top10Acc: 0.6657, Acc: 0.0352, MacroF1: 0.0292, TimeMAE: 11739.0440, TimeRMSE: 74205.2080, TimeMedAE: 4.0330
test [full], NDCG@5: 0.7455, HR@5: 0.9297, NDCG@10: 0.7671, HR@10: 0.9961, MRR: 0.6946
test [sampled], NDCG@5: 0.1866, HR@5: 0.2242, NDCG@10: 0.2369, HR@10: 0.3803, MRR: 0.2242
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=11, loss=1.2041
epoch=12, loss=1.1864
epoch=13, loss=1.1726
epoch=14, loss=1.1819
epoch=15, loss=1.1727
valid [task], Top5Acc: 0.4154, Top10Acc: 0.6335, Acc: 0.0881, MacroF1: 0.1300, TimeMAE: 71770.4900, TimeRMSE: 280777.1359, TimeMedAE: 663.0776
valid [full], NDCG@5: 0.6739, HR@5: 0.7950, NDCG@10: 0.7257, HR@10: 0.9563, MRR: 0.6595
valid [sampled], NDCG@5: 0.5696, HR@5: 0.5726, NDCG@10: 0.5776, HR@10: 0.5978, MRR: 0.5846
test [task], Top5Acc: 0.2834, Top10Acc: 0.6412, Acc: 0.0307, MacroF1: 0.0254, TimeMAE: 12080.4326, TimeRMSE: 77054.8158, TimeMedAE: 4.0156
test [full], NDCG@5: 0.7551, HR@5: 0.9517, NDCG@10: 0.7705, HR@10: 1.0000, MRR: 0.6963
test [sampled], NDCG@5: 0.1830, HR@5: 0.2193, NDCG@10: 0.2354, HR@10: 0.3821, MRR: 0.2228
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=16, loss=1.1649
epoch=17, loss=1.1601
epoch=18, loss=1.1562
epoch=19, loss=1.1417
epoch=20, loss=1.1480
valid [task], Top5Acc: 0.3980, Top10Acc: 0.5759, Acc: 0.0682, MacroF1: 0.1062, TimeMAE: 71520.6591, TimeRMSE: 290744.5095, TimeMedAE: 763.9623
valid [full], NDCG@5: 0.6802, HR@5: 0.8271, NDCG@10: 0.7132, HR@10: 0.9354, MRR: 0.6504
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5603, NDCG@10: 0.5659, HR@10: 0.5891, MRR: 0.5724
test [task], Top5Acc: 0.0839, Top10Acc: 0.5820, Acc: 0.0335, MacroF1: 0.0288, TimeMAE: 12300.5667, TimeRMSE: 79753.1876, TimeMedAE: 3.1832
test [full], NDCG@5: 0.6687, HR@5: 0.9360, NDCG@10: 0.6891, HR@10: 1.0000, MRR: 0.5873
test [sampled], NDCG@5: 0.1144, HR@5: 0.1228, NDCG@10: 0.1470, HR@10: 0.2267, MRR: 0.1653
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.1522
epoch=22, loss=1.1399
epoch=23, loss=1.1474
epoch=24, loss=1.1466
epoch=25, loss=1.1488
valid [task], Top5Acc: 0.4007, Top10Acc: 0.5812, Acc: 0.0681, MacroF1: 0.1054, TimeMAE: 68926.4641, TimeRMSE: 278665.3204, TimeMedAE: 779.2416
valid [full], NDCG@5: 0.6886, HR@5: 0.8454, NDCG@10: 0.7176, HR@10: 0.9384, MRR: 0.6541
valid [sampled], NDCG@5: 0.5567, HR@5: 0.5608, NDCG@10: 0.5669, HR@10: 0.5931, MRR: 0.5727
test [task], Top5Acc: 0.1651, Top10Acc: 0.6137, Acc: 0.0335, MacroF1: 0.0305, TimeMAE: 11740.5377, TimeRMSE: 72020.9196, TimeMedAE: 4.3580
test [full], NDCG@5: 0.6741, HR@5: 0.9280, NDCG@10: 0.6975, HR@10: 0.9999, MRR: 0.5978
test [sampled], NDCG@5: 0.1478, HR@5: 0.1581, NDCG@10: 0.1834, HR@10: 0.2718, MRR: 0.1963
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1323
epoch=27, loss=1.1492
epoch=28, loss=1.1261
epoch=29, loss=1.1347
epoch=30, loss=1.1230
valid [task], Top5Acc: 0.4044, Top10Acc: 0.5873, Acc: 0.0698, MacroF1: 0.1020, TimeMAE: 71413.7327, TimeRMSE: 282600.7277, TimeMedAE: 753.8540
valid [full], NDCG@5: 0.6923, HR@5: 0.8517, NDCG@10: 0.7188, HR@10: 0.9385, MRR: 0.6559
valid [sampled], NDCG@5: 0.5578, HR@5: 0.5627, NDCG@10: 0.5673, HR@10: 0.5923, MRR: 0.5738
test [task], Top5Acc: 0.3951, Top10Acc: 0.5599, Acc: 0.0307, MacroF1: 0.0311, TimeMAE: 11522.5881, TimeRMSE: 75739.0921, TimeMedAE: 3.6767
test [full], NDCG@5: 0.7009, HR@5: 0.9254, NDCG@10: 0.7243, HR@10: 0.9999, MRR: 0.6323
test [sampled], NDCG@5: 0.0934, HR@5: 0.1188, NDCG@10: 0.1587, HR@10: 0.3249, MRR: 0.1474
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.1349
epoch=32, loss=1.1282
epoch=33, loss=1.1271
epoch=34, loss=1.1169
epoch=35, loss=1.1189
valid [task], Top5Acc: 0.3899, Top10Acc: 0.5663, Acc: 0.0643, MacroF1: 0.0953, TimeMAE: 69493.0033, TimeRMSE: 276532.1138, TimeMedAE: 772.1598
valid [full], NDCG@5: 0.6848, HR@5: 0.8352, NDCG@10: 0.7143, HR@10: 0.9318, MRR: 0.6522
valid [sampled], NDCG@5: 0.5486, HR@5: 0.5517, NDCG@10: 0.5597, HR@10: 0.5866, MRR: 0.5662
test [task], Top5Acc: 0.2678, Top10Acc: 0.5886, Acc: 0.0306, MacroF1: 0.0254, TimeMAE: 12985.4463, TimeRMSE: 74748.6565, TimeMedAE: 7.1710
test [full], NDCG@5: 0.7029, HR@5: 0.9306, NDCG@10: 0.7253, HR@10: 1.0000, MRR: 0.6349
test [sampled], NDCG@5: 0.0959, HR@5: 0.1224, NDCG@10: 0.1507, HR@10: 0.2954, MRR: 0.1456
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1209
epoch=37, loss=1.1187
epoch=38, loss=1.1277
epoch=39, loss=1.1177
epoch=40, loss=1.1184
valid [task], Top5Acc: 0.3957, Top10Acc: 0.7119, Acc: 0.0639, MacroF1: 0.1062, TimeMAE: 70401.7687, TimeRMSE: 286523.8353, TimeMedAE: 731.3189
valid [full], NDCG@5: 0.7073, HR@5: 0.8534, NDCG@10: 0.7346, HR@10: 0.9400, MRR: 0.6741
valid [sampled], NDCG@5: 0.5520, HR@5: 0.5569, NDCG@10: 0.5683, HR@10: 0.6083, MRR: 0.5728
test [task], Top5Acc: 0.4007, Top10Acc: 0.6204, Acc: 0.0309, MacroF1: 0.0279, TimeMAE: 11460.1160, TimeRMSE: 70908.6119, TimeMedAE: 7.0330
test [full], NDCG@5: 0.6704, HR@5: 0.9301, NDCG@10: 0.6923, HR@10: 0.9999, MRR: 0.5887
test [sampled], NDCG@5: 0.0758, HR@5: 0.0883, NDCG@10: 0.1294, HR@10: 0.2585, MRR: 0.1328
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=41, loss=1.1239
epoch=42, loss=1.1163
epoch=43, loss=1.1021
epoch=44, loss=1.1143
epoch=45, loss=1.1049
valid [task], Top5Acc: 0.4037, Top10Acc: 0.6468, Acc: 0.0624, MacroF1: 0.0972, TimeMAE: 71279.2544, TimeRMSE: 287403.0694, TimeMedAE: 872.5658
valid [full], NDCG@5: 0.7114, HR@5: 0.8544, NDCG@10: 0.7380, HR@10: 0.9417, MRR: 0.6782
valid [sampled], NDCG@5: 0.5597, HR@5: 0.5643, NDCG@10: 0.5754, HR@10: 0.6137, MRR: 0.5797
test [task], Top5Acc: 0.4605, Top10Acc: 0.5959, Acc: 0.0264, MacroF1: 0.0240, TimeMAE: 11392.9353, TimeRMSE: 66680.3246, TimeMedAE: 6.9270
test [full], NDCG@5: 0.7824, HR@5: 0.9377, NDCG@10: 0.8015, HR@10: 1.0000, MRR: 0.7359
test [sampled], NDCG@5: 0.2015, HR@5: 0.2454, NDCG@10: 0.2653, HR@10: 0.4450, MRR: 0.2404
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=46, loss=1.1194
epoch=47, loss=1.1052
epoch=48, loss=1.0955
epoch=49, loss=1.1045
epoch=50, loss=1.1097
valid [task], Top5Acc: 0.3972, Top10Acc: 0.6232, Acc: 0.0662, MacroF1: 0.0900, TimeMAE: 72570.2725, TimeRMSE: 281464.3883, TimeMedAE: 748.5625
valid [full], NDCG@5: 0.7012, HR@5: 0.8440, NDCG@10: 0.7312, HR@10: 0.9400, MRR: 0.6702
valid [sampled], NDCG@5: 0.5569, HR@5: 0.5610, NDCG@10: 0.5702, HR@10: 0.6032, MRR: 0.5760
test [task], Top5Acc: 0.3683, Top10Acc: 0.5921, Acc: 0.0333, MacroF1: 0.0290, TimeMAE: 12244.7733, TimeRMSE: 67503.3323, TimeMedAE: 7.0063
test [full], NDCG@5: 0.6852, HR@5: 0.9366, NDCG@10: 0.7048, HR@10: 0.9999, MRR: 0.6052
test [sampled], NDCG@5: 0.0857, HR@5: 0.1048, NDCG@10: 0.1404, HR@10: 0.2780, MRR: 0.1406
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_anchor_ml20_s7/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42
epoch=1, loss=2.8483
epoch=2, loss=1.7124
epoch=3, loss=1.5800
epoch=4, loss=1.4923
epoch=5, loss=1.4453
valid [task], Top5Acc: 0.3383, Top10Acc: 0.7529, Acc: 0.0629, MacroF1: 0.0955, TimeMAE: 68418.9061, TimeRMSE: 276570.8495, TimeMedAE: 697.9265
valid [full], NDCG@5: 0.5920, HR@5: 0.7000, NDCG@10: 0.6826, HR@10: 0.9766, MRR: 0.5978
valid [sampled], NDCG@5: 0.5070, HR@5: 0.5079, NDCG@10: 0.5084, HR@10: 0.5124, MRR: 0.5223
test [task], Top5Acc: 0.0404, Top10Acc: 0.4262, Acc: 0.0250, MacroF1: 0.0223, TimeMAE: 11375.1936, TimeRMSE: 81156.0527, TimeMedAE: 3.2841
test [full], NDCG@5: 0.4286, HR@5: 0.5090, NDCG@10: 0.5920, HR@10: 1.0000, MRR: 0.4740
test [sampled], NDCG@5: 0.1454, HR@5: 0.1456, NDCG@10: 0.1506, HR@10: 0.1627, MRR: 0.1763
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=1.4109
epoch=7, loss=1.3744
epoch=8, loss=1.3538
epoch=9, loss=1.3408
epoch=10, loss=1.3148
valid [task], Top5Acc: 0.4283, Top10Acc: 0.7558, Acc: 0.0638, MacroF1: 0.0917, TimeMAE: 70756.3234, TimeRMSE: 282042.9712, TimeMedAE: 763.1891
valid [full], NDCG@5: 0.6586, HR@5: 0.7534, NDCG@10: 0.7231, HR@10: 0.9631, MRR: 0.6563
valid [sampled], NDCG@5: 0.5809, HR@5: 0.5822, NDCG@10: 0.5844, HR@10: 0.5931, MRR: 0.5938
test [task], Top5Acc: 0.2859, Top10Acc: 0.4637, Acc: 0.0270, MacroF1: 0.0219, TimeMAE: 12652.4545, TimeRMSE: 82133.8219, TimeMedAE: 7.8753
test [full], NDCG@5: 0.5728, HR@5: 0.7035, NDCG@10: 0.6691, HR@10: 1.0000, MRR: 0.5674
test [sampled], NDCG@5: 0.1496, HR@5: 0.1521, NDCG@10: 0.1759, HR@10: 0.2370, MRR: 0.1943
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=1.3081
epoch=12, loss=1.2994
epoch=13, loss=1.2895
epoch=14, loss=1.2920
epoch=15, loss=1.2742
valid [task], Top5Acc: 0.4511, Top10Acc: 0.7051, Acc: 0.0607, MacroF1: 0.0758, TimeMAE: 74687.1492, TimeRMSE: 283050.3108, TimeMedAE: 698.9759
valid [full], NDCG@5: 0.6661, HR@5: 0.7513, NDCG@10: 0.7337, HR@10: 0.9686, MRR: 0.6682
valid [sampled], NDCG@5: 0.6032, HR@5: 0.6035, NDCG@10: 0.6043, HR@10: 0.6069, MRR: 0.6144
test [task], Top5Acc: 0.3155, Top10Acc: 0.5198, Acc: 0.0230, MacroF1: 0.0168, TimeMAE: 11669.5785, TimeRMSE: 73839.3839, TimeMedAE: 58.4062
test [full], NDCG@5: 0.6537, HR@5: 0.9396, NDCG@10: 0.6731, HR@10: 1.0000, MRR: 0.5653
test [sampled], NDCG@5: 0.0824, HR@5: 0.0846, NDCG@10: 0.1134, HR@10: 0.1846, MRR: 0.1363
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=1.2686
epoch=17, loss=1.2552
epoch=18, loss=1.2641
epoch=19, loss=1.2525
epoch=20, loss=1.2467
valid [task], Top5Acc: 0.4493, Top10Acc: 0.7039, Acc: 0.0662, MacroF1: 0.1044, TimeMAE: 74176.1432, TimeRMSE: 284806.4305, TimeMedAE: 1345.5385
valid [full], NDCG@5: 0.6644, HR@5: 0.7499, NDCG@10: 0.7333, HR@10: 0.9691, MRR: 0.6673
valid [sampled], NDCG@5: 0.6009, HR@5: 0.6013, NDCG@10: 0.6022, HR@10: 0.6055, MRR: 0.6122
test [task], Top5Acc: 0.2968, Top10Acc: 0.5128, Acc: 0.0306, MacroF1: 0.0240, TimeMAE: 11947.8253, TimeRMSE: 72040.5382, TimeMedAE: 122.6997
test [full], NDCG@5: 0.7388, HR@5: 0.9407, NDCG@10: 0.7580, HR@10: 1.0000, MRR: 0.6797
test [sampled], NDCG@5: 0.1007, HR@5: 0.1361, NDCG@10: 0.1565, HR@10: 0.3102, MRR: 0.1465
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.2464
epoch=22, loss=1.2489
epoch=23, loss=1.2349
epoch=24, loss=1.2314
epoch=25, loss=1.2301
valid [task], Top5Acc: 0.4545, Top10Acc: 0.6924, Acc: 0.0666, MacroF1: 0.0572, TimeMAE: 75133.6969, TimeRMSE: 293867.6933, TimeMedAE: 633.3041
valid [full], NDCG@5: 0.6612, HR@5: 0.7375, NDCG@10: 0.7245, HR@10: 0.9457, MRR: 0.6647
valid [sampled], NDCG@5: 0.5899, HR@5: 0.5911, NDCG@10: 0.5942, HR@10: 0.6051, MRR: 0.6023
test [task], Top5Acc: 0.3158, Top10Acc: 0.5187, Acc: 0.0262, MacroF1: 0.0177, TimeMAE: 11904.1803, TimeRMSE: 74371.2284, TimeMedAE: 108.3227
test [full], NDCG@5: 0.7461, HR@5: 0.9451, NDCG@10: 0.7630, HR@10: 1.0000, MRR: 0.6867
test [sampled], NDCG@5: 0.1111, HR@5: 0.1471, NDCG@10: 0.1679, HR@10: 0.3247, MRR: 0.1572
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.2136
epoch=27, loss=1.2226
epoch=28, loss=1.2166
epoch=29, loss=1.2186
epoch=30, loss=1.2185
valid [task], Top5Acc: 0.4280, Top10Acc: 0.6510, Acc: 0.0638, MacroF1: 0.0517, TimeMAE: 72046.0373, TimeRMSE: 285345.4396, TimeMedAE: 757.5615
valid [full], NDCG@5: 0.6392, HR@5: 0.7017, NDCG@10: 0.7169, HR@10: 0.9460, MRR: 0.6542
valid [sampled], NDCG@5: 0.5724, HR@5: 0.5753, NDCG@10: 0.5790, HR@10: 0.5961, MRR: 0.5857
test [task], Top5Acc: 0.2979, Top10Acc: 0.5229, Acc: 0.0270, MacroF1: 0.0192, TimeMAE: 11808.8247, TimeRMSE: 78493.8835, TimeMedAE: 132.3737
test [full], NDCG@5: 0.7469, HR@5: 0.9417, NDCG@10: 0.7658, HR@10: 0.9999, MRR: 0.6896
test [sampled], NDCG@5: 0.0940, HR@5: 0.1276, NDCG@10: 0.1576, HR@10: 0.3265, MRR: 0.1446
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.2066
epoch=32, loss=1.2099
epoch=33, loss=1.2128
epoch=34, loss=1.2048
epoch=35, loss=1.2061
valid [task], Top5Acc: 0.4221, Top10Acc: 0.5966, Acc: 0.0624, MacroF1: 0.0551, TimeMAE: 70074.4326, TimeRMSE: 280504.8426, TimeMedAE: 1741.8897
valid [full], NDCG@5: 0.6425, HR@5: 0.7040, NDCG@10: 0.7258, HR@10: 0.9693, MRR: 0.6575
valid [sampled], NDCG@5: 0.5777, HR@5: 0.5813, NDCG@10: 0.5847, HR@10: 0.6034, MRR: 0.5908
test [task], Top5Acc: 0.3009, Top10Acc: 0.5232, Acc: 0.0238, MacroF1: 0.0149, TimeMAE: 11755.7473, TimeRMSE: 71660.5450, TimeMedAE: 90.7786
test [full], NDCG@5: 0.6688, HR@5: 0.9424, NDCG@10: 0.6870, HR@10: 1.0000, MRR: 0.5822
test [sampled], NDCG@5: 0.0664, HR@5: 0.0722, NDCG@10: 0.1068, HR@10: 0.2019, MRR: 0.1254
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.2041
epoch=37, loss=1.1969
epoch=38, loss=1.1904
epoch=39, loss=1.2093
epoch=40, loss=1.1952
valid [task], Top5Acc: 0.3894, Top10Acc: 0.5737, Acc: 0.0583, MacroF1: 0.0653, TimeMAE: 68860.6535, TimeRMSE: 272091.0451, TimeMedAE: 775.7081
valid [full], NDCG@5: 0.6349, HR@5: 0.7214, NDCG@10: 0.7071, HR@10: 0.9543, MRR: 0.6383
valid [sampled], NDCG@5: 0.5529, HR@5: 0.5564, NDCG@10: 0.5625, HR@10: 0.5866, MRR: 0.5676
test [task], Top5Acc: 0.2952, Top10Acc: 0.5115, Acc: 0.0218, MacroF1: 0.0166, TimeMAE: 11123.3279, TimeRMSE: 66031.8193, TimeMedAE: 83.5267
test [full], NDCG@5: 0.6550, HR@5: 0.9374, NDCG@10: 0.6751, HR@10: 1.0000, MRR: 0.5668
test [sampled], NDCG@5: 0.0436, HR@5: 0.0513, NDCG@10: 0.0856, HR@10: 0.1863, MRR: 0.1033
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.1968
epoch=42, loss=1.2001
epoch=43, loss=1.1998
epoch=44, loss=1.2011
epoch=45, loss=1.2040
valid [task], Top5Acc: 0.4209, Top10Acc: 0.5821, Acc: 0.0644, MacroF1: 0.0508, TimeMAE: 77026.1043, TimeRMSE: 286218.9715, TimeMedAE: 1543.8780
valid [full], NDCG@5: 0.6459, HR@5: 0.7422, NDCG@10: 0.7138, HR@10: 0.9569, MRR: 0.6448
valid [sampled], NDCG@5: 0.5508, HR@5: 0.5533, NDCG@10: 0.5575, HR@10: 0.5746, MRR: 0.5661
test [task], Top5Acc: 0.3259, Top10Acc: 0.5174, Acc: 0.0254, MacroF1: 0.0150, TimeMAE: 12729.8577, TimeRMSE: 70104.6549, TimeMedAE: 129.3972
test [full], NDCG@5: 0.7301, HR@5: 0.9021, NDCG@10: 0.7637, HR@10: 1.0000, MRR: 0.6875
test [sampled], NDCG@5: 0.1092, HR@5: 0.1471, NDCG@10: 0.1664, HR@10: 0.3261, MRR: 0.1551
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1894
epoch=47, loss=1.1905
epoch=48, loss=1.1836
epoch=49, loss=1.1930
epoch=50, loss=1.1811
valid [task], Top5Acc: 0.3995, Top10Acc: 0.5780, Acc: 0.0580, MacroF1: 0.0434, TimeMAE: 68641.8373, TimeRMSE: 280653.5231, TimeMedAE: 1439.1086
valid [full], NDCG@5: 0.6364, HR@5: 0.7412, NDCG@10: 0.7051, HR@10: 0.9574, MRR: 0.6329
valid [sampled], NDCG@5: 0.5330, HR@5: 0.5360, NDCG@10: 0.5415, HR@10: 0.5627, MRR: 0.5493
test [task], Top5Acc: 0.3285, Top10Acc: 0.5987, Acc: 0.0239, MacroF1: 0.0156, TimeMAE: 12373.9432, TimeRMSE: 69086.0041, TimeMedAE: 76.9804
test [full], NDCG@5: 0.7439, HR@5: 0.9015, NDCG@10: 0.7772, HR@10: 0.9980, MRR: 0.7053
test [sampled], NDCG@5: 0.1041, HR@5: 0.1440, NDCG@10: 0.1685, HR@10: 0.3458, MRR: 0.1520
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s42/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024
epoch=1, loss=3.1746
epoch=2, loss=1.7878
epoch=3, loss=1.5792
epoch=4, loss=1.4786
epoch=5, loss=1.4225
valid [task], Top5Acc: 0.3538, Top10Acc: 0.6978, Acc: 0.0699, MacroF1: 0.1092, TimeMAE: 72347.3263, TimeRMSE: 292168.4166, TimeMedAE: 1140.7852
valid [full], NDCG@5: 0.6041, HR@5: 0.7009, NDCG@10: 0.6673, HR@10: 0.9053, MRR: 0.6059
valid [sampled], NDCG@5: 0.5189, HR@5: 0.5195, NDCG@10: 0.5232, HR@10: 0.5330, MRR: 0.5340
test [task], Top5Acc: 0.2883, Top10Acc: 0.5326, Acc: 0.0214, MacroF1: 0.0195, TimeMAE: 12800.6221, TimeRMSE: 83246.1623, TimeMedAE: 43.7193
test [full], NDCG@5: 0.5948, HR@5: 0.7987, NDCG@10: 0.6531, HR@10: 0.9795, MRR: 0.5516
test [sampled], NDCG@5: 0.0999, HR@5: 0.1040, NDCG@10: 0.1320, HR@10: 0.2078, MRR: 0.1499
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=1.3844
epoch=7, loss=1.3584
epoch=8, loss=1.3461
epoch=9, loss=1.3224
epoch=10, loss=1.3194
valid [task], Top5Acc: 0.4320, Top10Acc: 0.7047, Acc: 0.0623, MacroF1: 0.0966, TimeMAE: 68851.2721, TimeRMSE: 273666.3347, TimeMedAE: 2253.0186
valid [full], NDCG@5: 0.6642, HR@5: 0.7455, NDCG@10: 0.7258, HR@10: 0.9450, MRR: 0.6668
valid [sampled], NDCG@5: 0.5958, HR@5: 0.5969, NDCG@10: 0.5991, HR@10: 0.6072, MRR: 0.6079
test [task], Top5Acc: 0.2983, Top10Acc: 0.5819, Acc: 0.0175, MacroF1: 0.0175, TimeMAE: 12628.4166, TimeRMSE: 74617.9551, TimeMedAE: 34.6581
test [full], NDCG@5: 0.6240, HR@5: 0.8802, NDCG@10: 0.6604, HR@10: 0.9942, MRR: 0.5530
test [sampled], NDCG@5: 0.0718, HR@5: 0.0768, NDCG@10: 0.1022, HR@10: 0.1742, MRR: 0.1244
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=11, loss=1.3147
epoch=12, loss=1.3052
epoch=13, loss=1.2907
epoch=14, loss=1.2777
epoch=15, loss=1.2807
valid [task], Top5Acc: 0.4542, Top10Acc: 0.6756, Acc: 0.0542, MacroF1: 0.0546, TimeMAE: 69954.3535, TimeRMSE: 283388.9583, TimeMedAE: 2985.1906
valid [full], NDCG@5: 0.6629, HR@5: 0.7277, NDCG@10: 0.7299, HR@10: 0.9465, MRR: 0.6727
valid [sampled], NDCG@5: 0.6150, HR@5: 0.6152, NDCG@10: 0.6159, HR@10: 0.6182, MRR: 0.6247
test [task], Top5Acc: 0.3220, Top10Acc: 0.5561, Acc: 0.0167, MacroF1: 0.0127, TimeMAE: 13194.6935, TimeRMSE: 82110.3109, TimeMedAE: 88.9608
test [full], NDCG@5: 0.7121, HR@5: 0.8703, NDCG@10: 0.7539, HR@10: 1.0000, MRR: 0.6761
test [sampled], NDCG@5: 0.1069, HR@5: 0.1479, NDCG@10: 0.1626, HR@10: 0.3221, MRR: 0.1495
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=16, loss=1.2746
epoch=17, loss=1.2632
epoch=18, loss=1.2577
epoch=19, loss=1.2626
epoch=20, loss=1.2494
valid [task], Top5Acc: 0.4544, Top10Acc: 0.6936, Acc: 0.0575, MacroF1: 0.0892, TimeMAE: 72161.1481, TimeRMSE: 293783.3315, TimeMedAE: 1232.6515
valid [full], NDCG@5: 0.6664, HR@5: 0.7381, NDCG@10: 0.7297, HR@10: 0.9456, MRR: 0.6719
valid [sampled], NDCG@5: 0.6076, HR@5: 0.6085, NDCG@10: 0.6104, HR@10: 0.6173, MRR: 0.6186
test [task], Top5Acc: 0.3316, Top10Acc: 0.5454, Acc: 0.0177, MacroF1: 0.0164, TimeMAE: 12512.0381, TimeRMSE: 79978.9067, TimeMedAE: 114.1617
test [full], NDCG@5: 0.6918, HR@5: 0.8724, NDCG@10: 0.7331, HR@10: 1.0000, MRR: 0.6479
test [sampled], NDCG@5: 0.1281, HR@5: 0.1695, NDCG@10: 0.1870, HR@10: 0.3528, MRR: 0.1684
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.2384
epoch=22, loss=1.2364
epoch=23, loss=1.2263
epoch=24, loss=1.2329
epoch=25, loss=1.2305
valid [task], Top5Acc: 0.4573, Top10Acc: 0.6971, Acc: 0.0666, MacroF1: 0.0915, TimeMAE: 72668.8491, TimeRMSE: 285322.5387, TimeMedAE: 767.6082
valid [full], NDCG@5: 0.6706, HR@5: 0.7519, NDCG@10: 0.7357, HR@10: 0.9555, MRR: 0.6749
valid [sampled], NDCG@5: 0.6066, HR@5: 0.6072, NDCG@10: 0.6093, HR@10: 0.6157, MRR: 0.6182
test [task], Top5Acc: 0.3336, Top10Acc: 0.5868, Acc: 0.0317, MacroF1: 0.0276, TimeMAE: 13511.6519, TimeRMSE: 79368.6776, TimeMedAE: 57.0905
test [full], NDCG@5: 0.6784, HR@5: 0.8927, NDCG@10: 0.7158, HR@10: 1.0000, MRR: 0.6250
test [sampled], NDCG@5: 0.1129, HR@5: 0.1506, NDCG@10: 0.1671, HR@10: 0.3191, MRR: 0.1532
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=26, loss=1.2274
epoch=27, loss=1.2170
epoch=28, loss=1.2238
epoch=29, loss=1.2227
epoch=30, loss=1.2070
valid [task], Top5Acc: 0.4567, Top10Acc: 0.5999, Acc: 0.0652, MacroF1: 0.1112, TimeMAE: 76760.1822, TimeRMSE: 292111.3120, TimeMedAE: 4485.4402
valid [full], NDCG@5: 0.6926, HR@5: 0.8057, NDCG@10: 0.7376, HR@10: 0.9419, MRR: 0.6801
valid [sampled], NDCG@5: 0.6014, HR@5: 0.6040, NDCG@10: 0.6064, HR@10: 0.6196, MRR: 0.6141
test [task], Top5Acc: 0.4208, Top10Acc: 0.6091, Acc: 0.0328, MacroF1: 0.0262, TimeMAE: 13892.6412, TimeRMSE: 76083.7124, TimeMedAE: 142.2186
test [full], NDCG@5: 0.7395, HR@5: 0.9733, NDCG@10: 0.7490, HR@10: 1.0000, MRR: 0.6664
test [sampled], NDCG@5: 0.1194, HR@5: 0.1613, NDCG@10: 0.1830, HR@10: 0.3591, MRR: 0.1634
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=31, loss=1.2216
epoch=32, loss=1.2055
epoch=33, loss=1.2180
epoch=34, loss=1.2084
epoch=35, loss=1.2178
valid [task], Top5Acc: 0.4391, Top10Acc: 0.5835, Acc: 0.0655, MacroF1: 0.0966, TimeMAE: 71642.5437, TimeRMSE: 287861.4063, TimeMedAE: 4802.9861
valid [full], NDCG@5: 0.6845, HR@5: 0.7943, NDCG@10: 0.7315, HR@10: 0.9401, MRR: 0.6735
valid [sampled], NDCG@5: 0.5976, HR@5: 0.5988, NDCG@10: 0.6015, HR@10: 0.6111, MRR: 0.6102
test [task], Top5Acc: 0.5135, Top10Acc: 0.6105, Acc: 0.0382, MacroF1: 0.0312, TimeMAE: 13976.5905, TimeRMSE: 83717.9120, TimeMedAE: 183.1664
test [full], NDCG@5: 0.8009, HR@5: 0.9592, NDCG@10: 0.8153, HR@10: 1.0000, MRR: 0.7551
test [sampled], NDCG@5: 0.2124, HR@5: 0.2561, NDCG@10: 0.2788, HR@10: 0.4624, MRR: 0.2509
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.2150
epoch=37, loss=1.2079
epoch=38, loss=1.2092
epoch=39, loss=1.2033
epoch=40, loss=1.2003
valid [task], Top5Acc: 0.4136, Top10Acc: 0.5772, Acc: 0.0630, MacroF1: 0.0868, TimeMAE: 78812.7499, TimeRMSE: 297881.2228, TimeMedAE: 5745.3853
valid [full], NDCG@5: 0.6801, HR@5: 0.8368, NDCG@10: 0.7120, HR@10: 0.9393, MRR: 0.6470
valid [sampled], NDCG@5: 0.5416, HR@5: 0.5455, NDCG@10: 0.5509, HR@10: 0.5748, MRR: 0.5580
test [task], Top5Acc: 0.4855, Top10Acc: 0.5993, Acc: 0.0247, MacroF1: 0.0219, TimeMAE: 14497.5147, TimeRMSE: 75395.5275, TimeMedAE: 101.1073
test [full], NDCG@5: 0.8209, HR@5: 0.9389, NDCG@10: 0.8414, HR@10: 1.0000, MRR: 0.7906
test [sampled], NDCG@5: 0.2548, HR@5: 0.3066, NDCG@10: 0.3249, HR@10: 0.5245, MRR: 0.2896
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.1976
epoch=42, loss=1.2014
epoch=43, loss=1.2038
epoch=44, loss=1.1920
epoch=45, loss=1.1928
valid [task], Top5Acc: 0.4096, Top10Acc: 0.5860, Acc: 0.0661, MacroF1: 0.0655, TimeMAE: 75263.8901, TimeRMSE: 285798.3498, TimeMedAE: 2442.5809
valid [full], NDCG@5: 0.6556, HR@5: 0.7758, NDCG@10: 0.7140, HR@10: 0.9577, MRR: 0.6440
valid [sampled], NDCG@5: 0.5413, HR@5: 0.5455, NDCG@10: 0.5517, HR@10: 0.5782, MRR: 0.5579
test [task], Top5Acc: 0.4978, Top10Acc: 0.6606, Acc: 0.0291, MacroF1: 0.0206, TimeMAE: 13293.3020, TimeRMSE: 73618.6256, TimeMedAE: 161.2538
test [full], NDCG@5: 0.8463, HR@5: 0.9481, NDCG@10: 0.8641, HR@10: 1.0000, MRR: 0.8204
test [sampled], NDCG@5: 0.2256, HR@5: 0.2828, NDCG@10: 0.3078, HR@10: 0.5379, MRR: 0.2644
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1901
epoch=47, loss=1.1866
epoch=48, loss=1.1892
epoch=49, loss=1.1834
epoch=50, loss=1.1865
valid [task], Top5Acc: 0.3967, Top10Acc: 0.5745, Acc: 0.0680, MacroF1: 0.0966, TimeMAE: 72902.4140, TimeRMSE: 289346.8780, TimeMedAE: 4615.6863
valid [full], NDCG@5: 0.6140, HR@5: 0.7578, NDCG@10: 0.6674, HR@10: 0.9199, MRR: 0.5965
valid [sampled], NDCG@5: 0.4847, HR@5: 0.4880, NDCG@10: 0.4918, HR@10: 0.5103, MRR: 0.5013
test [task], Top5Acc: 0.4719, Top10Acc: 0.6756, Acc: 0.0306, MacroF1: 0.0253, TimeMAE: 13451.2636, TimeRMSE: 71803.6687, TimeMedAE: 124.4466
test [full], NDCG@5: 0.8746, HR@5: 0.9524, NDCG@10: 0.8910, HR@10: 1.0000, MRR: 0.8567
test [sampled], NDCG@5: 0.3622, HR@5: 0.4059, NDCG@10: 0.4179, HR@10: 0.5786, MRR: 0.3917
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s2024/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7
epoch=1, loss=2.8306
epoch=2, loss=1.7300
epoch=3, loss=1.5877
epoch=4, loss=1.5011
epoch=5, loss=1.4467
valid [task], Top5Acc: 0.3898, Top10Acc: 0.7132, Acc: 0.0637, MacroF1: 0.1066, TimeMAE: 72142.9943, TimeRMSE: 289429.2064, TimeMedAE: 978.3202
valid [full], NDCG@5: 0.5020, HR@5: 0.6528, NDCG@10: 0.5977, HR@10: 0.9491, MRR: 0.4952
valid [sampled], NDCG@5: 0.3377, HR@5: 0.3638, NDCG@10: 0.3756, HR@10: 0.4820, MRR: 0.3607
test [task], Top5Acc: 0.3551, Top10Acc: 0.6160, Acc: 0.0338, MacroF1: 0.0271, TimeMAE: 14291.1845, TimeRMSE: 85626.2308, TimeMedAE: 3.3512
test [full], NDCG@5: 0.6708, HR@5: 0.8015, NDCG@10: 0.7349, HR@10: 1.0000, MRR: 0.6529
test [sampled], NDCG@5: 0.2323, HR@5: 0.2430, NDCG@10: 0.2583, HR@10: 0.3252, MRR: 0.2723
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=1.3987
epoch=7, loss=1.3748
epoch=8, loss=1.3529
epoch=9, loss=1.3372
epoch=10, loss=1.3241
valid [task], Top5Acc: 0.4163, Top10Acc: 0.7754, Acc: 0.0684, MacroF1: 0.0768, TimeMAE: 70615.1428, TimeRMSE: 289229.6660, TimeMedAE: 795.9506
valid [full], NDCG@5: 0.6662, HR@5: 0.7692, NDCG@10: 0.7220, HR@10: 0.9555, MRR: 0.6575
valid [sampled], NDCG@5: 0.5750, HR@5: 0.5764, NDCG@10: 0.5801, HR@10: 0.5924, MRR: 0.5889
test [task], Top5Acc: 0.3164, Top10Acc: 0.4755, Acc: 0.0305, MacroF1: 0.0246, TimeMAE: 12660.3550, TimeRMSE: 81513.5872, TimeMedAE: 7.6177
test [full], NDCG@5: 0.5953, HR@5: 0.7887, NDCG@10: 0.6625, HR@10: 1.0000, MRR: 0.5570
test [sampled], NDCG@5: 0.1106, HR@5: 0.1151, NDCG@10: 0.1431, HR@10: 0.2201, MRR: 0.1588
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=1.3150
epoch=12, loss=1.3009
epoch=13, loss=1.2848
epoch=14, loss=1.2794
epoch=15, loss=1.2753
valid [task], Top5Acc: 0.4504, Top10Acc: 0.7691, Acc: 0.0671, MacroF1: 0.0946, TimeMAE: 71791.2613, TimeRMSE: 279170.2273, TimeMedAE: 814.1828
valid [full], NDCG@5: 0.6553, HR@5: 0.7125, NDCG@10: 0.7326, HR@10: 0.9563, MRR: 0.6710
valid [sampled], NDCG@5: 0.6011, HR@5: 0.6015, NDCG@10: 0.6047, HR@10: 0.6129, MRR: 0.6133
test [task], Top5Acc: 0.3052, Top10Acc: 0.6160, Acc: 0.0262, MacroF1: 0.0228, TimeMAE: 12867.7166, TimeRMSE: 79895.4938, TimeMedAE: 8.6773
test [full], NDCG@5: 0.6576, HR@5: 0.8381, NDCG@10: 0.7115, HR@10: 1.0000, MRR: 0.6198
test [sampled], NDCG@5: 0.1740, HR@5: 0.1853, NDCG@10: 0.2004, HR@10: 0.2689, MRR: 0.2176
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=1.2631
epoch=17, loss=1.2649
epoch=18, loss=1.2491
epoch=19, loss=1.2425
epoch=20, loss=1.2453
valid [task], Top5Acc: 0.4499, Top10Acc: 0.7322, Acc: 0.0598, MacroF1: 0.0875, TimeMAE: 73186.1916, TimeRMSE: 292144.9913, TimeMedAE: 1354.7748
valid [full], NDCG@5: 0.6551, HR@5: 0.7089, NDCG@10: 0.7267, HR@10: 0.9364, MRR: 0.6709
valid [sampled], NDCG@5: 0.6056, HR@5: 0.6059, NDCG@10: 0.6075, HR@10: 0.6120, MRR: 0.6167
test [task], Top5Acc: 0.3026, Top10Acc: 0.6247, Acc: 0.0197, MacroF1: 0.0150, TimeMAE: 12663.4582, TimeRMSE: 82578.7614, TimeMedAE: 7.6712
test [full], NDCG@5: 0.7328, HR@5: 0.8736, NDCG@10: 0.7742, HR@10: 0.9999, MRR: 0.7035
test [sampled], NDCG@5: 0.2107, HR@5: 0.2485, NDCG@10: 0.2580, HR@10: 0.3958, MRR: 0.2457
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.2437
epoch=22, loss=1.2371
epoch=23, loss=1.2416
epoch=24, loss=1.2289
epoch=25, loss=1.2319
valid [task], Top5Acc: 0.4252, Top10Acc: 0.6075, Acc: 0.0609, MacroF1: 0.1063, TimeMAE: 68953.2840, TimeRMSE: 278188.2198, TimeMedAE: 1754.3827
valid [full], NDCG@5: 0.6425, HR@5: 0.7035, NDCG@10: 0.7226, HR@10: 0.9538, MRR: 0.6586
valid [sampled], NDCG@5: 0.5853, HR@5: 0.5878, NDCG@10: 0.5907, HR@10: 0.6048, MRR: 0.5974
test [task], Top5Acc: 0.3484, Top10Acc: 0.6256, Acc: 0.0241, MacroF1: 0.0217, TimeMAE: 12490.3675, TimeRMSE: 75309.1686, TimeMedAE: 20.4772
test [full], NDCG@5: 0.7746, HR@5: 0.8852, NDCG@10: 0.8136, HR@10: 0.9999, MRR: 0.7539
test [sampled], NDCG@5: 0.2170, HR@5: 0.2541, NDCG@10: 0.2776, HR@10: 0.4436, MRR: 0.2579
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.2227
epoch=27, loss=1.2339
epoch=28, loss=1.2093
epoch=29, loss=1.2170
epoch=30, loss=1.2109
valid [task], Top5Acc: 0.4339, Top10Acc: 0.6367, Acc: 0.0617, MacroF1: 0.0948, TimeMAE: 71998.0801, TimeRMSE: 282394.0598, TimeMedAE: 1921.5013
valid [full], NDCG@5: 0.6562, HR@5: 0.7396, NDCG@10: 0.7142, HR@10: 0.9180, MRR: 0.6600
valid [sampled], NDCG@5: 0.5811, HR@5: 0.5832, NDCG@10: 0.5874, HR@10: 0.6034, MRR: 0.5944
test [task], Top5Acc: 0.3898, Top10Acc: 0.6241, Acc: 0.0207, MacroF1: 0.0186, TimeMAE: 11995.0953, TimeRMSE: 77264.8113, TimeMedAE: 15.5365
test [full], NDCG@5: 0.6898, HR@5: 0.8801, NDCG@10: 0.7310, HR@10: 0.9999, MRR: 0.6417
test [sampled], NDCG@5: 0.1788, HR@5: 0.1851, NDCG@10: 0.2175, HR@10: 0.3091, MRR: 0.2299
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.2192
epoch=32, loss=1.2214
epoch=33, loss=1.2037
epoch=34, loss=1.2061
epoch=35, loss=1.2055
valid [task], Top5Acc: 0.4159, Top10Acc: 0.6326, Acc: 0.0641, MacroF1: 0.0843, TimeMAE: 70097.7284, TimeRMSE: 278537.8963, TimeMedAE: 3655.7991
valid [full], NDCG@5: 0.6709, HR@5: 0.7811, NDCG@10: 0.7255, HR@10: 0.9541, MRR: 0.6608
valid [sampled], NDCG@5: 0.5755, HR@5: 0.5781, NDCG@10: 0.5835, HR@10: 0.6035, MRR: 0.5896
test [task], Top5Acc: 0.3925, Top10Acc: 0.6343, Acc: 0.0301, MacroF1: 0.0223, TimeMAE: 13299.0300, TimeRMSE: 77861.1880, TimeMedAE: 13.0787
test [full], NDCG@5: 0.7540, HR@5: 0.9268, NDCG@10: 0.7785, HR@10: 0.9999, MRR: 0.7068
test [sampled], NDCG@5: 0.1190, HR@5: 0.1724, NDCG@10: 0.1934, HR@10: 0.4039, MRR: 0.1605
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.2019
epoch=37, loss=1.1974
epoch=38, loss=1.2088
epoch=39, loss=1.2029
epoch=40, loss=1.2021
valid [task], Top5Acc: 0.4293, Top10Acc: 0.6118, Acc: 0.0693, MacroF1: 0.0992, TimeMAE: 75244.7950, TimeRMSE: 281681.1160, TimeMedAE: 5050.6979
valid [full], NDCG@5: 0.6824, HR@5: 0.7964, NDCG@10: 0.7218, HR@10: 0.9189, MRR: 0.6682
valid [sampled], NDCG@5: 0.5803, HR@5: 0.5831, NDCG@10: 0.5886, HR@10: 0.6091, MRR: 0.5952
test [task], Top5Acc: 0.4561, Top10Acc: 0.6660, Acc: 0.0311, MacroF1: 0.0247, TimeMAE: 16034.5099, TimeRMSE: 69565.8388, TimeMedAE: 55.8766
test [full], NDCG@5: 0.8277, HR@5: 0.9819, NDCG@10: 0.8339, HR@10: 0.9999, MRR: 0.7785
test [sampled], NDCG@5: 0.1252, HR@5: 0.1804, NDCG@10: 0.2127, HR@10: 0.4537, MRR: 0.1737
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.2094
epoch=42, loss=1.1978
epoch=43, loss=1.1875
epoch=44, loss=1.1948
epoch=45, loss=1.1832
valid [task], Top5Acc: 0.3966, Top10Acc: 0.6628, Acc: 0.0645, MacroF1: 0.0981, TimeMAE: 73644.6985, TimeRMSE: 287345.3858, TimeMedAE: 7958.6898
valid [full], NDCG@5: 0.6929, HR@5: 0.8460, NDCG@10: 0.7197, HR@10: 0.9354, MRR: 0.6576
valid [sampled], NDCG@5: 0.5362, HR@5: 0.5418, NDCG@10: 0.5504, HR@10: 0.5866, MRR: 0.5553
test [task], Top5Acc: 0.4836, Top10Acc: 0.6809, Acc: 0.0276, MacroF1: 0.0241, TimeMAE: 15126.8118, TimeRMSE: 70533.0970, TimeMedAE: 591.8425
test [full], NDCG@5: 0.8443, HR@5: 0.9919, NDCG@10: 0.8471, HR@10: 0.9999, MRR: 0.7949
test [sampled], NDCG@5: 0.1349, HR@5: 0.2019, NDCG@10: 0.2361, HR@10: 0.5166, MRR: 0.1821
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.2013
epoch=47, loss=1.1899
epoch=48, loss=1.1843
epoch=49, loss=1.1829
epoch=50, loss=1.1898
valid [task], Top5Acc: 0.4010, Top10Acc: 0.6125, Acc: 0.0670, MacroF1: 0.0830, TimeMAE: 74793.7308, TimeRMSE: 286184.7716, TimeMedAE: 3982.9078
valid [full], NDCG@5: 0.6968, HR@5: 0.8281, NDCG@10: 0.7280, HR@10: 0.9299, MRR: 0.6711
valid [sampled], NDCG@5: 0.5637, HR@5: 0.5700, NDCG@10: 0.5796, HR@10: 0.6198, MRR: 0.5815
test [task], Top5Acc: 0.4835, Top10Acc: 0.6898, Acc: 0.0299, MacroF1: 0.0275, TimeMAE: 13745.7831, TimeRMSE: 64698.7973, TimeMedAE: 264.5798
test [full], NDCG@5: 0.8372, HR@5: 0.9966, NDCG@10: 0.8384, HR@10: 0.9999, MRR: 0.7827
test [sampled], NDCG@5: 0.1043, HR@5: 0.1824, NDCG@10: 0.2142, HR@10: 0.5241, MRR: 0.1520
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2/multitask_refine_ml50_do035_s7/sasrec_last.pth

In [ ]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'enable_time_prediction': config.get('enable_time_prediction', False),
            'time_prediction_target': config.get('time_prediction_target'),
            'time_loss_weight': config.get('time_loss_weight'),
            'time_target_transform': config.get('time_target_transform'),
            'time_modeling_mode': config.get('time_modeling_mode'),
        }
        for group_name in ['best_valid', 'best_test_at_best_valid', 'last_valid', 'last_test']:
            group = summary.get(group_name) or {}
            for mode, metrics in group.items():
                for key, value in metrics.items():
                    row[f'{group_name}_{mode}_{key}'] = value
        rows.append(row)
    return pd.DataFrame(rows)

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1600)
pd.set_option('display.max_colwidth', None)

## Comparison summary

In [23]:
baseline_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
multitask_runs = [
    'multitask_anchor_ml20_s42',
    'multitask_anchor_ml20_s2024',
    'multitask_anchor_ml20_s7',
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
multitask_df = rebuild_df(MULTITASK_BASELINE_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['variant'] = baseline_subset['run_name'].map(
    lambda x: 'anchor_single_task' if x.startswith('anchor_ml20') else 'refine_single_task'
)

multitask_subset = multitask_df[multitask_df['run_name'].isin(multitask_runs)].copy()
multitask_subset['variant'] = multitask_subset['run_name'].map(
    lambda x: 'anchor_multi_task' if 'anchor_ml20' in x else 'refine_multi_task'
)

df_compare = pd.concat([baseline_subset, multitask_subset], ignore_index=True)
df_compare = df_compare.sort_values(['variant', 'seed', 'run_name']).reset_index(drop=True)

id_cols = [
    'run_name', 'seed', 'variant', 'maxlen', 'dropout_rate',
    'hidden_units', 'selection_metric', 'enable_time_prediction',
    'time_prediction_target', 'time_loss_weight',
    'time_target_transform', 'time_modeling_mode',
]

metric_prefixes = (
    'best_valid_',
    'best_test_at_best_valid_',
    'last_valid_',
    'last_test_',
)

metric_cols = sorted([
    c for c in df_compare.columns
    if c.startswith(metric_prefixes)
])

display_cols = [c for c in id_cols if c in df_compare.columns] + metric_cols
df_compare[display_cols]

,run_name,seed,variant,maxlen,dropout_rate,hidden_units,selection_metric,enable_time_prediction,time_prediction_target,time_loss_weight,time_target_transform,time_modeling_mode,best_test_at_best_valid_full_hr@10,best_test_at_best_valid_full_hr@5,best_test_at_best_valid_full_mean_rank,best_test_at_best_valid_full_median_rank,best_test_at_best_valid_full_mrr,best_test_at_best_valid_full_ndcg@10,best_test_at_best_valid_full_ndcg@5,best_test_at_best_valid_full_num_eval_users,best_test_at_best_valid_sampled_hr@10,best_test_at_best_valid_sampled_hr@5,best_test_at_best_valid_sampled_mean_rank,best_test_at_best_valid_sampled_median_rank,best_test_at_best_valid_sampled_mrr,best_test_at_best_valid_sampled_ndcg@10,best_test_at_best_valid_sampled_ndcg@5,best_test_at_best_valid_sampled_num_eval_users,best_test_at_best_valid_task_accuracy,best_test_at_best_valid_task_macro_f1,best_test_at_best_valid_task_time_mae,best_test_at_best_valid_task_time_median_ae,best_test_at_best_valid_task_time_rmse,best_test_at_best_valid_task_top10_accuracy,best_test_at_best_valid_task_top1_accuracy,best_test_at_best_valid_task_top5_accuracy,best_valid_full_hr@10,best_valid_full_hr@5,best_valid_full_mean_rank,best_valid_full_median_rank,best_valid_full_mrr,best_valid_full_ndcg@10,best_valid_full_ndcg@5,best_valid_full_num_eval_users,best_valid_sampled_hr@10,best_valid_sampled_hr@5,best_valid_sampled_mean_rank,best_valid_sampled_median_rank,best_valid_sampled_mrr,best_valid_sampled_ndcg@10,best_valid_sampled_ndcg@5,best_valid_sampled_num_eval_users,best_valid_task_accuracy,best_valid_task_macro_f1,best_valid_task_time_mae,best_valid_task_time_median_ae,best_valid_task_time_rmse,best_valid_task_top10_accuracy,best_valid_task_top1_accuracy,best_valid_task_top5_accuracy,last_test_full_hr@10,last_test_full_hr@5,last_test_full_mean_rank,last_test_full_median_rank,last_test_full_mrr,last_test_full_ndcg@10,last_test_full_ndcg@5,last_test_full_num_eval_users,last_test_sampled_hr@10,last_test_sampled_hr@5,last_test_sampled_mean_rank,last_test_sampled_median_rank,last_test_sampled_mrr,last_test_sampled_ndcg@10,last_test_sampled_ndcg@5,last_test_sampled_num_eval_users,last_test_task_accuracy,last_test_task_macro_f1,last_test_task_time_mae,last_test_task_time_median_ae,last_test_task_time_rmse,last_test_task_top10_accuracy,last_test_task_top1_accuracy,last_test_task_top5_accuracy,last_valid_full_hr@10,last_valid_full_hr@5,last_valid_full_mean_rank,last_valid_full_median_rank,last_valid_full_mrr,last_valid_full_ndcg@10,last_valid_full_ndcg@5,last_valid_full_num_eval_users,last_valid_sampled_hr@10,last_valid_sampled_hr@5,last_valid_sampled_mean_rank,last_valid_sampled_median_rank,last_valid_sampled_mrr,last_valid_sampled_ndcg@10,last_valid_sampled_ndcg@5,last_valid_sampled_num_eval_users,last_valid_task_accuracy,last_valid_task_macro_f1,last_valid_task_time_mae,last_valid_task_time_median_ae,last_valid_task_time_rmse,last_valid_task_top10_accuracy,last_valid_task_top1_accuracy,last_valid_task_top5_accuracy
0,multitask_anchor_ml20_s7,7,anchor_multi_task,20,0.20,50,full_valid_ndcg@10,True,delta_next_seconds,1.0,log1p,disabled,1.000000,0.937745,2.000947,1.0,0.735914,0.801466,0.782387,7389,0.444986,0.245365,17.870483,12.0,0.240381,0.265319,0.201450,7389,0.026391,0.023985,11392.935271,6.927000,66680.324584,0.595886,0.026391,0.460549,0.941655,0.854410,3.126323,1.0,0.678242,0.737962,0.711434,7370,0.613704,0.564315,17.737313,1.0,0.579719,0.575376,0.559712,7370,0.062415,0.097186,71279.254416,872.565819,287403.069435,0.646811,0.062415,0.403664,0.999864,0.936575,2.266739,2.0,0.605188,0.704814,0.685202,7363,0.278012,0.104849,19.570420,15.0,0.140627,0.140360,0.085710,7363,0.033274,0.028958,12244.773316,7.006304,67503.332274,0.592150,0.033274,0.368328,0.940043,0.844004,3.170103,1.0,0.670183,0.731218,0.701211,7372,0.603228,0.561042,18.026858,1.0,0.575956,0.570175,0.556852,7372,0.066196,0.090025,72570.272486,748.562512,281464.388283,0.623169,0.066196,0.397179
1,multitask_anchor_ml20_s42,42,anchor_multi_task,20,0.20,50,full_valid_ndcg@10,True,delta_next_seconds,1.0,log1p,disabled,1.000000,0.939242,1.852657,1.0,0.743154,0.807542,0.787125,7357,0.434416,0.273753,15.268044,12.0,0.291828,0.299259,0.247860,7357,0.014952,0.013136,14103.788645,97.581539,78650.533998,0.668887,0.014952,0.475194,0.977823,0.858147,2.760920,1.0,0.671713,0.743167,0.706218,7395,0.597431,0.544557,16.139148,1.0,0.558208,0.553859,0.537092,7395,0.054091,0.061878,74326.740373,7959.664375,281978.202367,0.674645,0.054091,0.406085,1.000000,0.945361,1.573844,1.0,0.847952,0.885321,0.865905,7394,0.569516,0.344874,13.489045,8.0,0.320867,0.359908,0.287454,7394,0.055991,0.025910,13106.454442,191.403947,68593.575330,0.650933,0.055991,0.470652,0.944963,0.860041,3.019337,1.0,0.661771,0.726697,0.700252,7395,0.590805,0.536444,17.605139,1.0,0.550324,0.546628,0.529333,7395,0.052062,0.051647,71862.814870,4491.248192,279634.101080,0.614199,0.052062,0.393374
2,multitask_anchor_ml20_s2024,2024,anchor_multi_task,20,0.20,50,full_valid_ndcg@10,True,delta_next_seconds,1.0,log1p,disabled,1.000000,0.995393,1.851626,1.0,0.732784,0.799277,0.797671,7380,0.392276,0.297290,13.644444,14.0,0.320801,0.310335,0.280105,7380,0.119919,0.054179,12525.380619,111.336105,72469.964842,0.663686,0.119919,0.243767,0.945636,0.808310,3.217456,1.0,0.658848,0.722638,0.678676,7413,0.592203,0.566302,19.488871,1.0,0.578897,0.570902,0.562662,7413,0.070282,0.084001,75091.483010,1279.797112,295137.219510,0.682989,0.070282,0.402536,1.000000,0.986663,1.690961,2.0,0.725305,0.795789,0.791122,7423,0.389196,0.260946,12.847636,13.0,0.303257,0.292951,0.252845,7423,0.093763,0.051914,13455.993405,207.686574,71729.470298,0.734070,0.093763,0.583187,0.946344,0.835383,3.096094,1.0,0.646032,0.714320,0.678627,7399,0.554399,0.526828,18.796729,1.0,0.544681,0.533296,0.524583,7399,0.067171,0.084986,71988.741786,3264.989735,287294.437544,0.672118,0.067171,0.400189
3,anchor_ml20_s7,7,anchor_single_task,20,0.20,32,full_valid_ndcg@10,False,None,None,None,None,1.000000,0.971918,1.430134,1.0,0.885501,0.913637,0.903861,7407,0.667438,0.484209,9.763136,6.0,0.443705,0.480200,0.420861,7346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.961857,0.883942,2.772499,1.0,0.691225,0.753294,0.729167,7367,0.661113,0.594609,15.208858,1.0,0.597937,0.601240,0.580044,7383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.956669,1.731889,1.0,0.780412,0.835623,0.822065,7385,0.544839,0.381062,11.920347,9.0,0.405286,0.414510,0.363345,7382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.960530,0.888213,2.737767,1.0,0.683248,0.747180,0.725017,7398,0.661141,0.570516,14.342799,1.0,0.586551,0.590678,0.562303,7360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,anchor_ml20_s42,42,anchor_single_task,20,0.20,32,full_valid_ndcg@10,False,None,None,None,None,1.000000,0.995781,1.344720,1.0,0.886842,0.915296,0.913814,7348,0.652470,0.473262,9.030072,6.0,0.430220,0.464891,0.406641,7349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.977546,0.848505,2.737590,1.0,0.681799,0.750367,0.708784,7393,0.654340,0.567822,14.970660,1.0,0.578433,0.583692,0.556357,7328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.995781,1.344720,1.0,0.886842,0.915296,0.913814,7348,0.652470,0.473262,9.030072,6.0,0.430220,0.464891,0.406641,7349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.977546,0.848505,2.737590,1.0,0.681799,0.750367,0.708784,7393,0.654340,0.567822,14.970660,1.0,0.578433,0.583692,0.556357,7328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,anchor_ml20_s2024,2024,anchor_single_task,20,0.20,32,full_valid_ndcg@10,False,None,None,None,None,0.999865,0.937829,1.823084,1.0,0.789072,0.840611,0.819421,7399,0.518524,0.326822,13.557322,10.0,0.292464,0.323103,0.261120,7423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.967429,0.850202,2.913055,1.0,0.668534,0.736821,0.700301,7430,0.616064,0.563197,16.282414,1.0,0.578608,0.574314,0.557801,7358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999864,0.958554,1.606876,1.0,0.865230,0.897713,0.884829,7359,0.637333,0.399919,12.026454,7.0,0.332808,0.387358,0.309534,7409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.948505,0.844293,3.025679,1.0,0.658093,0.723654,0.690190,7360,0.613248,0.554050,16.675698,1.0,0.567926,0.565817,0.547177,7382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,multitask_refine_ml50_do035_s7,7,refine_multi_task,50,0.35,50,full_valid_ndcg@10,True,delta_next_seconds,1.0,log1p,disabled,1.000000,0.838091,2.701468,2.0,0.619819,0.711474,0.657646,7356,0.268896,0.185291,21.047580,16.0,0.217592,0.200368,0.173962,7356,0.026237,0.022837,12867.716649,8.677288,79895.493810,0.615960,0.026237,0.305193,0.956292,0.712502,3.531017,1.0,0.670971,0.732565,0.655287,7367,0.612868,0.601466,22.294421,1.0,0.613268,0.604692,0.601089,7367,0.067056,0.094597,71791.261270,814.182786,279170.227263,0.769105,0.067056,0.450387,0.999864,0.996605,1.553850,1.0,0.782711,0.838354,0.837206,7363,0.524107,0.182398,12.813799,10.0,0.152033,0.214172,0.104274,7363,0.029879,0.027522,13745.783128,264.579771,64698.797325,0.689800,0.029879,0.483499,0.929870,0.828133,3.262615,1.0,0.671052,0.728034,0.696849,7372,0.619778,0.569995,18.480602,1.0,0.581505,0.579635,0.563730,7372,0.067010,0.083028,74793.730785,3982.907754,286184.771575,0.612453,0.067010,0.400977
7,multitask_refine_ml50_do035_s42,42,refine_multi_task,50,0.35,50,full_valid_ndcg@10,True,delta_next_seconds,1.0,log1p,disabled,1.000000,0.939640,2.516173,2.0,0.565251,0.673060,0.653704,7389,0.184599,0.084585,20.594668,16.0,0.136265,0.113424,0.082418,7389,0.023007,0.016782,11669.578547,58.406232,73839.383908,0.519827,0.023007,0.315469,0.968635,0.751256,3.446029,1.0,0.668249,0.733665,0.666060,7365,0.606925,0.603530,21.899389,1.0,0.614372,0.604295,0.603242,7365,0.060692,0.075838,74687.149202,698.975902,283050.310794,0.705092,0.060692,0.451052,0.997971,0.901542,2.127536,1.0,0.705348,0.777200,0.743862,7394,0.345821,0.144036,18.619015,14.0,0.151960,0.168454,0.104082,7394,0.023938,0.015615,12373.943222,76.980443,69086.004066,0.598729,0.023938,0.328510,0.957404,0.741176,3.551589,1.0,0.632860,0.705052,0.636362,7395,0.562677,0.536038,22.120622,1.0,0.549325,0.541467,0.532959,7395,0.058012,0.043391,68641.837342,1439.108608,280653.523074,0.577958,0.058012,0.399459
8,multitask_refine_ml50_do035_s2024,2024,refine_multi_task,50,0.35,50,full_valid_ndcg@10,True,delta_next_seconds,1.0,log1p,disabled,1.000000,0.973295,2.150874,2.0,0.666433,0.749001,0.739492,7377,0.359089,0.161312,18.026434,15.0,0.163382,0.182997,0.119428,7377,0.032805,0.026196,13892.641159,142.218559,76083.712405,0.609055,0.032805,0.420767,0.941862,0.805665,3.248408,1.0,0.680081,0.737569,0.692600,7379,0.619596,0.604011,19.513213,1.0,0.614094,0.606361,0.601399,7379,0.065185,0.111175,76760.182247,4485.440184,292111.312040,0.599946,0.065185,0.456701,1.000000,0.952445,1.632628,1.0,0.856683,0.891050,0.874604,7423,0.578607,0.405901,13.242624,8.0,0.391706,0.417862,0.362217,7423,0.030581,0.025305,13451.263567,124.446563,71803.668668,0.675603,0.030581,0.471912,0.919854,0.757805,3.730099,2.0,0.596464,0.667442,0.614013,7399,0.510339,0.488039,24.248277,8.0,0.501295,0.491790,0.484654,7399,0.067982,0.096633,72902.414007,4615.686349,289346.878025,0.574537,0.067982,0.396675
9,refine_ml50_do035_s7,7,refine_single_task,50,0.35,50,full_valid_ndcg@10,False,None,None,None,None,1.000000,0.957678,1.690586,1.0,0.831208,0.872416,0.859037,7372,0.656933,0.417493,12.025805,7.0,0.345750,0.403018,0.324827,7363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.961737,0.857259,3.112483,1.0,0.660451,0.728826,0.696223,7370,0.611043,0.575315,16.832724,1.0,0.581977,0.577254,0.565802,7389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.999729,1.497089,1.0,0.829215,0.872246,0.872156,7385,0.671498,0.483744,9.397047,6.0,0.427149,0.469188,0.408015,7382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.961611,0.863747,2.998378,2.0,0.634333,0.710532,0.679314,7398,0.591033,0.509918,16.715353,5.0,0.517415,0.520338,0.494720,7360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,refine_ml50_do035_s42,42,refine_single_task,50,0.35,50,full_valid_ndcg@10,False,None,None,None,None,1.000000,0.926375,1.760207,1.0,0.858375,0.891774,0.868726,7348,0.640631,0.467411,13.317594,6.0,0.419230,0.456024,0.399455,7349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.977276,0.854186,2.952928,1.0,0.663510,0.735378,0.697410,7393,0.606441,0.565093,16.592112,1.0,0.572753,0.568693,0.555385,7328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.926375,1.760207,1.0,0.858375,0.891774,0.868726,7348,0.640631,0.467411,13.317594,6.0,0.419230,0.456024,0.399455,7349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.977276,0.854186,2.952928,1.0,0.663510,0.735378,0.697410,7393,0.606441,0.565093,16.592112,1.0,0.572753,0.568693,0.555385,7328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,refine_ml50_do035_s2024,2024,refine_single_task,50,0.35,50,full_valid_ndcg@10,False,None,None,None,None,1.000000,0.850196,2.554370,1.0,0.707187,0.775861,0.727453,7403,0.431769,0.264514,19.897857,13.0,0.234183,0.257972,0.203548,7372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.992973,0.906351,2.688514,1.0,0.664353,0.741573,0.713154,7400,0.597043,0.567069,13.592567,1.0,0.582973,0.572972,0.563603,7373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.951352,1.608778,1.0,0.863615,0.896385,0.880219,7359,0.657579,0.499663,11.161695,6.0,0.460484,0.492040,0.440554,7409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974457,0.837364,3.201359,2.0,0.583494,0.674192,0.629209,7360,0.505283,0.459902,20.284747,10.0,0.471125,0.464462,0.449908,7382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
summary_metric_cols = sorted([
    c for c in df_compare.columns
    if c.startswith((
        'best_valid_',
        'best_test_at_best_valid_',
        'last_valid_',
        'last_test_',
    ))
])

summary_compare = df_compare.groupby('variant')[summary_metric_cols].agg(['mean', 'std'])
summary_compare

                   best_test_at_best_valid_full_hr@10           best_test_at_best_valid_full_hr@5           best_test_at_best_valid_full_mean_rank           best_test_at_best_valid_full_median_rank      best_test_at_best_valid_full_mrr           best_test_at_best_valid_full_ndcg@10           best_test_at_best_valid_full_ndcg@5           best_test_at_best_valid_full_num_eval_users            best_test_at_best_valid_sampled_hr@10           best_test_at_best_valid_sampled_hr@5           best_test_at_best_valid_sampled_mean_rank           best_test_at_best_valid_sampled_median_rank           best_test_at_best_valid_sampled_mrr           best_test_at_best_valid_sampled_ndcg@10           best_test_at_best_valid_sampled_ndcg@5           best_test_at_best_valid_sampled_num_eval_users            best_test_at_best_valid_task_accuracy           best_test_at_best_valid_task_macro_f1           best_test_at_best_valid_task_time_mae              best_test_at_best_valid_task_time_median_ae            best_test_at_best_valid_task_time_rmse              best_test_at_best_valid_task_top10_accuracy           best_test_at_best_valid_task_top1_accuracy           best_test_at_best_valid_task_top5_accuracy           best_valid_full_hr@10           best_valid_full_hr@5           best_valid_full_mean_rank           best_valid_full_median_rank      best_valid_full_mrr           best_valid_full_ndcg@10           best_valid_full_ndcg@5           best_valid_full_num_eval_users            best_valid_sampled_hr@10           best_valid_sampled_hr@5           best_valid_sampled_mean_rank            \
                                                 mean       std                              mean       std                                   mean       std                                     mean  std                             mean       std                                 mean       std                                mean       std                                        mean        std                                  mean       std                                 mean       std                                      mean       std                                        mean       std                                mean       std                                    mean       std                                   mean       std                                           mean        std                                  mean       std                                  mean       std                                  mean          std                                        mean        std                                   mean          std                                        mean       std                                       mean       std                                       mean       std                  mean       std                 mean       std                      mean       std                        mean  std                mean       std                    mean       std                   mean       std                           mean        std                     mean       std                    mean       std                         mean       std
variant
anchor_multi_task                            1.000000  0.000000                          0.957460  0.032859                               1.901744  0.085915                                      1.0  0.0                         0.737284  0.005319                             0.802762  0.004282                            0.789061  0.007824                                 7375.333333  16.502525                              0.423893  0.027886                             0.272136  0.026000                                 15.594324  2.131829                                   12.666667  1.154701                            0.284337  0.040730                                0.291637  0.023456                               0.243138  0.039539                                    7375.333333  16.502525                              0.053754  0.057585                              0.030433  0.021268                          12674.034845  1361.526740                                   71.948215  56.728439                           72600.274475  5986.168541                                    0.642819  0.040729                                   0.053754  0.057585                                   0.393170  0.129594              0.955038  0.019832             0.840289  0.027758                  3.034899  0.241609                         1.0  0.0            0.669601  0.009868                0.734589  0.010672               0.698776  0.017601                    7392.666667  21.594752                 0.601113  0.011214                0.558391  0.012022                    17.788444  1.675447
anchor_single_task                           0.999955  0.000078                          0.968510  0.029126                               1.532646  0.255127                                      1.0  0.0                         0.853805  0.056064                             0.889848  0.042649                            0.879032  0.051864                                 7384.666667  32.005208                              0.612810  0.081997                             0.428098  0.087878                                 10.783510  2.429994                                    7.333333  2.309401                            0.388797  0.083699                                0.422731  0.086620                               0.362874  0.088408                                    7372.666667  43.615746                                   NaN       NaN                                   NaN       NaN                                   NaN          NaN                                         NaN        NaN                                    NaN          NaN                                         NaN       NaN                                        NaN       NaN                                        NaN       NaN              0.968944  0.007954             0.860883  0.019988                  2.807715  0.092882                         1.0  0.0            0.680520  0.011400                0.746827  0.008788               0.712751  0.014836                    7396.666667  31.659648                 0.643839  0.024291                0.575209  0.016959                    15.487311  0.698803
refine_multi_task                            1.000000  0.000000                          0.917009  0.070386                               2.456172  0.280158                                      2.0  0.0                         0.617168  0.050643                             0.711178  0.037972                            0.683614  0.048432                                 7374.000000  16.703293                              0.270861  0.087262                             0.143729  0.052605                                 19.889560  1.629329                                   15.666667  0.577350                            0.172413  0.041409                                0.165596  0.046010                               0.125269  0.046051                                    7374.000000  16.703293                              0.027350  0.004993                              0.021938  0.004771                          12809.978785  1112.655423                                   69.767360  67.491660                           76606.196708  3061.675876                                    0.581614  0.053620                                   0.027350  0.004993                                   0.347143  0.063967              0.955596  0.013400             0.756474  0.046800                  3.408484  0.144997                         1.0  0.0            0.673100  0.006196                0.734600  0.002629               0.671316  0.019204                    7370.333333   7.571878                 0.613130  0.006340                0.603003  0.001352                    21.235674  1.504715
refine_single_task                           1.000000  0.000000                          0.911416  0.055280                               2.001721  0.479872                                      1.0  0.0                         0.798923  0.080599                             0.846684  0.062093                            0.818405  0.078916                                 7374.333333  27.574142                              0.576445  0.125558                             0.383139  0.105721                                 15.080419  4.221725                                    8.666667  3.785939                            0.333054  0.093175                                0.372338  0.102528                               0.309277  0.098875                                    7361.333333  11.590226                                   NaN       NaN                                   NaN       NaN                                   NaN          NaN                                         NaN        NaN                                    NaN          NaN                                         NaN       NaN                                        NaN       NaN                                        NaN       NaN              0.977329  0.015618             0.872599  0.029271                  2.917975  0.214135                         1.0  0.0            0.662771  0.002053                0.735259  0.006374               0.702263  0.009451                    7387.666667  15.695010                 0.604843  0.007136                0.569159  0.005422                    15.672468  1.805260

                   best_valid_sampled_median_rank      best_valid_sampled_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_ndcg@5           best_valid_sampled_num_eval_users            best_valid_task_accuracy           best_valid_task_macro_f1           best_valid_task_time_mae              best_valid_task_time_median_ae              best_valid_task_time_rmse              best_valid_task_top10_accuracy           best_valid_task_top1_accuracy           best_valid_task_top5_accuracy           last_test_full_hr@10           last_test_full_hr@5           last_test_full_mean_rank           last_test_full_median_rank          last_test_full_mrr           last_test_full_ndcg@10           last_test_full_ndcg@5           last_test_full_num_eval_users            last_test_sampled_hr@10           last_test_sampled_hr@5           last_test_sampled_mean_rank           last_test_sampled_median_rank           last_test_sampled_mrr           last_test_sampled_ndcg@10           last_test_sampled_ndcg@5           last_test_sampled_num_eval_users            last_test_task_accuracy           last_test_task_macro_f1           last_test_task_time_mae             last_test_task_time_median_ae             last_test_task_time_rmse              last_test_task_top10_accuracy           last_test_task_top1_accuracy           last_test_task_top5_accuracy           last_valid_full_hr@10           last_valid_full_hr@5           last_valid_full_mean_rank           last_valid_full_median_rank          last_valid_full_mrr           last_valid_full_ndcg@10            \
                                             mean  std                   mean       std                       mean       std                      mean       std                              mean        std                     mean       std                     mean       std                     mean          std                           mean          std                      mean          std                           mean       std                          mean       std                          mean       std                 mean       std                mean       std                     mean       std                       mean      std               mean       std                   mean       std                  mean       std                          mean        std                    mean       std                   mean       std                        mean       std                          mean       std                  mean       std                      mean       std                     mean       std                             mean        std                    mean       std                    mean       std                    mean         std                          mean         std                     mean          std                          mean       std                         mean       std                         mean       std                  mean       std                 mean       std                      mean       std                        mean      std                mean       std                    mean       std
variant
anchor_multi_task                             1.0  0.0               0.572275  0.012189                   0.566712  0.011354                  0.553155  0.013989                       7392.666667  21.594752                 0.062263  0.008097                 0.081022  0.017841             73565.825933  2016.808073                    3370.675769  3979.393378             288172.830437  6613.193785                       0.668149  0.018944                      0.062263  0.008097                      0.404095  0.001813             0.999955  0.000078            0.956200  0.026745                 1.843848  0.370887                   1.666667  0.57735           0.726148  0.121384               0.795308  0.090254              0.780743  0.090797                   7393.333333  30.005555                0.412241  0.147112               0.236889  0.121808                   15.302367  3.710129                     12.000000  3.605551              0.254917  0.099369                  0.264406  0.112523                 0.208670  0.107883                      7393.333333  30.005555                0.061009  0.030555                0.035594  0.014216            12935.740387  623.394732                    135.365608  111.460146              69275.45930  2194.033947                      0.659051  0.071307                     0.061009  0.030555                     0.474056  0.107470              0.943783  0.003312             0.846476  0.012513                  3.095178  0.075387                    1.000000  0.00000            0.659329  0.012260                0.724079  0.008748
anchor_single_task                            1.0  0.0               0.584993  0.011211                   0.586415  0.013668                  0.564734  0.013279                       7356.333333  27.537853                      NaN       NaN                      NaN       NaN                      NaN          NaN                            NaN          NaN                       NaN          NaN                            NaN       NaN                           NaN       NaN                           NaN       NaN             0.999955  0.000078            0.970335  0.022057                 1.561162  0.197591                   1.000000  0.00000           0.844161  0.056256               0.882877  0.041857              0.873569  0.046899                   7364.000000  19.000000                0.611547  0.058265               0.418081  0.048709                   10.992291  1.700159                      7.333333  1.527525              0.389438  0.050603                  0.422253  0.039342                 0.359840  0.048648                      7380.000000  30.049958                     NaN       NaN                     NaN       NaN                     NaN         NaN                           NaN         NaN                      NaN          NaN                           NaN       NaN                          NaN       NaN                          NaN       NaN              0.962194  0.014592             0.860337  0.024233                  2.833679  0.166278                    1.000000  0.00000            0.674380  0.014124                0.740400  0.014590
refine_multi_task                             1.0  0.0               0.613911  0.000574                   0.605116  0.001097                  0.601910  0.001164                       7370.333333   7.571878                 0.064311  0.003270                 0.093870  0.017680             74412.864240  2495.790075                    1999.532957  2153.629311             284777.283366  6641.140301                       0.691381  0.085409                      0.064311  0.003270                      0.452714  0.003470             0.999279  0.001134            0.950197  0.047571                 1.771338  0.310981                   1.000000  0.00000           0.781581  0.075674               0.835535  0.056977              0.818557  0.067336                   7393.333333  30.005555                0.482845  0.121755               0.244112  0.141420                   14.891813  3.234966                     10.666667  3.055050              0.231900  0.138396                  0.266829  0.132781                 0.190191  0.148979                      7393.333333  30.005555                0.028133  0.003649                0.022814  0.006332            13190.329972  722.184836                    155.335592   97.539613              68529.49002  3584.979793                      0.654711  0.048999                     0.028133  0.003649                     0.427973  0.086333              0.935709  0.019444             0.775705  0.046159                  3.514768  0.235907                    1.333333  0.57735            0.633459  0.037297                0.700176  0.030589
refine_single_task                            1.0  0.0               0.579235  0.005635                   0.572973  0.004280                  0.561597  0.005491                       7363.333333  31.628047                      NaN       NaN                      NaN       NaN                      NaN          NaN                            NaN          NaN                       NaN          NaN                            NaN       NaN                           NaN       NaN                           NaN       NaN             1.000000  0.000000            0.959152  0.037294                 1.622025  0.132058                   1.000000  0.00000           0.850402  0.018534               0.886802  0.012815              0.873700  0.005900                   7364.000000  19.000000                0.656569  0.015458               0.483606  0.016126                   11.292112  1.963525                      6.000000  0.000000              0.435621  0.021893                  0.472417  0.018223                 0.416008  0.021684                      7380.000000  30.049958                     NaN       NaN                     NaN       NaN                     NaN         NaN                           NaN         NaN                      NaN          NaN                           NaN       NaN                          NaN       NaN                          NaN       NaN              0.971115  0.008350             0.851766  0.013357                  3.050888  0.132278                    1.666667  0.57735            0.627112  0.040494                0.706701  0.030772

                   last_valid_full_ndcg@5           last_valid_full_num_eval_users            last_valid_sampled_hr@10           last_valid_sampled_hr@5           last_valid_sampled_mean_rank           last_valid_sampled_median_rank           last_valid_sampled_mrr           last_valid_sampled_ndcg@10           last_valid_sampled_ndcg@5           last_valid_sampled_num_eval_users            last_valid_task_accuracy           last_valid_task_macro_f1           last_valid_task_time_mae              last_valid_task_time_median_ae              last_valid_task_time_rmse              last_valid_task_top10_accuracy           last_valid_task_top1_accuracy           last_valid_task_top5_accuracy

Interpretation guide:

- compare `anchor_single_task` vs `anchor_multi_task`
- compare `refine_single_task` vs `refine_multi_task`
- use `best_test_at_best_valid_full_ndcg@10` as the main Stage 3 comparison metric
- use mean/std across `42`, `2024`, `7` for final interpretation
- task metrics are shown directly as `accuracy`, `macro_f1`, `top5_accuracy`, `top10_accuracy`, `time_mae`, `time_rmse`