# SASRec Stage 3 Refine Attention-Bias Multi-Task BPI2012 Colab Train 08

This notebook extends the Stage 3 attention-bias multi-task experiments to the
`refine_ml50_do035` backbone.

Main comparison groups:
- `refine_single_task`
- `refine_attnbias_single_task`
- `refine_multi_task_w1.0`
- `refine_attnbias_multi_task_w1.0`
- `refine_attnbias_multi_task_w0.1`

Main comparison metric:
- `full ranking + NDCG@10`

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.11.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only_stage3_v2'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10'
MULTITASK_BASELINE_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2'
MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2'
MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR:', SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR)
print('MULTITASK_BASELINE_OUTPUT_DIR:', MULTITASK_BASELINE_OUTPUT_DIR)
print('MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR:', MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR)
print('MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR:', MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR)
print('NOTEBOOK_DIR:', NOTEBOOK_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10
MULTITASK_BASELINE_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2
MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2
MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2
NOTEBOOK_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/notebooks

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR"
!mkdir -p "$MULTITASK_BASELINE_OUTPUT_DIR"
!mkdir -p "$MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR"
!mkdir -p "$MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.11.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.5)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

## Prepare Stage 3 processed dataset

This notebook regenerates the Stage 3 dataset into the versioned Drive folder
before training, so the run does not depend on any stale local processed files.

In [8]:
%cd /content/time-aware-behavior-prediction
!python scripts/regenerate_stage3_processed_dataset.py --output-dir "$DATA_DIR" --backup-existing
!ls "$DATA_DIR"

/content/time-aware-behavior-prediction
[info] moved existing output to backup: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2__backup_20260607_113944
[ok] regenerated Stage 3 processed dataset at: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2
[ok] metadata written to: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2/stage3_dataset_metadata.json
{
  "timestamp": 0,
  "delta_prev_seconds": 0,
  "delta_start_seconds": 0,
  "delta_next_seconds": 0
}
events_complete_only_filtered.csv  sasrec_interactions.csv	 user_map.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   stage3_dataset_metadata.json

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!rm -rf data/processed/bpi2012_complete_only_stage3_v2
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only_stage3_v2

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv	 user_map.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   stage3_dataset_metadata.json

In [10]:
import pandas as pd

time_features_path = 'data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv'
df = pd.read_csv(time_features_path)
required_cols = ['delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds']
missing = [c for c in required_cols if c not in df.columns]

if missing:
    raise ValueError(f'Missing required Stage 3 columns: {missing}')

print('Stage 3 processed file is ready.')
print(df.columns.tolist())
df[['user_id', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds']].head()

Stage 3 processed file is ready.
['case_id', 'activity', 'lifecycle', 'timestamp', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds', 'user_id', 'item_id']

,user_id,event_idx,delta_prev_seconds,delta_start_seconds,delta_next_seconds
0,1,0,0.000,0.000,0.334
1,1,1,0.334,0.334,53.026
2,1,2,53.026,53.360,39785.402
3,1,3,39785.402,39838.762,145.935
4,1,4,145.935,39984.697,-0.000

## Experiment design

This notebook tests the `refine_ml50_do035` backbone with:
- single-task attention bias (`Stage 2` reference)
- multi-task attention bias with `time_loss_weight=1.0`
- multi-task attention bias with `time_loss_weight=0.1`

Fixed settings:
- backbone: `refine_ml50_do035`
- time-aware backbone: `delta_start + 9-bucket attention bias`
- multi-task outputs: `next activity + next time`
- time target: `delta_next_seconds`
- time target transform: `log1p`
- time loss: `huber`
- best epoch criterion: `full_valid_ndcg@10`
- final comparison uses all 3 seeds: `42`, `2024`, `7`

## Check prerequisite reference runs

In [11]:
from pathlib import Path

baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
single_task_attnbias_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]
multitask_baseline_runs = [
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]

checks = [
    ('baseline', BASELINE_NDCG10_OUTPUT_DIR, baseline_runs),
    ('single-task attention bias', SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR, single_task_attnbias_runs),
    ('multi-task baseline', MULTITASK_BASELINE_OUTPUT_DIR, multitask_baseline_runs),
]

print('=' * 80)
for label, output_dir, run_names in checks:
    print(label)
    base = Path(output_dir)
    for run_name in run_names:
        run_dir = base / run_name
        print(' ', run_name, 'EXISTS' if run_dir.exists() else 'MISSING')
    print('-' * 80)

================================================================================
baseline
  refine_ml50_do035_s42 EXISTS
  refine_ml50_do035_s2024 EXISTS
  refine_ml50_do035_s7 EXISTS
--------------------------------------------------------------------------------
single-task attention bias
  attnbias_dstart_ml50_do035_b9_s42 EXISTS
  attnbias_dstart_ml50_do035_b9_s2024 EXISTS
  attnbias_dstart_ml50_do035_b9_s7 EXISTS
--------------------------------------------------------------------------------
multi-task baseline
  multitask_refine_ml50_do035_s42 EXISTS
  multitask_refine_ml50_do035_s2024 EXISTS
  multitask_refine_ml50_do035_s7 EXISTS
--------------------------------------------------------------------------------

## Check planned refine attention-bias multi-task runs

In [12]:
planned_attnbias_multitask_runs = [
    'multitask_attnbias_dstart_ml50_do035_b9_s42',
    'multitask_attnbias_dstart_ml50_do035_b9_s2024',
    'multitask_attnbias_dstart_ml50_do035_b9_s7',
    'multitask_attnbias_dstart_ml50_do035_b9_w01_s42',
    'multitask_attnbias_dstart_ml50_do035_b9_w01_s2024',
    'multitask_attnbias_dstart_ml50_do035_b9_w01_s7',
]

checks = [
    ('w1.0', MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR),
    ('w0.1', MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR),
]

for label, output_dir in checks:
    base = Path(output_dir)
    print('=' * 80)
    print(f'Stage 3 refine attention-bias multi-task runs ({label})')
    for run_name in planned_attnbias_multitask_runs:
        if (label == 'w1.0' and '_w01_' in run_name) or (label == 'w0.1' and '_w01_' not in run_name):
            continue
        run_dir = base / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Stage 3 refine attention-bias multi-task runs (w1.0)
multitask_attnbias_dstart_ml50_do035_b9_s42 EXISTS
multitask_attnbias_dstart_ml50_do035_b9_s2024 EXISTS
multitask_attnbias_dstart_ml50_do035_b9_s7 EXISTS
================================================================================
Stage 3 refine attention-bias multi-task runs (w0.1)
multitask_attnbias_dstart_ml50_do035_b9_w01_s42 EXISTS
multitask_attnbias_dstart_ml50_do035_b9_w01_s2024 EXISTS
multitask_attnbias_dstart_ml50_do035_b9_w01_s7 OK

## Train refine attention-bias multi-task w1.0 runs

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_attnbias_dstart_ml50_do035_b9_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42
epoch=1, loss=3.0479
epoch=2, loss=1.7479
epoch=3, loss=1.5749
epoch=4, loss=1.4773
epoch=5, loss=1.4232
valid [task], Top5Acc: 0.4741, Top10Acc: 0.7317, Acc: 0.0583, MacroF1: 0.0782, TimeMAE: 69475.7882, TimeRMSE: 277601.1101, TimeMedAE: 860.2867
valid [full], NDCG@5: 0.5947, HR@5: 0.6861, NDCG@10: 0.6972, HR@10: 0.9948, MRR: 0.6097
valid [sampled], NDCG@5: 0.5151, HR@5: 0.5159, NDCG@10: 0.5188, HR@10: 0.5278, MRR: 0.5309
test [task], Top5Acc: 0.0536, Top10Acc: 0.4662, Acc: 0.0118, MacroF1: 0.0116, TimeMAE: 11466.2591, TimeRMSE: 82258.5313, TimeMedAE: 4.6117
test [full], NDCG@5: 0.5533, HR@5: 0.7788, NDCG@10: 0.6156, HR@10: 0.9667, MRR: 0.5128
test [sampled], NDCG@5: 0.0850, HR@5: 0.0888, NDCG@10: 0.1068, HR@10: 0.1587, MRR: 0.1268
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=6, loss=1.3933
epoch=7, loss=1.3601
epoch=8, loss=1.3426
epoch=9, loss=1.3308
epoch=10, loss=1.2924
valid [task], Top5Acc: 0.5349, Top10Acc: 0.7693, Acc: 0.0609, MacroF1: 0.0702, TimeMAE: 69622.6657, TimeRMSE: 282426.5732, TimeMedAE: 820.3120
valid [full], NDCG@5: 0.6591, HR@5: 0.7389, NDCG@10: 0.7380, HR@10: 0.9849, MRR: 0.6673
valid [sampled], NDCG@5: 0.5968, HR@5: 0.5976, NDCG@10: 0.5988, HR@10: 0.6040, MRR: 0.6087
test [task], Top5Acc: 0.2881, Top10Acc: 0.3995, Acc: 0.0115, MacroF1: 0.0099, TimeMAE: 12274.7833, TimeRMSE: 81620.2614, TimeMedAE: 17.2527
test [full], NDCG@5: 0.6520, HR@5: 0.7808, NDCG@10: 0.7253, HR@10: 1.0000, MRR: 0.6407
test [sampled], NDCG@5: 0.1196, HR@5: 0.1576, NDCG@10: 0.1751, HR@10: 0.3313, MRR: 0.1580
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=11, loss=1.2651
epoch=12, loss=1.2439
epoch=13, loss=1.2149
epoch=14, loss=1.2150
epoch=15, loss=1.1996
valid [task], Top5Acc: 0.5499, Top10Acc: 0.7286, Acc: 0.0612, MacroF1: 0.0852, TimeMAE: 71356.9482, TimeRMSE: 282275.5501, TimeMedAE: 814.2499
valid [full], NDCG@5: 0.6720, HR@5: 0.7521, NDCG@10: 0.7402, HR@10: 0.9682, MRR: 0.6763
valid [sampled], NDCG@5: 0.6073, HR@5: 0.6076, NDCG@10: 0.6098, HR@10: 0.6158, MRR: 0.6194
test [task], Top5Acc: 0.0932, Top10Acc: 0.5952, Acc: 0.0146, MacroF1: 0.0144, TimeMAE: 11370.9387, TimeRMSE: 75045.2463, TimeMedAE: 49.4418
test [full], NDCG@5: 0.6266, HR@5: 0.8643, NDCG@10: 0.6721, HR@10: 1.0000, MRR: 0.5683
test [sampled], NDCG@5: 0.1798, HR@5: 0.1805, NDCG@10: 0.1887, HR@10: 0.2092, MRR: 0.2213
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=16, loss=1.1899
epoch=17, loss=1.1772
epoch=18, loss=1.1809
epoch=19, loss=1.1683
epoch=20, loss=1.1551
valid [task], Top5Acc: 0.4524, Top10Acc: 0.7259, Acc: 0.0659, MacroF1: 0.0960, TimeMAE: 73527.1822, TimeRMSE: 282519.9768, TimeMedAE: 890.2198
valid [full], NDCG@5: 0.6659, HR@5: 0.7391, NDCG@10: 0.7393, HR@10: 0.9686, MRR: 0.6749
valid [sampled], NDCG@5: 0.6054, HR@5: 0.6058, NDCG@10: 0.6074, HR@10: 0.6124, MRR: 0.6174
test [task], Top5Acc: 0.3351, Top10Acc: 0.6104, Acc: 0.0195, MacroF1: 0.0182, TimeMAE: 12239.1981, TimeRMSE: 72188.4761, TimeMedAE: 80.3534
test [full], NDCG@5: 0.7894, HR@5: 0.9490, NDCG@10: 0.8058, HR@10: 1.0000, MRR: 0.7433
test [sampled], NDCG@5: 0.2078, HR@5: 0.2414, NDCG@10: 0.2578, HR@10: 0.3971, MRR: 0.2483
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.1608
epoch=22, loss=1.1587
epoch=23, loss=1.1345
epoch=24, loss=1.1298
epoch=25, loss=1.1238
valid [task], Top5Acc: 0.4549, Top10Acc: 0.5928, Acc: 0.0704, MacroF1: 0.0858, TimeMAE: 73304.9609, TimeRMSE: 292124.9071, TimeMedAE: 916.5903
valid [full], NDCG@5: 0.6736, HR@5: 0.7522, NDCG@10: 0.7415, HR@10: 0.9695, MRR: 0.6776
valid [sampled], NDCG@5: 0.6076, HR@5: 0.6080, NDCG@10: 0.6109, HR@10: 0.6188, MRR: 0.6199
test [task], Top5Acc: 0.3258, Top10Acc: 0.6229, Acc: 0.0272, MacroF1: 0.0259, TimeMAE: 11795.9460, TimeRMSE: 73596.1862, TimeMedAE: 72.6279
test [full], NDCG@5: 0.7951, HR@5: 0.9497, NDCG@10: 0.8118, HR@10: 1.0000, MRR: 0.7517
test [sampled], NDCG@5: 0.2257, HR@5: 0.2616, NDCG@10: 0.2771, HR@10: 0.4216, MRR: 0.2643
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=26, loss=1.1096
epoch=27, loss=1.1050
epoch=28, loss=1.1043
epoch=29, loss=1.0992
epoch=30, loss=1.0953
valid [task], Top5Acc: 0.4469, Top10Acc: 0.5920, Acc: 0.0673, MacroF1: 0.0854, TimeMAE: 74514.9759, TimeRMSE: 284520.2079, TimeMedAE: 1400.8798
valid [full], NDCG@5: 0.6624, HR@5: 0.7401, NDCG@10: 0.7323, HR@10: 0.9540, MRR: 0.6701
valid [sampled], NDCG@5: 0.5921, HR@5: 0.5949, NDCG@10: 0.5988, HR@10: 0.6160, MRR: 0.6051
test [task], Top5Acc: 0.3187, Top10Acc: 0.6394, Acc: 0.0310, MacroF1: 0.0261, TimeMAE: 11911.7988, TimeRMSE: 76389.8802, TimeMedAE: 115.3789
test [full], NDCG@5: 0.8022, HR@5: 0.9609, NDCG@10: 0.8155, HR@10: 0.9999, MRR: 0.7561
test [sampled], NDCG@5: 0.2111, HR@5: 0.2433, NDCG@10: 0.2667, HR@10: 0.4162, MRR: 0.2541
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.0961
epoch=32, loss=1.0906
epoch=33, loss=1.0934
epoch=34, loss=1.0849
epoch=35, loss=1.0851
valid [task], Top5Acc: 0.4566, Top10Acc: 0.6419, Acc: 0.0619, MacroF1: 0.0799, TimeMAE: 70299.4506, TimeRMSE: 281214.7312, TimeMedAE: 1427.8252
valid [full], NDCG@5: 0.7056, HR@5: 0.8364, NDCG@10: 0.7484, HR@10: 0.9689, MRR: 0.6841
valid [sampled], NDCG@5: 0.5972, HR@5: 0.5990, NDCG@10: 0.6026, HR@10: 0.6160, MRR: 0.6119
test [task], Top5Acc: 0.3185, Top10Acc: 0.6673, Acc: 0.0236, MacroF1: 0.0197, TimeMAE: 11338.9883, TimeRMSE: 72120.0574, TimeMedAE: 75.2898
test [full], NDCG@5: 0.7800, HR@5: 0.9757, NDCG@10: 0.7885, HR@10: 1.0000, MRR: 0.7192
test [sampled], NDCG@5: 0.2106, HR@5: 0.2469, NDCG@10: 0.2640, HR@10: 0.4139, MRR: 0.2493
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=36, loss=1.0899
epoch=37, loss=1.0809
epoch=38, loss=1.0714
epoch=39, loss=1.0895
epoch=40, loss=1.0787
valid [task], Top5Acc: 0.4047, Top10Acc: 0.5831, Acc: 0.0636, MacroF1: 0.1047, TimeMAE: 70107.1002, TimeRMSE: 271269.0116, TimeMedAE: 863.6860
valid [full], NDCG@5: 0.6462, HR@5: 0.7390, NDCG@10: 0.7159, HR@10: 0.9521, MRR: 0.6498
valid [sampled], NDCG@5: 0.5649, HR@5: 0.5700, NDCG@10: 0.5750, HR@10: 0.6014, MRR: 0.5788
test [task], Top5Acc: 0.2817, Top10Acc: 0.6232, Acc: 0.0284, MacroF1: 0.0247, TimeMAE: 10637.4711, TimeRMSE: 65954.8264, TimeMedAE: 74.0006
test [full], NDCG@5: 0.7583, HR@5: 0.8943, NDCG@10: 0.7945, HR@10: 1.0000, MRR: 0.7289
test [sampled], NDCG@5: 0.1866, HR@5: 0.2273, NDCG@10: 0.2457, HR@10: 0.4119, MRR: 0.2272
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.0769
epoch=42, loss=1.0769
epoch=43, loss=1.0834
epoch=44, loss=1.0813
epoch=45, loss=1.0805
valid [task], Top5Acc: 0.4235, Top10Acc: 0.6875, Acc: 0.0678, MacroF1: 0.1100, TimeMAE: 73991.0401, TimeRMSE: 282518.5612, TimeMedAE: 3558.6259
valid [full], NDCG@5: 0.7037, HR@5: 0.8460, NDCG@10: 0.7379, HR@10: 0.9530, MRR: 0.6758
valid [sampled], NDCG@5: 0.5822, HR@5: 0.5863, NDCG@10: 0.5899, HR@10: 0.6104, MRR: 0.5972
test [task], Top5Acc: 0.3414, Top10Acc: 0.6963, Acc: 0.0317, MacroF1: 0.0282, TimeMAE: 14152.4957, TimeRMSE: 72957.4469, TimeMedAE: 100.3974
test [full], NDCG@5: 0.7419, HR@5: 0.9821, NDCG@10: 0.7480, HR@10: 1.0000, MRR: 0.6628
test [sampled], NDCG@5: 0.1883, HR@5: 0.1997, NDCG@10: 0.2263, HR@10: 0.3206, MRR: 0.2376
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.0693
epoch=47, loss=1.0731
epoch=48, loss=1.0684
epoch=49, loss=1.0702
epoch=50, loss=1.0591
valid [task], Top5Acc: 0.4196, Top10Acc: 0.7021, Acc: 0.0653, MacroF1: 0.0993, TimeMAE: 69466.4794, TimeRMSE: 277741.6235, TimeMedAE: 3273.2635
valid [full], NDCG@5: 0.6659, HR@5: 0.8492, NDCG@10: 0.6994, HR@10: 0.9540, MRR: 0.6239
valid [sampled], NDCG@5: 0.4959, HR@5: 0.5005, NDCG@10: 0.5047, HR@10: 0.5279, MRR: 0.5142
test [task], Top5Acc: 0.3157, Top10Acc: 0.6796, Acc: 0.0312, MacroF1: 0.0263, TimeMAE: 12807.3738, TimeRMSE: 68230.3778, TimeMedAE: 79.5035
test [full], NDCG@5: 0.7931, HR@5: 0.9931, NDCG@10: 0.7954, HR@10: 1.0000, MRR: 0.7266
test [sampled], NDCG@5: 0.2056, HR@5: 0.2309, NDCG@10: 0.2554, HR@10: 0.3877, MRR: 0.2516
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s42/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_attnbias_dstart_ml50_do035_b9_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024
epoch=1, loss=2.8451
epoch=2, loss=1.7460
epoch=3, loss=1.5668
epoch=4, loss=1.4792
epoch=5, loss=1.4259
valid [task], Top5Acc: 0.3531, Top10Acc: 0.6957, Acc: 0.0551, MacroF1: 0.0869, TimeMAE: 74203.5075, TimeRMSE: 290869.9884, TimeMedAE: 814.5342
valid [full], NDCG@5: 0.5915, HR@5: 0.6823, NDCG@10: 0.6608, HR@10: 0.8996, MRR: 0.5998
valid [sampled], NDCG@5: 0.5190, HR@5: 0.5192, NDCG@10: 0.5213, HR@10: 0.5266, MRR: 0.5326
test [task], Top5Acc: 0.2959, Top10Acc: 0.6225, Acc: 0.0149, MacroF1: 0.0150, TimeMAE: 13255.5605, TimeRMSE: 81388.0988, TimeMedAE: 111.3771
test [full], NDCG@5: 0.6721, HR@5: 0.8901, NDCG@10: 0.7018, HR@10: 0.9811, MRR: 0.6127
test [sampled], NDCG@5: 0.1570, HR@5: 0.1622, NDCG@10: 0.1859, HR@10: 0.2553, MRR: 0.2058
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=6, loss=1.3765
epoch=7, loss=1.3534
epoch=8, loss=1.3331
epoch=9, loss=1.3102
epoch=10, loss=1.3082
valid [task], Top5Acc: 0.4232, Top10Acc: 0.7306, Acc: 0.0558, MacroF1: 0.0325, TimeMAE: 68640.0091, TimeRMSE: 274463.3095, TimeMedAE: 710.2910
valid [full], NDCG@5: 0.6637, HR@5: 0.7678, NDCG@10: 0.7116, HR@10: 0.9225, MRR: 0.6563
valid [sampled], NDCG@5: 0.5788, HR@5: 0.5798, NDCG@10: 0.5828, HR@10: 0.5922, MRR: 0.5918
test [task], Top5Acc: 0.3114, Top10Acc: 0.4437, Acc: 0.0080, MacroF1: 0.0048, TimeMAE: 12086.3126, TimeRMSE: 75683.7825, TimeMedAE: 8.8715
test [full], NDCG@5: 0.6004, HR@5: 0.6848, NDCG@10: 0.7000, HR@10: 0.9893, MRR: 0.6154
test [sampled], NDCG@5: 0.0886, HR@5: 0.1266, NDCG@10: 0.1394, HR@10: 0.2846, MRR: 0.1258
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=11, loss=1.2959
epoch=12, loss=1.2875
epoch=13, loss=1.2781
epoch=14, loss=1.2659
epoch=15, loss=1.2631
valid [task], Top5Acc: 0.5446, Top10Acc: 0.6813, Acc: 0.0602, MacroF1: 0.0368, TimeMAE: 70222.1100, TimeRMSE: 283761.5516, TimeMedAE: 800.5836
valid [full], NDCG@5: 0.6596, HR@5: 0.7289, NDCG@10: 0.7304, HR@10: 0.9526, MRR: 0.6700
valid [sampled], NDCG@5: 0.6085, HR@5: 0.6091, NDCG@10: 0.6101, HR@10: 0.6143, MRR: 0.6186
test [task], Top5Acc: 0.3131, Top10Acc: 0.5146, Acc: 0.0150, MacroF1: 0.0112, TimeMAE: 11756.6710, TimeRMSE: 79037.5732, TimeMedAE: 10.8822
test [full], NDCG@5: 0.5784, HR@5: 0.8589, NDCG@10: 0.6244, HR@10: 1.0000, MRR: 0.5010
test [sampled], NDCG@5: 0.0791, HR@5: 0.0868, NDCG@10: 0.1087, HR@10: 0.1810, MRR: 0.1272
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=16, loss=1.2555
epoch=17, loss=1.2440
epoch=18, loss=1.2423
epoch=19, loss=1.2458
epoch=20, loss=1.2337
valid [task], Top5Acc: 0.5197, Top10Acc: 0.6920, Acc: 0.0624, MacroF1: 0.0356, TimeMAE: 73981.5738, TimeRMSE: 291715.9425, TimeMedAE: 925.3019
valid [full], NDCG@5: 0.6743, HR@5: 0.7587, NDCG@10: 0.7370, HR@10: 0.9521, MRR: 0.6777
valid [sampled], NDCG@5: 0.6129, HR@5: 0.6131, NDCG@10: 0.6139, HR@10: 0.6164, MRR: 0.6235
test [task], Top5Acc: 0.3259, Top10Acc: 0.5206, Acc: 0.0156, MacroF1: 0.0105, TimeMAE: 11851.1579, TimeRMSE: 72819.2742, TimeMedAE: 3.8668
test [full], NDCG@5: 0.7115, HR@5: 0.9357, NDCG@10: 0.7339, HR@10: 1.0000, MRR: 0.6470
test [sampled], NDCG@5: 0.1389, HR@5: 0.1785, NDCG@10: 0.2004, HR@10: 0.3703, MRR: 0.1792
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=21, loss=1.2205
epoch=22, loss=1.2006
epoch=23, loss=1.1757
epoch=24, loss=1.1763
epoch=25, loss=1.1658
valid [task], Top5Acc: 0.4548, Top10Acc: 0.7352, Acc: 0.0570, MacroF1: 0.0332, TimeMAE: 71472.8200, TimeRMSE: 286655.2201, TimeMedAE: 1553.2838
valid [full], NDCG@5: 0.6687, HR@5: 0.7624, NDCG@10: 0.7367, HR@10: 0.9687, MRR: 0.6706
valid [sampled], NDCG@5: 0.5947, HR@5: 0.5968, NDCG@10: 0.5986, HR@10: 0.6091, MRR: 0.6070
test [task], Top5Acc: 0.5020, Top10Acc: 0.5990, Acc: 0.0225, MacroF1: 0.0126, TimeMAE: 13532.8817, TimeRMSE: 79026.6061, TimeMedAE: 142.8151
test [full], NDCG@5: 0.6620, HR@5: 0.9310, NDCG@10: 0.6855, HR@10: 0.9999, MRR: 0.5793
test [sampled], NDCG@5: 0.1518, HR@5: 0.1647, NDCG@10: 0.1983, HR@10: 0.3124, MRR: 0.2007
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1595
epoch=27, loss=1.1509
epoch=28, loss=1.1503
epoch=29, loss=1.1471
epoch=30, loss=1.1342
valid [task], Top5Acc: 0.4513, Top10Acc: 0.7080, Acc: 0.0599, MacroF1: 0.0397, TimeMAE: 78572.1059, TimeRMSE: 291972.4783, TimeMedAE: 10619.7513
valid [full], NDCG@5: 0.6882, HR@5: 0.8076, NDCG@10: 0.7395, HR@10: 0.9695, MRR: 0.6730
valid [sampled], NDCG@5: 0.5843, HR@5: 0.5883, NDCG@10: 0.5922, HR@10: 0.6130, MRR: 0.5985
test [task], Top5Acc: 0.6089, Top10Acc: 0.6335, Acc: 0.1173, MacroF1: 0.0461, TimeMAE: 15157.5162, TimeRMSE: 76170.3747, TimeMedAE: 108.4949
test [full], NDCG@5: 0.7748, HR@5: 0.9535, NDCG@10: 0.7905, HR@10: 0.9999, MRR: 0.7211
test [sampled], NDCG@5: 0.2235, HR@5: 0.2715, NDCG@10: 0.2979, HR@10: 0.5025, MRR: 0.2597
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=31, loss=1.1490
epoch=32, loss=1.1313
epoch=33, loss=1.1428
epoch=34, loss=1.1310
epoch=35, loss=1.1402
valid [task], Top5Acc: 0.4549, Top10Acc: 0.7650, Acc: 0.0565, MacroF1: 0.0389, TimeMAE: 71008.3432, TimeRMSE: 288257.2652, TimeMedAE: 3963.8022
valid [full], NDCG@5: 0.6974, HR@5: 0.8426, NDCG@10: 0.7369, HR@10: 0.9690, MRR: 0.6686
valid [sampled], NDCG@5: 0.5627, HR@5: 0.5686, NDCG@10: 0.5759, HR@10: 0.6099, MRR: 0.5797
test [task], Top5Acc: 0.5024, Top10Acc: 0.6523, Acc: 0.0833, MacroF1: 0.0335, TimeMAE: 13323.3162, TimeRMSE: 82686.1730, TimeMedAE: 25.7235
test [full], NDCG@5: 0.8083, HR@5: 0.9423, NDCG@10: 0.8279, HR@10: 1.0000, MRR: 0.7711
test [sampled], NDCG@5: 0.2922, HR@5: 0.3428, NDCG@10: 0.3570, HR@10: 0.5429, MRR: 0.3215
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1331
epoch=37, loss=1.1329
epoch=38, loss=1.1343
epoch=39, loss=1.1249
epoch=40, loss=1.1226
valid [task], Top5Acc: 0.4551, Top10Acc: 0.6022, Acc: 0.0598, MacroF1: 0.0544, TimeMAE: 79833.6450, TimeRMSE: 295736.0821, TimeMedAE: 11040.2012
valid [full], NDCG@5: 0.6746, HR@5: 0.8018, NDCG@10: 0.7227, HR@10: 0.9528, MRR: 0.6574
valid [sampled], NDCG@5: 0.5656, HR@5: 0.5706, NDCG@10: 0.5757, HR@10: 0.6022, MRR: 0.5804
test [task], Top5Acc: 0.5817, Top10Acc: 0.6354, Acc: 0.2084, MacroF1: 0.0605, TimeMAE: 15516.7615, TimeRMSE: 73363.5357, TimeMedAE: 68.0614
test [full], NDCG@5: 0.8123, HR@5: 0.9343, NDCG@10: 0.8344, HR@10: 1.0000, MRR: 0.7805
test [sampled], NDCG@5: 0.3515, HR@5: 0.3923, NDCG@10: 0.4043, HR@10: 0.5565, MRR: 0.3785
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.1277
epoch=42, loss=1.1211
epoch=43, loss=1.1279
epoch=44, loss=1.1219
epoch=45, loss=1.1163
valid [task], Top5Acc: 0.4584, Top10Acc: 0.6583, Acc: 0.0571, MacroF1: 0.0357, TimeMAE: 77913.8319, TimeRMSE: 288998.3758, TimeMedAE: 6040.6781
valid [full], NDCG@5: 0.7019, HR@5: 0.8494, NDCG@10: 0.7341, HR@10: 0.9514, MRR: 0.6715
valid [sampled], NDCG@5: 0.5775, HR@5: 0.5813, NDCG@10: 0.5870, HR@10: 0.6110, MRR: 0.5933
test [task], Top5Acc: 0.6098, Top10Acc: 0.6555, Acc: 0.0678, MacroF1: 0.0349, TimeMAE: 13738.6665, TimeRMSE: 72191.9975, TimeMedAE: 42.1435
test [full], NDCG@5: 0.7984, HR@5: 0.9134, NDCG@10: 0.8268, HR@10: 1.0000, MRR: 0.7709
test [sampled], NDCG@5: 0.3168, HR@5: 0.3619, NDCG@10: 0.3774, HR@10: 0.5489, MRR: 0.3455
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1117
epoch=47, loss=1.1159
epoch=48, loss=1.1182
epoch=49, loss=1.1085
epoch=50, loss=1.1105
valid [task], Top5Acc: 0.4115, Top10Acc: 0.5932, Acc: 0.0626, MacroF1: 0.0465, TimeMAE: 77629.2301, TimeRMSE: 290988.6142, TimeMedAE: 5850.5917
valid [full], NDCG@5: 0.6560, HR@5: 0.7704, NDCG@10: 0.7196, HR@10: 0.9686, MRR: 0.6481
valid [sampled], NDCG@5: 0.5609, HR@5: 0.5651, NDCG@10: 0.5694, HR@10: 0.5917, MRR: 0.5754
test [task], Top5Acc: 0.5775, Top10Acc: 0.6232, Acc: 0.0432, MacroF1: 0.0258, TimeMAE: 14410.3072, TimeRMSE: 69416.4046, TimeMedAE: 69.6504
test [full], NDCG@5: 0.7722, HR@5: 0.9042, NDCG@10: 0.8040, HR@10: 1.0000, MRR: 0.7405
test [sampled], NDCG@5: 0.2093, HR@5: 0.2692, NDCG@10: 0.2903, HR@10: 0.5204, MRR: 0.2447
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s2024/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_attnbias_dstart_ml50_do035_b9_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7
epoch=1, loss=3.2969
epoch=2, loss=1.7796
epoch=3, loss=1.6205
epoch=4, loss=1.5294
epoch=5, loss=1.4809
valid [task], Top5Acc: 0.2969, Top10Acc: 0.6944, Acc: 0.0502, MacroF1: 0.0859, TimeMAE: 71546.4460, TimeRMSE: 290715.7656, TimeMedAE: 2032.2478
valid [full], NDCG@5: 0.4900, HR@5: 0.6359, NDCG@10: 0.6047, HR@10: 0.9778, MRR: 0.4927
valid [sampled], NDCG@5: 0.3358, HR@5: 0.3615, NDCG@10: 0.3722, HR@10: 0.4751, MRR: 0.3582
test [task], Top5Acc: 0.1844, Top10Acc: 0.6760, Acc: 0.0410, MacroF1: 0.0416, TimeMAE: 14042.6985, TimeRMSE: 88814.2607, TimeMedAE: 23.2417
test [full], NDCG@5: 0.6887, HR@5: 0.9216, NDCG@10: 0.7163, HR@10: 1.0000, MRR: 0.6245
test [sampled], NDCG@5: 0.1525, HR@5: 0.1598, NDCG@10: 0.1796, HR@10: 0.2463, MRR: 0.2007
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=6, loss=1.4300
epoch=7, loss=1.4026
epoch=8, loss=1.3686
epoch=9, loss=1.3428
epoch=10, loss=1.3196
valid [task], Top5Acc: 0.3377, Top10Acc: 0.7144, Acc: 0.0618, MacroF1: 0.0484, TimeMAE: 70526.3849, TimeRMSE: 291655.9920, TimeMedAE: 1018.8657
valid [full], NDCG@5: 0.6016, HR@5: 0.6878, NDCG@10: 0.6877, HR@10: 0.9585, MRR: 0.6117
valid [sampled], NDCG@5: 0.5180, HR@5: 0.5224, NDCG@10: 0.5266, HR@10: 0.5495, MRR: 0.5329
test [task], Top5Acc: 0.1556, Top10Acc: 0.5727, Acc: 0.0286, MacroF1: 0.0204, TimeMAE: 12901.3431, TimeRMSE: 84915.5249, TimeMedAE: 9.5236
test [full], NDCG@5: 0.5842, HR@5: 0.7515, NDCG@10: 0.6675, HR@10: 0.9978, MRR: 0.5648
test [sampled], NDCG@5: 0.1559, HR@5: 0.1646, NDCG@10: 0.1779, HR@10: 0.2349, MRR: 0.1974
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=11, loss=1.2896
epoch=12, loss=1.2659
epoch=13, loss=1.2327
epoch=14, loss=1.2221
epoch=15, loss=1.2082
valid [task], Top5Acc: 0.4040, Top10Acc: 0.7330, Acc: 0.0630, MacroF1: 0.0566, TimeMAE: 70927.1670, TimeRMSE: 282818.9045, TimeMedAE: 1053.4493
valid [full], NDCG@5: 0.6221, HR@5: 0.6955, NDCG@10: 0.7025, HR@10: 0.9514, MRR: 0.6344
valid [sampled], NDCG@5: 0.5533, HR@5: 0.5556, NDCG@10: 0.5590, HR@10: 0.5734, MRR: 0.5665
test [task], Top5Acc: 0.0979, Top10Acc: 0.6868, Acc: 0.0144, MacroF1: 0.0101, TimeMAE: 12673.1170, TimeRMSE: 83936.2881, TimeMedAE: 11.4311
test [full], NDCG@5: 0.5927, HR@5: 0.7959, NDCG@10: 0.6618, HR@10: 0.9988, MRR: 0.5563
test [sampled], NDCG@5: 0.1598, HR@5: 0.1620, NDCG@10: 0.1722, HR@10: 0.2021, MRR: 0.2017
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=16, loss=1.1881
epoch=17, loss=1.1843
epoch=18, loss=1.1728
epoch=19, loss=1.1707
epoch=20, loss=1.1669
valid [task], Top5Acc: 0.4426, Top10Acc: 0.5737, Acc: 0.0667, MacroF1: 0.0515, TimeMAE: 72420.5515, TimeRMSE: 292791.3401, TimeMedAE: 2484.8705
valid [full], NDCG@5: 0.6430, HR@5: 0.7131, NDCG@10: 0.7180, HR@10: 0.9458, MRR: 0.6562
valid [sampled], NDCG@5: 0.5837, HR@5: 0.5860, NDCG@10: 0.5890, HR@10: 0.6027, MRR: 0.5954
test [task], Top5Acc: 0.1445, Top10Acc: 0.6181, Acc: 0.0254, MacroF1: 0.0190, TimeMAE: 13209.6565, TimeRMSE: 86697.0660, TimeMedAE: 91.6561
test [full], NDCG@5: 0.6570, HR@5: 0.9341, NDCG@10: 0.6785, HR@10: 0.9977, MRR: 0.5754
test [sampled], NDCG@5: 0.1640, HR@5: 0.1657, NDCG@10: 0.1810, HR@10: 0.2207, MRR: 0.2096
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=21, loss=1.1645
epoch=22, loss=1.1548
epoch=23, loss=1.1578
epoch=24, loss=1.1529
epoch=25, loss=1.1502
valid [task], Top5Acc: 0.3940, Top10Acc: 0.6064, Acc: 0.0642, MacroF1: 0.0543, TimeMAE: 69849.7904, TimeRMSE: 280340.1089, TimeMedAE: 2552.9653
valid [full], NDCG@5: 0.7012, HR@5: 0.8410, NDCG@10: 0.7411, HR@10: 0.9681, MRR: 0.6749
valid [sampled], NDCG@5: 0.5846, HR@5: 0.5875, NDCG@10: 0.5899, HR@10: 0.6042, MRR: 0.5991
test [task], Top5Acc: 0.3829, Top10Acc: 0.6177, Acc: 0.0280, MacroF1: 0.0227, TimeMAE: 12280.7781, TimeRMSE: 76506.9433, TimeMedAE: 301.3679
test [full], NDCG@5: 0.7241, HR@5: 0.9782, NDCG@10: 0.7300, HR@10: 0.9953, MRR: 0.6407
test [sampled], NDCG@5: 0.1611, HR@5: 0.1651, NDCG@10: 0.1980, HR@10: 0.2833, MRR: 0.2149
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=26, loss=1.1428
epoch=27, loss=1.1558
epoch=28, loss=1.1311
epoch=29, loss=1.1353
epoch=30, loss=1.1284
valid [task], Top5Acc: 0.4388, Top10Acc: 0.6316, Acc: 0.0613, MacroF1: 0.0772, TimeMAE: 72577.0831, TimeRMSE: 284084.3707, TimeMedAE: 2632.7747
valid [full], NDCG@5: 0.6740, HR@5: 0.8027, NDCG@10: 0.7265, HR@10: 0.9674, MRR: 0.6563
valid [sampled], NDCG@5: 0.5548, HR@5: 0.5583, NDCG@10: 0.5627, HR@10: 0.5832, MRR: 0.5707
test [task], Top5Acc: 0.4310, Top10Acc: 0.6182, Acc: 0.0191, MacroF1: 0.0174, TimeMAE: 12472.0527, TimeRMSE: 80819.8260, TimeMedAE: 316.7233
test [full], NDCG@5: 0.7017, HR@5: 0.9177, NDCG@10: 0.7291, HR@10: 0.9974, MRR: 0.6392
test [sampled], NDCG@5: 0.1581, HR@5: 0.1635, NDCG@10: 0.1987, HR@10: 0.2941, MRR: 0.2123
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.1325
epoch=32, loss=1.1342
epoch=33, loss=1.1222
epoch=34, loss=1.1258
epoch=35, loss=1.1181
valid [task], Top5Acc: 0.4162, Top10Acc: 0.5791, Acc: 0.0640, MacroF1: 0.0784, TimeMAE: 76225.8207, TimeRMSE: 281701.8667, TimeMedAE: 9547.4754
valid [full], NDCG@5: 0.6967, HR@5: 0.8333, NDCG@10: 0.7389, HR@10: 0.9682, MRR: 0.6708
valid [sampled], NDCG@5: 0.5530, HR@5: 0.5555, NDCG@10: 0.5633, HR@10: 0.5878, MRR: 0.5721
test [task], Top5Acc: 0.5005, Top10Acc: 0.6202, Acc: 0.0271, MacroF1: 0.0239, TimeMAE: 15370.6065, TimeRMSE: 77390.4573, TimeMedAE: 424.1325
test [full], NDCG@5: 0.7283, HR@5: 0.9407, NDCG@10: 0.7486, HR@10: 0.9999, MRR: 0.6634
test [sampled], NDCG@5: 0.1716, HR@5: 0.1748, NDCG@10: 0.2124, HR@10: 0.3061, MRR: 0.2269
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1276
epoch=37, loss=1.1176
epoch=38, loss=1.1243
epoch=39, loss=1.1188
epoch=40, loss=1.1229
valid [task], Top5Acc: 0.3998, Top10Acc: 0.5745, Acc: 0.0662, MacroF1: 0.0749, TimeMAE: 74683.1785, TimeRMSE: 285384.5589, TimeMedAE: 3951.0007
valid [full], NDCG@5: 0.6841, HR@5: 0.8471, NDCG@10: 0.7211, HR@10: 0.9675, MRR: 0.6472
valid [sampled], NDCG@5: 0.5160, HR@5: 0.5195, NDCG@10: 0.5242, HR@10: 0.5452, MRR: 0.5350
test [task], Top5Acc: 0.5012, Top10Acc: 0.5218, Acc: 0.0274, MacroF1: 0.0222, TimeMAE: 13912.9620, TimeRMSE: 72118.4125, TimeMedAE: 471.5495
test [full], NDCG@5: 0.6769, HR@5: 0.9625, NDCG@10: 0.6896, HR@10: 0.9999, MRR: 0.5857
test [sampled], NDCG@5: 0.0730, HR@5: 0.0767, NDCG@10: 0.1182, HR@10: 0.2222, MRR: 0.1319
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.1190
epoch=42, loss=1.1176
epoch=43, loss=1.1037
epoch=44, loss=1.1136
epoch=45, loss=1.1000
valid [task], Top5Acc: 0.3980, Top10Acc: 0.5763, Acc: 0.0657, MacroF1: 0.0929, TimeMAE: 76498.3057, TimeRMSE: 288875.0725, TimeMedAE: 9310.5052
valid [full], NDCG@5: 0.7069, HR@5: 0.8501, NDCG@10: 0.7391, HR@10: 0.9544, MRR: 0.6762
valid [sampled], NDCG@5: 0.5569, HR@5: 0.5601, NDCG@10: 0.5690, HR@10: 0.5982, MRR: 0.5760
test [task], Top5Acc: 0.3057, Top10Acc: 0.5152, Acc: 0.0273, MacroF1: 0.0244, TimeMAE: 18333.2290, TimeRMSE: 72907.0281, TimeMedAE: 501.1593
test [full], NDCG@5: 0.6519, HR@5: 0.9319, NDCG@10: 0.6730, HR@10: 0.9984, MRR: 0.5664
test [sampled], NDCG@5: 0.0805, HR@5: 0.0839, NDCG@10: 0.1085, HR@10: 0.1746, MRR: 0.1338
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1152
epoch=47, loss=1.1090
epoch=48, loss=1.1039
epoch=49, loss=1.1006
epoch=50, loss=1.1085
valid [task], Top5Acc: 0.3766, Top10Acc: 0.5695, Acc: 0.0670, MacroF1: 0.0794, TimeMAE: 77560.7114, TimeRMSE: 288977.1809, TimeMedAE: 2631.2669
valid [full], NDCG@5: 0.6954, HR@5: 0.8459, NDCG@10: 0.7287, HR@10: 0.9523, MRR: 0.6630
valid [sampled], NDCG@5: 0.5376, HR@5: 0.5435, NDCG@10: 0.5520, HR@10: 0.5888, MRR: 0.5574
test [task], Top5Acc: 0.4694, Top10Acc: 0.6174, Acc: 0.0282, MacroF1: 0.0212, TimeMAE: 12876.9731, TimeRMSE: 68614.0565, TimeMedAE: 496.2505
test [full], NDCG@5: 0.7248, HR@5: 0.9427, NDCG@10: 0.7439, HR@10: 0.9999, MRR: 0.6569
test [sampled], NDCG@5: 0.1522, HR@5: 0.1586, NDCG@10: 0.1993, HR@10: 0.3102, MRR: 0.2092
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_s7/sasrec_last.pth

## Train refine attention-bias multi-task w0.1 runs

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_attnbias_dstart_ml50_do035_b9_w01_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 0.1 \
  --output_dir "$MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42
epoch=1, loss=0.8965
epoch=2, loss=0.4229
epoch=3, loss=0.3437
epoch=4, loss=0.3051
epoch=5, loss=0.2809
valid [task], Top5Acc: 0.4872, Top10Acc: 0.7646, Acc: 0.0603, MacroF1: 0.0930, TimeMAE: 73939.8953, TimeRMSE: 279427.1200, TimeMedAE: 831.4806
valid [full], NDCG@5: 0.6551, HR@5: 0.7716, NDCG@10: 0.7263, HR@10: 0.9967, MRR: 0.6467
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5621, NDCG@10: 0.5659, HR@10: 0.5840, MRR: 0.5738
test [task], Top5Acc: 0.2827, Top10Acc: 0.4386, Acc: 0.0118, MacroF1: 0.0119, TimeMAE: 11530.7183, TimeRMSE: 81986.8328, TimeMedAE: 8.3850
test [full], NDCG@5: 0.5470, HR@5: 0.6757, NDCG@10: 0.5875, HR@10: 0.8082, MRR: 0.5328
test [sampled], NDCG@5: 0.1461, HR@5: 0.1515, NDCG@10: 0.1745, HR@10: 0.2424, MRR: 0.1870
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/sasrec_best.pth
epoch=6, loss=0.2664
epoch=7, loss=0.2500
epoch=8, loss=0.2413
epoch=9, loss=0.2361
epoch=10, loss=0.2293
valid [task], Top5Acc: 0.4982, Top10Acc: 0.6989, Acc: 0.1138, MacroF1: 0.1155, TimeMAE: 71750.9421, TimeRMSE: 282336.4032, TimeMedAE: 756.8479
valid [full], NDCG@5: 0.6626, HR@5: 0.7762, NDCG@10: 0.7300, HR@10: 0.9803, MRR: 0.6566
valid [sampled], NDCG@5: 0.5676, HR@5: 0.5732, NDCG@10: 0.5774, HR@10: 0.6035, MRR: 0.5818
test [task], Top5Acc: 0.2811, Top10Acc: 0.5697, Acc: 0.0128, MacroF1: 0.0127, TimeMAE: 13356.5516, TimeRMSE: 85893.6836, TimeMedAE: 8.3640
test [full], NDCG@5: 0.7195, HR@5: 0.8563, NDCG@10: 0.7672, HR@10: 1.0000, MRR: 0.6951
test [sampled], NDCG@5: 0.1759, HR@5: 0.2149, NDCG@10: 0.2278, HR@10: 0.3764, MRR: 0.2131
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/sasrec_best.pth
epoch=11, loss=0.2267
epoch=12, loss=0.2228
epoch=13, loss=0.2166
epoch=14, loss=0.2202
epoch=15, loss=0.2165
valid [task], Top5Acc: 0.4216, Top10Acc: 0.7054, Acc: 0.1332, MacroF1: 0.1454, TimeMAE: 74403.7632, TimeRMSE: 283602.7963, TimeMedAE: 641.8618
valid [full], NDCG@5: 0.6607, HR@5: 0.7742, NDCG@10: 0.7189, HR@10: 0.9590, MRR: 0.6509
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5677, NDCG@10: 0.5730, HR@10: 0.5984, MRR: 0.5779
test [task], Top5Acc: 0.2797, Top10Acc: 0.5457, Acc: 0.0166, MacroF1: 0.0141, TimeMAE: 12251.9608, TimeRMSE: 78508.1998, TimeMedAE: 8.3850
test [full], NDCG@5: 0.7046, HR@5: 0.7944, NDCG@10: 0.7691, HR@10: 1.0000, MRR: 0.7002
test [sampled], NDCG@5: 0.1807, HR@5: 0.2215, NDCG@10: 0.2354, HR@10: 0.3913, MRR: 0.2169
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.2129
epoch=17, loss=0.2089
epoch=18, loss=0.2071
epoch=19, loss=0.2041
epoch=20, loss=0.1999
valid [task], Top5Acc: 0.3983, Top10Acc: 0.7012, Acc: 0.0816, MacroF1: 0.1393, TimeMAE: 79333.5781, TimeRMSE: 289688.4326, TimeMedAE: 3796.2071
valid [full], NDCG@5: 0.6949, HR@5: 0.8427, NDCG@10: 0.7303, HR@10: 0.9574, MRR: 0.6643
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5643, NDCG@10: 0.5717, HR@10: 0.6067, MRR: 0.5755
test [task], Top5Acc: 0.2764, Top10Acc: 0.6725, Acc: 0.0230, MacroF1: 0.0208, TimeMAE: 12028.2921, TimeRMSE: 73708.1879, TimeMedAE: 10.7637
test [full], NDCG@5: 0.7733, HR@5: 0.9400, NDCG@10: 0.7938, HR@10: 1.0000, MRR: 0.7280
test [sampled], NDCG@5: 0.1837, HR@5: 0.2215, NDCG@10: 0.2387, HR@10: 0.3926, MRR: 0.2247
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/sasrec_best.pth
epoch=21, loss=0.1998
epoch=22, loss=0.1995
epoch=23, loss=0.1957
epoch=24, loss=0.1938
epoch=25, loss=0.1925
valid [task], Top5Acc: 0.4002, Top10Acc: 0.6945, Acc: 0.0877, MacroF1: 0.1330, TimeMAE: 76365.2769, TimeRMSE: 294212.9171, TimeMedAE: 5929.4521
valid [full], NDCG@5: 0.7201, HR@5: 0.8629, NDCG@10: 0.7541, HR@10: 0.9734, MRR: 0.6880
valid [sampled], NDCG@5: 0.5658, HR@5: 0.5724, NDCG@10: 0.5828, HR@10: 0.6264, MRR: 0.5860
test [task], Top5Acc: 0.0877, Top10Acc: 0.6886, Acc: 0.0265, MacroF1: 0.0212, TimeMAE: 13341.4402, TimeRMSE: 80674.0125, TimeMedAE: 26.5877
test [full], NDCG@5: 0.6953, HR@5: 0.9460, NDCG@10: 0.7133, HR@10: 1.0000, MRR: 0.6191
test [sampled], NDCG@5: 0.1584, HR@5: 0.1715, NDCG@10: 0.1869, HR@10: 0.2617, MRR: 0.2047
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/sasrec_best.pth
epoch=26, loss=0.1903
epoch=27, loss=0.1899
epoch=28, loss=0.1882
epoch=29, loss=0.1888
epoch=30, loss=0.1859
valid [task], Top5Acc: 0.4055, Top10Acc: 0.5893, Acc: 0.0875, MacroF1: 0.1356, TimeMAE: 75576.0678, TimeRMSE: 287488.3397, TimeMedAE: 841.6922
valid [full], NDCG@5: 0.6609, HR@5: 0.7840, NDCG@10: 0.7137, HR@10: 0.9454, MRR: 0.6471
valid [sampled], NDCG@5: 0.5390, HR@5: 0.5444, NDCG@10: 0.5529, HR@10: 0.5881, MRR: 0.5563
test [task], Top5Acc: 0.2786, Top10Acc: 0.6720, Acc: 0.0318, MacroF1: 0.0254, TimeMAE: 12083.7591, TimeRMSE: 81099.9022, TimeMedAE: 8.7083
test [full], NDCG@5: 0.6984, HR@5: 0.9413, NDCG@10: 0.7190, HR@10: 1.0000, MRR: 0.6259
test [sampled], NDCG@5: 0.1599, HR@5: 0.1691, NDCG@10: 0.1923, HR@10: 0.2723, MRR: 0.2095
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.1873
epoch=32, loss=0.1840
epoch=33, loss=0.1859
epoch=34, loss=0.1823
epoch=35, loss=0.1833
valid [task], Top5Acc: 0.4038, Top10Acc: 0.6016, Acc: 0.0833, MacroF1: 0.1399, TimeMAE: 75379.2142, TimeRMSE: 283517.9928, TimeMedAE: 3288.2922
valid [full], NDCG@5: 0.7061, HR@5: 0.8630, NDCG@10: 0.7400, HR@10: 0.9737, MRR: 0.6705
valid [sampled], NDCG@5: 0.5651, HR@5: 0.5716, NDCG@10: 0.5778, HR@10: 0.6115, MRR: 0.5822
test [task], Top5Acc: 0.3287, Top10Acc: 0.5887, Acc: 0.0324, MacroF1: 0.0286, TimeMAE: 12373.5935, TimeRMSE: 74097.1144, TimeMedAE: 93.4360
test [full], NDCG@5: 0.7008, HR@5: 0.9705, NDCG@10: 0.7111, HR@10: 1.0000, MRR: 0.6130
test [sampled], NDCG@5: 0.0858, HR@5: 0.1041, NDCG@10: 0.1398, HR@10: 0.2758, MRR: 0.1431
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.1817
epoch=37, loss=0.1817
epoch=38, loss=0.1803
epoch=39, loss=0.1829
epoch=40, loss=0.1798
valid [task], Top5Acc: 0.3985, Top10Acc: 0.6888, Acc: 0.0861, MacroF1: 0.1467, TimeMAE: 69490.4822, TimeRMSE: 271007.8789, TimeMedAE: 4085.2827
valid [full], NDCG@5: 0.7069, HR@5: 0.8581, NDCG@10: 0.7275, HR@10: 0.9260, MRR: 0.6694
valid [sampled], NDCG@5: 0.5304, HR@5: 0.5378, NDCG@10: 0.5513, HR@10: 0.6034, MRR: 0.5526
test [task], Top5Acc: 0.3545, Top10Acc: 0.6229, Acc: 0.0322, MacroF1: 0.0256, TimeMAE: 12125.7841, TimeRMSE: 72582.5513, TimeMedAE: 123.5687
test [full], NDCG@5: 0.7147, HR@5: 0.9510, NDCG@10: 0.7314, HR@10: 1.0000, MRR: 0.6396
test [sampled], NDCG@5: 0.1139, HR@5: 0.1280, NDCG@10: 0.1693, HR@10: 0.3047, MRR: 0.1728
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.1809
epoch=42, loss=0.1808
epoch=43, loss=0.1819
epoch=44, loss=0.1805
epoch=45, loss=0.1811
valid [task], Top5Acc: 0.4082, Top10Acc: 0.6518, Acc: 0.0735, MacroF1: 0.1192, TimeMAE: 82125.0038, TimeRMSE: 287654.6707, TimeMedAE: 11189.5874
valid [full], NDCG@5: 0.7018, HR@5: 0.8616, NDCG@10: 0.7286, HR@10: 0.9494, MRR: 0.6627
valid [sampled], NDCG@5: 0.5371, HR@5: 0.5436, NDCG@10: 0.5507, HR@10: 0.5861, MRR: 0.5568
test [task], Top5Acc: 0.3838, Top10Acc: 0.6694, Acc: 0.0453, MacroF1: 0.0310, TimeMAE: 14348.5799, TimeRMSE: 74997.8562, TimeMedAE: 168.6558
test [full], NDCG@5: 0.7411, HR@5: 0.9570, NDCG@10: 0.7558, HR@10: 1.0000, MRR: 0.6734
test [sampled], NDCG@5: 0.1851, HR@5: 0.2114, NDCG@10: 0.2423, HR@10: 0.3908, MRR: 0.2340
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.1758
epoch=47, loss=0.1791
epoch=48, loss=0.1766
epoch=49, loss=0.1788
epoch=50, loss=0.1766
valid [task], Top5Acc: 0.3980, Top10Acc: 0.6160, Acc: 0.0721, MacroF1: 0.0990, TimeMAE: 71767.7019, TimeRMSE: 281168.1504, TimeMedAE: 7804.3782
valid [full], NDCG@5: 0.6988, HR@5: 0.8346, NDCG@10: 0.7277, HR@10: 0.9268, MRR: 0.6696
valid [sampled], NDCG@5: 0.5302, HR@5: 0.5385, NDCG@10: 0.5518, HR@10: 0.6064, MRR: 0.5522
test [task], Top5Acc: 0.4151, Top10Acc: 0.7169, Acc: 0.0334, MacroF1: 0.0256, TimeMAE: 13386.7677, TimeRMSE: 75279.3937, TimeMedAE: 161.9140
test [full], NDCG@5: 0.7829, HR@5: 0.9556, NDCG@10: 0.7981, HR@10: 1.0000, MRR: 0.7294
test [sampled], NDCG@5: 0.2888, HR@5: 0.3132, NDCG@10: 0.3412, HR@10: 0.4782, MRR: 0.3327
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s42/sasrec_last.pth

In [ ]:
!python src/train_sasrec.py \
  --run_name multitask_attnbias_dstart_ml50_do035_b9_w01_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 0.1 \
  --output_dir "$MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024
epoch=1, loss=0.8832
epoch=2, loss=0.4327
epoch=3, loss=0.3458
epoch=4, loss=0.3034
epoch=5, loss=0.2811
valid [task], Top5Acc: 0.4981, Top10Acc: 0.7141, Acc: 0.0922, MacroF1: 0.1377, TimeMAE: 100511.0429, TimeRMSE: 326375.8715, TimeMedAE: 815.7832
valid [full], NDCG@5: 0.6555, HR@5: 0.7703, NDCG@10: 0.7214, HR@10: 0.9769, MRR: 0.6475
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5653, NDCG@10: 0.5682, HR@10: 0.5892, MRR: 0.5745
test [task], Top5Acc: 0.2752, Top10Acc: 0.6384, Acc: 0.0312, MacroF1: 0.0252, TimeMAE: 13605.0011, TimeRMSE: 85800.8524, TimeMedAE: 24.7114
test [full], NDCG@5: 0.7575, HR@5: 0.9068, NDCG@10: 0.7877, HR@10: 0.9999, MRR: 0.7215
test [sampled], NDCG@5: 0.1852, HR@5: 0.2188, NDCG@10: 0.2365, HR@10: 0.3788, MRR: 0.2264
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/sasrec_best.pth
epoch=6, loss=0.2619
epoch=7, loss=0.2519
epoch=8, loss=0.2450
epoch=9, loss=0.2371
epoch=10, loss=0.2364
valid [task], Top5Acc: 0.5286, Top10Acc: 0.7127, Acc: 0.0827, MacroF1: 0.1018, TimeMAE: 78479.2486, TimeRMSE: 281278.5140, TimeMedAE: 826.0334
valid [full], NDCG@5: 0.6793, HR@5: 0.7783, NDCG@10: 0.7377, HR@10: 0.9693, MRR: 0.6724
valid [sampled], NDCG@5: 0.5976, HR@5: 0.5991, NDCG@10: 0.6022, HR@10: 0.6135, MRR: 0.6106
test [task], Top5Acc: 0.3558, Top10Acc: 0.6377, Acc: 0.0262, MacroF1: 0.0182, TimeMAE: 11630.6548, TimeRMSE: 71110.8516, TimeMedAE: 58.3835
test [full], NDCG@5: 0.7970, HR@5: 0.8996, NDCG@10: 0.8287, HR@10: 1.0000, MRR: 0.7740
test [sampled], NDCG@5: 0.2070, HR@5: 0.2485, NDCG@10: 0.2727, HR@10: 0.4547, MRR: 0.2502
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/sasrec_best.pth
epoch=11, loss=0.2318
epoch=12, loss=0.2296
epoch=13, loss=0.2260
epoch=14, loss=0.2214
epoch=15, loss=0.2201
valid [task], Top5Acc: 0.4989, Top10Acc: 0.7222, Acc: 0.0833, MacroF1: 0.1214, TimeMAE: 77412.5052, TimeRMSE: 286480.0282, TimeMedAE: 3980.2479
valid [full], NDCG@5: 0.7094, HR@5: 0.8836, NDCG@10: 0.7364, HR@10: 0.9699, MRR: 0.6670
valid [sampled], NDCG@5: 0.5638, HR@5: 0.5665, NDCG@10: 0.5717, HR@10: 0.5914, MRR: 0.5813
test [task], Top5Acc: 0.4303, Top10Acc: 0.6364, Acc: 0.0811, MacroF1: 0.0378, TimeMAE: 12287.4409, TimeRMSE: 76759.6816, TimeMedAE: 97.1377
test [full], NDCG@5: 0.8751, HR@5: 0.9409, NDCG@10: 0.8931, HR@10: 1.0000, MRR: 0.8595
test [sampled], NDCG@5: 0.2912, HR@5: 0.3470, NDCG@10: 0.3646, HR@10: 0.5755, MRR: 0.3258
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.2191
epoch=17, loss=0.2155
epoch=18, loss=0.2159
epoch=19, loss=0.2154
epoch=20, loss=0.2139
valid [task], Top5Acc: 0.4979, Top10Acc: 0.7109, Acc: 0.1222, MacroF1: 0.1500, TimeMAE: 81942.0796, TimeRMSE: 293297.1117, TimeMedAE: 4949.0386
valid [full], NDCG@5: 0.7016, HR@5: 0.8751, NDCG@10: 0.7267, HR@10: 0.9565, MRR: 0.6593
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5609, NDCG@10: 0.5663, HR@10: 0.5874, MRR: 0.5752
test [task], Top5Acc: 0.3811, Top10Acc: 0.6338, Acc: 0.1072, MacroF1: 0.0462, TimeMAE: 14447.7356, TimeRMSE: 73004.2299, TimeMedAE: 51.7762
test [full], NDCG@5: 0.8654, HR@5: 0.9412, NDCG@10: 0.8831, HR@10: 1.0000, MRR: 0.8464
test [sampled], NDCG@5: 0.2769, HR@5: 0.3266, NDCG@10: 0.3468, HR@10: 0.5442, MRR: 0.3137
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.2104
epoch=22, loss=0.2083
epoch=23, loss=0.2066
epoch=24, loss=0.2088
epoch=25, loss=0.2081
valid [task], Top5Acc: 0.4995, Top10Acc: 0.7884, Acc: 0.1742, MacroF1: 0.1706, TimeMAE: 93373.0828, TimeRMSE: 294183.4698, TimeMedAE: 8660.2363
valid [full], NDCG@5: 0.7174, HR@5: 0.8870, NDCG@10: 0.7429, HR@10: 0.9712, MRR: 0.6741
valid [sampled], NDCG@5: 0.5560, HR@5: 0.5596, NDCG@10: 0.5680, HR@10: 0.5973, MRR: 0.5761
test [task], Top5Acc: 0.4555, Top10Acc: 0.6710, Acc: 0.0983, MacroF1: 0.0400, TimeMAE: 19960.9707, TimeRMSE: 79569.8046, TimeMedAE: 489.3808
test [full], NDCG@5: 0.8857, HR@5: 0.9610, NDCG@10: 0.8985, HR@10: 1.0000, MRR: 0.8659
test [sampled], NDCG@5: 0.2864, HR@5: 0.3392, NDCG@10: 0.3546, HR@10: 0.5505, MRR: 0.3222
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/sasrec_best.pth
epoch=26, loss=0.2050
epoch=27, loss=0.2039
epoch=28, loss=0.2010
epoch=29, loss=0.2014
epoch=30, loss=0.1956
valid [task], Top5Acc: 0.5030, Top10Acc: 0.7046, Acc: 0.1727, MacroF1: 0.1725, TimeMAE: 90471.1644, TimeRMSE: 297368.4596, TimeMedAE: 7711.1556
valid [full], NDCG@5: 0.7105, HR@5: 0.8623, NDCG@10: 0.7380, HR@10: 0.9522, MRR: 0.6755
valid [sampled], NDCG@5: 0.5642, HR@5: 0.5676, NDCG@10: 0.5748, HR@10: 0.6010, MRR: 0.5830
test [task], Top5Acc: 0.4709, Top10Acc: 0.6495, Acc: 0.0888, MacroF1: 0.0312, TimeMAE: 16592.8081, TimeRMSE: 75883.8537, TimeMedAE: 456.5840
test [full], NDCG@5: 0.9015, HR@5: 0.9961, NDCG@10: 0.9028, HR@10: 1.0000, MRR: 0.8705
test [sampled], NDCG@5: 0.2762, HR@5: 0.3289, NDCG@10: 0.3492, HR@10: 0.5550, MRR: 0.3142
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.1951
epoch=32, loss=0.1935
epoch=33, loss=0.1926
epoch=34, loss=0.1904
epoch=35, loss=0.1915
valid [task], Top5Acc: 0.4985, Top10Acc: 0.8043, Acc: 0.1691, MacroF1: 0.1615, TimeMAE: 85073.2150, TimeRMSE: 292663.0887, TimeMedAE: 8166.7099
valid [full], NDCG@5: 0.7132, HR@5: 0.8672, NDCG@10: 0.7471, HR@10: 0.9724, MRR: 0.6791
valid [sampled], NDCG@5: 0.5611, HR@5: 0.5657, NDCG@10: 0.5741, HR@10: 0.6066, MRR: 0.5811
test [task], Top5Acc: 0.4299, Top10Acc: 0.6523, Acc: 0.0904, MacroF1: 0.0299, TimeMAE: 15423.8973, TimeRMSE: 80246.5376, TimeMedAE: 226.5409
test [full], NDCG@5: 0.8896, HR@5: 0.9999, NDCG@10: 0.8897, HR@10: 1.0000, MRR: 0.8521
test [sampled], NDCG@5: 0.2767, HR@5: 0.3229, NDCG@10: 0.3438, HR@10: 0.5312, MRR: 0.3163
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/sasrec_best.pth
epoch=36, loss=0.1900
epoch=37, loss=0.1893
epoch=38, loss=0.1873
epoch=39, loss=0.1867
epoch=40, loss=0.1864
valid [task], Top5Acc: 0.5020, Top10Acc: 0.7071, Acc: 0.1712, MacroF1: 0.1618, TimeMAE: 97733.7396, TimeRMSE: 304494.2460, TimeMedAE: 9135.6742
valid [full], NDCG@5: 0.7104, HR@5: 0.8632, NDCG@10: 0.7443, HR@10: 0.9715, MRR: 0.6761
valid [sampled], NDCG@5: 0.5601, HR@5: 0.5659, NDCG@10: 0.5737, HR@10: 0.6088, MRR: 0.5790
test [task], Top5Acc: 0.4348, Top10Acc: 0.6304, Acc: 0.0925, MacroF1: 0.0279, TimeMAE: 19028.0061, TimeRMSE: 76831.1722, TimeMedAE: 199.0609
test [full], NDCG@5: 0.8961, HR@5: 0.9995, NDCG@10: 0.8963, HR@10: 1.0000, MRR: 0.8612
test [sampled], NDCG@5: 0.3189, HR@5: 0.3730, NDCG@10: 0.3873, HR@10: 0.5846, MRR: 0.3529
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.1860
epoch=42, loss=0.1875
epoch=43, loss=0.1854
epoch=44, loss=0.1828
epoch=45, loss=0.1843
valid [task], Top5Acc: 0.5022, Top10Acc: 0.7135, Acc: 0.1694, MacroF1: 0.1617, TimeMAE: 90988.1649, TimeRMSE: 295745.3134, TimeMedAE: 6533.9365
valid [full], NDCG@5: 0.6936, HR@5: 0.8602, NDCG@10: 0.7289, HR@10: 0.9715, MRR: 0.6563
valid [sampled], NDCG@5: 0.5427, HR@5: 0.5466, NDCG@10: 0.5526, HR@10: 0.5778, MRR: 0.5617
test [task], Top5Acc: 0.4223, Top10Acc: 0.6257, Acc: 0.0735, MacroF1: 0.0248, TimeMAE: 16163.3400, TimeRMSE: 73247.6601, TimeMedAE: 113.5431
test [full], NDCG@5: 0.8680, HR@5: 0.9999, NDCG@10: 0.8680, HR@10: 1.0000, MRR: 0.8236
test [sampled], NDCG@5: 0.2976, HR@5: 0.3390, NDCG@10: 0.3606, HR@10: 0.5351, MRR: 0.3361
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.1827
epoch=47, loss=0.1824
epoch=48, loss=0.1818
epoch=49, loss=0.1802
epoch=50, loss=0.1814
valid [task], Top5Acc: 0.4979, Top10Acc: 0.7339, Acc: 0.1685, MacroF1: 0.1646, TimeMAE: 95458.3186, TimeRMSE: 298152.6680, TimeMedAE: 12353.6906
valid [full], NDCG@5: 0.6975, HR@5: 0.8627, NDCG@10: 0.7327, HR@10: 0.9722, MRR: 0.6604
valid [sampled], NDCG@5: 0.5375, HR@5: 0.5399, NDCG@10: 0.5487, HR@10: 0.5753, MRR: 0.5586
test [task], Top5Acc: 0.4482, Top10Acc: 0.6431, Acc: 0.0798, MacroF1: 0.0285, TimeMAE: 16669.3836, TimeRMSE: 71348.7735, TimeMedAE: 226.2125
test [full], NDCG@5: 0.8153, HR@5: 0.9999, NDCG@10: 0.8153, HR@10: 1.0000, MRR: 0.7520
test [sampled], NDCG@5: 0.3382, HR@5: 0.3601, NDCG@10: 0.3828, HR@10: 0.5002, MRR: 0.3784
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s2024/sasrec_last.pth

In [13]:
!python src/train_sasrec.py \
  --run_name multitask_attnbias_dstart_ml50_do035_b9_w01_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 0.1 \
  --output_dir "$MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7
epoch=1, loss=0.9030
epoch=2, loss=0.4477
epoch=3, loss=0.3571
epoch=4, loss=0.3177
epoch=5, loss=0.2935
valid [task], Top5Acc: 0.4659, Top10Acc: 0.7888, Acc: 0.0916, MacroF1: 0.1731, TimeMAE: 77743.6406, TimeRMSE: 293442.9292, TimeMedAE: 3468.6527
valid [full], NDCG@5: 0.6510, HR@5: 0.7863, NDCG@10: 0.7118, HR@10: 0.9721, MRR: 0.6358
valid [sampled], NDCG@5: 0.5347, HR@5: 0.5373, NDCG@10: 0.5427, HR@10: 0.5624, MRR: 0.5515
test [task], Top5Acc: 0.0754, Top10Acc: 0.5324, Acc: 0.0431, MacroF1: 0.0385, TimeMAE: 14486.6793, TimeRMSE: 84547.3891, TimeMedAE: 47.6911
test [full], NDCG@5: 0.5978, HR@5: 0.8730, NDCG@10: 0.6397, HR@10: 1.0000, MRR: 0.5248
test [sampled], NDCG@5: 0.0850, HR@5: 0.0914, NDCG@10: 0.1026, HR@10: 0.1472, MRR: 0.1313
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/sasrec_best.pth
epoch=6, loss=0.2698
epoch=7, loss=0.2571
epoch=8, loss=0.2446
epoch=9, loss=0.2384
epoch=10, loss=0.2325
valid [task], Top5Acc: 0.4285, Top10Acc: 0.6726, Acc: 0.0645, MacroF1: 0.0481, TimeMAE: 74981.4481, TimeRMSE: 291029.1379, TimeMedAE: 7964.5408
valid [full], NDCG@5: 0.6985, HR@5: 0.8345, NDCG@10: 0.7376, HR@10: 0.9554, MRR: 0.6747
valid [sampled], NDCG@5: 0.5803, HR@5: 0.5834, NDCG@10: 0.5879, HR@10: 0.6073, MRR: 0.5956
test [task], Top5Acc: 0.3731, Top10Acc: 0.6147, Acc: 0.0334, MacroF1: 0.0218, TimeMAE: 14214.7659, TimeRMSE: 82843.2585, TimeMedAE: 61.3600
test [full], NDCG@5: 0.7186, HR@5: 0.9616, NDCG@10: 0.7316, HR@10: 1.0000, MRR: 0.6416
test [sampled], NDCG@5: 0.1029, HR@5: 0.1111, NDCG@10: 0.1501, HR@10: 0.2625, MRR: 0.1607
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/sasrec_best.pth
epoch=11, loss=0.2276
epoch=12, loss=0.2226
epoch=13, loss=0.2180
epoch=14, loss=0.2131
epoch=15, loss=0.2095
valid [task], Top5Acc: 0.4060, Top10Acc: 0.6866, Acc: 0.0643, MacroF1: 0.0605, TimeMAE: 71815.3253, TimeRMSE: 283820.9809, TimeMedAE: 4092.8986
valid [full], NDCG@5: 0.7073, HR@5: 0.8573, NDCG@10: 0.7416, HR@10: 0.9692, MRR: 0.6725
valid [sampled], NDCG@5: 0.5286, HR@5: 0.5350, NDCG@10: 0.5504, HR@10: 0.6038, MRR: 0.5521
test [task], Top5Acc: 0.3582, Top10Acc: 0.6440, Acc: 0.0266, MacroF1: 0.0220, TimeMAE: 13635.0716, TimeRMSE: 87244.6792, TimeMedAE: 34.5213
test [full], NDCG@5: 0.7684, HR@5: 0.9970, NDCG@10: 0.7694, HR@10: 1.0000, MRR: 0.6890
test [sampled], NDCG@5: 0.1947, HR@5: 0.2039, NDCG@10: 0.2526, HR@10: 0.3889, MRR: 0.2537
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/sasrec_best.pth
epoch=16, loss=0.2072
epoch=17, loss=0.2022
epoch=18, loss=0.2000
epoch=19, loss=0.1997
epoch=20, loss=0.1971
valid [task], Top5Acc: 0.4011, Top10Acc: 0.6734, Acc: 0.0585, MacroF1: 0.0668, TimeMAE: 75686.1571, TimeRMSE: 293958.8996, TimeMedAE: 4209.5167
valid [full], NDCG@5: 0.7053, HR@5: 0.8725, NDCG@10: 0.7357, HR@10: 0.9707, MRR: 0.6644
valid [sampled], NDCG@5: 0.5294, HR@5: 0.5350, NDCG@10: 0.5472, HR@10: 0.5906, MRR: 0.5514
test [task], Top5Acc: 0.3634, Top10Acc: 0.7202, Acc: 0.0254, MacroF1: 0.0202, TimeMAE: 13887.1200, TimeRMSE: 85109.6901, TimeMedAE: 47.4233
test [full], NDCG@5: 0.7912, HR@5: 0.9995, NDCG@10: 0.7914, HR@10: 1.0000, MRR: 0.7181
test [sampled], NDCG@5: 0.3229, HR@5: 0.3303, NDCG@10: 0.3644, HR@10: 0.4635, MRR: 0.3714
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.1960
epoch=22, loss=0.1928
epoch=23, loss=0.1936
epoch=24, loss=0.1925
epoch=25, loss=0.1894
valid [task], Top5Acc: 0.4023, Top10Acc: 0.6969, Acc: 0.0578, MacroF1: 0.0697, TimeMAE: 74813.0255, TimeRMSE: 282945.8312, TimeMedAE: 4529.0770
valid [full], NDCG@5: 0.6745, HR@5: 0.8531, NDCG@10: 0.7122, HR@10: 0.9707, MRR: 0.6329
valid [sampled], NDCG@5: 0.4791, HR@5: 0.4851, NDCG@10: 0.4972, HR@10: 0.5422, MRR: 0.5027
test [task], Top5Acc: 0.4643, Top10Acc: 0.7253, Acc: 0.0208, MacroF1: 0.0199, TimeMAE: 13744.9220, TimeRMSE: 73155.9902, TimeMedAE: 125.4211
test [full], NDCG@5: 0.7905, HR@5: 0.9970, NDCG@10: 0.7915, HR@10: 1.0000, MRR: 0.7182
test [sampled], NDCG@5: 0.3050, HR@5: 0.3154, NDCG@10: 0.3516, HR@10: 0.4640, MRR: 0.3546
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.1905
epoch=27, loss=0.1902
epoch=28, loss=0.1869
epoch=29, loss=0.1885
epoch=30, loss=0.1864
valid [task], Top5Acc: 0.4063, Top10Acc: 0.7140, Acc: 0.0548, MacroF1: 0.0807, TimeMAE: 77711.8994, TimeRMSE: 285295.0324, TimeMedAE: 5037.3883
valid [full], NDCG@5: 0.6846, HR@5: 0.8737, NDCG@10: 0.7133, HR@10: 0.9682, MRR: 0.6352
valid [sampled], NDCG@5: 0.4782, HR@5: 0.4855, NDCG@10: 0.4985, HR@10: 0.5495, MRR: 0.5021
test [task], Top5Acc: 0.4819, Top10Acc: 0.7094, Acc: 0.0151, MacroF1: 0.0148, TimeMAE: 15429.0543, TimeRMSE: 77672.0371, TimeMedAE: 231.1735
test [full], NDCG@5: 0.8013, HR@5: 0.9970, NDCG@10: 0.8023, HR@10: 1.0000, MRR: 0.7333
test [sampled], NDCG@5: 0.2941, HR@5: 0.3140, NDCG@10: 0.3443, HR@10: 0.4726, MRR: 0.3409
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.1864
epoch=32, loss=0.1872
epoch=33, loss=0.1855
epoch=34, loss=0.1843
epoch=35, loss=0.1858
valid [task], Top5Acc: 0.4192, Top10Acc: 0.7293, Acc: 0.0560, MacroF1: 0.0713, TimeMAE: 78426.8361, TimeRMSE: 284363.8421, TimeMedAE: 5205.4346
valid [full], NDCG@5: 0.6866, HR@5: 0.8733, NDCG@10: 0.7168, HR@10: 0.9709, MRR: 0.6383
valid [sampled], NDCG@5: 0.4771, HR@5: 0.4848, NDCG@10: 0.4981, HR@10: 0.5508, MRR: 0.5017
test [task], Top5Acc: 0.4813, Top10Acc: 0.7419, Acc: 0.0234, MacroF1: 0.0194, TimeMAE: 16886.7167, TimeRMSE: 76876.3361, TimeMedAE: 197.2226
test [full], NDCG@5: 0.8111, HR@5: 0.9980, NDCG@10: 0.8118, HR@10: 1.0000, MRR: 0.7454
test [sampled], NDCG@5: 0.3039, HR@5: 0.3214, NDCG@10: 0.3579, HR@10: 0.4920, MRR: 0.3526
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.1857
epoch=37, loss=0.1836
epoch=38, loss=0.1852
epoch=39, loss=0.1842
epoch=40, loss=0.1830
valid [task], Top5Acc: 0.4089, Top10Acc: 0.7238, Acc: 0.0569, MacroF1: 0.0675, TimeMAE: 79394.5305, TimeRMSE: 286569.9358, TimeMedAE: 5142.1187
valid [full], NDCG@5: 0.6890, HR@5: 0.8738, NDCG@10: 0.7186, HR@10: 0.9701, MRR: 0.6410
valid [sampled], NDCG@5: 0.4823, HR@5: 0.4908, NDCG@10: 0.5021, HR@10: 0.5528, MRR: 0.5062
test [task], Top5Acc: 0.4965, Top10Acc: 0.7128, Acc: 0.1127, MacroF1: 0.0426, TimeMAE: 19283.6304, TimeRMSE: 73015.2047, TimeMedAE: 257.4412
test [full], NDCG@5: 0.8242, HR@5: 0.9958, NDCG@10: 0.8255, HR@10: 1.0000, MRR: 0.7648
test [sampled], NDCG@5: 0.3494, HR@5: 0.3666, NDCG@10: 0.4000, HR@10: 0.5268, MRR: 0.3932
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.1844
epoch=42, loss=0.1836
epoch=43, loss=0.1818
epoch=44, loss=0.1831
epoch=45, loss=0.1808
valid [task], Top5Acc: 0.4275, Top10Acc: 0.7227, Acc: 0.0541, MacroF1: 0.0699, TimeMAE: 77678.7649, TimeRMSE: 291114.5639, TimeMedAE: 5121.9495
valid [full], NDCG@5: 0.6914, HR@5: 0.8754, NDCG@10: 0.7211, HR@10: 0.9719, MRR: 0.6434
valid [sampled], NDCG@5: 0.4776, HR@5: 0.4851, NDCG@10: 0.4990, HR@10: 0.5526, MRR: 0.5028
test [task], Top5Acc: 0.4800, Top10Acc: 0.6963, Acc: 0.0494, MacroF1: 0.0238, TimeMAE: 16133.9113, TimeRMSE: 73776.1249, TimeMedAE: 232.0574
test [full], NDCG@5: 0.7810, HR@5: 0.9644, NDCG@10: 0.7932, HR@10: 1.0000, MRR: 0.7220
test [sampled], NDCG@5: 0.2892, HR@5: 0.3055, NDCG@10: 0.3383, HR@10: 0.4607, MRR: 0.3361
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.1823
epoch=47, loss=0.1813
epoch=48, loss=0.1797
epoch=49, loss=0.1800
epoch=50, loss=0.1809
valid [task], Top5Acc: 0.4007, Top10Acc: 0.7256, Acc: 0.0594, MacroF1: 0.0708, TimeMAE: 84283.1704, TimeRMSE: 290334.4674, TimeMedAE: 6782.0132
valid [full], NDCG@5: 0.7180, HR@5: 0.8759, NDCG@10: 0.7474, HR@10: 0.9718, MRR: 0.6783
valid [sampled], NDCG@5: 0.5313, HR@5: 0.5397, NDCG@10: 0.5567, HR@10: 0.6194, MRR: 0.5558
test [task], Top5Acc: 0.5382, Top10Acc: 0.7147, Acc: 0.1228, MacroF1: 0.0487, TimeMAE: 14519.6267, TimeRMSE: 66724.2202, TimeMedAE: 163.4428
test [full], NDCG@5: 0.9092, HR@5: 0.9971, NDCG@10: 0.9101, HR@10: 1.0000, MRR: 0.8790
test [sampled], NDCG@5: 0.3271, HR@5: 0.3807, NDCG@10: 0.4063, HR@10: 0.6280, MRR: 0.3651
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_w01_ndcg10_v2/multitask_attnbias_dstart_ml50_do035_b9_w01_s7/sasrec_last.pth

## Load run summaries

In [14]:
import json
from pathlib import Path
import pandas as pd

def rebuild_df(output_dir):
    rows = []
    for run_dir in sorted(Path(output_dir).iterdir()):
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_attention_bias': config.get('use_time_attention_bias', False),
            'enable_time_prediction': config.get('enable_time_prediction', False),
            'time_delta_column': config.get('time_delta_column'),
            'time_prediction_target': config.get('time_prediction_target'),
            'time_loss_weight': config.get('time_loss_weight'),
            'time_target_transform': config.get('time_target_transform'),
            'time_modeling_mode': config.get('time_modeling_mode'),
        }
        for group_name in ['best_valid', 'best_test_at_best_valid', 'last_valid', 'last_test']:
            metrics = summary.get(group_name, {})
            for metric_name, value in metrics.items():
                row[f'{group_name}_{metric_name}'] = value
        rows.append(row)
    return pd.DataFrame(rows)

## Compare refine single-task / plain multi-task / attention-bias multi-task

In [24]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
single_task_attnbias_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]
multitask_baseline_runs = [
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]
multitask_attnbias_runs = [
    'multitask_attnbias_dstart_ml50_do035_b9_s42',
    'multitask_attnbias_dstart_ml50_do035_b9_s2024',
    'multitask_attnbias_dstart_ml50_do035_b9_s7',
]
multitask_attnbias_w01_runs = [
    'multitask_attnbias_dstart_ml50_do035_b9_w01_s42',
    'multitask_attnbias_dstart_ml50_do035_b9_w01_s2024',
    'multitask_attnbias_dstart_ml50_do035_b9_w01_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
single_task_attnbias_df = rebuild_df(SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR)
multitask_baseline_df = rebuild_df(MULTITASK_BASELINE_OUTPUT_DIR)
multitask_attnbias_df = rebuild_df(MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR)
multitask_attnbias_w01_df = rebuild_df(MULTITASK_REFINE_ATTNBIAS_W01_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['variant'] = 'refine_single_task'

single_task_attnbias_subset = single_task_attnbias_df[single_task_attnbias_df['run_name'].isin(single_task_attnbias_runs)].copy()
single_task_attnbias_subset['variant'] = 'refine_attnbias_single_task'

multitask_baseline_subset = multitask_baseline_df[multitask_baseline_df['run_name'].isin(multitask_baseline_runs)].copy()
multitask_baseline_subset['variant'] = 'refine_multi_task_w1.0'

multitask_attnbias_subset = multitask_attnbias_df[multitask_attnbias_df['run_name'].isin(multitask_attnbias_runs)].copy()
multitask_attnbias_subset['variant'] = 'refine_attnbias_multi_task_w1.0'

multitask_attnbias_w01_subset = multitask_attnbias_w01_df[multitask_attnbias_w01_df['run_name'].isin(multitask_attnbias_w01_runs)].copy()
multitask_attnbias_w01_subset['variant'] = 'refine_attnbias_multi_task_w0.1'

df_compare = pd.concat(
    [
        baseline_subset,
        single_task_attnbias_subset,
        multitask_baseline_subset,
        multitask_attnbias_subset,
        multitask_attnbias_w01_subset,
    ],
    ignore_index=True,
)
df_compare = df_compare.sort_values(['variant', 'seed', 'run_name']).reset_index(drop=True)

# nested dict metric columns -> flat columns
nested_metric_cols = [
    'best_valid_full',
    'best_valid_sampled',
    'best_test_at_best_valid_full',
    'best_test_at_best_valid_sampled',
    'best_valid_task',
    'best_test_at_best_valid_task',
    'last_valid_full',
    'last_valid_sampled',
    'last_test_full',
    'last_test_sampled',
    'last_valid_task',
    'last_test_task',
]

for col in nested_metric_cols:
    if col in df_compare.columns:
        expanded = pd.json_normalize(df_compare[col]).add_prefix(col + '_')
        df_compare = pd.concat([df_compare.drop(columns=[col]), expanded], axis=1)

id_cols = [
    'run_name',
    'seed',
    'variant',
    'maxlen',
    'dropout_rate',
    'selection_metric',
    'time_loss_weight',
    'best_epoch',
]

metric_prefixes = (
    'best_valid_',
    'best_test_at_best_valid_',
    'last_valid_',
    'last_test_',
)

metric_cols = [c for c in df_compare.columns if c.startswith(metric_prefixes)]

def metric_sort_key(col):
    if col.startswith('best_valid_'):
        group_rank = 0
        name = col[len('best_valid_'):]
    elif col.startswith('best_test_at_best_valid_'):
        group_rank = 1
        name = col[len('best_test_at_best_valid_'):]
    elif col.startswith('last_valid_'):
        group_rank = 2
        name = col[len('last_valid_'):]
    elif col.startswith('last_test_'):
        group_rank = 3
        name = col[len('last_test_'):]
    else:
        group_rank = 99
        name = col

    metric_order = [
        'full_ndcg@10', 'full_hr@10', 'full_ndcg@5', 'full_hr@5', 'full_mrr',
        'sampled_ndcg@10', 'sampled_hr@10', 'sampled_ndcg@5', 'sampled_hr@5', 'sampled_mrr',
        'task_accuracy', 'task_macro_f1', 'task_top5_accuracy', 'task_top10_accuracy',
        'task_time_mae', 'task_time_rmse', 'task_time_median_ae',
    ]

    try:
        metric_rank = metric_order.index(name)
    except ValueError:
        metric_rank = 999

    return (group_rank, metric_rank, name)

metric_cols = sorted(metric_cols, key=metric_sort_key)

display_cols = [c for c in id_cols if c in df_compare.columns] + metric_cols

import pandas as pd

print('num display cols =', len(display_cols))
print(display_cols)

with pd.option_context(
    'display.max_columns', None,
    'display.max_colwidth', None,
    'display.width', 1000,
):
    display(df_compare[display_cols])

num display cols = 104
['run_name', 'seed', 'variant', 'maxlen', 'dropout_rate', 'selection_metric', 'time_loss_weight', 'best_epoch', 'best_valid_full_ndcg@10', 'best_valid_full_hr@10', 'best_valid_full_ndcg@5', 'best_valid_full_hr@5', 'best_valid_full_mrr', 'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10', 'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5', 'best_valid_sampled_mrr', 'best_valid_task_accuracy', 'best_valid_task_macro_f1', 'best_valid_task_top5_accuracy', 'best_valid_task_top10_accuracy', 'best_valid_task_time_mae', 'best_valid_task_time_rmse', 'best_valid_task_time_median_ae', 'best_valid_full_mean_rank', 'best_valid_full_median_rank', 'best_valid_full_num_eval_users', 'best_valid_sampled_mean_rank', 'best_valid_sampled_median_rank', 'best_valid_sampled_num_eval_users', 'best_valid_task_top1_accuracy', 'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10', 'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5', 'best_test_at_best_valid_full_mrr', 'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10', 'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5', 'best_test_at_best_valid_sampled_mrr', 'best_test_at_best_valid_task_accuracy', 'best_test_at_best_valid_task_macro_f1', 'best_test_at_best_valid_task_top5_accuracy', 'best_test_at_best_valid_task_top10_accuracy', 'best_test_at_best_valid_task_time_mae', 'best_test_at_best_valid_task_time_rmse', 'best_test_at_best_valid_task_time_median_ae', 'best_test_at_best_valid_full_mean_rank', 'best_test_at_best_valid_full_median_rank', 'best_test_at_best_valid_full_num_eval_users', 'best_test_at_best_valid_sampled_mean_rank', 'best_test_at_best_valid_sampled_median_rank', 'best_test_at_best_valid_sampled_num_eval_users', 'best_test_at_best_valid_task_top1_accuracy', 'last_valid_full_ndcg@10', 'last_valid_full_hr@10', 'last_valid_full_ndcg@5', 'last_valid_full_hr@5', 'last_valid_full_mrr', 'last_valid_sampled_ndcg@10', 'last_valid_sampled_hr@10', 'last_valid_sampled_ndcg@5', 'last_valid_sampled_hr@5', 'last_valid_sampled_mrr', 'last_valid_task_accuracy', 'last_valid_task_macro_f1', 'last_valid_task_top5_accuracy', 'last_valid_task_top10_accuracy', 'last_valid_task_time_mae', 'last_valid_task_time_rmse', 'last_valid_task_time_median_ae', 'last_valid_full_mean_rank', 'last_valid_full_median_rank', 'last_valid_full_num_eval_users', 'last_valid_sampled_mean_rank', 'last_valid_sampled_median_rank', 'last_valid_sampled_num_eval_users', 'last_valid_task_top1_accuracy', 'last_test_full_ndcg@10', 'last_test_full_hr@10', 'last_test_full_ndcg@5', 'last_test_full_hr@5', 'last_test_full_mrr', 'last_test_sampled_ndcg@10', 'last_test_sampled_hr@10', 'last_test_sampled_ndcg@5', 'last_test_sampled_hr@5', 'last_test_sampled_mrr', 'last_test_task_accuracy', 'last_test_task_macro_f1', 'last_test_task_top5_accuracy', 'last_test_task_top10_accuracy', 'last_test_task_time_mae', 'last_test_task_time_rmse', 'last_test_task_time_median_ae', 'last_test_full_mean_rank', 'last_test_full_median_rank', 'last_test_full_num_eval_users', 'last_test_sampled_mean_rank', 'last_test_sampled_median_rank', 'last_test_sampled_num_eval_users', 'last_test_task_top1_accuracy']

,run_name,seed,variant,maxlen,dropout_rate,selection_metric,time_loss_weight,best_epoch,best_valid_full_ndcg@10,best_valid_full_hr@10,best_valid_full_ndcg@5,best_valid_full_hr@5,best_valid_full_mrr,best_valid_sampled_ndcg@10,best_valid_sampled_hr@10,best_valid_sampled_ndcg@5,best_valid_sampled_hr@5,best_valid_sampled_mrr,best_valid_task_accuracy,best_valid_task_macro_f1,best_valid_task_top5_accuracy,best_valid_task_top10_accuracy,best_valid_task_time_mae,best_valid_task_time_rmse,best_valid_task_time_median_ae,best_valid_full_mean_rank,best_valid_full_median_rank,best_valid_full_num_eval_users,best_valid_sampled_mean_rank,best_valid_sampled_median_rank,best_valid_sampled_num_eval_users,best_valid_task_top1_accuracy,best_test_at_best_valid_full_ndcg@10,best_test_at_best_valid_full_hr@10,best_test_at_best_valid_full_ndcg@5,best_test_at_best_valid_full_hr@5,best_test_at_best_valid_full_mrr,best_test_at_best_valid_sampled_ndcg@10,best_test_at_best_valid_sampled_hr@10,best_test_at_best_valid_sampled_ndcg@5,best_test_at_best_valid_sampled_hr@5,best_test_at_best_valid_sampled_mrr,best_test_at_best_valid_task_accuracy,best_test_at_best_valid_task_macro_f1,best_test_at_best_valid_task_top5_accuracy,best_test_at_best_valid_task_top10_accuracy,best_test_at_best_valid_task_time_mae,best_test_at_best_valid_task_time_rmse,best_test_at_best_valid_task_time_median_ae,best_test_at_best_valid_full_mean_rank,best_test_at_best_valid_full_median_rank,best_test_at_best_valid_full_num_eval_users,best_test_at_best_valid_sampled_mean_rank,best_test_at_best_valid_sampled_median_rank,best_test_at_best_valid_sampled_num_eval_users,best_test_at_best_valid_task_top1_accuracy,last_valid_full_ndcg@10,last_valid_full_hr@10,last_valid_full_ndcg@5,last_valid_full_hr@5,last_valid_full_mrr,last_valid_sampled_ndcg@10,last_valid_sampled_hr@10,last_valid_sampled_ndcg@5,last_valid_sampled_hr@5,last_valid_sampled_mrr,last_valid_task_accuracy,last_valid_task_macro_f1,last_valid_task_top5_accuracy,last_valid_task_top10_accuracy,last_valid_task_time_mae,last_valid_task_time_rmse,last_valid_task_time_median_ae,last_valid_full_mean_rank,last_valid_full_median_rank,last_valid_full_num_eval_users,last_valid_sampled_mean_rank,last_valid_sampled_median_rank,last_valid_sampled_num_eval_users,last_valid_task_top1_accuracy,last_test_full_ndcg@10,last_test_full_hr@10,last_test_full_ndcg@5,last_test_full_hr@5,last_test_full_mrr,last_test_sampled_ndcg@10,last_test_sampled_hr@10,last_test_sampled_ndcg@5,last_test_sampled_hr@5,last_test_sampled_mrr,last_test_task_accuracy,last_test_task_macro_f1,last_test_task_top5_accuracy,last_test_task_top10_accuracy,last_test_task_time_mae,last_test_task_time_rmse,last_test_task_time_median_ae,last_test_full_mean_rank,last_test_full_median_rank,last_test_full_num_eval_users,last_test_sampled_mean_rank,last_test_sampled_median_rank,last_test_sampled_num_eval_users,last_test_task_top1_accuracy
0,multitask_attnbias_dstart_ml50_do035_b9_w01_s7,7,refine_attnbias_multi_task_w0.1,50,0.35,full_valid_ndcg@10,0.1,50,0.747438,0.971785,0.718038,0.875882,0.678257,0.556673,0.619371,0.531293,0.539745,0.555830,0.059414,0.070785,0.400705,0.725583,84283.170385,290334.467376,6782.013222,2.651926,1.0,7372,15.498101,1.0,7372,0.059414,0.910145,1.000000,0.909194,0.997148,0.878992,0.406329,0.628005,0.327147,0.380687,0.365058,0.122776,0.048669,0.538232,0.714654,14519.626672,66724.220192,163.442845,1.292272,1.0,7363,9.401603,8.0,7363,0.122776,0.747438,0.971785,0.718038,0.875882,0.678257,0.556673,0.619371,0.531293,0.539745,0.555830,0.059414,0.070785,0.400705,0.725583,84283.170385,290334.467376,6782.013222,2.651926,1.0,7372,15.498101,1.0,7372,0.059414,0.910145,1.000000,0.909194,0.997148,0.878992,0.406329,0.628005,0.327147,0.380687,0.365058,0.122776,0.048669,0.538232,0.714654,14519.626672,66724.220192,163.442845,1.292272,1.0,7363,9.401603,8.0,7363,0.122776
1,multitask_attnbias_dstart_ml50_do035_b9_w01_s42,42,refine_attnbias_multi_task_w0.1,50,0.35,full_valid_ndcg@10,0.1,25,0.754081,0.973402,0.720115,0.862939,0.687993,0.582806,0.626408,0.565753,0.572398,0.586026,0.087665,0.132977,0.400190,0.694531,76365.276858,294212.917052,5929.452052,2.726150,1.0,7369,15.697245,1.0,7369,0.087665,0.713291,1.000000,0.695319,0.945953,0.619143,0.186914,0.261721,0.158355,0.171463,0.204731,0.026483,0.021165,0.087691,0.688556,13341.440172,80674.012550,26.587719,2.334955,2.0,7401,18.036887,16.0,7401,0.026483,0.727700,0.926842,0.698772,0.834618,0.669572,0.551771,0.606356,0.530170,0.538472,0.552165,0.072076,0.098976,0.397972,0.615957,71767.701876,281168.150360,7804.378162,3.145098,1.0,7395,17.873293,1.0,7395,0.072076,0.798086,1.000000,0.782929,0.955640,0.729412,0.341206,0.478226,0.288788,0.313227,0.332750,0.033405,0.025637,0.415066,0.716933,13386.767728,75279.393740,161.914007,1.792670,1.0,7394,13.006086,11.0,7394,0.033405
2,multitask_attnbias_dstart_ml50_do035_b9_w01_s2024,2024,refine_attnbias_multi_task_w0.1,50,0.35,full_valid_ndcg@10,0.1,35,0.747122,0.972426,0.713235,0.867156,0.679094,0.574105,0.606629,0.561107,0.565743,0.581110,0.169112,0.161482,0.498506,0.804265,85073.214953,292663.088750,8166.709943,2.719913,1.0,7362,15.897446,1.0,7362,0.169112,0.889683,1.000000,0.889638,0.999864,0.852099,0.343842,0.531165,0.276726,0.322945,0.316257,0.090365,0.029939,0.429913,0.652286,15423.897343,80246.537604,226.540898,1.394529,1.0,7348,11.280621,9.0,7348,0.090365,0.732697,0.972158,0.697516,0.862684,0.660390,0.548712,0.575348,0.537490,0.539938,0.558612,0.168536,0.164564,0.497905,0.733883,95458.318639,298152.667960,12353.690613,2.816597,1.0,7399,16.748209,1.0,7399,0.168536,0.815325,1.000000,0.815277,0.999865,0.752005,0.382758,0.500202,0.338229,0.360097,0.378398,0.079752,0.028544,0.448202,0.643136,16669.383613,71348.773530,226.212491,1.638825,1.0,7423,11.253940,10.0,7423,0.079752
3,multitask_attnbias_dstart_ml50_do035_b9_s7,7,refine_attnbias_multi_task_w1.0,50,0.35,full_valid_ndcg@10,1.0,25,0.741140,0.968127,0.701169,0.841042,0.674917,0.589915,0.604232,0.584575,0.587549,0.599089,0.064153,0.054342,0.394005,0.606402,69849.790407,280340.108895,2552.965280,3.011935,1.0,7373,17.845382,1.0,7373,0.064153,0.729992,0.995266,0.724066,0.978226,0.640692,0.197971,0.283338,0.161131,0.165134,0.214905,0.027996,0.022689,0.382878,0.617663,12280.778068,76506.943274,301.367851,2.080741,2.0,7394,16.620909,15.0,7394,0.027996,0.728704,0.952252,0.695395,0.845903,0.662983,0.552035,0.588850,0.537572,0.543543,0.557376,0.067010,0.079417,0.376560,0.569452,77560.711384,288977.180877,2631.266902,2.957271,1.0,7372,17.220836,1.0,7372,0.067010,0.743937,0.999864,0.724760,0.942686,0.656857,0.199282,0.310200,0.152196,0.158631,0.209191,0.028249,0.021235,0.469374,0.617411,12876.973075,68614.056475,496.250522,2.008149,2.0,7363,16.374032,14.0,7363,0.028249
4,multitask_attnbias_dstart_ml50_do035_b9_s42,42,refine_attnbias_multi_task_w1.0,50,0.35,full_valid_ndcg@10,1.0,35,0.748445,0.968937,0.705553,0.836408,0.684121,0.602575,0.615979,0.597182,0.599023,0.611855,0.061856,0.079921,0.456593,0.641888,70299.450571,281214.731226,1427.825244,2.915220,1.0,7372,17.665491,1.0,7372,0.061856,0.788496,1.000000,0.779972,0.975749,0.719152,0.264049,0.413901,0.210614,0.246850,0.249278,0.023574,0.019707,0.318521,0.667254,11338.988327,72120.057406,75.289802,1.981168,1.0,7381,16.461049,14.0,7381,0.023574,0.699354,0.954023,0.665918,0.849222,0.623899,0.504659,0.527924,0.495889,0.500473,0.514211,0.065314,0.099263,0.419608,0.702096,69466.479428,277741.623479,3273.263471,3.105882,2.0,7395,19.828262,5.0,7395,0.065314,0.795395,1.000000,0.793063,0.993103,0.726593,0.255352,0.387747,0.205621,0.230863,0.251561,0.031242,0.026259,0.315661,0.679605,12807.373775,68230.377762,79.503466,1.824452,1.0,7394,15.024750,13.0,7394,0.031242
5,multitask_attnbias_dstart_ml50_do035_b9_s2024,2024,refine_attnbias_multi_task_w1.0,50,0.35,full_valid_ndcg@10,1.0,30,0.739497,0.969508,0.688210,0.807562,0.672990,0.592206,0.612956,0.584314,0.588291,0.598530,0.059900,0.039673,0.451281,0.707955,78572.105940,291972.478347,10619.751266,3.107332,1.0,7379,18.460225,1.0,7379,0.059900,0.790523,0.999864,0.774766,0.953504,0.721091,0.297880,0.502508,0.223472,0.271520,0.259729,0.117256,0.046148,0.608920,0.633455,15157.516227,76170.374705,108.494928,1.945913,1.0,7377,17.704351,10.0,7377,0.117256,0.719612,0.968644,0.655971,0.770374,0.648119,0.569445,0.591702,0.560896,0.565076,0.575365,0.062576,0.046511,0.411542,0.593188,77629.230065,290988.614199,5850.591732,3.308690,1.0,7399,20.429382,1.0,7399,0.062576,0.803990,1.000000,0.772160,0.904217,0.740478,0.290265,0.520410,0.209346,0.269163,0.244717,0.043244,0.025775,0.577529,0.623198,14410.307229,69416.404637,69.650415,2.058197,1.0,7423,17.906103,10.0,7423,0.043244
6,attnbias_dstart_ml50_do035_b9_s7,7,refine_attnbias_single_task,50,0.35,full_valid_ndcg@10,None,40,0.755366,0.953861,0.714870,0.824671,0.699184,0.623265,0.666077,0.607399,0.615479,0.623619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.940290,1.0,7369,15.480822,1.0,7352,NaN,0.846762,1.000000,0.846665,0.999728,0.793978,0.497216,0.628223,0.442098,0.450204,0.485290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.514189,1.0,7365,8.274627,8.0,7370,NaN,0.748363,0.928494,0.714632,0.819681,0.699457,0.630482,0.684511,0.611895,0.626495,0.625430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.073398,1.0,7398,15.989402,1.0,7360,NaN,0.934451,1.000000,0.933494,0.997156,0.912365,0.529426,0.733406,0.466134,0.538743,0.485151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.254841,1.0,7385,7.575860,5.0,7382,NaN
7,attnbias_dstart_ml50_do035_b9_s42,42,refine_attnbias_single_task,50,0.35,full_valid_ndcg@10,None,20,0.741856,0.969750,0.709565,0.864487,0.673783,0.585005,0.635957,0.566501,0.577970,0.585189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.852686,1.0,7372,15.394391,1.0,7381,NaN,0.785724,0.999865,0.764719,0.935724,0.714860,0.199334,0.453522,0.115783,0.193920,0.156593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.999459,1.0,7390,15.241145,11.0,7369,NaN,0.738854,0.940484,0.708232,0.842689,0.679894,0.585965,0.658297,0.558905,0.573281,0.578959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.067767,1.0,7393,16.826283,1.0,7328,NaN,0.817886,1.000000,0.804969,0.962303,0.755813,0.345401,0.528507,0.277343,0.313648,0.321681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.698285,1.0,7348,11.890733,10.0,7349,NaN
8,attnbias_dstart_ml50_do035_b9_s2024,2024,refine_attnbias_single_task,50,0.35,full_valid_ndcg@10,None,20,0.735385,0.971475,0.702964,0.865254,0.665031,0.566216,0.612548,0.548977,0.558247,0.568592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.903287,1.0,7362,16.295182,1.0,7348,NaN,0.885738,0.999865,0.863911,0.928234,0.850981,0.428086,0.626287,0.366083,0.436179,0.388188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.851072,1.0,7413,14.057317,7.0,7380,NaN,0.723258,0.974185,0.685963,0.855571,0.648469,0.542247,0.565836,0.532469,0.534273,0.554553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.973234,1.0,7360,16.033595,1.0,7382,NaN,0.883681,0.999864,0.867159,0.949178,0.847403,0.460193,0.614253,0.412824,0.468754,0.434559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.718304,1.0,7359,12.058982,6.0,7409,NaN
9,multitask_refine_ml50_do035_s7,7,refine_multi_task_w1.0,50,0.35,full_valid_ndcg@10,1.0,15,0.732565,0.956292,0.655287,0.712502,0.670971,0.604692,0.612868,0.601089,0.601466,0.613268,0.067056,0.094597,0.450387,0.769105,71791.261270,279170.227263,814.182786,3.531017,1.0,7367,22.294421,1.0,7367,0.067056,0.711474,1.000000,0.657646,0.838091,0.619819,0.200368,0.268896,0.173962,0.185291,0.217592,0.026237,0.022837,0.305193,0.615960,12867.716649,79895.493810,8.677288,2.701468,2.0,7356,21.047580,16.0,7356,0.026237,0.728034,0.929870,0.696849,0.828133,0.671052,0.579635,0.619778,0.563730,0.569995,0.581505,0.067010,0.083028,0.400977,0.612453,74793.730785,286184.771575,3982.907754,3.262615,1.0,7372,18.480602,1.0,7372,0.067010,0.838354,0.999864,0.837206,0.996605,0.782711,0.214172,0.524107,0.104274,0.182398,0.152033,0.029879,0.027522,0.483499,0.689800,13745.783128,64698.797325,264.579771,1.553850,1.0,7363,12.813799,10.0,7363,0.029879
10,multitask_refine_ml50_do035_s42,42,refine_multi_task_w1.0,50,0.35,full_valid_ndcg@10,1.0,15,0.733665,0.968635,0.666060,0.751256,0.668249,0.604295,0.606925,0.603242,0.603530,0.614372,0.060692,0.075838,0.451052,0.705092,74687.149202,283050.310794,698.975902,3.446029,1.0,7365,21.899389,1.0,7365,0.060692,0.673060,1.000000,0.653704,0.939640,0.565251,0.113424,0.184599,0.082418,0.084585,0.136265,0.023007,0.016782,0.315469,0.519827,11669.578547,73839.383908,58.406232,2.516173,2.0,7389,20.594668,16.0,7389,0.023007,0.705052,0.957404,0.636362,0.741176,0.632860,0.541467,0.562677,0.532959,0.536038,0.549325,0.058012,0.043391,0.399459,0.577958,68641.837342,280653.523074,1439.108608,3.551589,1.0,7395,22.120622,1.0,7395,0.058012,0.777200,0.997971,0.743862,0.901542,0.705348,0.168454,0.345821,0.104082,0.144036,0.151960,0.023938,0.015615,0.328510,0.598729,12373.943222,69086.004066,76.980443,2.127536,1.0,7394,18.619015,14.0,7394,0.023938
11,multitask_refine_ml50_do035_s2024,2024,refine_multi_task_w1.0,50,0.35,full_valid_ndcg@10,1.0,30,0.737569,0.941862,0.692600,0.805665,0.680081,0.606361,0.619596,0.601399,0.604011,0.614094,0.065185,0.111175,0.456701,0.599946,76760.182247,292111.312040,4485.440184,3.248408,1.0,7379,19.513213,1.0,7379,0.065185,0.749001,1.000000,0.739492,0.973295,0.666433,0.182997,0.359089,0.119428,0.161312,0.163382,0.032805,0.026196,0.420767,0.609055,13892.641159,76083.712405,142.218559,2.150874,2.0,7377,18.026434,15.0,7377,0.032805,0.667442,0.919854,0.614013,0.757805,0.596464,0.491790,0.510339,0.484654,0.488039,0.501295,0.067982,0.096633,0.396675,0.574537,72902.414007,289346.878025,4615.686349,3.730099,2.0,7399,24.248277,8.0,7399,0.067982,0.891050,1.000000,0.874604,0.952445,0.856683,0.417862,0.578607,0.362217,0.405901,0.391706,0.030581,0.025305,0.471912,0.675603,13451.263567,71803.668668,124.446563,1.632628,1.0,7423,13.242624,8.0,7423,0.030581
12,refine_ml50_do035_s7,7,refine_single_task,50,0.35,full_valid_ndcg@10,None,25,0.728826,0.961737,0.696223,0.857259,0.660451,0.577254,0.611043,0.565802,0.575315,0.581977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.112483,1.0,7370,16.832724,1.0,7389,NaN,0.872416,1.000000,0.859037,0.957678,0.831208,0.403018,0.656933,0.324827,0.417493,0.345750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.690586,1.0,7372,12.025805,7.0,7363,NaN,0.710532,0.961611,0.679314,0.863747,0.634333,0.520338,0.591033,0.494720,0.509918,0.517415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.998378,2.0,7398,16.715353,5.0,7360,NaN,0.872246,1.000000,0.872156,0.999729,0.829215,0.469188,0.671498,0.408015,0.483744,0.427149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.497089,1.0,7385,9.397047,6.0,7382,NaN
13,refine_ml50_do035_s42,42,refine_single_task,50,0.35,full_valid_ndcg@10,None,50,0.735378,0.977276,0.697410,0.854186,0.663510,0.568693,0.606441,0.555385,0.565093,0.572753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.952928,1.0,7393,16.592112,1.0,7328,NaN,0.891774,1.000000,0.868726,0.926375,0.858375,0.456024,0.640631,0.399455,0.467411,0.419230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.760207,1.0,7348,13.317594,6.0,7349,NaN,0.735378,0.977276,0.697410,0.854186,0.663510,0.568693,0.606441,0.555385,0.565093,0.572753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.952928,1.0,7393,16.592112,1.0,7328,NaN,0.891774,1.000000,0.868726,0.926375,0.858375,0.456024,0.640631,0.399455,0.467411,0.419230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.760207,1.0,7348,13.317594,6.0,7349,NaN
14,refine_ml50_do035_s2024,2024,refine_single_task,50,0.35,full_valid_ndcg@10,None,5,0.741573,0.992973,0.713154,0.906351,0.664353,0.572972,0.597043,0.563603,0.567069,0.582973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.688514,1.0,7400,13.592567,1.0,7373,NaN,0.775861,1.000000,0.727453,0.850196,0.707187,0.257972,0.431769,0.203548,0.264514,0.234183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.554370,1.0,7403,19.897857,13.0,7372,NaN,0.674192,0.974457,0.629209,0.837364,0.583494,0.464462,0.505283,0.449908,0.459902,0.471125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.201359,2.0,7360,20.284747,10.0,7382,NaN,0.896385,1.000000,0.880219,0.951352,0.863615,0.492040,0.657579,0.440554,0.499663,0.460484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.608778,1.0,7359,11.161695,6.0,7409,NaN

In [25]:
import pandas as pd

candidate_cols = [
    c for c in df_compare.columns
    if c.startswith(('best_valid_', 'best_test_at_best_valid_'))
]

summary_metric_cols = []
for c in candidate_cols:
    converted = pd.to_numeric(df_compare[c], errors='coerce')
    if converted.notna().any():
        df_compare[c] = converted
        summary_metric_cols.append(c)

def summary_metric_sort_key(col):
    if col.startswith('best_valid_'):
        group_rank = 0
        name = col[len('best_valid_'):]
    elif col.startswith('best_test_at_best_valid_'):
        group_rank = 1
        name = col[len('best_test_at_best_valid_'):]
    else:
        group_rank = 99
        name = col

    metric_order = [
        'full_ndcg@10', 'full_hr@10', 'full_ndcg@5', 'full_hr@5', 'full_mrr',
        'sampled_ndcg@10', 'sampled_hr@10', 'sampled_ndcg@5', 'sampled_hr@5', 'sampled_mrr',
        'task_accuracy', 'task_macro_f1', 'task_top5_accuracy', 'task_top10_accuracy',
        'task_time_mae', 'task_time_rmse', 'task_time_median_ae',
    ]

    try:
        metric_rank = metric_order.index(name)
    except ValueError:
        metric_rank = 999

    return (group_rank, metric_rank, name)

summary_metric_cols = sorted(summary_metric_cols, key=summary_metric_sort_key)

print('num summary metric cols =', len(summary_metric_cols))
print(summary_metric_cols)

summary_compare = df_compare.groupby('variant')[summary_metric_cols].agg(['mean', 'std'])

with pd.option_context(
    'display.max_columns', None,
    'display.max_colwidth', None,
    'display.width', 2000,
):
    display(summary_compare)

num summary metric cols = 48
['best_valid_full_ndcg@10', 'best_valid_full_hr@10', 'best_valid_full_ndcg@5', 'best_valid_full_hr@5', 'best_valid_full_mrr', 'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10', 'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5', 'best_valid_sampled_mrr', 'best_valid_task_accuracy', 'best_valid_task_macro_f1', 'best_valid_task_top5_accuracy', 'best_valid_task_top10_accuracy', 'best_valid_task_time_mae', 'best_valid_task_time_rmse', 'best_valid_task_time_median_ae', 'best_valid_full_mean_rank', 'best_valid_full_median_rank', 'best_valid_full_num_eval_users', 'best_valid_sampled_mean_rank', 'best_valid_sampled_median_rank', 'best_valid_sampled_num_eval_users', 'best_valid_task_top1_accuracy', 'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10', 'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5', 'best_test_at_best_valid_full_mrr', 'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10', 'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5', 'best_test_at_best_valid_sampled_mrr', 'best_test_at_best_valid_task_accuracy', 'best_test_at_best_valid_task_macro_f1', 'best_test_at_best_valid_task_top5_accuracy', 'best_test_at_best_valid_task_top10_accuracy', 'best_test_at_best_valid_task_time_mae', 'best_test_at_best_valid_task_time_rmse', 'best_test_at_best_valid_task_time_median_ae', 'best_test_at_best_valid_full_mean_rank', 'best_test_at_best_valid_full_median_rank', 'best_test_at_best_valid_full_num_eval_users', 'best_test_at_best_valid_sampled_mean_rank', 'best_test_at_best_valid_sampled_median_rank', 'best_test_at_best_valid_sampled_num_eval_users', 'best_test_at_best_valid_task_top1_accuracy']

                                best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_valid_task_accuracy           best_valid_task_macro_f1           best_valid_task_top5_accuracy           best_valid_task_top10_accuracy           best_valid_task_time_mae              best_valid_task_time_rmse              best_valid_task_time_median_ae              best_valid_full_mean_rank           best_valid_full_median_rank      best_valid_full_num_eval_users            best_valid_sampled_mean_rank           best_valid_sampled_median_rank      best_valid_sampled_num_eval_users            best_valid_task_top1_accuracy           best_test_at_best_valid_full_ndcg@10           best_test_at_best_valid_full_hr@10           best_test_at_best_valid_full_ndcg@5           best_test_at_best_valid_full_hr@5           best_test_at_best_valid_full_mrr           best_test_at_best_valid_sampled_ndcg@10           best_test_at_best_valid_sampled_hr@10           best_test_at_best_valid_sampled_ndcg@5           best_test_at_best_valid_sampled_hr@5           best_test_at_best_valid_sampled_mrr           best_test_at_best_valid_task_accuracy           best_test_at_best_valid_task_macro_f1           best_test_at_best_valid_task_top5_accuracy           best_test_at_best_valid_task_top10_accuracy           best_test_at_best_valid_task_time_mae              best_test_at_best_valid_task_time_rmse              best_test_at_best_valid_task_time_median_ae             best_test_at_best_valid_full_mean_rank           best_test_at_best_valid_full_median_rank          best_test_at_best_valid_full_num_eval_users            best_test_at_best_valid_sampled_mean_rank           best_test_at_best_valid_sampled_median_rank            \
                                                   mean       std                  mean       std                   mean       std                 mean       std                mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                     mean       std                     mean       std                          mean       std                           mean       std                     mean          std                      mean          std                           mean          std                      mean       std                        mean  std                           mean        std                         mean       std                           mean  std                              mean        std                          mean       std                                 mean       std                               mean       std                                mean       std                              mean       std                             mean       std                                    mean       std                                  mean       std                                   mean       std                                 mean       std                                mean       std                                  mean       std                                  mean       std                                       mean       std                                        mean       std                                  mean          std                                   mean          std                                        mean         std                                   mean       std                                     mean      std                                        mean        std                                      mean       std                                        mean       std
variant
refine_attnbias_multi_task_w0.1                0.749547  0.003930              0.972538  0.000814               0.717129  0.003529             0.868659  0.006601            0.681781  0.005396                   0.571194  0.013307                 0.617469  0.010026                  0.552717  0.018699                0.559295  0.017255               0.574322  0.016202                 0.105397  0.056958                 0.121748  0.046379                      0.433134  0.056614                       0.741460  0.056564             81907.220732  4815.692996             292403.491059  1952.213152                    6959.391739  1129.127128                  2.699330  0.041171                         1.0  0.0                    7367.666667   5.131601                    15.697597  0.199673                            1.0  0.0                       7367.666667   5.131601                      0.105397  0.056958                             0.837707  0.108231                           1.000000  0.000000                            0.831384  0.118241                          0.980988  0.030372                         0.783411  0.142895                                0.312362  0.113044                              0.473630  0.189799                               0.254076  0.086646                             0.291699  0.108055                            0.295348  0.082183                              0.079875  0.048996                              0.033258  0.014050                                   0.351945  0.235172                                    0.685165  0.031322                          14428.321395  1044.226727                           75881.590115  7933.394711                                  138.857154  102.218690                               1.673919  0.574753                                 1.333333  0.57735                                 7370.666667  27.319102                                 12.906370  4.541402                                   11.000000  4.358899
refine_attnbias_multi_task_w1.0                0.743028  0.004763              0.968857  0.000694               0.698311  0.009018             0.828337  0.018140            0.677342  0.005949                   0.594899  0.006746                 0.611056  0.006100                  0.588691  0.007355                0.591621  0.006421               0.603158  0.007537                 0.061969  0.002129                 0.057979  0.020369                      0.433959  0.034703                       0.652082  0.051538             72907.115639  4911.174492             284509.106156  6478.247016                    4866.847263  5013.822232                  3.011496  0.096057                         1.0  0.0                    7374.666667   3.785939                    17.990366  0.416732                            1.0  0.0                       7374.666667   3.785939                      0.061969  0.002129                             0.769670  0.034377                           0.998377  0.002695                            0.759601  0.030885                          0.969159  0.013614                         0.693645  0.045869                                0.253300  0.050815                              0.399915  0.110252                               0.198406  0.032915                             0.227835  0.055684                            0.241304  0.023452                              0.056275  0.052857                              0.029515  0.014482                                   0.436773  0.152517                                    0.639457  0.025334                          12925.760874  1989.294082                           74932.458462  2441.417493                                  161.717527  122.074997                               2.002607  0.069924                                 1.333333  0.57735                                 7384.000000   8.888194                                 16.928770  0.676413                                   13.000000  2.645751
refine_attnbias_single_task                    0.744203  0.010195              0.965029  0.009710               0.709133  0.005965             0.851471  0.023212            0.679333  0.017740                   0.591495  0.029073                 0.638194  0.026835                  0.574292  0.029980                0.583899  0.029073               0.592467  0.028226                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                      NaN          NaN                       NaN          NaN                            NaN          NaN                  2.898754  0.043978                         1.0  0.0                    7367.666667   5.131601                    15.723465  0.497004                            1.0  0.0                       7360.333333  18.009257                           NaN       NaN                             0.839408  0.050411                           0.999910  0.000078                            0.825099  0.052996                          0.954562  0.039294                         0.786607  0.068359                                0.374879  0.155906                              0.569344  0.100310                               0.307988  0.170739                             0.360101  0.144087                            0.343357  0.168872                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN                                   NaN          NaN                                    NaN          NaN                                         NaN         NaN                               1.788240  0.248662                                 1.000000  0.00000                                 7389.333333  24.006943                                 12.524363  3.727674                                    8.666667  2.081666
refine_multi_task_w1.0                         0.734600  0.002629              0.955596  0.013400               0.671316  0.019204             0.756474  0.046800            0.673100  0.006196                   0.605116  0.001097                 0.613130  0.006340                  0.601910  0.001164                0.603003  0.001352               0.613911  0.000574                 0.064311  0.003270                 0.093870  0.017680                      0.452714  0.003470                       0.691381  0.085409             74412.864240  2495.790075             284777.283366  6641.140301                    1999.532957  2153.629311                  3.408484  0.144997                         1.0  0.0                    7370.333333   7.571878                    21.235674  1.504715                            1.0  0.0                       7370.333333   7.571878                      0.064311  0.003270                             0.711178  0.037972                           1.000000  0.000000                            0.683614  0.048432                          0.917009  0.070386                         0.617168  0.050643                                0.165596  0.046010                              0.270861  0.087262                               0.125269  0.046051                             0.143729  0.052605                            0.172413  0.041409                              0.027350  0.004993                              0.021938  0.004771                                   0.347143  0.063967                                    0.581614  0.053620                          12809.978785  1112.655423                           76606.196708  3061.675876                                   69.767360   67.491660                               2.456172  0.280158                                 2.000000  0.00000                                 7374.000000  16.703293                                 19.889560  1.629329                                   15.666667  0.577350
refine_single_task                             0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                      NaN          NaN                       NaN          NaN                            NaN          NaN                  2.917975  0.214135                         1.0  0.0                    7387.666667  15.695010                    15.672468  1.805260                            1.0  0.0                       7363.333333  31.628047                           NaN       NaN                             0.846684  0.062093                           1.000000  0.000000                            0.818405  0.078916                          0.911416  0.055280                         0.798923  0.080599                                0.372338  0.102528                              0.576445  0.125558                               0.309277  0.098875                             0.383139  0.105721                            0.333054  0.093175                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN                                   NaN          NaN                                    NaN          NaN                                         NaN         NaN                               2.001721  0.479872                                 1.000000  0.00000                                 7374.333333  27.574142                                 15.080419  4.221725                                    8.666667  3.785939

                                best_test_at_best_valid_sampled_num_eval_users            best_test_at_best_valid_task_top1_accuracy
                                                                          mean        std                                       mean       std
variant
refine_attnbias_multi_task_w0.1                                    7370.666667  27.319102                                   0.079875  0.048996
refine_attnbias_multi_task_w1.0                                    7384.000000   8.888194                                   0.056275  0.052857
refine_attnbias_single_task                                        7373.000000   6.082763                                        NaN       NaN
refine_multi_task_w1.0                                             7374.000000  16.703293                                   0.027350  0.004993
refine_single_task                                                 7361.333333  11.590226                                        NaN       NaN

## What to look at

Read the results in this order:
- compare `refine_single_task` vs `refine_attnbias_single_task`
- compare `refine_multi_task_w1.0` vs `refine_attnbias_multi_task_w1.0`
- compare `refine_attnbias_multi_task_w1.0` vs `refine_attnbias_multi_task_w0.1`
- then decide whether refine behaves like anchor or shows a different trade-off pattern