# SASRec Time-Aware BPI2012 Colab Train (`anchor_ml20` baseline)

Colab notebook for the next time-aware SASRec experiment after choosing `anchor_ml20` as the final baseline.

Goals:
- reuse the completed `anchor_ml20` baseline results
- train only the new time-aware runs
- compare baseline vs `8-bucket` vs `9-bucket`
- evaluate under both `NDCG@10` and `NDCG@5` model-selection criteria

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
TIMEAWARE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10'
TIMEAWARE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('TIMEAWARE_NDCG10_OUTPUT_DIR:', TIMEAWARE_NDCG10_OUTPUT_DIR)
print('TIMEAWARE_NDCG5_OUTPUT_DIR:', TIMEAWARE_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
TIMEAWARE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10
TIMEAWARE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG10_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `anchor_ml20`
- `hidden_units=32, num_blocks=2, num_heads=1, maxlen=20, lr=0.001, dropout=0.2`
- seeds: `42`, `2024`, `7`

Comparison targets:
- baseline (reuse existing completed runs)
- time-aware `8-bucket`
- time-aware `9-bucket`

Time-aware design:
- `x = item_embedding + positional_embedding + time_embedding`
- time source: `delta_prev_seconds`

## Check existing baseline runs

These baseline runs should already exist and must not be retrained.

In [10]:
from pathlib import Path

baseline_ndcg10_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
]
baseline_ndcg5_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
]

for label, output_dir, run_names in [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR), baseline_ndcg10_runs),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR), baseline_ndcg5_runs),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
anchor_ml20_s42 EXISTS
anchor_ml20_s2024 EXISTS
anchor_ml20_s7 EXISTS
================================================================================
Baseline NDCG@5
anchor_ml20_s42 EXISTS
anchor_ml20_s2024 EXISTS
anchor_ml20_s7 EXISTS

## Check planned time-aware runs

Only train runs that are still missing.

In [11]:
planned_ndcg10 = [
    'timeaware_anchor_ml20_b8_s42',
    'timeaware_anchor_ml20_b8_s2024',
    'timeaware_anchor_ml20_b8_s7',
    'timeaware_anchor_ml20_b9_s42',
    'timeaware_anchor_ml20_b9_s2024',
    'timeaware_anchor_ml20_b9_s7',
]
planned_ndcg5 = [
    'timeaware_anchor_ml20_b8_s42',
    'timeaware_anchor_ml20_b8_s2024',
    'timeaware_anchor_ml20_b8_s7',
    'timeaware_anchor_ml20_b9_s42',
    'timeaware_anchor_ml20_b9_s2024',
    'timeaware_anchor_ml20_b9_s7',
]

for label, output_dir, run_names in [
    ('Time-aware NDCG@10', Path(TIMEAWARE_NDCG10_OUTPUT_DIR), planned_ndcg10),
    ('Time-aware NDCG@5', Path(TIMEAWARE_NDCG5_OUTPUT_DIR), planned_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Time-aware NDCG@10
timeaware_anchor_ml20_b8_s42 OK
timeaware_anchor_ml20_b8_s2024 OK
timeaware_anchor_ml20_b8_s7 OK
timeaware_anchor_ml20_b9_s42 OK
timeaware_anchor_ml20_b9_s2024 OK
timeaware_anchor_ml20_b9_s7 OK
================================================================================
Time-aware NDCG@5
timeaware_anchor_ml20_b8_s42 OK
timeaware_anchor_ml20_b8_s2024 OK
timeaware_anchor_ml20_b8_s7 OK
timeaware_anchor_ml20_b9_s42 OK
timeaware_anchor_ml20_b9_s2024 OK
timeaware_anchor_ml20_b9_s7 OK

## Train time-aware runs for `NDCG@10`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_anchor_ml20_b8_s42

In [12]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b8_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42
epoch=1, loss=0.6426
epoch=2, loss=0.3038
epoch=3, loss=0.2099
epoch=4, loss=0.1665
epoch=5, loss=0.1410
valid [full], NDCG@5: 0.6361, HR@5: 0.7458, NDCG@10: 0.7103, HR@10: 0.9801, MRR: 0.6324
valid [sampled], NDCG@5: 0.5426, HR@5: 0.5440, NDCG@10: 0.5502, HR@10: 0.5689, MRR: 0.5602
test [full], NDCG@5: 0.7578, HR@5: 0.8828, NDCG@10: 0.7957, HR@10: 0.9991, MRR: 0.7315
test [sampled], NDCG@5: 0.1689, HR@5: 0.2476, NDCG@10: 0.2490, HR@10: 0.4949, MRR: 0.2017
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/sasrec_best.pth
epoch=6, loss=0.1241
epoch=7, loss=0.1162
epoch=8, loss=0.1102
epoch=9, loss=0.1048
epoch=10, loss=0.0997
valid [full], NDCG@5: 0.6420, HR@5: 0.7662, NDCG@10: 0.7102, HR@10: 0.9728, MRR: 0.6334
valid [sampled], NDCG@5: 0.5365, HR@5: 0.5412, NDCG@10: 0.5486, HR@10: 0.5795, MRR: 0.5550
test [full], NDCG@5: 0.8332, HR@5: 0.9364, NDCG@10: 0.8538, HR@10: 1.0000, MRR: 0.8066
test [sampled], NDCG@5: 0.4007, HR@5: 0.4282, NDCG@10: 0.4438, HR@10: 0.5645, MRR: 0.4331
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0987
epoch=12, loss=0.0968
epoch=13, loss=0.0940
epoch=14, loss=0.0924
epoch=15, loss=0.0919
valid [full], NDCG@5: 0.6694, HR@5: 0.8324, NDCG@10: 0.7149, HR@10: 0.9763, MRR: 0.6366
valid [sampled], NDCG@5: 0.5202, HR@5: 0.5261, NDCG@10: 0.5374, HR@10: 0.5809, MRR: 0.5427
test [full], NDCG@5: 0.7941, HR@5: 0.9667, NDCG@10: 0.8049, HR@10: 1.0000, MRR: 0.7390
test [sampled], NDCG@5: 0.3235, HR@5: 0.3359, NDCG@10: 0.3792, HR@10: 0.5150, MRR: 0.3711
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/sasrec_best.pth
epoch=16, loss=0.0908
epoch=17, loss=0.0891
epoch=18, loss=0.0903
epoch=19, loss=0.0866
epoch=20, loss=0.0882
valid [full], NDCG@5: 0.6571, HR@5: 0.8058, NDCG@10: 0.7058, HR@10: 0.9596, MRR: 0.6309
valid [sampled], NDCG@5: 0.4992, HR@5: 0.5032, NDCG@10: 0.5163, HR@10: 0.5574, MRR: 0.5227
test [full], NDCG@5: 0.7916, HR@5: 0.9989, NDCG@10: 0.7919, HR@10: 1.0000, MRR: 0.7229
test [sampled], NDCG@5: 0.3435, HR@5: 0.3474, NDCG@10: 0.3824, HR@10: 0.4733, MRR: 0.3898
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0858
epoch=22, loss=0.0864
epoch=23, loss=0.0851
epoch=24, loss=0.0874
epoch=25, loss=0.0838
valid [full], NDCG@5: 0.6260, HR@5: 0.8025, NDCG@10: 0.6699, HR@10: 0.9406, MRR: 0.5907
valid [sampled], NDCG@5: 0.4400, HR@5: 0.4523, NDCG@10: 0.4648, HR@10: 0.5303, MRR: 0.4634
test [full], NDCG@5: 0.7931, HR@5: 0.9996, NDCG@10: 0.7932, HR@10: 1.0000, MRR: 0.7233
test [sampled], NDCG@5: 0.3176, HR@5: 0.3253, NDCG@10: 0.3549, HR@10: 0.4456, MRR: 0.3654
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0829
epoch=27, loss=0.0843
epoch=28, loss=0.0841
epoch=29, loss=0.0835
epoch=30, loss=0.0823
valid [full], NDCG@5: 0.6401, HR@5: 0.8322, NDCG@10: 0.6811, HR@10: 0.9611, MRR: 0.5970
valid [sampled], NDCG@5: 0.4443, HR@5: 0.4590, NDCG@10: 0.4702, HR@10: 0.5402, MRR: 0.4678
test [full], NDCG@5: 0.8037, HR@5: 0.9993, NDCG@10: 0.8039, HR@10: 1.0000, MRR: 0.7379
test [sampled], NDCG@5: 0.3524, HR@5: 0.3627, NDCG@10: 0.3823, HR@10: 0.4589, MRR: 0.3948
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0843
epoch=32, loss=0.0814
epoch=33, loss=0.0824
epoch=34, loss=0.0813
epoch=35, loss=0.0799
valid [full], NDCG@5: 0.6370, HR@5: 0.8119, NDCG@10: 0.6741, HR@10: 0.9302, MRR: 0.5990
valid [sampled], NDCG@5: 0.4498, HR@5: 0.4648, NDCG@10: 0.4793, HR@10: 0.5576, MRR: 0.4733
test [full], NDCG@5: 0.8013, HR@5: 0.9996, NDCG@10: 0.8014, HR@10: 1.0000, MRR: 0.7340
test [sampled], NDCG@5: 0.3413, HR@5: 0.3546, NDCG@10: 0.3750, HR@10: 0.4623, MRR: 0.3848
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0800
epoch=37, loss=0.0811
epoch=38, loss=0.0810
epoch=39, loss=0.0809
epoch=40, loss=0.0802
valid [full], NDCG@5: 0.6315, HR@5: 0.7988, NDCG@10: 0.6719, HR@10: 0.9279, MRR: 0.5977
valid [sampled], NDCG@5: 0.4484, HR@5: 0.4631, NDCG@10: 0.4798, HR@10: 0.5617, MRR: 0.4721
test [full], NDCG@5: 0.7969, HR@5: 0.9997, NDCG@10: 0.7970, HR@10: 1.0000, MRR: 0.7286
test [sampled], NDCG@5: 0.3410, HR@5: 0.3506, NDCG@10: 0.3708, HR@10: 0.4461, MRR: 0.3839
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0807
epoch=42, loss=0.0807
epoch=43, loss=0.0821
epoch=44, loss=0.0793
epoch=45, loss=0.0818
valid [full], NDCG@5: 0.6320, HR@5: 0.7961, NDCG@10: 0.6791, HR@10: 0.9453, MRR: 0.6004
valid [sampled], NDCG@5: 0.4469, HR@5: 0.4613, NDCG@10: 0.4792, HR@10: 0.5636, MRR: 0.4712
test [full], NDCG@5: 0.8118, HR@5: 0.9997, NDCG@10: 0.8119, HR@10: 1.0000, MRR: 0.7482
test [sampled], NDCG@5: 0.3694, HR@5: 0.3806, NDCG@10: 0.3972, HR@10: 0.4696, MRR: 0.4101
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0763
epoch=47, loss=0.0805
epoch=48, loss=0.0777
epoch=49, loss=0.0788
epoch=50, loss=0.0793
valid [full], NDCG@5: 0.6442, HR@5: 0.8244, NDCG@10: 0.6855, HR@10: 0.9535, MRR: 0.6054
valid [sampled], NDCG@5: 0.4491, HR@5: 0.4653, NDCG@10: 0.4787, HR@10: 0.5583, MRR: 0.4729
test [full], NDCG@5: 0.8008, HR@5: 0.9999, NDCG@10: 0.8009, HR@10: 1.0000, MRR: 0.7337
test [sampled], NDCG@5: 0.3476, HR@5: 0.3607, NDCG@10: 0.3786, HR@10: 0.4598, MRR: 0.3894
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s42/sasrec_last.pth

### timeaware_anchor_ml20_b8_s2024

In [13]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b8_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024
epoch=1, loss=0.6654
epoch=2, loss=0.3158
epoch=3, loss=0.2140
epoch=4, loss=0.1656
epoch=5, loss=0.1401
valid [full], NDCG@5: 0.6224, HR@5: 0.7353, NDCG@10: 0.7023, HR@10: 0.9882, MRR: 0.6187
valid [sampled], NDCG@5: 0.5199, HR@5: 0.5203, NDCG@10: 0.5285, HR@10: 0.5485, MRR: 0.5395
test [full], NDCG@5: 0.7852, HR@5: 0.8973, NDCG@10: 0.8148, HR@10: 0.9903, MRR: 0.7618
test [sampled], NDCG@5: 0.2319, HR@5: 0.3067, NDCG@10: 0.2923, HR@10: 0.4919, MRR: 0.2577
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=6, loss=0.1274
epoch=7, loss=0.1160
epoch=8, loss=0.1083
epoch=9, loss=0.1060
epoch=10, loss=0.1027
valid [full], NDCG@5: 0.6413, HR@5: 0.7734, NDCG@10: 0.7055, HR@10: 0.9715, MRR: 0.6284
valid [sampled], NDCG@5: 0.5289, HR@5: 0.5298, NDCG@10: 0.5358, HR@10: 0.5521, MRR: 0.5479
test [full], NDCG@5: 0.8010, HR@5: 0.9097, NDCG@10: 0.8303, HR@10: 0.9993, MRR: 0.7775
test [sampled], NDCG@5: 0.2423, HR@5: 0.3089, NDCG@10: 0.3120, HR@10: 0.5247, MRR: 0.2744
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=11, loss=0.1002
epoch=12, loss=0.0972
epoch=13, loss=0.0963
epoch=14, loss=0.0933
epoch=15, loss=0.0913
valid [full], NDCG@5: 0.6784, HR@5: 0.8569, NDCG@10: 0.7153, HR@10: 0.9714, MRR: 0.6395
valid [sampled], NDCG@5: 0.5392, HR@5: 0.5426, NDCG@10: 0.5475, HR@10: 0.5692, MRR: 0.5585
test [full], NDCG@5: 0.7741, HR@5: 0.9375, NDCG@10: 0.7945, HR@10: 1.0000, MRR: 0.7273
test [sampled], NDCG@5: 0.2666, HR@5: 0.2917, NDCG@10: 0.3299, HR@10: 0.4929, MRR: 0.3122
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=16, loss=0.0902
epoch=17, loss=0.0896
epoch=18, loss=0.0901
epoch=19, loss=0.0886
epoch=20, loss=0.0862
valid [full], NDCG@5: 0.6699, HR@5: 0.8337, NDCG@10: 0.7149, HR@10: 0.9739, MRR: 0.6387
valid [sampled], NDCG@5: 0.5334, HR@5: 0.5378, NDCG@10: 0.5425, HR@10: 0.5667, MRR: 0.5517
test [full], NDCG@5: 0.7855, HR@5: 0.9177, NDCG@10: 0.8128, HR@10: 1.0000, MRR: 0.7524
test [sampled], NDCG@5: 0.3440, HR@5: 0.3615, NDCG@10: 0.3952, HR@10: 0.5251, MRR: 0.3845
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0875
epoch=22, loss=0.0861
epoch=23, loss=0.0852
epoch=24, loss=0.0849
epoch=25, loss=0.0850
valid [full], NDCG@5: 0.6851, HR@5: 0.8567, NDCG@10: 0.7224, HR@10: 0.9734, MRR: 0.6477
valid [sampled], NDCG@5: 0.5372, HR@5: 0.5482, NDCG@10: 0.5492, HR@10: 0.5855, MRR: 0.5547
test [full], NDCG@5: 0.7923, HR@5: 0.9361, NDCG@10: 0.8133, HR@10: 1.0000, MRR: 0.7526
test [sampled], NDCG@5: 0.3594, HR@5: 0.3721, NDCG@10: 0.4059, HR@10: 0.5211, MRR: 0.4001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=26, loss=0.0816
epoch=27, loss=0.0842
epoch=28, loss=0.0833
epoch=29, loss=0.0850
epoch=30, loss=0.0812
valid [full], NDCG@5: 0.6905, HR@5: 0.8556, NDCG@10: 0.7295, HR@10: 0.9774, MRR: 0.6548
valid [sampled], NDCG@5: 0.5338, HR@5: 0.5438, NDCG@10: 0.5515, HR@10: 0.5995, MRR: 0.5541
test [full], NDCG@5: 0.7990, HR@5: 0.9336, NDCG@10: 0.8206, HR@10: 1.0000, MRR: 0.7621
test [sampled], NDCG@5: 0.3674, HR@5: 0.3770, NDCG@10: 0.4126, HR@10: 0.5232, MRR: 0.4086
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=31, loss=0.0836
epoch=32, loss=0.0839
epoch=33, loss=0.0821
epoch=34, loss=0.0837
epoch=35, loss=0.0825
valid [full], NDCG@5: 0.6447, HR@5: 0.7629, NDCG@10: 0.7143, HR@10: 0.9756, MRR: 0.6378
valid [sampled], NDCG@5: 0.5438, HR@5: 0.5515, NDCG@10: 0.5597, HR@10: 0.6018, MRR: 0.5615
test [full], NDCG@5: 0.7765, HR@5: 0.8993, NDCG@10: 0.8100, HR@10: 1.0000, MRR: 0.7487
test [sampled], NDCG@5: 0.3751, HR@5: 0.3835, NDCG@10: 0.4203, HR@10: 0.5292, MRR: 0.4157
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0822
epoch=37, loss=0.0808
epoch=38, loss=0.0812
epoch=39, loss=0.0802
epoch=40, loss=0.0787
valid [full], NDCG@5: 0.6706, HR@5: 0.8096, NDCG@10: 0.7242, HR@10: 0.9758, MRR: 0.6497
valid [sampled], NDCG@5: 0.5417, HR@5: 0.5530, NDCG@10: 0.5623, HR@10: 0.6174, MRR: 0.5603
test [full], NDCG@5: 0.7798, HR@5: 0.8993, NDCG@10: 0.8136, HR@10: 1.0000, MRR: 0.7531
test [sampled], NDCG@5: 0.3753, HR@5: 0.3850, NDCG@10: 0.4205, HR@10: 0.5297, MRR: 0.4158
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0810
epoch=42, loss=0.0825
epoch=43, loss=0.0800
epoch=44, loss=0.0799
epoch=45, loss=0.0781
valid [full], NDCG@5: 0.6648, HR@5: 0.8029, NDCG@10: 0.7216, HR@10: 0.9773, MRR: 0.6461
valid [sampled], NDCG@5: 0.5472, HR@5: 0.5588, NDCG@10: 0.5611, HR@10: 0.6014, MRR: 0.5629
test [full], NDCG@5: 0.8616, HR@5: 0.9240, NDCG@10: 0.8869, HR@10: 1.0000, MRR: 0.8516
test [sampled], NDCG@5: 0.4108, HR@5: 0.4695, NDCG@10: 0.4660, HR@10: 0.6393, MRR: 0.4335
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0791
epoch=47, loss=0.0801
epoch=48, loss=0.0799
epoch=49, loss=0.0776
epoch=50, loss=0.0796
valid [full], NDCG@5: 0.6681, HR@5: 0.8072, NDCG@10: 0.7221, HR@10: 0.9751, MRR: 0.6474
valid [sampled], NDCG@5: 0.5425, HR@5: 0.5557, NDCG@10: 0.5587, HR@10: 0.6062, MRR: 0.5593
test [full], NDCG@5: 0.7810, HR@5: 0.9005, NDCG@10: 0.8131, HR@10: 1.0000, MRR: 0.7526
test [sampled], NDCG@5: 0.3838, HR@5: 0.3968, NDCG@10: 0.4304, HR@10: 0.5464, MRR: 0.4227
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s2024/sasrec_last.pth

### timeaware_anchor_ml20_b8_s7

In [14]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b8_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7
epoch=1, loss=0.6868
epoch=2, loss=0.3246
epoch=3, loss=0.2269
epoch=4, loss=0.1721
epoch=5, loss=0.1438
valid [full], NDCG@5: 0.6513, HR@5: 0.7788, NDCG@10: 0.7040, HR@10: 0.9438, MRR: 0.6369
valid [sampled], NDCG@5: 0.5570, HR@5: 0.5583, NDCG@10: 0.5603, HR@10: 0.5687, MRR: 0.5723
test [full], NDCG@5: 0.6535, HR@5: 0.9260, NDCG@10: 0.6711, HR@10: 0.9776, MRR: 0.5739
test [sampled], NDCG@5: 0.1664, HR@5: 0.1686, NDCG@10: 0.1840, HR@10: 0.2262, MRR: 0.2136
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=6, loss=0.1281
epoch=7, loss=0.1195
epoch=8, loss=0.1087
epoch=9, loss=0.1056
epoch=10, loss=0.1012
valid [full], NDCG@5: 0.6464, HR@5: 0.7906, NDCG@10: 0.6939, HR@10: 0.9366, MRR: 0.6259
valid [sampled], NDCG@5: 0.5323, HR@5: 0.5328, NDCG@10: 0.5351, HR@10: 0.5419, MRR: 0.5483
test [full], NDCG@5: 0.6844, HR@5: 0.9667, NDCG@10: 0.6949, HR@10: 0.9973, MRR: 0.5961
test [sampled], NDCG@5: 0.1653, HR@5: 0.1698, NDCG@10: 0.1916, HR@10: 0.2555, MRR: 0.2167
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1001
epoch=12, loss=0.0968
epoch=13, loss=0.0926
epoch=14, loss=0.0927
epoch=15, loss=0.0925
valid [full], NDCG@5: 0.6627, HR@5: 0.8310, NDCG@10: 0.6967, HR@10: 0.9376, MRR: 0.6278
valid [sampled], NDCG@5: 0.5298, HR@5: 0.5312, NDCG@10: 0.5359, HR@10: 0.5509, MRR: 0.5488
test [full], NDCG@5: 0.7260, HR@5: 0.9771, NDCG@10: 0.7338, HR@10: 1.0000, MRR: 0.6461
test [sampled], NDCG@5: 0.1832, HR@5: 0.1962, NDCG@10: 0.2178, HR@10: 0.3073, MRR: 0.2333
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0914
epoch=17, loss=0.0891
epoch=18, loss=0.0865
epoch=19, loss=0.0864
epoch=20, loss=0.0876
valid [full], NDCG@5: 0.6901, HR@5: 0.8498, NDCG@10: 0.7238, HR@10: 0.9543, MRR: 0.6551
valid [sampled], NDCG@5: 0.5424, HR@5: 0.5481, NDCG@10: 0.5613, HR@10: 0.6081, MRR: 0.5653
test [full], NDCG@5: 0.7466, HR@5: 0.9999, NDCG@10: 0.7466, HR@10: 1.0000, MRR: 0.6619
test [sampled], NDCG@5: 0.1932, HR@5: 0.2077, NDCG@10: 0.2332, HR@10: 0.3355, MRR: 0.2450
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=21, loss=0.0848
epoch=22, loss=0.0847
epoch=23, loss=0.0857
epoch=24, loss=0.0849
epoch=25, loss=0.0844
valid [full], NDCG@5: 0.7021, HR@5: 0.8628, NDCG@10: 0.7314, HR@10: 0.9555, MRR: 0.6646
valid [sampled], NDCG@5: 0.5473, HR@5: 0.5533, NDCG@10: 0.5646, HR@10: 0.6083, MRR: 0.5700
test [full], NDCG@5: 0.7727, HR@5: 0.9958, NDCG@10: 0.7742, HR@10: 1.0000, MRR: 0.7011
test [sampled], NDCG@5: 0.2845, HR@5: 0.3006, NDCG@10: 0.3102, HR@10: 0.3827, MRR: 0.3245
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=26, loss=0.0842
epoch=27, loss=0.0845
epoch=28, loss=0.0822
epoch=29, loss=0.0816
epoch=30, loss=0.0812
valid [full], NDCG@5: 0.6900, HR@5: 0.8489, NDCG@10: 0.7246, HR@10: 0.9581, MRR: 0.6551
valid [sampled], NDCG@5: 0.5259, HR@5: 0.5324, NDCG@10: 0.5451, HR@10: 0.5934, MRR: 0.5490
test [full], NDCG@5: 0.7648, HR@5: 0.9984, NDCG@10: 0.7654, HR@10: 1.0000, MRR: 0.6893
test [sampled], NDCG@5: 0.2632, HR@5: 0.2836, NDCG@10: 0.2925, HR@10: 0.3759, MRR: 0.3039
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0838
epoch=32, loss=0.0801
epoch=33, loss=0.0818
epoch=34, loss=0.0796
epoch=35, loss=0.0812
valid [full], NDCG@5: 0.6806, HR@5: 0.8391, NDCG@10: 0.7172, HR@10: 0.9561, MRR: 0.6466
valid [sampled], NDCG@5: 0.5275, HR@5: 0.5317, NDCG@10: 0.5448, HR@10: 0.5866, MRR: 0.5506
test [full], NDCG@5: 0.7813, HR@5: 0.9997, NDCG@10: 0.7814, HR@10: 1.0000, MRR: 0.7091
test [sampled], NDCG@5: 0.2803, HR@5: 0.2992, NDCG@10: 0.3155, HR@10: 0.4108, MRR: 0.3230
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0818
epoch=37, loss=0.0812
epoch=38, loss=0.0799
epoch=39, loss=0.0795
epoch=40, loss=0.0817
valid [full], NDCG@5: 0.7172, HR@5: 0.8747, NDCG@10: 0.7441, HR@10: 0.9604, MRR: 0.6784
valid [sampled], NDCG@5: 0.5415, HR@5: 0.5581, NDCG@10: 0.5754, HR@10: 0.6653, MRR: 0.5650
test [full], NDCG@5: 0.7839, HR@5: 0.9999, NDCG@10: 0.7839, HR@10: 1.0000, MRR: 0.7095
test [sampled], NDCG@5: 0.2207, HR@5: 0.2414, NDCG@10: 0.2850, HR@10: 0.4475, MRR: 0.2745
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=41, loss=0.0816
epoch=42, loss=0.0790
epoch=43, loss=0.0774
epoch=44, loss=0.0814
epoch=45, loss=0.0791
valid [full], NDCG@5: 0.7135, HR@5: 0.8826, NDCG@10: 0.7377, HR@10: 0.9609, MRR: 0.6706
valid [sampled], NDCG@5: 0.5448, HR@5: 0.5544, NDCG@10: 0.5694, HR@10: 0.6328, MRR: 0.5678
test [full], NDCG@5: 0.7887, HR@5: 0.9996, NDCG@10: 0.7888, HR@10: 1.0000, MRR: 0.7183
test [sampled], NDCG@5: 0.2751, HR@5: 0.2979, NDCG@10: 0.3169, HR@10: 0.4306, MRR: 0.3190
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0777
epoch=47, loss=0.0779
epoch=48, loss=0.0779
epoch=49, loss=0.0776
epoch=50, loss=0.0785
valid [full], NDCG@5: 0.7350, HR@5: 0.8900, NDCG@10: 0.7559, HR@10: 0.9588, MRR: 0.6952
valid [sampled], NDCG@5: 0.5797, HR@5: 0.5901, NDCG@10: 0.6073, HR@10: 0.6780, MRR: 0.6023
test [full], NDCG@5: 0.8077, HR@5: 0.9995, NDCG@10: 0.8079, HR@10: 1.0000, MRR: 0.7437
test [sampled], NDCG@5: 0.2899, HR@5: 0.3098, NDCG@10: 0.3350, HR@10: 0.4530, MRR: 0.3353
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b8_s7/sasrec_last.pth

### timeaware_anchor_ml20_b9_s42

In [15]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b9_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42
epoch=1, loss=0.6439
epoch=2, loss=0.3050
epoch=3, loss=0.2097
epoch=4, loss=0.1655
epoch=5, loss=0.1402
valid [full], NDCG@5: 0.6423, HR@5: 0.7503, NDCG@10: 0.7151, HR@10: 0.9814, MRR: 0.6386
valid [sampled], NDCG@5: 0.5593, HR@5: 0.5607, NDCG@10: 0.5657, HR@10: 0.5815, MRR: 0.5756
test [full], NDCG@5: 0.7782, HR@5: 0.8932, NDCG@10: 0.8132, HR@10: 1.0000, MRR: 0.7539
test [sampled], NDCG@5: 0.1876, HR@5: 0.2663, NDCG@10: 0.2698, HR@10: 0.5204, MRR: 0.2207
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/sasrec_best.pth
epoch=6, loss=0.1237
epoch=7, loss=0.1159
epoch=8, loss=0.1096
epoch=9, loss=0.1043
epoch=10, loss=0.0993
valid [full], NDCG@5: 0.6226, HR@5: 0.7313, NDCG@10: 0.7003, HR@10: 0.9704, MRR: 0.6225
valid [sampled], NDCG@5: 0.5298, HR@5: 0.5347, NDCG@10: 0.5414, HR@10: 0.5713, MRR: 0.5474
test [full], NDCG@5: 0.8417, HR@5: 0.9527, NDCG@10: 0.8570, HR@10: 1.0000, MRR: 0.8104
test [sampled], NDCG@5: 0.4585, HR@5: 0.4677, NDCG@10: 0.4907, HR@10: 0.5711, MRR: 0.4920
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0984
epoch=12, loss=0.0964
epoch=13, loss=0.0939
epoch=14, loss=0.0925
epoch=15, loss=0.0919
valid [full], NDCG@5: 0.6306, HR@5: 0.7834, NDCG@10: 0.6875, HR@10: 0.9594, MRR: 0.6075
valid [sampled], NDCG@5: 0.4853, HR@5: 0.4909, NDCG@10: 0.5017, HR@10: 0.5433, MRR: 0.5081
test [full], NDCG@5: 0.7868, HR@5: 0.9620, NDCG@10: 0.7991, HR@10: 1.0000, MRR: 0.7317
test [sampled], NDCG@5: 0.3235, HR@5: 0.3549, NDCG@10: 0.3842, HR@10: 0.5466, MRR: 0.3648
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0906
epoch=17, loss=0.0894
epoch=18, loss=0.0899
epoch=19, loss=0.0863
epoch=20, loss=0.0878
valid [full], NDCG@5: 0.6364, HR@5: 0.7562, NDCG@10: 0.7005, HR@10: 0.9571, MRR: 0.6262
valid [sampled], NDCG@5: 0.5086, HR@5: 0.5138, NDCG@10: 0.5235, HR@10: 0.5610, MRR: 0.5288
test [full], NDCG@5: 0.7817, HR@5: 0.9923, NDCG@10: 0.7844, HR@10: 1.0000, MRR: 0.7131
test [sampled], NDCG@5: 0.3268, HR@5: 0.3351, NDCG@10: 0.3763, HR@10: 0.4942, MRR: 0.3747
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0854
epoch=22, loss=0.0859
epoch=23, loss=0.0849
epoch=24, loss=0.0872
epoch=25, loss=0.0836
valid [full], NDCG@5: 0.6027, HR@5: 0.7752, NDCG@10: 0.6529, HR@10: 0.9321, MRR: 0.5722
valid [sampled], NDCG@5: 0.4308, HR@5: 0.4391, NDCG@10: 0.4477, HR@10: 0.4924, MRR: 0.4528
test [full], NDCG@5: 0.8035, HR@5: 0.9924, NDCG@10: 0.8061, HR@10: 1.0000, MRR: 0.7412
test [sampled], NDCG@5: 0.3697, HR@5: 0.3761, NDCG@10: 0.4216, HR@10: 0.5441, MRR: 0.4179
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0831
epoch=27, loss=0.0842
epoch=28, loss=0.0843
epoch=29, loss=0.0835
epoch=30, loss=0.0825
valid [full], NDCG@5: 0.6236, HR@5: 0.8126, NDCG@10: 0.6710, HR@10: 0.9606, MRR: 0.5844
valid [sampled], NDCG@5: 0.4321, HR@5: 0.4436, NDCG@10: 0.4541, HR@10: 0.5128, MRR: 0.4559
test [full], NDCG@5: 0.8087, HR@5: 0.9996, NDCG@10: 0.8088, HR@10: 1.0000, MRR: 0.7442
test [sampled], NDCG@5: 0.3614, HR@5: 0.3720, NDCG@10: 0.4164, HR@10: 0.5495, MRR: 0.4094
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0841
epoch=32, loss=0.0812
epoch=33, loss=0.0822
epoch=34, loss=0.0812
epoch=35, loss=0.0797
valid [full], NDCG@5: 0.6118, HR@5: 0.7869, NDCG@10: 0.6600, HR@10: 0.9356, MRR: 0.5792
valid [sampled], NDCG@5: 0.4368, HR@5: 0.4502, NDCG@10: 0.4597, HR@10: 0.5222, MRR: 0.4589
test [full], NDCG@5: 0.8032, HR@5: 0.9995, NDCG@10: 0.8034, HR@10: 1.0000, MRR: 0.7369
test [sampled], NDCG@5: 0.3553, HR@5: 0.3645, NDCG@10: 0.3832, HR@10: 0.4546, MRR: 0.3979
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0798
epoch=37, loss=0.0811
epoch=38, loss=0.0805
epoch=39, loss=0.0809
epoch=40, loss=0.0801
valid [full], NDCG@5: 0.6229, HR@5: 0.8003, NDCG@10: 0.6642, HR@10: 0.9298, MRR: 0.5867
valid [sampled], NDCG@5: 0.4354, HR@5: 0.4467, NDCG@10: 0.4602, HR@10: 0.5246, MRR: 0.4600
test [full], NDCG@5: 0.8120, HR@5: 0.9993, NDCG@10: 0.8122, HR@10: 1.0000, MRR: 0.7488
test [sampled], NDCG@5: 0.3728, HR@5: 0.3803, NDCG@10: 0.4021, HR@10: 0.4746, MRR: 0.4146
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0804
epoch=42, loss=0.0807
epoch=43, loss=0.0821
epoch=44, loss=0.0791
epoch=45, loss=0.0817
valid [full], NDCG@5: 0.6512, HR@5: 0.8093, NDCG@10: 0.6966, HR@10: 0.9521, MRR: 0.6206
valid [sampled], NDCG@5: 0.4686, HR@5: 0.4806, NDCG@10: 0.4957, HR@10: 0.5665, MRR: 0.4939
test [full], NDCG@5: 0.8100, HR@5: 0.9988, NDCG@10: 0.8104, HR@10: 1.0000, MRR: 0.7466
test [sampled], NDCG@5: 0.3871, HR@5: 0.3966, NDCG@10: 0.4348, HR@10: 0.5499, MRR: 0.4318
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0760
epoch=47, loss=0.0805
epoch=48, loss=0.0776
epoch=49, loss=0.0785
epoch=50, loss=0.0792
valid [full], NDCG@5: 0.6715, HR@5: 0.8259, NDCG@10: 0.7110, HR@10: 0.9506, MRR: 0.6400
valid [sampled], NDCG@5: 0.4929, HR@5: 0.5076, NDCG@10: 0.5195, HR@10: 0.5913, MRR: 0.5162
test [full], NDCG@5: 0.7991, HR@5: 0.9997, NDCG@10: 0.7992, HR@10: 1.0000, MRR: 0.7316
test [sampled], NDCG@5: 0.3459, HR@5: 0.3598, NDCG@10: 0.3982, HR@10: 0.5276, MRR: 0.3926
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s42/sasrec_last.pth

### timeaware_anchor_ml20_b9_s2024

In [16]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b9_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024
epoch=1, loss=0.6604
epoch=2, loss=0.3156
epoch=3, loss=0.2133
epoch=4, loss=0.1649
epoch=5, loss=0.1394
valid [full], NDCG@5: 0.6306, HR@5: 0.7476, NDCG@10: 0.7033, HR@10: 0.9797, MRR: 0.6233
valid [sampled], NDCG@5: 0.5281, HR@5: 0.5292, NDCG@10: 0.5369, HR@10: 0.5577, MRR: 0.5469
test [full], NDCG@5: 0.7836, HR@5: 0.9071, NDCG@10: 0.8092, HR@10: 0.9884, MRR: 0.7549
test [sampled], NDCG@5: 0.2303, HR@5: 0.3041, NDCG@10: 0.2889, HR@10: 0.4835, MRR: 0.2562
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1266
epoch=7, loss=0.1155
epoch=8, loss=0.1083
epoch=9, loss=0.1057
epoch=10, loss=0.1025
valid [full], NDCG@5: 0.6459, HR@5: 0.7851, NDCG@10: 0.7067, HR@10: 0.9718, MRR: 0.6294
valid [sampled], NDCG@5: 0.5282, HR@5: 0.5291, NDCG@10: 0.5355, HR@10: 0.5531, MRR: 0.5474
test [full], NDCG@5: 0.7384, HR@5: 0.9184, NDCG@10: 0.7655, HR@10: 0.9996, MRR: 0.6891
test [sampled], NDCG@5: 0.2142, HR@5: 0.2353, NDCG@10: 0.2792, HR@10: 0.4427, MRR: 0.2645
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=11, loss=0.1002
epoch=12, loss=0.0970
epoch=13, loss=0.0961
epoch=14, loss=0.0931
epoch=15, loss=0.0913
valid [full], NDCG@5: 0.6581, HR@5: 0.8102, NDCG@10: 0.7102, HR@10: 0.9716, MRR: 0.6336
valid [sampled], NDCG@5: 0.5356, HR@5: 0.5387, NDCG@10: 0.5438, HR@10: 0.5648, MRR: 0.5545
test [full], NDCG@5: 0.7846, HR@5: 0.9634, NDCG@10: 0.7971, HR@10: 1.0000, MRR: 0.7302
test [sampled], NDCG@5: 0.3046, HR@5: 0.3226, NDCG@10: 0.3598, HR@10: 0.4987, MRR: 0.3488
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=16, loss=0.0900
epoch=17, loss=0.0898
epoch=18, loss=0.0903
epoch=19, loss=0.0885
epoch=20, loss=0.0862
valid [full], NDCG@5: 0.6456, HR@5: 0.7734, NDCG@10: 0.7113, HR@10: 0.9738, MRR: 0.6348
valid [sampled], NDCG@5: 0.5321, HR@5: 0.5366, NDCG@10: 0.5413, HR@10: 0.5655, MRR: 0.5499
test [full], NDCG@5: 0.7846, HR@5: 0.9192, NDCG@10: 0.8115, HR@10: 1.0000, MRR: 0.7506
test [sampled], NDCG@5: 0.3486, HR@5: 0.3644, NDCG@10: 0.3985, HR@10: 0.5240, MRR: 0.3892
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=21, loss=0.0874
epoch=22, loss=0.0860
epoch=23, loss=0.0854
epoch=24, loss=0.0849
epoch=25, loss=0.0852
valid [full], NDCG@5: 0.6734, HR@5: 0.8236, NDCG@10: 0.7159, HR@10: 0.9563, MRR: 0.6459
valid [sampled], NDCG@5: 0.5359, HR@5: 0.5448, NDCG@10: 0.5516, HR@10: 0.5946, MRR: 0.5540
test [full], NDCG@5: 0.7868, HR@5: 0.9251, NDCG@10: 0.8121, HR@10: 0.9999, MRR: 0.7510
test [sampled], NDCG@5: 0.3609, HR@5: 0.3724, NDCG@10: 0.4069, HR@10: 0.5203, MRR: 0.4019
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=26, loss=0.0817
epoch=27, loss=0.0842
epoch=28, loss=0.0836
epoch=29, loss=0.0850
epoch=30, loss=0.0813
valid [full], NDCG@5: 0.6754, HR@5: 0.8215, NDCG@10: 0.7212, HR@10: 0.9615, MRR: 0.6504
valid [sampled], NDCG@5: 0.5384, HR@5: 0.5487, NDCG@10: 0.5548, HR@10: 0.6003, MRR: 0.5567
test [full], NDCG@5: 0.7988, HR@5: 0.9289, NDCG@10: 0.8219, HR@10: 1.0000, MRR: 0.7637
test [sampled], NDCG@5: 0.3772, HR@5: 0.3862, NDCG@10: 0.4226, HR@10: 0.5331, MRR: 0.4181
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=31, loss=0.0839
epoch=32, loss=0.0837
epoch=33, loss=0.0823
epoch=34, loss=0.0835
epoch=35, loss=0.0825
valid [full], NDCG@5: 0.6474, HR@5: 0.7506, NDCG@10: 0.7120, HR@10: 0.9472, MRR: 0.6453
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5680, NDCG@10: 0.5743, HR@10: 0.6174, MRR: 0.5743
test [full], NDCG@5: 0.7791, HR@5: 0.9031, NDCG@10: 0.8111, HR@10: 0.9999, MRR: 0.7500
test [sampled], NDCG@5: 0.3741, HR@5: 0.3834, NDCG@10: 0.4210, HR@10: 0.5346, MRR: 0.4148
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0823
epoch=37, loss=0.0809
epoch=38, loss=0.0815
epoch=39, loss=0.0804
epoch=40, loss=0.0790
valid [full], NDCG@5: 0.6647, HR@5: 0.7815, NDCG@10: 0.7187, HR@10: 0.9461, MRR: 0.6540
valid [sampled], NDCG@5: 0.5584, HR@5: 0.5697, NDCG@10: 0.5767, HR@10: 0.6268, MRR: 0.5748
test [full], NDCG@5: 0.7760, HR@5: 0.8960, NDCG@10: 0.8106, HR@10: 1.0000, MRR: 0.7490
test [sampled], NDCG@5: 0.3686, HR@5: 0.3816, NDCG@10: 0.4162, HR@10: 0.5338, MRR: 0.4088
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0810
epoch=42, loss=0.0826
epoch=43, loss=0.0800
epoch=44, loss=0.0800
epoch=45, loss=0.0784
valid [full], NDCG@5: 0.6537, HR@5: 0.7729, NDCG@10: 0.7124, HR@10: 0.9488, MRR: 0.6451
valid [sampled], NDCG@5: 0.5519, HR@5: 0.5642, NDCG@10: 0.5658, HR@10: 0.6070, MRR: 0.5666
test [full], NDCG@5: 0.7832, HR@5: 0.9058, NDCG@10: 0.8145, HR@10: 1.0000, MRR: 0.7541
test [sampled], NDCG@5: 0.3790, HR@5: 0.3931, NDCG@10: 0.4277, HR@10: 0.5493, MRR: 0.4186
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0793
epoch=47, loss=0.0800
epoch=48, loss=0.0796
epoch=49, loss=0.0780
epoch=50, loss=0.0799
valid [full], NDCG@5: 0.6550, HR@5: 0.7617, NDCG@10: 0.7250, HR@10: 0.9751, MRR: 0.6519
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5698, NDCG@10: 0.5724, HR@10: 0.6183, MRR: 0.5719
test [full], NDCG@5: 0.7772, HR@5: 0.8974, NDCG@10: 0.8103, HR@10: 1.0000, MRR: 0.7490
test [sampled], NDCG@5: 0.3805, HR@5: 0.3913, NDCG@10: 0.4264, HR@10: 0.5389, MRR: 0.4202
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s2024/sasrec_last.pth

### timeaware_anchor_ml20_b9_s7

In [17]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b9_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7
epoch=1, loss=0.6771
epoch=2, loss=0.3217
epoch=3, loss=0.2233
epoch=4, loss=0.1713
epoch=5, loss=0.1432
valid [full], NDCG@5: 0.6560, HR@5: 0.8076, NDCG@10: 0.7039, HR@10: 0.9593, MRR: 0.6304
valid [sampled], NDCG@5: 0.5389, HR@5: 0.5402, NDCG@10: 0.5440, HR@10: 0.5565, MRR: 0.5563
test [full], NDCG@5: 0.6490, HR@5: 0.9041, NDCG@10: 0.6739, HR@10: 0.9796, MRR: 0.5769
test [sampled], NDCG@5: 0.1676, HR@5: 0.1700, NDCG@10: 0.1851, HR@10: 0.2276, MRR: 0.2152
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=6, loss=0.1278
epoch=7, loss=0.1195
epoch=8, loss=0.1089
epoch=9, loss=0.1059
epoch=10, loss=0.1017
valid [full], NDCG@5: 0.6626, HR@5: 0.8288, NDCG@10: 0.6983, HR@10: 0.9397, MRR: 0.6298
valid [sampled], NDCG@5: 0.5332, HR@5: 0.5340, NDCG@10: 0.5372, HR@10: 0.5468, MRR: 0.5504
test [full], NDCG@5: 0.6936, HR@5: 0.9773, NDCG@10: 0.7009, HR@10: 0.9984, MRR: 0.6034
test [sampled], NDCG@5: 0.1706, HR@5: 0.1763, NDCG@10: 0.1972, HR@10: 0.2629, MRR: 0.2216
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1005
epoch=12, loss=0.0970
epoch=13, loss=0.0929
epoch=14, loss=0.0928
epoch=15, loss=0.0925
valid [full], NDCG@5: 0.6615, HR@5: 0.8356, NDCG@10: 0.6990, HR@10: 0.9532, MRR: 0.6249
valid [sampled], NDCG@5: 0.5266, HR@5: 0.5291, NDCG@10: 0.5342, HR@10: 0.5532, MRR: 0.5456
test [full], NDCG@5: 0.7183, HR@5: 0.9793, NDCG@10: 0.7254, HR@10: 0.9999, MRR: 0.6348
test [sampled], NDCG@5: 0.1851, HR@5: 0.1935, NDCG@10: 0.2154, HR@10: 0.2918, MRR: 0.2361
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0917
epoch=17, loss=0.0892
epoch=18, loss=0.0870
epoch=19, loss=0.0866
epoch=20, loss=0.0875
valid [full], NDCG@5: 0.6907, HR@5: 0.8579, NDCG@10: 0.7215, HR@10: 0.9542, MRR: 0.6526
valid [sampled], NDCG@5: 0.5425, HR@5: 0.5531, NDCG@10: 0.5610, HR@10: 0.6107, MRR: 0.5627
test [full], NDCG@5: 0.7853, HR@5: 0.9997, NDCG@10: 0.7854, HR@10: 1.0000, MRR: 0.7120
test [sampled], NDCG@5: 0.2188, HR@5: 0.2401, NDCG@10: 0.2852, HR@10: 0.4519, MRR: 0.2724
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=21, loss=0.0852
epoch=22, loss=0.0849
epoch=23, loss=0.0857
epoch=24, loss=0.0852
epoch=25, loss=0.0842
valid [full], NDCG@5: 0.6827, HR@5: 0.8483, NDCG@10: 0.7184, HR@10: 0.9585, MRR: 0.6467
valid [sampled], NDCG@5: 0.5256, HR@5: 0.5302, NDCG@10: 0.5416, HR@10: 0.5813, MRR: 0.5486
test [full], NDCG@5: 0.8191, HR@5: 0.9995, NDCG@10: 0.8193, HR@10: 1.0000, MRR: 0.7579
test [sampled], NDCG@5: 0.2608, HR@5: 0.2931, NDCG@10: 0.3224, HR@10: 0.4887, MRR: 0.3067
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0843
epoch=27, loss=0.0849
epoch=28, loss=0.0823
epoch=29, loss=0.0819
epoch=30, loss=0.0812
valid [full], NDCG@5: 0.6913, HR@5: 0.8522, NDCG@10: 0.7255, HR@10: 0.9585, MRR: 0.6560
valid [sampled], NDCG@5: 0.5270, HR@5: 0.5356, NDCG@10: 0.5464, HR@10: 0.5970, MRR: 0.5493
test [full], NDCG@5: 0.8380, HR@5: 0.9996, NDCG@10: 0.8382, HR@10: 1.0000, MRR: 0.7827
test [sampled], NDCG@5: 0.2930, HR@5: 0.3305, NDCG@10: 0.3593, HR@10: 0.5407, MRR: 0.3365
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=31, loss=0.0842
epoch=32, loss=0.0802
epoch=33, loss=0.0819
epoch=34, loss=0.0798
epoch=35, loss=0.0811
valid [full], NDCG@5: 0.6751, HR@5: 0.8281, NDCG@10: 0.7125, HR@10: 0.9457, MRR: 0.6444
valid [sampled], NDCG@5: 0.5290, HR@5: 0.5395, NDCG@10: 0.5452, HR@10: 0.5901, MRR: 0.5486
test [full], NDCG@5: 0.8131, HR@5: 0.9949, NDCG@10: 0.8150, HR@10: 1.0000, MRR: 0.7510
test [sampled], NDCG@5: 0.2665, HR@5: 0.2936, NDCG@10: 0.3327, HR@10: 0.5038, MRR: 0.3160
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0817
epoch=37, loss=0.0813
epoch=38, loss=0.0803
epoch=39, loss=0.0797
epoch=40, loss=0.0818
valid [full], NDCG@5: 0.7125, HR@5: 0.8719, NDCG@10: 0.7400, HR@10: 0.9612, MRR: 0.6734
valid [sampled], NDCG@5: 0.5427, HR@5: 0.5592, NDCG@10: 0.5710, HR@10: 0.6483, MRR: 0.5645
test [full], NDCG@5: 0.8037, HR@5: 0.9921, NDCG@10: 0.8065, HR@10: 1.0000, MRR: 0.7401
test [sampled], NDCG@5: 0.2287, HR@5: 0.2626, NDCG@10: 0.2994, HR@10: 0.4867, MRR: 0.2786
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=41, loss=0.0821
epoch=42, loss=0.0788
epoch=43, loss=0.0778
epoch=44, loss=0.0817
epoch=45, loss=0.0795
valid [full], NDCG@5: 0.7111, HR@5: 0.8763, NDCG@10: 0.7380, HR@10: 0.9624, MRR: 0.6706
valid [sampled], NDCG@5: 0.5440, HR@5: 0.5568, NDCG@10: 0.5704, HR@10: 0.6402, MRR: 0.5662
test [full], NDCG@5: 0.8294, HR@5: 0.9816, NDCG@10: 0.8359, HR@10: 1.0000, MRR: 0.7793
test [sampled], NDCG@5: 0.2935, HR@5: 0.3303, NDCG@10: 0.3639, HR@10: 0.5532, MRR: 0.3383
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0780
epoch=47, loss=0.0783
epoch=48, loss=0.0782
epoch=49, loss=0.0776
epoch=50, loss=0.0785
valid [full], NDCG@5: 0.7146, HR@5: 0.8674, NDCG@10: 0.7438, HR@10: 0.9605, MRR: 0.6789
valid [sampled], NDCG@5: 0.5508, HR@5: 0.5668, NDCG@10: 0.5825, HR@10: 0.6670, MRR: 0.5733
test [full], NDCG@5: 0.8340, HR@5: 0.9716, NDCG@10: 0.8440, HR@10: 1.0000, MRR: 0.7905
test [sampled], NDCG@5: 0.3225, HR@5: 0.3522, NDCG@10: 0.3868, HR@10: 0.5562, MRR: 0.3663
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10/timeaware_anchor_ml20_b9_s7/sasrec_last.pth

## Train time-aware runs for `NDCG@5`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_anchor_ml20_b8_s42

In [18]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b8_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42
epoch=1, loss=0.6426
epoch=2, loss=0.3038
epoch=3, loss=0.2099
epoch=4, loss=0.1665
epoch=5, loss=0.1410
valid [full], NDCG@5: 0.6361, HR@5: 0.7458, NDCG@10: 0.7103, HR@10: 0.9801, MRR: 0.6324
valid [sampled], NDCG@5: 0.5426, HR@5: 0.5440, NDCG@10: 0.5502, HR@10: 0.5689, MRR: 0.5602
test [full], NDCG@5: 0.7578, HR@5: 0.8828, NDCG@10: 0.7957, HR@10: 0.9991, MRR: 0.7315
test [sampled], NDCG@5: 0.1689, HR@5: 0.2476, NDCG@10: 0.2490, HR@10: 0.4949, MRR: 0.2017
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/sasrec_best.pth
epoch=6, loss=0.1241
epoch=7, loss=0.1162
epoch=8, loss=0.1102
epoch=9, loss=0.1048
epoch=10, loss=0.0997
valid [full], NDCG@5: 0.6420, HR@5: 0.7662, NDCG@10: 0.7102, HR@10: 0.9728, MRR: 0.6334
valid [sampled], NDCG@5: 0.5365, HR@5: 0.5412, NDCG@10: 0.5486, HR@10: 0.5795, MRR: 0.5550
test [full], NDCG@5: 0.8332, HR@5: 0.9364, NDCG@10: 0.8538, HR@10: 1.0000, MRR: 0.8066
test [sampled], NDCG@5: 0.4007, HR@5: 0.4282, NDCG@10: 0.4438, HR@10: 0.5645, MRR: 0.4331
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/sasrec_best.pth
epoch=11, loss=0.0987
epoch=12, loss=0.0968
epoch=13, loss=0.0940
epoch=14, loss=0.0924
epoch=15, loss=0.0919
valid [full], NDCG@5: 0.6694, HR@5: 0.8324, NDCG@10: 0.7149, HR@10: 0.9763, MRR: 0.6366
valid [sampled], NDCG@5: 0.5202, HR@5: 0.5261, NDCG@10: 0.5374, HR@10: 0.5809, MRR: 0.5427
test [full], NDCG@5: 0.7941, HR@5: 0.9667, NDCG@10: 0.8049, HR@10: 1.0000, MRR: 0.7390
test [sampled], NDCG@5: 0.3235, HR@5: 0.3359, NDCG@10: 0.3792, HR@10: 0.5150, MRR: 0.3711
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/sasrec_best.pth
epoch=16, loss=0.0908
epoch=17, loss=0.0891
epoch=18, loss=0.0903
epoch=19, loss=0.0866
epoch=20, loss=0.0882
valid [full], NDCG@5: 0.6571, HR@5: 0.8058, NDCG@10: 0.7058, HR@10: 0.9596, MRR: 0.6309
valid [sampled], NDCG@5: 0.4992, HR@5: 0.5032, NDCG@10: 0.5163, HR@10: 0.5574, MRR: 0.5227
test [full], NDCG@5: 0.7916, HR@5: 0.9989, NDCG@10: 0.7919, HR@10: 1.0000, MRR: 0.7229
test [sampled], NDCG@5: 0.3435, HR@5: 0.3474, NDCG@10: 0.3824, HR@10: 0.4733, MRR: 0.3898
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0858
epoch=22, loss=0.0864
epoch=23, loss=0.0851
epoch=24, loss=0.0874
epoch=25, loss=0.0838
valid [full], NDCG@5: 0.6260, HR@5: 0.8025, NDCG@10: 0.6699, HR@10: 0.9406, MRR: 0.5907
valid [sampled], NDCG@5: 0.4400, HR@5: 0.4523, NDCG@10: 0.4648, HR@10: 0.5303, MRR: 0.4634
test [full], NDCG@5: 0.7931, HR@5: 0.9996, NDCG@10: 0.7932, HR@10: 1.0000, MRR: 0.7233
test [sampled], NDCG@5: 0.3176, HR@5: 0.3253, NDCG@10: 0.3549, HR@10: 0.4456, MRR: 0.3654
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0829
epoch=27, loss=0.0843
epoch=28, loss=0.0841
epoch=29, loss=0.0835
epoch=30, loss=0.0823
valid [full], NDCG@5: 0.6401, HR@5: 0.8322, NDCG@10: 0.6811, HR@10: 0.9611, MRR: 0.5970
valid [sampled], NDCG@5: 0.4443, HR@5: 0.4590, NDCG@10: 0.4702, HR@10: 0.5402, MRR: 0.4678
test [full], NDCG@5: 0.8037, HR@5: 0.9993, NDCG@10: 0.8039, HR@10: 1.0000, MRR: 0.7379
test [sampled], NDCG@5: 0.3524, HR@5: 0.3627, NDCG@10: 0.3823, HR@10: 0.4589, MRR: 0.3948
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0843
epoch=32, loss=0.0814
epoch=33, loss=0.0824
epoch=34, loss=0.0813
epoch=35, loss=0.0799
valid [full], NDCG@5: 0.6370, HR@5: 0.8119, NDCG@10: 0.6741, HR@10: 0.9302, MRR: 0.5990
valid [sampled], NDCG@5: 0.4498, HR@5: 0.4648, NDCG@10: 0.4793, HR@10: 0.5576, MRR: 0.4733
test [full], NDCG@5: 0.8013, HR@5: 0.9996, NDCG@10: 0.8014, HR@10: 1.0000, MRR: 0.7340
test [sampled], NDCG@5: 0.3413, HR@5: 0.3546, NDCG@10: 0.3750, HR@10: 0.4623, MRR: 0.3848
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0800
epoch=37, loss=0.0811
epoch=38, loss=0.0810
epoch=39, loss=0.0809
epoch=40, loss=0.0802
valid [full], NDCG@5: 0.6315, HR@5: 0.7988, NDCG@10: 0.6719, HR@10: 0.9279, MRR: 0.5977
valid [sampled], NDCG@5: 0.4484, HR@5: 0.4631, NDCG@10: 0.4798, HR@10: 0.5617, MRR: 0.4721
test [full], NDCG@5: 0.7969, HR@5: 0.9997, NDCG@10: 0.7970, HR@10: 1.0000, MRR: 0.7286
test [sampled], NDCG@5: 0.3410, HR@5: 0.3506, NDCG@10: 0.3708, HR@10: 0.4461, MRR: 0.3839
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0807
epoch=42, loss=0.0807
epoch=43, loss=0.0821
epoch=44, loss=0.0793
epoch=45, loss=0.0818
valid [full], NDCG@5: 0.6320, HR@5: 0.7961, NDCG@10: 0.6791, HR@10: 0.9453, MRR: 0.6004
valid [sampled], NDCG@5: 0.4469, HR@5: 0.4613, NDCG@10: 0.4792, HR@10: 0.5636, MRR: 0.4712
test [full], NDCG@5: 0.8118, HR@5: 0.9997, NDCG@10: 0.8119, HR@10: 1.0000, MRR: 0.7482
test [sampled], NDCG@5: 0.3694, HR@5: 0.3806, NDCG@10: 0.3972, HR@10: 0.4696, MRR: 0.4101
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0763
epoch=47, loss=0.0805
epoch=48, loss=0.0777
epoch=49, loss=0.0788
epoch=50, loss=0.0793
valid [full], NDCG@5: 0.6442, HR@5: 0.8244, NDCG@10: 0.6855, HR@10: 0.9535, MRR: 0.6054
valid [sampled], NDCG@5: 0.4491, HR@5: 0.4653, NDCG@10: 0.4787, HR@10: 0.5583, MRR: 0.4729
test [full], NDCG@5: 0.8008, HR@5: 0.9999, NDCG@10: 0.8009, HR@10: 1.0000, MRR: 0.7337
test [sampled], NDCG@5: 0.3476, HR@5: 0.3607, NDCG@10: 0.3786, HR@10: 0.4598, MRR: 0.3894
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s42/sasrec_last.pth

### timeaware_anchor_ml20_b8_s2024

In [19]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b8_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024
epoch=1, loss=0.6654
epoch=2, loss=0.3158
epoch=3, loss=0.2140
epoch=4, loss=0.1656
epoch=5, loss=0.1401
valid [full], NDCG@5: 0.6224, HR@5: 0.7353, NDCG@10: 0.7023, HR@10: 0.9882, MRR: 0.6187
valid [sampled], NDCG@5: 0.5199, HR@5: 0.5203, NDCG@10: 0.5285, HR@10: 0.5485, MRR: 0.5395
test [full], NDCG@5: 0.7852, HR@5: 0.8973, NDCG@10: 0.8148, HR@10: 0.9903, MRR: 0.7618
test [sampled], NDCG@5: 0.2319, HR@5: 0.3067, NDCG@10: 0.2923, HR@10: 0.4919, MRR: 0.2577
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=6, loss=0.1274
epoch=7, loss=0.1160
epoch=8, loss=0.1083
epoch=9, loss=0.1060
epoch=10, loss=0.1027
valid [full], NDCG@5: 0.6413, HR@5: 0.7734, NDCG@10: 0.7055, HR@10: 0.9715, MRR: 0.6284
valid [sampled], NDCG@5: 0.5289, HR@5: 0.5298, NDCG@10: 0.5358, HR@10: 0.5521, MRR: 0.5479
test [full], NDCG@5: 0.8010, HR@5: 0.9097, NDCG@10: 0.8303, HR@10: 0.9993, MRR: 0.7775
test [sampled], NDCG@5: 0.2423, HR@5: 0.3089, NDCG@10: 0.3120, HR@10: 0.5247, MRR: 0.2744
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=11, loss=0.1002
epoch=12, loss=0.0972
epoch=13, loss=0.0963
epoch=14, loss=0.0933
epoch=15, loss=0.0913
valid [full], NDCG@5: 0.6784, HR@5: 0.8569, NDCG@10: 0.7153, HR@10: 0.9714, MRR: 0.6395
valid [sampled], NDCG@5: 0.5392, HR@5: 0.5426, NDCG@10: 0.5475, HR@10: 0.5692, MRR: 0.5585
test [full], NDCG@5: 0.7741, HR@5: 0.9375, NDCG@10: 0.7945, HR@10: 1.0000, MRR: 0.7273
test [sampled], NDCG@5: 0.2666, HR@5: 0.2917, NDCG@10: 0.3299, HR@10: 0.4929, MRR: 0.3122
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=16, loss=0.0902
epoch=17, loss=0.0896
epoch=18, loss=0.0901
epoch=19, loss=0.0886
epoch=20, loss=0.0862
valid [full], NDCG@5: 0.6699, HR@5: 0.8337, NDCG@10: 0.7149, HR@10: 0.9739, MRR: 0.6387
valid [sampled], NDCG@5: 0.5334, HR@5: 0.5378, NDCG@10: 0.5425, HR@10: 0.5667, MRR: 0.5517
test [full], NDCG@5: 0.7855, HR@5: 0.9177, NDCG@10: 0.8128, HR@10: 1.0000, MRR: 0.7524
test [sampled], NDCG@5: 0.3440, HR@5: 0.3615, NDCG@10: 0.3952, HR@10: 0.5251, MRR: 0.3845
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0875
epoch=22, loss=0.0861
epoch=23, loss=0.0852
epoch=24, loss=0.0849
epoch=25, loss=0.0850
valid [full], NDCG@5: 0.6851, HR@5: 0.8567, NDCG@10: 0.7224, HR@10: 0.9734, MRR: 0.6477
valid [sampled], NDCG@5: 0.5372, HR@5: 0.5482, NDCG@10: 0.5492, HR@10: 0.5855, MRR: 0.5547
test [full], NDCG@5: 0.7923, HR@5: 0.9361, NDCG@10: 0.8133, HR@10: 1.0000, MRR: 0.7526
test [sampled], NDCG@5: 0.3594, HR@5: 0.3721, NDCG@10: 0.4059, HR@10: 0.5211, MRR: 0.4001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=26, loss=0.0816
epoch=27, loss=0.0842
epoch=28, loss=0.0833
epoch=29, loss=0.0850
epoch=30, loss=0.0812
valid [full], NDCG@5: 0.6905, HR@5: 0.8556, NDCG@10: 0.7295, HR@10: 0.9774, MRR: 0.6548
valid [sampled], NDCG@5: 0.5338, HR@5: 0.5438, NDCG@10: 0.5515, HR@10: 0.5995, MRR: 0.5541
test [full], NDCG@5: 0.7990, HR@5: 0.9336, NDCG@10: 0.8206, HR@10: 1.0000, MRR: 0.7621
test [sampled], NDCG@5: 0.3674, HR@5: 0.3770, NDCG@10: 0.4126, HR@10: 0.5232, MRR: 0.4086
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/sasrec_best.pth
epoch=31, loss=0.0836
epoch=32, loss=0.0839
epoch=33, loss=0.0821
epoch=34, loss=0.0837
epoch=35, loss=0.0825
valid [full], NDCG@5: 0.6447, HR@5: 0.7629, NDCG@10: 0.7143, HR@10: 0.9756, MRR: 0.6378
valid [sampled], NDCG@5: 0.5438, HR@5: 0.5515, NDCG@10: 0.5597, HR@10: 0.6018, MRR: 0.5615
test [full], NDCG@5: 0.7765, HR@5: 0.8993, NDCG@10: 0.8100, HR@10: 1.0000, MRR: 0.7487
test [sampled], NDCG@5: 0.3751, HR@5: 0.3835, NDCG@10: 0.4203, HR@10: 0.5292, MRR: 0.4157
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0822
epoch=37, loss=0.0808
epoch=38, loss=0.0812
epoch=39, loss=0.0802
epoch=40, loss=0.0787
valid [full], NDCG@5: 0.6706, HR@5: 0.8096, NDCG@10: 0.7242, HR@10: 0.9758, MRR: 0.6497
valid [sampled], NDCG@5: 0.5417, HR@5: 0.5530, NDCG@10: 0.5623, HR@10: 0.6174, MRR: 0.5603
test [full], NDCG@5: 0.7798, HR@5: 0.8993, NDCG@10: 0.8136, HR@10: 1.0000, MRR: 0.7531
test [sampled], NDCG@5: 0.3753, HR@5: 0.3850, NDCG@10: 0.4205, HR@10: 0.5297, MRR: 0.4158
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0810
epoch=42, loss=0.0825
epoch=43, loss=0.0800
epoch=44, loss=0.0799
epoch=45, loss=0.0781
valid [full], NDCG@5: 0.6648, HR@5: 0.8029, NDCG@10: 0.7216, HR@10: 0.9773, MRR: 0.6461
valid [sampled], NDCG@5: 0.5472, HR@5: 0.5588, NDCG@10: 0.5611, HR@10: 0.6014, MRR: 0.5629
test [full], NDCG@5: 0.8616, HR@5: 0.9240, NDCG@10: 0.8869, HR@10: 1.0000, MRR: 0.8516
test [sampled], NDCG@5: 0.4108, HR@5: 0.4695, NDCG@10: 0.4660, HR@10: 0.6393, MRR: 0.4335
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0791
epoch=47, loss=0.0801
epoch=48, loss=0.0799
epoch=49, loss=0.0776
epoch=50, loss=0.0796
valid [full], NDCG@5: 0.6681, HR@5: 0.8072, NDCG@10: 0.7221, HR@10: 0.9751, MRR: 0.6474
valid [sampled], NDCG@5: 0.5425, HR@5: 0.5557, NDCG@10: 0.5587, HR@10: 0.6062, MRR: 0.5593
test [full], NDCG@5: 0.7810, HR@5: 0.9005, NDCG@10: 0.8131, HR@10: 1.0000, MRR: 0.7526
test [sampled], NDCG@5: 0.3838, HR@5: 0.3968, NDCG@10: 0.4304, HR@10: 0.5464, MRR: 0.4227
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s2024/sasrec_last.pth

### timeaware_anchor_ml20_b8_s7

In [20]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b8_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7
epoch=1, loss=0.6868
epoch=2, loss=0.3246
epoch=3, loss=0.2269
epoch=4, loss=0.1721
epoch=5, loss=0.1438
valid [full], NDCG@5: 0.6513, HR@5: 0.7788, NDCG@10: 0.7040, HR@10: 0.9438, MRR: 0.6369
valid [sampled], NDCG@5: 0.5570, HR@5: 0.5583, NDCG@10: 0.5603, HR@10: 0.5687, MRR: 0.5723
test [full], NDCG@5: 0.6535, HR@5: 0.9260, NDCG@10: 0.6711, HR@10: 0.9776, MRR: 0.5739
test [sampled], NDCG@5: 0.1664, HR@5: 0.1686, NDCG@10: 0.1840, HR@10: 0.2262, MRR: 0.2136
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=6, loss=0.1281
epoch=7, loss=0.1195
epoch=8, loss=0.1087
epoch=9, loss=0.1056
epoch=10, loss=0.1012
valid [full], NDCG@5: 0.6464, HR@5: 0.7906, NDCG@10: 0.6939, HR@10: 0.9366, MRR: 0.6259
valid [sampled], NDCG@5: 0.5323, HR@5: 0.5328, NDCG@10: 0.5351, HR@10: 0.5419, MRR: 0.5483
test [full], NDCG@5: 0.6844, HR@5: 0.9667, NDCG@10: 0.6949, HR@10: 0.9973, MRR: 0.5961
test [sampled], NDCG@5: 0.1653, HR@5: 0.1698, NDCG@10: 0.1916, HR@10: 0.2555, MRR: 0.2167
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1001
epoch=12, loss=0.0968
epoch=13, loss=0.0926
epoch=14, loss=0.0927
epoch=15, loss=0.0925
valid [full], NDCG@5: 0.6627, HR@5: 0.8310, NDCG@10: 0.6967, HR@10: 0.9376, MRR: 0.6278
valid [sampled], NDCG@5: 0.5298, HR@5: 0.5312, NDCG@10: 0.5359, HR@10: 0.5509, MRR: 0.5488
test [full], NDCG@5: 0.7260, HR@5: 0.9771, NDCG@10: 0.7338, HR@10: 1.0000, MRR: 0.6461
test [sampled], NDCG@5: 0.1832, HR@5: 0.1962, NDCG@10: 0.2178, HR@10: 0.3073, MRR: 0.2333
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=16, loss=0.0914
epoch=17, loss=0.0891
epoch=18, loss=0.0865
epoch=19, loss=0.0864
epoch=20, loss=0.0876
valid [full], NDCG@5: 0.6901, HR@5: 0.8498, NDCG@10: 0.7238, HR@10: 0.9543, MRR: 0.6551
valid [sampled], NDCG@5: 0.5424, HR@5: 0.5481, NDCG@10: 0.5613, HR@10: 0.6081, MRR: 0.5653
test [full], NDCG@5: 0.7466, HR@5: 0.9999, NDCG@10: 0.7466, HR@10: 1.0000, MRR: 0.6619
test [sampled], NDCG@5: 0.1932, HR@5: 0.2077, NDCG@10: 0.2332, HR@10: 0.3355, MRR: 0.2450
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=21, loss=0.0848
epoch=22, loss=0.0847
epoch=23, loss=0.0857
epoch=24, loss=0.0849
epoch=25, loss=0.0844
valid [full], NDCG@5: 0.7021, HR@5: 0.8628, NDCG@10: 0.7314, HR@10: 0.9555, MRR: 0.6646
valid [sampled], NDCG@5: 0.5473, HR@5: 0.5533, NDCG@10: 0.5646, HR@10: 0.6083, MRR: 0.5700
test [full], NDCG@5: 0.7727, HR@5: 0.9958, NDCG@10: 0.7742, HR@10: 1.0000, MRR: 0.7011
test [sampled], NDCG@5: 0.2845, HR@5: 0.3006, NDCG@10: 0.3102, HR@10: 0.3827, MRR: 0.3245
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=26, loss=0.0842
epoch=27, loss=0.0845
epoch=28, loss=0.0822
epoch=29, loss=0.0816
epoch=30, loss=0.0812
valid [full], NDCG@5: 0.6900, HR@5: 0.8489, NDCG@10: 0.7246, HR@10: 0.9581, MRR: 0.6551
valid [sampled], NDCG@5: 0.5259, HR@5: 0.5324, NDCG@10: 0.5451, HR@10: 0.5934, MRR: 0.5490
test [full], NDCG@5: 0.7648, HR@5: 0.9984, NDCG@10: 0.7654, HR@10: 1.0000, MRR: 0.6893
test [sampled], NDCG@5: 0.2632, HR@5: 0.2836, NDCG@10: 0.2925, HR@10: 0.3759, MRR: 0.3039
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0838
epoch=32, loss=0.0801
epoch=33, loss=0.0818
epoch=34, loss=0.0796
epoch=35, loss=0.0812
valid [full], NDCG@5: 0.6806, HR@5: 0.8391, NDCG@10: 0.7172, HR@10: 0.9561, MRR: 0.6466
valid [sampled], NDCG@5: 0.5275, HR@5: 0.5317, NDCG@10: 0.5448, HR@10: 0.5866, MRR: 0.5506
test [full], NDCG@5: 0.7813, HR@5: 0.9997, NDCG@10: 0.7814, HR@10: 1.0000, MRR: 0.7091
test [sampled], NDCG@5: 0.2803, HR@5: 0.2992, NDCG@10: 0.3155, HR@10: 0.4108, MRR: 0.3230
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0818
epoch=37, loss=0.0812
epoch=38, loss=0.0799
epoch=39, loss=0.0795
epoch=40, loss=0.0817
valid [full], NDCG@5: 0.7172, HR@5: 0.8747, NDCG@10: 0.7441, HR@10: 0.9604, MRR: 0.6784
valid [sampled], NDCG@5: 0.5415, HR@5: 0.5581, NDCG@10: 0.5754, HR@10: 0.6653, MRR: 0.5650
test [full], NDCG@5: 0.7839, HR@5: 0.9999, NDCG@10: 0.7839, HR@10: 1.0000, MRR: 0.7095
test [sampled], NDCG@5: 0.2207, HR@5: 0.2414, NDCG@10: 0.2850, HR@10: 0.4475, MRR: 0.2745
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
epoch=41, loss=0.0816
epoch=42, loss=0.0790
epoch=43, loss=0.0774
epoch=44, loss=0.0814
epoch=45, loss=0.0791
valid [full], NDCG@5: 0.7135, HR@5: 0.8826, NDCG@10: 0.7377, HR@10: 0.9609, MRR: 0.6706
valid [sampled], NDCG@5: 0.5448, HR@5: 0.5544, NDCG@10: 0.5694, HR@10: 0.6328, MRR: 0.5678
test [full], NDCG@5: 0.7887, HR@5: 0.9996, NDCG@10: 0.7888, HR@10: 1.0000, MRR: 0.7183
test [sampled], NDCG@5: 0.2751, HR@5: 0.2979, NDCG@10: 0.3169, HR@10: 0.4306, MRR: 0.3190
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0777
epoch=47, loss=0.0779
epoch=48, loss=0.0779
epoch=49, loss=0.0776
epoch=50, loss=0.0785
valid [full], NDCG@5: 0.7350, HR@5: 0.8900, NDCG@10: 0.7559, HR@10: 0.9588, MRR: 0.6952
valid [sampled], NDCG@5: 0.5797, HR@5: 0.5901, NDCG@10: 0.6073, HR@10: 0.6780, MRR: 0.6023
test [full], NDCG@5: 0.8077, HR@5: 0.9995, NDCG@10: 0.8079, HR@10: 1.0000, MRR: 0.7437
test [sampled], NDCG@5: 0.2899, HR@5: 0.3098, NDCG@10: 0.3350, HR@10: 0.4530, MRR: 0.3353
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b8_s7/sasrec_last.pth

### timeaware_anchor_ml20_b9_s42

In [21]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b9_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42
epoch=1, loss=0.6439
epoch=2, loss=0.3050
epoch=3, loss=0.2097
epoch=4, loss=0.1655
epoch=5, loss=0.1402
valid [full], NDCG@5: 0.6423, HR@5: 0.7503, NDCG@10: 0.7151, HR@10: 0.9814, MRR: 0.6386
valid [sampled], NDCG@5: 0.5593, HR@5: 0.5607, NDCG@10: 0.5657, HR@10: 0.5815, MRR: 0.5756
test [full], NDCG@5: 0.7782, HR@5: 0.8932, NDCG@10: 0.8132, HR@10: 1.0000, MRR: 0.7539
test [sampled], NDCG@5: 0.1876, HR@5: 0.2663, NDCG@10: 0.2698, HR@10: 0.5204, MRR: 0.2207
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/sasrec_best.pth
epoch=6, loss=0.1237
epoch=7, loss=0.1159
epoch=8, loss=0.1096
epoch=9, loss=0.1043
epoch=10, loss=0.0993
valid [full], NDCG@5: 0.6226, HR@5: 0.7313, NDCG@10: 0.7003, HR@10: 0.9704, MRR: 0.6225
valid [sampled], NDCG@5: 0.5298, HR@5: 0.5347, NDCG@10: 0.5414, HR@10: 0.5713, MRR: 0.5474
test [full], NDCG@5: 0.8417, HR@5: 0.9527, NDCG@10: 0.8570, HR@10: 1.0000, MRR: 0.8104
test [sampled], NDCG@5: 0.4585, HR@5: 0.4677, NDCG@10: 0.4907, HR@10: 0.5711, MRR: 0.4920
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0984
epoch=12, loss=0.0964
epoch=13, loss=0.0939
epoch=14, loss=0.0925
epoch=15, loss=0.0919
valid [full], NDCG@5: 0.6306, HR@5: 0.7834, NDCG@10: 0.6875, HR@10: 0.9594, MRR: 0.6075
valid [sampled], NDCG@5: 0.4853, HR@5: 0.4909, NDCG@10: 0.5017, HR@10: 0.5433, MRR: 0.5081
test [full], NDCG@5: 0.7868, HR@5: 0.9620, NDCG@10: 0.7991, HR@10: 1.0000, MRR: 0.7317
test [sampled], NDCG@5: 0.3235, HR@5: 0.3549, NDCG@10: 0.3842, HR@10: 0.5466, MRR: 0.3648
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0906
epoch=17, loss=0.0894
epoch=18, loss=0.0899
epoch=19, loss=0.0863
epoch=20, loss=0.0878
valid [full], NDCG@5: 0.6364, HR@5: 0.7562, NDCG@10: 0.7005, HR@10: 0.9571, MRR: 0.6262
valid [sampled], NDCG@5: 0.5086, HR@5: 0.5138, NDCG@10: 0.5235, HR@10: 0.5610, MRR: 0.5288
test [full], NDCG@5: 0.7817, HR@5: 0.9923, NDCG@10: 0.7844, HR@10: 1.0000, MRR: 0.7131
test [sampled], NDCG@5: 0.3268, HR@5: 0.3351, NDCG@10: 0.3763, HR@10: 0.4942, MRR: 0.3747
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0854
epoch=22, loss=0.0859
epoch=23, loss=0.0849
epoch=24, loss=0.0872
epoch=25, loss=0.0836
valid [full], NDCG@5: 0.6027, HR@5: 0.7752, NDCG@10: 0.6529, HR@10: 0.9321, MRR: 0.5722
valid [sampled], NDCG@5: 0.4308, HR@5: 0.4391, NDCG@10: 0.4477, HR@10: 0.4924, MRR: 0.4528
test [full], NDCG@5: 0.8035, HR@5: 0.9924, NDCG@10: 0.8061, HR@10: 1.0000, MRR: 0.7412
test [sampled], NDCG@5: 0.3697, HR@5: 0.3761, NDCG@10: 0.4216, HR@10: 0.5441, MRR: 0.4179
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0831
epoch=27, loss=0.0842
epoch=28, loss=0.0843
epoch=29, loss=0.0835
epoch=30, loss=0.0825
valid [full], NDCG@5: 0.6236, HR@5: 0.8126, NDCG@10: 0.6710, HR@10: 0.9606, MRR: 0.5844
valid [sampled], NDCG@5: 0.4321, HR@5: 0.4436, NDCG@10: 0.4541, HR@10: 0.5128, MRR: 0.4559
test [full], NDCG@5: 0.8087, HR@5: 0.9996, NDCG@10: 0.8088, HR@10: 1.0000, MRR: 0.7442
test [sampled], NDCG@5: 0.3614, HR@5: 0.3720, NDCG@10: 0.4164, HR@10: 0.5495, MRR: 0.4094
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0841
epoch=32, loss=0.0812
epoch=33, loss=0.0822
epoch=34, loss=0.0812
epoch=35, loss=0.0797
valid [full], NDCG@5: 0.6118, HR@5: 0.7869, NDCG@10: 0.6600, HR@10: 0.9356, MRR: 0.5792
valid [sampled], NDCG@5: 0.4368, HR@5: 0.4502, NDCG@10: 0.4597, HR@10: 0.5222, MRR: 0.4589
test [full], NDCG@5: 0.8032, HR@5: 0.9995, NDCG@10: 0.8034, HR@10: 1.0000, MRR: 0.7369
test [sampled], NDCG@5: 0.3553, HR@5: 0.3645, NDCG@10: 0.3832, HR@10: 0.4546, MRR: 0.3979
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0798
epoch=37, loss=0.0811
epoch=38, loss=0.0805
epoch=39, loss=0.0809
epoch=40, loss=0.0801
valid [full], NDCG@5: 0.6229, HR@5: 0.8003, NDCG@10: 0.6642, HR@10: 0.9298, MRR: 0.5867
valid [sampled], NDCG@5: 0.4354, HR@5: 0.4467, NDCG@10: 0.4602, HR@10: 0.5246, MRR: 0.4600
test [full], NDCG@5: 0.8120, HR@5: 0.9993, NDCG@10: 0.8122, HR@10: 1.0000, MRR: 0.7488
test [sampled], NDCG@5: 0.3728, HR@5: 0.3803, NDCG@10: 0.4021, HR@10: 0.4746, MRR: 0.4146
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0804
epoch=42, loss=0.0807
epoch=43, loss=0.0821
epoch=44, loss=0.0791
epoch=45, loss=0.0817
valid [full], NDCG@5: 0.6512, HR@5: 0.8093, NDCG@10: 0.6966, HR@10: 0.9521, MRR: 0.6206
valid [sampled], NDCG@5: 0.4686, HR@5: 0.4806, NDCG@10: 0.4957, HR@10: 0.5665, MRR: 0.4939
test [full], NDCG@5: 0.8100, HR@5: 0.9988, NDCG@10: 0.8104, HR@10: 1.0000, MRR: 0.7466
test [sampled], NDCG@5: 0.3871, HR@5: 0.3966, NDCG@10: 0.4348, HR@10: 0.5499, MRR: 0.4318
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/sasrec_best.pth
epoch=46, loss=0.0760
epoch=47, loss=0.0805
epoch=48, loss=0.0776
epoch=49, loss=0.0785
epoch=50, loss=0.0792
valid [full], NDCG@5: 0.6715, HR@5: 0.8259, NDCG@10: 0.7110, HR@10: 0.9506, MRR: 0.6400
valid [sampled], NDCG@5: 0.4929, HR@5: 0.5076, NDCG@10: 0.5195, HR@10: 0.5913, MRR: 0.5162
test [full], NDCG@5: 0.7991, HR@5: 0.9997, NDCG@10: 0.7992, HR@10: 1.0000, MRR: 0.7316
test [sampled], NDCG@5: 0.3459, HR@5: 0.3598, NDCG@10: 0.3982, HR@10: 0.5276, MRR: 0.3926
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s42/sasrec_last.pth

### timeaware_anchor_ml20_b9_s2024

In [22]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b9_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024
epoch=1, loss=0.6604
epoch=2, loss=0.3156
epoch=3, loss=0.2133
epoch=4, loss=0.1649
epoch=5, loss=0.1394
valid [full], NDCG@5: 0.6306, HR@5: 0.7476, NDCG@10: 0.7033, HR@10: 0.9797, MRR: 0.6233
valid [sampled], NDCG@5: 0.5281, HR@5: 0.5292, NDCG@10: 0.5369, HR@10: 0.5577, MRR: 0.5469
test [full], NDCG@5: 0.7836, HR@5: 0.9071, NDCG@10: 0.8092, HR@10: 0.9884, MRR: 0.7549
test [sampled], NDCG@5: 0.2303, HR@5: 0.3041, NDCG@10: 0.2889, HR@10: 0.4835, MRR: 0.2562
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1266
epoch=7, loss=0.1155
epoch=8, loss=0.1083
epoch=9, loss=0.1057
epoch=10, loss=0.1025
valid [full], NDCG@5: 0.6459, HR@5: 0.7851, NDCG@10: 0.7067, HR@10: 0.9718, MRR: 0.6294
valid [sampled], NDCG@5: 0.5282, HR@5: 0.5291, NDCG@10: 0.5355, HR@10: 0.5531, MRR: 0.5474
test [full], NDCG@5: 0.7384, HR@5: 0.9184, NDCG@10: 0.7655, HR@10: 0.9996, MRR: 0.6891
test [sampled], NDCG@5: 0.2142, HR@5: 0.2353, NDCG@10: 0.2792, HR@10: 0.4427, MRR: 0.2645
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=11, loss=0.1002
epoch=12, loss=0.0970
epoch=13, loss=0.0961
epoch=14, loss=0.0931
epoch=15, loss=0.0913
valid [full], NDCG@5: 0.6581, HR@5: 0.8102, NDCG@10: 0.7102, HR@10: 0.9716, MRR: 0.6336
valid [sampled], NDCG@5: 0.5356, HR@5: 0.5387, NDCG@10: 0.5438, HR@10: 0.5648, MRR: 0.5545
test [full], NDCG@5: 0.7846, HR@5: 0.9634, NDCG@10: 0.7971, HR@10: 1.0000, MRR: 0.7302
test [sampled], NDCG@5: 0.3046, HR@5: 0.3226, NDCG@10: 0.3598, HR@10: 0.4987, MRR: 0.3488
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=16, loss=0.0900
epoch=17, loss=0.0898
epoch=18, loss=0.0903
epoch=19, loss=0.0885
epoch=20, loss=0.0862
valid [full], NDCG@5: 0.6456, HR@5: 0.7734, NDCG@10: 0.7113, HR@10: 0.9738, MRR: 0.6348
valid [sampled], NDCG@5: 0.5321, HR@5: 0.5366, NDCG@10: 0.5413, HR@10: 0.5655, MRR: 0.5499
test [full], NDCG@5: 0.7846, HR@5: 0.9192, NDCG@10: 0.8115, HR@10: 1.0000, MRR: 0.7506
test [sampled], NDCG@5: 0.3486, HR@5: 0.3644, NDCG@10: 0.3985, HR@10: 0.5240, MRR: 0.3892
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0874
epoch=22, loss=0.0860
epoch=23, loss=0.0854
epoch=24, loss=0.0849
epoch=25, loss=0.0852
valid [full], NDCG@5: 0.6734, HR@5: 0.8236, NDCG@10: 0.7159, HR@10: 0.9563, MRR: 0.6459
valid [sampled], NDCG@5: 0.5359, HR@5: 0.5448, NDCG@10: 0.5516, HR@10: 0.5946, MRR: 0.5540
test [full], NDCG@5: 0.7868, HR@5: 0.9251, NDCG@10: 0.8121, HR@10: 0.9999, MRR: 0.7510
test [sampled], NDCG@5: 0.3609, HR@5: 0.3724, NDCG@10: 0.4069, HR@10: 0.5203, MRR: 0.4019
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=26, loss=0.0817
epoch=27, loss=0.0842
epoch=28, loss=0.0836
epoch=29, loss=0.0850
epoch=30, loss=0.0813
valid [full], NDCG@5: 0.6754, HR@5: 0.8215, NDCG@10: 0.7212, HR@10: 0.9615, MRR: 0.6504
valid [sampled], NDCG@5: 0.5384, HR@5: 0.5487, NDCG@10: 0.5548, HR@10: 0.6003, MRR: 0.5567
test [full], NDCG@5: 0.7988, HR@5: 0.9289, NDCG@10: 0.8219, HR@10: 1.0000, MRR: 0.7637
test [sampled], NDCG@5: 0.3772, HR@5: 0.3862, NDCG@10: 0.4226, HR@10: 0.5331, MRR: 0.4181
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/sasrec_best.pth
epoch=31, loss=0.0839
epoch=32, loss=0.0837
epoch=33, loss=0.0823
epoch=34, loss=0.0835
epoch=35, loss=0.0825
valid [full], NDCG@5: 0.6474, HR@5: 0.7506, NDCG@10: 0.7120, HR@10: 0.9472, MRR: 0.6453
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5680, NDCG@10: 0.5743, HR@10: 0.6174, MRR: 0.5743
test [full], NDCG@5: 0.7791, HR@5: 0.9031, NDCG@10: 0.8111, HR@10: 0.9999, MRR: 0.7500
test [sampled], NDCG@5: 0.3741, HR@5: 0.3834, NDCG@10: 0.4210, HR@10: 0.5346, MRR: 0.4148
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0823
epoch=37, loss=0.0809
epoch=38, loss=0.0815
epoch=39, loss=0.0804
epoch=40, loss=0.0790
valid [full], NDCG@5: 0.6647, HR@5: 0.7815, NDCG@10: 0.7187, HR@10: 0.9461, MRR: 0.6540
valid [sampled], NDCG@5: 0.5584, HR@5: 0.5697, NDCG@10: 0.5767, HR@10: 0.6268, MRR: 0.5748
test [full], NDCG@5: 0.7760, HR@5: 0.8960, NDCG@10: 0.8106, HR@10: 1.0000, MRR: 0.7490
test [sampled], NDCG@5: 0.3686, HR@5: 0.3816, NDCG@10: 0.4162, HR@10: 0.5338, MRR: 0.4088
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0810
epoch=42, loss=0.0826
epoch=43, loss=0.0800
epoch=44, loss=0.0800
epoch=45, loss=0.0784
valid [full], NDCG@5: 0.6537, HR@5: 0.7729, NDCG@10: 0.7124, HR@10: 0.9488, MRR: 0.6451
valid [sampled], NDCG@5: 0.5519, HR@5: 0.5642, NDCG@10: 0.5658, HR@10: 0.6070, MRR: 0.5666
test [full], NDCG@5: 0.7832, HR@5: 0.9058, NDCG@10: 0.8145, HR@10: 1.0000, MRR: 0.7541
test [sampled], NDCG@5: 0.3790, HR@5: 0.3931, NDCG@10: 0.4277, HR@10: 0.5493, MRR: 0.4186
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0793
epoch=47, loss=0.0800
epoch=48, loss=0.0796
epoch=49, loss=0.0780
epoch=50, loss=0.0799
valid [full], NDCG@5: 0.6550, HR@5: 0.7617, NDCG@10: 0.7250, HR@10: 0.9751, MRR: 0.6519
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5698, NDCG@10: 0.5724, HR@10: 0.6183, MRR: 0.5719
test [full], NDCG@5: 0.7772, HR@5: 0.8974, NDCG@10: 0.8103, HR@10: 1.0000, MRR: 0.7490
test [sampled], NDCG@5: 0.3805, HR@5: 0.3913, NDCG@10: 0.4264, HR@10: 0.5389, MRR: 0.4202
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s2024/sasrec_last.pth

### timeaware_anchor_ml20_b9_s7

In [23]:
!python src/train_sasrec.py \
  --run_name timeaware_anchor_ml20_b9_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7
epoch=1, loss=0.6771
epoch=2, loss=0.3217
epoch=3, loss=0.2233
epoch=4, loss=0.1713
epoch=5, loss=0.1432
valid [full], NDCG@5: 0.6560, HR@5: 0.8076, NDCG@10: 0.7039, HR@10: 0.9593, MRR: 0.6304
valid [sampled], NDCG@5: 0.5389, HR@5: 0.5402, NDCG@10: 0.5440, HR@10: 0.5565, MRR: 0.5563
test [full], NDCG@5: 0.6490, HR@5: 0.9041, NDCG@10: 0.6739, HR@10: 0.9796, MRR: 0.5769
test [sampled], NDCG@5: 0.1676, HR@5: 0.1700, NDCG@10: 0.1851, HR@10: 0.2276, MRR: 0.2152
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=6, loss=0.1278
epoch=7, loss=0.1195
epoch=8, loss=0.1089
epoch=9, loss=0.1059
epoch=10, loss=0.1017
valid [full], NDCG@5: 0.6626, HR@5: 0.8288, NDCG@10: 0.6983, HR@10: 0.9397, MRR: 0.6298
valid [sampled], NDCG@5: 0.5332, HR@5: 0.5340, NDCG@10: 0.5372, HR@10: 0.5468, MRR: 0.5504
test [full], NDCG@5: 0.6936, HR@5: 0.9773, NDCG@10: 0.7009, HR@10: 0.9984, MRR: 0.6034
test [sampled], NDCG@5: 0.1706, HR@5: 0.1763, NDCG@10: 0.1972, HR@10: 0.2629, MRR: 0.2216
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=11, loss=0.1005
epoch=12, loss=0.0970
epoch=13, loss=0.0929
epoch=14, loss=0.0928
epoch=15, loss=0.0925
valid [full], NDCG@5: 0.6615, HR@5: 0.8356, NDCG@10: 0.6990, HR@10: 0.9532, MRR: 0.6249
valid [sampled], NDCG@5: 0.5266, HR@5: 0.5291, NDCG@10: 0.5342, HR@10: 0.5532, MRR: 0.5456
test [full], NDCG@5: 0.7183, HR@5: 0.9793, NDCG@10: 0.7254, HR@10: 0.9999, MRR: 0.6348
test [sampled], NDCG@5: 0.1851, HR@5: 0.1935, NDCG@10: 0.2154, HR@10: 0.2918, MRR: 0.2361
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0917
epoch=17, loss=0.0892
epoch=18, loss=0.0870
epoch=19, loss=0.0866
epoch=20, loss=0.0875
valid [full], NDCG@5: 0.6907, HR@5: 0.8579, NDCG@10: 0.7215, HR@10: 0.9542, MRR: 0.6526
valid [sampled], NDCG@5: 0.5425, HR@5: 0.5531, NDCG@10: 0.5610, HR@10: 0.6107, MRR: 0.5627
test [full], NDCG@5: 0.7853, HR@5: 0.9997, NDCG@10: 0.7854, HR@10: 1.0000, MRR: 0.7120
test [sampled], NDCG@5: 0.2188, HR@5: 0.2401, NDCG@10: 0.2852, HR@10: 0.4519, MRR: 0.2724
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=21, loss=0.0852
epoch=22, loss=0.0849
epoch=23, loss=0.0857
epoch=24, loss=0.0852
epoch=25, loss=0.0842
valid [full], NDCG@5: 0.6827, HR@5: 0.8483, NDCG@10: 0.7184, HR@10: 0.9585, MRR: 0.6467
valid [sampled], NDCG@5: 0.5256, HR@5: 0.5302, NDCG@10: 0.5416, HR@10: 0.5813, MRR: 0.5486
test [full], NDCG@5: 0.8191, HR@5: 0.9995, NDCG@10: 0.8193, HR@10: 1.0000, MRR: 0.7579
test [sampled], NDCG@5: 0.2608, HR@5: 0.2931, NDCG@10: 0.3224, HR@10: 0.4887, MRR: 0.3067
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0843
epoch=27, loss=0.0849
epoch=28, loss=0.0823
epoch=29, loss=0.0819
epoch=30, loss=0.0812
valid [full], NDCG@5: 0.6913, HR@5: 0.8522, NDCG@10: 0.7255, HR@10: 0.9585, MRR: 0.6560
valid [sampled], NDCG@5: 0.5270, HR@5: 0.5356, NDCG@10: 0.5464, HR@10: 0.5970, MRR: 0.5493
test [full], NDCG@5: 0.8380, HR@5: 0.9996, NDCG@10: 0.8382, HR@10: 1.0000, MRR: 0.7827
test [sampled], NDCG@5: 0.2930, HR@5: 0.3305, NDCG@10: 0.3593, HR@10: 0.5407, MRR: 0.3365
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=31, loss=0.0842
epoch=32, loss=0.0802
epoch=33, loss=0.0819
epoch=34, loss=0.0798
epoch=35, loss=0.0811
valid [full], NDCG@5: 0.6751, HR@5: 0.8281, NDCG@10: 0.7125, HR@10: 0.9457, MRR: 0.6444
valid [sampled], NDCG@5: 0.5290, HR@5: 0.5395, NDCG@10: 0.5452, HR@10: 0.5901, MRR: 0.5486
test [full], NDCG@5: 0.8131, HR@5: 0.9949, NDCG@10: 0.8150, HR@10: 1.0000, MRR: 0.7510
test [sampled], NDCG@5: 0.2665, HR@5: 0.2936, NDCG@10: 0.3327, HR@10: 0.5038, MRR: 0.3160
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0817
epoch=37, loss=0.0813
epoch=38, loss=0.0803
epoch=39, loss=0.0797
epoch=40, loss=0.0818
valid [full], NDCG@5: 0.7125, HR@5: 0.8719, NDCG@10: 0.7400, HR@10: 0.9612, MRR: 0.6734
valid [sampled], NDCG@5: 0.5427, HR@5: 0.5592, NDCG@10: 0.5710, HR@10: 0.6483, MRR: 0.5645
test [full], NDCG@5: 0.8037, HR@5: 0.9921, NDCG@10: 0.8065, HR@10: 1.0000, MRR: 0.7401
test [sampled], NDCG@5: 0.2287, HR@5: 0.2626, NDCG@10: 0.2994, HR@10: 0.4867, MRR: 0.2786
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
epoch=41, loss=0.0821
epoch=42, loss=0.0788
epoch=43, loss=0.0778
epoch=44, loss=0.0817
epoch=45, loss=0.0795
valid [full], NDCG@5: 0.7111, HR@5: 0.8763, NDCG@10: 0.7380, HR@10: 0.9624, MRR: 0.6706
valid [sampled], NDCG@5: 0.5440, HR@5: 0.5568, NDCG@10: 0.5704, HR@10: 0.6402, MRR: 0.5662
test [full], NDCG@5: 0.8294, HR@5: 0.9816, NDCG@10: 0.8359, HR@10: 1.0000, MRR: 0.7793
test [sampled], NDCG@5: 0.2935, HR@5: 0.3303, NDCG@10: 0.3639, HR@10: 0.5532, MRR: 0.3383
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0780
epoch=47, loss=0.0783
epoch=48, loss=0.0782
epoch=49, loss=0.0776
epoch=50, loss=0.0785
valid [full], NDCG@5: 0.7146, HR@5: 0.8674, NDCG@10: 0.7438, HR@10: 0.9605, MRR: 0.6789
valid [sampled], NDCG@5: 0.5508, HR@5: 0.5668, NDCG@10: 0.5825, HR@10: 0.6670, MRR: 0.5733
test [full], NDCG@5: 0.8340, HR@5: 0.9716, NDCG@10: 0.8440, HR@10: 1.0000, MRR: 0.7905
test [sampled], NDCG@5: 0.3225, HR@5: 0.3522, NDCG@10: 0.3868, HR@10: 0.5562, MRR: 0.3663
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg5/timeaware_anchor_ml20_b9_s7/sasrec_last.pth

## Rebuild result tables from run folders

This avoids schema issues and lets us combine existing baseline runs with new time-aware runs safely.

In [26]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'time_bucket_boundaries': ','.join(str(x) for x in config.get('time_bucket_boundaries', [])),
            'time_bucket_count': config.get('time_bucket_count'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [27]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## NDCG@10 comparison summary

In [28]:
baseline_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
]
timeaware_runs = [
    'timeaware_anchor_ml20_b8_s42',
    'timeaware_anchor_ml20_b8_s2024',
    'timeaware_anchor_ml20_b8_s7',
    'timeaware_anchor_ml20_b9_s42',
    'timeaware_anchor_ml20_b9_s2024',
    'timeaware_anchor_ml20_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['bucket_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['bucket_variant'] = timeaware_subset['run_name'].apply(lambda x: 'b8' if '_b8_' in x else 'b9')

df_ndcg10 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['bucket_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'bucket_variant', 'use_time_embedding', 'time_bucket_boundaries',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                         run_name  seed bucket_variant  use_time_embedding                           time_bucket_boundaries  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     timeaware_anchor_ml20_b8_s7     7             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.755893               0.958773                0.734980              0.889970             0.695174                0.807914              1.000000               0.807725             0.999458            0.743702                    0.607341                  0.677989                   0.579652                 0.590082                0.602256                   0.335040                 0.452994                  0.289917                0.309808               0.335265
1    timeaware_anchor_ml20_b8_s42    42             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.714948               0.976252                0.669355              0.832406             0.636630                0.804902              1.000000               0.794084             0.966734            0.739006                    0.537377                  0.580867                   0.520171                 0.526145                0.542696                   0.379151                 0.515020                  0.323546                0.335871               0.371140
2  timeaware_anchor_ml20_b8_s2024  2024             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.729521               0.977380                0.690536              0.855614             0.654781                0.820632              1.000000               0.799047             0.933586            0.762066                    0.551496                  0.599456                   0.533787                 0.543810                0.554080                   0.412570                 0.523190                  0.367354                0.377000               0.408648
3     timeaware_anchor_ml20_b9_s7     7             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.743844               0.960530                0.714598              0.867397             0.678884                0.843990              1.000000               0.834025             0.971564            0.790520                    0.582482                  0.666984                   0.550773                 0.566848                0.573250                   0.386793                 0.556218                  0.322537                0.352208               0.366348
4    timeaware_anchor_ml20_b9_s42    42             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.715128               0.981350                0.642260              0.750340             0.638622                0.813155              1.000000               0.778245             0.893199            0.753896                    0.565702                  0.581509                   0.559273                 0.560707                0.575554                   0.269814                 0.520394                  0.187604                0.266343               0.220679
5  timeaware_anchor_ml20_b9_s2024  2024             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.724989               0.975136                0.655030              0.761685             0.651891                0.810350              1.000000               0.777245             0.897405            0.749042                    0.572362                  0.618261                   0.556768                 0.569764                0.571922                   0.426353                 0.538939                  0.380476                0.391281               0.420197
6                  anchor_ml20_s7     7       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.753294               0.961857                0.729167              0.883942             0.691225                0.913637              1.000000               0.903861             0.971918            0.885501                    0.601240                  0.661113                   0.580044                 0.594609                0.597937                   0.480200                 0.667438                  0.420861                0.484209               0.443705
7                 anchor_ml20_s42    42       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296              1.000000               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
8               anchor_ml20_s2024  2024       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.736821               0.967429                0.700301              0.850202             0.668534                0.840611              0.999865               0.819421             0.937829            0.789072                    0.574314                  0.616064                   0.557801                 0.563197                0.578608                   0.323103                 0.518524                  0.261120                0.326822               0.292464

In [29]:
summary_ndcg10 = df_ndcg10.groupby('bucket_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

               best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                  mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
bucket_variant
b8                            0.733454  0.020754              0.970802  0.010433               0.698290  0.033493             0.859330  0.028961            0.662195  0.029968               0.811149  0.008349             1.000000  0.000000              0.800285  0.006904            0.966593  0.032936           0.748258  0.012186                   0.565405  0.036998                 0.619437  0.051552                  0.544537  0.031164                0.553345  0.033018               0.566344  0.031618                  0.375587  0.038888                0.497068  0.038387                 0.326939  0.038830               0.340893  0.033877              0.371684  0.036695
b9                            0.727987  0.014591              0.972339  0.010688               0.670629  0.038609             0.793141  0.064557            0.656466  0.020517               0.822498  0.018665             1.000000  0.000000              0.796505  0.032497            0.920722  0.044080           0.764486  0.022676                   0.573515  0.008449                 0.622251  0.042877                  0.555605  0.004368                0.565773  0.004623               0.573575  0.001837                  0.360987  0.081398                0.538517  0.017915                 0.296873  0.098964               0.336610  0.063913              0.335741  0.103220
baseline                      0.746827  0.008788              0.968944  0.007954               0.712751  0.014836             0.860883  0.019988            0.680520  0.011400               0.889848  0.042649             0.999955  0.000078              0.879032  0.051864            0.968510  0.029126           0.853805  0.056064                   0.586415  0.013668                 0.643839  0.024291                  0.564734  0.013279                0.575209  0.016959               0.584993  0.011211                  0.422731  0.086620                0.612810  0.081997                 0.362874  0.088408               0.428098  0.087878              0.388797  0.083699

Interpretation guide for NDCG@10:
- first compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` across `baseline`, `b8`, and `b9`
- then check whether sampled metrics and MRR show a similar trend
- baseline is reused from the completed sanity-check winner; only time-aware runs are newly trained here

## NDCG@5 comparison summary

In [30]:
baseline_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
]
timeaware_runs = [
    'timeaware_anchor_ml20_b8_s42',
    'timeaware_anchor_ml20_b8_s2024',
    'timeaware_anchor_ml20_b8_s7',
    'timeaware_anchor_ml20_b9_s42',
    'timeaware_anchor_ml20_b9_s2024',
    'timeaware_anchor_ml20_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['bucket_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['bucket_variant'] = timeaware_subset['run_name'].apply(lambda x: 'b8' if '_b8_' in x else 'b9')

df_ndcg5 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['bucket_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'bucket_variant', 'use_time_embedding', 'time_bucket_boundaries',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                         run_name  seed bucket_variant  use_time_embedding                           time_bucket_boundaries  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     timeaware_anchor_ml20_b8_s7     7             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.755893               0.958773                0.734980              0.889970             0.695174                0.807914              1.000000               0.807725             0.999458            0.743702                    0.607341                  0.677989                   0.579652                 0.590082                0.602256                   0.335040                 0.452994                  0.289917                0.309808               0.335265
1    timeaware_anchor_ml20_b8_s42    42             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.714948               0.976252                0.669355              0.832406             0.636630                0.804902              1.000000               0.794084             0.966734            0.739006                    0.537377                  0.580867                   0.520171                 0.526145                0.542696                   0.379151                 0.515020                  0.323546                0.335871               0.371140
2  timeaware_anchor_ml20_b8_s2024  2024             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.729521               0.977380                0.690536              0.855614             0.654781                0.820632              1.000000               0.799047             0.933586            0.762066                    0.551496                  0.599456                   0.533787                 0.543810                0.554080                   0.412570                 0.523190                  0.367354                0.377000               0.408648
3     timeaware_anchor_ml20_b9_s7     7             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.743844               0.960530                0.714598              0.867397             0.678884                0.843990              1.000000               0.834025             0.971564            0.790520                    0.582482                  0.666984                   0.550773                 0.566848                0.573250                   0.386793                 0.556218                  0.322537                0.352208               0.366348
4    timeaware_anchor_ml20_b9_s42    42             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.710988               0.950629                0.671512              0.825916             0.639986                0.799224              1.000000               0.799134             0.999728            0.731606                    0.519510                  0.591294                   0.492885                 0.507642                0.516172                   0.398216                 0.527555                  0.345916                0.359777               0.392595
5  timeaware_anchor_ml20_b9_s2024  2024             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.721180               0.961533                0.675432              0.821482             0.650350                0.821910              1.000000               0.798775             0.928852            0.763670                    0.554774                  0.600272                   0.538369                 0.548707                0.556652                   0.422625                 0.533089                  0.377200                0.386222               0.418122
6                  anchor_ml20_s7     7       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.753294               0.961857                0.729167              0.883942             0.691225                0.913637              1.000000               0.903861             0.971918            0.885501                    0.601240                  0.661113                   0.580044                 0.594609                0.597937                   0.480200                 0.667438                  0.420861                0.484209               0.443705
7                 anchor_ml20_s42    42       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296              1.000000               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
8               anchor_ml20_s2024  2024       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.736821               0.967429                0.700301              0.850202             0.668534                0.840611              0.999865               0.819421             0.937829            0.789072                    0.574314                  0.616064                   0.557801                 0.563197                0.578608                   0.323103                 0.518524                  0.261120                0.326822               0.292464

In [31]:
summary_ndcg5 = df_ndcg5.groupby('bucket_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

               best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                  mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
bucket_variant
b8                            0.733454  0.020754              0.970802  0.010433               0.698290  0.033493             0.859330  0.028961            0.662195  0.029968               0.811149  0.008349             1.000000  0.000000              0.800285  0.006904            0.966593  0.032936           0.748258  0.012186                   0.565405  0.036998                 0.619437  0.051552                  0.544537  0.031164                0.553345  0.033018               0.566344  0.031618                  0.375587  0.038888                0.497068  0.038387                 0.326939  0.038830               0.340893  0.033877              0.371684  0.036695
b9                            0.725337  0.016818              0.957564  0.006027               0.687181  0.023825             0.838265  0.025326            0.656407  0.020144               0.821708  0.022384             1.000000  0.000000              0.810645  0.020249            0.966714  0.035686           0.761932  0.029495                   0.552255  0.031561                 0.619516  0.041352                  0.527343  0.030478                0.541066  0.030334               0.548692  0.029360                  0.402545  0.018304                0.538954  0.015205                 0.348551  0.027427               0.366069  0.017859              0.392355  0.025888
baseline                      0.746827  0.008788              0.968944  0.007954               0.712751  0.014836             0.860883  0.019988            0.680520  0.011400               0.889848  0.042649             0.999955  0.000078              0.879032  0.051864            0.968510  0.029126           0.853805  0.056064                   0.586415  0.013668                 0.643839  0.024291                  0.564734  0.013279                0.575209  0.016959               0.584993  0.011211                  0.422731  0.086620                0.612810  0.081997                 0.362874  0.088408               0.428098  0.087878              0.388797  0.083699

Interpretation guide for NDCG@5:
- first compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` across `baseline`, `b8`, and `b9`
- then check whether sampled metrics and MRR show a similar trend
- baseline is reused from the completed sanity-check winner; only time-aware runs are newly trained here