# SASRec Stage 3 Baseline Multi-Task BPI2012 Colab Train 02

This notebook is the Stage 3 follow-up version.

Main changes from `01`:
- reuse all available single-task baseline seeds (`42`, `2024`, `7`)
- compare multi-task runs with the same 3 seeds
- inspect mean/std instead of only `s42`
- show task metrics with the final metric names used in later experiments

Main comparison metric:
- `full ranking + NDCG@10`

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.11.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
MULTITASK_BASELINE_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('MULTITASK_BASELINE_OUTPUT_DIR:', MULTITASK_BASELINE_OUTPUT_DIR)
print('NOTEBOOK_DIR:', NOTEBOOK_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
MULTITASK_BASELINE_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10
NOTEBOOK_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/notebooks

In [6]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$MULTITASK_BASELINE_OUTPUT_DIR"

In [7]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [8]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [9]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.11.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.4)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [10]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [11]:
%cd /content/time-aware-behavior-prediction
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Verify Stage 3 processed file

Stage 3 next-time prediction uses the processed time-feature CSV.
This check confirms that `delta_next_seconds` already exists.

In [12]:
import pandas as pd

time_features_path = 'data/processed/bpi2012_complete_only/events_encoded_time_features.csv'
df = pd.read_csv(time_features_path)
required_cols = [
    'delta_prev_seconds',
    'delta_start_seconds',
    'delta_next_seconds',
]
missing = [c for c in required_cols if c not in df.columns]

if missing:
    raise ValueError(f'Missing required Stage 3 columns: {missing}')

print('Stage 3 processed file is ready.')
print(df.columns.tolist())
df[['user_id', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds']].head()

Stage 3 processed file is ready.
['case_id', 'activity', 'lifecycle', 'timestamp', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds', 'user_id', 'item_id']

,user_id,event_idx,delta_prev_seconds,delta_start_seconds,delta_next_seconds
0,1,0,0.000,0.000,0.334
1,1,1,0.334,0.334,53.026
2,1,2,53.026,53.360,39785.402
3,1,3,39785.402,39838.762,145.935
4,1,4,145.935,39984.697,-0.000

## Experiment design

Stage 3 baseline multi-task runs:

- backbone 1: `anchor_ml20`
- backbone 2: `refine_ml50_do035`
- multi-task outputs: `next activity + next time`
- time target: `delta_next_seconds`
- time target transform: `log1p`
- time loss: `huber`
- time loss weight: `1.0`
- best epoch criterion: `full_valid_ndcg@10`
- final comparison should use all 3 seeds when available: `42`, `2024`, `7`

## Check prerequisite baseline runs (all 3 seeds)

In [13]:
from pathlib import Path

baseline_required_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

output_dir = Path(BASELINE_NDCG10_OUTPUT_DIR)
print('=' * 80)
print('Baseline NDCG@10 prerequisite runs')
for run_name in baseline_required_runs:
    run_dir = output_dir / run_name
    print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10 prerequisite runs
anchor_ml20_s42 EXISTS
anchor_ml20_s2024 EXISTS
anchor_ml20_s7 EXISTS
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS

## Check planned multi-task runs

In [14]:
planned_multitask_runs = [
    'multitask_anchor_ml20_s42',
    'multitask_anchor_ml20_s2024',
    'multitask_anchor_ml20_s7',
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]

output_dir = Path(MULTITASK_BASELINE_OUTPUT_DIR)
print('=' * 80)
print('Stage 3 baseline multi-task runs')
for run_name in planned_multitask_runs:
    run_dir = output_dir / run_name
    print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Stage 3 baseline multi-task runs
multitask_anchor_ml20_s42 EXISTS
multitask_anchor_ml20_s2024 EXISTS
multitask_anchor_ml20_s7 EXISTS
multitask_refine_ml50_do035_s42 EXISTS
multitask_refine_ml50_do035_s2024 EXISTS
multitask_refine_ml50_do035_s7 EXISTS

## Train multi-task runs

In [15]:
!python src/train_sasrec.py \
  --run_name multitask_anchor_ml20_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42
epoch=1, loss=2.5763
epoch=2, loss=1.5438
epoch=3, loss=1.4283
epoch=4, loss=1.3598
epoch=5, loss=1.3169
valid [task], Top5Acc: 0.4004, Top10Acc: 0.7708, Acc: 0.0551, MacroF1: 0.0988, TimeMAE: 70257.4629, TimeRMSE: 275813.0764, TimeMedAE: 878.5276
valid [full], NDCG@5: 0.6264, HR@5: 0.7599, NDCG@10: 0.6882, HR@10: 0.9589, MRR: 0.6119
valid [sampled], NDCG@5: 0.5231, HR@5: 0.5234, NDCG@10: 0.5258, HR@10: 0.5317, MRR: 0.5389
test [task], Top5Acc: 0.0465, Top10Acc: 0.5384, Acc: 0.0141, MacroF1: 0.0150, TimeMAE: 11838.0120, TimeRMSE: 80375.7233, TimeMedAE: 18.9408
test [full], NDCG@5: 0.5044, HR@5: 0.7720, NDCG@10: 0.5789, HR@10: 0.9948, MRR: 0.4511
test [sampled], NDCG@5: 0.1488, HR@5: 0.1493, NDCG@10: 0.1517, HR@10: 0.1585, MRR: 0.1817
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/sasrec_best.pth
epoch=6, loss=1.2768
epoch=7, loss=1.2440
epoch=8, loss=1.2293
epoch=9, loss=1.2198
epoch=10, loss=1.1948
valid [task], Top5Acc: 0.4393, Top10Acc: 0.7199, Acc: 0.0566, MacroF1: 0.1012, TimeMAE: 73042.4915, TimeRMSE: 280169.5301, TimeMedAE: 2841.6642
valid [full], NDCG@5: 0.6488, HR@5: 0.7116, NDCG@10: 0.7298, HR@10: 0.9690, MRR: 0.6636
valid [sampled], NDCG@5: 0.5995, HR@5: 0.6000, NDCG@10: 0.6010, HR@10: 0.6048, MRR: 0.6104
test [task], Top5Acc: 0.2907, Top10Acc: 0.5856, Acc: 0.0154, MacroF1: 0.0165, TimeMAE: 13148.2232, TimeRMSE: 77550.7323, TimeMedAE: 20.4210
test [full], NDCG@5: 0.6303, HR@5: 0.8882, NDCG@10: 0.6659, HR@10: 1.0000, MRR: 0.5560
test [sampled], NDCG@5: 0.1101, HR@5: 0.1140, NDCG@10: 0.1469, HR@10: 0.2320, MRR: 0.1620
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/sasrec_best.pth
epoch=11, loss=1.1900
epoch=12, loss=1.1899
epoch=13, loss=1.1753
epoch=14, loss=1.1842
epoch=15, loss=1.1689
valid [task], Top5Acc: 0.3946, Top10Acc: 0.6961, Acc: 0.0551, MacroF1: 0.0684, TimeMAE: 73459.6493, TimeRMSE: 281435.3356, TimeMedAE: 6070.5624
valid [full], NDCG@5: 0.6515, HR@5: 0.7610, NDCG@10: 0.7174, HR@10: 0.9700, MRR: 0.6452
valid [sampled], NDCG@5: 0.5537, HR@5: 0.5572, NDCG@10: 0.5639, HR@10: 0.5890, MRR: 0.5694
test [task], Top5Acc: 0.4474, Top10Acc: 0.6420, Acc: 0.0172, MacroF1: 0.0153, TimeMAE: 12608.1956, TimeRMSE: 73713.5654, TimeMedAE: 40.7931
test [full], NDCG@5: 0.7968, HR@5: 0.9108, NDCG@10: 0.8262, HR@10: 1.0000, MRR: 0.7700
test [sampled], NDCG@5: 0.1808, HR@5: 0.2272, NDCG@10: 0.2513, HR@10: 0.4480, MRR: 0.2242
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=1.1587
epoch=17, loss=1.1545
epoch=18, loss=1.1562
epoch=19, loss=1.1550
epoch=20, loss=1.1449
valid [task], Top5Acc: 0.4213, Top10Acc: 0.6013, Acc: 0.0470, MacroF1: 0.0440, TimeMAE: 77337.0189, TimeRMSE: 285206.4250, TimeMedAE: 3030.6868
valid [full], NDCG@5: 0.6670, HR@5: 0.7765, NDCG@10: 0.7281, HR@10: 0.9691, MRR: 0.6588
valid [sampled], NDCG@5: 0.5693, HR@5: 0.5730, NDCG@10: 0.5783, HR@10: 0.6017, MRR: 0.5842
test [task], Top5Acc: 0.4574, Top10Acc: 0.6289, Acc: 0.0131, MacroF1: 0.0084, TimeMAE: 13649.3968, TimeRMSE: 72703.2040, TimeMedAE: 39.1284
test [full], NDCG@5: 0.8273, HR@5: 0.9078, NDCG@10: 0.8578, HR@10: 1.0000, MRR: 0.8131
test [sampled], NDCG@5: 0.2162, HR@5: 0.2720, NDCG@10: 0.2902, HR@10: 0.5025, MRR: 0.2537
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.1529
epoch=22, loss=1.1522
epoch=23, loss=1.1394
epoch=24, loss=1.1376
epoch=25, loss=1.1330
valid [task], Top5Acc: 0.3987, Top10Acc: 0.5911, Acc: 0.0550, MacroF1: 0.0370, TimeMAE: 76206.6568, TimeRMSE: 291258.3538, TimeMedAE: 3658.6471
valid [full], NDCG@5: 0.6738, HR@5: 0.8378, NDCG@10: 0.7161, HR@10: 0.9750, MRR: 0.6393
valid [sampled], NDCG@5: 0.5251, HR@5: 0.5291, NDCG@10: 0.5344, HR@10: 0.5584, MRR: 0.5433
test [task], Top5Acc: 0.4206, Top10Acc: 0.6275, Acc: 0.0111, MacroF1: 0.0066, TimeMAE: 12553.0882, TimeRMSE: 69896.5936, TimeMedAE: 18.2198
test [full], NDCG@5: 0.7517, HR@5: 0.9247, NDCG@10: 0.7769, HR@10: 1.0000, MRR: 0.7030
test [sampled], NDCG@5: 0.2107, HR@5: 0.2328, NDCG@10: 0.2611, HR@10: 0.3918, MRR: 0.2572
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1268
epoch=27, loss=1.1301
epoch=28, loss=1.1348
epoch=29, loss=1.1282
epoch=30, loss=1.1313
valid [task], Top5Acc: 0.4084, Top10Acc: 0.6928, Acc: 0.0537, MacroF1: 0.0522, TimeMAE: 74664.9504, TimeRMSE: 282278.0303, TimeMedAE: 6863.6727
valid [full], NDCG@5: 0.7061, HR@5: 0.8561, NDCG@10: 0.7424, HR@10: 0.9761, MRR: 0.6717
valid [sampled], NDCG@5: 0.5385, HR@5: 0.5456, NDCG@10: 0.5549, HR@10: 0.5974, MRR: 0.5594
test [task], Top5Acc: 0.4789, Top10Acc: 0.6682, Acc: 0.0147, MacroF1: 0.0120, TimeMAE: 14168.8950, TimeRMSE: 78819.2271, TimeMedAE: 129.4086
test [full], NDCG@5: 0.7854, HR@5: 0.9293, NDCG@10: 0.8092, HR@10: 1.0000, MRR: 0.7457
test [sampled], NDCG@5: 0.3238, HR@5: 0.3429, NDCG@10: 0.3670, HR@10: 0.4779, MRR: 0.3638
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/sasrec_best.pth
epoch=31, loss=1.1198
epoch=32, loss=1.1221
epoch=33, loss=1.1273
epoch=34, loss=1.1195
epoch=35, loss=1.1220
valid [task], Top5Acc: 0.4023, Top10Acc: 0.6879, Acc: 0.0544, MacroF1: 0.0376, TimeMAE: 75984.4756, TimeRMSE: 278080.8265, TimeMedAE: 4332.8245
valid [full], NDCG@5: 0.6988, HR@5: 0.8528, NDCG@10: 0.7262, HR@10: 0.9425, MRR: 0.6627
valid [sampled], NDCG@5: 0.5310, HR@5: 0.5362, NDCG@10: 0.5450, HR@10: 0.5806, MRR: 0.5523
test [task], Top5Acc: 0.4777, Top10Acc: 0.6739, Acc: 0.0159, MacroF1: 0.0099, TimeMAE: 15619.9533, TimeRMSE: 70691.9149, TimeMedAE: 243.4300
test [full], NDCG@5: 0.7829, HR@5: 0.9225, NDCG@10: 0.8092, HR@10: 1.0000, MRR: 0.7455
test [sampled], NDCG@5: 0.2886, HR@5: 0.3070, NDCG@10: 0.3317, HR@10: 0.4430, MRR: 0.3307
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1267
epoch=37, loss=1.1116
epoch=38, loss=1.1053
epoch=39, loss=1.1182
epoch=40, loss=1.1135
valid [task], Top5Acc: 0.4005, Top10Acc: 0.6770, Acc: 0.0516, MacroF1: 0.0656, TimeMAE: 71065.8855, TimeRMSE: 269209.1387, TimeMedAE: 5599.8781
valid [full], NDCG@5: 0.7024, HR@5: 0.8498, NDCG@10: 0.7312, HR@10: 0.9426, MRR: 0.6690
valid [sampled], NDCG@5: 0.5287, HR@5: 0.5355, NDCG@10: 0.5489, HR@10: 0.5989, MRR: 0.5515
test [task], Top5Acc: 0.4716, Top10Acc: 0.6649, Acc: 0.0121, MacroF1: 0.0101, TimeMAE: 12861.1250, TimeRMSE: 66020.5432, TimeMedAE: 330.2540
test [full], NDCG@5: 0.7791, HR@5: 0.9376, NDCG@10: 0.8002, HR@10: 1.0000, MRR: 0.7333
test [sampled], NDCG@5: 0.2777, HR@5: 0.2949, NDCG@10: 0.3235, HR@10: 0.4394, MRR: 0.3213
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.1159
epoch=42, loss=1.1175
epoch=43, loss=1.1213
epoch=44, loss=1.1233
epoch=45, loss=1.1190
valid [task], Top5Acc: 0.4195, Top10Acc: 0.6861, Acc: 0.0619, MacroF1: 0.0628, TimeMAE: 83105.2547, TimeRMSE: 282868.3568, TimeMedAE: 8626.0454
valid [full], NDCG@5: 0.7088, HR@5: 0.8566, NDCG@10: 0.7362, HR@10: 0.9450, MRR: 0.6747
valid [sampled], NDCG@5: 0.5472, HR@5: 0.5512, NDCG@10: 0.5604, HR@10: 0.5929, MRR: 0.5681
test [task], Top5Acc: 0.5073, Top10Acc: 0.6701, Acc: 0.0542, MacroF1: 0.0317, TimeMAE: 17117.9133, TimeRMSE: 73540.9301, TimeMedAE: 436.2500
test [full], NDCG@5: 0.8861, HR@5: 0.9386, NDCG@10: 0.9070, HR@10: 1.0000, MRR: 0.8778
test [sampled], NDCG@5: 0.3829, HR@5: 0.4266, NDCG@10: 0.4365, HR@10: 0.5927, MRR: 0.4111
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1101
epoch=47, loss=1.1101
epoch=48, loss=1.1068
epoch=49, loss=1.1127
epoch=50, loss=1.1041
valid [task], Top5Acc: 0.3958, Top10Acc: 0.7089, Acc: 0.0537, MacroF1: 0.0621, TimeMAE: 77560.8790, TimeRMSE: 279732.4279, TimeMedAE: 8886.6479
valid [full], NDCG@5: 0.7036, HR@5: 0.8602, NDCG@10: 0.7302, HR@10: 0.9447, MRR: 0.6661
valid [sampled], NDCG@5: 0.5307, HR@5: 0.5378, NDCG@10: 0.5485, HR@10: 0.5939, MRR: 0.5523
test [task], Top5Acc: 0.4727, Top10Acc: 0.6684, Acc: 0.0418, MacroF1: 0.0255, TimeMAE: 15395.2112, TimeRMSE: 68897.3634, TimeMedAE: 346.2522
test [full], NDCG@5: 0.8737, HR@5: 0.9417, NDCG@10: 0.8942, HR@10: 1.0000, MRR: 0.8602
test [sampled], NDCG@5: 0.3460, HR@5: 0.3972, NDCG@10: 0.4115, HR@10: 0.6002, MRR: 0.3767
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s42/sasrec_last.pth

In [16]:
!python src/train_sasrec.py \
  --run_name multitask_anchor_ml20_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024
epoch=1, loss=2.8066
epoch=2, loss=1.5922
epoch=3, loss=1.4238
epoch=4, loss=1.3530
epoch=5, loss=1.3070
valid [task], Top5Acc: 0.4705, Top10Acc: 0.7222, Acc: 0.0877, MacroF1: 0.1529, TimeMAE: 76237.8869, TimeRMSE: 291919.8238, TimeMedAE: 1167.8160
valid [full], NDCG@5: 0.6216, HR@5: 0.7224, NDCG@10: 0.6944, HR@10: 0.9546, MRR: 0.6220
valid [sampled], NDCG@5: 0.5316, HR@5: 0.5323, NDCG@10: 0.5372, HR@10: 0.5497, MRR: 0.5476
test [task], Top5Acc: 0.0602, Top10Acc: 0.4795, Acc: 0.0359, MacroF1: 0.0325, TimeMAE: 12705.2599, TimeRMSE: 79468.5364, TimeMedAE: 8.6100
test [full], NDCG@5: 0.5260, HR@5: 0.7389, NDCG@10: 0.6077, HR@10: 1.0000, MRR: 0.4898
test [sampled], NDCG@5: 0.1461, HR@5: 0.1469, NDCG@10: 0.1534, HR@10: 0.1706, MRR: 0.1817
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=6, loss=1.2665
epoch=7, loss=1.2408
epoch=8, loss=1.2335
epoch=9, loss=1.2120
epoch=10, loss=1.2130
valid [task], Top5Acc: 0.4035, Top10Acc: 0.7367, Acc: 0.0848, MacroF1: 0.1250, TimeMAE: 69708.9390, TimeRMSE: 272306.9038, TimeMedAE: 1440.9027
valid [full], NDCG@5: 0.6330, HR@5: 0.7250, NDCG@10: 0.7076, HR@10: 0.9561, MRR: 0.6379
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5603, NDCG@10: 0.5629, HR@10: 0.5734, MRR: 0.5724
test [task], Top5Acc: 0.2902, Top10Acc: 0.6739, Acc: 0.0326, MacroF1: 0.0274, TimeMAE: 12400.5497, TimeRMSE: 72061.6573, TimeMedAE: 79.4116
test [full], NDCG@5: 0.6628, HR@5: 0.9364, NDCG@10: 0.6844, HR@10: 1.0000, MRR: 0.5794
test [sampled], NDCG@5: 0.0960, HR@5: 0.1000, NDCG@10: 0.1345, HR@10: 0.2237, MRR: 0.1527
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=11, loss=1.2018
epoch=12, loss=1.1975
epoch=13, loss=1.1873
epoch=14, loss=1.1762
epoch=15, loss=1.1760
valid [task], Top5Acc: 0.4018, Top10Acc: 0.6228, Acc: 0.0871, MacroF1: 0.1557, TimeMAE: 70894.6507, TimeRMSE: 281660.0658, TimeMedAE: 1055.7523
valid [full], NDCG@5: 0.6255, HR@5: 0.6992, NDCG@10: 0.7002, HR@10: 0.9323, MRR: 0.6377
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5604, NDCG@10: 0.5638, HR@10: 0.5787, MRR: 0.5715
test [task], Top5Acc: 0.1252, Top10Acc: 0.6647, Acc: 0.0483, MacroF1: 0.0353, TimeMAE: 11506.6608, TimeRMSE: 74947.7176, TimeMedAE: 63.5668
test [full], NDCG@5: 0.7360, HR@5: 0.9816, NDCG@10: 0.7424, HR@10: 1.0000, MRR: 0.6568
test [sampled], NDCG@5: 0.1973, HR@5: 0.2089, NDCG@10: 0.2240, HR@10: 0.2933, MRR: 0.2434
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=1.1624
epoch=17, loss=1.1686
epoch=18, loss=1.1637
epoch=19, loss=1.1671
epoch=20, loss=1.1626
valid [task], Top5Acc: 0.4050, Top10Acc: 0.6966, Acc: 0.0819, MacroF1: 0.1117, TimeMAE: 72173.5820, TimeRMSE: 291371.5915, TimeMedAE: 1726.7908
valid [full], NDCG@5: 0.6353, HR@5: 0.7350, NDCG@10: 0.7058, HR@10: 0.9597, MRR: 0.6346
valid [sampled], NDCG@5: 0.5508, HR@5: 0.5527, NDCG@10: 0.5580, HR@10: 0.5754, MRR: 0.5657
test [task], Top5Acc: 0.3553, Top10Acc: 0.6357, Acc: 0.0623, MacroF1: 0.0415, TimeMAE: 12316.4516, TimeRMSE: 74132.6139, TimeMedAE: 45.2746
test [full], NDCG@5: 0.7180, HR@5: 0.9668, NDCG@10: 0.7291, HR@10: 1.0000, MRR: 0.6384
test [sampled], NDCG@5: 0.1832, HR@5: 0.1934, NDCG@10: 0.2223, HR@10: 0.3182, MRR: 0.2325
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.1567
epoch=22, loss=1.1521
epoch=23, loss=1.1516
epoch=24, loss=1.1573
epoch=25, loss=1.1537
valid [task], Top5Acc: 0.4039, Top10Acc: 0.5542, Acc: 0.0864, MacroF1: 0.1287, TimeMAE: 74349.8529, TimeRMSE: 284296.1925, TimeMedAE: 1387.4767
valid [full], NDCG@5: 0.6251, HR@5: 0.7262, NDCG@10: 0.6916, HR@10: 0.9314, MRR: 0.6255
valid [sampled], NDCG@5: 0.5247, HR@5: 0.5271, NDCG@10: 0.5340, HR@10: 0.5564, MRR: 0.5412
test [task], Top5Acc: 0.4056, Top10Acc: 0.6799, Acc: 0.0922, MacroF1: 0.0525, TimeMAE: 13940.4668, TimeRMSE: 76155.0026, TimeMedAE: 62.1819
test [full], NDCG@5: 0.7836, HR@5: 0.9892, NDCG@10: 0.7874, HR@10: 1.0000, MRR: 0.7140
test [sampled], NDCG@5: 0.2373, HR@5: 0.2431, NDCG@10: 0.2758, HR@10: 0.3667, MRR: 0.2889
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1443
epoch=27, loss=1.1435
epoch=28, loss=1.1473
epoch=29, loss=1.1540
epoch=30, loss=1.1300
valid [task], Top5Acc: 0.4040, Top10Acc: 0.6318, Acc: 0.0679, MacroF1: 0.0994, TimeMAE: 76473.5385, TimeRMSE: 292269.6861, TimeMedAE: 3031.9472
valid [full], NDCG@5: 0.6621, HR@5: 0.7796, NDCG@10: 0.7157, HR@10: 0.9476, MRR: 0.6504
valid [sampled], NDCG@5: 0.5615, HR@5: 0.5642, NDCG@10: 0.5695, HR@10: 0.5894, MRR: 0.5766
test [task], Top5Acc: 0.4475, Top10Acc: 0.6565, Acc: 0.0992, MacroF1: 0.0547, TimeMAE: 13231.8862, TimeRMSE: 74164.4714, TimeMedAE: 118.8176
test [full], NDCG@5: 0.7839, HR@5: 0.9954, NDCG@10: 0.7855, HR@10: 1.0000, MRR: 0.7123
test [sampled], NDCG@5: 0.2293, HR@5: 0.2395, NDCG@10: 0.2701, HR@10: 0.3701, MRR: 0.2790
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=31, loss=1.1507
epoch=32, loss=1.1288
epoch=33, loss=1.1476
epoch=34, loss=1.1344
epoch=35, loss=1.1426
valid [task], Top5Acc: 0.4067, Top10Acc: 0.6122, Acc: 0.0603, MacroF1: 0.0741, TimeMAE: 70713.8883, TimeRMSE: 286648.9495, TimeMedAE: 1811.0550
valid [full], NDCG@5: 0.6604, HR@5: 0.7872, NDCG@10: 0.7121, HR@10: 0.9468, MRR: 0.6453
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5537, NDCG@10: 0.5599, HR@10: 0.5791, MRR: 0.5684
test [task], Top5Acc: 0.1364, Top10Acc: 0.6360, Acc: 0.0834, MacroF1: 0.0438, TimeMAE: 12897.7579, TimeRMSE: 79952.2036, TimeMedAE: 104.3409
test [full], NDCG@5: 0.7183, HR@5: 0.9729, NDCG@10: 0.7278, HR@10: 1.0000, MRR: 0.6375
test [sampled], NDCG@5: 0.2027, HR@5: 0.2090, NDCG@10: 0.2251, HR@10: 0.2810, MRR: 0.2487
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1349
epoch=37, loss=1.1369
epoch=38, loss=1.1356
epoch=39, loss=1.1258
epoch=40, loss=1.1289
valid [task], Top5Acc: 0.4025, Top10Acc: 0.6481, Acc: 0.0703, MacroF1: 0.0691, TimeMAE: 76033.3824, TimeRMSE: 296497.5951, TimeMedAE: 1482.5302
valid [full], NDCG@5: 0.6713, HR@5: 0.7989, NDCG@10: 0.7185, HR@10: 0.9456, MRR: 0.6536
valid [sampled], NDCG@5: 0.5575, HR@5: 0.5600, NDCG@10: 0.5656, HR@10: 0.5856, MRR: 0.5742
test [task], Top5Acc: 0.4762, Top10Acc: 0.6648, Acc: 0.1165, MacroF1: 0.0515, TimeMAE: 12305.2889, TimeRMSE: 71731.7118, TimeMedAE: 57.0300
test [full], NDCG@5: 0.8281, HR@5: 0.9924, NDCG@10: 0.8307, HR@10: 1.0000, MRR: 0.7726
test [sampled], NDCG@5: 0.2890, HR@5: 0.3061, NDCG@10: 0.3328, HR@10: 0.4446, MRR: 0.3344
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/sasrec_best.pth
epoch=41, loss=1.1212
epoch=42, loss=1.1298
epoch=43, loss=1.1384
epoch=44, loss=1.1256
epoch=45, loss=1.1237
valid [task], Top5Acc: 0.4003, Top10Acc: 0.5999, Acc: 0.0603, MacroF1: 0.0705, TimeMAE: 76078.7577, TimeRMSE: 288669.5010, TimeMedAE: 2674.6747
valid [full], NDCG@5: 0.6509, HR@5: 0.7684, NDCG@10: 0.7075, HR@10: 0.9462, MRR: 0.6401
valid [sampled], NDCG@5: 0.5466, HR@5: 0.5494, NDCG@10: 0.5550, HR@10: 0.5763, MRR: 0.5625
test [task], Top5Acc: 0.2475, Top10Acc: 0.6639, Acc: 0.1010, MacroF1: 0.0475, TimeMAE: 12974.1709, TimeRMSE: 72926.9797, TimeMedAE: 35.3326
test [full], NDCG@5: 0.7412, HR@5: 0.9898, NDCG@10: 0.7447, HR@10: 1.0000, MRR: 0.6594
test [sampled], NDCG@5: 0.2212, HR@5: 0.2268, NDCG@10: 0.2453, HR@10: 0.3040, MRR: 0.2675
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1209
epoch=47, loss=1.1155
epoch=48, loss=1.1243
epoch=49, loss=1.1138
epoch=50, loss=1.1174
valid [task], Top5Acc: 0.4005, Top10Acc: 0.5805, Acc: 0.0673, MacroF1: 0.0887, TimeMAE: 72802.2378, TimeRMSE: 287247.8856, TimeMedAE: 3157.2148
valid [full], NDCG@5: 0.6579, HR@5: 0.7981, NDCG@10: 0.7052, HR@10: 0.9463, MRR: 0.6356
valid [sampled], NDCG@5: 0.5252, HR@5: 0.5270, NDCG@10: 0.5335, HR@10: 0.5533, MRR: 0.5436
test [task], Top5Acc: 0.4712, Top10Acc: 0.7202, Acc: 0.1010, MacroF1: 0.0574, TimeMAE: 13630.6568, TimeRMSE: 71494.1065, TimeMedAE: 194.1350
test [full], NDCG@5: 0.7710, HR@5: 0.9774, NDCG@10: 0.7790, HR@10: 1.0000, MRR: 0.7038
test [sampled], NDCG@5: 0.2234, HR@5: 0.2309, NDCG@10: 0.2650, HR@10: 0.3639, MRR: 0.2745
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s2024/sasrec_last.pth

In [17]:
!python src/train_sasrec.py \
  --run_name multitask_anchor_ml20_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7
epoch=1, loss=2.5159
epoch=2, loss=1.5425
epoch=3, loss=1.4187
epoch=4, loss=1.3537
epoch=5, loss=1.3111
valid [task], Top5Acc: 0.3653, Top10Acc: 0.7063, Acc: 0.0763, MacroF1: 0.1307, TimeMAE: 71307.8360, TimeRMSE: 288739.1460, TimeMedAE: 716.9146
valid [full], NDCG@5: 0.6091, HR@5: 0.7073, NDCG@10: 0.6951, HR@10: 0.9818, MRR: 0.6128
valid [sampled], NDCG@5: 0.5145, HR@5: 0.5171, NDCG@10: 0.5248, HR@10: 0.5495, MRR: 0.5310
test [task], Top5Acc: 0.3190, Top10Acc: 0.4255, Acc: 0.0480, MacroF1: 0.0334, TimeMAE: 12699.1679, TimeRMSE: 84246.7643, TimeMedAE: 2.5440
test [full], NDCG@5: 0.6475, HR@5: 0.7518, NDCG@10: 0.6850, HR@10: 0.8728, MRR: 0.6373
test [sampled], NDCG@5: 0.1062, HR@5: 0.1431, NDCG@10: 0.1614, HR@10: 0.3149, MRR: 0.1456
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=6, loss=1.2672
epoch=7, loss=1.2576
epoch=8, loss=1.2310
epoch=9, loss=1.2216
epoch=10, loss=1.2127
valid [task], Top5Acc: 0.4109, Top10Acc: 0.7304, Acc: 0.0885, MacroF1: 0.1349, TimeMAE: 73419.1760, TimeRMSE: 289236.0005, TimeMedAE: 692.8371
valid [full], NDCG@5: 0.6648, HR@5: 0.7841, NDCG@10: 0.7208, HR@10: 0.9555, MRR: 0.6535
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5654, NDCG@10: 0.5706, HR@10: 0.5873, MRR: 0.5788
test [task], Top5Acc: 0.3012, Top10Acc: 0.6158, Acc: 0.0368, MacroF1: 0.0299, TimeMAE: 11677.8220, TimeRMSE: 73295.1583, TimeMedAE: 3.6701
test [full], NDCG@5: 0.7417, HR@5: 0.9358, NDCG@10: 0.7618, HR@10: 0.9958, MRR: 0.6874
test [sampled], NDCG@5: 0.1361, HR@5: 0.1752, NDCG@10: 0.1967, HR@10: 0.3639, MRR: 0.1795
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=11, loss=1.2087
epoch=12, loss=1.1915
epoch=13, loss=1.1795
epoch=14, loss=1.1874
epoch=15, loss=1.1793
valid [task], Top5Acc: 0.4076, Top10Acc: 0.6454, Acc: 0.0876, MacroF1: 0.1347, TimeMAE: 71663.1257, TimeRMSE: 280623.5801, TimeMedAE: 644.0560
valid [full], NDCG@5: 0.6714, HR@5: 0.7923, NDCG@10: 0.7197, HR@10: 0.9410, MRR: 0.6570
valid [sampled], NDCG@5: 0.5622, HR@5: 0.5660, NDCG@10: 0.5717, HR@10: 0.5958, MRR: 0.5780
test [task], Top5Acc: 0.2720, Top10Acc: 0.6357, Acc: 0.0306, MacroF1: 0.0257, TimeMAE: 11906.5511, TimeRMSE: 76125.6430, TimeMedAE: 4.8360
test [full], NDCG@5: 0.7393, HR@5: 0.9107, NDCG@10: 0.7686, HR@10: 1.0000, MRR: 0.6943
test [sampled], NDCG@5: 0.1750, HR@5: 0.2122, NDCG@10: 0.2301, HR@10: 0.3836, MRR: 0.2154
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=1.1695
epoch=17, loss=1.1653
epoch=18, loss=1.1606
epoch=19, loss=1.1462
epoch=20, loss=1.1535
valid [task], Top5Acc: 0.3965, Top10Acc: 0.5789, Acc: 0.0683, MacroF1: 0.1063, TimeMAE: 71504.7083, TimeRMSE: 290511.2657, TimeMedAE: 766.1950
valid [full], NDCG@5: 0.6840, HR@5: 0.8368, NDCG@10: 0.7141, HR@10: 0.9354, MRR: 0.6512
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5591, NDCG@10: 0.5649, HR@10: 0.5888, MRR: 0.5714
test [task], Top5Acc: 0.0896, Top10Acc: 0.6238, Acc: 0.0331, MacroF1: 0.0268, TimeMAE: 12353.2316, TimeRMSE: 79724.4378, TimeMedAE: 3.6940
test [full], NDCG@5: 0.6763, HR@5: 0.9519, NDCG@10: 0.6923, HR@10: 1.0000, MRR: 0.5913
test [sampled], NDCG@5: 0.1511, HR@5: 0.1585, NDCG@10: 0.1770, HR@10: 0.2415, MRR: 0.1988
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.1585
epoch=22, loss=1.1426
epoch=23, loss=1.1529
epoch=24, loss=1.1501
epoch=25, loss=1.1549
valid [task], Top5Acc: 0.4009, Top10Acc: 0.5847, Acc: 0.0680, MacroF1: 0.1096, TimeMAE: 68525.2125, TimeRMSE: 278890.6865, TimeMedAE: 755.1452
valid [full], NDCG@5: 0.6906, HR@5: 0.8397, NDCG@10: 0.7214, HR@10: 0.9380, MRR: 0.6591
valid [sampled], NDCG@5: 0.5577, HR@5: 0.5622, NDCG@10: 0.5691, HR@10: 0.5983, MRR: 0.5745
test [task], Top5Acc: 0.3362, Top10Acc: 0.6247, Acc: 0.0325, MacroF1: 0.0296, TimeMAE: 11760.8898, TimeRMSE: 72910.6665, TimeMedAE: 6.8405
test [full], NDCG@5: 0.7221, HR@5: 0.9314, NDCG@10: 0.7454, HR@10: 0.9999, MRR: 0.6596
test [sampled], NDCG@5: 0.1508, HR@5: 0.1650, NDCG@10: 0.2002, HR@10: 0.3223, MRR: 0.2041
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=26, loss=1.1384
epoch=27, loss=1.1531
epoch=28, loss=1.1311
epoch=29, loss=1.1394
epoch=30, loss=1.1285
valid [task], Top5Acc: 0.4047, Top10Acc: 0.6103, Acc: 0.0678, MacroF1: 0.1004, TimeMAE: 71288.9622, TimeRMSE: 282330.9695, TimeMedAE: 778.4708
valid [full], NDCG@5: 0.7013, HR@5: 0.8683, NDCG@10: 0.7230, HR@10: 0.9385, MRR: 0.6603
valid [sampled], NDCG@5: 0.5551, HR@5: 0.5596, NDCG@10: 0.5654, HR@10: 0.5918, MRR: 0.5727
test [task], Top5Acc: 0.2258, Top10Acc: 0.5759, Acc: 0.0292, MacroF1: 0.0297, TimeMAE: 11356.1513, TimeRMSE: 74875.6814, TimeMedAE: 3.4310
test [full], NDCG@5: 0.6756, HR@5: 0.9221, NDCG@10: 0.6998, HR@10: 0.9999, MRR: 0.6014
test [sampled], NDCG@5: 0.1055, HR@5: 0.1318, NDCG@10: 0.1563, HR@10: 0.2914, MRR: 0.1530
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=31, loss=1.1422
epoch=32, loss=1.1331
epoch=33, loss=1.1301
epoch=34, loss=1.1214
epoch=35, loss=1.1246
valid [task], Top5Acc: 0.3887, Top10Acc: 0.6827, Acc: 0.0658, MacroF1: 0.0954, TimeMAE: 69082.7924, TimeRMSE: 276465.9253, TimeMedAE: 849.4615
valid [full], NDCG@5: 0.6986, HR@5: 0.8393, NDCG@10: 0.7292, HR@10: 0.9378, MRR: 0.6683
valid [sampled], NDCG@5: 0.5500, HR@5: 0.5535, NDCG@10: 0.5647, HR@10: 0.6000, MRR: 0.5703
test [task], Top5Acc: 0.2711, Top10Acc: 0.6232, Acc: 0.0316, MacroF1: 0.0281, TimeMAE: 13092.7691, TimeRMSE: 75316.3106, TimeMedAE: 7.0335
test [full], NDCG@5: 0.6942, HR@5: 0.9366, NDCG@10: 0.7143, HR@10: 0.9999, MRR: 0.6199
test [sampled], NDCG@5: 0.1055, HR@5: 0.1255, NDCG@10: 0.1515, HR@10: 0.2714, MRR: 0.1552
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=36, loss=1.1267
epoch=37, loss=1.1236
epoch=38, loss=1.1322
epoch=39, loss=1.1223
epoch=40, loss=1.1250
valid [task], Top5Acc: 0.3956, Top10Acc: 0.6849, Acc: 0.0626, MacroF1: 0.1048, TimeMAE: 70126.4573, TimeRMSE: 286281.9838, TimeMedAE: 797.3017
valid [full], NDCG@5: 0.7132, HR@5: 0.8688, NDCG@10: 0.7366, HR@10: 0.9450, MRR: 0.6747
valid [sampled], NDCG@5: 0.5539, HR@5: 0.5586, NDCG@10: 0.5700, HR@10: 0.6093, MRR: 0.5746
test [task], Top5Acc: 0.4689, Top10Acc: 0.6085, Acc: 0.0240, MacroF1: 0.0228, TimeMAE: 11651.5369, TimeRMSE: 71586.8908, TimeMedAE: 7.0360
test [full], NDCG@5: 0.6785, HR@5: 0.9270, NDCG@10: 0.7014, HR@10: 0.9999, MRR: 0.6010
test [sampled], NDCG@5: 0.0921, HR@5: 0.1101, NDCG@10: 0.1475, HR@10: 0.2855, MRR: 0.1465
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=41, loss=1.1288
epoch=42, loss=1.1221
epoch=43, loss=1.1070
epoch=44, loss=1.1186
epoch=45, loss=1.1100
valid [task], Top5Acc: 0.4020, Top10Acc: 0.6084, Acc: 0.0620, MacroF1: 0.0923, TimeMAE: 71386.6744, TimeRMSE: 287652.3131, TimeMedAE: 781.0267
valid [full], NDCG@5: 0.7189, HR@5: 0.8761, NDCG@10: 0.7395, HR@10: 0.9445, MRR: 0.6786
valid [sampled], NDCG@5: 0.5574, HR@5: 0.5619, NDCG@10: 0.5728, HR@10: 0.6103, MRR: 0.5780
test [task], Top5Acc: 0.4657, Top10Acc: 0.5602, Acc: 0.0231, MacroF1: 0.0216, TimeMAE: 11294.5674, TimeRMSE: 66736.0081, TimeMedAE: 6.8710
test [full], NDCG@5: 0.7308, HR@5: 0.9391, NDCG@10: 0.7496, HR@10: 0.9999, MRR: 0.6657
test [sampled], NDCG@5: 0.2526, HR@5: 0.2969, NDCG@10: 0.3149, HR@10: 0.4913, MRR: 0.2877
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_best.pth
epoch=46, loss=1.1238
epoch=47, loss=1.1104
epoch=48, loss=1.1005
epoch=49, loss=1.1107
epoch=50, loss=1.1147
valid [task], Top5Acc: 0.4010, Top10Acc: 0.6011, Acc: 0.0640, MacroF1: 0.0926, TimeMAE: 72491.4181, TimeRMSE: 282145.7623, TimeMedAE: 721.2331
valid [full], NDCG@5: 0.7112, HR@5: 0.8669, NDCG@10: 0.7339, HR@10: 0.9411, MRR: 0.6729
valid [sampled], NDCG@5: 0.5573, HR@5: 0.5619, NDCG@10: 0.5711, HR@10: 0.6057, MRR: 0.5767
test [task], Top5Acc: 0.4463, Top10Acc: 0.6192, Acc: 0.0280, MacroF1: 0.0256, TimeMAE: 11771.5981, TimeRMSE: 66527.2053, TimeMedAE: 6.6299
test [full], NDCG@5: 0.7396, HR@5: 0.9377, NDCG@10: 0.7593, HR@10: 0.9999, MRR: 0.6786
test [sampled], NDCG@5: 0.1440, HR@5: 0.1650, NDCG@10: 0.1955, HR@10: 0.3273, MRR: 0.1958
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_anchor_ml20_s7/sasrec_last.pth

In [18]:
!python src/train_sasrec.py \
  --run_name multitask_refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42
epoch=1, loss=2.8505
epoch=2, loss=1.7178
epoch=3, loss=1.5850
epoch=4, loss=1.4952
epoch=5, loss=1.4479
valid [task], Top5Acc: 0.3369, Top10Acc: 0.7661, Acc: 0.0630, MacroF1: 0.0964, TimeMAE: 68718.9606, TimeRMSE: 276894.8275, TimeMedAE: 685.3123
valid [full], NDCG@5: 0.5947, HR@5: 0.7072, NDCG@10: 0.6826, HR@10: 0.9763, MRR: 0.5979
valid [sampled], NDCG@5: 0.5073, HR@5: 0.5086, NDCG@10: 0.5090, HR@10: 0.5139, MRR: 0.5224
test [task], Top5Acc: 0.0402, Top10Acc: 0.4269, Acc: 0.0250, MacroF1: 0.0223, TimeMAE: 11325.0808, TimeRMSE: 81139.4116, TimeMedAE: 3.4103
test [full], NDCG@5: 0.4271, HR@5: 0.5046, NDCG@10: 0.5770, HR@10: 0.9536, MRR: 0.4722
test [sampled], NDCG@5: 0.1455, HR@5: 0.1458, NDCG@10: 0.1507, HR@10: 0.1629, MRR: 0.1761
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=1.4108
epoch=7, loss=1.3745
epoch=8, loss=1.3583
epoch=9, loss=1.3453
epoch=10, loss=1.3211
valid [task], Top5Acc: 0.4295, Top10Acc: 0.7673, Acc: 0.0661, MacroF1: 0.1176, TimeMAE: 70429.4472, TimeRMSE: 281189.0658, TimeMedAE: 718.8368
valid [full], NDCG@5: 0.6576, HR@5: 0.7519, NDCG@10: 0.7213, HR@10: 0.9584, MRR: 0.6556
valid [sampled], NDCG@5: 0.5809, HR@5: 0.5821, NDCG@10: 0.5842, HR@10: 0.5925, MRR: 0.5936
test [task], Top5Acc: 0.2867, Top10Acc: 0.4294, Acc: 0.0290, MacroF1: 0.0260, TimeMAE: 12705.5297, TimeRMSE: 81744.4256, TimeMedAE: 6.0490
test [full], NDCG@5: 0.5535, HR@5: 0.6879, NDCG@10: 0.6547, HR@10: 1.0000, MRR: 0.5487
test [sampled], NDCG@5: 0.1328, HR@5: 0.1360, NDCG@10: 0.1594, HR@10: 0.2218, MRR: 0.1774
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=1.3132
epoch=12, loss=1.3047
epoch=13, loss=1.2940
epoch=14, loss=1.2959
epoch=15, loss=1.2792
valid [task], Top5Acc: 0.4508, Top10Acc: 0.7044, Acc: 0.0623, MacroF1: 0.0958, TimeMAE: 73614.5586, TimeRMSE: 282302.0449, TimeMedAE: 709.8786
valid [full], NDCG@5: 0.6654, HR@5: 0.7517, NDCG@10: 0.7323, HR@10: 0.9686, MRR: 0.6667
valid [sampled], NDCG@5: 0.6026, HR@5: 0.6029, NDCG@10: 0.6036, HR@10: 0.6062, MRR: 0.6135
test [task], Top5Acc: 0.3258, Top10Acc: 0.5196, Acc: 0.0246, MacroF1: 0.0196, TimeMAE: 11674.6627, TimeRMSE: 74033.6241, TimeMedAE: 51.9407
test [full], NDCG@5: 0.6565, HR@5: 0.9375, NDCG@10: 0.6763, HR@10: 1.0000, MRR: 0.5693
test [sampled], NDCG@5: 0.0840, HR@5: 0.0862, NDCG@10: 0.1164, HR@10: 0.1906, MRR: 0.1386
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=1.2735
epoch=17, loss=1.2623
epoch=18, loss=1.2689
epoch=19, loss=1.2591
epoch=20, loss=1.2524
valid [task], Top5Acc: 0.4482, Top10Acc: 0.7034, Acc: 0.0663, MacroF1: 0.1059, TimeMAE: 74968.7356, TimeRMSE: 284365.8009, TimeMedAE: 824.8350
valid [full], NDCG@5: 0.6644, HR@5: 0.7493, NDCG@10: 0.7329, HR@10: 0.9691, MRR: 0.6670
valid [sampled], NDCG@5: 0.6005, HR@5: 0.6009, NDCG@10: 0.6022, HR@10: 0.6064, MRR: 0.6119
test [task], Top5Acc: 0.2929, Top10Acc: 0.5121, Acc: 0.0300, MacroF1: 0.0238, TimeMAE: 12011.0498, TimeRMSE: 71423.2159, TimeMedAE: 147.6289
test [full], NDCG@5: 0.6529, HR@5: 0.9394, NDCG@10: 0.6724, HR@10: 1.0000, MRR: 0.5640
test [sampled], NDCG@5: 0.0687, HR@5: 0.0724, NDCG@10: 0.1018, HR@10: 0.1788, MRR: 0.1237
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/sasrec_best.pth
epoch=21, loss=1.2528
epoch=22, loss=1.2547
epoch=23, loss=1.2409
epoch=24, loss=1.2363
epoch=25, loss=1.2352
valid [task], Top5Acc: 0.4523, Top10Acc: 0.6920, Acc: 0.0676, MacroF1: 0.0596, TimeMAE: 75407.7340, TimeRMSE: 294336.6762, TimeMedAE: 599.8074
valid [full], NDCG@5: 0.6594, HR@5: 0.7370, NDCG@10: 0.7228, HR@10: 0.9457, MRR: 0.6624
valid [sampled], NDCG@5: 0.5873, HR@5: 0.5875, NDCG@10: 0.5912, HR@10: 0.6002, MRR: 0.6002
test [task], Top5Acc: 0.3124, Top10Acc: 0.5193, Acc: 0.0278, MacroF1: 0.0194, TimeMAE: 11892.2832, TimeRMSE: 74800.6616, TimeMedAE: 38.1063
test [full], NDCG@5: 0.6595, HR@5: 0.9443, NDCG@10: 0.6767, HR@10: 1.0000, MRR: 0.5701
test [sampled], NDCG@5: 0.0787, HR@5: 0.0832, NDCG@10: 0.1124, HR@10: 0.1916, MRR: 0.1328
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.2195
epoch=27, loss=1.2281
epoch=28, loss=1.2234
epoch=29, loss=1.2231
epoch=30, loss=1.2234
valid [task], Top5Acc: 0.4243, Top10Acc: 0.5924, Acc: 0.0638, MacroF1: 0.0522, TimeMAE: 71779.7566, TimeRMSE: 285084.2215, TimeMedAE: 766.5635
valid [full], NDCG@5: 0.6394, HR@5: 0.6972, NDCG@10: 0.7189, HR@10: 0.9485, MRR: 0.6559
valid [sampled], NDCG@5: 0.5787, HR@5: 0.5813, NDCG@10: 0.5859, HR@10: 0.6041, MRR: 0.5915
test [task], Top5Acc: 0.2929, Top10Acc: 0.5224, Acc: 0.0269, MacroF1: 0.0190, TimeMAE: 11929.5130, TimeRMSE: 78815.6891, TimeMedAE: 144.9531
test [full], NDCG@5: 0.6695, HR@5: 0.9467, NDCG@10: 0.6873, HR@10: 0.9999, MRR: 0.5834
test [sampled], NDCG@5: 0.0667, HR@5: 0.0779, NDCG@10: 0.1030, HR@10: 0.1937, MRR: 0.1221
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.2109
epoch=32, loss=1.2155
epoch=33, loss=1.2179
epoch=34, loss=1.2108
epoch=35, loss=1.2105
valid [task], Top5Acc: 0.4343, Top10Acc: 0.5954, Acc: 0.0614, MacroF1: 0.0568, TimeMAE: 69818.1835, TimeRMSE: 280684.3997, TimeMedAE: 660.2943
valid [full], NDCG@5: 0.6631, HR@5: 0.7431, NDCG@10: 0.7283, HR@10: 0.9552, MRR: 0.6659
valid [sampled], NDCG@5: 0.5921, HR@5: 0.5943, NDCG@10: 0.5974, HR@10: 0.6108, MRR: 0.6047
test [task], Top5Acc: 0.3085, Top10Acc: 0.5301, Acc: 0.0226, MacroF1: 0.0158, TimeMAE: 11701.6552, TimeRMSE: 72545.8232, TimeMedAE: 90.9253
test [full], NDCG@5: 0.6629, HR@5: 0.9365, NDCG@10: 0.6840, HR@10: 1.0000, MRR: 0.5788
test [sampled], NDCG@5: 0.0773, HR@5: 0.0820, NDCG@10: 0.1139, HR@10: 0.2001, MRR: 0.1348
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.2093
epoch=37, loss=1.2016
epoch=38, loss=1.1946
epoch=39, loss=1.2143
epoch=40, loss=1.1990
valid [task], Top5Acc: 0.3893, Top10Acc: 0.6727, Acc: 0.0590, MacroF1: 0.0821, TimeMAE: 68658.6663, TimeRMSE: 271472.4399, TimeMedAE: 568.4091
valid [full], NDCG@5: 0.6396, HR@5: 0.7295, NDCG@10: 0.7103, HR@10: 0.9543, MRR: 0.6420
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5601, NDCG@10: 0.5662, HR@10: 0.5913, MRR: 0.5709
test [task], Top5Acc: 0.2988, Top10Acc: 0.5115, Acc: 0.0225, MacroF1: 0.0184, TimeMAE: 11131.6924, TimeRMSE: 66664.4962, TimeMedAE: 76.9151
test [full], NDCG@5: 0.7140, HR@5: 0.8857, NDCG@10: 0.7537, HR@10: 1.0000, MRR: 0.6739
test [sampled], NDCG@5: 0.0743, HR@5: 0.1151, NDCG@10: 0.1395, HR@10: 0.3196, MRR: 0.1234
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.2015
epoch=42, loss=1.2048
epoch=43, loss=1.2038
epoch=44, loss=1.2054
epoch=45, loss=1.2092
valid [task], Top5Acc: 0.4160, Top10Acc: 0.5749, Acc: 0.0645, MacroF1: 0.0501, TimeMAE: 75243.2986, TimeRMSE: 287074.6697, TimeMedAE: 1281.6860
valid [full], NDCG@5: 0.6477, HR@5: 0.7507, NDCG@10: 0.7081, HR@10: 0.9391, MRR: 0.6434
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5494, NDCG@10: 0.5544, HR@10: 0.5745, MRR: 0.5621
test [task], Top5Acc: 0.3177, Top10Acc: 0.5182, Acc: 0.0254, MacroF1: 0.0169, TimeMAE: 11795.5178, TimeRMSE: 69962.4670, TimeMedAE: 101.4357
test [full], NDCG@5: 0.7418, HR@5: 0.9040, NDCG@10: 0.7735, HR@10: 1.0000, MRR: 0.7002
test [sampled], NDCG@5: 0.1048, HR@5: 0.1436, NDCG@10: 0.1665, HR@10: 0.3369, MRR: 0.1518
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1938
epoch=47, loss=1.1952
epoch=48, loss=1.1883
epoch=49, loss=1.1969
epoch=50, loss=1.1860
valid [task], Top5Acc: 0.3924, Top10Acc: 0.5697, Acc: 0.0581, MacroF1: 0.0455, TimeMAE: 68322.8765, TimeRMSE: 280865.2338, TimeMedAE: 1001.3672
valid [full], NDCG@5: 0.6134, HR@5: 0.7160, NDCG@10: 0.6846, HR@10: 0.9394, MRR: 0.6125
valid [sampled], NDCG@5: 0.5089, HR@5: 0.5129, NDCG@10: 0.5181, HR@10: 0.5414, MRR: 0.5251
test [task], Top5Acc: 0.3197, Top10Acc: 0.6182, Acc: 0.0229, MacroF1: 0.0158, TimeMAE: 11676.3736, TimeRMSE: 69139.5658, TimeMedAE: 70.1119
test [full], NDCG@5: 0.7782, HR@5: 0.9176, NDCG@10: 0.8069, HR@10: 0.9999, MRR: 0.7447
test [sampled], NDCG@5: 0.1816, HR@5: 0.2222, NDCG@10: 0.2441, HR@10: 0.4178, MRR: 0.2244
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s42/sasrec_last.pth

In [19]:
!python src/train_sasrec.py \
  --run_name multitask_refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024
epoch=1, loss=3.1766
epoch=2, loss=1.7923
epoch=3, loss=1.5831
epoch=4, loss=1.4831
epoch=5, loss=1.4271
valid [task], Top5Acc: 0.3530, Top10Acc: 0.6978, Acc: 0.0731, MacroF1: 0.1150, TimeMAE: 72415.8090, TimeRMSE: 292456.3123, TimeMedAE: 1158.1624
valid [full], NDCG@5: 0.6044, HR@5: 0.7012, NDCG@10: 0.6672, HR@10: 0.9041, MRR: 0.6062
valid [sampled], NDCG@5: 0.5189, HR@5: 0.5195, NDCG@10: 0.5233, HR@10: 0.5332, MRR: 0.5340
test [task], Top5Acc: 0.2852, Top10Acc: 0.5307, Acc: 0.0203, MacroF1: 0.0191, TimeMAE: 12778.4592, TimeRMSE: 83517.4034, TimeMedAE: 50.6332
test [full], NDCG@5: 0.5992, HR@5: 0.7997, NDCG@10: 0.6596, HR@10: 0.9784, MRR: 0.5598
test [sampled], NDCG@5: 0.1093, HR@5: 0.1135, NDCG@10: 0.1397, HR@10: 0.2119, MRR: 0.1589
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=1.3887
epoch=7, loss=1.3629
epoch=8, loss=1.3504
epoch=9, loss=1.3277
epoch=10, loss=1.3241
valid [task], Top5Acc: 0.4335, Top10Acc: 0.7051, Acc: 0.0628, MacroF1: 0.1019, TimeMAE: 68879.3133, TimeRMSE: 273841.4755, TimeMedAE: 2263.6109
valid [full], NDCG@5: 0.6669, HR@5: 0.7456, NDCG@10: 0.7306, HR@10: 0.9520, MRR: 0.6705
valid [sampled], NDCG@5: 0.6017, HR@5: 0.6026, NDCG@10: 0.6047, HR@10: 0.6120, MRR: 0.6135
test [task], Top5Acc: 0.2987, Top10Acc: 0.5373, Acc: 0.0179, MacroF1: 0.0180, TimeMAE: 12522.2794, TimeRMSE: 74498.3165, TimeMedAE: 43.6719
test [full], NDCG@5: 0.6164, HR@5: 0.8721, NDCG@10: 0.6567, HR@10: 0.9986, MRR: 0.5462
test [sampled], NDCG@5: 0.0698, HR@5: 0.0734, NDCG@10: 0.1002, HR@10: 0.1713, MRR: 0.1228
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=11, loss=1.3189
epoch=12, loss=1.3112
epoch=13, loss=1.2948
epoch=14, loss=1.2834
epoch=15, loss=1.2860
valid [task], Top5Acc: 0.4525, Top10Acc: 0.6922, Acc: 0.0589, MacroF1: 0.0799, TimeMAE: 69805.6615, TimeRMSE: 283877.4711, TimeMedAE: 3100.8958
valid [full], NDCG@5: 0.6692, HR@5: 0.7459, NDCG@10: 0.7349, HR@10: 0.9596, MRR: 0.6742
valid [sampled], NDCG@5: 0.6154, HR@5: 0.6156, NDCG@10: 0.6159, HR@10: 0.6174, MRR: 0.6253
test [task], Top5Acc: 0.3258, Top10Acc: 0.5411, Acc: 0.0184, MacroF1: 0.0164, TimeMAE: 13194.9651, TimeRMSE: 82865.2986, TimeMedAE: 89.4141
test [full], NDCG@5: 0.7050, HR@5: 0.8715, NDCG@10: 0.7472, HR@10: 1.0000, MRR: 0.6670
test [sampled], NDCG@5: 0.1094, HR@5: 0.1502, NDCG@10: 0.1662, HR@10: 0.3283, MRR: 0.1513
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/sasrec_best.pth
epoch=16, loss=1.2799
epoch=17, loss=1.2688
epoch=18, loss=1.2639
epoch=19, loss=1.2720
epoch=20, loss=1.2575
valid [task], Top5Acc: 0.4350, Top10Acc: 0.6727, Acc: 0.0592, MacroF1: 0.0932, TimeMAE: 72258.9190, TimeRMSE: 293305.9512, TimeMedAE: 1996.3508
valid [full], NDCG@5: 0.6687, HR@5: 0.7365, NDCG@10: 0.7332, HR@10: 0.9464, MRR: 0.6758
valid [sampled], NDCG@5: 0.6113, HR@5: 0.6118, NDCG@10: 0.6132, HR@10: 0.6180, MRR: 0.6224
test [task], Top5Acc: 0.3433, Top10Acc: 0.5810, Acc: 0.0178, MacroF1: 0.0156, TimeMAE: 12876.7158, TimeRMSE: 80283.1721, TimeMedAE: 211.8244
test [full], NDCG@5: 0.6979, HR@5: 0.8834, NDCG@10: 0.7369, HR@10: 1.0000, MRR: 0.6523
test [sampled], NDCG@5: 0.1310, HR@5: 0.1719, NDCG@10: 0.1906, HR@10: 0.3575, MRR: 0.1719
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.2451
epoch=22, loss=1.2429
epoch=23, loss=1.2327
epoch=24, loss=1.2382
epoch=25, loss=1.2361
valid [task], Top5Acc: 0.4569, Top10Acc: 0.6659, Acc: 0.0661, MacroF1: 0.0768, TimeMAE: 72621.3228, TimeRMSE: 284958.6425, TimeMedAE: 672.8261
valid [full], NDCG@5: 0.6698, HR@5: 0.7447, NDCG@10: 0.7329, HR@10: 0.9402, MRR: 0.6763
valid [sampled], NDCG@5: 0.6074, HR@5: 0.6081, NDCG@10: 0.6105, HR@10: 0.6180, MRR: 0.6191
test [task], Top5Acc: 0.3883, Top10Acc: 0.5880, Acc: 0.0317, MacroF1: 0.0246, TimeMAE: 13650.3055, TimeRMSE: 79454.1641, TimeMedAE: 60.1133
test [full], NDCG@5: 0.6981, HR@5: 0.9004, NDCG@10: 0.7325, HR@10: 1.0000, MRR: 0.6460
test [sampled], NDCG@5: 0.1217, HR@5: 0.1653, NDCG@10: 0.1821, HR@10: 0.3534, MRR: 0.1623
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.2333
epoch=27, loss=1.2250
epoch=28, loss=1.2322
epoch=29, loss=1.2308
epoch=30, loss=1.2136
valid [task], Top5Acc: 0.4330, Top10Acc: 0.5761, Acc: 0.0660, MacroF1: 0.0990, TimeMAE: 74308.7746, TimeRMSE: 292066.1854, TimeMedAE: 1595.3323
valid [full], NDCG@5: 0.6605, HR@5: 0.7506, NDCG@10: 0.7231, HR@10: 0.9419, MRR: 0.6618
valid [sampled], NDCG@5: 0.5779, HR@5: 0.5823, NDCG@10: 0.5876, HR@10: 0.6128, MRR: 0.5916
test [task], Top5Acc: 0.4195, Top10Acc: 0.5918, Acc: 0.0529, MacroF1: 0.0350, TimeMAE: 12656.9344, TimeRMSE: 76653.1666, TimeMedAE: 147.8988
test [full], NDCG@5: 0.7341, HR@5: 0.8855, NDCG@10: 0.7740, HR@10: 1.0000, MRR: 0.7005
test [sampled], NDCG@5: 0.1333, HR@5: 0.1891, NDCG@10: 0.2136, HR@10: 0.4380, MRR: 0.1750
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.2288
epoch=32, loss=1.2121
epoch=33, loss=1.2257
epoch=34, loss=1.2147
epoch=35, loss=1.2238
valid [task], Top5Acc: 0.4200, Top10Acc: 0.5788, Acc: 0.0644, MacroF1: 0.0918, TimeMAE: 70747.5653, TimeRMSE: 288098.1693, TimeMedAE: 2087.6302
valid [full], NDCG@5: 0.6544, HR@5: 0.7474, NDCG@10: 0.7097, HR@10: 0.9169, MRR: 0.6542
valid [sampled], NDCG@5: 0.5745, HR@5: 0.5784, NDCG@10: 0.5830, HR@10: 0.6049, MRR: 0.5874
test [task], Top5Acc: 0.5343, Top10Acc: 0.6008, Acc: 0.0461, MacroF1: 0.0333, TimeMAE: 13304.7425, TimeRMSE: 83226.1162, TimeMedAE: 123.1368
test [full], NDCG@5: 0.7967, HR@5: 0.8968, NDCG@10: 0.8325, HR@10: 1.0000, MRR: 0.7791
test [sampled], NDCG@5: 0.2186, HR@5: 0.2718, NDCG@10: 0.2903, HR@10: 0.4937, MRR: 0.2543
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.2216
epoch=37, loss=1.2149
epoch=38, loss=1.2160
epoch=39, loss=1.2092
epoch=40, loss=1.2064
valid [task], Top5Acc: 0.4036, Top10Acc: 0.5712, Acc: 0.0608, MacroF1: 0.0750, TimeMAE: 76587.1478, TimeRMSE: 297280.4496, TimeMedAE: 2705.7512
valid [full], NDCG@5: 0.6554, HR@5: 0.7873, NDCG@10: 0.7051, HR@10: 0.9412, MRR: 0.6377
valid [sampled], NDCG@5: 0.5351, HR@5: 0.5405, NDCG@10: 0.5459, HR@10: 0.5743, MRR: 0.5506
test [task], Top5Acc: 0.4874, Top10Acc: 0.5925, Acc: 0.0226, MacroF1: 0.0177, TimeMAE: 12994.2543, TimeRMSE: 74511.8954, TimeMedAE: 100.7825
test [full], NDCG@5: 0.8282, HR@5: 0.9579, NDCG@10: 0.8427, HR@10: 0.9999, MRR: 0.7922
test [sampled], NDCG@5: 0.2307, HR@5: 0.2832, NDCG@10: 0.3001, HR@10: 0.4986, MRR: 0.2676
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.2037
epoch=42, loss=1.2068
epoch=43, loss=1.2111
epoch=44, loss=1.1995
epoch=45, loss=1.1992
valid [task], Top5Acc: 0.3993, Top10Acc: 0.5813, Acc: 0.0672, MacroF1: 0.0810, TimeMAE: 74518.8964, TimeRMSE: 286355.5526, TimeMedAE: 808.1028
valid [full], NDCG@5: 0.6677, HR@5: 0.7899, NDCG@10: 0.7161, HR@10: 0.9417, MRR: 0.6522
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5673, NDCG@10: 0.5727, HR@10: 0.6017, MRR: 0.5765
test [task], Top5Acc: 0.4711, Top10Acc: 0.5496, Acc: 0.0296, MacroF1: 0.0227, TimeMAE: 13053.8584, TimeRMSE: 73729.4047, TimeMedAE: 126.3617
test [full], NDCG@5: 0.8197, HR@5: 0.9538, NDCG@10: 0.8355, HR@10: 1.0000, MRR: 0.7831
test [sampled], NDCG@5: 0.2509, HR@5: 0.2915, NDCG@10: 0.3108, HR@10: 0.4774, MRR: 0.2886
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.1976
epoch=47, loss=1.1947
epoch=48, loss=1.1963
epoch=49, loss=1.1909
epoch=50, loss=1.1947
valid [task], Top5Acc: 0.3967, Top10Acc: 0.5744, Acc: 0.0639, MacroF1: 0.0741, TimeMAE: 72243.6130, TimeRMSE: 288446.3456, TimeMedAE: 3700.5254
valid [full], NDCG@5: 0.6002, HR@5: 0.7267, NDCG@10: 0.6622, HR@10: 0.9163, MRR: 0.5912
valid [sampled], NDCG@5: 0.4735, HR@5: 0.4763, NDCG@10: 0.4800, HR@10: 0.4968, MRR: 0.4904
test [task], Top5Acc: 0.4720, Top10Acc: 0.6547, Acc: 0.0264, MacroF1: 0.0235, TimeMAE: 13254.6753, TimeRMSE: 72473.3553, TimeMedAE: 141.0223
test [full], NDCG@5: 0.8114, HR@5: 0.9243, NDCG@10: 0.8367, HR@10: 1.0000, MRR: 0.7849
test [sampled], NDCG@5: 0.2556, HR@5: 0.3016, NDCG@10: 0.3192, HR@10: 0.4995, MRR: 0.2913
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s2024/sasrec_last.pth

In [20]:
!python src/train_sasrec.py \
  --run_name multitask_refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_BASELINE_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7
epoch=1, loss=2.8340
epoch=2, loss=1.7338
epoch=3, loss=1.5919
epoch=4, loss=1.5063
epoch=5, loss=1.4528
valid [task], Top5Acc: 0.3922, Top10Acc: 0.7020, Acc: 0.0631, MacroF1: 0.1005, TimeMAE: 72185.0271, TimeRMSE: 289690.4072, TimeMedAE: 1009.0027
valid [full], NDCG@5: 0.4991, HR@5: 0.6484, NDCG@10: 0.5953, HR@10: 0.9491, MRR: 0.4925
valid [sampled], NDCG@5: 0.3377, HR@5: 0.3638, NDCG@10: 0.3751, HR@10: 0.4805, MRR: 0.3601
test [task], Top5Acc: 0.3540, Top10Acc: 0.6121, Acc: 0.0312, MacroF1: 0.0253, TimeMAE: 14388.2277, TimeRMSE: 85508.5843, TimeMedAE: 3.4402
test [full], NDCG@5: 0.6578, HR@5: 0.7965, NDCG@10: 0.7232, HR@10: 1.0000, MRR: 0.6373
test [sampled], NDCG@5: 0.2280, HR@5: 0.2324, NDCG@10: 0.2527, HR@10: 0.3118, MRR: 0.2699
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=1.4039
epoch=7, loss=1.3782
epoch=8, loss=1.3559
epoch=9, loss=1.3423
epoch=10, loss=1.3284
valid [task], Top5Acc: 0.4159, Top10Acc: 0.7753, Acc: 0.0692, MacroF1: 0.0825, TimeMAE: 70370.0577, TimeRMSE: 289225.5786, TimeMedAE: 781.6792
valid [full], NDCG@5: 0.6677, HR@5: 0.7693, NDCG@10: 0.7278, HR@10: 0.9698, MRR: 0.6595
valid [sampled], NDCG@5: 0.5750, HR@5: 0.5768, NDCG@10: 0.5807, HR@10: 0.5947, MRR: 0.5893
test [task], Top5Acc: 0.3170, Top10Acc: 0.4520, Acc: 0.0314, MacroF1: 0.0252, TimeMAE: 12639.6634, TimeRMSE: 81506.4579, TimeMedAE: 7.8317
test [full], NDCG@5: 0.5805, HR@5: 0.7700, NDCG@10: 0.6538, HR@10: 1.0000, MRR: 0.5460
test [sampled], NDCG@5: 0.1010, HR@5: 0.1051, NDCG@10: 0.1302, HR@10: 0.1995, MRR: 0.1483
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=1.3185
epoch=12, loss=1.3059
epoch=13, loss=1.2900
epoch=14, loss=1.2844
epoch=15, loss=1.2806
valid [task], Top5Acc: 0.4492, Top10Acc: 0.7691, Acc: 0.0646, MacroF1: 0.0943, TimeMAE: 72160.3639, TimeRMSE: 279006.6489, TimeMedAE: 773.9543
valid [full], NDCG@5: 0.6546, HR@5: 0.7148, NDCG@10: 0.7313, HR@10: 0.9560, MRR: 0.6694
valid [sampled], NDCG@5: 0.5978, HR@5: 0.5982, NDCG@10: 0.6016, HR@10: 0.6103, MRR: 0.6103
test [task], Top5Acc: 0.3305, Top10Acc: 0.6206, Acc: 0.0226, MacroF1: 0.0205, TimeMAE: 12943.1533, TimeRMSE: 79617.7682, TimeMedAE: 17.8949
test [full], NDCG@5: 0.6547, HR@5: 0.8513, NDCG@10: 0.7036, HR@10: 1.0000, MRR: 0.6086
test [sampled], NDCG@5: 0.1694, HR@5: 0.1721, NDCG@10: 0.1966, HR@10: 0.2595, MRR: 0.2174
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=1.2669
epoch=17, loss=1.2693
epoch=18, loss=1.2533
epoch=19, loss=1.2467
epoch=20, loss=1.2508
valid [task], Top5Acc: 0.4508, Top10Acc: 0.7478, Acc: 0.0607, MacroF1: 0.0880, TimeMAE: 73453.8503, TimeRMSE: 291988.6844, TimeMedAE: 1125.6630
valid [full], NDCG@5: 0.6538, HR@5: 0.7079, NDCG@10: 0.7278, HR@10: 0.9392, MRR: 0.6710
valid [sampled], NDCG@5: 0.6042, HR@5: 0.6052, NDCG@10: 0.6067, HR@10: 0.6133, MRR: 0.6154
test [task], Top5Acc: 0.3201, Top10Acc: 0.6216, Acc: 0.0202, MacroF1: 0.0165, TimeMAE: 12560.3306, TimeRMSE: 81789.5679, TimeMedAE: 16.2639
test [full], NDCG@5: 0.7356, HR@5: 0.8704, NDCG@10: 0.7789, HR@10: 0.9999, MRR: 0.7091
test [sampled], NDCG@5: 0.2055, HR@5: 0.2443, NDCG@10: 0.2575, HR@10: 0.4066, MRR: 0.2421
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.2484
epoch=22, loss=1.2407
epoch=23, loss=1.2474
epoch=24, loss=1.2331
epoch=25, loss=1.2373
valid [task], Top5Acc: 0.4291, Top10Acc: 0.6076, Acc: 0.0613, MacroF1: 0.0996, TimeMAE: 69060.1613, TimeRMSE: 277073.3440, TimeMedAE: 1419.9845
valid [full], NDCG@5: 0.6530, HR@5: 0.7319, NDCG@10: 0.7226, HR@10: 0.9482, MRR: 0.6600
valid [sampled], NDCG@5: 0.5841, HR@5: 0.5858, NDCG@10: 0.5887, HR@10: 0.6003, MRR: 0.5968
test [task], Top5Acc: 0.3941, Top10Acc: 0.6212, Acc: 0.0249, MacroF1: 0.0211, TimeMAE: 12803.6775, TimeRMSE: 75122.1169, TimeMedAE: 49.8499
test [full], NDCG@5: 0.7873, HR@5: 0.9086, NDCG@10: 0.8185, HR@10: 0.9999, MRR: 0.7603
test [sampled], NDCG@5: 0.2212, HR@5: 0.2583, NDCG@10: 0.2820, HR@10: 0.4485, MRR: 0.2619
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.2291
epoch=27, loss=1.2388
epoch=28, loss=1.2152
epoch=29, loss=1.2224
epoch=30, loss=1.2163
valid [task], Top5Acc: 0.4281, Top10Acc: 0.6367, Acc: 0.0615, MacroF1: 0.1020, TimeMAE: 71853.6294, TimeRMSE: 282390.3076, TimeMedAE: 1367.6422
valid [full], NDCG@5: 0.6606, HR@5: 0.7541, NDCG@10: 0.7204, HR@10: 0.9385, MRR: 0.6599
valid [sampled], NDCG@5: 0.5761, HR@5: 0.5789, NDCG@10: 0.5832, HR@10: 0.6014, MRR: 0.5900
test [task], Top5Acc: 0.3848, Top10Acc: 0.6228, Acc: 0.0203, MacroF1: 0.0183, TimeMAE: 11960.8779, TimeRMSE: 77298.8981, TimeMedAE: 17.8381
test [full], NDCG@5: 0.6819, HR@5: 0.8910, NDCG@10: 0.7194, HR@10: 0.9999, MRR: 0.6256
test [sampled], NDCG@5: 0.1775, HR@5: 0.1832, NDCG@10: 0.2169, HR@10: 0.3098, MRR: 0.2283
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.2262
epoch=32, loss=1.2261
epoch=33, loss=1.2095
epoch=34, loss=1.2115
epoch=35, loss=1.2111
valid [task], Top5Acc: 0.4158, Top10Acc: 0.6268, Acc: 0.0629, MacroF1: 0.0922, TimeMAE: 70077.5028, TimeRMSE: 278676.4076, TimeMedAE: 3025.6165
valid [full], NDCG@5: 0.6783, HR@5: 0.7999, NDCG@10: 0.7214, HR@10: 0.9360, MRR: 0.6616
valid [sampled], NDCG@5: 0.5730, HR@5: 0.5752, NDCG@10: 0.5802, HR@10: 0.5977, MRR: 0.5879
test [task], Top5Acc: 0.4420, Top10Acc: 0.6238, Acc: 0.0285, MacroF1: 0.0215, TimeMAE: 13213.9480, TimeRMSE: 77187.2497, TimeMedAE: 24.4470
test [full], NDCG@5: 0.8014, HR@5: 0.9301, NDCG@10: 0.8246, HR@10: 0.9999, MRR: 0.7673
test [sampled], NDCG@5: 0.2176, HR@5: 0.2640, NDCG@10: 0.2861, HR@10: 0.4780, MRR: 0.2565
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.2066
epoch=37, loss=1.2016
epoch=38, loss=1.2123
epoch=39, loss=1.2077
epoch=40, loss=1.2084
valid [task], Top5Acc: 0.4286, Top10Acc: 0.5711, Acc: 0.0692, MacroF1: 0.1123, TimeMAE: 74644.9775, TimeRMSE: 282034.6662, TimeMedAE: 2889.9374
valid [full], NDCG@5: 0.6752, HR@5: 0.7877, NDCG@10: 0.7228, HR@10: 0.9361, MRR: 0.6637
valid [sampled], NDCG@5: 0.5790, HR@5: 0.5806, NDCG@10: 0.5853, HR@10: 0.6002, MRR: 0.5935
test [task], Top5Acc: 0.4067, Top10Acc: 0.5910, Acc: 0.0305, MacroF1: 0.0246, TimeMAE: 13209.3097, TimeRMSE: 68312.6175, TimeMedAE: 24.6439
test [full], NDCG@5: 0.8228, HR@5: 0.9144, NDCG@10: 0.8514, HR@10: 0.9999, MRR: 0.8041
test [sampled], NDCG@5: 0.1904, HR@5: 0.2384, NDCG@10: 0.2671, HR@10: 0.4786, MRR: 0.2339
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.2127
epoch=42, loss=1.2025
epoch=43, loss=1.1930
epoch=44, loss=1.1971
epoch=45, loss=1.1872
valid [task], Top5Acc: 0.3966, Top10Acc: 0.6155, Acc: 0.0658, MacroF1: 0.1026, TimeMAE: 72048.7186, TimeRMSE: 285885.8551, TimeMedAE: 4458.2238
valid [full], NDCG@5: 0.6837, HR@5: 0.8392, NDCG@10: 0.7128, HR@10: 0.9354, MRR: 0.6487
valid [sampled], NDCG@5: 0.5305, HR@5: 0.5357, NDCG@10: 0.5407, HR@10: 0.5677, MRR: 0.5484
test [task], Top5Acc: 0.4421, Top10Acc: 0.5979, Acc: 0.0295, MacroF1: 0.0256, TimeMAE: 13467.1429, TimeRMSE: 69080.1093, TimeMedAE: 7.8090
test [full], NDCG@5: 0.7455, HR@5: 0.9271, NDCG@10: 0.7696, HR@10: 0.9999, MRR: 0.6924
test [sampled], NDCG@5: 0.0854, HR@5: 0.1301, NDCG@10: 0.1641, HR@10: 0.3764, MRR: 0.1355
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.2053
epoch=47, loss=1.1953
epoch=48, loss=1.1896
epoch=49, loss=1.1885
epoch=50, loss=1.1951
valid [task], Top5Acc: 0.4049, Top10Acc: 0.5719, Acc: 0.0677, MacroF1: 0.0951, TimeMAE: 74036.4886, TimeRMSE: 285540.5304, TimeMedAE: 2365.2663
valid [full], NDCG@5: 0.7121, HR@5: 0.8488, NDCG@10: 0.7295, HR@10: 0.9067, MRR: 0.6807
valid [sampled], NDCG@5: 0.5660, HR@5: 0.5712, NDCG@10: 0.5820, HR@10: 0.6213, MRR: 0.5855
test [task], Top5Acc: 0.4338, Top10Acc: 0.5473, Acc: 0.0307, MacroF1: 0.0251, TimeMAE: 12089.7110, TimeRMSE: 64624.5971, TimeMedAE: 7.9927
test [full], NDCG@5: 0.7606, HR@5: 0.9257, NDCG@10: 0.7852, HR@10: 0.9999, MRR: 0.7132
test [sampled], NDCG@5: 0.0922, HR@5: 0.1484, NDCG@10: 0.1777, HR@10: 0.4156, MRR: 0.1391
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10/multitask_refine_ml50_do035_s7/sasrec_last.pth

In [21]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'enable_time_prediction': config.get('enable_time_prediction', False),
            'time_prediction_target': config.get('time_prediction_target'),
            'time_loss_weight': config.get('time_loss_weight'),
            'time_target_transform': config.get('time_target_transform'),
            'time_modeling_mode': config.get('time_modeling_mode'),
        }
        for group_name in ['best_valid', 'best_test_at_best_valid', 'last_valid', 'last_test']:
            group = summary.get(group_name) or {}
            for mode, metrics in group.items():
                for key, value in metrics.items():
                    row[f'{group_name}_{mode}_{key}'] = value
        rows.append(row)
    return pd.DataFrame(rows)

In [22]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1600)
pd.set_option('display.max_colwidth', None)

## Comparison summary

In [25]:
baseline_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
multitask_runs = [
    'multitask_anchor_ml20_s42',
    'multitask_anchor_ml20_s2024',
    'multitask_anchor_ml20_s7',
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
multitask_df = rebuild_df(MULTITASK_BASELINE_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['variant'] = baseline_subset['run_name'].map(
    lambda x: 'anchor_single_task' if x.startswith('anchor_ml20') else 'refine_single_task'
)

multitask_subset = multitask_df[multitask_df['run_name'].isin(multitask_runs)].copy()
multitask_subset['variant'] = multitask_subset['run_name'].map(
    lambda x: 'anchor_multi_task' if 'anchor_ml20' in x else 'refine_multi_task'
)

df_compare = pd.concat([baseline_subset, multitask_subset], ignore_index=True)
df_compare = df_compare.sort_values(['variant', 'seed', 'run_name']).reset_index(drop=True)

display_cols = [
    'run_name', 'seed', 'variant', 'maxlen', 'dropout_rate', 'selection_metric',
    'best_epoch',

    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_mrr',

    'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5',
    'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10',
    'best_test_at_best_valid_full_mrr',

    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_mrr',

    'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5',
    'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10',
    'best_test_at_best_valid_sampled_mrr',

    'best_valid_task_accuracy',
    'best_valid_task_macro_f1',
    'best_valid_task_top5_accuracy',
    'best_valid_task_top10_accuracy',
    'best_valid_task_time_mae',
    'best_valid_task_time_rmse',
    'best_valid_task_time_median_ae',

    'best_test_at_best_valid_task_accuracy',
    'best_test_at_best_valid_task_macro_f1',
    'best_test_at_best_valid_task_top5_accuracy',
    'best_test_at_best_valid_task_top10_accuracy',
    'best_test_at_best_valid_task_time_mae',
    'best_test_at_best_valid_task_time_rmse',
    'best_test_at_best_valid_task_time_median_ae',
]

existing_display_cols = [c for c in display_cols if c in df_compare.columns]
df_compare[existing_display_cols]

                             run_name  seed             variant  maxlen  dropout_rate    selection_metric  best_epoch  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_mrr  best_test_at_best_valid_full_ndcg@5  best_test_at_best_valid_full_hr@5  best_test_at_best_valid_full_ndcg@10  best_test_at_best_valid_full_hr@10  best_test_at_best_valid_full_mrr  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_mrr  best_test_at_best_valid_sampled_ndcg@5  best_test_at_best_valid_sampled_hr@5  best_test_at_best_valid_sampled_ndcg@10  best_test_at_best_valid_sampled_hr@10  best_test_at_best_valid_sampled_mrr  best_valid_task_accuracy  best_valid_task_macro_f1  best_valid_task_top5_accuracy  best_valid_task_top10_accuracy  best_valid_task_time_mae  best_valid_task_time_rmse  best_valid_task_time_median_ae  best_test_at_best_valid_task_accuracy  best_test_at_best_valid_task_macro_f1  best_test_at_best_valid_task_top5_accuracy  best_test_at_best_valid_task_top10_accuracy  best_test_at_best_valid_task_time_mae  best_test_at_best_valid_task_time_rmse  best_test_at_best_valid_task_time_median_ae
0            multitask_anchor_ml20_s7     7   anchor_multi_task      20          0.20  full_valid_ndcg@10          45                0.718860              0.876119                 0.739533               0.944505             0.678634                             0.730814                           0.939099                              0.749556                            0.999865                          0.665654                   0.557397                 0.561872                    0.572765                  0.610312                0.578015                                0.252553                              0.296928                                 0.314915                               0.491271                             0.287664                  0.062008                  0.092260                       0.402035                        0.608412              71386.674438              287652.313094                      781.026734                               0.023143                               0.021551                                    0.465692                                     0.560157                           11294.567416                            66736.008111                                     6.871000
1           multitask_anchor_ml20_s42    42   anchor_multi_task      20          0.20  full_valid_ndcg@10          30                0.706125              0.856119                 0.742361               0.976065             0.671685                             0.785379                           0.929319                              0.809234                            1.000000                          0.745731                   0.538513                 0.545639                    0.554949                  0.597431                0.559410                                0.323805                              0.342939                                 0.366958                               0.477912                             0.363845                  0.053685                  0.052223                       0.408384                        0.692765              74664.950418              282278.030256                     6863.672687                               0.014680                               0.011972                                    0.478864                                     0.668207                           14168.895027                            78819.227077                                   129.408642
2         multitask_anchor_ml20_s2024  2024   anchor_multi_task      20          0.20  full_valid_ndcg@10          40                0.671279              0.798867                 0.718543               0.945636             0.653637                             0.828095                           0.992412                              0.830744                            1.000000                          0.772635                   0.557500                 0.559962                    0.565643                  0.585593                0.574222                                0.289004                              0.306098                                 0.332764                               0.444580                             0.334374                  0.070282                  0.069061                       0.402536                        0.648051              76033.382424              296497.595071                     1482.530225                               0.116531                               0.051538                                    0.476152                                     0.664770                           12305.288892                            71731.711803                                    57.030022
3                      anchor_ml20_s7     7  anchor_single_task      20          0.20  full_valid_ndcg@10          30                0.729167              0.883942                 0.753294               0.961857             0.691225                             0.903861                           0.971918                              0.913637                            1.000000                          0.885501                   0.580044                 0.594609                    0.601240                  0.661113                0.597937                                0.420861                              0.484209                                 0.480200                               0.667438                             0.443705                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
4                     anchor_ml20_s42    42  anchor_single_task      20          0.20  full_valid_ndcg@10          50                0.708784              0.848505                 0.750367               0.977546             0.681799                             0.913814                           0.995781                              0.915296                            1.000000                          0.886842                   0.556357                 0.567822                    0.583692                  0.654340                0.578433                                0.406641                              0.473262                                 0.464891                               0.652470                             0.430220                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
5                   anchor_ml20_s2024  2024  anchor_single_task      20          0.20  full_valid_ndcg@10          25                0.700301              0.850202                 0.736821               0.967429             0.668534                             0.819421                           0.937829                              0.840611                            0.999865                          0.789072                   0.557801                 0.563197                    0.574314                  0.616064                0.578608                                0.261120                              0.326822                                 0.323103                               0.518524                             0.292464                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
6      multitask_refine_ml50_do035_s7     7   refine_multi_task      50          0.35  full_valid_ndcg@10          15                0.654646              0.714809                 0.731297               0.956020             0.669411                             0.654655                           0.851278                              0.703583                            1.000000                          0.608590                   0.597831                 0.598208                    0.601645                  0.610289                0.610293                                0.169432                              0.172104                                 0.196568                               0.259516                             0.217373                  0.064612                  0.094257                       0.449165                        0.769105              72160.363915              279006.648888                      773.954303                               0.022567                               0.020475                                    0.330479                                     0.620582                           12943.153281                            79617.768250                                    17.894858
7     multitask_refine_ml50_do035_s42    42   refine_multi_task      50          0.35  full_valid_ndcg@10          20                0.664381              0.749320                 0.732935               0.969141             0.667017                             0.652864                           0.939369                              0.672353                            1.000000                          0.563962                   0.600481                 0.600870                    0.602203                  0.606444                0.611856                                0.068749                              0.072405                                 0.101780                               0.178779                             0.123676                  0.066340                  0.105943                       0.448206                        0.703371              74968.735553              284365.800932                      824.835017                               0.030045                               0.023825                                    0.292868                                     0.512113                           12011.049804                            71423.215883                                   147.628924
8   multitask_refine_ml50_do035_s2024  2024   refine_multi_task      50          0.35  full_valid_ndcg@10          15                0.669176              0.745948                 0.734897               0.959616             0.674166                             0.705045                           0.871530                              0.747177                            1.000000                          0.667004                   0.615382                 0.615613                    0.615925                  0.617369                0.625271                                0.109371                              0.150245                                 0.166198                               0.328253                             0.151291                  0.058887                  0.079922                       0.452458                        0.692193              69805.661457              283877.471092                     3100.895828                               0.018372                               0.016412                                    0.325803                                     0.541100                           13194.965088                            82865.298609                                    89.414126
9                refine_ml50_do035_s7     7  refine_single_task      50          0.35  full_valid_ndcg@10          25                0.696223              0.857259                 0.728826               0.961737             0.660451                             0.859037                           0.957678                              0.872416                            1.000000                          0.831208                   0.565802                 0.575315                    0.577254                  0.611043                0.581977                                0.324827                              0.417493                                 0.403018                               0.656933                             0.345750                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
10              refine_ml50_do035_s42    42  refine_single_task      50          0.35  full_valid_ndcg@10          50                0.697410              0.854186                 0.735378               0.977276             0.663510                             0.868726                           0.926375                              0.891774                            1.000000                          0.858375                   0.555385                 0.565093                    0.568693                  0.606441                0.572753                                0.399455                              0.467411                                 0.456024                               0.640631                             0.419230                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
11            refine_ml50_do035_s2024  2024  refine_single_task      50          0.35  full_valid_ndcg@10           5                0.713154              0.906351                 0.741573               0.992973             0.664353                             0.727453                           0.850196                              0.775861                            1.000000                          0.707187                   0.563603                 0.567069                    0.572972                  0.597043                0.582973                                0.203548                              0.264514                                 0.257972                               0.431769                             0.234183                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN

In [26]:
summary_metric_cols = [
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_mrr',

    'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5',
    'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10',
    'best_test_at_best_valid_full_mrr',

    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_mrr',

    'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5',
    'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10',
    'best_test_at_best_valid_sampled_mrr',

    'best_valid_task_accuracy',
    'best_valid_task_macro_f1',
    'best_valid_task_top5_accuracy',
    'best_valid_task_top10_accuracy',
    'best_valid_task_time_mae',
    'best_valid_task_time_rmse',
    'best_valid_task_time_median_ae',

    'best_test_at_best_valid_task_accuracy',
    'best_test_at_best_valid_task_macro_f1',
    'best_test_at_best_valid_task_top5_accuracy',
    'best_test_at_best_valid_task_top10_accuracy',
    'best_test_at_best_valid_task_time_mae',
    'best_test_at_best_valid_task_time_rmse',
    'best_test_at_best_valid_task_time_median_ae',
]

summary_metric_cols = [c for c in summary_metric_cols if c in df_compare.columns]
summary_compare = df_compare.groupby('variant')[summary_metric_cols].agg(['mean', 'std'])
summary_compare

                   best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_mrr           best_test_at_best_valid_full_ndcg@5           best_test_at_best_valid_full_hr@5           best_test_at_best_valid_full_ndcg@10           best_test_at_best_valid_full_hr@10           best_test_at_best_valid_full_mrr           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_mrr           best_test_at_best_valid_sampled_ndcg@5           best_test_at_best_valid_sampled_hr@5           best_test_at_best_valid_sampled_ndcg@10           best_test_at_best_valid_sampled_hr@10           best_test_at_best_valid_sampled_mrr           best_valid_task_accuracy           best_valid_task_macro_f1           best_valid_task_top5_accuracy          best_valid_task_top10_accuracy           best_valid_task_time_mae              best_valid_task_time_rmse              best_valid_task_time_median_ae              best_test_at_best_valid_task_accuracy           best_test_at_best_valid_task_macro_f1           best_test_at_best_valid_task_top5_accuracy           best_test_at_best_valid_task_top10_accuracy           best_test_at_best_valid_task_time_mae              best_test_at_best_valid_task_time_rmse              best_test_at_best_valid_task_time_median_ae
                                     mean       std                 mean       std                    mean       std                  mean       std                mean       std                                mean       std                              mean       std                                 mean       std                               mean       std                             mean       std                      mean       std                    mean       std                       mean       std                     mean       std                   mean       std                                   mean       std                                 mean       std                                    mean       std                                  mean       std                                mean       std                     mean       std                     mean       std                          mean      std                           mean       std                     mean          std                      mean          std                           mean          std                                  mean       std                                  mean       std                                       mean       std                                        mean       std                                  mean          std                                   mean          std                                        mean        std
variant
anchor_multi_task                0.698754  0.024632             0.843702  0.040095                0.733479  0.013012              0.955402  0.017904            0.667986  0.012903                            0.781429  0.048761                          0.953610  0.033957                             0.796511  0.042063                           0.999955  0.000078                         0.728006  0.055649                  0.551137  0.010933                0.555825  0.008873                   0.564452  0.008967                 0.597779  0.012363               0.570549  0.009831                               0.288454  0.035629                             0.315321  0.024353                                0.338212  0.026446                              0.471254  0.024047                            0.328628  0.038414                 0.061992  0.008299                 0.071181  0.020103                      0.404318  0.00353                       0.649743  0.042202             74028.335760  2387.871949             288809.312807  7180.041235                    3042.409882  3327.846730                              0.051451  0.056520                              0.028354  0.020642                                   0.473569  0.006955                                    0.631045  0.061415                          12589.583778  1458.100645                           72428.982330  6071.711850                                   64.436555  61.603660
anchor_single_task               0.712751  0.014836             0.860883  0.019988                0.746827  0.008788              0.968944  0.007954            0.680520  0.011400                            0.879032  0.051864                          0.968510  0.029126                             0.889848  0.042649                           0.999955  0.000078                         0.853805  0.056064                  0.564734  0.013279                0.575209  0.016959                   0.586415  0.013668                 0.643839  0.024291               0.584993  0.011211                               0.362874  0.088408                             0.428098  0.087878                                0.422731  0.086620                              0.612810  0.081997                            0.388797  0.083699                      NaN       NaN                      NaN       NaN                           NaN      NaN                            NaN       NaN                      NaN          NaN                       NaN          NaN                            NaN          NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN                                   NaN          NaN                                    NaN          NaN                                         NaN        NaN
refine_multi_task                0.662735  0.007404             0.736693  0.019026                0.733043  0.001802              0.961592  0.006780            0.670198  0.003639                            0.670855  0.029623                          0.887392  0.046138                             0.707704  0.037582                           1.000000  0.000000                         0.613185  0.051675                  0.604565  0.009462                0.604897  0.009375                   0.606591  0.008088                 0.611367  0.005542               0.615807  0.008234                               0.115851  0.050653                             0.131585  0.052404                                0.154849  0.048403                              0.255516  0.074817                            0.164113  0.048147                 0.063280  0.003901                 0.093374  0.013033                      0.449943  0.00223                       0.721557  0.041556             72311.586975  2584.856832             282416.640304  2963.215753                    1566.561716  1329.015834                              0.023661  0.005913                              0.020238  0.003712                                   0.316383  0.020499                                    0.557931  0.056159                          12716.389391   623.682809                           77968.760914  5896.586569                                   84.979303  64.980633
refine_single_task               0.702263  0.009451             0.872599  0.029271                0.735259  0.006374              0.977329  0.015618            0.662771  0.002053                            0.818405  0.078916                          0.911416  0.055280                             0.846684  0.062093                           1.000000  0.000000                         0.798923  0.080599                  0.561597  0.005491                0.569159  0.005422                   0.572973  0.004280                 0.604843  0.007136               0.579235  0.005635                               0.309277  0.098875                             0.383139  0.105721                                0.372338  0.102528                              0.576445  0.125558                            0.333054  0.093175                      NaN       NaN                      NaN       NaN                           NaN      NaN                            NaN       NaN                      NaN          NaN                       NaN          NaN                            NaN          NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN                                   NaN          NaN                                    NaN          NaN                                         NaN        NaN

Interpretation guide:

- compare `anchor_single_task` vs `anchor_multi_task`
- compare `refine_single_task` vs `refine_multi_task`
- use `best_test_at_best_valid_full_ndcg@10` as the main Stage 3 comparison metric
- use mean/std across `42`, `2024`, `7` for final interpretation
- task metrics are shown directly as `accuracy`, `macro_f1`, `top5_accuracy`, `top10_accuracy`, `time_mae`, `time_rmse`