# SASRec BPI2012 Colab Sanity Check

Colab notebook for SASRec sanity checks.

Goals:
- reuse already completed runs instead of retraining them
- train only the missing seeds for the two selected candidate settings
- summarize mean/std and valid-test trends separately for `NDCG@10` and `NDCG@5` model-selection criteria

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012'
NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('NDCG10_OUTPUT_DIR:', NDCG10_OUTPUT_DIR)
print('NDCG5_OUTPUT_DIR:', NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012
NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$NDCG10_OUTPUT_DIR"
!mkdir -p "$NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction

/content
/content/time-aware-behavior-prediction

In [6]:
# If you need the latest code from GitHub, uncomment below.
# %cd /content/time-aware-behavior-prediction
# !git pull

In [7]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [8]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [9]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [10]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Candidate settings

Selected candidates for sanity check:
- `anchor_v3_bpi_short_context` (`hidden_units=32, maxlen=20, dropout=0.2`)
- `refine_v3_ml50_do025` (`hidden_units=50, maxlen=50, dropout=0.25`)

We will evaluate them under two model-selection criteria separately:
- `full_valid_ndcg@10`
- `full_valid_ndcg@5`

## Check existing completed runs

These runs should already exist and **must not be retrained**.

In [11]:
from pathlib import Path

existing_ndcg10 = [
    'anchor_v3_bpi_short_context_seed42',
    'refine_v3_ml50_do025_seed42',
    'refine_v3_ml50_do025_seed2024',
]
existing_ndcg5 = [
    'anchor_v3_bpi_short_context_seed42_ndcg5',
    'refine_v3_ml50_do025_seed42_ndcg5',
    'refine_v3_ml50_do025_seed2024_ndcg5',
]

for label, output_dir, run_names in [
    ('NDCG@10', Path(NDCG10_OUTPUT_DIR), existing_ndcg10),
    ('NDCG@5', Path(NDCG5_OUTPUT_DIR), existing_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
NDCG@10
anchor_v3_bpi_short_context_seed42 EXISTS
refine_v3_ml50_do025_seed42 EXISTS
refine_v3_ml50_do025_seed2024 EXISTS
================================================================================
NDCG@5
anchor_v3_bpi_short_context_seed42_ndcg5 EXISTS
refine_v3_ml50_do025_seed42_ndcg5 EXISTS
refine_v3_ml50_do025_seed2024_ndcg5 EXISTS

## Train only missing seeds for `NDCG@10`

Run these cells only if the corresponding run directory does not already exist.

### anchor_v3_bpi_short_context_seed2024

In [12]:
!python src/train_sasrec.py \
  --run_name anchor_v3_bpi_short_context_seed2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024
epoch=1, loss=0.6261
epoch=2, loss=0.3053
epoch=3, loss=0.2087
epoch=4, loss=0.1653
epoch=5, loss=0.1432
valid [full], NDCG@5: 0.3456, HR@5: 0.5019, NDCG@10: 0.4161, HR@10: 0.7234, MRR: 0.3477
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5593, NDCG@10: 0.5623, HR@10: 0.5710, MRR: 0.5754
test [full], NDCG@5: 0.3824, HR@5: 0.6077, NDCG@10: 0.5008, HR@10: 0.9629, MRR: 0.3623
test [sampled], NDCG@5: 0.5563, HR@5: 0.5605, NDCG@10: 0.5669, HR@10: 0.5944, MRR: 0.5767
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/sasrec_best.pth
epoch=6, loss=0.1316
epoch=7, loss=0.1203
epoch=8, loss=0.1159
epoch=9, loss=0.1099
epoch=10, loss=0.1077
valid [full], NDCG@5: 0.3579, HR@5: 0.5182, NDCG@10: 0.4796, HR@10: 0.9231, MRR: 0.3564
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5581, NDCG@10: 0.5595, HR@10: 0.5636, MRR: 0.5734
test [full], NDCG@5: 0.3757, HR@5: 0.5720, NDCG@10: 0.5050, HR@10: 0.9620, MRR: 0.3702
test [sampled], NDCG@5: 0.5123, HR@5: 0.5216, NDCG@10: 0.5275, HR@10: 0.5696, MRR: 0.5324
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/sasrec_best.pth
epoch=11, loss=0.1037
epoch=12, loss=0.1033
epoch=13, loss=0.1030
epoch=14, loss=0.0999
epoch=15, loss=0.1001
valid [full], NDCG@5: 0.3383, HR@5: 0.4942, NDCG@10: 0.4653, HR@10: 0.9164, MRR: 0.3419
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5678, NDCG@10: 0.5738, HR@10: 0.6021, MRR: 0.5804
test [full], NDCG@5: 0.3249, HR@5: 0.5873, NDCG@10: 0.4465, HR@10: 0.9542, MRR: 0.2957
test [sampled], NDCG@5: 0.6338, HR@5: 0.6438, NDCG@10: 0.6510, HR@10: 0.6974, MRR: 0.6485
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0977
epoch=17, loss=0.0986
epoch=18, loss=0.0959
epoch=19, loss=0.0959
epoch=20, loss=0.0952
valid [full], NDCG@5: 0.3144, HR@5: 0.4541, NDCG@10: 0.4723, HR@10: 0.9647, MRR: 0.3333
valid [sampled], NDCG@5: 0.5531, HR@5: 0.5599, NDCG@10: 0.5653, HR@10: 0.5984, MRR: 0.5701
test [full], NDCG@5: 0.3240, HR@5: 0.5844, NDCG@10: 0.4578, HR@10: 0.9884, MRR: 0.2973
test [sampled], NDCG@5: 0.7290, HR@5: 0.7385, NDCG@10: 0.7413, HR@10: 0.7764, MRR: 0.7395
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0931
epoch=22, loss=0.0940
epoch=23, loss=0.0927
epoch=24, loss=0.0933
epoch=25, loss=0.0913
valid [full], NDCG@5: 0.3106, HR@5: 0.4476, NDCG@10: 0.4856, HR@10: 0.9777, MRR: 0.3426
valid [sampled], NDCG@5: 0.5519, HR@5: 0.5568, NDCG@10: 0.5648, HR@10: 0.5974, MRR: 0.5697
test [full], NDCG@5: 0.3016, HR@5: 0.5351, NDCG@10: 0.4527, HR@10: 0.9919, MRR: 0.2901
test [sampled], NDCG@5: 0.6789, HR@5: 0.6919, NDCG@10: 0.7034, HR@10: 0.7690, MRR: 0.6948
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/sasrec_best.pth
epoch=26, loss=0.0902
epoch=27, loss=0.0944
epoch=28, loss=0.0919
epoch=29, loss=0.0926
epoch=30, loss=0.0886
valid [full], NDCG@5: 0.3173, HR@5: 0.4612, NDCG@10: 0.4841, HR@10: 0.9775, MRR: 0.3415
valid [sampled], NDCG@5: 0.5372, HR@5: 0.5441, NDCG@10: 0.5547, HR@10: 0.5999, MRR: 0.5576
test [full], NDCG@5: 0.4213, HR@5: 0.7949, NDCG@10: 0.4835, HR@10: 0.9874, MRR: 0.3265
test [sampled], NDCG@5: 0.7468, HR@5: 0.7537, NDCG@10: 0.7617, HR@10: 0.8013, MRR: 0.7585
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0910
epoch=32, loss=0.0885
epoch=33, loss=0.0899
epoch=34, loss=0.0889
epoch=35, loss=0.0877
valid [full], NDCG@5: 0.3110, HR@5: 0.4526, NDCG@10: 0.4739, HR@10: 0.9731, MRR: 0.3320
valid [sampled], NDCG@5: 0.5451, HR@5: 0.5565, NDCG@10: 0.5632, HR@10: 0.6132, MRR: 0.5643
test [full], NDCG@5: 0.2990, HR@5: 0.5553, NDCG@10: 0.4418, HR@10: 0.9824, MRR: 0.2788
test [sampled], NDCG@5: 0.7675, HR@5: 0.7697, NDCG@10: 0.7769, HR@10: 0.8000, MRR: 0.7790
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0888
epoch=37, loss=0.0894
epoch=38, loss=0.0893
epoch=39, loss=0.0897
epoch=40, loss=0.0893
valid [full], NDCG@5: 0.3362, HR@5: 0.5045, NDCG@10: 0.4906, HR@10: 0.9768, MRR: 0.3485
valid [sampled], NDCG@5: 0.5613, HR@5: 0.5699, NDCG@10: 0.5810, HR@10: 0.6329, MRR: 0.5810
test [full], NDCG@5: 0.4033, HR@5: 0.7659, NDCG@10: 0.4750, HR@10: 0.9897, MRR: 0.3173
test [sampled], NDCG@5: 0.7528, HR@5: 0.7684, NDCG@10: 0.7735, HR@10: 0.8330, MRR: 0.7629
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/sasrec_best.pth
epoch=41, loss=0.0870
epoch=42, loss=0.0902
epoch=43, loss=0.0906
epoch=44, loss=0.0875
epoch=45, loss=0.0868
valid [full], NDCG@5: 0.3231, HR@5: 0.4788, NDCG@10: 0.4878, HR@10: 0.9749, MRR: 0.3457
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5633, NDCG@10: 0.5764, HR@10: 0.6332, MRR: 0.5748
test [full], NDCG@5: 0.2953, HR@5: 0.5426, NDCG@10: 0.4429, HR@10: 0.9900, MRR: 0.2784
test [sampled], NDCG@5: 0.7939, HR@5: 0.8039, NDCG@10: 0.8114, HR@10: 0.8590, MRR: 0.8041
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0852
epoch=47, loss=0.0858
epoch=48, loss=0.0882
epoch=49, loss=0.0854
epoch=50, loss=0.0877
valid [full], NDCG@5: 0.2977, HR@5: 0.4200, NDCG@10: 0.4778, HR@10: 0.9707, MRR: 0.3362
valid [sampled], NDCG@5: 0.5148, HR@5: 0.5213, NDCG@10: 0.5320, HR@10: 0.5761, MRR: 0.5358
test [full], NDCG@5: 0.3081, HR@5: 0.5378, NDCG@10: 0.4595, HR@10: 0.9819, MRR: 0.3022
test [sampled], NDCG@5: 0.8169, HR@5: 0.8229, NDCG@10: 0.8280, HR@10: 0.8577, MRR: 0.8251
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed2024/sasrec_last.pth

### anchor_v3_bpi_short_context_seed7

In [13]:
!python src/train_sasrec.py \
  --run_name anchor_v3_bpi_short_context_seed7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7
epoch=1, loss=0.6517
epoch=2, loss=0.3093
epoch=3, loss=0.2163
epoch=4, loss=0.1750
epoch=5, loss=0.1489
valid [full], NDCG@5: 0.3963, HR@5: 0.6169, NDCG@10: 0.4420, HR@10: 0.7547, MRR: 0.3623
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5575, NDCG@10: 0.5649, HR@10: 0.5880, MRR: 0.5741
test [full], NDCG@5: 0.2216, HR@5: 0.3935, NDCG@10: 0.2634, HR@10: 0.5249, MRR: 0.2171
test [sampled], NDCG@5: 0.5651, HR@5: 0.5692, NDCG@10: 0.5821, HR@10: 0.6240, MRR: 0.5870
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/sasrec_best.pth
epoch=6, loss=0.1356
epoch=7, loss=0.1253
epoch=8, loss=0.1189
epoch=9, loss=0.1178
epoch=10, loss=0.1113
valid [full], NDCG@5: 0.3745, HR@5: 0.5891, NDCG@10: 0.4391, HR@10: 0.7838, MRR: 0.3475
valid [sampled], NDCG@5: 0.5614, HR@5: 0.5693, NDCG@10: 0.5729, HR@10: 0.6056, MRR: 0.5777
test [full], NDCG@5: 0.2611, HR@5: 0.4576, NDCG@10: 0.3365, HR@10: 0.6912, MRR: 0.2504
test [sampled], NDCG@5: 0.5925, HR@5: 0.6128, NDCG@10: 0.6247, HR@10: 0.7129, MRR: 0.6126
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1104
epoch=12, loss=0.1082
epoch=13, loss=0.1045
epoch=14, loss=0.1037
epoch=15, loss=0.1019
valid [full], NDCG@5: 0.3361, HR@5: 0.4969, NDCG@10: 0.4259, HR@10: 0.7717, MRR: 0.3370
valid [sampled], NDCG@5: 0.5723, HR@5: 0.5856, NDCG@10: 0.5915, HR@10: 0.6454, MRR: 0.5902
test [full], NDCG@5: 0.2792, HR@5: 0.4923, NDCG@10: 0.3732, HR@10: 0.7871, MRR: 0.2669
test [sampled], NDCG@5: 0.7295, HR@5: 0.7472, NDCG@10: 0.7554, HR@10: 0.8276, MRR: 0.7439
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0983
epoch=17, loss=0.0964
epoch=18, loss=0.0969
epoch=19, loss=0.0962
epoch=20, loss=0.0959
valid [full], NDCG@5: 0.3652, HR@5: 0.5614, NDCG@10: 0.4338, HR@10: 0.7710, MRR: 0.3459
valid [sampled], NDCG@5: 0.5849, HR@5: 0.5988, NDCG@10: 0.6026, HR@10: 0.6539, MRR: 0.6010
test [full], NDCG@5: 0.3615, HR@5: 0.6124, NDCG@10: 0.4882, HR@10: 0.9835, MRR: 0.3370
test [sampled], NDCG@5: 0.7865, HR@5: 0.7979, NDCG@10: 0.8013, HR@10: 0.8443, MRR: 0.7957
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0973
epoch=22, loss=0.0935
epoch=23, loss=0.0956
epoch=24, loss=0.0914
epoch=25, loss=0.0938
valid [full], NDCG@5: 0.4277, HR@5: 0.6742, NDCG@10: 0.4659, HR@10: 0.7878, MRR: 0.3815
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5706, NDCG@10: 0.5832, HR@10: 0.6381, MRR: 0.5829
test [full], NDCG@5: 0.5274, HR@5: 0.8941, NDCG@10: 0.5612, HR@10: 0.9938, MRR: 0.4248
test [sampled], NDCG@5: 0.8183, HR@5: 0.8237, NDCG@10: 0.8338, HR@10: 0.8727, MRR: 0.8293
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/sasrec_best.pth
epoch=26, loss=0.0918
epoch=27, loss=0.0926
epoch=28, loss=0.0919
epoch=29, loss=0.0901
epoch=30, loss=0.0911
valid [full], NDCG@5: 0.3784, HR@5: 0.5951, NDCG@10: 0.4329, HR@10: 0.7588, MRR: 0.3525
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5682, NDCG@10: 0.5824, HR@10: 0.6449, MRR: 0.5797
test [full], NDCG@5: 0.4797, HR@5: 0.8036, NDCG@10: 0.5389, HR@10: 0.9838, MRR: 0.4019
test [sampled], NDCG@5: 0.6537, HR@5: 0.7094, NDCG@10: 0.7063, HR@10: 0.8701, MRR: 0.6643
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0915
epoch=32, loss=0.0902
epoch=33, loss=0.0899
epoch=34, loss=0.0871
epoch=35, loss=0.0905
valid [full], NDCG@5: 0.3632, HR@5: 0.5535, NDCG@10: 0.4374, HR@10: 0.7764, MRR: 0.3526
valid [sampled], NDCG@5: 0.5431, HR@5: 0.5553, NDCG@10: 0.5681, HR@10: 0.6348, MRR: 0.5642
test [full], NDCG@5: 0.4196, HR@5: 0.6268, NDCG@10: 0.5431, HR@10: 0.9823, MRR: 0.4095
test [sampled], NDCG@5: 0.6612, HR@5: 0.7159, NDCG@10: 0.7121, HR@10: 0.8716, MRR: 0.6709
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0891
epoch=37, loss=0.0893
epoch=38, loss=0.0899
epoch=39, loss=0.0885
epoch=40, loss=0.0887
valid [full], NDCG@5: 0.3894, HR@5: 0.5952, NDCG@10: 0.4485, HR@10: 0.7743, MRR: 0.3662
valid [sampled], NDCG@5: 0.5842, HR@5: 0.5959, NDCG@10: 0.6056, HR@10: 0.6627, MRR: 0.6036
test [full], NDCG@5: 0.4711, HR@5: 0.8497, NDCG@10: 0.5159, HR@10: 0.9837, MRR: 0.3704
test [sampled], NDCG@5: 0.6976, HR@5: 0.7528, NDCG@10: 0.7423, HR@10: 0.8893, MRR: 0.7030
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0912
epoch=42, loss=0.0869
epoch=43, loss=0.0903
epoch=44, loss=0.0877
epoch=45, loss=0.0876
valid [full], NDCG@5: 0.3814, HR@5: 0.5952, NDCG@10: 0.4348, HR@10: 0.7556, MRR: 0.3574
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5730, NDCG@10: 0.5778, HR@10: 0.6312, MRR: 0.5769
test [full], NDCG@5: 0.4316, HR@5: 0.6914, NDCG@10: 0.5335, HR@10: 0.9822, MRR: 0.3954
test [sampled], NDCG@5: 0.6638, HR@5: 0.7238, NDCG@10: 0.7154, HR@10: 0.8815, MRR: 0.6712
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0898
epoch=47, loss=0.0889
epoch=48, loss=0.0869
epoch=49, loss=0.0862
epoch=50, loss=0.0870
valid [full], NDCG@5: 0.3608, HR@5: 0.5607, NDCG@10: 0.4839, HR@10: 0.9280, MRR: 0.3561
valid [sampled], NDCG@5: 0.5620, HR@5: 0.5717, NDCG@10: 0.5890, HR@10: 0.6571, MRR: 0.5845
test [full], NDCG@5: 0.4903, HR@5: 0.8260, NDCG@10: 0.5422, HR@10: 0.9812, MRR: 0.4051
test [sampled], NDCG@5: 0.6530, HR@5: 0.7085, NDCG@10: 0.7043, HR@10: 0.8659, MRR: 0.6625
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/anchor_v3_bpi_short_context_seed7/sasrec_last.pth

### refine_v3_ml50_do025_seed7

In [14]:
!python src/train_sasrec.py \
  --run_name refine_v3_ml50_do025_seed7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7
epoch=1, loss=0.5213
epoch=2, loss=0.2527
epoch=3, loss=0.1836
epoch=4, loss=0.1486
epoch=5, loss=0.1288
valid [full], NDCG@5: 0.3332, HR@5: 0.4863, NDCG@10: 0.4342, HR@10: 0.7879, MRR: 0.3404
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5622, NDCG@10: 0.5664, HR@10: 0.5942, MRR: 0.5735
test [full], NDCG@5: 0.2762, HR@5: 0.4801, NDCG@10: 0.3083, HR@10: 0.5748, MRR: 0.2475
test [sampled], NDCG@5: 0.3947, HR@5: 0.4062, NDCG@10: 0.4352, HR@10: 0.5358, MRR: 0.4298
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/sasrec_best.pth
epoch=6, loss=0.1146
epoch=7, loss=0.1086
epoch=8, loss=0.1031
epoch=9, loss=0.1006
epoch=10, loss=0.0969
valid [full], NDCG@5: 0.3235, HR@5: 0.4553, NDCG@10: 0.4091, HR@10: 0.7213, MRR: 0.3377
valid [sampled], NDCG@5: 0.5556, HR@5: 0.5578, NDCG@10: 0.5622, HR@10: 0.5787, MRR: 0.5738
test [full], NDCG@5: 0.2899, HR@5: 0.4525, NDCG@10: 0.3853, HR@10: 0.7457, MRR: 0.2948
test [sampled], NDCG@5: 0.4303, HR@5: 0.4972, NDCG@10: 0.4952, HR@10: 0.6974, MRR: 0.4519
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0957
epoch=12, loss=0.0946
epoch=13, loss=0.0910
epoch=14, loss=0.0868
epoch=15, loss=0.0901
valid [full], NDCG@5: 0.3250, HR@5: 0.4800, NDCG@10: 0.4215, HR@10: 0.7719, MRR: 0.3370
valid [sampled], NDCG@5: 0.5618, HR@5: 0.5683, NDCG@10: 0.5777, HR@10: 0.6190, MRR: 0.5814
test [full], NDCG@5: 0.3346, HR@5: 0.5988, NDCG@10: 0.4712, HR@10: 0.9974, MRR: 0.3090
test [sampled], NDCG@5: 0.5143, HR@5: 0.5929, NDCG@10: 0.5899, HR@10: 0.8241, MRR: 0.5288
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0890
epoch=17, loss=0.0848
epoch=18, loss=0.0844
epoch=19, loss=0.0846
epoch=20, loss=0.0822
valid [full], NDCG@5: 0.3694, HR@5: 0.5826, NDCG@10: 0.4344, HR@10: 0.7771, MRR: 0.3494
valid [sampled], NDCG@5: 0.5621, HR@5: 0.5724, NDCG@10: 0.5790, HR@10: 0.6260, MRR: 0.5787
test [full], NDCG@5: 0.3553, HR@5: 0.6182, NDCG@10: 0.4868, HR@10: 0.9968, MRR: 0.3315
test [sampled], NDCG@5: 0.5350, HR@5: 0.6079, NDCG@10: 0.6052, HR@10: 0.8227, MRR: 0.5484
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/sasrec_best.pth
epoch=21, loss=0.0822
epoch=22, loss=0.0826
epoch=23, loss=0.0838
epoch=24, loss=0.0832
epoch=25, loss=0.0828
valid [full], NDCG@5: 0.4230, HR@5: 0.6410, NDCG@10: 0.5313, HR@10: 0.9910, MRR: 0.3938
valid [sampled], NDCG@5: 0.5646, HR@5: 0.5764, NDCG@10: 0.5795, HR@10: 0.6227, MRR: 0.5799
test [full], NDCG@5: 0.5143, HR@5: 0.8691, NDCG@10: 0.5595, HR@10: 0.9989, MRR: 0.4197
test [sampled], NDCG@5: 0.6072, HR@5: 0.6197, NDCG@10: 0.6488, HR@10: 0.7532, MRR: 0.6338
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/sasrec_best.pth
epoch=26, loss=0.0821
epoch=27, loss=0.0822
epoch=28, loss=0.0810
epoch=29, loss=0.0819
epoch=30, loss=0.0799
valid [full], NDCG@5: 0.4018, HR@5: 0.6131, NDCG@10: 0.5213, HR@10: 0.9879, MRR: 0.3820
valid [sampled], NDCG@5: 0.5556, HR@5: 0.5605, NDCG@10: 0.5662, HR@10: 0.5941, MRR: 0.5723
test [full], NDCG@5: 0.4988, HR@5: 0.8809, NDCG@10: 0.5395, HR@10: 0.9986, MRR: 0.3945
test [sampled], NDCG@5: 0.6382, HR@5: 0.6843, NDCG@10: 0.6825, HR@10: 0.8199, MRR: 0.6498
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0798
epoch=32, loss=0.0796
epoch=33, loss=0.0789
epoch=34, loss=0.0781
epoch=35, loss=0.0812
valid [full], NDCG@5: 0.4075, HR@5: 0.6361, NDCG@10: 0.5259, HR@10: 0.9887, MRR: 0.3857
valid [sampled], NDCG@5: 0.5558, HR@5: 0.5671, NDCG@10: 0.5697, HR@10: 0.6106, MRR: 0.5716
test [full], NDCG@5: 0.3759, HR@5: 0.6276, NDCG@10: 0.5045, HR@10: 0.9985, MRR: 0.3529
test [sampled], NDCG@5: 0.7476, HR@5: 0.7563, NDCG@10: 0.7685, HR@10: 0.8226, MRR: 0.7605
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0791
epoch=37, loss=0.0785
epoch=38, loss=0.0793
epoch=39, loss=0.0774
epoch=40, loss=0.0778
valid [full], NDCG@5: 0.4097, HR@5: 0.6179, NDCG@10: 0.5311, HR@10: 0.9904, MRR: 0.3926
valid [sampled], NDCG@5: 0.5566, HR@5: 0.5675, NDCG@10: 0.5713, HR@10: 0.6132, MRR: 0.5741
test [full], NDCG@5: 0.4201, HR@5: 0.6353, NDCG@10: 0.5485, HR@10: 0.9995, MRR: 0.4089
test [sampled], NDCG@5: 0.7149, HR@5: 0.7204, NDCG@10: 0.7389, HR@10: 0.7973, MRR: 0.7328
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0813
epoch=42, loss=0.0782
epoch=43, loss=0.0796
epoch=44, loss=0.0780
epoch=45, loss=0.0795
valid [full], NDCG@5: 0.4119, HR@5: 0.6152, NDCG@10: 0.5343, HR@10: 0.9937, MRR: 0.3959
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5689, NDCG@10: 0.5718, HR@10: 0.6229, MRR: 0.5708
test [full], NDCG@5: 0.4235, HR@5: 0.6315, NDCG@10: 0.5508, HR@10: 0.9991, MRR: 0.4126
test [sampled], NDCG@5: 0.7341, HR@5: 0.7460, NDCG@10: 0.7602, HR@10: 0.8286, MRR: 0.7485
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/sasrec_best.pth
epoch=46, loss=0.0778
epoch=47, loss=0.0787
epoch=48, loss=0.0783
epoch=49, loss=0.0773
epoch=50, loss=0.0791
valid [full], NDCG@5: 0.4184, HR@5: 0.6288, NDCG@10: 0.5351, HR@10: 0.9859, MRR: 0.3988
valid [sampled], NDCG@5: 0.5307, HR@5: 0.5334, NDCG@10: 0.5402, HR@10: 0.5640, MRR: 0.5508
test [full], NDCG@5: 0.4462, HR@5: 0.6310, NDCG@10: 0.5746, HR@10: 0.9991, MRR: 0.4445
test [sampled], NDCG@5: 0.7589, HR@5: 0.7613, NDCG@10: 0.7747, HR@10: 0.8121, MRR: 0.7735
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012/refine_v3_ml50_do025_seed7/sasrec_last.pth

## Train only missing seeds for `NDCG@5`

Run these cells only if the corresponding run directory does not already exist.

### anchor_v3_bpi_short_context_seed2024_ndcg5

In [15]:
!python src/train_sasrec.py \
  --run_name anchor_v3_bpi_short_context_seed2024_ndcg5 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5
epoch=1, loss=0.6261
epoch=2, loss=0.3053
epoch=3, loss=0.2087
epoch=4, loss=0.1653
epoch=5, loss=0.1432
valid [full], NDCG@5: 0.3456, HR@5: 0.5019, NDCG@10: 0.4161, HR@10: 0.7234, MRR: 0.3477
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5593, NDCG@10: 0.5623, HR@10: 0.5710, MRR: 0.5754
test [full], NDCG@5: 0.3824, HR@5: 0.6077, NDCG@10: 0.5008, HR@10: 0.9629, MRR: 0.3623
test [sampled], NDCG@5: 0.5563, HR@5: 0.5605, NDCG@10: 0.5669, HR@10: 0.5944, MRR: 0.5767
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/sasrec_best.pth
epoch=6, loss=0.1316
epoch=7, loss=0.1203
epoch=8, loss=0.1159
epoch=9, loss=0.1099
epoch=10, loss=0.1077
valid [full], NDCG@5: 0.3579, HR@5: 0.5182, NDCG@10: 0.4796, HR@10: 0.9231, MRR: 0.3564
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5581, NDCG@10: 0.5595, HR@10: 0.5636, MRR: 0.5734
test [full], NDCG@5: 0.3757, HR@5: 0.5720, NDCG@10: 0.5050, HR@10: 0.9620, MRR: 0.3702
test [sampled], NDCG@5: 0.5123, HR@5: 0.5216, NDCG@10: 0.5275, HR@10: 0.5696, MRR: 0.5324
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/sasrec_best.pth
epoch=11, loss=0.1037
epoch=12, loss=0.1033
epoch=13, loss=0.1030
epoch=14, loss=0.0999
epoch=15, loss=0.1001
valid [full], NDCG@5: 0.3383, HR@5: 0.4942, NDCG@10: 0.4653, HR@10: 0.9164, MRR: 0.3419
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5678, NDCG@10: 0.5738, HR@10: 0.6021, MRR: 0.5804
test [full], NDCG@5: 0.3249, HR@5: 0.5873, NDCG@10: 0.4465, HR@10: 0.9542, MRR: 0.2957
test [sampled], NDCG@5: 0.6338, HR@5: 0.6438, NDCG@10: 0.6510, HR@10: 0.6974, MRR: 0.6485
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0977
epoch=17, loss=0.0986
epoch=18, loss=0.0959
epoch=19, loss=0.0959
epoch=20, loss=0.0952
valid [full], NDCG@5: 0.3144, HR@5: 0.4541, NDCG@10: 0.4723, HR@10: 0.9647, MRR: 0.3333
valid [sampled], NDCG@5: 0.5531, HR@5: 0.5599, NDCG@10: 0.5653, HR@10: 0.5984, MRR: 0.5701
test [full], NDCG@5: 0.3240, HR@5: 0.5844, NDCG@10: 0.4578, HR@10: 0.9884, MRR: 0.2973
test [sampled], NDCG@5: 0.7290, HR@5: 0.7385, NDCG@10: 0.7413, HR@10: 0.7764, MRR: 0.7395
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0931
epoch=22, loss=0.0940
epoch=23, loss=0.0927
epoch=24, loss=0.0933
epoch=25, loss=0.0913
valid [full], NDCG@5: 0.3106, HR@5: 0.4476, NDCG@10: 0.4856, HR@10: 0.9777, MRR: 0.3426
valid [sampled], NDCG@5: 0.5519, HR@5: 0.5568, NDCG@10: 0.5648, HR@10: 0.5974, MRR: 0.5697
test [full], NDCG@5: 0.3016, HR@5: 0.5351, NDCG@10: 0.4527, HR@10: 0.9919, MRR: 0.2901
test [sampled], NDCG@5: 0.6789, HR@5: 0.6919, NDCG@10: 0.7034, HR@10: 0.7690, MRR: 0.6948
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0902
epoch=27, loss=0.0944
epoch=28, loss=0.0919
epoch=29, loss=0.0926
epoch=30, loss=0.0886
valid [full], NDCG@5: 0.3173, HR@5: 0.4612, NDCG@10: 0.4841, HR@10: 0.9775, MRR: 0.3415
valid [sampled], NDCG@5: 0.5372, HR@5: 0.5441, NDCG@10: 0.5547, HR@10: 0.5999, MRR: 0.5576
test [full], NDCG@5: 0.4213, HR@5: 0.7949, NDCG@10: 0.4835, HR@10: 0.9874, MRR: 0.3265
test [sampled], NDCG@5: 0.7468, HR@5: 0.7537, NDCG@10: 0.7617, HR@10: 0.8013, MRR: 0.7585
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0910
epoch=32, loss=0.0885
epoch=33, loss=0.0899
epoch=34, loss=0.0889
epoch=35, loss=0.0877
valid [full], NDCG@5: 0.3110, HR@5: 0.4526, NDCG@10: 0.4739, HR@10: 0.9731, MRR: 0.3320
valid [sampled], NDCG@5: 0.5451, HR@5: 0.5565, NDCG@10: 0.5632, HR@10: 0.6132, MRR: 0.5643
test [full], NDCG@5: 0.2990, HR@5: 0.5553, NDCG@10: 0.4418, HR@10: 0.9824, MRR: 0.2788
test [sampled], NDCG@5: 0.7675, HR@5: 0.7697, NDCG@10: 0.7769, HR@10: 0.8000, MRR: 0.7790
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0888
epoch=37, loss=0.0894
epoch=38, loss=0.0893
epoch=39, loss=0.0897
epoch=40, loss=0.0893
valid [full], NDCG@5: 0.3362, HR@5: 0.5045, NDCG@10: 0.4906, HR@10: 0.9768, MRR: 0.3485
valid [sampled], NDCG@5: 0.5613, HR@5: 0.5699, NDCG@10: 0.5810, HR@10: 0.6329, MRR: 0.5810
test [full], NDCG@5: 0.4033, HR@5: 0.7659, NDCG@10: 0.4750, HR@10: 0.9897, MRR: 0.3173
test [sampled], NDCG@5: 0.7528, HR@5: 0.7684, NDCG@10: 0.7735, HR@10: 0.8330, MRR: 0.7629
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0870
epoch=42, loss=0.0902
epoch=43, loss=0.0906
epoch=44, loss=0.0875
epoch=45, loss=0.0868
valid [full], NDCG@5: 0.3231, HR@5: 0.4788, NDCG@10: 0.4878, HR@10: 0.9749, MRR: 0.3457
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5633, NDCG@10: 0.5764, HR@10: 0.6332, MRR: 0.5748
test [full], NDCG@5: 0.2953, HR@5: 0.5426, NDCG@10: 0.4429, HR@10: 0.9900, MRR: 0.2784
test [sampled], NDCG@5: 0.7939, HR@5: 0.8039, NDCG@10: 0.8114, HR@10: 0.8590, MRR: 0.8041
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0852
epoch=47, loss=0.0858
epoch=48, loss=0.0882
epoch=49, loss=0.0854
epoch=50, loss=0.0877
valid [full], NDCG@5: 0.2977, HR@5: 0.4200, NDCG@10: 0.4778, HR@10: 0.9707, MRR: 0.3362
valid [sampled], NDCG@5: 0.5148, HR@5: 0.5213, NDCG@10: 0.5320, HR@10: 0.5761, MRR: 0.5358
test [full], NDCG@5: 0.3081, HR@5: 0.5378, NDCG@10: 0.4595, HR@10: 0.9819, MRR: 0.3022
test [sampled], NDCG@5: 0.8169, HR@5: 0.8229, NDCG@10: 0.8280, HR@10: 0.8577, MRR: 0.8251
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed2024_ndcg5/sasrec_last.pth

### anchor_v3_bpi_short_context_seed7_ndcg5

In [16]:
!python src/train_sasrec.py \
  --run_name anchor_v3_bpi_short_context_seed7_ndcg5 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5
epoch=1, loss=0.6517
epoch=2, loss=0.3093
epoch=3, loss=0.2163
epoch=4, loss=0.1750
epoch=5, loss=0.1489
valid [full], NDCG@5: 0.3963, HR@5: 0.6169, NDCG@10: 0.4420, HR@10: 0.7547, MRR: 0.3623
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5575, NDCG@10: 0.5649, HR@10: 0.5880, MRR: 0.5741
test [full], NDCG@5: 0.2216, HR@5: 0.3935, NDCG@10: 0.2634, HR@10: 0.5249, MRR: 0.2171
test [sampled], NDCG@5: 0.5651, HR@5: 0.5692, NDCG@10: 0.5821, HR@10: 0.6240, MRR: 0.5870
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/sasrec_best.pth
epoch=6, loss=0.1356
epoch=7, loss=0.1253
epoch=8, loss=0.1189
epoch=9, loss=0.1178
epoch=10, loss=0.1113
valid [full], NDCG@5: 0.3745, HR@5: 0.5891, NDCG@10: 0.4391, HR@10: 0.7838, MRR: 0.3475
valid [sampled], NDCG@5: 0.5614, HR@5: 0.5693, NDCG@10: 0.5729, HR@10: 0.6056, MRR: 0.5777
test [full], NDCG@5: 0.2611, HR@5: 0.4576, NDCG@10: 0.3365, HR@10: 0.6912, MRR: 0.2504
test [sampled], NDCG@5: 0.5925, HR@5: 0.6128, NDCG@10: 0.6247, HR@10: 0.7129, MRR: 0.6126
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1104
epoch=12, loss=0.1082
epoch=13, loss=0.1045
epoch=14, loss=0.1037
epoch=15, loss=0.1019
valid [full], NDCG@5: 0.3361, HR@5: 0.4969, NDCG@10: 0.4259, HR@10: 0.7717, MRR: 0.3370
valid [sampled], NDCG@5: 0.5723, HR@5: 0.5856, NDCG@10: 0.5915, HR@10: 0.6454, MRR: 0.5902
test [full], NDCG@5: 0.2792, HR@5: 0.4923, NDCG@10: 0.3732, HR@10: 0.7871, MRR: 0.2669
test [sampled], NDCG@5: 0.7295, HR@5: 0.7472, NDCG@10: 0.7554, HR@10: 0.8276, MRR: 0.7439
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0983
epoch=17, loss=0.0964
epoch=18, loss=0.0969
epoch=19, loss=0.0962
epoch=20, loss=0.0959
valid [full], NDCG@5: 0.3652, HR@5: 0.5614, NDCG@10: 0.4338, HR@10: 0.7710, MRR: 0.3459
valid [sampled], NDCG@5: 0.5849, HR@5: 0.5988, NDCG@10: 0.6026, HR@10: 0.6539, MRR: 0.6010
test [full], NDCG@5: 0.3615, HR@5: 0.6124, NDCG@10: 0.4882, HR@10: 0.9835, MRR: 0.3370
test [sampled], NDCG@5: 0.7865, HR@5: 0.7979, NDCG@10: 0.8013, HR@10: 0.8443, MRR: 0.7957
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0973
epoch=22, loss=0.0935
epoch=23, loss=0.0956
epoch=24, loss=0.0914
epoch=25, loss=0.0938
valid [full], NDCG@5: 0.4277, HR@5: 0.6742, NDCG@10: 0.4659, HR@10: 0.7878, MRR: 0.3815
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5706, NDCG@10: 0.5832, HR@10: 0.6381, MRR: 0.5829
test [full], NDCG@5: 0.5274, HR@5: 0.8941, NDCG@10: 0.5612, HR@10: 0.9938, MRR: 0.4248
test [sampled], NDCG@5: 0.8183, HR@5: 0.8237, NDCG@10: 0.8338, HR@10: 0.8727, MRR: 0.8293
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/sasrec_best.pth
epoch=26, loss=0.0918
epoch=27, loss=0.0926
epoch=28, loss=0.0919
epoch=29, loss=0.0901
epoch=30, loss=0.0911
valid [full], NDCG@5: 0.3784, HR@5: 0.5951, NDCG@10: 0.4329, HR@10: 0.7588, MRR: 0.3525
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5682, NDCG@10: 0.5824, HR@10: 0.6449, MRR: 0.5797
test [full], NDCG@5: 0.4797, HR@5: 0.8036, NDCG@10: 0.5389, HR@10: 0.9838, MRR: 0.4019
test [sampled], NDCG@5: 0.6537, HR@5: 0.7094, NDCG@10: 0.7063, HR@10: 0.8701, MRR: 0.6643
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0915
epoch=32, loss=0.0902
epoch=33, loss=0.0899
epoch=34, loss=0.0871
epoch=35, loss=0.0905
valid [full], NDCG@5: 0.3632, HR@5: 0.5535, NDCG@10: 0.4374, HR@10: 0.7764, MRR: 0.3526
valid [sampled], NDCG@5: 0.5431, HR@5: 0.5553, NDCG@10: 0.5681, HR@10: 0.6348, MRR: 0.5642
test [full], NDCG@5: 0.4196, HR@5: 0.6268, NDCG@10: 0.5431, HR@10: 0.9823, MRR: 0.4095
test [sampled], NDCG@5: 0.6612, HR@5: 0.7159, NDCG@10: 0.7121, HR@10: 0.8716, MRR: 0.6709
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0891
epoch=37, loss=0.0893
epoch=38, loss=0.0899
epoch=39, loss=0.0885
epoch=40, loss=0.0887
valid [full], NDCG@5: 0.3894, HR@5: 0.5952, NDCG@10: 0.4485, HR@10: 0.7743, MRR: 0.3662
valid [sampled], NDCG@5: 0.5842, HR@5: 0.5959, NDCG@10: 0.6056, HR@10: 0.6627, MRR: 0.6036
test [full], NDCG@5: 0.4711, HR@5: 0.8497, NDCG@10: 0.5159, HR@10: 0.9837, MRR: 0.3704
test [sampled], NDCG@5: 0.6976, HR@5: 0.7528, NDCG@10: 0.7423, HR@10: 0.8893, MRR: 0.7030
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0912
epoch=42, loss=0.0869
epoch=43, loss=0.0903
epoch=44, loss=0.0877
epoch=45, loss=0.0876
valid [full], NDCG@5: 0.3814, HR@5: 0.5952, NDCG@10: 0.4348, HR@10: 0.7556, MRR: 0.3574
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5730, NDCG@10: 0.5778, HR@10: 0.6312, MRR: 0.5769
test [full], NDCG@5: 0.4316, HR@5: 0.6914, NDCG@10: 0.5335, HR@10: 0.9822, MRR: 0.3954
test [sampled], NDCG@5: 0.6638, HR@5: 0.7238, NDCG@10: 0.7154, HR@10: 0.8815, MRR: 0.6712
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0898
epoch=47, loss=0.0889
epoch=48, loss=0.0869
epoch=49, loss=0.0862
epoch=50, loss=0.0870
valid [full], NDCG@5: 0.3608, HR@5: 0.5607, NDCG@10: 0.4839, HR@10: 0.9280, MRR: 0.3561
valid [sampled], NDCG@5: 0.5620, HR@5: 0.5717, NDCG@10: 0.5890, HR@10: 0.6571, MRR: 0.5845
test [full], NDCG@5: 0.4903, HR@5: 0.8260, NDCG@10: 0.5422, HR@10: 0.9812, MRR: 0.4051
test [sampled], NDCG@5: 0.6530, HR@5: 0.7085, NDCG@10: 0.7043, HR@10: 0.8659, MRR: 0.6625
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_v3_bpi_short_context_seed7_ndcg5/sasrec_last.pth

### refine_v3_ml50_do025_seed7_ndcg5

In [17]:
!python src/train_sasrec.py \
  --run_name refine_v3_ml50_do025_seed7_ndcg5 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5
epoch=1, loss=0.5213
epoch=2, loss=0.2527
epoch=3, loss=0.1836
epoch=4, loss=0.1486
epoch=5, loss=0.1288
valid [full], NDCG@5: 0.3332, HR@5: 0.4863, NDCG@10: 0.4342, HR@10: 0.7879, MRR: 0.3404
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5622, NDCG@10: 0.5664, HR@10: 0.5942, MRR: 0.5735
test [full], NDCG@5: 0.2762, HR@5: 0.4801, NDCG@10: 0.3083, HR@10: 0.5748, MRR: 0.2475
test [sampled], NDCG@5: 0.3947, HR@5: 0.4062, NDCG@10: 0.4352, HR@10: 0.5358, MRR: 0.4298
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/sasrec_best.pth
epoch=6, loss=0.1146
epoch=7, loss=0.1086
epoch=8, loss=0.1031
epoch=9, loss=0.1006
epoch=10, loss=0.0969
valid [full], NDCG@5: 0.3235, HR@5: 0.4553, NDCG@10: 0.4091, HR@10: 0.7213, MRR: 0.3377
valid [sampled], NDCG@5: 0.5556, HR@5: 0.5578, NDCG@10: 0.5622, HR@10: 0.5787, MRR: 0.5738
test [full], NDCG@5: 0.2899, HR@5: 0.4525, NDCG@10: 0.3853, HR@10: 0.7457, MRR: 0.2948
test [sampled], NDCG@5: 0.4303, HR@5: 0.4972, NDCG@10: 0.4952, HR@10: 0.6974, MRR: 0.4519
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0957
epoch=12, loss=0.0946
epoch=13, loss=0.0910
epoch=14, loss=0.0868
epoch=15, loss=0.0901
valid [full], NDCG@5: 0.3250, HR@5: 0.4800, NDCG@10: 0.4215, HR@10: 0.7719, MRR: 0.3370
valid [sampled], NDCG@5: 0.5618, HR@5: 0.5683, NDCG@10: 0.5777, HR@10: 0.6190, MRR: 0.5814
test [full], NDCG@5: 0.3346, HR@5: 0.5988, NDCG@10: 0.4712, HR@10: 0.9974, MRR: 0.3090
test [sampled], NDCG@5: 0.5143, HR@5: 0.5929, NDCG@10: 0.5899, HR@10: 0.8241, MRR: 0.5288
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0890
epoch=17, loss=0.0848
epoch=18, loss=0.0844
epoch=19, loss=0.0846
epoch=20, loss=0.0822
valid [full], NDCG@5: 0.3694, HR@5: 0.5826, NDCG@10: 0.4344, HR@10: 0.7771, MRR: 0.3494
valid [sampled], NDCG@5: 0.5621, HR@5: 0.5724, NDCG@10: 0.5790, HR@10: 0.6260, MRR: 0.5787
test [full], NDCG@5: 0.3553, HR@5: 0.6182, NDCG@10: 0.4868, HR@10: 0.9968, MRR: 0.3315
test [sampled], NDCG@5: 0.5350, HR@5: 0.6079, NDCG@10: 0.6052, HR@10: 0.8227, MRR: 0.5484
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/sasrec_best.pth
epoch=21, loss=0.0822
epoch=22, loss=0.0826
epoch=23, loss=0.0838
epoch=24, loss=0.0832
epoch=25, loss=0.0828
valid [full], NDCG@5: 0.4230, HR@5: 0.6410, NDCG@10: 0.5313, HR@10: 0.9910, MRR: 0.3938
valid [sampled], NDCG@5: 0.5646, HR@5: 0.5764, NDCG@10: 0.5795, HR@10: 0.6227, MRR: 0.5799
test [full], NDCG@5: 0.5143, HR@5: 0.8691, NDCG@10: 0.5595, HR@10: 0.9989, MRR: 0.4197
test [sampled], NDCG@5: 0.6072, HR@5: 0.6197, NDCG@10: 0.6488, HR@10: 0.7532, MRR: 0.6338
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/sasrec_best.pth
epoch=26, loss=0.0821
epoch=27, loss=0.0822
epoch=28, loss=0.0810
epoch=29, loss=0.0819
epoch=30, loss=0.0799
valid [full], NDCG@5: 0.4018, HR@5: 0.6131, NDCG@10: 0.5213, HR@10: 0.9879, MRR: 0.3820
valid [sampled], NDCG@5: 0.5556, HR@5: 0.5605, NDCG@10: 0.5662, HR@10: 0.5941, MRR: 0.5723
test [full], NDCG@5: 0.4988, HR@5: 0.8809, NDCG@10: 0.5395, HR@10: 0.9986, MRR: 0.3945
test [sampled], NDCG@5: 0.6382, HR@5: 0.6843, NDCG@10: 0.6825, HR@10: 0.8199, MRR: 0.6498
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0798
epoch=32, loss=0.0796
epoch=33, loss=0.0789
epoch=34, loss=0.0781
epoch=35, loss=0.0812
valid [full], NDCG@5: 0.4075, HR@5: 0.6361, NDCG@10: 0.5259, HR@10: 0.9887, MRR: 0.3857
valid [sampled], NDCG@5: 0.5558, HR@5: 0.5671, NDCG@10: 0.5697, HR@10: 0.6106, MRR: 0.5716
test [full], NDCG@5: 0.3759, HR@5: 0.6276, NDCG@10: 0.5045, HR@10: 0.9985, MRR: 0.3529
test [sampled], NDCG@5: 0.7476, HR@5: 0.7563, NDCG@10: 0.7685, HR@10: 0.8226, MRR: 0.7605
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0791
epoch=37, loss=0.0785
epoch=38, loss=0.0793
epoch=39, loss=0.0774
epoch=40, loss=0.0778
valid [full], NDCG@5: 0.4097, HR@5: 0.6179, NDCG@10: 0.5311, HR@10: 0.9904, MRR: 0.3926
valid [sampled], NDCG@5: 0.5566, HR@5: 0.5675, NDCG@10: 0.5713, HR@10: 0.6132, MRR: 0.5741
test [full], NDCG@5: 0.4201, HR@5: 0.6353, NDCG@10: 0.5485, HR@10: 0.9995, MRR: 0.4089
test [sampled], NDCG@5: 0.7149, HR@5: 0.7204, NDCG@10: 0.7389, HR@10: 0.7973, MRR: 0.7328
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0813
epoch=42, loss=0.0782
epoch=43, loss=0.0796
epoch=44, loss=0.0780
epoch=45, loss=0.0795
valid [full], NDCG@5: 0.4119, HR@5: 0.6152, NDCG@10: 0.5343, HR@10: 0.9937, MRR: 0.3959
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5689, NDCG@10: 0.5718, HR@10: 0.6229, MRR: 0.5708
test [full], NDCG@5: 0.4235, HR@5: 0.6315, NDCG@10: 0.5508, HR@10: 0.9991, MRR: 0.4126
test [sampled], NDCG@5: 0.7341, HR@5: 0.7460, NDCG@10: 0.7602, HR@10: 0.8286, MRR: 0.7485
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0778
epoch=47, loss=0.0787
epoch=48, loss=0.0783
epoch=49, loss=0.0773
epoch=50, loss=0.0791
valid [full], NDCG@5: 0.4184, HR@5: 0.6288, NDCG@10: 0.5351, HR@10: 0.9859, MRR: 0.3988
valid [sampled], NDCG@5: 0.5307, HR@5: 0.5334, NDCG@10: 0.5402, HR@10: 0.5640, MRR: 0.5508
test [full], NDCG@5: 0.4462, HR@5: 0.6310, NDCG@10: 0.5746, HR@10: 0.9991, MRR: 0.4445
test [sampled], NDCG@5: 0.7589, HR@5: 0.7613, NDCG@10: 0.7747, HR@10: 0.8121, MRR: 0.7735
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_v3_ml50_do025_seed7_ndcg5/sasrec_last.pth

## Rebuild result table from run folders

This avoids schema issues in `experiment_index.csv` and lets us combine old and new runs safely.

In [18]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    for run_dir in Path(output_dir).iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

## `NDCG@10` sanity check summary

In [19]:
ndcg10_targets = [
    'anchor_v3_bpi_short_context_seed42',
    'anchor_v3_bpi_short_context_seed2024',
    'anchor_v3_bpi_short_context_seed7',
    'refine_v3_ml50_do025_seed42',
    'refine_v3_ml50_do025_seed2024',
    'refine_v3_ml50_do025_seed7',
]

df10 = rebuild_df(NDCG10_OUTPUT_DIR)
df10_sc = df10[df10['run_name'].isin(ndcg10_targets)].copy()
df10_sc = df10_sc.sort_values(['run_name']).reset_index(drop=True)
df10_sc[[
    'run_name', 'seed',
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]]

,run_name,seed,best_valid_full_ndcg@10,best_test_full_ndcg@10,best_valid_full_ndcg@5,best_test_full_ndcg@5,best_valid_full_mrr,best_test_full_mrr,best_valid_sampled_ndcg@10,best_test_sampled_ndcg@10,best_valid_sampled_ndcg@5,best_test_sampled_ndcg@5,best_valid_sampled_mrr,best_test_sampled_mrr
0,anchor_v3_bpi_short_context_seed2024,2024,0.490568,0.475035,0.336216,0.403287,0.348531,0.317342,0.581044,0.773536,0.561285,0.752792,0.581029,0.762922
1,anchor_v3_bpi_short_context_seed42,42,0.483317,0.469208,0.331368,0.318109,0.338438,0.310513,0.581774,0.818501,0.556769,0.795135,0.579600,0.804634
2,anchor_v3_bpi_short_context_seed7,7,0.483947,0.542173,0.360762,0.490305,0.356064,0.405136,0.589005,0.704285,0.561976,0.652995,0.584501,0.662476
3,refine_v3_ml50_do025_seed2024,2024,0.500475,0.460943,0.376172,0.337719,0.356303,0.299817,0.569319,0.821949,0.553469,0.811153,0.569866,0.816608
4,refine_v3_ml50_do025_seed42,42,0.512117,0.546236,0.387751,0.416791,0.372049,0.406292,0.550634,0.820534,0.541576,0.809862,0.557796,0.816182
5,refine_v3_ml50_do025_seed7,7,0.535115,0.574559,0.418443,0.446163,0.398813,0.444456,0.540185,0.774719,0.530723,0.758924,0.550779,0.773473

In [20]:
df10_sc['candidate'] = df10_sc['run_name'].apply(
    lambda x: 'anchor_short_context' if 'anchor_v3_bpi_short_context' in x else 'refine_ml50_do025'
)
summary10 = df10_sc.groupby('candidate')[[
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary10

                     best_valid_full_ndcg@10           best_test_full_ndcg@10  \
                                        mean       std                   mean
candidate
anchor_short_context                0.485944  0.004016               0.495472
refine_ml50_do025                   0.515902  0.017627               0.527246

                               best_valid_full_ndcg@5            \
                           std                   mean       std
candidate
anchor_short_context  0.040549               0.342782  0.015758
refine_ml50_do025     0.059141               0.394122  0.021844

                     best_test_full_ndcg@5           best_valid_full_mrr  \
                                      mean       std                mean
candidate
anchor_short_context              0.403900  0.086100            0.347678
refine_ml50_do025                 0.400224  0.056088            0.375722

                                ... best_test_sampled_ndcg@10            \
                           std  ...                      mean       std
candidate                       ...
anchor_short_context  0.008844  ...                  0.765441  0.057537
refine_ml50_do025     0.021492  ...                  0.805734  0.026869

                     best_valid_sampled_ndcg@5            \
                                          mean       std
candidate
anchor_short_context                  0.560010  0.002828
refine_ml50_do025                     0.541923  0.011377

                     best_test_sampled_ndcg@5            \
                                         mean       std
candidate
anchor_short_context                 0.733641  0.072980
refine_ml50_do025                    0.793313  0.029789

                     best_valid_sampled_mrr           best_test_sampled_mrr  \
                                       mean       std                  mean
candidate
anchor_short_context                0.58171  0.002520              0.743344
refine_ml50_do025                   0.55948  0.009654              0.802087


                           std
candidate
anchor_short_context  0.073073
refine_ml50_do025     0.024782

[2 rows x 24 columns]

Interpretation guide for `NDCG@10`:
- compare mean/std of `best_valid_full_ndcg@10` and `best_test_full_ndcg@10`
- then check whether `@5`, sampled, and MRR show a similar trend

## `NDCG@5` sanity check summary

In [21]:
ndcg5_targets = [
    'anchor_v3_bpi_short_context_seed42_ndcg5',
    'anchor_v3_bpi_short_context_seed2024_ndcg5',
    'anchor_v3_bpi_short_context_seed7_ndcg5',
    'refine_v3_ml50_do025_seed42_ndcg5',
    'refine_v3_ml50_do025_seed2024_ndcg5',
    'refine_v3_ml50_do025_seed7_ndcg5',
]

df5 = rebuild_df(NDCG5_OUTPUT_DIR)
df5_sc = df5[df5['run_name'].isin(ndcg5_targets)].copy()
df5_sc = df5_sc.sort_values(['run_name']).reset_index(drop=True)
df5_sc[[
    'run_name', 'seed',
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]]

,run_name,seed,best_valid_full_ndcg@5,best_test_full_ndcg@5,best_valid_full_ndcg@10,best_test_full_ndcg@10,best_valid_full_mrr,best_test_full_mrr,best_valid_sampled_ndcg@5,best_test_sampled_ndcg@5,best_valid_sampled_ndcg@10,best_test_sampled_ndcg@10,best_valid_sampled_mrr,best_test_sampled_mrr
0,anchor_v3_bpi_short_context_seed2024_ndcg5,2024,0.357948,0.375725,0.479559,0.505049,0.356380,0.370158,0.557876,0.512325,0.559503,0.527502,0.573449,0.532365
1,anchor_v3_bpi_short_context_seed42_ndcg5,42,0.331368,0.318109,0.483317,0.469208,0.338438,0.310513,0.556769,0.795135,0.581774,0.818501,0.579600,0.804634
2,anchor_v3_bpi_short_context_seed7_ndcg5,7,0.427728,0.527406,0.465877,0.561206,0.381493,0.424770,0.561732,0.818276,0.583188,0.833809,0.582869,0.829311
3,refine_v3_ml50_do025_seed2024_ndcg5,2024,0.376172,0.337719,0.500475,0.460943,0.356303,0.299817,0.553469,0.811153,0.569319,0.821949,0.569866,0.816608
4,refine_v3_ml50_do025_seed42_ndcg5,42,0.387751,0.416791,0.512117,0.546236,0.372049,0.406292,0.541576,0.809862,0.550634,0.820534,0.557796,0.816182
5,refine_v3_ml50_do025_seed7_ndcg5,7,0.422964,0.514319,0.531336,0.559463,0.393817,0.419656,0.564573,0.607155,0.579456,0.648849,0.579905,0.633788

In [22]:
df5_sc['candidate'] = df5_sc['run_name'].apply(
    lambda x: 'anchor_short_context' if 'anchor_v3_bpi_short_context' in x else 'refine_ml50_do025'
)
summary5 = df5_sc.groupby('candidate')[[
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary5

                     best_valid_full_ndcg@5           best_test_full_ndcg@5  \
                                       mean       std                  mean
candidate
anchor_short_context               0.372348  0.049768              0.407080
refine_ml50_do025                  0.395629  0.024370              0.422943

                               best_valid_full_ndcg@10            \
                           std                    mean       std
candidate
anchor_short_context  0.108114                0.476251  0.009179
refine_ml50_do025     0.088461                0.514643  0.015584

                     best_test_full_ndcg@10           best_valid_full_mrr  \
                                       mean       std                mean
candidate
anchor_short_context               0.511821  0.046371            0.358770
refine_ml50_do025                  0.522214  0.053473            0.374056

                                ... best_test_sampled_ndcg@5            \
                           std  ...                     mean       std
candidate                       ...
anchor_short_context  0.021627  ...                 0.708578  0.170354
refine_ml50_do025     0.018837  ...                 0.742723  0.117407

                     best_valid_sampled_ndcg@10            \
                                           mean       std
candidate
anchor_short_context                   0.574822  0.013285
refine_ml50_do025                      0.566470  0.014621

                     best_test_sampled_ndcg@10            \
                                          mean       std
candidate
anchor_short_context                  0.726604  0.172597
refine_ml50_do025                     0.763777  0.099533

                     best_valid_sampled_mrr           best_test_sampled_mrr  \
                                       mean       std                  mean
candidate
anchor_short_context               0.578639  0.004783              0.722103
refine_ml50_do025                  0.569189  0.011070              0.755526


                           std
candidate
anchor_short_context  0.164781
refine_ml50_do025     0.105428

[2 rows x 24 columns]

Interpretation guide for `NDCG@5`:
- compare mean/std of `best_valid_full_ndcg@5` and `best_test_full_ndcg@5`
- then check whether `@10`, sampled, and MRR show a similar trend