# SASRec BPI2012 Colab Train (Eval Fix)

Colab notebook for re-running the selected SASRec baseline settings after fixing the evaluation code.

This notebook runs both model-selection criteria:
- `full_valid_ndcg@10`
- `full_valid_ndcg@5`

Output directories:
- `sasrec_bpi2012_ndcg10`
- `sasrec_bpi2012_ndcg5`

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('NDCG10_OUTPUT_DIR:', NDCG10_OUTPUT_DIR)
print('NDCG5_OUTPUT_DIR:', NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$NDCG10_OUTPUT_DIR"
!mkdir -p "$NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction

/content
/content/time-aware-behavior-prediction

In [6]:
# If you need the latest code from GitHub, uncomment below.
%cd /content/time-aware-behavior-prediction
!git pull

/content/time-aware-behavior-prediction
Already up to date.

In [7]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [8]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [9]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [10]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Planned runs

Selected baseline runs to re-run after the evaluation fix:
- `anchor_pd_s42`
- `anchor_ml100_s42`
- `anchor_ml50_s42`
- `anchor_ml20_s42`
- `refine_ml50_do030_s42`
- `refine_ml50_do035_s42`
- `refine_ml50_do025_s42`
- `refine_ml50_do025_s2024`
- `refine_ml50_do030_s2024`
- `refine_ml75_do030_s42`
- `refine_ml100_do030_s42`

In [11]:
from pathlib import Path

planned_run_names = [
    'anchor_pd_s42',
    'anchor_ml100_s42',
    'anchor_ml50_s42',
    'anchor_ml20_s42',
    'refine_ml50_do030_s42',
    'refine_ml50_do035_s42',
    'refine_ml50_do025_s42',
    'refine_ml50_do025_s2024',
    'refine_ml50_do030_s2024',
    'refine_ml75_do030_s42',
    'refine_ml100_do030_s42',
]

for label, output_dir in [('NDCG@10', Path(NDCG10_OUTPUT_DIR)), ('NDCG@5', Path(NDCG5_OUTPUT_DIR))]:
    print('=' * 80)
    print(label)
    for run_name in planned_run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
NDCG@10
anchor_pd_s42 OK
anchor_ml100_s42 OK
anchor_ml50_s42 OK
anchor_ml20_s42 OK
refine_ml50_do030_s42 OK
refine_ml50_do035_s42 OK
refine_ml50_do025_s42 OK
refine_ml50_do025_s2024 OK
refine_ml50_do030_s2024 OK
refine_ml75_do030_s42 OK
refine_ml100_do030_s42 OK
================================================================================
NDCG@5
anchor_pd_s42 OK
anchor_ml100_s42 OK
anchor_ml50_s42 OK
anchor_ml20_s42 OK
refine_ml50_do030_s42 OK
refine_ml50_do035_s42 OK
refine_ml50_do025_s42 OK
refine_ml50_do025_s2024 OK
refine_ml50_do030_s2024 OK
refine_ml75_do030_s42 OK
refine_ml100_do030_s42 OK

## Train runs with `selection_metric = full_valid_ndcg@10`

### anchor_pd_s42

In [12]:
!python src/train_sasrec.py \
  --run_name anchor_pd_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 200 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42
epoch=1, loss=0.4974
epoch=2, loss=0.2282
epoch=3, loss=0.1655
epoch=4, loss=0.1360
epoch=5, loss=0.1199
valid [full], NDCG@5: 0.6457, HR@5: 0.7414, NDCG@10: 0.7226, HR@10: 0.9828, MRR: 0.6469
valid [sampled], NDCG@5: 0.5632, HR@5: 0.5772, NDCG@10: 0.5810, HR@10: 0.6324, MRR: 0.5772
test [full], NDCG@5: 0.5359, HR@5: 0.7313, NDCG@10: 0.6238, HR@10: 1.0000, MRR: 0.5074
test [sampled], NDCG@5: 0.1698, HR@5: 0.1750, NDCG@10: 0.2127, HR@10: 0.3140, MRR: 0.2129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/sasrec_best.pth
epoch=6, loss=0.1124
epoch=7, loss=0.1030
epoch=8, loss=0.0992
epoch=9, loss=0.0966
epoch=10, loss=0.0923
valid [full], NDCG@5: 0.6980, HR@5: 0.8756, NDCG@10: 0.7293, HR@10: 0.9753, MRR: 0.6558
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5715, NDCG@10: 0.5721, HR@10: 0.6113, MRR: 0.5756
test [full], NDCG@5: 0.6804, HR@5: 0.8952, NDCG@10: 0.7154, HR@10: 1.0000, MRR: 0.6228
test [sampled], NDCG@5: 0.1679, HR@5: 0.1809, NDCG@10: 0.2285, HR@10: 0.3746, MRR: 0.2214
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/sasrec_best.pth
epoch=11, loss=0.0916
epoch=12, loss=0.0896
epoch=13, loss=0.0875
epoch=14, loss=0.0869
epoch=15, loss=0.0875
valid [full], NDCG@5: 0.6519, HR@5: 0.7713, NDCG@10: 0.7199, HR@10: 0.9776, MRR: 0.6447
valid [sampled], NDCG@5: 0.5652, HR@5: 0.5730, NDCG@10: 0.5749, HR@10: 0.6033, MRR: 0.5801
test [full], NDCG@5: 0.6956, HR@5: 0.9285, NDCG@10: 0.7188, HR@10: 1.0000, MRR: 0.6260
test [sampled], NDCG@5: 0.1543, HR@5: 0.1608, NDCG@10: 0.2141, HR@10: 0.3545, MRR: 0.2126
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0873
epoch=17, loss=0.0838
epoch=18, loss=0.0833
epoch=19, loss=0.0829
epoch=20, loss=0.0818
valid [full], NDCG@5: 0.6580, HR@5: 0.7842, NDCG@10: 0.7207, HR@10: 0.9760, MRR: 0.6466
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5650, NDCG@10: 0.5669, HR@10: 0.5898, MRR: 0.5744
test [full], NDCG@5: 0.7722, HR@5: 0.9157, NDCG@10: 0.8002, HR@10: 1.0000, MRR: 0.7365
test [sampled], NDCG@5: 0.2045, HR@5: 0.2675, NDCG@10: 0.2660, HR@10: 0.4576, MRR: 0.2389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0816
epoch=22, loss=0.0815
epoch=23, loss=0.0812
epoch=24, loss=0.0797
epoch=25, loss=0.0815
valid [full], NDCG@5: 0.6420, HR@5: 0.7389, NDCG@10: 0.7180, HR@10: 0.9755, MRR: 0.6442
valid [sampled], NDCG@5: 0.5542, HR@5: 0.5650, NDCG@10: 0.5660, HR@10: 0.6010, MRR: 0.5681
test [full], NDCG@5: 0.7003, HR@5: 0.9287, NDCG@10: 0.7239, HR@10: 1.0000, MRR: 0.6322
test [sampled], NDCG@5: 0.1743, HR@5: 0.1864, NDCG@10: 0.2316, HR@10: 0.3717, MRR: 0.2295
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0795
epoch=27, loss=0.0796
epoch=28, loss=0.0797
epoch=29, loss=0.0810
epoch=30, loss=0.0797
valid [full], NDCG@5: 0.6878, HR@5: 0.8375, NDCG@10: 0.7328, HR@10: 0.9764, MRR: 0.6608
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5686, NDCG@10: 0.5719, HR@10: 0.6086, MRR: 0.5760
test [full], NDCG@5: 0.7415, HR@5: 0.9454, NDCG@10: 0.7593, HR@10: 1.0000, MRR: 0.6779
test [sampled], NDCG@5: 0.1989, HR@5: 0.2094, NDCG@10: 0.2660, HR@10: 0.4256, MRR: 0.2574
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/sasrec_best.pth
epoch=31, loss=0.0793
epoch=32, loss=0.0776
epoch=33, loss=0.0798
epoch=34, loss=0.0773
epoch=35, loss=0.0776
valid [full], NDCG@5: 0.6686, HR@5: 0.8068, NDCG@10: 0.7166, HR@10: 0.9565, MRR: 0.6478
valid [sampled], NDCG@5: 0.5600, HR@5: 0.5681, NDCG@10: 0.5722, HR@10: 0.6062, MRR: 0.5760
test [full], NDCG@5: 0.7990, HR@5: 0.9320, NDCG@10: 0.8210, HR@10: 1.0000, MRR: 0.7629
test [sampled], NDCG@5: 0.2178, HR@5: 0.2824, NDCG@10: 0.2869, HR@10: 0.4975, MRR: 0.2541
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0784
epoch=37, loss=0.0769
epoch=38, loss=0.0776
epoch=39, loss=0.0787
epoch=40, loss=0.0761
valid [full], NDCG@5: 0.6495, HR@5: 0.7723, NDCG@10: 0.7091, HR@10: 0.9544, MRR: 0.6396
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5631, NDCG@10: 0.5661, HR@10: 0.5856, MRR: 0.5746
test [full], NDCG@5: 0.8664, HR@5: 0.9372, NDCG@10: 0.8872, HR@10: 1.0000, MRR: 0.8518
test [sampled], NDCG@5: 0.3147, HR@5: 0.3903, NDCG@10: 0.3813, HR@10: 0.5955, MRR: 0.3403
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0776
epoch=42, loss=0.0766
epoch=43, loss=0.0785
epoch=44, loss=0.0780
epoch=45, loss=0.0766
valid [full], NDCG@5: 0.6504, HR@5: 0.7483, NDCG@10: 0.7172, HR@10: 0.9515, MRR: 0.6511
valid [sampled], NDCG@5: 0.5626, HR@5: 0.5739, NDCG@10: 0.5767, HR@10: 0.6172, MRR: 0.5762
test [full], NDCG@5: 0.8764, HR@5: 0.9285, NDCG@10: 0.8990, HR@10: 1.0000, MRR: 0.8677
test [sampled], NDCG@5: 0.3319, HR@5: 0.4129, NDCG@10: 0.4057, HR@10: 0.6395, MRR: 0.3557
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0748
epoch=47, loss=0.0771
epoch=48, loss=0.0759
epoch=49, loss=0.0764
epoch=50, loss=0.0767
valid [full], NDCG@5: 0.6473, HR@5: 0.7491, NDCG@10: 0.7143, HR@10: 0.9541, MRR: 0.6466
valid [sampled], NDCG@5: 0.5569, HR@5: 0.5647, NDCG@10: 0.5671, HR@10: 0.5966, MRR: 0.5712
test [full], NDCG@5: 0.7559, HR@5: 0.9178, NDCG@10: 0.7825, HR@10: 1.0000, MRR: 0.7128
test [sampled], NDCG@5: 0.2602, HR@5: 0.2904, NDCG@10: 0.3051, HR@10: 0.4314, MRR: 0.3003
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_pd_s42/sasrec_last.pth

### anchor_ml100_s42

In [13]:
!python src/train_sasrec.py \
  --run_name anchor_ml100_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 100 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42
epoch=1, loss=0.4891
epoch=2, loss=0.2275
epoch=3, loss=0.1620
epoch=4, loss=0.1320
epoch=5, loss=0.1166
valid [full], NDCG@5: 0.6230, HR@5: 0.6725, NDCG@10: 0.7174, HR@10: 0.9646, MRR: 0.6482
valid [sampled], NDCG@5: 0.5689, HR@5: 0.5814, NDCG@10: 0.5844, HR@10: 0.6298, MRR: 0.5812
test [full], NDCG@5: 0.4660, HR@5: 0.6063, NDCG@10: 0.5864, HR@10: 0.9842, MRR: 0.4681
test [sampled], NDCG@5: 0.1427, HR@5: 0.1480, NDCG@10: 0.1838, HR@10: 0.2807, MRR: 0.1835
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/sasrec_best.pth
epoch=6, loss=0.1066
epoch=7, loss=0.1002
epoch=8, loss=0.0960
epoch=9, loss=0.0940
epoch=10, loss=0.0905
valid [full], NDCG@5: 0.6381, HR@5: 0.7276, NDCG@10: 0.7152, HR@10: 0.9618, MRR: 0.6442
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5645, NDCG@10: 0.5698, HR@10: 0.6207, MRR: 0.5673
test [full], NDCG@5: 0.6412, HR@5: 0.8975, NDCG@10: 0.6749, HR@10: 0.9999, MRR: 0.5676
test [sampled], NDCG@5: 0.1367, HR@5: 0.1505, NDCG@10: 0.2033, HR@10: 0.3638, MRR: 0.1915
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0902
epoch=12, loss=0.0881
epoch=13, loss=0.0868
epoch=14, loss=0.0862
epoch=15, loss=0.0862
valid [full], NDCG@5: 0.6397, HR@5: 0.7314, NDCG@10: 0.7072, HR@10: 0.9410, MRR: 0.6430
valid [sampled], NDCG@5: 0.5669, HR@5: 0.5767, NDCG@10: 0.5785, HR@10: 0.6128, MRR: 0.5804
test [full], NDCG@5: 0.6873, HR@5: 0.9343, NDCG@10: 0.7093, HR@10: 1.0000, MRR: 0.6130
test [sampled], NDCG@5: 0.1339, HR@5: 0.1442, NDCG@10: 0.1866, HR@10: 0.3143, MRR: 0.1918
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0865
epoch=17, loss=0.0831
epoch=18, loss=0.0827
epoch=19, loss=0.0836
epoch=20, loss=0.0820
valid [full], NDCG@5: 0.6623, HR@5: 0.7759, NDCG@10: 0.7153, HR@10: 0.9405, MRR: 0.6522
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5627, NDCG@10: 0.5716, HR@10: 0.6059, MRR: 0.5756
test [full], NDCG@5: 0.7503, HR@5: 0.9453, NDCG@10: 0.7692, HR@10: 0.9999, MRR: 0.6916
test [sampled], NDCG@5: 0.1965, HR@5: 0.2178, NDCG@10: 0.2648, HR@10: 0.4356, MRR: 0.2507
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0816
epoch=22, loss=0.0814
epoch=23, loss=0.0807
epoch=24, loss=0.0797
epoch=25, loss=0.0815
valid [full], NDCG@5: 0.6469, HR@5: 0.7552, NDCG@10: 0.7106, HR@10: 0.9535, MRR: 0.6410
valid [sampled], NDCG@5: 0.5361, HR@5: 0.5450, NDCG@10: 0.5522, HR@10: 0.5956, MRR: 0.5534
test [full], NDCG@5: 0.7512, HR@5: 0.9433, NDCG@10: 0.7703, HR@10: 1.0000, MRR: 0.6925
test [sampled], NDCG@5: 0.1606, HR@5: 0.1883, NDCG@10: 0.2420, HR@10: 0.4479, MRR: 0.2180
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0794
epoch=27, loss=0.0799
epoch=28, loss=0.0796
epoch=29, loss=0.0809
epoch=30, loss=0.0803
valid [full], NDCG@5: 0.6648, HR@5: 0.7658, NDCG@10: 0.7313, HR@10: 0.9764, MRR: 0.6604
valid [sampled], NDCG@5: 0.5626, HR@5: 0.5767, NDCG@10: 0.5818, HR@10: 0.6367, MRR: 0.5776
test [full], NDCG@5: 0.7804, HR@5: 0.9199, NDCG@10: 0.8059, HR@10: 1.0000, MRR: 0.7415
test [sampled], NDCG@5: 0.2383, HR@5: 0.2755, NDCG@10: 0.3122, HR@10: 0.5090, MRR: 0.2848
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/sasrec_best.pth
epoch=31, loss=0.0789
epoch=32, loss=0.0775
epoch=33, loss=0.0793
epoch=34, loss=0.0765
epoch=35, loss=0.0782
valid [full], NDCG@5: 0.6577, HR@5: 0.7650, NDCG@10: 0.7194, HR@10: 0.9567, MRR: 0.6515
valid [sampled], NDCG@5: 0.5563, HR@5: 0.5668, NDCG@10: 0.5758, HR@10: 0.6280, MRR: 0.5732
test [full], NDCG@5: 0.7356, HR@5: 0.9222, NDCG@10: 0.7609, HR@10: 1.0000, MRR: 0.6833
test [sampled], NDCG@5: 0.2287, HR@5: 0.2579, NDCG@10: 0.2721, HR@10: 0.3945, MRR: 0.2712
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0781
epoch=37, loss=0.0770
epoch=38, loss=0.0777
epoch=39, loss=0.0778
epoch=40, loss=0.0761
valid [full], NDCG@5: 0.6486, HR@5: 0.7627, NDCG@10: 0.7103, HR@10: 0.9549, MRR: 0.6412
valid [sampled], NDCG@5: 0.5527, HR@5: 0.5577, NDCG@10: 0.5635, HR@10: 0.5918, MRR: 0.5696
test [full], NDCG@5: 0.7182, HR@5: 0.9127, NDCG@10: 0.7462, HR@10: 1.0000, MRR: 0.6686
test [sampled], NDCG@5: 0.2474, HR@5: 0.2710, NDCG@10: 0.2822, HR@10: 0.3796, MRR: 0.2838
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0779
epoch=42, loss=0.0778
epoch=43, loss=0.0784
epoch=44, loss=0.0776
epoch=45, loss=0.0769
valid [full], NDCG@5: 0.6814, HR@5: 0.8167, NDCG@10: 0.7259, HR@10: 0.9556, MRR: 0.6596
valid [sampled], NDCG@5: 0.5553, HR@5: 0.5644, NDCG@10: 0.5737, HR@10: 0.6222, MRR: 0.5734
test [full], NDCG@5: 0.7503, HR@5: 0.9131, NDCG@10: 0.7775, HR@10: 1.0000, MRR: 0.7062
test [sampled], NDCG@5: 0.3053, HR@5: 0.3213, NDCG@10: 0.3380, HR@10: 0.4258, MRR: 0.3456
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0745
epoch=47, loss=0.0766
epoch=48, loss=0.0758
epoch=49, loss=0.0765
epoch=50, loss=0.0759
valid [full], NDCG@5: 0.6650, HR@5: 0.7531, NDCG@10: 0.7308, HR@10: 0.9546, MRR: 0.6665
valid [sampled], NDCG@5: 0.5545, HR@5: 0.5610, NDCG@10: 0.5765, HR@10: 0.6311, MRR: 0.5742
test [full], NDCG@5: 0.7489, HR@5: 0.9164, NDCG@10: 0.7753, HR@10: 1.0000, MRR: 0.7028
test [sampled], NDCG@5: 0.2856, HR@5: 0.3045, NDCG@10: 0.3206, HR@10: 0.4154, MRR: 0.3265
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml100_s42/sasrec_last.pth

### anchor_ml50_s42

In [14]:
!python src/train_sasrec.py \
  --run_name anchor_ml50_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42
epoch=1, loss=0.4793
epoch=2, loss=0.2166
epoch=3, loss=0.1564
epoch=4, loss=0.1245
epoch=5, loss=0.1127
valid [full], NDCG@5: 0.6566, HR@5: 0.7705, NDCG@10: 0.7221, HR@10: 0.9808, MRR: 0.6467
valid [sampled], NDCG@5: 0.5561, HR@5: 0.5710, NDCG@10: 0.5758, HR@10: 0.6326, MRR: 0.5713
test [full], NDCG@5: 0.4875, HR@5: 0.6521, NDCG@10: 0.5959, HR@10: 0.9999, MRR: 0.4741
test [sampled], NDCG@5: 0.1370, HR@5: 0.1437, NDCG@10: 0.1829, HR@10: 0.2915, MRR: 0.1796
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/sasrec_best.pth
epoch=6, loss=0.1045
epoch=7, loss=0.1006
epoch=8, loss=0.0948
epoch=9, loss=0.0927
epoch=10, loss=0.0919
valid [full], NDCG@5: 0.6540, HR@5: 0.7700, NDCG@10: 0.7208, HR@10: 0.9735, MRR: 0.6471
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5737, NDCG@10: 0.5728, HR@10: 0.6132, MRR: 0.5738
test [full], NDCG@5: 0.6773, HR@5: 0.9070, NDCG@10: 0.7068, HR@10: 1.0000, MRR: 0.6098
test [sampled], NDCG@5: 0.1461, HR@5: 0.1717, NDCG@10: 0.2125, HR@10: 0.3837, MRR: 0.1974
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0904
epoch=12, loss=0.0884
epoch=13, loss=0.0869
epoch=14, loss=0.0868
epoch=15, loss=0.0873
valid [full], NDCG@5: 0.6948, HR@5: 0.8606, NDCG@10: 0.7322, HR@10: 0.9777, MRR: 0.6585
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5713, NDCG@10: 0.5752, HR@10: 0.6215, MRR: 0.5770
test [full], NDCG@5: 0.7971, HR@5: 0.9206, NDCG@10: 0.8220, HR@10: 1.0000, MRR: 0.7641
test [sampled], NDCG@5: 0.2187, HR@5: 0.2901, NDCG@10: 0.2918, HR@10: 0.5167, MRR: 0.2530
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/sasrec_best.pth
epoch=16, loss=0.0839
epoch=17, loss=0.0821
epoch=18, loss=0.0825
epoch=19, loss=0.0827
epoch=20, loss=0.0822
valid [full], NDCG@5: 0.6654, HR@5: 0.7984, NDCG@10: 0.7239, HR@10: 0.9760, MRR: 0.6502
valid [sampled], NDCG@5: 0.5583, HR@5: 0.5677, NDCG@10: 0.5711, HR@10: 0.6075, MRR: 0.5738
test [full], NDCG@5: 0.7567, HR@5: 0.8934, NDCG@10: 0.7911, HR@10: 1.0000, MRR: 0.7239
test [sampled], NDCG@5: 0.1517, HR@5: 0.2231, NDCG@10: 0.2319, HR@10: 0.4725, MRR: 0.1909
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0798
epoch=22, loss=0.0806
epoch=23, loss=0.0809
epoch=24, loss=0.0806
epoch=25, loss=0.0796
valid [full], NDCG@5: 0.6334, HR@5: 0.7361, NDCG@10: 0.7038, HR@10: 0.9503, MRR: 0.6338
valid [sampled], NDCG@5: 0.5277, HR@5: 0.5397, NDCG@10: 0.5448, HR@10: 0.5923, MRR: 0.5438
test [full], NDCG@5: 0.7536, HR@5: 0.9168, NDCG@10: 0.7793, HR@10: 1.0000, MRR: 0.7066
test [sampled], NDCG@5: 0.1976, HR@5: 0.2314, NDCG@10: 0.2765, HR@10: 0.4808, MRR: 0.2484
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0790
epoch=27, loss=0.0806
epoch=28, loss=0.0789
epoch=29, loss=0.0807
epoch=30, loss=0.0798
valid [full], NDCG@5: 0.6578, HR@5: 0.7867, NDCG@10: 0.7196, HR@10: 0.9764, MRR: 0.6446
valid [sampled], NDCG@5: 0.5435, HR@5: 0.5470, NDCG@10: 0.5548, HR@10: 0.5830, MRR: 0.5619
test [full], NDCG@5: 0.8511, HR@5: 0.9206, NDCG@10: 0.8755, HR@10: 1.0000, MRR: 0.8369
test [sampled], NDCG@5: 0.2673, HR@5: 0.3530, NDCG@10: 0.3479, HR@10: 0.6010, MRR: 0.2946
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0798
epoch=32, loss=0.0786
epoch=33, loss=0.0794
epoch=34, loss=0.0785
epoch=35, loss=0.0777
valid [full], NDCG@5: 0.6451, HR@5: 0.7696, NDCG@10: 0.7125, HR@10: 0.9773, MRR: 0.6356
valid [sampled], NDCG@5: 0.5524, HR@5: 0.5555, NDCG@10: 0.5614, HR@10: 0.5840, MRR: 0.5696
test [full], NDCG@5: 0.8443, HR@5: 0.9113, NDCG@10: 0.8724, HR@10: 1.0000, MRR: 0.8332
test [sampled], NDCG@5: 0.2810, HR@5: 0.3656, NDCG@10: 0.3575, HR@10: 0.6017, MRR: 0.3063
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0778
epoch=37, loss=0.0768
epoch=38, loss=0.0769
epoch=39, loss=0.0776
epoch=40, loss=0.0783
valid [full], NDCG@5: 0.6622, HR@5: 0.7988, NDCG@10: 0.7111, HR@10: 0.9507, MRR: 0.6430
valid [sampled], NDCG@5: 0.5575, HR@5: 0.5592, NDCG@10: 0.5654, HR@10: 0.5843, MRR: 0.5750
test [full], NDCG@5: 0.8631, HR@5: 0.9248, NDCG@10: 0.8866, HR@10: 1.0000, MRR: 0.8518
test [sampled], NDCG@5: 0.3200, HR@5: 0.3984, NDCG@10: 0.3870, HR@10: 0.6039, MRR: 0.3437
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0783
epoch=42, loss=0.0782
epoch=43, loss=0.0778
epoch=44, loss=0.0770
epoch=45, loss=0.0775
valid [full], NDCG@5: 0.6431, HR@5: 0.7968, NDCG@10: 0.6929, HR@10: 0.9514, MRR: 0.6180
valid [sampled], NDCG@5: 0.5036, HR@5: 0.5058, NDCG@10: 0.5133, HR@10: 0.5373, MRR: 0.5243
test [full], NDCG@5: 0.8601, HR@5: 0.9249, NDCG@10: 0.8836, HR@10: 1.0000, MRR: 0.8476
test [sampled], NDCG@5: 0.3805, HR@5: 0.4444, NDCG@10: 0.4362, HR@10: 0.6156, MRR: 0.4035
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0754
epoch=47, loss=0.0761
epoch=48, loss=0.0759
epoch=49, loss=0.0761
epoch=50, loss=0.0759
valid [full], NDCG@5: 0.6497, HR@5: 0.7787, NDCG@10: 0.7055, HR@10: 0.9513, MRR: 0.6348
valid [sampled], NDCG@5: 0.5306, HR@5: 0.5325, NDCG@10: 0.5392, HR@10: 0.5602, MRR: 0.5493
test [full], NDCG@5: 0.8572, HR@5: 0.9264, NDCG@10: 0.8803, HR@10: 1.0000, MRR: 0.8431
test [sampled], NDCG@5: 0.3985, HR@5: 0.4598, NDCG@10: 0.4479, HR@10: 0.6112, MRR: 0.4190
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml50_s42/sasrec_last.pth

### anchor_ml20_s42

In [15]:
!python src/train_sasrec.py \
  --run_name anchor_ml20_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42
epoch=1, loss=0.6703
epoch=2, loss=0.3156
epoch=3, loss=0.2178
epoch=4, loss=0.1735
epoch=5, loss=0.1464
valid [full], NDCG@5: 0.7050, HR@5: 0.8805, NDCG@10: 0.7424, HR@10: 0.9916, MRR: 0.6648
valid [sampled], NDCG@5: 0.5452, HR@5: 0.5520, NDCG@10: 0.5650, HR@10: 0.6151, MRR: 0.5682
test [full], NDCG@5: 0.8392, HR@5: 0.9371, NDCG@10: 0.8599, HR@10: 1.0000, MRR: 0.8146
test [sampled], NDCG@5: 0.1971, HR@5: 0.2797, NDCG@10: 0.2821, HR@10: 0.5416, MRR: 0.2314
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/sasrec_best.pth
epoch=6, loss=0.1322
epoch=7, loss=0.1238
epoch=8, loss=0.1171
epoch=9, loss=0.1131
epoch=10, loss=0.1092
valid [full], NDCG@5: 0.6742, HR@5: 0.8562, NDCG@10: 0.7120, HR@10: 0.9734, MRR: 0.6334
valid [sampled], NDCG@5: 0.5228, HR@5: 0.5274, NDCG@10: 0.5369, HR@10: 0.5729, MRR: 0.5446
test [full], NDCG@5: 0.8288, HR@5: 0.9454, NDCG@10: 0.8470, HR@10: 0.9999, MRR: 0.7970
test [sampled], NDCG@5: 0.3035, HR@5: 0.3738, NDCG@10: 0.3708, HR@10: 0.5821, MRR: 0.3303
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1086
epoch=12, loss=0.1067
epoch=13, loss=0.1041
epoch=14, loss=0.1027
epoch=15, loss=0.1021
valid [full], NDCG@5: 0.6804, HR@5: 0.8697, NDCG@10: 0.7143, HR@10: 0.9758, MRR: 0.6355
valid [sampled], NDCG@5: 0.5274, HR@5: 0.5321, NDCG@10: 0.5376, HR@10: 0.5648, MRR: 0.5483
test [full], NDCG@5: 0.8901, HR@5: 0.9945, NDCG@10: 0.8920, HR@10: 1.0000, MRR: 0.8564
test [sampled], NDCG@5: 0.3154, HR@5: 0.3981, NDCG@10: 0.3880, HR@10: 0.6220, MRR: 0.3401
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.1001
epoch=17, loss=0.0988
epoch=18, loss=0.0989
epoch=19, loss=0.0967
epoch=20, loss=0.0975
valid [full], NDCG@5: 0.6752, HR@5: 0.8547, NDCG@10: 0.7144, HR@10: 0.9757, MRR: 0.6360
valid [sampled], NDCG@5: 0.5226, HR@5: 0.5262, NDCG@10: 0.5329, HR@10: 0.5594, MRR: 0.5437
test [full], NDCG@5: 0.8838, HR@5: 0.9778, NDCG@10: 0.8915, HR@10: 0.9999, MRR: 0.8560
test [sampled], NDCG@5: 0.3369, HR@5: 0.4147, NDCG@10: 0.4050, HR@10: 0.6241, MRR: 0.3615
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0959
epoch=22, loss=0.0971
epoch=23, loss=0.0959
epoch=24, loss=0.0952
epoch=25, loss=0.0929
valid [full], NDCG@5: 0.6875, HR@5: 0.8651, NDCG@10: 0.7223, HR@10: 0.9755, MRR: 0.6459
valid [sampled], NDCG@5: 0.5211, HR@5: 0.5269, NDCG@10: 0.5374, HR@10: 0.5787, MRR: 0.5438
test [full], NDCG@5: 0.9018, HR@5: 0.9985, NDCG@10: 0.9023, HR@10: 1.0000, MRR: 0.8693
test [sampled], NDCG@5: 0.3587, HR@5: 0.4302, NDCG@10: 0.4253, HR@10: 0.6355, MRR: 0.3851
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0930
epoch=27, loss=0.0946
epoch=28, loss=0.0938
epoch=29, loss=0.0940
epoch=30, loss=0.0926
valid [full], NDCG@5: 0.6919, HR@5: 0.8413, NDCG@10: 0.7357, HR@10: 0.9764, MRR: 0.6636
valid [sampled], NDCG@5: 0.5498, HR@5: 0.5555, NDCG@10: 0.5668, HR@10: 0.6092, MRR: 0.5715
test [full], NDCG@5: 0.8918, HR@5: 0.9993, NDCG@10: 0.8920, HR@10: 1.0000, MRR: 0.8556
test [sampled], NDCG@5: 0.3868, HR@5: 0.4563, NDCG@10: 0.4423, HR@10: 0.6268, MRR: 0.4087
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0940
epoch=32, loss=0.0908
epoch=33, loss=0.0918
epoch=34, loss=0.0898
epoch=35, loss=0.0902
valid [full], NDCG@5: 0.6693, HR@5: 0.8005, NDCG@10: 0.7257, HR@10: 0.9768, MRR: 0.6517
valid [sampled], NDCG@5: 0.5538, HR@5: 0.5597, NDCG@10: 0.5685, HR@10: 0.6061, MRR: 0.5731
test [full], NDCG@5: 0.9021, HR@5: 0.9929, NDCG@10: 0.9046, HR@10: 1.0000, MRR: 0.8727
test [sampled], NDCG@5: 0.3976, HR@5: 0.4687, NDCG@10: 0.4550, HR@10: 0.6454, MRR: 0.4196
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0888
epoch=37, loss=0.0913
epoch=38, loss=0.0899
epoch=39, loss=0.0903
epoch=40, loss=0.0885
valid [full], NDCG@5: 0.6885, HR@5: 0.8269, NDCG@10: 0.7352, HR@10: 0.9758, MRR: 0.6639
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5669, NDCG@10: 0.5793, HR@10: 0.6283, MRR: 0.5808
test [full], NDCG@5: 0.9154, HR@5: 0.9988, NDCG@10: 0.9158, HR@10: 1.0000, MRR: 0.8872
test [sampled], NDCG@5: 0.4116, HR@5: 0.4741, NDCG@10: 0.4661, HR@10: 0.6417, MRR: 0.4356
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0902
epoch=42, loss=0.0892
epoch=43, loss=0.0902
epoch=44, loss=0.0881
epoch=45, loss=0.0913
valid [full], NDCG@5: 0.7025, HR@5: 0.8598, NDCG@10: 0.7401, HR@10: 0.9780, MRR: 0.6687
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5625, NDCG@10: 0.5745, HR@10: 0.6209, MRR: 0.5778
test [full], NDCG@5: 0.9003, HR@5: 0.9954, NDCG@10: 0.9020, HR@10: 1.0000, MRR: 0.8690
test [sampled], NDCG@5: 0.3840, HR@5: 0.4518, NDCG@10: 0.4470, HR@10: 0.6450, MRR: 0.4094
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0848
epoch=47, loss=0.0888
epoch=48, loss=0.0873
epoch=49, loss=0.0878
epoch=50, loss=0.0870
valid [full], NDCG@5: 0.7088, HR@5: 0.8485, NDCG@10: 0.7504, HR@10: 0.9775, MRR: 0.6818
valid [sampled], NDCG@5: 0.5564, HR@5: 0.5678, NDCG@10: 0.5837, HR@10: 0.6543, MRR: 0.5784
test [full], NDCG@5: 0.9138, HR@5: 0.9958, NDCG@10: 0.9153, HR@10: 1.0000, MRR: 0.8868
test [sampled], NDCG@5: 0.4066, HR@5: 0.4733, NDCG@10: 0.4649, HR@10: 0.6525, MRR: 0.4302
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s42/sasrec_last.pth

### refine_ml50_do030_s42

In [16]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do030_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42
epoch=1, loss=0.5360
epoch=2, loss=0.2475
epoch=3, loss=0.1849
epoch=4, loss=0.1493
epoch=5, loss=0.1305
valid [full], NDCG@5: 0.6477, HR@5: 0.7576, NDCG@10: 0.6943, HR@10: 0.9076, MRR: 0.6380
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5666, NDCG@10: 0.5702, HR@10: 0.6159, MRR: 0.5690
test [full], NDCG@5: 0.4378, HR@5: 0.5577, NDCG@10: 0.5739, HR@10: 0.9914, MRR: 0.4509
test [sampled], NDCG@5: 0.1360, HR@5: 0.1425, NDCG@10: 0.1793, HR@10: 0.2819, MRR: 0.1759
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/sasrec_best.pth
epoch=6, loss=0.1189
epoch=7, loss=0.1129
epoch=8, loss=0.1061
epoch=9, loss=0.1020
epoch=10, loss=0.1001
valid [full], NDCG@5: 0.6349, HR@5: 0.7316, NDCG@10: 0.7103, HR@10: 0.9705, MRR: 0.6365
valid [sampled], NDCG@5: 0.5581, HR@5: 0.5718, NDCG@10: 0.5709, HR@10: 0.6110, MRR: 0.5704
test [full], NDCG@5: 0.7211, HR@5: 0.8743, NDCG@10: 0.7620, HR@10: 1.0000, MRR: 0.6854
test [sampled], NDCG@5: 0.1905, HR@5: 0.2607, NDCG@10: 0.2593, HR@10: 0.4741, MRR: 0.2214
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/sasrec_best.pth
epoch=11, loss=0.0980
epoch=12, loss=0.0960
epoch=13, loss=0.0940
epoch=14, loss=0.0936
epoch=15, loss=0.0941
valid [full], NDCG@5: 0.6839, HR@5: 0.8331, NDCG@10: 0.7284, HR@10: 0.9753, MRR: 0.6559
valid [sampled], NDCG@5: 0.5708, HR@5: 0.5829, NDCG@10: 0.5855, HR@10: 0.6286, MRR: 0.5861
test [full], NDCG@5: 0.8195, HR@5: 0.9279, NDCG@10: 0.8431, HR@10: 1.0000, MRR: 0.7924
test [sampled], NDCG@5: 0.2151, HR@5: 0.2973, NDCG@10: 0.2941, HR@10: 0.5413, MRR: 0.2469
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/sasrec_best.pth
epoch=16, loss=0.0896
epoch=17, loss=0.0883
epoch=18, loss=0.0881
epoch=19, loss=0.0877
epoch=20, loss=0.0876
valid [full], NDCG@5: 0.6424, HR@5: 0.7353, NDCG@10: 0.7155, HR@10: 0.9662, MRR: 0.6450
valid [sampled], NDCG@5: 0.5648, HR@5: 0.5715, NDCG@10: 0.5749, HR@10: 0.6029, MRR: 0.5790
test [full], NDCG@5: 0.8084, HR@5: 0.8774, NDCG@10: 0.8483, HR@10: 1.0000, MRR: 0.8010
test [sampled], NDCG@5: 0.2331, HR@5: 0.3226, NDCG@10: 0.3147, HR@10: 0.5742, MRR: 0.2605
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0855
epoch=22, loss=0.0855
epoch=23, loss=0.0861
epoch=24, loss=0.0857
epoch=25, loss=0.0844
valid [full], NDCG@5: 0.6385, HR@5: 0.7415, NDCG@10: 0.7063, HR@10: 0.9536, MRR: 0.6373
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5527, NDCG@10: 0.5580, HR@10: 0.5890, MRR: 0.5617
test [full], NDCG@5: 0.8463, HR@5: 0.9045, NDCG@10: 0.8766, HR@10: 1.0000, MRR: 0.8388
test [sampled], NDCG@5: 0.2854, HR@5: 0.3719, NDCG@10: 0.3636, HR@10: 0.6114, MRR: 0.3097
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0832
epoch=27, loss=0.0852
epoch=28, loss=0.0831
epoch=29, loss=0.0843
epoch=30, loss=0.0843
valid [full], NDCG@5: 0.6472, HR@5: 0.7611, NDCG@10: 0.7164, HR@10: 0.9764, MRR: 0.6415
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5545, NDCG@10: 0.5601, HR@10: 0.5837, MRR: 0.5672
test [full], NDCG@5: 0.8502, HR@5: 0.9105, NDCG@10: 0.8787, HR@10: 1.0000, MRR: 0.8417
test [sampled], NDCG@5: 0.2362, HR@5: 0.3175, NDCG@10: 0.3218, HR@10: 0.5821, MRR: 0.2677
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0837
epoch=32, loss=0.0823
epoch=33, loss=0.0832
epoch=34, loss=0.0824
epoch=35, loss=0.0812
valid [full], NDCG@5: 0.6380, HR@5: 0.7530, NDCG@10: 0.7038, HR@10: 0.9553, MRR: 0.6329
valid [sampled], NDCG@5: 0.5548, HR@5: 0.5564, NDCG@10: 0.5615, HR@10: 0.5774, MRR: 0.5712
test [full], NDCG@5: 0.8221, HR@5: 0.8984, NDCG@10: 0.8546, HR@10: 1.0000, MRR: 0.8098
test [sampled], NDCG@5: 0.2346, HR@5: 0.3192, NDCG@10: 0.3073, HR@10: 0.5430, MRR: 0.2610
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0814
epoch=37, loss=0.0802
epoch=38, loss=0.0811
epoch=39, loss=0.0809
epoch=40, loss=0.0818
valid [full], NDCG@5: 0.6586, HR@5: 0.7976, NDCG@10: 0.7084, HR@10: 0.9524, MRR: 0.6391
valid [sampled], NDCG@5: 0.5543, HR@5: 0.5565, NDCG@10: 0.5623, HR@10: 0.5821, MRR: 0.5711
test [full], NDCG@5: 0.8551, HR@5: 0.9243, NDCG@10: 0.8787, HR@10: 1.0000, MRR: 0.8414
test [sampled], NDCG@5: 0.3003, HR@5: 0.3781, NDCG@10: 0.3675, HR@10: 0.5846, MRR: 0.3252
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0813
epoch=42, loss=0.0819
epoch=43, loss=0.0809
epoch=44, loss=0.0808
epoch=45, loss=0.0809
valid [full], NDCG@5: 0.6573, HR@5: 0.7835, NDCG@10: 0.7120, HR@10: 0.9522, MRR: 0.6438
valid [sampled], NDCG@5: 0.5523, HR@5: 0.5555, NDCG@10: 0.5609, HR@10: 0.5827, MRR: 0.5692
test [full], NDCG@5: 0.8519, HR@5: 0.9219, NDCG@10: 0.8762, HR@10: 1.0000, MRR: 0.8379
test [sampled], NDCG@5: 0.3119, HR@5: 0.3891, NDCG@10: 0.3796, HR@10: 0.5969, MRR: 0.3364
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0788
epoch=47, loss=0.0798
epoch=48, loss=0.0799
epoch=49, loss=0.0792
epoch=50, loss=0.0788
valid [full], NDCG@5: 0.6709, HR@5: 0.8454, NDCG@10: 0.7048, HR@10: 0.9528, MRR: 0.6325
valid [sampled], NDCG@5: 0.5137, HR@5: 0.5198, NDCG@10: 0.5257, HR@10: 0.5576, MRR: 0.5338
test [full], NDCG@5: 0.8499, HR@5: 0.9215, NDCG@10: 0.8744, HR@10: 1.0000, MRR: 0.8352
test [sampled], NDCG@5: 0.3932, HR@5: 0.4563, NDCG@10: 0.4451, HR@10: 0.6153, MRR: 0.4133
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s42/sasrec_last.pth

### refine_ml50_do035_s42

In [17]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42
epoch=1, loss=0.5673
epoch=2, loss=0.2638
epoch=3, loss=0.1987
epoch=4, loss=0.1638
epoch=5, loss=0.1414
valid [full], NDCG@5: 0.6434, HR@5: 0.7559, NDCG@10: 0.6854, HR@10: 0.8896, MRR: 0.6333
valid [sampled], NDCG@5: 0.5545, HR@5: 0.5603, NDCG@10: 0.5654, HR@10: 0.5947, MRR: 0.5698
test [full], NDCG@5: 0.4390, HR@5: 0.6201, NDCG@10: 0.5094, HR@10: 0.8432, MRR: 0.4211
test [sampled], NDCG@5: 0.1322, HR@5: 0.1359, NDCG@10: 0.1472, HR@10: 0.1844, MRR: 0.1664
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1290
epoch=7, loss=0.1210
epoch=8, loss=0.1137
epoch=9, loss=0.1093
epoch=10, loss=0.1068
valid [full], NDCG@5: 0.6132, HR@5: 0.6798, NDCG@10: 0.7075, HR@10: 0.9700, MRR: 0.6332
valid [sampled], NDCG@5: 0.5556, HR@5: 0.5692, NDCG@10: 0.5683, HR@10: 0.6082, MRR: 0.5675
test [full], NDCG@5: 0.7193, HR@5: 0.8732, NDCG@10: 0.7595, HR@10: 1.0000, MRR: 0.6825
test [sampled], NDCG@5: 0.1816, HR@5: 0.2519, NDCG@10: 0.2515, HR@10: 0.4689, MRR: 0.2129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=0.1033
epoch=12, loss=0.1010
epoch=13, loss=0.0993
epoch=14, loss=0.0983
epoch=15, loss=0.0982
valid [full], NDCG@5: 0.6582, HR@5: 0.7812, NDCG@10: 0.7176, HR@10: 0.9712, MRR: 0.6447
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5788, NDCG@10: 0.5795, HR@10: 0.6176, MRR: 0.5805
test [full], NDCG@5: 0.7798, HR@5: 0.8926, NDCG@10: 0.8145, HR@10: 1.0000, MRR: 0.7553
test [sampled], NDCG@5: 0.2096, HR@5: 0.2901, NDCG@10: 0.2837, HR@10: 0.5181, MRR: 0.2392
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0938
epoch=17, loss=0.0921
epoch=18, loss=0.0919
epoch=19, loss=0.0913
epoch=20, loss=0.0912
valid [full], NDCG@5: 0.6678, HR@5: 0.7918, NDCG@10: 0.7258, HR@10: 0.9677, MRR: 0.6559
valid [sampled], NDCG@5: 0.5678, HR@5: 0.5781, NDCG@10: 0.5793, HR@10: 0.6135, MRR: 0.5818
test [full], NDCG@5: 0.8150, HR@5: 0.9157, NDCG@10: 0.8413, HR@10: 0.9999, MRR: 0.7912
test [sampled], NDCG@5: 0.2193, HR@5: 0.3068, NDCG@10: 0.3005, HR@10: 0.5576, MRR: 0.2482
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/sasrec_best.pth
epoch=21, loss=0.0892
epoch=22, loss=0.0887
epoch=23, loss=0.0893
epoch=24, loss=0.0884
epoch=25, loss=0.0879
valid [full], NDCG@5: 0.6722, HR@5: 0.8205, NDCG@10: 0.7192, HR@10: 0.9664, MRR: 0.6469
valid [sampled], NDCG@5: 0.5401, HR@5: 0.5508, NDCG@10: 0.5553, HR@10: 0.5977, MRR: 0.5573
test [full], NDCG@5: 0.8439, HR@5: 0.9245, NDCG@10: 0.8668, HR@10: 0.9999, MRR: 0.8250
test [sampled], NDCG@5: 0.2562, HR@5: 0.3499, NDCG@10: 0.3416, HR@10: 0.6114, MRR: 0.2819
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0865
epoch=27, loss=0.0884
epoch=28, loss=0.0859
epoch=29, loss=0.0870
epoch=30, loss=0.0869
valid [full], NDCG@5: 0.6817, HR@5: 0.8317, NDCG@10: 0.7279, HR@10: 0.9749, MRR: 0.6555
valid [sampled], NDCG@5: 0.5619, HR@5: 0.5660, NDCG@10: 0.5710, HR@10: 0.5946, MRR: 0.5791
test [full], NDCG@5: 0.8127, HR@5: 0.9201, NDCG@10: 0.8373, HR@10: 1.0000, MRR: 0.7857
test [sampled], NDCG@5: 0.1741, HR@5: 0.2645, NDCG@10: 0.2634, HR@10: 0.5397, MRR: 0.2062
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/sasrec_best.pth
epoch=31, loss=0.0868
epoch=32, loss=0.0853
epoch=33, loss=0.0859
epoch=34, loss=0.0851
epoch=35, loss=0.0836
valid [full], NDCG@5: 0.6720, HR@5: 0.8324, NDCG@10: 0.7155, HR@10: 0.9698, MRR: 0.6414
valid [sampled], NDCG@5: 0.5550, HR@5: 0.5571, NDCG@10: 0.5615, HR@10: 0.5777, MRR: 0.5726
test [full], NDCG@5: 0.8381, HR@5: 0.9183, NDCG@10: 0.8629, HR@10: 0.9999, MRR: 0.8211
test [sampled], NDCG@5: 0.2152, HR@5: 0.3021, NDCG@10: 0.2995, HR@10: 0.5623, MRR: 0.2450
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0842
epoch=37, loss=0.0825
epoch=38, loss=0.0835
epoch=39, loss=0.0839
epoch=40, loss=0.0842
valid [full], NDCG@5: 0.6761, HR@5: 0.8327, NDCG@10: 0.7220, HR@10: 0.9754, MRR: 0.6473
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5566, NDCG@10: 0.5612, HR@10: 0.5760, MRR: 0.5737
test [full], NDCG@5: 0.8332, HR@5: 0.9225, NDCG@10: 0.8567, HR@10: 1.0000, MRR: 0.8122
test [sampled], NDCG@5: 0.2043, HR@5: 0.2897, NDCG@10: 0.2871, HR@10: 0.5451, MRR: 0.2353
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0837
epoch=42, loss=0.0842
epoch=43, loss=0.0833
epoch=44, loss=0.0830
epoch=45, loss=0.0832
valid [full], NDCG@5: 0.6901, HR@5: 0.8644, NDCG@10: 0.7262, HR@10: 0.9775, MRR: 0.6512
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5502, NDCG@10: 0.5561, HR@10: 0.5811, MRR: 0.5662
test [full], NDCG@5: 0.8615, HR@5: 0.9514, NDCG@10: 0.8778, HR@10: 1.0000, MRR: 0.8387
test [sampled], NDCG@5: 0.2836, HR@5: 0.3660, NDCG@10: 0.3571, HR@10: 0.5917, MRR: 0.3104
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0806
epoch=47, loss=0.0818
epoch=48, loss=0.0822
epoch=49, loss=0.0818
epoch=50, loss=0.0810
valid [full], NDCG@5: 0.6974, HR@5: 0.8542, NDCG@10: 0.7354, HR@10: 0.9773, MRR: 0.6635
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5651, NDCG@10: 0.5687, HR@10: 0.6064, MRR: 0.5728
test [full], NDCG@5: 0.8687, HR@5: 0.9264, NDCG@10: 0.8918, HR@10: 1.0000, MRR: 0.8584
test [sampled], NDCG@5: 0.3995, HR@5: 0.4674, NDCG@10: 0.4560, HR@10: 0.6406, MRR: 0.4192
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s42/sasrec_last.pth

### refine_ml50_do025_s42

In [18]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do025_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42
epoch=1, loss=0.5066
epoch=2, loss=0.2315
epoch=3, loss=0.1700
epoch=4, loss=0.1361
epoch=5, loss=0.1203
valid [full], NDCG@5: 0.6551, HR@5: 0.7708, NDCG@10: 0.7204, HR@10: 0.9803, MRR: 0.6446
valid [sampled], NDCG@5: 0.5541, HR@5: 0.5661, NDCG@10: 0.5730, HR@10: 0.6257, MRR: 0.5705
test [full], NDCG@5: 0.4666, HR@5: 0.6195, NDCG@10: 0.5856, HR@10: 1.0000, MRR: 0.4610
test [sampled], NDCG@5: 0.1341, HR@5: 0.1405, NDCG@10: 0.1812, HR@10: 0.2923, MRR: 0.1766
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/sasrec_best.pth
epoch=6, loss=0.1109
epoch=7, loss=0.1059
epoch=8, loss=0.0996
epoch=9, loss=0.0969
epoch=10, loss=0.0953
valid [full], NDCG@5: 0.6791, HR@5: 0.8402, NDCG@10: 0.7203, HR@10: 0.9686, MRR: 0.6477
valid [sampled], NDCG@5: 0.5577, HR@5: 0.5710, NDCG@10: 0.5692, HR@10: 0.6063, MRR: 0.5719
test [full], NDCG@5: 0.6568, HR@5: 0.9186, NDCG@10: 0.6822, HR@10: 1.0000, MRR: 0.5765
test [sampled], NDCG@5: 0.1575, HR@5: 0.1747, NDCG@10: 0.2177, HR@10: 0.3680, MRR: 0.2085
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0933
epoch=12, loss=0.0914
epoch=13, loss=0.0901
epoch=14, loss=0.0898
epoch=15, loss=0.0901
valid [full], NDCG@5: 0.6988, HR@5: 0.8559, NDCG@10: 0.7373, HR@10: 0.9753, MRR: 0.6664
valid [sampled], NDCG@5: 0.5767, HR@5: 0.5888, NDCG@10: 0.5903, HR@10: 0.6309, MRR: 0.5927
test [full], NDCG@5: 0.7330, HR@5: 0.9227, NDCG@10: 0.7572, HR@10: 1.0000, MRR: 0.6762
test [sampled], NDCG@5: 0.1715, HR@5: 0.1972, NDCG@10: 0.2436, HR@10: 0.4273, MRR: 0.2259
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/sasrec_best.pth
epoch=16, loss=0.0862
epoch=17, loss=0.0846
epoch=18, loss=0.0851
epoch=19, loss=0.0848
epoch=20, loss=0.0844
valid [full], NDCG@5: 0.6580, HR@5: 0.7767, NDCG@10: 0.7231, HR@10: 0.9760, MRR: 0.6494
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5702, NDCG@10: 0.5717, HR@10: 0.6117, MRR: 0.5727
test [full], NDCG@5: 0.7323, HR@5: 0.8943, NDCG@10: 0.7665, HR@10: 1.0000, MRR: 0.6902
test [sampled], NDCG@5: 0.1947, HR@5: 0.2281, NDCG@10: 0.2680, HR@10: 0.4608, MRR: 0.2437
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0824
epoch=22, loss=0.0828
epoch=23, loss=0.0831
epoch=24, loss=0.0828
epoch=25, loss=0.0816
valid [full], NDCG@5: 0.6411, HR@5: 0.7720, NDCG@10: 0.7057, HR@10: 0.9755, MRR: 0.6273
valid [sampled], NDCG@5: 0.5246, HR@5: 0.5300, NDCG@10: 0.5367, HR@10: 0.5681, MRR: 0.5424
test [full], NDCG@5: 0.8659, HR@5: 0.9249, NDCG@10: 0.8894, HR@10: 1.0000, MRR: 0.8557
test [sampled], NDCG@5: 0.2910, HR@5: 0.3803, NDCG@10: 0.3708, HR@10: 0.6239, MRR: 0.3147
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0810
epoch=27, loss=0.0827
epoch=28, loss=0.0812
epoch=29, loss=0.0823
epoch=30, loss=0.0821
valid [full], NDCG@5: 0.6667, HR@5: 0.7998, NDCG@10: 0.7247, HR@10: 0.9764, MRR: 0.6508
valid [sampled], NDCG@5: 0.5511, HR@5: 0.5584, NDCG@10: 0.5632, HR@10: 0.5960, MRR: 0.5682
test [full], NDCG@5: 0.8700, HR@5: 0.9218, NDCG@10: 0.8945, HR@10: 1.0000, MRR: 0.8621
test [sampled], NDCG@5: 0.3002, HR@5: 0.3920, NDCG@10: 0.3783, HR@10: 0.6311, MRR: 0.3224
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0814
epoch=32, loss=0.0804
epoch=33, loss=0.0813
epoch=34, loss=0.0805
epoch=35, loss=0.0787
valid [full], NDCG@5: 0.6321, HR@5: 0.7427, NDCG@10: 0.7033, HR@10: 0.9708, MRR: 0.6276
valid [sampled], NDCG@5: 0.5525, HR@5: 0.5543, NDCG@10: 0.5589, HR@10: 0.5743, MRR: 0.5681
test [full], NDCG@5: 0.8533, HR@5: 0.9120, NDCG@10: 0.8809, HR@10: 1.0000, MRR: 0.8448
test [sampled], NDCG@5: 0.2981, HR@5: 0.3853, NDCG@10: 0.3709, HR@10: 0.6093, MRR: 0.3204
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0794
epoch=37, loss=0.0779
epoch=38, loss=0.0789
epoch=39, loss=0.0789
epoch=40, loss=0.0798
valid [full], NDCG@5: 0.6371, HR@5: 0.8026, NDCG@10: 0.6853, HR@10: 0.9548, MRR: 0.6077
valid [sampled], NDCG@5: 0.4989, HR@5: 0.5008, NDCG@10: 0.5072, HR@10: 0.5271, MRR: 0.5189
test [full], NDCG@5: 0.8607, HR@5: 0.9267, NDCG@10: 0.8836, HR@10: 1.0000, MRR: 0.8478
test [sampled], NDCG@5: 0.3443, HR@5: 0.4116, NDCG@10: 0.4032, HR@10: 0.5931, MRR: 0.3688
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0798
epoch=42, loss=0.0802
epoch=43, loss=0.0791
epoch=44, loss=0.0788
epoch=45, loss=0.0791
valid [full], NDCG@5: 0.6192, HR@5: 0.7600, NDCG@10: 0.6794, HR@10: 0.9500, MRR: 0.6025
valid [sampled], NDCG@5: 0.4934, HR@5: 0.4957, NDCG@10: 0.5009, HR@10: 0.5197, MRR: 0.5125
test [full], NDCG@5: 0.8646, HR@5: 0.9220, NDCG@10: 0.8888, HR@10: 1.0000, MRR: 0.8550
test [sampled], NDCG@5: 0.3295, HR@5: 0.4089, NDCG@10: 0.3959, HR@10: 0.6124, MRR: 0.3522
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0769
epoch=47, loss=0.0781
epoch=48, loss=0.0775
epoch=49, loss=0.0777
epoch=50, loss=0.0769
valid [full], NDCG@5: 0.6462, HR@5: 0.7728, NDCG@10: 0.7044, HR@10: 0.9513, MRR: 0.6342
valid [sampled], NDCG@5: 0.5267, HR@5: 0.5299, NDCG@10: 0.5377, HR@10: 0.5652, MRR: 0.5453
test [full], NDCG@5: 0.8679, HR@5: 0.9261, NDCG@10: 0.8909, HR@10: 1.0000, MRR: 0.8573
test [sampled], NDCG@5: 0.3770, HR@5: 0.4494, NDCG@10: 0.4378, HR@10: 0.6359, MRR: 0.3979
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s42/sasrec_last.pth

### refine_ml50_do025_s2024

In [19]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do025_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024
epoch=1, loss=0.5681
epoch=2, loss=0.2402
epoch=3, loss=0.1763
epoch=4, loss=0.1409
epoch=5, loss=0.1248
valid [full], NDCG@5: 0.6843, HR@5: 0.8465, NDCG@10: 0.7338, HR@10: 0.9939, MRR: 0.6549
valid [sampled], NDCG@5: 0.5604, HR@5: 0.5637, NDCG@10: 0.5685, HR@10: 0.5894, MRR: 0.5784
test [full], NDCG@5: 0.7561, HR@5: 0.8822, NDCG@10: 0.7931, HR@10: 1.0000, MRR: 0.7288
test [sampled], NDCG@5: 0.1681, HR@5: 0.2351, NDCG@10: 0.2364, HR@10: 0.4463, MRR: 0.2037
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/sasrec_best.pth
epoch=6, loss=0.1121
epoch=7, loss=0.1043
epoch=8, loss=0.1006
epoch=9, loss=0.0951
epoch=10, loss=0.0942
valid [full], NDCG@5: 0.6579, HR@5: 0.7653, NDCG@10: 0.7238, HR@10: 0.9739, MRR: 0.6515
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5683, NDCG@10: 0.5739, HR@10: 0.6196, MRR: 0.5730
test [full], NDCG@5: 0.7544, HR@5: 0.8836, NDCG@10: 0.7910, HR@10: 1.0000, MRR: 0.7237
test [sampled], NDCG@5: 0.2142, HR@5: 0.2597, NDCG@10: 0.2974, HR@10: 0.5214, MRR: 0.2590
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0919
epoch=12, loss=0.0901
epoch=13, loss=0.0879
epoch=14, loss=0.0878
epoch=15, loss=0.0883
valid [full], NDCG@5: 0.6946, HR@5: 0.8559, NDCG@10: 0.7325, HR@10: 0.9745, MRR: 0.6597
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5520, NDCG@10: 0.5637, HR@10: 0.6078, MRR: 0.5686
test [full], NDCG@5: 0.8544, HR@5: 0.9162, NDCG@10: 0.8811, HR@10: 1.0000, MRR: 0.8445
test [sampled], NDCG@5: 0.2253, HR@5: 0.3130, NDCG@10: 0.3142, HR@10: 0.5879, MRR: 0.2560
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0854
epoch=17, loss=0.0849
epoch=18, loss=0.0852
epoch=19, loss=0.0840
epoch=20, loss=0.0844
valid [full], NDCG@5: 0.6496, HR@5: 0.7816, NDCG@10: 0.7127, HR@10: 0.9768, MRR: 0.6351
valid [sampled], NDCG@5: 0.5239, HR@5: 0.5283, NDCG@10: 0.5399, HR@10: 0.5789, MRR: 0.5444
test [full], NDCG@5: 0.8233, HR@5: 0.8748, NDCG@10: 0.8638, HR@10: 1.0000, MRR: 0.8227
test [sampled], NDCG@5: 0.3214, HR@5: 0.3924, NDCG@10: 0.3863, HR@10: 0.5913, MRR: 0.3456
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0839
epoch=22, loss=0.0830
epoch=23, loss=0.0828
epoch=24, loss=0.0849
epoch=25, loss=0.0836
valid [full], NDCG@5: 0.6160, HR@5: 0.7848, NDCG@10: 0.6778, HR@10: 0.9740, MRR: 0.5894
valid [sampled], NDCG@5: 0.4594, HR@5: 0.4713, NDCG@10: 0.4738, HR@10: 0.5162, MRR: 0.4787
test [full], NDCG@5: 0.8821, HR@5: 0.9676, NDCG@10: 0.8931, HR@10: 1.0000, MRR: 0.8593
test [sampled], NDCG@5: 0.3084, HR@5: 0.3837, NDCG@10: 0.3796, HR@10: 0.6041, MRR: 0.3350
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0805
epoch=27, loss=0.0801
epoch=28, loss=0.0805
epoch=29, loss=0.0836
epoch=30, loss=0.0797
valid [full], NDCG@5: 0.5992, HR@5: 0.7386, NDCG@10: 0.6770, HR@10: 0.9768, MRR: 0.5889
valid [sampled], NDCG@5: 0.4733, HR@5: 0.4834, NDCG@10: 0.4855, HR@10: 0.5212, MRR: 0.4909
test [full], NDCG@5: 0.8545, HR@5: 0.9168, NDCG@10: 0.8827, HR@10: 1.0000, MRR: 0.8466
test [sampled], NDCG@5: 0.3788, HR@5: 0.4443, NDCG@10: 0.4320, HR@10: 0.6079, MRR: 0.3996
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0811
epoch=32, loss=0.0813
epoch=33, loss=0.0794
epoch=34, loss=0.0805
epoch=35, loss=0.0790
valid [full], NDCG@5: 0.6377, HR@5: 0.7570, NDCG@10: 0.7030, HR@10: 0.9545, MRR: 0.6309
valid [sampled], NDCG@5: 0.5351, HR@5: 0.5458, NDCG@10: 0.5476, HR@10: 0.5849, MRR: 0.5506
test [full], NDCG@5: 0.8791, HR@5: 0.9724, NDCG@10: 0.8888, HR@10: 1.0000, MRR: 0.8538
test [sampled], NDCG@5: 0.4189, HR@5: 0.4726, NDCG@10: 0.4658, HR@10: 0.6163, MRR: 0.4410
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0806
epoch=37, loss=0.0795
epoch=38, loss=0.0802
epoch=39, loss=0.0797
epoch=40, loss=0.0779
valid [full], NDCG@5: 0.6194, HR@5: 0.7994, NDCG@10: 0.6772, HR@10: 0.9759, MRR: 0.5878
valid [sampled], NDCG@5: 0.4641, HR@5: 0.4752, NDCG@10: 0.4769, HR@10: 0.5147, MRR: 0.4829
test [full], NDCG@5: 0.8742, HR@5: 0.9458, NDCG@10: 0.8913, HR@10: 1.0000, MRR: 0.8575
test [sampled], NDCG@5: 0.4001, HR@5: 0.4608, NDCG@10: 0.4521, HR@10: 0.6210, MRR: 0.4218
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0789
epoch=42, loss=0.0792
epoch=43, loss=0.0794
epoch=44, loss=0.0770
epoch=45, loss=0.0781
valid [full], NDCG@5: 0.6179, HR@5: 0.8002, NDCG@10: 0.6756, HR@10: 0.9774, MRR: 0.5852
valid [sampled], NDCG@5: 0.4650, HR@5: 0.4733, NDCG@10: 0.4755, HR@10: 0.5061, MRR: 0.4844
test [full], NDCG@5: 0.8693, HR@5: 0.9401, NDCG@10: 0.8892, HR@10: 1.0000, MRR: 0.8547
test [sampled], NDCG@5: 0.3735, HR@5: 0.4362, NDCG@10: 0.4288, HR@10: 0.6064, MRR: 0.3972
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0771
epoch=47, loss=0.0774
epoch=48, loss=0.0782
epoch=49, loss=0.0766
epoch=50, loss=0.0788
valid [full], NDCG@5: 0.6139, HR@5: 0.7929, NDCG@10: 0.6751, HR@10: 0.9751, MRR: 0.5849
valid [sampled], NDCG@5: 0.4563, HR@5: 0.4668, NDCG@10: 0.4696, HR@10: 0.5081, MRR: 0.4760
test [full], NDCG@5: 0.8710, HR@5: 0.9414, NDCG@10: 0.8897, HR@10: 1.0000, MRR: 0.8554
test [sampled], NDCG@5: 0.4023, HR@5: 0.4647, NDCG@10: 0.4562, HR@10: 0.6302, MRR: 0.4238
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do025_s2024/sasrec_last.pth

### refine_ml50_do030_s2024

In [20]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do030_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024
epoch=1, loss=0.5987
epoch=2, loss=0.2553
epoch=3, loss=0.1894
epoch=4, loss=0.1533
epoch=5, loss=0.1350
valid [full], NDCG@5: 0.7439, HR@5: 0.9658, NDCG@10: 0.7536, HR@10: 0.9931, MRR: 0.6785
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5725, NDCG@10: 0.5807, HR@10: 0.6159, MRR: 0.5882
test [full], NDCG@5: 0.7688, HR@5: 0.9350, NDCG@10: 0.7900, HR@10: 1.0000, MRR: 0.7235
test [sampled], NDCG@5: 0.1627, HR@5: 0.2252, NDCG@10: 0.2248, HR@10: 0.4173, MRR: 0.1993
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/sasrec_best.pth
epoch=6, loss=0.1200
epoch=7, loss=0.1109
epoch=8, loss=0.1070
epoch=9, loss=0.1001
epoch=10, loss=0.0988
valid [full], NDCG@5: 0.6875, HR@5: 0.8443, NDCG@10: 0.7296, HR@10: 0.9719, MRR: 0.6576
valid [sampled], NDCG@5: 0.5530, HR@5: 0.5610, NDCG@10: 0.5691, HR@10: 0.6120, MRR: 0.5716
test [full], NDCG@5: 0.7472, HR@5: 0.9068, NDCG@10: 0.7776, HR@10: 1.0000, MRR: 0.7046
test [sampled], NDCG@5: 0.1471, HR@5: 0.1861, NDCG@10: 0.2371, HR@10: 0.4713, MRR: 0.2001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0960
epoch=12, loss=0.0938
epoch=13, loss=0.0911
epoch=14, loss=0.0912
epoch=15, loss=0.0916
valid [full], NDCG@5: 0.7035, HR@5: 0.8841, NDCG@10: 0.7317, HR@10: 0.9737, MRR: 0.6576
valid [sampled], NDCG@5: 0.5185, HR@5: 0.5258, NDCG@10: 0.5443, HR@10: 0.6088, MRR: 0.5450
test [full], NDCG@5: 0.8845, HR@5: 0.9392, NDCG@10: 0.9040, HR@10: 1.0000, MRR: 0.8738
test [sampled], NDCG@5: 0.3833, HR@5: 0.4471, NDCG@10: 0.4435, HR@10: 0.6328, MRR: 0.4081
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0890
epoch=17, loss=0.0877
epoch=18, loss=0.0876
epoch=19, loss=0.0872
epoch=20, loss=0.0869
valid [full], NDCG@5: 0.6491, HR@5: 0.8351, NDCG@10: 0.6938, HR@10: 0.9750, MRR: 0.6089
valid [sampled], NDCG@5: 0.4674, HR@5: 0.4725, NDCG@10: 0.4882, HR@10: 0.5389, MRR: 0.4923
test [full], NDCG@5: 0.8844, HR@5: 0.9483, NDCG@10: 0.9015, HR@10: 1.0000, MRR: 0.8700
test [sampled], NDCG@5: 0.3879, HR@5: 0.4534, NDCG@10: 0.4483, HR@10: 0.6390, MRR: 0.4122
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0868
epoch=22, loss=0.0855
epoch=23, loss=0.0858
epoch=24, loss=0.0868
epoch=25, loss=0.0855
valid [full], NDCG@5: 0.6741, HR@5: 0.8369, NDCG@10: 0.7113, HR@10: 0.9520, MRR: 0.6406
valid [sampled], NDCG@5: 0.5063, HR@5: 0.5117, NDCG@10: 0.5270, HR@10: 0.5779, MRR: 0.5309
test [full], NDCG@5: 0.8872, HR@5: 0.9467, NDCG@10: 0.9039, HR@10: 1.0000, MRR: 0.8736
test [sampled], NDCG@5: 0.4076, HR@5: 0.4702, NDCG@10: 0.4614, HR@10: 0.6363, MRR: 0.4297
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0829
epoch=27, loss=0.0827
epoch=28, loss=0.0835
epoch=29, loss=0.0850
epoch=30, loss=0.0824
valid [full], NDCG@5: 0.6413, HR@5: 0.8181, NDCG@10: 0.6859, HR@10: 0.9550, MRR: 0.6065
valid [sampled], NDCG@5: 0.4742, HR@5: 0.4852, NDCG@10: 0.4923, HR@10: 0.5418, MRR: 0.4947
test [full], NDCG@5: 0.8867, HR@5: 0.9475, NDCG@10: 0.9029, HR@10: 1.0000, MRR: 0.8721
test [sampled], NDCG@5: 0.4217, HR@5: 0.4795, NDCG@10: 0.4722, HR@10: 0.6349, MRR: 0.4440
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0829
epoch=32, loss=0.0836
epoch=33, loss=0.0814
epoch=34, loss=0.0818
epoch=35, loss=0.0808
valid [full], NDCG@5: 0.6430, HR@5: 0.8228, NDCG@10: 0.6841, HR@10: 0.9490, MRR: 0.6061
valid [sampled], NDCG@5: 0.4766, HR@5: 0.4797, NDCG@10: 0.4900, HR@10: 0.5227, MRR: 0.5000
test [full], NDCG@5: 0.8838, HR@5: 0.9594, NDCG@10: 0.8964, HR@10: 1.0000, MRR: 0.8635
test [sampled], NDCG@5: 0.4169, HR@5: 0.4689, NDCG@10: 0.4622, HR@10: 0.6082, MRR: 0.4408
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0823
epoch=37, loss=0.0818
epoch=38, loss=0.0820
epoch=39, loss=0.0817
epoch=40, loss=0.0800
valid [full], NDCG@5: 0.6399, HR@5: 0.8005, NDCG@10: 0.6975, HR@10: 0.9758, MRR: 0.6136
valid [sampled], NDCG@5: 0.4771, HR@5: 0.4894, NDCG@10: 0.5024, HR@10: 0.5693, MRR: 0.4997
test [full], NDCG@5: 0.8916, HR@5: 0.9574, NDCG@10: 0.9051, HR@10: 1.0000, MRR: 0.8747
test [sampled], NDCG@5: 0.4286, HR@5: 0.4818, NDCG@10: 0.4777, HR@10: 0.6339, MRR: 0.4523
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0808
epoch=42, loss=0.0814
epoch=43, loss=0.0815
epoch=44, loss=0.0785
epoch=45, loss=0.0806
valid [full], NDCG@5: 0.6417, HR@5: 0.8378, NDCG@10: 0.6856, HR@10: 0.9767, MRR: 0.5972
valid [sampled], NDCG@5: 0.4526, HR@5: 0.4580, NDCG@10: 0.4716, HR@10: 0.5192, MRR: 0.4787
test [full], NDCG@5: 0.8934, HR@5: 0.9773, NDCG@10: 0.9015, HR@10: 1.0000, MRR: 0.8695
test [sampled], NDCG@5: 0.4144, HR@5: 0.4734, NDCG@10: 0.4633, HR@10: 0.6235, MRR: 0.4375
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0792
epoch=47, loss=0.0798
epoch=48, loss=0.0799
epoch=49, loss=0.0785
epoch=50, loss=0.0802
valid [full], NDCG@5: 0.6619, HR@5: 0.8342, NDCG@10: 0.7067, HR@10: 0.9743, MRR: 0.6263
valid [sampled], NDCG@5: 0.4887, HR@5: 0.4917, NDCG@10: 0.5069, HR@10: 0.5499, MRR: 0.5145
test [full], NDCG@5: 0.8815, HR@5: 0.9586, NDCG@10: 0.8946, HR@10: 1.0000, MRR: 0.8610
test [sampled], NDCG@5: 0.4228, HR@5: 0.4728, NDCG@10: 0.4690, HR@10: 0.6149, MRR: 0.4472
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do030_s2024/sasrec_last.pth

### refine_ml75_do030_s42

In [21]:
!python src/train_sasrec.py \
  --run_name refine_ml75_do030_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 75 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42
epoch=1, loss=0.5423
epoch=2, loss=0.2566
epoch=3, loss=0.1895
epoch=4, loss=0.1550
epoch=5, loss=0.1346
valid [full], NDCG@5: 0.6334, HR@5: 0.7080, NDCG@10: 0.7187, HR@10: 0.9788, MRR: 0.6444
valid [sampled], NDCG@5: 0.5632, HR@5: 0.5782, NDCG@10: 0.5810, HR@10: 0.6336, MRR: 0.5759
test [full], NDCG@5: 0.4215, HR@5: 0.5434, NDCG@10: 0.5647, HR@10: 0.9999, MRR: 0.4357
test [sampled], NDCG@5: 0.1462, HR@5: 0.1517, NDCG@10: 0.1850, HR@10: 0.2766, MRR: 0.1841
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/sasrec_best.pth
epoch=6, loss=0.1242
epoch=7, loss=0.1132
epoch=8, loss=0.1076
epoch=9, loss=0.1039
epoch=10, loss=0.1004
valid [full], NDCG@5: 0.6418, HR@5: 0.7530, NDCG@10: 0.7101, HR@10: 0.9701, MRR: 0.6358
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5652, NDCG@10: 0.5659, HR@10: 0.6086, MRR: 0.5655
test [full], NDCG@5: 0.5969, HR@5: 0.8665, NDCG@10: 0.6403, HR@10: 1.0000, MRR: 0.5236
test [sampled], NDCG@5: 0.1396, HR@5: 0.1606, NDCG@10: 0.1950, HR@10: 0.3363, MRR: 0.1852
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0973
epoch=12, loss=0.0965
epoch=13, loss=0.0945
epoch=14, loss=0.0919
epoch=15, loss=0.0928
valid [full], NDCG@5: 0.6311, HR@5: 0.7302, NDCG@10: 0.7108, HR@10: 0.9738, MRR: 0.6358
valid [sampled], NDCG@5: 0.5681, HR@5: 0.5714, NDCG@10: 0.5738, HR@10: 0.5894, MRR: 0.5821
test [full], NDCG@5: 0.7273, HR@5: 0.8948, NDCG@10: 0.7611, HR@10: 1.0000, MRR: 0.6848
test [sampled], NDCG@5: 0.1946, HR@5: 0.2604, NDCG@10: 0.2569, HR@10: 0.4537, MRR: 0.2250
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0915
epoch=17, loss=0.0899
epoch=18, loss=0.0880
epoch=19, loss=0.0856
epoch=20, loss=0.0862
valid [full], NDCG@5: 0.6501, HR@5: 0.7676, NDCG@10: 0.7165, HR@10: 0.9735, MRR: 0.6426
valid [sampled], NDCG@5: 0.5577, HR@5: 0.5623, NDCG@10: 0.5643, HR@10: 0.5830, MRR: 0.5729
test [full], NDCG@5: 0.7843, HR@5: 0.8842, NDCG@10: 0.8212, HR@10: 1.0000, MRR: 0.7652
test [sampled], NDCG@5: 0.2234, HR@5: 0.3095, NDCG@10: 0.3046, HR@10: 0.5596, MRR: 0.2508
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0869
epoch=22, loss=0.0871
epoch=23, loss=0.0834
epoch=24, loss=0.0846
epoch=25, loss=0.0841
valid [full], NDCG@5: 0.6261, HR@5: 0.7588, NDCG@10: 0.6896, HR@10: 0.9534, MRR: 0.6138
valid [sampled], NDCG@5: 0.5063, HR@5: 0.5097, NDCG@10: 0.5154, HR@10: 0.5386, MRR: 0.5247
test [full], NDCG@5: 0.8354, HR@5: 0.9249, NDCG@10: 0.8587, HR@10: 1.0000, MRR: 0.8142
test [sampled], NDCG@5: 0.2589, HR@5: 0.3527, NDCG@10: 0.3399, HR@10: 0.6001, MRR: 0.2827
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0835
epoch=27, loss=0.0858
epoch=28, loss=0.0822
epoch=29, loss=0.0863
epoch=30, loss=0.0821
valid [full], NDCG@5: 0.6753, HR@5: 0.8232, NDCG@10: 0.7243, HR@10: 0.9764, MRR: 0.6504
valid [sampled], NDCG@5: 0.5535, HR@5: 0.5595, NDCG@10: 0.5638, HR@10: 0.5921, MRR: 0.5708
test [full], NDCG@5: 0.8477, HR@5: 0.9177, NDCG@10: 0.8733, HR@10: 1.0000, MRR: 0.8341
test [sampled], NDCG@5: 0.2813, HR@5: 0.3734, NDCG@10: 0.3616, HR@10: 0.6193, MRR: 0.3040
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/sasrec_best.pth
epoch=31, loss=0.0827
epoch=32, loss=0.0819
epoch=33, loss=0.0831
epoch=34, loss=0.0810
epoch=35, loss=0.0814
valid [full], NDCG@5: 0.6265, HR@5: 0.7820, NDCG@10: 0.6818, HR@10: 0.9522, MRR: 0.6036
valid [sampled], NDCG@5: 0.4945, HR@5: 0.4966, NDCG@10: 0.5028, HR@10: 0.5234, MRR: 0.5144
test [full], NDCG@5: 0.8379, HR@5: 0.9206, NDCG@10: 0.8626, HR@10: 1.0000, MRR: 0.8197
test [sampled], NDCG@5: 0.2836, HR@5: 0.3637, NDCG@10: 0.3593, HR@10: 0.5964, MRR: 0.3100
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0800
epoch=37, loss=0.0794
epoch=38, loss=0.0811
epoch=39, loss=0.0803
epoch=40, loss=0.0805
valid [full], NDCG@5: 0.6898, HR@5: 0.8545, NDCG@10: 0.7275, HR@10: 0.9759, MRR: 0.6540
valid [sampled], NDCG@5: 0.5535, HR@5: 0.5565, NDCG@10: 0.5653, HR@10: 0.5945, MRR: 0.5739
test [full], NDCG@5: 0.8709, HR@5: 0.9221, NDCG@10: 0.8951, HR@10: 1.0000, MRR: 0.8629
test [sampled], NDCG@5: 0.3081, HR@5: 0.3902, NDCG@10: 0.3800, HR@10: 0.6115, MRR: 0.3329
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/sasrec_best.pth
epoch=41, loss=0.0797
epoch=42, loss=0.0815
epoch=43, loss=0.0814
epoch=44, loss=0.0807
epoch=45, loss=0.0788
valid [full], NDCG@5: 0.6694, HR@5: 0.8437, NDCG@10: 0.7049, HR@10: 0.9556, MRR: 0.6311
valid [sampled], NDCG@5: 0.5102, HR@5: 0.5137, NDCG@10: 0.5243, HR@10: 0.5589, MRR: 0.5330
test [full], NDCG@5: 0.8489, HR@5: 0.9212, NDCG@10: 0.8731, HR@10: 1.0000, MRR: 0.8338
test [sampled], NDCG@5: 0.4237, HR@5: 0.4771, NDCG@10: 0.4647, HR@10: 0.6033, MRR: 0.4431
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0785
epoch=47, loss=0.0796
epoch=48, loss=0.0786
epoch=49, loss=0.0794
epoch=50, loss=0.0800
valid [full], NDCG@5: 0.6760, HR@5: 0.8489, NDCG@10: 0.7091, HR@10: 0.9546, MRR: 0.6374
valid [sampled], NDCG@5: 0.5169, HR@5: 0.5222, NDCG@10: 0.5298, HR@10: 0.5632, MRR: 0.5375
test [full], NDCG@5: 0.8314, HR@5: 0.9215, NDCG@10: 0.8557, HR@10: 1.0000, MRR: 0.8101
test [sampled], NDCG@5: 0.3960, HR@5: 0.4628, NDCG@10: 0.4481, HR@10: 0.6216, MRR: 0.4129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml75_do030_s42/sasrec_last.pth

### refine_ml100_do030_s42

In [22]:
!python src/train_sasrec.py \
  --run_name refine_ml100_do030_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 100 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42
epoch=1, loss=0.5443
epoch=2, loss=0.2581
epoch=3, loss=0.1902
epoch=4, loss=0.1567
epoch=5, loss=0.1356
valid [full], NDCG@5: 0.6461, HR@5: 0.7348, NDCG@10: 0.7279, HR@10: 0.9925, MRR: 0.6507
valid [sampled], NDCG@5: 0.5705, HR@5: 0.5853, NDCG@10: 0.5859, HR@10: 0.6330, MRR: 0.5827
test [full], NDCG@5: 0.4594, HR@5: 0.5923, NDCG@10: 0.5847, HR@10: 0.9859, MRR: 0.4657
test [sampled], NDCG@5: 0.1540, HR@5: 0.1590, NDCG@10: 0.1933, HR@10: 0.2859, MRR: 0.1936
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/sasrec_best.pth
epoch=6, loss=0.1224
epoch=7, loss=0.1130
epoch=8, loss=0.1072
epoch=9, loss=0.1040
epoch=10, loss=0.0996
valid [full], NDCG@5: 0.6488, HR@5: 0.7552, NDCG@10: 0.7171, HR@10: 0.9708, MRR: 0.6439
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5692, NDCG@10: 0.5741, HR@10: 0.6251, MRR: 0.5717
test [full], NDCG@5: 0.7142, HR@5: 0.8702, NDCG@10: 0.7567, HR@10: 1.0000, MRR: 0.6797
test [sampled], NDCG@5: 0.1867, HR@5: 0.2542, NDCG@10: 0.2523, HR@10: 0.4564, MRR: 0.2172
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0983
epoch=12, loss=0.0959
epoch=13, loss=0.0938
epoch=14, loss=0.0927
epoch=15, loss=0.0926
valid [full], NDCG@5: 0.6470, HR@5: 0.7461, NDCG@10: 0.7191, HR@10: 0.9773, MRR: 0.6455
valid [sampled], NDCG@5: 0.5770, HR@5: 0.5882, NDCG@10: 0.5879, HR@10: 0.6215, MRR: 0.5888
test [full], NDCG@5: 0.8241, HR@5: 0.9079, NDCG@10: 0.8557, HR@10: 1.0000, MRR: 0.8097
test [sampled], NDCG@5: 0.2341, HR@5: 0.3236, NDCG@10: 0.3175, HR@10: 0.5803, MRR: 0.2620
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0923
epoch=17, loss=0.0887
epoch=18, loss=0.0879
epoch=19, loss=0.0884
epoch=20, loss=0.0868
valid [full], NDCG@5: 0.6588, HR@5: 0.7774, NDCG@10: 0.7157, HR@10: 0.9594, MRR: 0.6469
valid [sampled], NDCG@5: 0.5612, HR@5: 0.5666, NDCG@10: 0.5717, HR@10: 0.5998, MRR: 0.5766
test [full], NDCG@5: 0.8208, HR@5: 0.8984, NDCG@10: 0.8529, HR@10: 0.9999, MRR: 0.8070
test [sampled], NDCG@5: 0.2673, HR@5: 0.3554, NDCG@10: 0.3451, HR@10: 0.5936, MRR: 0.2918
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0866
epoch=22, loss=0.0860
epoch=23, loss=0.0848
epoch=24, loss=0.0833
epoch=25, loss=0.0857
valid [full], NDCG@5: 0.6863, HR@5: 0.8365, NDCG@10: 0.7300, HR@10: 0.9737, MRR: 0.6582
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5604, NDCG@10: 0.5684, HR@10: 0.6020, MRR: 0.5741
test [full], NDCG@5: 0.8163, HR@5: 0.9263, NDCG@10: 0.8396, HR@10: 1.0000, MRR: 0.7883
test [sampled], NDCG@5: 0.2529, HR@5: 0.3212, NDCG@10: 0.3225, HR@10: 0.5364, MRR: 0.2850
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/sasrec_best.pth
epoch=26, loss=0.0837
epoch=27, loss=0.0835
epoch=28, loss=0.0848
epoch=29, loss=0.0848
epoch=30, loss=0.0847
valid [full], NDCG@5: 0.6725, HR@5: 0.7897, NDCG@10: 0.7335, HR@10: 0.9762, MRR: 0.6622
valid [sampled], NDCG@5: 0.5621, HR@5: 0.5762, NDCG@10: 0.5787, HR@10: 0.6278, MRR: 0.5773
test [full], NDCG@5: 0.8413, HR@5: 0.9194, NDCG@10: 0.8665, HR@10: 1.0000, MRR: 0.8238
test [sampled], NDCG@5: 0.2743, HR@5: 0.3596, NDCG@10: 0.3506, HR@10: 0.5930, MRR: 0.3001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/sasrec_best.pth
epoch=31, loss=0.0827
epoch=32, loss=0.0810
epoch=33, loss=0.0828
epoch=34, loss=0.0796
epoch=35, loss=0.0824
valid [full], NDCG@5: 0.6558, HR@5: 0.7772, NDCG@10: 0.7143, HR@10: 0.9557, MRR: 0.6449
valid [sampled], NDCG@5: 0.5487, HR@5: 0.5564, NDCG@10: 0.5634, HR@10: 0.6027, MRR: 0.5662
test [full], NDCG@5: 0.7945, HR@5: 0.9183, NDCG@10: 0.8198, HR@10: 1.0000, MRR: 0.7621
test [sampled], NDCG@5: 0.2406, HR@5: 0.3224, NDCG@10: 0.3189, HR@10: 0.5643, MRR: 0.2679
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0812
epoch=37, loss=0.0808
epoch=38, loss=0.0811
epoch=39, loss=0.0818
epoch=40, loss=0.0794
valid [full], NDCG@5: 0.6356, HR@5: 0.7234, NDCG@10: 0.7178, HR@10: 0.9758, MRR: 0.6434
valid [sampled], NDCG@5: 0.5602, HR@5: 0.5671, NDCG@10: 0.5706, HR@10: 0.5995, MRR: 0.5753
test [full], NDCG@5: 0.8233, HR@5: 0.9214, NDCG@10: 0.8483, HR@10: 1.0000, MRR: 0.8000
test [sampled], NDCG@5: 0.2682, HR@5: 0.3407, NDCG@10: 0.3356, HR@10: 0.5493, MRR: 0.2974
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0808
epoch=42, loss=0.0809
epoch=43, loss=0.0816
epoch=44, loss=0.0801
epoch=45, loss=0.0798
valid [full], NDCG@5: 0.6680, HR@5: 0.7903, NDCG@10: 0.7294, HR@10: 0.9780, MRR: 0.6561
valid [sampled], NDCG@5: 0.5538, HR@5: 0.5598, NDCG@10: 0.5685, HR@10: 0.6058, MRR: 0.5725
test [full], NDCG@5: 0.8231, HR@5: 0.9201, NDCG@10: 0.8479, HR@10: 1.0000, MRR: 0.7988
test [sampled], NDCG@5: 0.2111, HR@5: 0.2902, NDCG@10: 0.2997, HR@10: 0.5653, MRR: 0.2467
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0778
epoch=47, loss=0.0804
epoch=48, loss=0.0793
epoch=49, loss=0.0800
epoch=50, loss=0.0795
valid [full], NDCG@5: 0.6831, HR@5: 0.8073, NDCG@10: 0.7376, HR@10: 0.9765, MRR: 0.6669
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5677, NDCG@10: 0.5731, HR@10: 0.6146, MRR: 0.5760
test [full], NDCG@5: 0.8619, HR@5: 0.9203, NDCG@10: 0.8867, HR@10: 1.0000, MRR: 0.8516
test [sampled], NDCG@5: 0.3435, HR@5: 0.4305, NDCG@10: 0.4094, HR@10: 0.6312, MRR: 0.3614
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml100_do030_s42/sasrec_last.pth

## Train runs with `selection_metric = full_valid_ndcg@5`

### anchor_pd_s42

In [23]:
!python src/train_sasrec.py \
  --run_name anchor_pd_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 200 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42
epoch=1, loss=0.4974
epoch=2, loss=0.2282
epoch=3, loss=0.1655
epoch=4, loss=0.1360
epoch=5, loss=0.1199
valid [full], NDCG@5: 0.6457, HR@5: 0.7414, NDCG@10: 0.7226, HR@10: 0.9828, MRR: 0.6469
valid [sampled], NDCG@5: 0.5632, HR@5: 0.5772, NDCG@10: 0.5810, HR@10: 0.6324, MRR: 0.5772
test [full], NDCG@5: 0.5359, HR@5: 0.7313, NDCG@10: 0.6238, HR@10: 1.0000, MRR: 0.5074
test [sampled], NDCG@5: 0.1698, HR@5: 0.1750, NDCG@10: 0.2127, HR@10: 0.3140, MRR: 0.2129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/sasrec_best.pth
epoch=6, loss=0.1124
epoch=7, loss=0.1030
epoch=8, loss=0.0992
epoch=9, loss=0.0966
epoch=10, loss=0.0923
valid [full], NDCG@5: 0.6980, HR@5: 0.8756, NDCG@10: 0.7293, HR@10: 0.9753, MRR: 0.6558
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5715, NDCG@10: 0.5721, HR@10: 0.6113, MRR: 0.5756
test [full], NDCG@5: 0.6804, HR@5: 0.8952, NDCG@10: 0.7154, HR@10: 1.0000, MRR: 0.6228
test [sampled], NDCG@5: 0.1679, HR@5: 0.1809, NDCG@10: 0.2285, HR@10: 0.3746, MRR: 0.2214
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/sasrec_best.pth
epoch=11, loss=0.0916
epoch=12, loss=0.0896
epoch=13, loss=0.0875
epoch=14, loss=0.0869
epoch=15, loss=0.0875
valid [full], NDCG@5: 0.6519, HR@5: 0.7713, NDCG@10: 0.7199, HR@10: 0.9776, MRR: 0.6447
valid [sampled], NDCG@5: 0.5652, HR@5: 0.5730, NDCG@10: 0.5749, HR@10: 0.6033, MRR: 0.5801
test [full], NDCG@5: 0.6956, HR@5: 0.9285, NDCG@10: 0.7188, HR@10: 1.0000, MRR: 0.6260
test [sampled], NDCG@5: 0.1543, HR@5: 0.1608, NDCG@10: 0.2141, HR@10: 0.3545, MRR: 0.2126
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0873
epoch=17, loss=0.0838
epoch=18, loss=0.0833
epoch=19, loss=0.0829
epoch=20, loss=0.0818
valid [full], NDCG@5: 0.6580, HR@5: 0.7842, NDCG@10: 0.7207, HR@10: 0.9760, MRR: 0.6466
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5650, NDCG@10: 0.5669, HR@10: 0.5898, MRR: 0.5744
test [full], NDCG@5: 0.7722, HR@5: 0.9157, NDCG@10: 0.8002, HR@10: 1.0000, MRR: 0.7365
test [sampled], NDCG@5: 0.2045, HR@5: 0.2675, NDCG@10: 0.2660, HR@10: 0.4576, MRR: 0.2389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0816
epoch=22, loss=0.0815
epoch=23, loss=0.0812
epoch=24, loss=0.0797
epoch=25, loss=0.0815
valid [full], NDCG@5: 0.6420, HR@5: 0.7389, NDCG@10: 0.7180, HR@10: 0.9755, MRR: 0.6442
valid [sampled], NDCG@5: 0.5542, HR@5: 0.5650, NDCG@10: 0.5660, HR@10: 0.6010, MRR: 0.5681
test [full], NDCG@5: 0.7003, HR@5: 0.9287, NDCG@10: 0.7239, HR@10: 1.0000, MRR: 0.6322
test [sampled], NDCG@5: 0.1743, HR@5: 0.1864, NDCG@10: 0.2316, HR@10: 0.3717, MRR: 0.2295
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0795
epoch=27, loss=0.0796
epoch=28, loss=0.0797
epoch=29, loss=0.0810
epoch=30, loss=0.0797
valid [full], NDCG@5: 0.6878, HR@5: 0.8375, NDCG@10: 0.7328, HR@10: 0.9764, MRR: 0.6608
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5686, NDCG@10: 0.5719, HR@10: 0.6086, MRR: 0.5760
test [full], NDCG@5: 0.7415, HR@5: 0.9454, NDCG@10: 0.7593, HR@10: 1.0000, MRR: 0.6779
test [sampled], NDCG@5: 0.1989, HR@5: 0.2094, NDCG@10: 0.2660, HR@10: 0.4256, MRR: 0.2574
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0793
epoch=32, loss=0.0776
epoch=33, loss=0.0798
epoch=34, loss=0.0773
epoch=35, loss=0.0776
valid [full], NDCG@5: 0.6686, HR@5: 0.8068, NDCG@10: 0.7166, HR@10: 0.9565, MRR: 0.6478
valid [sampled], NDCG@5: 0.5600, HR@5: 0.5681, NDCG@10: 0.5722, HR@10: 0.6062, MRR: 0.5760
test [full], NDCG@5: 0.7990, HR@5: 0.9320, NDCG@10: 0.8210, HR@10: 1.0000, MRR: 0.7629
test [sampled], NDCG@5: 0.2178, HR@5: 0.2824, NDCG@10: 0.2869, HR@10: 0.4975, MRR: 0.2541
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0784
epoch=37, loss=0.0769
epoch=38, loss=0.0776
epoch=39, loss=0.0787
epoch=40, loss=0.0761
valid [full], NDCG@5: 0.6495, HR@5: 0.7723, NDCG@10: 0.7091, HR@10: 0.9544, MRR: 0.6396
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5631, NDCG@10: 0.5661, HR@10: 0.5856, MRR: 0.5746
test [full], NDCG@5: 0.8664, HR@5: 0.9372, NDCG@10: 0.8872, HR@10: 1.0000, MRR: 0.8518
test [sampled], NDCG@5: 0.3147, HR@5: 0.3903, NDCG@10: 0.3813, HR@10: 0.5955, MRR: 0.3403
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0776
epoch=42, loss=0.0766
epoch=43, loss=0.0785
epoch=44, loss=0.0780
epoch=45, loss=0.0766
valid [full], NDCG@5: 0.6504, HR@5: 0.7483, NDCG@10: 0.7172, HR@10: 0.9515, MRR: 0.6511
valid [sampled], NDCG@5: 0.5626, HR@5: 0.5739, NDCG@10: 0.5767, HR@10: 0.6172, MRR: 0.5762
test [full], NDCG@5: 0.8764, HR@5: 0.9285, NDCG@10: 0.8990, HR@10: 1.0000, MRR: 0.8677
test [sampled], NDCG@5: 0.3319, HR@5: 0.4129, NDCG@10: 0.4057, HR@10: 0.6395, MRR: 0.3557
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0748
epoch=47, loss=0.0771
epoch=48, loss=0.0759
epoch=49, loss=0.0764
epoch=50, loss=0.0767
valid [full], NDCG@5: 0.6473, HR@5: 0.7491, NDCG@10: 0.7143, HR@10: 0.9541, MRR: 0.6466
valid [sampled], NDCG@5: 0.5569, HR@5: 0.5647, NDCG@10: 0.5671, HR@10: 0.5966, MRR: 0.5712
test [full], NDCG@5: 0.7559, HR@5: 0.9178, NDCG@10: 0.7825, HR@10: 1.0000, MRR: 0.7128
test [sampled], NDCG@5: 0.2602, HR@5: 0.2904, NDCG@10: 0.3051, HR@10: 0.4314, MRR: 0.3003
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_pd_s42/sasrec_last.pth

### anchor_ml100_s42

In [24]:
!python src/train_sasrec.py \
  --run_name anchor_ml100_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 100 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42
epoch=1, loss=0.4891
epoch=2, loss=0.2275
epoch=3, loss=0.1620
epoch=4, loss=0.1320
epoch=5, loss=0.1166
valid [full], NDCG@5: 0.6230, HR@5: 0.6725, NDCG@10: 0.7174, HR@10: 0.9646, MRR: 0.6482
valid [sampled], NDCG@5: 0.5689, HR@5: 0.5814, NDCG@10: 0.5844, HR@10: 0.6298, MRR: 0.5812
test [full], NDCG@5: 0.4660, HR@5: 0.6063, NDCG@10: 0.5864, HR@10: 0.9842, MRR: 0.4681
test [sampled], NDCG@5: 0.1427, HR@5: 0.1480, NDCG@10: 0.1838, HR@10: 0.2807, MRR: 0.1835
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/sasrec_best.pth
epoch=6, loss=0.1066
epoch=7, loss=0.1002
epoch=8, loss=0.0960
epoch=9, loss=0.0940
epoch=10, loss=0.0905
valid [full], NDCG@5: 0.6381, HR@5: 0.7276, NDCG@10: 0.7152, HR@10: 0.9618, MRR: 0.6442
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5645, NDCG@10: 0.5698, HR@10: 0.6207, MRR: 0.5673
test [full], NDCG@5: 0.6412, HR@5: 0.8975, NDCG@10: 0.6749, HR@10: 0.9999, MRR: 0.5676
test [sampled], NDCG@5: 0.1367, HR@5: 0.1505, NDCG@10: 0.2033, HR@10: 0.3638, MRR: 0.1915
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/sasrec_best.pth
epoch=11, loss=0.0902
epoch=12, loss=0.0881
epoch=13, loss=0.0868
epoch=14, loss=0.0862
epoch=15, loss=0.0862
valid [full], NDCG@5: 0.6397, HR@5: 0.7314, NDCG@10: 0.7072, HR@10: 0.9410, MRR: 0.6430
valid [sampled], NDCG@5: 0.5669, HR@5: 0.5767, NDCG@10: 0.5785, HR@10: 0.6128, MRR: 0.5804
test [full], NDCG@5: 0.6873, HR@5: 0.9343, NDCG@10: 0.7093, HR@10: 1.0000, MRR: 0.6130
test [sampled], NDCG@5: 0.1339, HR@5: 0.1442, NDCG@10: 0.1866, HR@10: 0.3143, MRR: 0.1918
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/sasrec_best.pth
epoch=16, loss=0.0865
epoch=17, loss=0.0831
epoch=18, loss=0.0827
epoch=19, loss=0.0836
epoch=20, loss=0.0820
valid [full], NDCG@5: 0.6623, HR@5: 0.7759, NDCG@10: 0.7153, HR@10: 0.9405, MRR: 0.6522
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5627, NDCG@10: 0.5716, HR@10: 0.6059, MRR: 0.5756
test [full], NDCG@5: 0.7503, HR@5: 0.9453, NDCG@10: 0.7692, HR@10: 0.9999, MRR: 0.6916
test [sampled], NDCG@5: 0.1965, HR@5: 0.2178, NDCG@10: 0.2648, HR@10: 0.4356, MRR: 0.2507
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/sasrec_best.pth
epoch=21, loss=0.0816
epoch=22, loss=0.0814
epoch=23, loss=0.0807
epoch=24, loss=0.0797
epoch=25, loss=0.0815
valid [full], NDCG@5: 0.6469, HR@5: 0.7552, NDCG@10: 0.7106, HR@10: 0.9535, MRR: 0.6410
valid [sampled], NDCG@5: 0.5361, HR@5: 0.5450, NDCG@10: 0.5522, HR@10: 0.5956, MRR: 0.5534
test [full], NDCG@5: 0.7512, HR@5: 0.9433, NDCG@10: 0.7703, HR@10: 1.0000, MRR: 0.6925
test [sampled], NDCG@5: 0.1606, HR@5: 0.1883, NDCG@10: 0.2420, HR@10: 0.4479, MRR: 0.2180
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0794
epoch=27, loss=0.0799
epoch=28, loss=0.0796
epoch=29, loss=0.0809
epoch=30, loss=0.0803
valid [full], NDCG@5: 0.6648, HR@5: 0.7658, NDCG@10: 0.7313, HR@10: 0.9764, MRR: 0.6604
valid [sampled], NDCG@5: 0.5626, HR@5: 0.5767, NDCG@10: 0.5818, HR@10: 0.6367, MRR: 0.5776
test [full], NDCG@5: 0.7804, HR@5: 0.9199, NDCG@10: 0.8059, HR@10: 1.0000, MRR: 0.7415
test [sampled], NDCG@5: 0.2383, HR@5: 0.2755, NDCG@10: 0.3122, HR@10: 0.5090, MRR: 0.2848
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/sasrec_best.pth
epoch=31, loss=0.0789
epoch=32, loss=0.0775
epoch=33, loss=0.0793
epoch=34, loss=0.0765
epoch=35, loss=0.0782
valid [full], NDCG@5: 0.6577, HR@5: 0.7650, NDCG@10: 0.7194, HR@10: 0.9567, MRR: 0.6515
valid [sampled], NDCG@5: 0.5563, HR@5: 0.5668, NDCG@10: 0.5758, HR@10: 0.6280, MRR: 0.5732
test [full], NDCG@5: 0.7356, HR@5: 0.9222, NDCG@10: 0.7609, HR@10: 1.0000, MRR: 0.6833
test [sampled], NDCG@5: 0.2287, HR@5: 0.2579, NDCG@10: 0.2721, HR@10: 0.3945, MRR: 0.2712
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0781
epoch=37, loss=0.0770
epoch=38, loss=0.0777
epoch=39, loss=0.0778
epoch=40, loss=0.0761
valid [full], NDCG@5: 0.6486, HR@5: 0.7627, NDCG@10: 0.7103, HR@10: 0.9549, MRR: 0.6412
valid [sampled], NDCG@5: 0.5527, HR@5: 0.5577, NDCG@10: 0.5635, HR@10: 0.5918, MRR: 0.5696
test [full], NDCG@5: 0.7182, HR@5: 0.9127, NDCG@10: 0.7462, HR@10: 1.0000, MRR: 0.6686
test [sampled], NDCG@5: 0.2474, HR@5: 0.2710, NDCG@10: 0.2822, HR@10: 0.3796, MRR: 0.2838
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0779
epoch=42, loss=0.0778
epoch=43, loss=0.0784
epoch=44, loss=0.0776
epoch=45, loss=0.0769
valid [full], NDCG@5: 0.6814, HR@5: 0.8167, NDCG@10: 0.7259, HR@10: 0.9556, MRR: 0.6596
valid [sampled], NDCG@5: 0.5553, HR@5: 0.5644, NDCG@10: 0.5737, HR@10: 0.6222, MRR: 0.5734
test [full], NDCG@5: 0.7503, HR@5: 0.9131, NDCG@10: 0.7775, HR@10: 1.0000, MRR: 0.7062
test [sampled], NDCG@5: 0.3053, HR@5: 0.3213, NDCG@10: 0.3380, HR@10: 0.4258, MRR: 0.3456
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/sasrec_best.pth
epoch=46, loss=0.0745
epoch=47, loss=0.0766
epoch=48, loss=0.0758
epoch=49, loss=0.0765
epoch=50, loss=0.0759
valid [full], NDCG@5: 0.6650, HR@5: 0.7531, NDCG@10: 0.7308, HR@10: 0.9546, MRR: 0.6665
valid [sampled], NDCG@5: 0.5545, HR@5: 0.5610, NDCG@10: 0.5765, HR@10: 0.6311, MRR: 0.5742
test [full], NDCG@5: 0.7489, HR@5: 0.9164, NDCG@10: 0.7753, HR@10: 1.0000, MRR: 0.7028
test [sampled], NDCG@5: 0.2856, HR@5: 0.3045, NDCG@10: 0.3206, HR@10: 0.4154, MRR: 0.3265
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml100_s42/sasrec_last.pth

### anchor_ml50_s42

In [25]:
!python src/train_sasrec.py \
  --run_name anchor_ml50_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42
epoch=1, loss=0.4793
epoch=2, loss=0.2166
epoch=3, loss=0.1564
epoch=4, loss=0.1245
epoch=5, loss=0.1127
valid [full], NDCG@5: 0.6566, HR@5: 0.7705, NDCG@10: 0.7221, HR@10: 0.9808, MRR: 0.6467
valid [sampled], NDCG@5: 0.5561, HR@5: 0.5710, NDCG@10: 0.5758, HR@10: 0.6326, MRR: 0.5713
test [full], NDCG@5: 0.4875, HR@5: 0.6521, NDCG@10: 0.5959, HR@10: 0.9999, MRR: 0.4741
test [sampled], NDCG@5: 0.1370, HR@5: 0.1437, NDCG@10: 0.1829, HR@10: 0.2915, MRR: 0.1796
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/sasrec_best.pth
epoch=6, loss=0.1045
epoch=7, loss=0.1006
epoch=8, loss=0.0948
epoch=9, loss=0.0927
epoch=10, loss=0.0919
valid [full], NDCG@5: 0.6540, HR@5: 0.7700, NDCG@10: 0.7208, HR@10: 0.9735, MRR: 0.6471
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5737, NDCG@10: 0.5728, HR@10: 0.6132, MRR: 0.5738
test [full], NDCG@5: 0.6773, HR@5: 0.9070, NDCG@10: 0.7068, HR@10: 1.0000, MRR: 0.6098
test [sampled], NDCG@5: 0.1461, HR@5: 0.1717, NDCG@10: 0.2125, HR@10: 0.3837, MRR: 0.1974
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0904
epoch=12, loss=0.0884
epoch=13, loss=0.0869
epoch=14, loss=0.0868
epoch=15, loss=0.0873
valid [full], NDCG@5: 0.6948, HR@5: 0.8606, NDCG@10: 0.7322, HR@10: 0.9777, MRR: 0.6585
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5713, NDCG@10: 0.5752, HR@10: 0.6215, MRR: 0.5770
test [full], NDCG@5: 0.7971, HR@5: 0.9206, NDCG@10: 0.8220, HR@10: 1.0000, MRR: 0.7641
test [sampled], NDCG@5: 0.2187, HR@5: 0.2901, NDCG@10: 0.2918, HR@10: 0.5167, MRR: 0.2530
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/sasrec_best.pth
epoch=16, loss=0.0839
epoch=17, loss=0.0821
epoch=18, loss=0.0825
epoch=19, loss=0.0827
epoch=20, loss=0.0822
valid [full], NDCG@5: 0.6654, HR@5: 0.7984, NDCG@10: 0.7239, HR@10: 0.9760, MRR: 0.6502
valid [sampled], NDCG@5: 0.5583, HR@5: 0.5677, NDCG@10: 0.5711, HR@10: 0.6075, MRR: 0.5738
test [full], NDCG@5: 0.7567, HR@5: 0.8934, NDCG@10: 0.7911, HR@10: 1.0000, MRR: 0.7239
test [sampled], NDCG@5: 0.1517, HR@5: 0.2231, NDCG@10: 0.2319, HR@10: 0.4725, MRR: 0.1909
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0798
epoch=22, loss=0.0806
epoch=23, loss=0.0809
epoch=24, loss=0.0806
epoch=25, loss=0.0796
valid [full], NDCG@5: 0.6334, HR@5: 0.7361, NDCG@10: 0.7038, HR@10: 0.9503, MRR: 0.6338
valid [sampled], NDCG@5: 0.5277, HR@5: 0.5397, NDCG@10: 0.5448, HR@10: 0.5923, MRR: 0.5438
test [full], NDCG@5: 0.7536, HR@5: 0.9168, NDCG@10: 0.7793, HR@10: 1.0000, MRR: 0.7066
test [sampled], NDCG@5: 0.1976, HR@5: 0.2314, NDCG@10: 0.2765, HR@10: 0.4808, MRR: 0.2484
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0790
epoch=27, loss=0.0806
epoch=28, loss=0.0789
epoch=29, loss=0.0807
epoch=30, loss=0.0798
valid [full], NDCG@5: 0.6578, HR@5: 0.7867, NDCG@10: 0.7196, HR@10: 0.9764, MRR: 0.6446
valid [sampled], NDCG@5: 0.5435, HR@5: 0.5470, NDCG@10: 0.5548, HR@10: 0.5830, MRR: 0.5619
test [full], NDCG@5: 0.8511, HR@5: 0.9206, NDCG@10: 0.8755, HR@10: 1.0000, MRR: 0.8369
test [sampled], NDCG@5: 0.2673, HR@5: 0.3530, NDCG@10: 0.3479, HR@10: 0.6010, MRR: 0.2946
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0798
epoch=32, loss=0.0786
epoch=33, loss=0.0794
epoch=34, loss=0.0785
epoch=35, loss=0.0777
valid [full], NDCG@5: 0.6451, HR@5: 0.7696, NDCG@10: 0.7125, HR@10: 0.9773, MRR: 0.6356
valid [sampled], NDCG@5: 0.5524, HR@5: 0.5555, NDCG@10: 0.5614, HR@10: 0.5840, MRR: 0.5696
test [full], NDCG@5: 0.8443, HR@5: 0.9113, NDCG@10: 0.8724, HR@10: 1.0000, MRR: 0.8332
test [sampled], NDCG@5: 0.2810, HR@5: 0.3656, NDCG@10: 0.3575, HR@10: 0.6017, MRR: 0.3063
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0778
epoch=37, loss=0.0768
epoch=38, loss=0.0769
epoch=39, loss=0.0776
epoch=40, loss=0.0783
valid [full], NDCG@5: 0.6622, HR@5: 0.7988, NDCG@10: 0.7111, HR@10: 0.9507, MRR: 0.6430
valid [sampled], NDCG@5: 0.5575, HR@5: 0.5592, NDCG@10: 0.5654, HR@10: 0.5843, MRR: 0.5750
test [full], NDCG@5: 0.8631, HR@5: 0.9248, NDCG@10: 0.8866, HR@10: 1.0000, MRR: 0.8518
test [sampled], NDCG@5: 0.3200, HR@5: 0.3984, NDCG@10: 0.3870, HR@10: 0.6039, MRR: 0.3437
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0783
epoch=42, loss=0.0782
epoch=43, loss=0.0778
epoch=44, loss=0.0770
epoch=45, loss=0.0775
valid [full], NDCG@5: 0.6431, HR@5: 0.7968, NDCG@10: 0.6929, HR@10: 0.9514, MRR: 0.6180
valid [sampled], NDCG@5: 0.5036, HR@5: 0.5058, NDCG@10: 0.5133, HR@10: 0.5373, MRR: 0.5243
test [full], NDCG@5: 0.8601, HR@5: 0.9249, NDCG@10: 0.8836, HR@10: 1.0000, MRR: 0.8476
test [sampled], NDCG@5: 0.3805, HR@5: 0.4444, NDCG@10: 0.4362, HR@10: 0.6156, MRR: 0.4035
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0754
epoch=47, loss=0.0761
epoch=48, loss=0.0759
epoch=49, loss=0.0761
epoch=50, loss=0.0759
valid [full], NDCG@5: 0.6497, HR@5: 0.7787, NDCG@10: 0.7055, HR@10: 0.9513, MRR: 0.6348
valid [sampled], NDCG@5: 0.5306, HR@5: 0.5325, NDCG@10: 0.5392, HR@10: 0.5602, MRR: 0.5493
test [full], NDCG@5: 0.8572, HR@5: 0.9264, NDCG@10: 0.8803, HR@10: 1.0000, MRR: 0.8431
test [sampled], NDCG@5: 0.3985, HR@5: 0.4598, NDCG@10: 0.4479, HR@10: 0.6112, MRR: 0.4190
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml50_s42/sasrec_last.pth

### anchor_ml20_s42

In [26]:
!python src/train_sasrec.py \
  --run_name anchor_ml20_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42
epoch=1, loss=0.6703
epoch=2, loss=0.3156
epoch=3, loss=0.2178
epoch=4, loss=0.1735
epoch=5, loss=0.1464
valid [full], NDCG@5: 0.7050, HR@5: 0.8805, NDCG@10: 0.7424, HR@10: 0.9916, MRR: 0.6648
valid [sampled], NDCG@5: 0.5452, HR@5: 0.5520, NDCG@10: 0.5650, HR@10: 0.6151, MRR: 0.5682
test [full], NDCG@5: 0.8392, HR@5: 0.9371, NDCG@10: 0.8599, HR@10: 1.0000, MRR: 0.8146
test [sampled], NDCG@5: 0.1971, HR@5: 0.2797, NDCG@10: 0.2821, HR@10: 0.5416, MRR: 0.2314
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/sasrec_best.pth
epoch=6, loss=0.1322
epoch=7, loss=0.1238
epoch=8, loss=0.1171
epoch=9, loss=0.1131
epoch=10, loss=0.1092
valid [full], NDCG@5: 0.6742, HR@5: 0.8562, NDCG@10: 0.7120, HR@10: 0.9734, MRR: 0.6334
valid [sampled], NDCG@5: 0.5228, HR@5: 0.5274, NDCG@10: 0.5369, HR@10: 0.5729, MRR: 0.5446
test [full], NDCG@5: 0.8288, HR@5: 0.9454, NDCG@10: 0.8470, HR@10: 0.9999, MRR: 0.7970
test [sampled], NDCG@5: 0.3035, HR@5: 0.3738, NDCG@10: 0.3708, HR@10: 0.5821, MRR: 0.3303
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1086
epoch=12, loss=0.1067
epoch=13, loss=0.1041
epoch=14, loss=0.1027
epoch=15, loss=0.1021
valid [full], NDCG@5: 0.6804, HR@5: 0.8697, NDCG@10: 0.7143, HR@10: 0.9758, MRR: 0.6355
valid [sampled], NDCG@5: 0.5274, HR@5: 0.5321, NDCG@10: 0.5376, HR@10: 0.5648, MRR: 0.5483
test [full], NDCG@5: 0.8901, HR@5: 0.9945, NDCG@10: 0.8920, HR@10: 1.0000, MRR: 0.8564
test [sampled], NDCG@5: 0.3154, HR@5: 0.3981, NDCG@10: 0.3880, HR@10: 0.6220, MRR: 0.3401
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.1001
epoch=17, loss=0.0988
epoch=18, loss=0.0989
epoch=19, loss=0.0967
epoch=20, loss=0.0975
valid [full], NDCG@5: 0.6752, HR@5: 0.8547, NDCG@10: 0.7144, HR@10: 0.9757, MRR: 0.6360
valid [sampled], NDCG@5: 0.5226, HR@5: 0.5262, NDCG@10: 0.5329, HR@10: 0.5594, MRR: 0.5437
test [full], NDCG@5: 0.8838, HR@5: 0.9778, NDCG@10: 0.8915, HR@10: 0.9999, MRR: 0.8560
test [sampled], NDCG@5: 0.3369, HR@5: 0.4147, NDCG@10: 0.4050, HR@10: 0.6241, MRR: 0.3615
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0959
epoch=22, loss=0.0971
epoch=23, loss=0.0959
epoch=24, loss=0.0952
epoch=25, loss=0.0929
valid [full], NDCG@5: 0.6875, HR@5: 0.8651, NDCG@10: 0.7223, HR@10: 0.9755, MRR: 0.6459
valid [sampled], NDCG@5: 0.5211, HR@5: 0.5269, NDCG@10: 0.5374, HR@10: 0.5787, MRR: 0.5438
test [full], NDCG@5: 0.9018, HR@5: 0.9985, NDCG@10: 0.9023, HR@10: 1.0000, MRR: 0.8693
test [sampled], NDCG@5: 0.3587, HR@5: 0.4302, NDCG@10: 0.4253, HR@10: 0.6355, MRR: 0.3851
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0930
epoch=27, loss=0.0946
epoch=28, loss=0.0938
epoch=29, loss=0.0940
epoch=30, loss=0.0926
valid [full], NDCG@5: 0.6919, HR@5: 0.8413, NDCG@10: 0.7357, HR@10: 0.9764, MRR: 0.6636
valid [sampled], NDCG@5: 0.5498, HR@5: 0.5555, NDCG@10: 0.5668, HR@10: 0.6092, MRR: 0.5715
test [full], NDCG@5: 0.8918, HR@5: 0.9993, NDCG@10: 0.8920, HR@10: 1.0000, MRR: 0.8556
test [sampled], NDCG@5: 0.3868, HR@5: 0.4563, NDCG@10: 0.4423, HR@10: 0.6268, MRR: 0.4087
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0940
epoch=32, loss=0.0908
epoch=33, loss=0.0918
epoch=34, loss=0.0898
epoch=35, loss=0.0902
valid [full], NDCG@5: 0.6693, HR@5: 0.8005, NDCG@10: 0.7257, HR@10: 0.9768, MRR: 0.6517
valid [sampled], NDCG@5: 0.5538, HR@5: 0.5597, NDCG@10: 0.5685, HR@10: 0.6061, MRR: 0.5731
test [full], NDCG@5: 0.9021, HR@5: 0.9929, NDCG@10: 0.9046, HR@10: 1.0000, MRR: 0.8727
test [sampled], NDCG@5: 0.3976, HR@5: 0.4687, NDCG@10: 0.4550, HR@10: 0.6454, MRR: 0.4196
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0888
epoch=37, loss=0.0913
epoch=38, loss=0.0899
epoch=39, loss=0.0903
epoch=40, loss=0.0885
valid [full], NDCG@5: 0.6885, HR@5: 0.8269, NDCG@10: 0.7352, HR@10: 0.9758, MRR: 0.6639
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5669, NDCG@10: 0.5793, HR@10: 0.6283, MRR: 0.5808
test [full], NDCG@5: 0.9154, HR@5: 0.9988, NDCG@10: 0.9158, HR@10: 1.0000, MRR: 0.8872
test [sampled], NDCG@5: 0.4116, HR@5: 0.4741, NDCG@10: 0.4661, HR@10: 0.6417, MRR: 0.4356
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0902
epoch=42, loss=0.0892
epoch=43, loss=0.0902
epoch=44, loss=0.0881
epoch=45, loss=0.0913
valid [full], NDCG@5: 0.7025, HR@5: 0.8598, NDCG@10: 0.7401, HR@10: 0.9780, MRR: 0.6687
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5625, NDCG@10: 0.5745, HR@10: 0.6209, MRR: 0.5778
test [full], NDCG@5: 0.9003, HR@5: 0.9954, NDCG@10: 0.9020, HR@10: 1.0000, MRR: 0.8690
test [sampled], NDCG@5: 0.3840, HR@5: 0.4518, NDCG@10: 0.4470, HR@10: 0.6450, MRR: 0.4094
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0848
epoch=47, loss=0.0888
epoch=48, loss=0.0873
epoch=49, loss=0.0878
epoch=50, loss=0.0870
valid [full], NDCG@5: 0.7088, HR@5: 0.8485, NDCG@10: 0.7504, HR@10: 0.9775, MRR: 0.6818
valid [sampled], NDCG@5: 0.5564, HR@5: 0.5678, NDCG@10: 0.5837, HR@10: 0.6543, MRR: 0.5784
test [full], NDCG@5: 0.9138, HR@5: 0.9958, NDCG@10: 0.9153, HR@10: 1.0000, MRR: 0.8868
test [sampled], NDCG@5: 0.4066, HR@5: 0.4733, NDCG@10: 0.4649, HR@10: 0.6525, MRR: 0.4302
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s42/sasrec_last.pth

### refine_ml50_do030_s42

In [27]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do030_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42
epoch=1, loss=0.5360
epoch=2, loss=0.2475
epoch=3, loss=0.1849
epoch=4, loss=0.1493
epoch=5, loss=0.1305
valid [full], NDCG@5: 0.6477, HR@5: 0.7576, NDCG@10: 0.6943, HR@10: 0.9076, MRR: 0.6380
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5666, NDCG@10: 0.5702, HR@10: 0.6159, MRR: 0.5690
test [full], NDCG@5: 0.4378, HR@5: 0.5577, NDCG@10: 0.5739, HR@10: 0.9914, MRR: 0.4509
test [sampled], NDCG@5: 0.1360, HR@5: 0.1425, NDCG@10: 0.1793, HR@10: 0.2819, MRR: 0.1759
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/sasrec_best.pth
epoch=6, loss=0.1189
epoch=7, loss=0.1129
epoch=8, loss=0.1061
epoch=9, loss=0.1020
epoch=10, loss=0.1001
valid [full], NDCG@5: 0.6349, HR@5: 0.7316, NDCG@10: 0.7103, HR@10: 0.9705, MRR: 0.6365
valid [sampled], NDCG@5: 0.5581, HR@5: 0.5718, NDCG@10: 0.5709, HR@10: 0.6110, MRR: 0.5704
test [full], NDCG@5: 0.7211, HR@5: 0.8743, NDCG@10: 0.7620, HR@10: 1.0000, MRR: 0.6854
test [sampled], NDCG@5: 0.1905, HR@5: 0.2607, NDCG@10: 0.2593, HR@10: 0.4741, MRR: 0.2214
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0980
epoch=12, loss=0.0960
epoch=13, loss=0.0940
epoch=14, loss=0.0936
epoch=15, loss=0.0941
valid [full], NDCG@5: 0.6839, HR@5: 0.8331, NDCG@10: 0.7284, HR@10: 0.9753, MRR: 0.6559
valid [sampled], NDCG@5: 0.5708, HR@5: 0.5829, NDCG@10: 0.5855, HR@10: 0.6286, MRR: 0.5861
test [full], NDCG@5: 0.8195, HR@5: 0.9279, NDCG@10: 0.8431, HR@10: 1.0000, MRR: 0.7924
test [sampled], NDCG@5: 0.2151, HR@5: 0.2973, NDCG@10: 0.2941, HR@10: 0.5413, MRR: 0.2469
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/sasrec_best.pth
epoch=16, loss=0.0896
epoch=17, loss=0.0883
epoch=18, loss=0.0881
epoch=19, loss=0.0877
epoch=20, loss=0.0876
valid [full], NDCG@5: 0.6424, HR@5: 0.7353, NDCG@10: 0.7155, HR@10: 0.9662, MRR: 0.6450
valid [sampled], NDCG@5: 0.5648, HR@5: 0.5715, NDCG@10: 0.5749, HR@10: 0.6029, MRR: 0.5790
test [full], NDCG@5: 0.8084, HR@5: 0.8774, NDCG@10: 0.8483, HR@10: 1.0000, MRR: 0.8010
test [sampled], NDCG@5: 0.2331, HR@5: 0.3226, NDCG@10: 0.3147, HR@10: 0.5742, MRR: 0.2605
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0855
epoch=22, loss=0.0855
epoch=23, loss=0.0861
epoch=24, loss=0.0857
epoch=25, loss=0.0844
valid [full], NDCG@5: 0.6385, HR@5: 0.7415, NDCG@10: 0.7063, HR@10: 0.9536, MRR: 0.6373
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5527, NDCG@10: 0.5580, HR@10: 0.5890, MRR: 0.5617
test [full], NDCG@5: 0.8463, HR@5: 0.9045, NDCG@10: 0.8766, HR@10: 1.0000, MRR: 0.8388
test [sampled], NDCG@5: 0.2854, HR@5: 0.3719, NDCG@10: 0.3636, HR@10: 0.6114, MRR: 0.3097
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0832
epoch=27, loss=0.0852
epoch=28, loss=0.0831
epoch=29, loss=0.0843
epoch=30, loss=0.0843
valid [full], NDCG@5: 0.6472, HR@5: 0.7611, NDCG@10: 0.7164, HR@10: 0.9764, MRR: 0.6415
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5545, NDCG@10: 0.5601, HR@10: 0.5837, MRR: 0.5672
test [full], NDCG@5: 0.8502, HR@5: 0.9105, NDCG@10: 0.8787, HR@10: 1.0000, MRR: 0.8417
test [sampled], NDCG@5: 0.2362, HR@5: 0.3175, NDCG@10: 0.3218, HR@10: 0.5821, MRR: 0.2677
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0837
epoch=32, loss=0.0823
epoch=33, loss=0.0832
epoch=34, loss=0.0824
epoch=35, loss=0.0812
valid [full], NDCG@5: 0.6380, HR@5: 0.7530, NDCG@10: 0.7038, HR@10: 0.9553, MRR: 0.6329
valid [sampled], NDCG@5: 0.5548, HR@5: 0.5564, NDCG@10: 0.5615, HR@10: 0.5774, MRR: 0.5712
test [full], NDCG@5: 0.8221, HR@5: 0.8984, NDCG@10: 0.8546, HR@10: 1.0000, MRR: 0.8098
test [sampled], NDCG@5: 0.2346, HR@5: 0.3192, NDCG@10: 0.3073, HR@10: 0.5430, MRR: 0.2610
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0814
epoch=37, loss=0.0802
epoch=38, loss=0.0811
epoch=39, loss=0.0809
epoch=40, loss=0.0818
valid [full], NDCG@5: 0.6586, HR@5: 0.7976, NDCG@10: 0.7084, HR@10: 0.9524, MRR: 0.6391
valid [sampled], NDCG@5: 0.5543, HR@5: 0.5565, NDCG@10: 0.5623, HR@10: 0.5821, MRR: 0.5711
test [full], NDCG@5: 0.8551, HR@5: 0.9243, NDCG@10: 0.8787, HR@10: 1.0000, MRR: 0.8414
test [sampled], NDCG@5: 0.3003, HR@5: 0.3781, NDCG@10: 0.3675, HR@10: 0.5846, MRR: 0.3252
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0813
epoch=42, loss=0.0819
epoch=43, loss=0.0809
epoch=44, loss=0.0808
epoch=45, loss=0.0809
valid [full], NDCG@5: 0.6573, HR@5: 0.7835, NDCG@10: 0.7120, HR@10: 0.9522, MRR: 0.6438
valid [sampled], NDCG@5: 0.5523, HR@5: 0.5555, NDCG@10: 0.5609, HR@10: 0.5827, MRR: 0.5692
test [full], NDCG@5: 0.8519, HR@5: 0.9219, NDCG@10: 0.8762, HR@10: 1.0000, MRR: 0.8379
test [sampled], NDCG@5: 0.3119, HR@5: 0.3891, NDCG@10: 0.3796, HR@10: 0.5969, MRR: 0.3364
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0788
epoch=47, loss=0.0798
epoch=48, loss=0.0799
epoch=49, loss=0.0792
epoch=50, loss=0.0788
valid [full], NDCG@5: 0.6709, HR@5: 0.8454, NDCG@10: 0.7048, HR@10: 0.9528, MRR: 0.6325
valid [sampled], NDCG@5: 0.5137, HR@5: 0.5198, NDCG@10: 0.5257, HR@10: 0.5576, MRR: 0.5338
test [full], NDCG@5: 0.8499, HR@5: 0.9215, NDCG@10: 0.8744, HR@10: 1.0000, MRR: 0.8352
test [sampled], NDCG@5: 0.3932, HR@5: 0.4563, NDCG@10: 0.4451, HR@10: 0.6153, MRR: 0.4133
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s42/sasrec_last.pth

### refine_ml50_do035_s42

In [28]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42
epoch=1, loss=0.5673
epoch=2, loss=0.2638
epoch=3, loss=0.1987
epoch=4, loss=0.1638
epoch=5, loss=0.1414
valid [full], NDCG@5: 0.6434, HR@5: 0.7559, NDCG@10: 0.6854, HR@10: 0.8896, MRR: 0.6333
valid [sampled], NDCG@5: 0.5545, HR@5: 0.5603, NDCG@10: 0.5654, HR@10: 0.5947, MRR: 0.5698
test [full], NDCG@5: 0.4390, HR@5: 0.6201, NDCG@10: 0.5094, HR@10: 0.8432, MRR: 0.4211
test [sampled], NDCG@5: 0.1322, HR@5: 0.1359, NDCG@10: 0.1472, HR@10: 0.1844, MRR: 0.1664
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1290
epoch=7, loss=0.1210
epoch=8, loss=0.1137
epoch=9, loss=0.1093
epoch=10, loss=0.1068
valid [full], NDCG@5: 0.6132, HR@5: 0.6798, NDCG@10: 0.7075, HR@10: 0.9700, MRR: 0.6332
valid [sampled], NDCG@5: 0.5556, HR@5: 0.5692, NDCG@10: 0.5683, HR@10: 0.6082, MRR: 0.5675
test [full], NDCG@5: 0.7193, HR@5: 0.8732, NDCG@10: 0.7595, HR@10: 1.0000, MRR: 0.6825
test [sampled], NDCG@5: 0.1816, HR@5: 0.2519, NDCG@10: 0.2515, HR@10: 0.4689, MRR: 0.2129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1033
epoch=12, loss=0.1010
epoch=13, loss=0.0993
epoch=14, loss=0.0983
epoch=15, loss=0.0982
valid [full], NDCG@5: 0.6582, HR@5: 0.7812, NDCG@10: 0.7176, HR@10: 0.9712, MRR: 0.6447
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5788, NDCG@10: 0.5795, HR@10: 0.6176, MRR: 0.5805
test [full], NDCG@5: 0.7798, HR@5: 0.8926, NDCG@10: 0.8145, HR@10: 1.0000, MRR: 0.7553
test [sampled], NDCG@5: 0.2096, HR@5: 0.2901, NDCG@10: 0.2837, HR@10: 0.5181, MRR: 0.2392
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0938
epoch=17, loss=0.0921
epoch=18, loss=0.0919
epoch=19, loss=0.0913
epoch=20, loss=0.0912
valid [full], NDCG@5: 0.6678, HR@5: 0.7918, NDCG@10: 0.7258, HR@10: 0.9677, MRR: 0.6559
valid [sampled], NDCG@5: 0.5678, HR@5: 0.5781, NDCG@10: 0.5793, HR@10: 0.6135, MRR: 0.5818
test [full], NDCG@5: 0.8150, HR@5: 0.9157, NDCG@10: 0.8413, HR@10: 0.9999, MRR: 0.7912
test [sampled], NDCG@5: 0.2193, HR@5: 0.3068, NDCG@10: 0.3005, HR@10: 0.5576, MRR: 0.2482
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_best.pth
epoch=21, loss=0.0892
epoch=22, loss=0.0887
epoch=23, loss=0.0893
epoch=24, loss=0.0884
epoch=25, loss=0.0879
valid [full], NDCG@5: 0.6722, HR@5: 0.8205, NDCG@10: 0.7192, HR@10: 0.9664, MRR: 0.6469
valid [sampled], NDCG@5: 0.5401, HR@5: 0.5508, NDCG@10: 0.5553, HR@10: 0.5977, MRR: 0.5573
test [full], NDCG@5: 0.8439, HR@5: 0.9245, NDCG@10: 0.8668, HR@10: 0.9999, MRR: 0.8250
test [sampled], NDCG@5: 0.2562, HR@5: 0.3499, NDCG@10: 0.3416, HR@10: 0.6114, MRR: 0.2819
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_best.pth
epoch=26, loss=0.0865
epoch=27, loss=0.0884
epoch=28, loss=0.0859
epoch=29, loss=0.0870
epoch=30, loss=0.0869
valid [full], NDCG@5: 0.6817, HR@5: 0.8317, NDCG@10: 0.7279, HR@10: 0.9749, MRR: 0.6555
valid [sampled], NDCG@5: 0.5619, HR@5: 0.5660, NDCG@10: 0.5710, HR@10: 0.5946, MRR: 0.5791
test [full], NDCG@5: 0.8127, HR@5: 0.9201, NDCG@10: 0.8373, HR@10: 1.0000, MRR: 0.7857
test [sampled], NDCG@5: 0.1741, HR@5: 0.2645, NDCG@10: 0.2634, HR@10: 0.5397, MRR: 0.2062
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_best.pth
epoch=31, loss=0.0868
epoch=32, loss=0.0853
epoch=33, loss=0.0859
epoch=34, loss=0.0851
epoch=35, loss=0.0836
valid [full], NDCG@5: 0.6720, HR@5: 0.8324, NDCG@10: 0.7155, HR@10: 0.9698, MRR: 0.6414
valid [sampled], NDCG@5: 0.5550, HR@5: 0.5571, NDCG@10: 0.5615, HR@10: 0.5777, MRR: 0.5726
test [full], NDCG@5: 0.8381, HR@5: 0.9183, NDCG@10: 0.8629, HR@10: 0.9999, MRR: 0.8211
test [sampled], NDCG@5: 0.2152, HR@5: 0.3021, NDCG@10: 0.2995, HR@10: 0.5623, MRR: 0.2450
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0842
epoch=37, loss=0.0825
epoch=38, loss=0.0835
epoch=39, loss=0.0839
epoch=40, loss=0.0842
valid [full], NDCG@5: 0.6761, HR@5: 0.8327, NDCG@10: 0.7220, HR@10: 0.9754, MRR: 0.6473
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5566, NDCG@10: 0.5612, HR@10: 0.5760, MRR: 0.5737
test [full], NDCG@5: 0.8332, HR@5: 0.9225, NDCG@10: 0.8567, HR@10: 1.0000, MRR: 0.8122
test [sampled], NDCG@5: 0.2043, HR@5: 0.2897, NDCG@10: 0.2871, HR@10: 0.5451, MRR: 0.2353
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0837
epoch=42, loss=0.0842
epoch=43, loss=0.0833
epoch=44, loss=0.0830
epoch=45, loss=0.0832
valid [full], NDCG@5: 0.6901, HR@5: 0.8644, NDCG@10: 0.7262, HR@10: 0.9775, MRR: 0.6512
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5502, NDCG@10: 0.5561, HR@10: 0.5811, MRR: 0.5662
test [full], NDCG@5: 0.8615, HR@5: 0.9514, NDCG@10: 0.8778, HR@10: 1.0000, MRR: 0.8387
test [sampled], NDCG@5: 0.2836, HR@5: 0.3660, NDCG@10: 0.3571, HR@10: 0.5917, MRR: 0.3104
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_best.pth
epoch=46, loss=0.0806
epoch=47, loss=0.0818
epoch=48, loss=0.0822
epoch=49, loss=0.0818
epoch=50, loss=0.0810
valid [full], NDCG@5: 0.6974, HR@5: 0.8542, NDCG@10: 0.7354, HR@10: 0.9773, MRR: 0.6635
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5651, NDCG@10: 0.5687, HR@10: 0.6064, MRR: 0.5728
test [full], NDCG@5: 0.8687, HR@5: 0.9264, NDCG@10: 0.8918, HR@10: 1.0000, MRR: 0.8584
test [sampled], NDCG@5: 0.3995, HR@5: 0.4674, NDCG@10: 0.4560, HR@10: 0.6406, MRR: 0.4192
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s42/sasrec_last.pth

### refine_ml50_do025_s42

In [29]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do025_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42
epoch=1, loss=0.5066
epoch=2, loss=0.2315
epoch=3, loss=0.1700
epoch=4, loss=0.1361
epoch=5, loss=0.1203
valid [full], NDCG@5: 0.6551, HR@5: 0.7708, NDCG@10: 0.7204, HR@10: 0.9803, MRR: 0.6446
valid [sampled], NDCG@5: 0.5541, HR@5: 0.5661, NDCG@10: 0.5730, HR@10: 0.6257, MRR: 0.5705
test [full], NDCG@5: 0.4666, HR@5: 0.6195, NDCG@10: 0.5856, HR@10: 1.0000, MRR: 0.4610
test [sampled], NDCG@5: 0.1341, HR@5: 0.1405, NDCG@10: 0.1812, HR@10: 0.2923, MRR: 0.1766
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/sasrec_best.pth
epoch=6, loss=0.1109
epoch=7, loss=0.1059
epoch=8, loss=0.0996
epoch=9, loss=0.0969
epoch=10, loss=0.0953
valid [full], NDCG@5: 0.6791, HR@5: 0.8402, NDCG@10: 0.7203, HR@10: 0.9686, MRR: 0.6477
valid [sampled], NDCG@5: 0.5577, HR@5: 0.5710, NDCG@10: 0.5692, HR@10: 0.6063, MRR: 0.5719
test [full], NDCG@5: 0.6568, HR@5: 0.9186, NDCG@10: 0.6822, HR@10: 1.0000, MRR: 0.5765
test [sampled], NDCG@5: 0.1575, HR@5: 0.1747, NDCG@10: 0.2177, HR@10: 0.3680, MRR: 0.2085
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/sasrec_best.pth
epoch=11, loss=0.0933
epoch=12, loss=0.0914
epoch=13, loss=0.0901
epoch=14, loss=0.0898
epoch=15, loss=0.0901
valid [full], NDCG@5: 0.6988, HR@5: 0.8559, NDCG@10: 0.7373, HR@10: 0.9753, MRR: 0.6664
valid [sampled], NDCG@5: 0.5767, HR@5: 0.5888, NDCG@10: 0.5903, HR@10: 0.6309, MRR: 0.5927
test [full], NDCG@5: 0.7330, HR@5: 0.9227, NDCG@10: 0.7572, HR@10: 1.0000, MRR: 0.6762
test [sampled], NDCG@5: 0.1715, HR@5: 0.1972, NDCG@10: 0.2436, HR@10: 0.4273, MRR: 0.2259
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/sasrec_best.pth
epoch=16, loss=0.0862
epoch=17, loss=0.0846
epoch=18, loss=0.0851
epoch=19, loss=0.0848
epoch=20, loss=0.0844
valid [full], NDCG@5: 0.6580, HR@5: 0.7767, NDCG@10: 0.7231, HR@10: 0.9760, MRR: 0.6494
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5702, NDCG@10: 0.5717, HR@10: 0.6117, MRR: 0.5727
test [full], NDCG@5: 0.7323, HR@5: 0.8943, NDCG@10: 0.7665, HR@10: 1.0000, MRR: 0.6902
test [sampled], NDCG@5: 0.1947, HR@5: 0.2281, NDCG@10: 0.2680, HR@10: 0.4608, MRR: 0.2437
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0824
epoch=22, loss=0.0828
epoch=23, loss=0.0831
epoch=24, loss=0.0828
epoch=25, loss=0.0816
valid [full], NDCG@5: 0.6411, HR@5: 0.7720, NDCG@10: 0.7057, HR@10: 0.9755, MRR: 0.6273
valid [sampled], NDCG@5: 0.5246, HR@5: 0.5300, NDCG@10: 0.5367, HR@10: 0.5681, MRR: 0.5424
test [full], NDCG@5: 0.8659, HR@5: 0.9249, NDCG@10: 0.8894, HR@10: 1.0000, MRR: 0.8557
test [sampled], NDCG@5: 0.2910, HR@5: 0.3803, NDCG@10: 0.3708, HR@10: 0.6239, MRR: 0.3147
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0810
epoch=27, loss=0.0827
epoch=28, loss=0.0812
epoch=29, loss=0.0823
epoch=30, loss=0.0821
valid [full], NDCG@5: 0.6667, HR@5: 0.7998, NDCG@10: 0.7247, HR@10: 0.9764, MRR: 0.6508
valid [sampled], NDCG@5: 0.5511, HR@5: 0.5584, NDCG@10: 0.5632, HR@10: 0.5960, MRR: 0.5682
test [full], NDCG@5: 0.8700, HR@5: 0.9218, NDCG@10: 0.8945, HR@10: 1.0000, MRR: 0.8621
test [sampled], NDCG@5: 0.3002, HR@5: 0.3920, NDCG@10: 0.3783, HR@10: 0.6311, MRR: 0.3224
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0814
epoch=32, loss=0.0804
epoch=33, loss=0.0813
epoch=34, loss=0.0805
epoch=35, loss=0.0787
valid [full], NDCG@5: 0.6321, HR@5: 0.7427, NDCG@10: 0.7033, HR@10: 0.9708, MRR: 0.6276
valid [sampled], NDCG@5: 0.5525, HR@5: 0.5543, NDCG@10: 0.5589, HR@10: 0.5743, MRR: 0.5681
test [full], NDCG@5: 0.8533, HR@5: 0.9120, NDCG@10: 0.8809, HR@10: 1.0000, MRR: 0.8448
test [sampled], NDCG@5: 0.2981, HR@5: 0.3853, NDCG@10: 0.3709, HR@10: 0.6093, MRR: 0.3204
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0794
epoch=37, loss=0.0779
epoch=38, loss=0.0789
epoch=39, loss=0.0789
epoch=40, loss=0.0798
valid [full], NDCG@5: 0.6371, HR@5: 0.8026, NDCG@10: 0.6853, HR@10: 0.9548, MRR: 0.6077
valid [sampled], NDCG@5: 0.4989, HR@5: 0.5008, NDCG@10: 0.5072, HR@10: 0.5271, MRR: 0.5189
test [full], NDCG@5: 0.8607, HR@5: 0.9267, NDCG@10: 0.8836, HR@10: 1.0000, MRR: 0.8478
test [sampled], NDCG@5: 0.3443, HR@5: 0.4116, NDCG@10: 0.4032, HR@10: 0.5931, MRR: 0.3688
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0798
epoch=42, loss=0.0802
epoch=43, loss=0.0791
epoch=44, loss=0.0788
epoch=45, loss=0.0791
valid [full], NDCG@5: 0.6192, HR@5: 0.7600, NDCG@10: 0.6794, HR@10: 0.9500, MRR: 0.6025
valid [sampled], NDCG@5: 0.4934, HR@5: 0.4957, NDCG@10: 0.5009, HR@10: 0.5197, MRR: 0.5125
test [full], NDCG@5: 0.8646, HR@5: 0.9220, NDCG@10: 0.8888, HR@10: 1.0000, MRR: 0.8550
test [sampled], NDCG@5: 0.3295, HR@5: 0.4089, NDCG@10: 0.3959, HR@10: 0.6124, MRR: 0.3522
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0769
epoch=47, loss=0.0781
epoch=48, loss=0.0775
epoch=49, loss=0.0777
epoch=50, loss=0.0769
valid [full], NDCG@5: 0.6462, HR@5: 0.7728, NDCG@10: 0.7044, HR@10: 0.9513, MRR: 0.6342
valid [sampled], NDCG@5: 0.5267, HR@5: 0.5299, NDCG@10: 0.5377, HR@10: 0.5652, MRR: 0.5453
test [full], NDCG@5: 0.8679, HR@5: 0.9261, NDCG@10: 0.8909, HR@10: 1.0000, MRR: 0.8573
test [sampled], NDCG@5: 0.3770, HR@5: 0.4494, NDCG@10: 0.4378, HR@10: 0.6359, MRR: 0.3979
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s42/sasrec_last.pth

### refine_ml50_do025_s2024

In [30]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do025_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024
epoch=1, loss=0.5681
epoch=2, loss=0.2402
epoch=3, loss=0.1763
epoch=4, loss=0.1409
epoch=5, loss=0.1248
valid [full], NDCG@5: 0.6843, HR@5: 0.8465, NDCG@10: 0.7338, HR@10: 0.9939, MRR: 0.6549
valid [sampled], NDCG@5: 0.5604, HR@5: 0.5637, NDCG@10: 0.5685, HR@10: 0.5894, MRR: 0.5784
test [full], NDCG@5: 0.7561, HR@5: 0.8822, NDCG@10: 0.7931, HR@10: 1.0000, MRR: 0.7288
test [sampled], NDCG@5: 0.1681, HR@5: 0.2351, NDCG@10: 0.2364, HR@10: 0.4463, MRR: 0.2037
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/sasrec_best.pth
epoch=6, loss=0.1121
epoch=7, loss=0.1043
epoch=8, loss=0.1006
epoch=9, loss=0.0951
epoch=10, loss=0.0942
valid [full], NDCG@5: 0.6579, HR@5: 0.7653, NDCG@10: 0.7238, HR@10: 0.9739, MRR: 0.6515
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5683, NDCG@10: 0.5739, HR@10: 0.6196, MRR: 0.5730
test [full], NDCG@5: 0.7544, HR@5: 0.8836, NDCG@10: 0.7910, HR@10: 1.0000, MRR: 0.7237
test [sampled], NDCG@5: 0.2142, HR@5: 0.2597, NDCG@10: 0.2974, HR@10: 0.5214, MRR: 0.2590
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0919
epoch=12, loss=0.0901
epoch=13, loss=0.0879
epoch=14, loss=0.0878
epoch=15, loss=0.0883
valid [full], NDCG@5: 0.6946, HR@5: 0.8559, NDCG@10: 0.7325, HR@10: 0.9745, MRR: 0.6597
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5520, NDCG@10: 0.5637, HR@10: 0.6078, MRR: 0.5686
test [full], NDCG@5: 0.8544, HR@5: 0.9162, NDCG@10: 0.8811, HR@10: 1.0000, MRR: 0.8445
test [sampled], NDCG@5: 0.2253, HR@5: 0.3130, NDCG@10: 0.3142, HR@10: 0.5879, MRR: 0.2560
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/sasrec_best.pth
epoch=16, loss=0.0854
epoch=17, loss=0.0849
epoch=18, loss=0.0852
epoch=19, loss=0.0840
epoch=20, loss=0.0844
valid [full], NDCG@5: 0.6496, HR@5: 0.7816, NDCG@10: 0.7127, HR@10: 0.9768, MRR: 0.6351
valid [sampled], NDCG@5: 0.5239, HR@5: 0.5283, NDCG@10: 0.5399, HR@10: 0.5789, MRR: 0.5444
test [full], NDCG@5: 0.8233, HR@5: 0.8748, NDCG@10: 0.8638, HR@10: 1.0000, MRR: 0.8227
test [sampled], NDCG@5: 0.3214, HR@5: 0.3924, NDCG@10: 0.3863, HR@10: 0.5913, MRR: 0.3456
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0839
epoch=22, loss=0.0830
epoch=23, loss=0.0828
epoch=24, loss=0.0849
epoch=25, loss=0.0836
valid [full], NDCG@5: 0.6160, HR@5: 0.7848, NDCG@10: 0.6778, HR@10: 0.9740, MRR: 0.5894
valid [sampled], NDCG@5: 0.4594, HR@5: 0.4713, NDCG@10: 0.4738, HR@10: 0.5162, MRR: 0.4787
test [full], NDCG@5: 0.8821, HR@5: 0.9676, NDCG@10: 0.8931, HR@10: 1.0000, MRR: 0.8593
test [sampled], NDCG@5: 0.3084, HR@5: 0.3837, NDCG@10: 0.3796, HR@10: 0.6041, MRR: 0.3350
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0805
epoch=27, loss=0.0801
epoch=28, loss=0.0805
epoch=29, loss=0.0836
epoch=30, loss=0.0797
valid [full], NDCG@5: 0.5992, HR@5: 0.7386, NDCG@10: 0.6770, HR@10: 0.9768, MRR: 0.5889
valid [sampled], NDCG@5: 0.4733, HR@5: 0.4834, NDCG@10: 0.4855, HR@10: 0.5212, MRR: 0.4909
test [full], NDCG@5: 0.8545, HR@5: 0.9168, NDCG@10: 0.8827, HR@10: 1.0000, MRR: 0.8466
test [sampled], NDCG@5: 0.3788, HR@5: 0.4443, NDCG@10: 0.4320, HR@10: 0.6079, MRR: 0.3996
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0811
epoch=32, loss=0.0813
epoch=33, loss=0.0794
epoch=34, loss=0.0805
epoch=35, loss=0.0790
valid [full], NDCG@5: 0.6377, HR@5: 0.7570, NDCG@10: 0.7030, HR@10: 0.9545, MRR: 0.6309
valid [sampled], NDCG@5: 0.5351, HR@5: 0.5458, NDCG@10: 0.5476, HR@10: 0.5849, MRR: 0.5506
test [full], NDCG@5: 0.8791, HR@5: 0.9724, NDCG@10: 0.8888, HR@10: 1.0000, MRR: 0.8538
test [sampled], NDCG@5: 0.4189, HR@5: 0.4726, NDCG@10: 0.4658, HR@10: 0.6163, MRR: 0.4410
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0806
epoch=37, loss=0.0795
epoch=38, loss=0.0802
epoch=39, loss=0.0797
epoch=40, loss=0.0779
valid [full], NDCG@5: 0.6194, HR@5: 0.7994, NDCG@10: 0.6772, HR@10: 0.9759, MRR: 0.5878
valid [sampled], NDCG@5: 0.4641, HR@5: 0.4752, NDCG@10: 0.4769, HR@10: 0.5147, MRR: 0.4829
test [full], NDCG@5: 0.8742, HR@5: 0.9458, NDCG@10: 0.8913, HR@10: 1.0000, MRR: 0.8575
test [sampled], NDCG@5: 0.4001, HR@5: 0.4608, NDCG@10: 0.4521, HR@10: 0.6210, MRR: 0.4218
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0789
epoch=42, loss=0.0792
epoch=43, loss=0.0794
epoch=44, loss=0.0770
epoch=45, loss=0.0781
valid [full], NDCG@5: 0.6179, HR@5: 0.8002, NDCG@10: 0.6756, HR@10: 0.9774, MRR: 0.5852
valid [sampled], NDCG@5: 0.4650, HR@5: 0.4733, NDCG@10: 0.4755, HR@10: 0.5061, MRR: 0.4844
test [full], NDCG@5: 0.8693, HR@5: 0.9401, NDCG@10: 0.8892, HR@10: 1.0000, MRR: 0.8547
test [sampled], NDCG@5: 0.3735, HR@5: 0.4362, NDCG@10: 0.4288, HR@10: 0.6064, MRR: 0.3972
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0771
epoch=47, loss=0.0774
epoch=48, loss=0.0782
epoch=49, loss=0.0766
epoch=50, loss=0.0788
valid [full], NDCG@5: 0.6139, HR@5: 0.7929, NDCG@10: 0.6751, HR@10: 0.9751, MRR: 0.5849
valid [sampled], NDCG@5: 0.4563, HR@5: 0.4668, NDCG@10: 0.4696, HR@10: 0.5081, MRR: 0.4760
test [full], NDCG@5: 0.8710, HR@5: 0.9414, NDCG@10: 0.8897, HR@10: 1.0000, MRR: 0.8554
test [sampled], NDCG@5: 0.4023, HR@5: 0.4647, NDCG@10: 0.4562, HR@10: 0.6302, MRR: 0.4238
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do025_s2024/sasrec_last.pth

### refine_ml50_do030_s2024

In [31]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do030_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024
epoch=1, loss=0.5987
epoch=2, loss=0.2553
epoch=3, loss=0.1894
epoch=4, loss=0.1533
epoch=5, loss=0.1350
valid [full], NDCG@5: 0.7439, HR@5: 0.9658, NDCG@10: 0.7536, HR@10: 0.9931, MRR: 0.6785
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5725, NDCG@10: 0.5807, HR@10: 0.6159, MRR: 0.5882
test [full], NDCG@5: 0.7688, HR@5: 0.9350, NDCG@10: 0.7900, HR@10: 1.0000, MRR: 0.7235
test [sampled], NDCG@5: 0.1627, HR@5: 0.2252, NDCG@10: 0.2248, HR@10: 0.4173, MRR: 0.1993
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/sasrec_best.pth
epoch=6, loss=0.1200
epoch=7, loss=0.1109
epoch=8, loss=0.1070
epoch=9, loss=0.1001
epoch=10, loss=0.0988
valid [full], NDCG@5: 0.6875, HR@5: 0.8443, NDCG@10: 0.7296, HR@10: 0.9719, MRR: 0.6576
valid [sampled], NDCG@5: 0.5530, HR@5: 0.5610, NDCG@10: 0.5691, HR@10: 0.6120, MRR: 0.5716
test [full], NDCG@5: 0.7472, HR@5: 0.9068, NDCG@10: 0.7776, HR@10: 1.0000, MRR: 0.7046
test [sampled], NDCG@5: 0.1471, HR@5: 0.1861, NDCG@10: 0.2371, HR@10: 0.4713, MRR: 0.2001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0960
epoch=12, loss=0.0938
epoch=13, loss=0.0911
epoch=14, loss=0.0912
epoch=15, loss=0.0916
valid [full], NDCG@5: 0.7035, HR@5: 0.8841, NDCG@10: 0.7317, HR@10: 0.9737, MRR: 0.6576
valid [sampled], NDCG@5: 0.5185, HR@5: 0.5258, NDCG@10: 0.5443, HR@10: 0.6088, MRR: 0.5450
test [full], NDCG@5: 0.8845, HR@5: 0.9392, NDCG@10: 0.9040, HR@10: 1.0000, MRR: 0.8738
test [sampled], NDCG@5: 0.3833, HR@5: 0.4471, NDCG@10: 0.4435, HR@10: 0.6328, MRR: 0.4081
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0890
epoch=17, loss=0.0877
epoch=18, loss=0.0876
epoch=19, loss=0.0872
epoch=20, loss=0.0869
valid [full], NDCG@5: 0.6491, HR@5: 0.8351, NDCG@10: 0.6938, HR@10: 0.9750, MRR: 0.6089
valid [sampled], NDCG@5: 0.4674, HR@5: 0.4725, NDCG@10: 0.4882, HR@10: 0.5389, MRR: 0.4923
test [full], NDCG@5: 0.8844, HR@5: 0.9483, NDCG@10: 0.9015, HR@10: 1.0000, MRR: 0.8700
test [sampled], NDCG@5: 0.3879, HR@5: 0.4534, NDCG@10: 0.4483, HR@10: 0.6390, MRR: 0.4122
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0868
epoch=22, loss=0.0855
epoch=23, loss=0.0858
epoch=24, loss=0.0868
epoch=25, loss=0.0855
valid [full], NDCG@5: 0.6741, HR@5: 0.8369, NDCG@10: 0.7113, HR@10: 0.9520, MRR: 0.6406
valid [sampled], NDCG@5: 0.5063, HR@5: 0.5117, NDCG@10: 0.5270, HR@10: 0.5779, MRR: 0.5309
test [full], NDCG@5: 0.8872, HR@5: 0.9467, NDCG@10: 0.9039, HR@10: 1.0000, MRR: 0.8736
test [sampled], NDCG@5: 0.4076, HR@5: 0.4702, NDCG@10: 0.4614, HR@10: 0.6363, MRR: 0.4297
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0829
epoch=27, loss=0.0827
epoch=28, loss=0.0835
epoch=29, loss=0.0850
epoch=30, loss=0.0824
valid [full], NDCG@5: 0.6413, HR@5: 0.8181, NDCG@10: 0.6859, HR@10: 0.9550, MRR: 0.6065
valid [sampled], NDCG@5: 0.4742, HR@5: 0.4852, NDCG@10: 0.4923, HR@10: 0.5418, MRR: 0.4947
test [full], NDCG@5: 0.8867, HR@5: 0.9475, NDCG@10: 0.9029, HR@10: 1.0000, MRR: 0.8721
test [sampled], NDCG@5: 0.4217, HR@5: 0.4795, NDCG@10: 0.4722, HR@10: 0.6349, MRR: 0.4440
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0829
epoch=32, loss=0.0836
epoch=33, loss=0.0814
epoch=34, loss=0.0818
epoch=35, loss=0.0808
valid [full], NDCG@5: 0.6430, HR@5: 0.8228, NDCG@10: 0.6841, HR@10: 0.9490, MRR: 0.6061
valid [sampled], NDCG@5: 0.4766, HR@5: 0.4797, NDCG@10: 0.4900, HR@10: 0.5227, MRR: 0.5000
test [full], NDCG@5: 0.8838, HR@5: 0.9594, NDCG@10: 0.8964, HR@10: 1.0000, MRR: 0.8635
test [sampled], NDCG@5: 0.4169, HR@5: 0.4689, NDCG@10: 0.4622, HR@10: 0.6082, MRR: 0.4408
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0823
epoch=37, loss=0.0818
epoch=38, loss=0.0820
epoch=39, loss=0.0817
epoch=40, loss=0.0800
valid [full], NDCG@5: 0.6399, HR@5: 0.8005, NDCG@10: 0.6975, HR@10: 0.9758, MRR: 0.6136
valid [sampled], NDCG@5: 0.4771, HR@5: 0.4894, NDCG@10: 0.5024, HR@10: 0.5693, MRR: 0.4997
test [full], NDCG@5: 0.8916, HR@5: 0.9574, NDCG@10: 0.9051, HR@10: 1.0000, MRR: 0.8747
test [sampled], NDCG@5: 0.4286, HR@5: 0.4818, NDCG@10: 0.4777, HR@10: 0.6339, MRR: 0.4523
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0808
epoch=42, loss=0.0814
epoch=43, loss=0.0815
epoch=44, loss=0.0785
epoch=45, loss=0.0806
valid [full], NDCG@5: 0.6417, HR@5: 0.8378, NDCG@10: 0.6856, HR@10: 0.9767, MRR: 0.5972
valid [sampled], NDCG@5: 0.4526, HR@5: 0.4580, NDCG@10: 0.4716, HR@10: 0.5192, MRR: 0.4787
test [full], NDCG@5: 0.8934, HR@5: 0.9773, NDCG@10: 0.9015, HR@10: 1.0000, MRR: 0.8695
test [sampled], NDCG@5: 0.4144, HR@5: 0.4734, NDCG@10: 0.4633, HR@10: 0.6235, MRR: 0.4375
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0792
epoch=47, loss=0.0798
epoch=48, loss=0.0799
epoch=49, loss=0.0785
epoch=50, loss=0.0802
valid [full], NDCG@5: 0.6619, HR@5: 0.8342, NDCG@10: 0.7067, HR@10: 0.9743, MRR: 0.6263
valid [sampled], NDCG@5: 0.4887, HR@5: 0.4917, NDCG@10: 0.5069, HR@10: 0.5499, MRR: 0.5145
test [full], NDCG@5: 0.8815, HR@5: 0.9586, NDCG@10: 0.8946, HR@10: 1.0000, MRR: 0.8610
test [sampled], NDCG@5: 0.4228, HR@5: 0.4728, NDCG@10: 0.4690, HR@10: 0.6149, MRR: 0.4472
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do030_s2024/sasrec_last.pth

### refine_ml75_do030_s42

In [32]:
!python src/train_sasrec.py \
  --run_name refine_ml75_do030_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 75 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42
epoch=1, loss=0.5423
epoch=2, loss=0.2566
epoch=3, loss=0.1895
epoch=4, loss=0.1550
epoch=5, loss=0.1346
valid [full], NDCG@5: 0.6334, HR@5: 0.7080, NDCG@10: 0.7187, HR@10: 0.9788, MRR: 0.6444
valid [sampled], NDCG@5: 0.5632, HR@5: 0.5782, NDCG@10: 0.5810, HR@10: 0.6336, MRR: 0.5759
test [full], NDCG@5: 0.4215, HR@5: 0.5434, NDCG@10: 0.5647, HR@10: 0.9999, MRR: 0.4357
test [sampled], NDCG@5: 0.1462, HR@5: 0.1517, NDCG@10: 0.1850, HR@10: 0.2766, MRR: 0.1841
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/sasrec_best.pth
epoch=6, loss=0.1242
epoch=7, loss=0.1132
epoch=8, loss=0.1076
epoch=9, loss=0.1039
epoch=10, loss=0.1004
valid [full], NDCG@5: 0.6418, HR@5: 0.7530, NDCG@10: 0.7101, HR@10: 0.9701, MRR: 0.6358
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5652, NDCG@10: 0.5659, HR@10: 0.6086, MRR: 0.5655
test [full], NDCG@5: 0.5969, HR@5: 0.8665, NDCG@10: 0.6403, HR@10: 1.0000, MRR: 0.5236
test [sampled], NDCG@5: 0.1396, HR@5: 0.1606, NDCG@10: 0.1950, HR@10: 0.3363, MRR: 0.1852
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/sasrec_best.pth
epoch=11, loss=0.0973
epoch=12, loss=0.0965
epoch=13, loss=0.0945
epoch=14, loss=0.0919
epoch=15, loss=0.0928
valid [full], NDCG@5: 0.6311, HR@5: 0.7302, NDCG@10: 0.7108, HR@10: 0.9738, MRR: 0.6358
valid [sampled], NDCG@5: 0.5681, HR@5: 0.5714, NDCG@10: 0.5738, HR@10: 0.5894, MRR: 0.5821
test [full], NDCG@5: 0.7273, HR@5: 0.8948, NDCG@10: 0.7611, HR@10: 1.0000, MRR: 0.6848
test [sampled], NDCG@5: 0.1946, HR@5: 0.2604, NDCG@10: 0.2569, HR@10: 0.4537, MRR: 0.2250
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0915
epoch=17, loss=0.0899
epoch=18, loss=0.0880
epoch=19, loss=0.0856
epoch=20, loss=0.0862
valid [full], NDCG@5: 0.6501, HR@5: 0.7676, NDCG@10: 0.7165, HR@10: 0.9735, MRR: 0.6426
valid [sampled], NDCG@5: 0.5577, HR@5: 0.5623, NDCG@10: 0.5643, HR@10: 0.5830, MRR: 0.5729
test [full], NDCG@5: 0.7843, HR@5: 0.8842, NDCG@10: 0.8212, HR@10: 1.0000, MRR: 0.7652
test [sampled], NDCG@5: 0.2234, HR@5: 0.3095, NDCG@10: 0.3046, HR@10: 0.5596, MRR: 0.2508
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/sasrec_best.pth
epoch=21, loss=0.0869
epoch=22, loss=0.0871
epoch=23, loss=0.0834
epoch=24, loss=0.0846
epoch=25, loss=0.0841
valid [full], NDCG@5: 0.6261, HR@5: 0.7588, NDCG@10: 0.6896, HR@10: 0.9534, MRR: 0.6138
valid [sampled], NDCG@5: 0.5063, HR@5: 0.5097, NDCG@10: 0.5154, HR@10: 0.5386, MRR: 0.5247
test [full], NDCG@5: 0.8354, HR@5: 0.9249, NDCG@10: 0.8587, HR@10: 1.0000, MRR: 0.8142
test [sampled], NDCG@5: 0.2589, HR@5: 0.3527, NDCG@10: 0.3399, HR@10: 0.6001, MRR: 0.2827
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0835
epoch=27, loss=0.0858
epoch=28, loss=0.0822
epoch=29, loss=0.0863
epoch=30, loss=0.0821
valid [full], NDCG@5: 0.6753, HR@5: 0.8232, NDCG@10: 0.7243, HR@10: 0.9764, MRR: 0.6504
valid [sampled], NDCG@5: 0.5535, HR@5: 0.5595, NDCG@10: 0.5638, HR@10: 0.5921, MRR: 0.5708
test [full], NDCG@5: 0.8477, HR@5: 0.9177, NDCG@10: 0.8733, HR@10: 1.0000, MRR: 0.8341
test [sampled], NDCG@5: 0.2813, HR@5: 0.3734, NDCG@10: 0.3616, HR@10: 0.6193, MRR: 0.3040
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/sasrec_best.pth
epoch=31, loss=0.0827
epoch=32, loss=0.0819
epoch=33, loss=0.0831
epoch=34, loss=0.0810
epoch=35, loss=0.0814
valid [full], NDCG@5: 0.6265, HR@5: 0.7820, NDCG@10: 0.6818, HR@10: 0.9522, MRR: 0.6036
valid [sampled], NDCG@5: 0.4945, HR@5: 0.4966, NDCG@10: 0.5028, HR@10: 0.5234, MRR: 0.5144
test [full], NDCG@5: 0.8379, HR@5: 0.9206, NDCG@10: 0.8626, HR@10: 1.0000, MRR: 0.8197
test [sampled], NDCG@5: 0.2836, HR@5: 0.3637, NDCG@10: 0.3593, HR@10: 0.5964, MRR: 0.3100
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0800
epoch=37, loss=0.0794
epoch=38, loss=0.0811
epoch=39, loss=0.0803
epoch=40, loss=0.0805
valid [full], NDCG@5: 0.6898, HR@5: 0.8545, NDCG@10: 0.7275, HR@10: 0.9759, MRR: 0.6540
valid [sampled], NDCG@5: 0.5535, HR@5: 0.5565, NDCG@10: 0.5653, HR@10: 0.5945, MRR: 0.5739
test [full], NDCG@5: 0.8709, HR@5: 0.9221, NDCG@10: 0.8951, HR@10: 1.0000, MRR: 0.8629
test [sampled], NDCG@5: 0.3081, HR@5: 0.3902, NDCG@10: 0.3800, HR@10: 0.6115, MRR: 0.3329
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/sasrec_best.pth
epoch=41, loss=0.0797
epoch=42, loss=0.0815
epoch=43, loss=0.0814
epoch=44, loss=0.0807
epoch=45, loss=0.0788
valid [full], NDCG@5: 0.6694, HR@5: 0.8437, NDCG@10: 0.7049, HR@10: 0.9556, MRR: 0.6311
valid [sampled], NDCG@5: 0.5102, HR@5: 0.5137, NDCG@10: 0.5243, HR@10: 0.5589, MRR: 0.5330
test [full], NDCG@5: 0.8489, HR@5: 0.9212, NDCG@10: 0.8731, HR@10: 1.0000, MRR: 0.8338
test [sampled], NDCG@5: 0.4237, HR@5: 0.4771, NDCG@10: 0.4647, HR@10: 0.6033, MRR: 0.4431
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0785
epoch=47, loss=0.0796
epoch=48, loss=0.0786
epoch=49, loss=0.0794
epoch=50, loss=0.0800
valid [full], NDCG@5: 0.6760, HR@5: 0.8489, NDCG@10: 0.7091, HR@10: 0.9546, MRR: 0.6374
valid [sampled], NDCG@5: 0.5169, HR@5: 0.5222, NDCG@10: 0.5298, HR@10: 0.5632, MRR: 0.5375
test [full], NDCG@5: 0.8314, HR@5: 0.9215, NDCG@10: 0.8557, HR@10: 1.0000, MRR: 0.8101
test [sampled], NDCG@5: 0.3960, HR@5: 0.4628, NDCG@10: 0.4481, HR@10: 0.6216, MRR: 0.4129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml75_do030_s42/sasrec_last.pth

### refine_ml100_do030_s42

In [33]:
!python src/train_sasrec.py \
  --run_name refine_ml100_do030_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 100 \
  --lr 0.001 \
  --dropout_rate 0.3 \
  --seed 42 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42
epoch=1, loss=0.5443
epoch=2, loss=0.2581
epoch=3, loss=0.1902
epoch=4, loss=0.1567
epoch=5, loss=0.1356
valid [full], NDCG@5: 0.6461, HR@5: 0.7348, NDCG@10: 0.7279, HR@10: 0.9925, MRR: 0.6507
valid [sampled], NDCG@5: 0.5705, HR@5: 0.5853, NDCG@10: 0.5859, HR@10: 0.6330, MRR: 0.5827
test [full], NDCG@5: 0.4594, HR@5: 0.5923, NDCG@10: 0.5847, HR@10: 0.9859, MRR: 0.4657
test [sampled], NDCG@5: 0.1540, HR@5: 0.1590, NDCG@10: 0.1933, HR@10: 0.2859, MRR: 0.1936
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/sasrec_best.pth
epoch=6, loss=0.1224
epoch=7, loss=0.1130
epoch=8, loss=0.1072
epoch=9, loss=0.1040
epoch=10, loss=0.0996
valid [full], NDCG@5: 0.6488, HR@5: 0.7552, NDCG@10: 0.7171, HR@10: 0.9708, MRR: 0.6439
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5692, NDCG@10: 0.5741, HR@10: 0.6251, MRR: 0.5717
test [full], NDCG@5: 0.7142, HR@5: 0.8702, NDCG@10: 0.7567, HR@10: 1.0000, MRR: 0.6797
test [sampled], NDCG@5: 0.1867, HR@5: 0.2542, NDCG@10: 0.2523, HR@10: 0.4564, MRR: 0.2172
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/sasrec_best.pth
epoch=11, loss=0.0983
epoch=12, loss=0.0959
epoch=13, loss=0.0938
epoch=14, loss=0.0927
epoch=15, loss=0.0926
valid [full], NDCG@5: 0.6470, HR@5: 0.7461, NDCG@10: 0.7191, HR@10: 0.9773, MRR: 0.6455
valid [sampled], NDCG@5: 0.5770, HR@5: 0.5882, NDCG@10: 0.5879, HR@10: 0.6215, MRR: 0.5888
test [full], NDCG@5: 0.8241, HR@5: 0.9079, NDCG@10: 0.8557, HR@10: 1.0000, MRR: 0.8097
test [sampled], NDCG@5: 0.2341, HR@5: 0.3236, NDCG@10: 0.3175, HR@10: 0.5803, MRR: 0.2620
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0923
epoch=17, loss=0.0887
epoch=18, loss=0.0879
epoch=19, loss=0.0884
epoch=20, loss=0.0868
valid [full], NDCG@5: 0.6588, HR@5: 0.7774, NDCG@10: 0.7157, HR@10: 0.9594, MRR: 0.6469
valid [sampled], NDCG@5: 0.5612, HR@5: 0.5666, NDCG@10: 0.5717, HR@10: 0.5998, MRR: 0.5766
test [full], NDCG@5: 0.8208, HR@5: 0.8984, NDCG@10: 0.8529, HR@10: 0.9999, MRR: 0.8070
test [sampled], NDCG@5: 0.2673, HR@5: 0.3554, NDCG@10: 0.3451, HR@10: 0.5936, MRR: 0.2918
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/sasrec_best.pth
epoch=21, loss=0.0866
epoch=22, loss=0.0860
epoch=23, loss=0.0848
epoch=24, loss=0.0833
epoch=25, loss=0.0857
valid [full], NDCG@5: 0.6863, HR@5: 0.8365, NDCG@10: 0.7300, HR@10: 0.9737, MRR: 0.6582
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5604, NDCG@10: 0.5684, HR@10: 0.6020, MRR: 0.5741
test [full], NDCG@5: 0.8163, HR@5: 0.9263, NDCG@10: 0.8396, HR@10: 1.0000, MRR: 0.7883
test [sampled], NDCG@5: 0.2529, HR@5: 0.3212, NDCG@10: 0.3225, HR@10: 0.5364, MRR: 0.2850
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/sasrec_best.pth
epoch=26, loss=0.0837
epoch=27, loss=0.0835
epoch=28, loss=0.0848
epoch=29, loss=0.0848
epoch=30, loss=0.0847
valid [full], NDCG@5: 0.6725, HR@5: 0.7897, NDCG@10: 0.7335, HR@10: 0.9762, MRR: 0.6622
valid [sampled], NDCG@5: 0.5621, HR@5: 0.5762, NDCG@10: 0.5787, HR@10: 0.6278, MRR: 0.5773
test [full], NDCG@5: 0.8413, HR@5: 0.9194, NDCG@10: 0.8665, HR@10: 1.0000, MRR: 0.8238
test [sampled], NDCG@5: 0.2743, HR@5: 0.3596, NDCG@10: 0.3506, HR@10: 0.5930, MRR: 0.3001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0827
epoch=32, loss=0.0810
epoch=33, loss=0.0828
epoch=34, loss=0.0796
epoch=35, loss=0.0824
valid [full], NDCG@5: 0.6558, HR@5: 0.7772, NDCG@10: 0.7143, HR@10: 0.9557, MRR: 0.6449
valid [sampled], NDCG@5: 0.5487, HR@5: 0.5564, NDCG@10: 0.5634, HR@10: 0.6027, MRR: 0.5662
test [full], NDCG@5: 0.7945, HR@5: 0.9183, NDCG@10: 0.8198, HR@10: 1.0000, MRR: 0.7621
test [sampled], NDCG@5: 0.2406, HR@5: 0.3224, NDCG@10: 0.3189, HR@10: 0.5643, MRR: 0.2679
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0812
epoch=37, loss=0.0808
epoch=38, loss=0.0811
epoch=39, loss=0.0818
epoch=40, loss=0.0794
valid [full], NDCG@5: 0.6356, HR@5: 0.7234, NDCG@10: 0.7178, HR@10: 0.9758, MRR: 0.6434
valid [sampled], NDCG@5: 0.5602, HR@5: 0.5671, NDCG@10: 0.5706, HR@10: 0.5995, MRR: 0.5753
test [full], NDCG@5: 0.8233, HR@5: 0.9214, NDCG@10: 0.8483, HR@10: 1.0000, MRR: 0.8000
test [sampled], NDCG@5: 0.2682, HR@5: 0.3407, NDCG@10: 0.3356, HR@10: 0.5493, MRR: 0.2974
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0808
epoch=42, loss=0.0809
epoch=43, loss=0.0816
epoch=44, loss=0.0801
epoch=45, loss=0.0798
valid [full], NDCG@5: 0.6680, HR@5: 0.7903, NDCG@10: 0.7294, HR@10: 0.9780, MRR: 0.6561
valid [sampled], NDCG@5: 0.5538, HR@5: 0.5598, NDCG@10: 0.5685, HR@10: 0.6058, MRR: 0.5725
test [full], NDCG@5: 0.8231, HR@5: 0.9201, NDCG@10: 0.8479, HR@10: 1.0000, MRR: 0.7988
test [sampled], NDCG@5: 0.2111, HR@5: 0.2902, NDCG@10: 0.2997, HR@10: 0.5653, MRR: 0.2467
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0778
epoch=47, loss=0.0804
epoch=48, loss=0.0793
epoch=49, loss=0.0800
epoch=50, loss=0.0795
valid [full], NDCG@5: 0.6831, HR@5: 0.8073, NDCG@10: 0.7376, HR@10: 0.9765, MRR: 0.6669
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5677, NDCG@10: 0.5731, HR@10: 0.6146, MRR: 0.5760
test [full], NDCG@5: 0.8619, HR@5: 0.9203, NDCG@10: 0.8867, HR@10: 1.0000, MRR: 0.8516
test [sampled], NDCG@5: 0.3435, HR@5: 0.4305, NDCG@10: 0.4094, HR@10: 0.6312, MRR: 0.3614
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml100_do030_s42/sasrec_last.pth

## Result lookup

Rebuild result tables directly from each run folder to avoid any CSV schema drift.

In [4]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [5]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## Result lookup: ndcg10

In [10]:
df_ndcg10 = rebuild_df(NDCG10_OUTPUT_DIR)
# df_ndcg10 = df_ndcg10.sort_values(['best_valid_full_ndcg@10', 'best_valid_full_hr@10'], ascending=False).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'maxlen', 'dropout_rate', 'best_epoch',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
    # 'checkpoint_best', 'checkpoint_last',
]]

                   run_name  seed  maxlen  dropout_rate  best_epoch  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0             anchor_pd_s42    42     200          0.20          30                 0.732820               0.976377                0.687751              0.837473             0.660809                0.759349                   1.0               0.741494             0.945437            0.677949                    0.571892                  0.608637                   0.559131                 0.568577                0.576002                   0.266000                 0.425584                  0.198901                0.209418               0.257410
1          anchor_ml100_s42    42     100          0.20          30                 0.731288               0.976377                0.664780              0.765794             0.660439                0.805918                   1.0               0.780413             0.919929            0.741519                    0.581806                  0.636746                   0.562553                 0.576725                0.577579                   0.312154                 0.508973                  0.238265                0.275536               0.284821
2           anchor_ml50_s42    42      50          0.20          15                 0.732238               0.977745                0.694772              0.860632             0.658512                0.821952                   1.0               0.797110             0.920622            0.764088                    0.575181                  0.621538                   0.559087                 0.571274                0.576963                   0.291792                 0.516651                  0.218746                0.290064               0.252954
3           anchor_ml20_s42    42      20          0.20          50                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296                   1.0               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
4     refine_ml50_do030_s42    42      50          0.30          15                 0.728433               0.975302                0.683934              0.833085             0.655886                0.843098                   1.0               0.819527             0.927924            0.792374                    0.585535                  0.628564                   0.570842                 0.582894                0.586061                   0.294100                 0.541253                  0.215080                0.297268               0.246889
5     refine_ml50_do035_s42    42      50          0.35          50                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774                   1.0               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
6     refine_ml50_do025_s42    42      50          0.25          15                 0.737294               0.975302                0.698773              0.855883             0.666429                0.757232                   1.0               0.733023             0.922650            0.676185                    0.590335                  0.630861                   0.576735                 0.588839                0.592687                   0.243580                 0.427348                  0.171452                0.197227               0.225910
7   refine_ml50_do025_s2024  2024      50          0.25           5                 0.733755               0.993919                0.684304              0.846486             0.654911                0.793137                   1.0               0.756145             0.882210            0.728828                    0.568471                  0.589448                   0.560388                 0.563678                0.578420                   0.236381                 0.446283                  0.168065                0.235079               0.203745
8   refine_ml50_do030_s2024  2024      50          0.30           5                 0.753595               0.993108                0.743881              0.965811             0.678463                0.790040                   1.0               0.768786             0.935026            0.723476                    0.580711                  0.615896                   0.567026                 0.572494                0.588228                   0.224842                 0.417254                  0.162712                0.225176               0.199310
9     refine_ml75_do030_s42    42      75          0.30          40                 0.727543               0.975913                0.689849              0.854533             0.653961                0.895066                   1.0               0.870918             0.922094            0.862916                    0.565326                  0.594543                   0.553512                 0.556456                0.573899                   0.380006                 0.611456                  0.308142                0.390165               0.332916
10   refine_ml100_do030_s42    42     100          0.30          50                 0.737589               0.976464                0.683139              0.807250             0.666935                0.886700                   1.0               0.861939             0.920250            0.851575                    0.573112                  0.614629                   0.558167                 0.567686                0.575993                   0.409377                 0.631242                  0.343535                0.430535               0.361373

## Result lookup: ndcg5

In [11]:
df_ndcg5 = rebuild_df(NDCG5_OUTPUT_DIR)
# df_ndcg5 = df_ndcg5.sort_values(['best_valid_full_ndcg@5', 'best_valid_full_hr@5'], ascending=False).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'maxlen', 'dropout_rate', 'best_epoch',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
    # 'checkpoint_best', 'checkpoint_last',
]]

                   run_name  seed  maxlen  dropout_rate  best_epoch  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0             anchor_pd_s42    42     200          0.20          10                 0.729260               0.975289                0.697986              0.875628             0.655816                0.715432                   1.0               0.680432             0.895188            0.622826                    0.572131                  0.611314                   0.559202                 0.571525                0.575570                   0.228458                 0.374611                  0.167941                0.180945               0.221445
1          anchor_ml100_s42    42     100          0.20          45                 0.725856               0.955607                0.681395              0.816725             0.659588                0.777539                   1.0               0.750338             0.913079            0.706159                    0.573727                  0.622219                   0.555278                 0.564433                0.573421                   0.337994                 0.425760                  0.305262                0.321254               0.345565
2           anchor_ml50_s42    42      50          0.20          15                 0.732238               0.977745                0.694772              0.860632             0.658512                0.821952                   1.0               0.797110             0.920622            0.764088                    0.575181                  0.621538                   0.559087                 0.571274                0.576963                   0.291792                 0.516651                  0.218746                0.290064               0.252954
3           anchor_ml20_s42    42      20          0.20          50                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296                   1.0               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
4     refine_ml50_do030_s42    42      50          0.30          15                 0.728433               0.975302                0.683934              0.833085             0.655886                0.843098                   1.0               0.819527             0.927924            0.792374                    0.585535                  0.628564                   0.570842                 0.582894                0.586061                   0.294100                 0.541253                  0.215080                0.297268               0.246889
5     refine_ml50_do035_s42    42      50          0.35          50                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774                   1.0               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
6     refine_ml50_do025_s42    42      50          0.25          15                 0.737294               0.975302                0.698773              0.855883             0.666429                0.757232                   1.0               0.733023             0.922650            0.676185                    0.590335                  0.630861                   0.576735                 0.588839                0.592687                   0.243580                 0.427348                  0.171452                0.197227               0.225910
7   refine_ml50_do025_s2024  2024      50          0.25          15                 0.732527               0.974495                0.694564              0.855922             0.659681                0.881074                   1.0               0.854356             0.916249            0.844470                    0.563718                  0.607806                   0.546371                 0.551972                0.568552                   0.314189                 0.587908                  0.225346                0.313000               0.255963
8   refine_ml50_do030_s2024  2024      50          0.30           5                 0.753595               0.993108                0.743881              0.965811             0.678463                0.790040                   1.0               0.768786             0.935026            0.723476                    0.580711                  0.615896                   0.567026                 0.572494                0.588228                   0.224842                 0.417254                  0.162712                0.225176               0.199310
9     refine_ml75_do030_s42    42      75          0.30          40                 0.727543               0.975913                0.689849              0.854533             0.653961                0.895066                   1.0               0.870918             0.922094            0.862916                    0.565326                  0.594543                   0.553512                 0.556456                0.573899                   0.380006                 0.611456                  0.308142                0.390165               0.332916
10   refine_ml100_do030_s42    42     100          0.30          25                 0.729972               0.973702                0.686307              0.836519             0.658201                0.839620                   1.0               0.816284             0.926302            0.788295                    0.568438                  0.601958                   0.555242                 0.560359                0.574081                   0.322494                 0.536381                  0.252931                0.321206               0.285027