# SASRec Attention-Bias Time-Aware BPI2012 Colab Train (`refine_ml50_do035` baseline)

Colab notebook for the first attention-bias time-aware experiment on top of `refine_ml50_do035`.

Design:
- baseline reuse: `refine_ml50_do035`
- time source: `delta_start_seconds`
- pairwise causal gap attention bias
- 9-bucket scalar attention bias
- evaluate under both `NDCG@10` and `NDCG@5` model-selection criteria

In [14]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: NVIDIA L4

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
TIMEAWARE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10'
TIMEAWARE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('TIMEAWARE_NDCG10_OUTPUT_DIR:', TIMEAWARE_NDCG10_OUTPUT_DIR)
print('TIMEAWARE_NDCG5_OUTPUT_DIR:', TIMEAWARE_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
TIMEAWARE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10
TIMEAWARE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5

In [17]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG10_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG5_OUTPUT_DIR"

In [18]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 10 (delta 8), reused 10 (delta 8), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 8.28 KiB | 2.07 MiB/s, done.
From https://github.com/hwbuzz/time-aware-behavior-prediction
   4e5059d..0856655  main       -> origin/main
Updating 4e5059d..0856655
Fast-forward
 ...c_timeaware_bpi2012_colab_train_06_260514.ipynb |   1 +
 ...re_refine_ml50_do035_attention_bias_notebook.py | 415 +++++++++++++++++++++
 src/sasrec_model.py                                |  41 +-
 src/sasrec_utils.py                                |  42 ++-
 src/train_sasrec.py                                |  19 +
 5 files changed, 512 insertions(+), 6 deletions(-)
 create mode 100644 notebooks/sasrec_timeaware_bpi2012_colab_train_06_260514.ipynb
 create mode 100644 scripts/generate_timeaware_refine_ml50_do035_attention_bias_notebook.py

In [19]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [21]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [20]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `refine_ml50_do035`
- `hidden_units=50, num_blocks=2, num_heads=1, maxlen=50, lr=0.001, dropout=0.35`
- seeds: `42`, `2024`, `7`

Time-aware design:
- `delta_start_seconds`
- causal pairwise gap attention bias
- 9-bucket scalar bias
- no additive time embedding in this notebook

## Check existing baseline runs

In [22]:
from pathlib import Path

baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

for label, output_dir in [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR)),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR)),
]:
    print('=' * 80)
    print(label)
    for run_name in baseline_runs:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS
================================================================================
Baseline NDCG@5
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS

## Check planned new runs

In [23]:
planned_ndcg10 = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]
planned_ndcg5 = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]

for label, output_dir, run_names in [
    ('Attention-Bias NDCG@10', Path(TIMEAWARE_NDCG10_OUTPUT_DIR), planned_ndcg10),
    ('Attention-Bias NDCG@5', Path(TIMEAWARE_NDCG5_OUTPUT_DIR), planned_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Attention-Bias NDCG@10
attnbias_dstart_ml50_do035_b9_s42 OK
attnbias_dstart_ml50_do035_b9_s2024 OK
attnbias_dstart_ml50_do035_b9_s7 OK
================================================================================
Attention-Bias NDCG@5
attnbias_dstart_ml50_do035_b9_s42 OK
attnbias_dstart_ml50_do035_b9_s2024 OK
attnbias_dstart_ml50_do035_b9_s7 OK

## Train attention-bias runs for `NDCG@10`

### attnbias_dstart_ml50_do035_b9_s42

In [24]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b9_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42
epoch=1, loss=0.5936
epoch=2, loss=0.2728
epoch=3, loss=0.2056
epoch=4, loss=0.1712
epoch=5, loss=0.1476
valid [full], NDCG@5: 0.6323, HR@5: 0.7273, NDCG@10: 0.6817, HR@10: 0.8820, MRR: 0.6319
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5589, NDCG@10: 0.5653, HR@10: 0.5833, MRR: 0.5735
test [full], NDCG@5: 0.5731, HR@5: 0.7451, NDCG@10: 0.6023, HR@10: 0.8396, MRR: 0.5400
test [sampled], NDCG@5: 0.1993, HR@5: 0.2006, NDCG@10: 0.2175, HR@10: 0.2605, MRR: 0.2402
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=6, loss=0.1335
epoch=7, loss=0.1231
epoch=8, loss=0.1148
epoch=9, loss=0.1095
epoch=10, loss=0.1083
valid [full], NDCG@5: 0.6579, HR@5: 0.7756, NDCG@10: 0.7180, HR@10: 0.9624, MRR: 0.6479
valid [sampled], NDCG@5: 0.5645, HR@5: 0.5778, NDCG@10: 0.5769, HR@10: 0.6158, MRR: 0.5779
test [full], NDCG@5: 0.6660, HR@5: 0.9119, NDCG@10: 0.6952, HR@10: 0.9999, MRR: 0.5957
test [sampled], NDCG@5: 0.1656, HR@5: 0.1809, NDCG@10: 0.2152, HR@10: 0.3400, MRR: 0.2156
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=11, loss=0.1056
epoch=12, loss=0.1025
epoch=13, loss=0.0993
epoch=14, loss=0.0974
epoch=15, loss=0.0972
valid [full], NDCG@5: 0.7082, HR@5: 0.8750, NDCG@10: 0.7358, HR@10: 0.9644, MRR: 0.6675
valid [sampled], NDCG@5: 0.5681, HR@5: 0.5803, NDCG@10: 0.5859, HR@10: 0.6359, MRR: 0.5867
test [full], NDCG@5: 0.6977, HR@5: 0.9398, NDCG@10: 0.7174, HR@10: 1.0000, MRR: 0.6212
test [sampled], NDCG@5: 0.0956, HR@5: 0.1208, NDCG@10: 0.1822, HR@10: 0.3974, MRR: 0.1592
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=16, loss=0.0934
epoch=17, loss=0.0908
epoch=18, loss=0.0914
epoch=19, loss=0.0895
epoch=20, loss=0.0901
valid [full], NDCG@5: 0.7096, HR@5: 0.8645, NDCG@10: 0.7419, HR@10: 0.9698, MRR: 0.6738
valid [sampled], NDCG@5: 0.5665, HR@5: 0.5780, NDCG@10: 0.5850, HR@10: 0.6360, MRR: 0.5852
test [full], NDCG@5: 0.7647, HR@5: 0.9357, NDCG@10: 0.7857, HR@10: 0.9999, MRR: 0.7149
test [sampled], NDCG@5: 0.1158, HR@5: 0.1939, NDCG@10: 0.1993, HR@10: 0.4535, MRR: 0.1566
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=21, loss=0.0874
epoch=22, loss=0.0880
epoch=23, loss=0.0886
epoch=24, loss=0.0867
epoch=25, loss=0.0863
valid [full], NDCG@5: 0.6960, HR@5: 0.8418, NDCG@10: 0.7287, HR@10: 0.9466, MRR: 0.6658
valid [sampled], NDCG@5: 0.5573, HR@5: 0.5684, NDCG@10: 0.5759, HR@10: 0.6266, MRR: 0.5757
test [full], NDCG@5: 0.8214, HR@5: 0.9458, NDCG@10: 0.8386, HR@10: 0.9999, MRR: 0.7851
test [sampled], NDCG@5: 0.1314, HR@5: 0.2273, NDCG@10: 0.2373, HR@10: 0.5541, MRR: 0.1706
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0849
epoch=27, loss=0.0864
epoch=28, loss=0.0851
epoch=29, loss=0.0861
epoch=30, loss=0.0847
valid [full], NDCG@5: 0.6912, HR@5: 0.8314, NDCG@10: 0.7275, HR@10: 0.9464, MRR: 0.6642
valid [sampled], NDCG@5: 0.5600, HR@5: 0.5714, NDCG@10: 0.5757, HR@10: 0.6200, MRR: 0.5769
test [full], NDCG@5: 0.8615, HR@5: 0.9401, NDCG@10: 0.8803, HR@10: 1.0000, MRR: 0.8419
test [sampled], NDCG@5: 0.3234, HR@5: 0.3999, NDCG@10: 0.3962, HR@10: 0.6242, MRR: 0.3494
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0835
epoch=32, loss=0.0825
epoch=33, loss=0.0834
epoch=34, loss=0.0816
epoch=35, loss=0.0809
valid [full], NDCG@5: 0.6831, HR@5: 0.8227, NDCG@10: 0.7237, HR@10: 0.9503, MRR: 0.6577
valid [sampled], NDCG@5: 0.5612, HR@5: 0.5733, NDCG@10: 0.5795, HR@10: 0.6306, MRR: 0.5785
test [full], NDCG@5: 0.7426, HR@5: 0.9483, NDCG@10: 0.7594, HR@10: 1.0000, MRR: 0.6782
test [sampled], NDCG@5: 0.1924, HR@5: 0.2197, NDCG@10: 0.2693, HR@10: 0.4658, MRR: 0.2467
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0799
epoch=37, loss=0.0782
epoch=38, loss=0.0793
epoch=39, loss=0.0792
epoch=40, loss=0.0806
valid [full], NDCG@5: 0.6970, HR@5: 0.8429, NDCG@10: 0.7290, HR@10: 0.9447, MRR: 0.6662
valid [sampled], NDCG@5: 0.5680, HR@5: 0.5794, NDCG@10: 0.5842, HR@10: 0.6303, MRR: 0.5854
test [full], NDCG@5: 0.7295, HR@5: 0.9629, NDCG@10: 0.7418, HR@10: 1.0000, MRR: 0.6557
test [sampled], NDCG@5: 0.2361, HR@5: 0.2505, NDCG@10: 0.2753, HR@10: 0.3767, MRR: 0.2850
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0795
epoch=42, loss=0.0795
epoch=43, loss=0.0784
epoch=44, loss=0.0767
epoch=45, loss=0.0773
valid [full], NDCG@5: 0.6908, HR@5: 0.8203, NDCG@10: 0.7288, HR@10: 0.9388, MRR: 0.6679
valid [sampled], NDCG@5: 0.5618, HR@5: 0.5772, NDCG@10: 0.5834, HR@10: 0.6450, MRR: 0.5790
test [full], NDCG@5: 0.7319, HR@5: 0.9571, NDCG@10: 0.7454, HR@10: 1.0000, MRR: 0.6610
test [sampled], NDCG@5: 0.2106, HR@5: 0.2353, NDCG@10: 0.2535, HR@10: 0.3715, MRR: 0.2574
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0745
epoch=47, loss=0.0755
epoch=48, loss=0.0754
epoch=49, loss=0.0743
epoch=50, loss=0.0758
valid [full], NDCG@5: 0.7082, HR@5: 0.8427, NDCG@10: 0.7389, HR@10: 0.9405, MRR: 0.6799
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5733, NDCG@10: 0.5860, HR@10: 0.6583, MRR: 0.5790
test [full], NDCG@5: 0.8050, HR@5: 0.9623, NDCG@10: 0.8179, HR@10: 1.0000, MRR: 0.7558
test [sampled], NDCG@5: 0.2773, HR@5: 0.3136, NDCG@10: 0.3454, HR@10: 0.5285, MRR: 0.3217
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s42/sasrec_last.pth

### attnbias_dstart_ml50_do035_b9_s2024

In [25]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b9_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024
epoch=1, loss=0.6139
epoch=2, loss=0.2744
epoch=3, loss=0.2006
epoch=4, loss=0.1654
epoch=5, loss=0.1461
valid [full], NDCG@5: 0.6635, HR@5: 0.7946, NDCG@10: 0.7241, HR@10: 0.9791, MRR: 0.6490
valid [sampled], NDCG@5: 0.5612, HR@5: 0.5656, NDCG@10: 0.5697, HR@10: 0.5924, MRR: 0.5772
test [full], NDCG@5: 0.7707, HR@5: 0.9296, NDCG@10: 0.7940, HR@10: 1.0000, MRR: 0.7285
test [sampled], NDCG@5: 0.2083, HR@5: 0.2682, NDCG@10: 0.2660, HR@10: 0.4467, MRR: 0.2421
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1315
epoch=7, loss=0.1228
epoch=8, loss=0.1167
epoch=9, loss=0.1107
epoch=10, loss=0.1087
valid [full], NDCG@5: 0.6654, HR@5: 0.7988, NDCG@10: 0.7227, HR@10: 0.9714, MRR: 0.6498
valid [sampled], NDCG@5: 0.5481, HR@5: 0.5588, NDCG@10: 0.5605, HR@10: 0.5973, MRR: 0.5637
test [full], NDCG@5: 0.8169, HR@5: 0.9172, NDCG@10: 0.8437, HR@10: 1.0000, MRR: 0.7941
test [sampled], NDCG@5: 0.1528, HR@5: 0.2547, NDCG@10: 0.2533, HR@10: 0.5651, MRR: 0.1853
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1060
epoch=12, loss=0.1016
epoch=13, loss=0.0989
epoch=14, loss=0.0987
epoch=15, loss=0.0977
valid [full], NDCG@5: 0.7016, HR@5: 0.8755, NDCG@10: 0.7319, HR@10: 0.9716, MRR: 0.6610
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5796, NDCG@10: 0.5807, HR@10: 0.6219, MRR: 0.5824
test [full], NDCG@5: 0.8307, HR@5: 0.9232, NDCG@10: 0.8544, HR@10: 1.0000, MRR: 0.8087
test [sampled], NDCG@5: 0.2059, HR@5: 0.2980, NDCG@10: 0.2863, HR@10: 0.5445, MRR: 0.2333
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=16, loss=0.0951
epoch=17, loss=0.0933
epoch=18, loss=0.0928
epoch=19, loss=0.0932
epoch=20, loss=0.0916
valid [full], NDCG@5: 0.7030, HR@5: 0.8653, NDCG@10: 0.7354, HR@10: 0.9715, MRR: 0.6650
valid [sampled], NDCG@5: 0.5490, HR@5: 0.5582, NDCG@10: 0.5662, HR@10: 0.6125, MRR: 0.5686
test [full], NDCG@5: 0.8639, HR@5: 0.9282, NDCG@10: 0.8857, HR@10: 0.9999, MRR: 0.8510
test [sampled], NDCG@5: 0.3661, HR@5: 0.4362, NDCG@10: 0.4281, HR@10: 0.6263, MRR: 0.3882
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=21, loss=0.0916
epoch=22, loss=0.0890
epoch=23, loss=0.0884
epoch=24, loss=0.0907
epoch=25, loss=0.0890
valid [full], NDCG@5: 0.6963, HR@5: 0.8717, NDCG@10: 0.7290, HR@10: 0.9744, MRR: 0.6556
valid [sampled], NDCG@5: 0.5432, HR@5: 0.5534, NDCG@10: 0.5584, HR@10: 0.6013, MRR: 0.5618
test [full], NDCG@5: 0.8698, HR@5: 0.9384, NDCG@10: 0.8887, HR@10: 1.0000, MRR: 0.8543
test [sampled], NDCG@5: 0.4023, HR@5: 0.4649, NDCG@10: 0.4545, HR@10: 0.6258, MRR: 0.4229
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0858
epoch=27, loss=0.0863
epoch=28, loss=0.0866
epoch=29, loss=0.0888
epoch=30, loss=0.0847
valid [full], NDCG@5: 0.6764, HR@5: 0.8391, NDCG@10: 0.7140, HR@10: 0.9592, MRR: 0.6423
valid [sampled], NDCG@5: 0.5324, HR@5: 0.5371, NDCG@10: 0.5426, HR@10: 0.5698, MRR: 0.5514
test [full], NDCG@5: 0.8728, HR@5: 0.9468, NDCG@10: 0.8890, HR@10: 1.0000, MRR: 0.8546
test [sampled], NDCG@5: 0.4011, HR@5: 0.4574, NDCG@10: 0.4492, HR@10: 0.6058, MRR: 0.4236
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0859
epoch=32, loss=0.0868
epoch=33, loss=0.0837
epoch=34, loss=0.0848
epoch=35, loss=0.0838
valid [full], NDCG@5: 0.6816, HR@5: 0.8481, NDCG@10: 0.7211, HR@10: 0.9737, MRR: 0.6462
valid [sampled], NDCG@5: 0.5451, HR@5: 0.5493, NDCG@10: 0.5556, HR@10: 0.5829, MRR: 0.5645
test [full], NDCG@5: 0.8355, HR@5: 0.9384, NDCG@10: 0.8543, HR@10: 0.9999, MRR: 0.8085
test [sampled], NDCG@5: 0.3383, HR@5: 0.3973, NDCG@10: 0.3980, HR@10: 0.5818, MRR: 0.3657
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0844
epoch=37, loss=0.0826
epoch=38, loss=0.0835
epoch=39, loss=0.0841
epoch=40, loss=0.0821
valid [full], NDCG@5: 0.6987, HR@5: 0.8646, NDCG@10: 0.7339, HR@10: 0.9756, MRR: 0.6616
valid [sampled], NDCG@5: 0.5523, HR@5: 0.5559, NDCG@10: 0.5672, HR@10: 0.6036, MRR: 0.5738
test [full], NDCG@5: 0.8741, HR@5: 0.9517, NDCG@10: 0.8894, HR@10: 0.9999, MRR: 0.8548
test [sampled], NDCG@5: 0.3992, HR@5: 0.4582, NDCG@10: 0.4496, HR@10: 0.6135, MRR: 0.4212
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0829
epoch=42, loss=0.0828
epoch=43, loss=0.0829
epoch=44, loss=0.0800
epoch=45, loss=0.0814
valid [full], NDCG@5: 0.7003, HR@5: 0.8541, NDCG@10: 0.7334, HR@10: 0.9608, MRR: 0.6666
valid [sampled], NDCG@5: 0.5540, HR@5: 0.5597, NDCG@10: 0.5742, HR@10: 0.6245, MRR: 0.5759
test [full], NDCG@5: 0.8184, HR@5: 0.9700, NDCG@10: 0.8290, HR@10: 0.9999, MRR: 0.7714
test [sampled], NDCG@5: 0.3701, HR@5: 0.3812, NDCG@10: 0.4146, HR@10: 0.5242, MRR: 0.4127
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0795
epoch=47, loss=0.0803
epoch=48, loss=0.0802
epoch=49, loss=0.0784
epoch=50, loss=0.0807
valid [full], NDCG@5: 0.6860, HR@5: 0.8556, NDCG@10: 0.7233, HR@10: 0.9742, MRR: 0.6485
valid [sampled], NDCG@5: 0.5325, HR@5: 0.5343, NDCG@10: 0.5422, HR@10: 0.5658, MRR: 0.5546
test [full], NDCG@5: 0.8672, HR@5: 0.9492, NDCG@10: 0.8837, HR@10: 0.9999, MRR: 0.8474
test [sampled], NDCG@5: 0.4128, HR@5: 0.4688, NDCG@10: 0.4602, HR@10: 0.6143, MRR: 0.4346
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s2024/sasrec_last.pth

### attnbias_dstart_ml50_do035_b9_s7

In [26]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b9_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7
epoch=1, loss=0.5867
epoch=2, loss=0.2771
epoch=3, loss=0.2056
epoch=4, loss=0.1732
epoch=5, loss=0.1501
valid [full], NDCG@5: 0.6290, HR@5: 0.7278, NDCG@10: 0.6913, HR@10: 0.9195, MRR: 0.6303
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5594, NDCG@10: 0.5641, HR@10: 0.5900, MRR: 0.5691
test [full], NDCG@5: 0.6675, HR@5: 0.8424, NDCG@10: 0.6993, HR@10: 0.9423, MRR: 0.6256
test [sampled], NDCG@5: 0.2334, HR@5: 0.2392, NDCG@10: 0.2791, HR@10: 0.3871, MRR: 0.2815
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=6, loss=0.1316
epoch=7, loss=0.1208
epoch=8, loss=0.1133
epoch=9, loss=0.1094
epoch=10, loss=0.1044
valid [full], NDCG@5: 0.6863, HR@5: 0.8396, NDCG@10: 0.7243, HR@10: 0.9563, MRR: 0.6570
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5600, NDCG@10: 0.5638, HR@10: 0.5788, MRR: 0.5761
test [full], NDCG@5: 0.7498, HR@5: 0.9927, NDCG@10: 0.7523, HR@10: 1.0000, MRR: 0.6673
test [sampled], NDCG@5: 0.1573, HR@5: 0.1709, NDCG@10: 0.2279, HR@10: 0.3983, MRR: 0.2192
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=11, loss=0.1038
epoch=12, loss=0.1001
epoch=13, loss=0.0967
epoch=14, loss=0.0922
epoch=15, loss=0.0942
valid [full], NDCG@5: 0.6728, HR@5: 0.8170, NDCG@10: 0.7200, HR@10: 0.9672, MRR: 0.6477
valid [sampled], NDCG@5: 0.5449, HR@5: 0.5465, NDCG@10: 0.5566, HR@10: 0.5844, MRR: 0.5656
test [full], NDCG@5: 0.7234, HR@5: 0.9966, NDCG@10: 0.7245, HR@10: 1.0000, MRR: 0.6293
test [sampled], NDCG@5: 0.1805, HR@5: 0.2104, NDCG@10: 0.2489, HR@10: 0.4283, MRR: 0.2318
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0927
epoch=17, loss=0.0892
epoch=18, loss=0.0883
epoch=19, loss=0.0860
epoch=20, loss=0.0858
valid [full], NDCG@5: 0.7028, HR@5: 0.8460, NDCG@10: 0.7407, HR@10: 0.9673, MRR: 0.6733
valid [sampled], NDCG@5: 0.5583, HR@5: 0.5714, NDCG@10: 0.5868, HR@10: 0.6612, MRR: 0.5794
test [full], NDCG@5: 0.8587, HR@5: 0.9968, NDCG@10: 0.8597, HR@10: 1.0000, MRR: 0.8117
test [sampled], NDCG@5: 0.3058, HR@5: 0.3833, NDCG@10: 0.3792, HR@10: 0.6092, MRR: 0.3337
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=21, loss=0.0853
epoch=22, loss=0.0830
epoch=23, loss=0.0830
epoch=24, loss=0.0824
epoch=25, loss=0.0798
valid [full], NDCG@5: 0.7094, HR@5: 0.8517, NDCG@10: 0.7461, HR@10: 0.9719, MRR: 0.6795
valid [sampled], NDCG@5: 0.5756, HR@5: 0.5867, NDCG@10: 0.5969, HR@10: 0.6535, MRR: 0.5942
test [full], NDCG@5: 0.8432, HR@5: 0.9982, NDCG@10: 0.8438, HR@10: 1.0000, MRR: 0.7908
test [sampled], NDCG@5: 0.3458, HR@5: 0.4017, NDCG@10: 0.4035, HR@10: 0.5807, MRR: 0.3753
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=26, loss=0.0825
epoch=27, loss=0.0807
epoch=28, loss=0.0807
epoch=29, loss=0.0800
epoch=30, loss=0.0776
valid [full], NDCG@5: 0.7023, HR@5: 0.8344, NDCG@10: 0.7452, HR@10: 0.9726, MRR: 0.6779
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5682, NDCG@10: 0.5822, HR@10: 0.6453, MRR: 0.5783
test [full], NDCG@5: 0.8470, HR@5: 0.9972, NDCG@10: 0.8479, HR@10: 1.0000, MRR: 0.7957
test [sampled], NDCG@5: 0.4020, HR@5: 0.4221, NDCG@10: 0.4588, HR@10: 0.6029, MRR: 0.4438
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0782
epoch=32, loss=0.0786
epoch=33, loss=0.0779
epoch=34, loss=0.0771
epoch=35, loss=0.0790
valid [full], NDCG@5: 0.6635, HR@5: 0.7933, NDCG@10: 0.7053, HR@10: 0.9287, MRR: 0.6434
valid [sampled], NDCG@5: 0.5415, HR@5: 0.5476, NDCG@10: 0.5542, HR@10: 0.5881, MRR: 0.5596
test [full], NDCG@5: 0.8101, HR@5: 0.9984, NDCG@10: 0.8107, HR@10: 1.0000, MRR: 0.7457
test [sampled], NDCG@5: 0.3954, HR@5: 0.4041, NDCG@10: 0.4462, HR@10: 0.5673, MRR: 0.4402
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0774
epoch=37, loss=0.0767
epoch=38, loss=0.0763
epoch=39, loss=0.0769
epoch=40, loss=0.0766
valid [full], NDCG@5: 0.7149, HR@5: 0.8247, NDCG@10: 0.7554, HR@10: 0.9539, MRR: 0.6992
valid [sampled], NDCG@5: 0.6074, HR@5: 0.6155, NDCG@10: 0.6233, HR@10: 0.6661, MRR: 0.6236
test [full], NDCG@5: 0.8467, HR@5: 0.9997, NDCG@10: 0.8468, HR@10: 1.0000, MRR: 0.7940
test [sampled], NDCG@5: 0.4421, HR@5: 0.4502, NDCG@10: 0.4972, HR@10: 0.6282, MRR: 0.4853
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=41, loss=0.0796
epoch=42, loss=0.0754
epoch=43, loss=0.0769
epoch=44, loss=0.0759
epoch=45, loss=0.0764
valid [full], NDCG@5: 0.7126, HR@5: 0.8514, NDCG@10: 0.7431, HR@10: 0.9509, MRR: 0.6821
valid [sampled], NDCG@5: 0.5587, HR@5: 0.5728, NDCG@10: 0.5884, HR@10: 0.6665, MRR: 0.5800
test [full], NDCG@5: 0.9217, HR@5: 0.9977, NDCG@10: 0.9225, HR@10: 1.0000, MRR: 0.8962
test [sampled], NDCG@5: 0.4570, HR@5: 0.5255, NDCG@10: 0.5166, HR@10: 0.7083, MRR: 0.4775
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0748
epoch=47, loss=0.0745
epoch=48, loss=0.0749
epoch=49, loss=0.0741
epoch=50, loss=0.0751
valid [full], NDCG@5: 0.7146, HR@5: 0.8197, NDCG@10: 0.7484, HR@10: 0.9285, MRR: 0.6995
valid [sampled], NDCG@5: 0.6119, HR@5: 0.6265, NDCG@10: 0.6305, HR@10: 0.6845, MRR: 0.6254
test [full], NDCG@5: 0.9335, HR@5: 0.9972, NDCG@10: 0.9345, HR@10: 1.0000, MRR: 0.9124
test [sampled], NDCG@5: 0.4661, HR@5: 0.5387, NDCG@10: 0.5294, HR@10: 0.7334, MRR: 0.4852
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml50_do035_b9_s7/sasrec_last.pth

## Train attention-bias runs for `NDCG@5`

### attnbias_dstart_ml50_do035_b9_s42

In [27]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b9_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42
epoch=1, loss=0.5936
epoch=2, loss=0.2727
epoch=3, loss=0.2056
epoch=4, loss=0.1713
epoch=5, loss=0.1476
valid [full], NDCG@5: 0.6324, HR@5: 0.7276, NDCG@10: 0.6819, HR@10: 0.8820, MRR: 0.6321
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5589, NDCG@10: 0.5654, HR@10: 0.5834, MRR: 0.5736
test [full], NDCG@5: 0.5722, HR@5: 0.7453, NDCG@10: 0.6007, HR@10: 0.8397, MRR: 0.5381
test [sampled], NDCG@5: 0.1982, HR@5: 0.1995, NDCG@10: 0.2166, HR@10: 0.2600, MRR: 0.2390
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=6, loss=0.1335
epoch=7, loss=0.1231
epoch=8, loss=0.1147
epoch=9, loss=0.1094
epoch=10, loss=0.1081
valid [full], NDCG@5: 0.6581, HR@5: 0.7762, NDCG@10: 0.7187, HR@10: 0.9624, MRR: 0.6485
valid [sampled], NDCG@5: 0.5643, HR@5: 0.5776, NDCG@10: 0.5766, HR@10: 0.6156, MRR: 0.5779
test [full], NDCG@5: 0.6647, HR@5: 0.9134, NDCG@10: 0.6934, HR@10: 0.9999, MRR: 0.5933
test [sampled], NDCG@5: 0.1667, HR@5: 0.1818, NDCG@10: 0.2158, HR@10: 0.3390, MRR: 0.2165
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=11, loss=0.1054
epoch=12, loss=0.1024
epoch=13, loss=0.0993
epoch=14, loss=0.0973
epoch=15, loss=0.0971
valid [full], NDCG@5: 0.7054, HR@5: 0.8681, NDCG@10: 0.7352, HR@10: 0.9644, MRR: 0.6668
valid [sampled], NDCG@5: 0.5668, HR@5: 0.5794, NDCG@10: 0.5865, HR@10: 0.6411, MRR: 0.5856
test [full], NDCG@5: 0.6995, HR@5: 0.9394, NDCG@10: 0.7194, HR@10: 1.0000, MRR: 0.6246
test [sampled], NDCG@5: 0.1034, HR@5: 0.1321, NDCG@10: 0.1878, HR@10: 0.4013, MRR: 0.1640
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=16, loss=0.0934
epoch=17, loss=0.0909
epoch=18, loss=0.0912
epoch=19, loss=0.0893
epoch=20, loss=0.0901
valid [full], NDCG@5: 0.7091, HR@5: 0.8623, NDCG@10: 0.7418, HR@10: 0.9698, MRR: 0.6738
valid [sampled], NDCG@5: 0.5665, HR@5: 0.5780, NDCG@10: 0.5853, HR@10: 0.6368, MRR: 0.5852
test [full], NDCG@5: 0.7632, HR@5: 0.9360, NDCG@10: 0.7832, HR@10: 0.9999, MRR: 0.7119
test [sampled], NDCG@5: 0.1123, HR@5: 0.1903, NDCG@10: 0.1944, HR@10: 0.4452, MRR: 0.1528
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/sasrec_best.pth
epoch=21, loss=0.0873
epoch=22, loss=0.0879
epoch=23, loss=0.0885
epoch=24, loss=0.0867
epoch=25, loss=0.0861
valid [full], NDCG@5: 0.6816, HR@5: 0.8132, NDCG@10: 0.7261, HR@10: 0.9526, MRR: 0.6607
valid [sampled], NDCG@5: 0.5564, HR@5: 0.5670, NDCG@10: 0.5756, HR@10: 0.6271, MRR: 0.5742
test [full], NDCG@5: 0.7695, HR@5: 0.9347, NDCG@10: 0.7897, HR@10: 0.9999, MRR: 0.7209
test [sampled], NDCG@5: 0.1098, HR@5: 0.1891, NDCG@10: 0.1939, HR@10: 0.4491, MRR: 0.1502
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0849
epoch=27, loss=0.0860
epoch=28, loss=0.0845
epoch=29, loss=0.0855
epoch=30, loss=0.0842
valid [full], NDCG@5: 0.6957, HR@5: 0.8377, NDCG@10: 0.7295, HR@10: 0.9463, MRR: 0.6666
valid [sampled], NDCG@5: 0.5602, HR@5: 0.5721, NDCG@10: 0.5772, HR@10: 0.6251, MRR: 0.5776
test [full], NDCG@5: 0.8660, HR@5: 0.9420, NDCG@10: 0.8839, HR@10: 1.0000, MRR: 0.8466
test [sampled], NDCG@5: 0.2958, HR@5: 0.3847, NDCG@10: 0.3777, HR@10: 0.6366, MRR: 0.3213
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0831
epoch=32, loss=0.0821
epoch=33, loss=0.0829
epoch=34, loss=0.0813
epoch=35, loss=0.0806
valid [full], NDCG@5: 0.6807, HR@5: 0.8192, NDCG@10: 0.7225, HR@10: 0.9504, MRR: 0.6563
valid [sampled], NDCG@5: 0.5612, HR@5: 0.5735, NDCG@10: 0.5776, HR@10: 0.6246, MRR: 0.5780
test [full], NDCG@5: 0.8516, HR@5: 0.9455, NDCG@10: 0.8691, HR@10: 1.0000, MRR: 0.8264
test [sampled], NDCG@5: 0.2677, HR@5: 0.3577, NDCG@10: 0.3534, HR@10: 0.6222, MRR: 0.2959
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0795
epoch=37, loss=0.0777
epoch=38, loss=0.0789
epoch=39, loss=0.0789
epoch=40, loss=0.0803
valid [full], NDCG@5: 0.7023, HR@5: 0.8483, NDCG@10: 0.7325, HR@10: 0.9452, MRR: 0.6704
valid [sampled], NDCG@5: 0.5668, HR@5: 0.5806, NDCG@10: 0.5891, HR@10: 0.6506, MRR: 0.5851
test [full], NDCG@5: 0.7273, HR@5: 0.9599, NDCG@10: 0.7395, HR@10: 1.0000, MRR: 0.6534
test [sampled], NDCG@5: 0.2394, HR@5: 0.2566, NDCG@10: 0.2811, HR@10: 0.3898, MRR: 0.2870
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0789
epoch=42, loss=0.0789
epoch=43, loss=0.0779
epoch=44, loss=0.0760
epoch=45, loss=0.0768
valid [full], NDCG@5: 0.6895, HR@5: 0.8217, NDCG@10: 0.7272, HR@10: 0.9393, MRR: 0.6655
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5746, NDCG@10: 0.5802, HR@10: 0.6385, MRR: 0.5771
test [full], NDCG@5: 0.7717, HR@5: 0.9534, NDCG@10: 0.7862, HR@10: 1.0000, MRR: 0.7160
test [sampled], NDCG@5: 0.2500, HR@5: 0.2860, NDCG@10: 0.3022, HR@10: 0.4496, MRR: 0.2923
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0742
epoch=47, loss=0.0754
epoch=48, loss=0.0748
epoch=49, loss=0.0744
epoch=50, loss=0.0756
valid [full], NDCG@5: 0.7074, HR@5: 0.8459, NDCG@10: 0.7365, HR@10: 0.9393, MRR: 0.6773
valid [sampled], NDCG@5: 0.5584, HR@5: 0.5727, NDCG@10: 0.5839, HR@10: 0.6530, MRR: 0.5777
test [full], NDCG@5: 0.8728, HR@5: 0.9648, NDCG@10: 0.8849, HR@10: 1.0000, MRR: 0.8466
test [sampled], NDCG@5: 0.3341, HR@5: 0.4139, NDCG@10: 0.4040, HR@10: 0.6284, MRR: 0.3588
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s42/sasrec_last.pth

### attnbias_dstart_ml50_do035_b9_s2024

In [28]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b9_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024
epoch=1, loss=0.6139
epoch=2, loss=0.2744
epoch=3, loss=0.2006
epoch=4, loss=0.1654
epoch=5, loss=0.1460
valid [full], NDCG@5: 0.6628, HR@5: 0.7938, NDCG@10: 0.7237, HR@10: 0.9785, MRR: 0.6487
valid [sampled], NDCG@5: 0.5611, HR@5: 0.5654, NDCG@10: 0.5695, HR@10: 0.5920, MRR: 0.5771
test [full], NDCG@5: 0.7702, HR@5: 0.9285, NDCG@10: 0.7942, HR@10: 1.0000, MRR: 0.7287
test [sampled], NDCG@5: 0.2082, HR@5: 0.2682, NDCG@10: 0.2660, HR@10: 0.4470, MRR: 0.2421
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1315
epoch=7, loss=0.1229
epoch=8, loss=0.1165
epoch=9, loss=0.1106
epoch=10, loss=0.1086
valid [full], NDCG@5: 0.6603, HR@5: 0.7808, NDCG@10: 0.7240, HR@10: 0.9712, MRR: 0.6517
valid [sampled], NDCG@5: 0.5529, HR@5: 0.5636, NDCG@10: 0.5651, HR@10: 0.6013, MRR: 0.5681
test [full], NDCG@5: 0.8126, HR@5: 0.9093, NDCG@10: 0.8422, HR@10: 1.0000, MRR: 0.7921
test [sampled], NDCG@5: 0.1517, HR@5: 0.2519, NDCG@10: 0.2515, HR@10: 0.5607, MRR: 0.1846
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1059
epoch=12, loss=0.1017
epoch=13, loss=0.0989
epoch=14, loss=0.0987
epoch=15, loss=0.0976
valid [full], NDCG@5: 0.6966, HR@5: 0.8708, NDCG@10: 0.7282, HR@10: 0.9712, MRR: 0.6567
valid [sampled], NDCG@5: 0.5657, HR@5: 0.5770, NDCG@10: 0.5770, HR@10: 0.6119, MRR: 0.5806
test [full], NDCG@5: 0.8290, HR@5: 0.9280, NDCG@10: 0.8513, HR@10: 1.0000, MRR: 0.8044
test [sampled], NDCG@5: 0.2007, HR@5: 0.2902, NDCG@10: 0.2800, HR@10: 0.5342, MRR: 0.2292
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=16, loss=0.0953
epoch=17, loss=0.0933
epoch=18, loss=0.0928
epoch=19, loss=0.0932
epoch=20, loss=0.0914
valid [full], NDCG@5: 0.7022, HR@5: 0.8658, NDCG@10: 0.7351, HR@10: 0.9717, MRR: 0.6645
valid [sampled], NDCG@5: 0.5490, HR@5: 0.5582, NDCG@10: 0.5658, HR@10: 0.6112, MRR: 0.5685
test [full], NDCG@5: 0.8648, HR@5: 0.9292, NDCG@10: 0.8865, HR@10: 1.0000, MRR: 0.8519
test [sampled], NDCG@5: 0.3256, HR@5: 0.4049, NDCG@10: 0.3974, HR@10: 0.6248, MRR: 0.3491
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=21, loss=0.0916
epoch=22, loss=0.0890
epoch=23, loss=0.0886
epoch=24, loss=0.0907
epoch=25, loss=0.0889
valid [full], NDCG@5: 0.6794, HR@5: 0.8425, NDCG@10: 0.7210, HR@10: 0.9743, MRR: 0.6463
valid [sampled], NDCG@5: 0.5406, HR@5: 0.5469, NDCG@10: 0.5537, HR@10: 0.5881, MRR: 0.5591
test [full], NDCG@5: 0.8717, HR@5: 0.9439, NDCG@10: 0.8886, HR@10: 1.0000, MRR: 0.8543
test [sampled], NDCG@5: 0.4012, HR@5: 0.4619, NDCG@10: 0.4529, HR@10: 0.6214, MRR: 0.4226
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0858
epoch=27, loss=0.0863
epoch=28, loss=0.0864
epoch=29, loss=0.0887
epoch=30, loss=0.0847
valid [full], NDCG@5: 0.6852, HR@5: 0.8446, NDCG@10: 0.7179, HR@10: 0.9502, MRR: 0.6499
valid [sampled], NDCG@5: 0.5302, HR@5: 0.5343, NDCG@10: 0.5447, HR@10: 0.5804, MRR: 0.5520
test [full], NDCG@5: 0.8094, HR@5: 0.9541, NDCG@10: 0.8234, HR@10: 1.0000, MRR: 0.7651
test [sampled], NDCG@5: 0.3566, HR@5: 0.3701, NDCG@10: 0.4022, HR@10: 0.5170, MRR: 0.3981
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0859
epoch=32, loss=0.0868
epoch=33, loss=0.0836
epoch=34, loss=0.0846
epoch=35, loss=0.0837
valid [full], NDCG@5: 0.6918, HR@5: 0.8549, NDCG@10: 0.7288, HR@10: 0.9746, MRR: 0.6560
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5603, NDCG@10: 0.5667, HR@10: 0.5939, MRR: 0.5756
test [full], NDCG@5: 0.8700, HR@5: 0.9537, NDCG@10: 0.8841, HR@10: 0.9999, MRR: 0.8480
test [sampled], NDCG@5: 0.3989, HR@5: 0.4564, NDCG@10: 0.4465, HR@10: 0.6023, MRR: 0.4210
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0842
epoch=37, loss=0.0827
epoch=38, loss=0.0833
epoch=39, loss=0.0839
epoch=40, loss=0.0820
valid [full], NDCG@5: 0.7123, HR@5: 0.8817, NDCG@10: 0.7414, HR@10: 0.9756, MRR: 0.6708
valid [sampled], NDCG@5: 0.5542, HR@5: 0.5605, NDCG@10: 0.5725, HR@10: 0.6191, MRR: 0.5765
test [full], NDCG@5: 0.8789, HR@5: 0.9529, NDCG@10: 0.8945, HR@10: 0.9999, MRR: 0.8611
test [sampled], NDCG@5: 0.4062, HR@5: 0.4647, NDCG@10: 0.4561, HR@10: 0.6188, MRR: 0.4285
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/sasrec_best.pth
epoch=41, loss=0.0828
epoch=42, loss=0.0827
epoch=43, loss=0.0827
epoch=44, loss=0.0800
epoch=45, loss=0.0815
valid [full], NDCG@5: 0.7067, HR@5: 0.8551, NDCG@10: 0.7356, HR@10: 0.9486, MRR: 0.6734
valid [sampled], NDCG@5: 0.5575, HR@5: 0.5659, NDCG@10: 0.5823, HR@10: 0.6452, MRR: 0.5794
test [full], NDCG@5: 0.8123, HR@5: 0.9567, NDCG@10: 0.8272, HR@10: 0.9999, MRR: 0.7693
test [sampled], NDCG@5: 0.3789, HR@5: 0.3874, NDCG@10: 0.4215, HR@10: 0.5245, MRR: 0.4213
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0794
epoch=47, loss=0.0804
epoch=48, loss=0.0801
epoch=49, loss=0.0785
epoch=50, loss=0.0810
valid [full], NDCG@5: 0.6901, HR@5: 0.8527, NDCG@10: 0.7281, HR@10: 0.9739, MRR: 0.6554
valid [sampled], NDCG@5: 0.5474, HR@5: 0.5486, NDCG@10: 0.5577, HR@10: 0.5820, MRR: 0.5685
test [full], NDCG@5: 0.8762, HR@5: 0.9723, NDCG@10: 0.8860, HR@10: 0.9999, MRR: 0.8498
test [sampled], NDCG@5: 0.4891, HR@5: 0.5451, NDCG@10: 0.5332, HR@10: 0.6796, MRR: 0.5057
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s2024/sasrec_last.pth

### attnbias_dstart_ml50_do035_b9_s7

In [29]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b9_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7
epoch=1, loss=0.5867
epoch=2, loss=0.2771
epoch=3, loss=0.2056
epoch=4, loss=0.1732
epoch=5, loss=0.1501
valid [full], NDCG@5: 0.6290, HR@5: 0.7278, NDCG@10: 0.6913, HR@10: 0.9195, MRR: 0.6303
valid [sampled], NDCG@5: 0.5544, HR@5: 0.5594, NDCG@10: 0.5641, HR@10: 0.5900, MRR: 0.5691
test [full], NDCG@5: 0.6675, HR@5: 0.8424, NDCG@10: 0.6993, HR@10: 0.9423, MRR: 0.6256
test [sampled], NDCG@5: 0.2334, HR@5: 0.2392, NDCG@10: 0.2791, HR@10: 0.3871, MRR: 0.2815
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=6, loss=0.1316
epoch=7, loss=0.1208
epoch=8, loss=0.1133
epoch=9, loss=0.1094
epoch=10, loss=0.1044
valid [full], NDCG@5: 0.6862, HR@5: 0.8396, NDCG@10: 0.7242, HR@10: 0.9563, MRR: 0.6568
valid [sampled], NDCG@5: 0.5577, HR@5: 0.5598, NDCG@10: 0.5637, HR@10: 0.5788, MRR: 0.5760
test [full], NDCG@5: 0.7499, HR@5: 0.9931, NDCG@10: 0.7523, HR@10: 1.0000, MRR: 0.6672
test [sampled], NDCG@5: 0.1659, HR@5: 0.1790, NDCG@10: 0.2351, HR@10: 0.4019, MRR: 0.2272
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=11, loss=0.1038
epoch=12, loss=0.1002
epoch=13, loss=0.0968
epoch=14, loss=0.0923
epoch=15, loss=0.0942
valid [full], NDCG@5: 0.6743, HR@5: 0.8204, NDCG@10: 0.7209, HR@10: 0.9674, MRR: 0.6486
valid [sampled], NDCG@5: 0.5464, HR@5: 0.5491, NDCG@10: 0.5582, HR@10: 0.5874, MRR: 0.5667
test [full], NDCG@5: 0.7260, HR@5: 0.9962, NDCG@10: 0.7273, HR@10: 1.0000, MRR: 0.6327
test [sampled], NDCG@5: 0.1579, HR@5: 0.1842, NDCG@10: 0.2321, HR@10: 0.4209, MRR: 0.2140
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0928
epoch=17, loss=0.0891
epoch=18, loss=0.0883
epoch=19, loss=0.0860
epoch=20, loss=0.0856
valid [full], NDCG@5: 0.7036, HR@5: 0.8459, NDCG@10: 0.7423, HR@10: 0.9701, MRR: 0.6746
valid [sampled], NDCG@5: 0.5615, HR@5: 0.5740, NDCG@10: 0.5894, HR@10: 0.6618, MRR: 0.5825
test [full], NDCG@5: 0.8665, HR@5: 0.9966, NDCG@10: 0.8677, HR@10: 1.0000, MRR: 0.8227
test [sampled], NDCG@5: 0.3493, HR@5: 0.4224, NDCG@10: 0.4124, HR@10: 0.6161, MRR: 0.3735
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=21, loss=0.0853
epoch=22, loss=0.0829
epoch=23, loss=0.0830
epoch=24, loss=0.0823
epoch=25, loss=0.0797
valid [full], NDCG@5: 0.7053, HR@5: 0.8360, NDCG@10: 0.7465, HR@10: 0.9687, MRR: 0.6812
valid [sampled], NDCG@5: 0.5734, HR@5: 0.5853, NDCG@10: 0.5987, HR@10: 0.6649, MRR: 0.5927
test [full], NDCG@5: 0.8502, HR@5: 0.9984, NDCG@10: 0.8507, HR@10: 1.0000, MRR: 0.7998
test [sampled], NDCG@5: 0.3487, HR@5: 0.4050, NDCG@10: 0.4094, HR@10: 0.5936, MRR: 0.3798
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=26, loss=0.0824
epoch=27, loss=0.0808
epoch=28, loss=0.0807
epoch=29, loss=0.0800
epoch=30, loss=0.0776
valid [full], NDCG@5: 0.6913, HR@5: 0.8305, NDCG@10: 0.7354, HR@10: 0.9714, MRR: 0.6655
valid [sampled], NDCG@5: 0.5402, HR@5: 0.5506, NDCG@10: 0.5634, HR@10: 0.6233, MRR: 0.5613
test [full], NDCG@5: 0.8103, HR@5: 0.9970, NDCG@10: 0.8113, HR@10: 1.0000, MRR: 0.7482
test [sampled], NDCG@5: 0.4026, HR@5: 0.4074, NDCG@10: 0.4290, HR@10: 0.4925, MRR: 0.4430
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0783
epoch=32, loss=0.0786
epoch=33, loss=0.0780
epoch=34, loss=0.0771
epoch=35, loss=0.0789
valid [full], NDCG@5: 0.6710, HR@5: 0.8135, NDCG@10: 0.7028, HR@10: 0.9172, MRR: 0.6438
valid [sampled], NDCG@5: 0.5371, HR@5: 0.5455, NDCG@10: 0.5510, HR@10: 0.5895, MRR: 0.5555
test [full], NDCG@5: 0.8301, HR@5: 0.9993, NDCG@10: 0.8304, HR@10: 1.0000, MRR: 0.7722
test [sampled], NDCG@5: 0.4447, HR@5: 0.4527, NDCG@10: 0.4879, HR@10: 0.5913, MRR: 0.4849
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0777
epoch=37, loss=0.0768
epoch=38, loss=0.0764
epoch=39, loss=0.0769
epoch=40, loss=0.0767
valid [full], NDCG@5: 0.7289, HR@5: 0.8547, NDCG@10: 0.7657, HR@10: 0.9758, MRR: 0.7039
valid [sampled], NDCG@5: 0.6068, HR@5: 0.6162, NDCG@10: 0.6256, HR@10: 0.6760, MRR: 0.6241
test [full], NDCG@5: 0.8477, HR@5: 0.9997, NDCG@10: 0.8478, HR@10: 1.0000, MRR: 0.7953
test [sampled], NDCG@5: 0.4445, HR@5: 0.4528, NDCG@10: 0.5002, HR@10: 0.6324, MRR: 0.4877
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/sasrec_best.pth
epoch=41, loss=0.0796
epoch=42, loss=0.0752
epoch=43, loss=0.0769
epoch=44, loss=0.0759
epoch=45, loss=0.0765
valid [full], NDCG@5: 0.7117, HR@5: 0.8449, NDCG@10: 0.7447, HR@10: 0.9505, MRR: 0.6841
valid [sampled], NDCG@5: 0.5601, HR@5: 0.5749, NDCG@10: 0.5904, HR@10: 0.6704, MRR: 0.5814
test [full], NDCG@5: 0.9161, HR@5: 0.9995, NDCG@10: 0.9163, HR@10: 1.0000, MRR: 0.8877
test [sampled], NDCG@5: 0.4461, HR@5: 0.5079, NDCG@10: 0.5054, HR@10: 0.6914, MRR: 0.4699
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0747
epoch=47, loss=0.0746
epoch=48, loss=0.0748
epoch=49, loss=0.0741
epoch=50, loss=0.0751
valid [full], NDCG@5: 0.7165, HR@5: 0.8195, NDCG@10: 0.7510, HR@10: 0.9303, MRR: 0.7018
valid [sampled], NDCG@5: 0.6115, HR@5: 0.6258, NDCG@10: 0.6304, HR@10: 0.6849, MRR: 0.6259
test [full], NDCG@5: 0.8515, HR@5: 0.9974, NDCG@10: 0.8524, HR@10: 1.0000, MRR: 0.8011
test [sampled], NDCG@5: 0.4177, HR@5: 0.4355, NDCG@10: 0.4790, HR@10: 0.6309, MRR: 0.4602
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml50_do035_b9_s7/sasrec_last.pth

## Rebuild result tables

In [30]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'use_time_attention_bias': config.get('use_time_attention_bias', False),
            'time_modeling_mode': config.get('time_modeling_mode'),
            'time_encoding': config.get('time_encoding'),
            'time_delta_column': config.get('time_delta_column'),
            'time_bucket_boundaries_parsed': config.get('time_bucket_boundaries_parsed'),
            'time_attention_bias_bucket_count': config.get('time_attention_bias_bucket_count'),
            'primary_metric_name': config.get('selection_metric'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [31]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## NDCG@10 comparison summary

In [32]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
timeaware_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['time_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['time_variant'] = 'attention_bias_dstart_b9'

df_ndcg10 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'time_variant', 'use_time_embedding', 'use_time_attention_bias', 'time_modeling_mode',
    'time_delta_column', 'time_bucket_boundaries_parsed', 'time_attention_bias_bucket_count',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                              run_name  seed              time_variant  use_time_embedding  use_time_attention_bias time_modeling_mode    time_delta_column             time_bucket_boundaries_parsed time_attention_bias_bucket_count  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     attnbias_dstart_ml50_do035_b9_s7     7  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.755366               0.953861                0.714870              0.824671             0.699184                0.846762              1.000000               0.846665             0.999728            0.793978                    0.623265                  0.666077                   0.607399                 0.615479                0.623619                   0.497216                 0.628223                  0.442098                0.450204               0.485290
1    attnbias_dstart_ml50_do035_b9_s42    42  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.741856               0.969750                0.709565              0.864487             0.673783                0.785724              0.999865               0.764719             0.935724            0.714860                    0.585005                  0.635957                   0.566501                 0.577970                0.585189                   0.199334                 0.453522                  0.115783                0.193920               0.156593
2  attnbias_dstart_ml50_do035_b9_s2024  2024  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.735385               0.971475                0.702964              0.865254             0.665031                0.885738              0.999865               0.863911             0.928234            0.850981                    0.566216                  0.612548                   0.548977                 0.558247                0.568592                   0.428086                 0.626287                  0.366083                0.436179               0.388188
3                 refine_ml50_do035_s7     7                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
4                refine_ml50_do035_s42    42                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
5              refine_ml50_do035_s2024  2024                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183

In [33]:
summary_ndcg10 = df_ndcg10.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

                         best_valid_full_ndcg@10           best_test_full_ndcg@10           best_valid_full_ndcg@5           best_test_full_ndcg@5           best_valid_full_mrr           best_test_full_mrr           best_valid_sampled_ndcg@10           best_test_sampled_ndcg@10           best_valid_sampled_ndcg@5           best_test_sampled_ndcg@5           best_valid_sampled_mrr           best_test_sampled_mrr
                                            mean       std                   mean       std                   mean       std                  mean       std                mean       std               mean       std                       mean       std                      mean       std                      mean       std                     mean       std                   mean       std                  mean       std
time_variant
attention_bias_dstart_b9                0.744203  0.010195               0.839408  0.050411               0.709133  0.005965              0.825099  0.052996            0.679333  0.017740           0.786607  0.068359                   0.591495  0.029073                  0.374879  0.155906                  0.574292  0.029980                 0.307988  0.170739               0.592467  0.028226              0.343357  0.168872
baseline                                0.735259  0.006374               0.846684  0.062093               0.702263  0.009451              0.818405  0.078916            0.662771  0.002053           0.798923  0.080599                   0.572973  0.004280                  0.372338  0.102528                  0.561597  0.005491                 0.309277  0.098875               0.579235  0.005635              0.333054  0.093175

Interpretation guide for NDCG@10:
- compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` first
- then check whether sampled and MRR move in the same direction
- baseline is reused; only attention-bias runs are newly trained here

## NDCG@5 comparison summary

In [34]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
timeaware_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['time_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['time_variant'] = 'attention_bias_dstart_b9'

df_ndcg5 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'time_variant', 'use_time_embedding', 'use_time_attention_bias', 'time_modeling_mode',
    'time_delta_column', 'time_bucket_boundaries_parsed', 'time_attention_bias_bucket_count',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                              run_name  seed              time_variant  use_time_embedding  use_time_attention_bias time_modeling_mode    time_delta_column             time_bucket_boundaries_parsed time_attention_bias_bucket_count  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     attnbias_dstart_ml50_do035_b9_s7     7  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.765708               0.975845                0.728865              0.854661             0.703877                0.847794              1.000000               0.847697             0.999728            0.795264                    0.625614                  0.676007                   0.606813                 0.616159                0.624051                   0.500175                 0.632429                  0.444546                0.452782               0.487732
1    attnbias_dstart_ml50_do035_b9_s42    42  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.741824               0.969750                0.709060              0.862317             0.673822                0.783187              0.999865               0.763183             0.935995            0.711912                    0.585252                  0.636770                   0.566501                 0.577970                0.585234                   0.194366                 0.445244                  0.112266                0.190256               0.152804
2  attnbias_dstart_ml50_do035_b9_s2024  2024  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.741407               0.975616                0.712340              0.881719             0.670798                0.894503              0.999865               0.878950             0.952884            0.861072                    0.572542                  0.619131                   0.554208                 0.560547                0.576476                   0.456145                 0.618822                  0.406179                0.464726               0.428497
3                 refine_ml50_do035_s7     7                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
4                refine_ml50_do035_s42    42                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
5              refine_ml50_do035_s2024  2024                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183

In [35]:
summary_ndcg5 = df_ndcg5.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

                         best_valid_full_ndcg@10           best_test_full_ndcg@10           best_valid_full_ndcg@5           best_test_full_ndcg@5           best_valid_full_mrr           best_test_full_mrr           best_valid_sampled_ndcg@10           best_test_sampled_ndcg@10           best_valid_sampled_ndcg@5           best_test_sampled_ndcg@5           best_valid_sampled_mrr           best_test_sampled_mrr
                                            mean       std                   mean       std                   mean       std                  mean       std                mean       std               mean       std                       mean       std                      mean       std                      mean       std                     mean       std                   mean       std                  mean       std
time_variant
attention_bias_dstart_b9                0.749646  0.013911               0.841828  0.055897               0.716755  0.010615              0.829944  0.059891            0.682833  0.018287           0.789416  0.074752                   0.594469  0.027711                  0.383562  0.165321                  0.575841  0.027518                 0.320997  0.181781               0.595254  0.025321              0.356344  0.178742
baseline                                0.735259  0.006374               0.846684  0.062093               0.702263  0.009451              0.818405  0.078916            0.662771  0.002053           0.798923  0.080599                   0.572973  0.004280                  0.372338  0.102528                  0.561597  0.005491                 0.309277  0.098875               0.579235  0.005635              0.333054  0.093175

Interpretation guide for NDCG@5:
- compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` first
- then check whether sampled and MRR move in the same direction
- baseline is reused; only attention-bias runs are newly trained here