# SASRec Time-Aware BPI2012 Colab Train (`refine_ml50_do035` baseline)

Colab notebook for the next time-aware SASRec experiment using `refine_ml50_do035` as the fixed baseline.

Goals:
- reuse the completed `refine_ml50_do035` baseline results
- train only the new time-aware runs
- compare baseline vs `8-bucket` vs `9-bucket`
- evaluate under both `NDCG@10` and `NDCG@5` model-selection criteria

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
TIMEAWARE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10'
TIMEAWARE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('TIMEAWARE_NDCG10_OUTPUT_DIR:', TIMEAWARE_NDCG10_OUTPUT_DIR)
print('TIMEAWARE_NDCG5_OUTPUT_DIR:', TIMEAWARE_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
TIMEAWARE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10
TIMEAWARE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG10_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `refine_ml50_do035`
- `hidden_units=50, num_blocks=2, num_heads=1, maxlen=50, lr=0.001, dropout=0.35`
- seeds: `42`, `2024`, `7`

Comparison targets:
- baseline (reuse existing completed runs)
- time-aware `8-bucket`
- time-aware `9-bucket`

Time-aware design:
- `x = item_embedding + positional_embedding + time_embedding`
- time source: `delta_prev_seconds`

## Check existing baseline runs

These baseline runs should already exist and must not be retrained.

In [10]:
from pathlib import Path

baseline_ndcg10_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
baseline_ndcg5_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

for label, output_dir, run_names in [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR), baseline_ndcg10_runs),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR), baseline_ndcg5_runs),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS
================================================================================
Baseline NDCG@5
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS

## Check planned time-aware runs

Only train runs that are still missing.

In [11]:
planned_ndcg10 = [
    'timeaware_refine_ml50_do035_b8_s42',
    'timeaware_refine_ml50_do035_b8_s2024',
    'timeaware_refine_ml50_do035_b8_s7',
    'timeaware_refine_ml50_do035_b9_s42',
    'timeaware_refine_ml50_do035_b9_s2024',
    'timeaware_refine_ml50_do035_b9_s7',
]
planned_ndcg5 = [
    'timeaware_refine_ml50_do035_b8_s42',
    'timeaware_refine_ml50_do035_b8_s2024',
    'timeaware_refine_ml50_do035_b8_s7',
    'timeaware_refine_ml50_do035_b9_s42',
    'timeaware_refine_ml50_do035_b9_s2024',
    'timeaware_refine_ml50_do035_b9_s7',
]

for label, output_dir, run_names in [
    ('Time-aware NDCG@10', Path(TIMEAWARE_NDCG10_OUTPUT_DIR), planned_ndcg10),
    ('Time-aware NDCG@5', Path(TIMEAWARE_NDCG5_OUTPUT_DIR), planned_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Time-aware NDCG@10
timeaware_refine_ml50_do035_b8_s42 EXISTS
timeaware_refine_ml50_do035_b8_s2024 EXISTS
timeaware_refine_ml50_do035_b8_s7 OK
timeaware_refine_ml50_do035_b9_s42 OK
timeaware_refine_ml50_do035_b9_s2024 OK
timeaware_refine_ml50_do035_b9_s7 OK
================================================================================
Time-aware NDCG@5
timeaware_refine_ml50_do035_b8_s42 OK
timeaware_refine_ml50_do035_b8_s2024 OK
timeaware_refine_ml50_do035_b8_s7 OK
timeaware_refine_ml50_do035_b9_s42 OK
timeaware_refine_ml50_do035_b9_s2024 OK
timeaware_refine_ml50_do035_b9_s7 OK

## Train time-aware runs for `NDCG@10`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_refine_ml50_do035_b8_s42

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b8_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42
epoch=1, loss=0.5829
epoch=2, loss=0.2632
epoch=3, loss=0.1991
epoch=4, loss=0.1635
epoch=5, loss=0.1403
valid [full], NDCG@5: 0.6186, HR@5: 0.6949, NDCG@10: 0.6822, HR@10: 0.8911, MRR: 0.6297
valid [sampled], NDCG@5: 0.5559, HR@5: 0.5598, NDCG@10: 0.5643, HR@10: 0.5868, MRR: 0.5701
test [full], NDCG@5: 0.5853, HR@5: 0.7508, NDCG@10: 0.6262, HR@10: 0.8816, MRR: 0.5557
test [sampled], NDCG@5: 0.2091, HR@5: 0.2126, NDCG@10: 0.2428, HR@10: 0.3219, MRR: 0.2514
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=6, loss=0.1243
epoch=7, loss=0.1149
epoch=8, loss=0.1071
epoch=9, loss=0.1018
epoch=10, loss=0.0998
valid [full], NDCG@5: 0.6446, HR@5: 0.7495, NDCG@10: 0.7148, HR@10: 0.9682, MRR: 0.6417
valid [sampled], NDCG@5: 0.5537, HR@5: 0.5680, NDCG@10: 0.5694, HR@10: 0.6170, MRR: 0.5682
test [full], NDCG@5: 0.6912, HR@5: 0.9186, NDCG@10: 0.7181, HR@10: 0.9999, MRR: 0.6248
test [sampled], NDCG@5: 0.1718, HR@5: 0.1864, NDCG@10: 0.2263, HR@10: 0.3620, MRR: 0.2261
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=11, loss=0.0970
epoch=12, loss=0.0937
epoch=13, loss=0.0909
epoch=14, loss=0.0899
epoch=15, loss=0.0887
valid [full], NDCG@5: 0.6778, HR@5: 0.8228, NDCG@10: 0.7262, HR@10: 0.9707, MRR: 0.6532
valid [sampled], NDCG@5: 0.5514, HR@5: 0.5644, NDCG@10: 0.5709, HR@10: 0.6256, MRR: 0.5697
test [full], NDCG@5: 0.7943, HR@5: 0.9552, NDCG@10: 0.8098, HR@10: 1.0000, MRR: 0.7459
test [sampled], NDCG@5: 0.2110, HR@5: 0.2795, NDCG@10: 0.2945, HR@10: 0.5402, MRR: 0.2506
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=16, loss=0.0862
epoch=17, loss=0.0829
epoch=18, loss=0.0832
epoch=19, loss=0.0825
epoch=20, loss=0.0829
valid [full], NDCG@5: 0.6884, HR@5: 0.8326, NDCG@10: 0.7338, HR@10: 0.9710, MRR: 0.6637
valid [sampled], NDCG@5: 0.5652, HR@5: 0.5765, NDCG@10: 0.5808, HR@10: 0.6248, MRR: 0.5818
test [full], NDCG@5: 0.7169, HR@5: 0.9421, NDCG@10: 0.7363, HR@10: 1.0000, MRR: 0.6478
test [sampled], NDCG@5: 0.1288, HR@5: 0.1645, NDCG@10: 0.2147, HR@10: 0.4379, MRR: 0.1850
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=21, loss=0.0799
epoch=22, loss=0.0799
epoch=23, loss=0.0803
epoch=24, loss=0.0786
epoch=25, loss=0.0798
valid [full], NDCG@5: 0.6816, HR@5: 0.8238, NDCG@10: 0.7207, HR@10: 0.9481, MRR: 0.6561
valid [sampled], NDCG@5: 0.5558, HR@5: 0.5667, NDCG@10: 0.5717, HR@10: 0.6161, MRR: 0.5720
test [full], NDCG@5: 0.7712, HR@5: 0.9605, NDCG@10: 0.7841, HR@10: 1.0000, MRR: 0.7115
test [sampled], NDCG@5: 0.1818, HR@5: 0.2177, NDCG@10: 0.2633, HR@10: 0.4748, MRR: 0.2345
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0776
epoch=27, loss=0.0801
epoch=28, loss=0.0774
epoch=29, loss=0.0786
epoch=30, loss=0.0777
valid [full], NDCG@5: 0.6871, HR@5: 0.8241, NDCG@10: 0.7278, HR@10: 0.9542, MRR: 0.6627
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5710, NDCG@10: 0.5781, HR@10: 0.6259, MRR: 0.5778
test [full], NDCG@5: 0.7620, HR@5: 0.9415, NDCG@10: 0.7817, HR@10: 0.9999, MRR: 0.7094
test [sampled], NDCG@5: 0.2771, HR@5: 0.3031, NDCG@10: 0.3286, HR@10: 0.4669, MRR: 0.3207
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0776
epoch=32, loss=0.0764
epoch=33, loss=0.0768
epoch=34, loss=0.0759
epoch=35, loss=0.0749
valid [full], NDCG@5: 0.6770, HR@5: 0.8321, NDCG@10: 0.7139, HR@10: 0.9496, MRR: 0.6452
valid [sampled], NDCG@5: 0.5384, HR@5: 0.5512, NDCG@10: 0.5593, HR@10: 0.6165, MRR: 0.5571
test [full], NDCG@5: 0.7277, HR@5: 0.9393, NDCG@10: 0.7463, HR@10: 1.0000, MRR: 0.6650
test [sampled], NDCG@5: 0.2538, HR@5: 0.2716, NDCG@10: 0.2924, HR@10: 0.3947, MRR: 0.2963
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0752
epoch=37, loss=0.0743
epoch=38, loss=0.0742
epoch=39, loss=0.0751
epoch=40, loss=0.0753
valid [full], NDCG@5: 0.6791, HR@5: 0.8317, NDCG@10: 0.7222, HR@10: 0.9709, MRR: 0.6490
valid [sampled], NDCG@5: 0.5473, HR@5: 0.5548, NDCG@10: 0.5641, HR@10: 0.6079, MRR: 0.5666
test [full], NDCG@5: 0.7400, HR@5: 0.9425, NDCG@10: 0.7577, HR@10: 1.0000, MRR: 0.6797
test [sampled], NDCG@5: 0.2778, HR@5: 0.2967, NDCG@10: 0.3108, HR@10: 0.4011, MRR: 0.3182
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0752
epoch=42, loss=0.0758
epoch=43, loss=0.0758
epoch=44, loss=0.0738
epoch=45, loss=0.0744
valid [full], NDCG@5: 0.6904, HR@5: 0.8272, NDCG@10: 0.7300, HR@10: 0.9503, MRR: 0.6659
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5753, NDCG@10: 0.5813, HR@10: 0.6325, MRR: 0.5805
test [full], NDCG@5: 0.7902, HR@5: 0.9343, NDCG@10: 0.8116, HR@10: 1.0000, MRR: 0.7493
test [sampled], NDCG@5: 0.3208, HR@5: 0.3470, NDCG@10: 0.3758, HR@10: 0.5212, MRR: 0.3622
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0722
epoch=47, loss=0.0732
epoch=48, loss=0.0726
epoch=49, loss=0.0723
epoch=50, loss=0.0736
valid [full], NDCG@5: 0.6994, HR@5: 0.8346, NDCG@10: 0.7359, HR@10: 0.9502, MRR: 0.6734
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5716, NDCG@10: 0.5817, HR@10: 0.6472, MRR: 0.5763
test [full], NDCG@5: 0.8079, HR@5: 0.9437, NDCG@10: 0.8254, HR@10: 1.0000, MRR: 0.7673
test [sampled], NDCG@5: 0.3415, HR@5: 0.3694, NDCG@10: 0.3980, HR@10: 0.5480, MRR: 0.3820
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s42/sasrec_last.pth

### timeaware_refine_ml50_do035_b8_s2024

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b8_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024
epoch=1, loss=0.6099
epoch=2, loss=0.2708
epoch=3, loss=0.1978
epoch=4, loss=0.1583
epoch=5, loss=0.1377
valid [full], NDCG@5: 0.7021, HR@5: 0.8905, NDCG@10: 0.7366, HR@10: 0.9919, MRR: 0.6577
valid [sampled], NDCG@5: 0.5478, HR@5: 0.5585, NDCG@10: 0.5607, HR@10: 0.5989, MRR: 0.5657
test [full], NDCG@5: 0.7724, HR@5: 0.9148, NDCG@10: 0.8008, HR@10: 1.0000, MRR: 0.7379
test [sampled], NDCG@5: 0.2150, HR@5: 0.2771, NDCG@10: 0.2735, HR@10: 0.4577, MRR: 0.2478
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/sasrec_best.pth
epoch=6, loss=0.1215
epoch=7, loss=0.1128
epoch=8, loss=0.1073
epoch=9, loss=0.0995
epoch=10, loss=0.0981
valid [full], NDCG@5: 0.7047, HR@5: 0.8713, NDCG@10: 0.7355, HR@10: 0.9704, MRR: 0.6649
valid [sampled], NDCG@5: 0.5418, HR@5: 0.5525, NDCG@10: 0.5596, HR@10: 0.6083, MRR: 0.5624
test [full], NDCG@5: 0.8062, HR@5: 0.9404, NDCG@10: 0.8241, HR@10: 0.9999, MRR: 0.7663
test [sampled], NDCG@5: 0.2274, HR@5: 0.2825, NDCG@10: 0.3037, HR@10: 0.5217, MRR: 0.2688
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0943
epoch=12, loss=0.0916
epoch=13, loss=0.0894
epoch=14, loss=0.0879
epoch=15, loss=0.0874
valid [full], NDCG@5: 0.7071, HR@5: 0.8889, NDCG@10: 0.7324, HR@10: 0.9714, MRR: 0.6609
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5640, NDCG@10: 0.5662, HR@10: 0.6089, MRR: 0.5700
test [full], NDCG@5: 0.7876, HR@5: 0.9523, NDCG@10: 0.8030, HR@10: 1.0000, MRR: 0.7362
test [sampled], NDCG@5: 0.1695, HR@5: 0.2071, NDCG@10: 0.2536, HR@10: 0.4743, MRR: 0.2238
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0841
epoch=17, loss=0.0838
epoch=18, loss=0.0829
epoch=19, loss=0.0826
epoch=20, loss=0.0827
valid [full], NDCG@5: 0.6866, HR@5: 0.8518, NDCG@10: 0.7146, HR@10: 0.9416, MRR: 0.6493
valid [sampled], NDCG@5: 0.5419, HR@5: 0.5478, NDCG@10: 0.5537, HR@10: 0.5846, MRR: 0.5604
test [full], NDCG@5: 0.8038, HR@5: 0.9982, NDCG@10: 0.8044, HR@10: 0.9999, MRR: 0.7379
test [sampled], NDCG@5: 0.1805, HR@5: 0.2211, NDCG@10: 0.2574, HR@10: 0.4640, MRR: 0.2305
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0804
epoch=22, loss=0.0798
epoch=23, loss=0.0792
epoch=24, loss=0.0806
epoch=25, loss=0.0791
valid [full], NDCG@5: 0.6960, HR@5: 0.8641, NDCG@10: 0.7196, HR@10: 0.9410, MRR: 0.6556
valid [sampled], NDCG@5: 0.5462, HR@5: 0.5586, NDCG@10: 0.5595, HR@10: 0.5998, MRR: 0.5630
test [full], NDCG@5: 0.7598, HR@5: 0.9791, NDCG@10: 0.7669, HR@10: 0.9999, MRR: 0.6880
test [sampled], NDCG@5: 0.1598, HR@5: 0.1956, NDCG@10: 0.2302, HR@10: 0.4184, MRR: 0.2105
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0764
epoch=27, loss=0.0765
epoch=28, loss=0.0766
epoch=29, loss=0.0798
epoch=30, loss=0.0761
valid [full], NDCG@5: 0.6775, HR@5: 0.8226, NDCG@10: 0.7175, HR@10: 0.9466, MRR: 0.6522
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5679, NDCG@10: 0.5693, HR@10: 0.6064, MRR: 0.5714
test [full], NDCG@5: 0.7488, HR@5: 0.9483, NDCG@10: 0.7649, HR@10: 1.0000, MRR: 0.6863
test [sampled], NDCG@5: 0.1478, HR@5: 0.1814, NDCG@10: 0.2225, HR@10: 0.4177, MRR: 0.2003
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0766
epoch=32, loss=0.0757
epoch=33, loss=0.0750
epoch=34, loss=0.0764
epoch=35, loss=0.0746
valid [full], NDCG@5: 0.6768, HR@5: 0.8626, NDCG@10: 0.7118, HR@10: 0.9730, MRR: 0.6336
valid [sampled], NDCG@5: 0.5194, HR@5: 0.5318, NDCG@10: 0.5344, HR@10: 0.5787, MRR: 0.5376
test [full], NDCG@5: 0.7868, HR@5: 0.9880, NDCG@10: 0.7909, HR@10: 0.9999, MRR: 0.7204
test [sampled], NDCG@5: 0.1789, HR@5: 0.2246, NDCG@10: 0.2546, HR@10: 0.4624, MRR: 0.2261
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0761
epoch=37, loss=0.0742
epoch=38, loss=0.0737
epoch=39, loss=0.0748
epoch=40, loss=0.0730
valid [full], NDCG@5: 0.7039, HR@5: 0.8695, NDCG@10: 0.7376, HR@10: 0.9752, MRR: 0.6654
valid [sampled], NDCG@5: 0.5416, HR@5: 0.5557, NDCG@10: 0.5643, HR@10: 0.6270, MRR: 0.5624
test [full], NDCG@5: 0.7933, HR@5: 0.9739, NDCG@10: 0.8023, HR@10: 0.9999, MRR: 0.7373
test [sampled], NDCG@5: 0.2547, HR@5: 0.2822, NDCG@10: 0.3002, HR@10: 0.4263, MRR: 0.2976
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/sasrec_best.pth
epoch=41, loss=0.0743
epoch=42, loss=0.0744
epoch=43, loss=0.0744
epoch=44, loss=0.0722
epoch=45, loss=0.0734
valid [full], NDCG@5: 0.6822, HR@5: 0.8370, NDCG@10: 0.7261, HR@10: 0.9759, MRR: 0.6520
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5585, NDCG@10: 0.5637, HR@10: 0.5993, MRR: 0.5689
test [full], NDCG@5: 0.7707, HR@5: 0.9573, NDCG@10: 0.7851, HR@10: 0.9999, MRR: 0.7164
test [sampled], NDCG@5: 0.2547, HR@5: 0.2793, NDCG@10: 0.2955, HR@10: 0.4080, MRR: 0.2956
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0717
epoch=47, loss=0.0733
epoch=48, loss=0.0737
epoch=49, loss=0.0709
epoch=50, loss=0.0737
valid [full], NDCG@5: 0.6864, HR@5: 0.8322, NDCG@10: 0.7308, HR@10: 0.9719, MRR: 0.6595
valid [sampled], NDCG@5: 0.5531, HR@5: 0.5610, NDCG@10: 0.5703, HR@10: 0.6151, MRR: 0.5724
test [full], NDCG@5: 0.7616, HR@5: 0.9356, NDCG@10: 0.7819, HR@10: 0.9999, MRR: 0.7096
test [sampled], NDCG@5: 0.2761, HR@5: 0.3040, NDCG@10: 0.3449, HR@10: 0.5230, MRR: 0.3216
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s2024/sasrec_last.pth

### timeaware_refine_ml50_do035_b8_s7

In [12]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b8_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7
epoch=1, loss=0.5810
epoch=2, loss=0.2715
epoch=3, loss=0.2022
epoch=4, loss=0.1681
epoch=5, loss=0.1452
valid [full], NDCG@5: 0.6743, HR@5: 0.8234, NDCG@10: 0.7235, HR@10: 0.9740, MRR: 0.6495
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5622, NDCG@10: 0.5672, HR@10: 0.5800, MRR: 0.5797
test [full], NDCG@5: 0.6352, HR@5: 0.8429, NDCG@10: 0.6734, HR@10: 0.9623, MRR: 0.5850
test [sampled], NDCG@5: 0.1949, HR@5: 0.2005, NDCG@10: 0.2382, HR@10: 0.3405, MRR: 0.2418
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=6, loss=0.1259
epoch=7, loss=0.1143
epoch=8, loss=0.1080
epoch=9, loss=0.1037
epoch=10, loss=0.0980
valid [full], NDCG@5: 0.6726, HR@5: 0.8102, NDCG@10: 0.7198, HR@10: 0.9579, MRR: 0.6518
valid [sampled], NDCG@5: 0.5645, HR@5: 0.5723, NDCG@10: 0.5735, HR@10: 0.6002, MRR: 0.5784
test [full], NDCG@5: 0.7233, HR@5: 0.9620, NDCG@10: 0.7360, HR@10: 1.0000, MRR: 0.6470
test [sampled], NDCG@5: 0.1002, HR@5: 0.1130, NDCG@10: 0.1777, HR@10: 0.3626, MRR: 0.1665
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0947
epoch=12, loss=0.0926
epoch=13, loss=0.0903
epoch=14, loss=0.0865
epoch=15, loss=0.0870
valid [full], NDCG@5: 0.6880, HR@5: 0.8429, NDCG@10: 0.7234, HR@10: 0.9540, MRR: 0.6562
valid [sampled], NDCG@5: 0.5585, HR@5: 0.5613, NDCG@10: 0.5701, HR@10: 0.5989, MRR: 0.5782
test [full], NDCG@5: 0.7767, HR@5: 0.9848, NDCG@10: 0.7820, HR@10: 1.0000, MRR: 0.7061
test [sampled], NDCG@5: 0.1442, HR@5: 0.1543, NDCG@10: 0.2270, HR@10: 0.4221, MRR: 0.2124
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0859
epoch=17, loss=0.0830
epoch=18, loss=0.0820
epoch=19, loss=0.0808
epoch=20, loss=0.0813
valid [full], NDCG@5: 0.6807, HR@5: 0.8006, NDCG@10: 0.7312, HR@10: 0.9549, MRR: 0.6661
valid [sampled], NDCG@5: 0.5660, HR@5: 0.5791, NDCG@10: 0.5872, HR@10: 0.6454, MRR: 0.5836
test [full], NDCG@5: 0.8288, HR@5: 0.9997, NDCG@10: 0.8289, HR@10: 1.0000, MRR: 0.7685
test [sampled], NDCG@5: 0.1945, HR@5: 0.2300, NDCG@10: 0.2903, HR@10: 0.5344, MRR: 0.2539
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=21, loss=0.0819
epoch=22, loss=0.0787
epoch=23, loss=0.0799
epoch=24, loss=0.0787
epoch=25, loss=0.0767
valid [full], NDCG@5: 0.7088, HR@5: 0.8501, NDCG@10: 0.7433, HR@10: 0.9571, MRR: 0.6798
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5815, NDCG@10: 0.5896, HR@10: 0.6525, MRR: 0.5862
test [full], NDCG@5: 0.8514, HR@5: 0.9995, NDCG@10: 0.8516, HR@10: 1.0000, MRR: 0.7997
test [sampled], NDCG@5: 0.3657, HR@5: 0.3932, NDCG@10: 0.4382, HR@10: 0.6230, MRR: 0.4112
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=26, loss=0.0779
epoch=27, loss=0.0768
epoch=28, loss=0.0768
epoch=29, loss=0.0771
epoch=30, loss=0.0740
valid [full], NDCG@5: 0.7095, HR@5: 0.8402, NDCG@10: 0.7479, HR@10: 0.9585, MRR: 0.6855
valid [sampled], NDCG@5: 0.5607, HR@5: 0.5742, NDCG@10: 0.5882, HR@10: 0.6600, MRR: 0.5817
test [full], NDCG@5: 0.9017, HR@5: 0.9989, NDCG@10: 0.9021, HR@10: 1.0000, MRR: 0.8685
test [sampled], NDCG@5: 0.3797, HR@5: 0.4475, NDCG@10: 0.4386, HR@10: 0.6292, MRR: 0.4055
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=31, loss=0.0761
epoch=32, loss=0.0750
epoch=33, loss=0.0751
epoch=34, loss=0.0743
epoch=35, loss=0.0757
valid [full], NDCG@5: 0.6900, HR@5: 0.8218, NDCG@10: 0.7329, HR@10: 0.9581, MRR: 0.6673
valid [sampled], NDCG@5: 0.5598, HR@5: 0.5743, NDCG@10: 0.5832, HR@10: 0.6470, MRR: 0.5776
test [full], NDCG@5: 0.7991, HR@5: 0.9989, NDCG@10: 0.7995, HR@10: 1.0000, MRR: 0.7314
test [sampled], NDCG@5: 0.3348, HR@5: 0.3535, NDCG@10: 0.3663, HR@10: 0.4536, MRR: 0.3751
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0737
epoch=37, loss=0.0750
epoch=38, loss=0.0741
epoch=39, loss=0.0743
epoch=40, loss=0.0741
valid [full], NDCG@5: 0.6932, HR@5: 0.8424, NDCG@10: 0.7299, HR@10: 0.9606, MRR: 0.6620
valid [sampled], NDCG@5: 0.5375, HR@5: 0.5435, NDCG@10: 0.5610, HR@10: 0.6192, MRR: 0.5609
test [full], NDCG@5: 0.8419, HR@5: 0.9997, NDCG@10: 0.8420, HR@10: 1.0000, MRR: 0.7876
test [sampled], NDCG@5: 0.3709, HR@5: 0.3801, NDCG@10: 0.4291, HR@10: 0.5674, MRR: 0.4189
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0765
epoch=42, loss=0.0726
epoch=43, loss=0.0738
epoch=44, loss=0.0725
epoch=45, loss=0.0730
valid [full], NDCG@5: 0.7045, HR@5: 0.8489, NDCG@10: 0.7401, HR@10: 0.9611, MRR: 0.6740
valid [sampled], NDCG@5: 0.5447, HR@5: 0.5599, NDCG@10: 0.5745, HR@10: 0.6537, MRR: 0.5664
test [full], NDCG@5: 0.8413, HR@5: 0.9999, NDCG@10: 0.8413, HR@10: 1.0000, MRR: 0.7864
test [sampled], NDCG@5: 0.3470, HR@5: 0.3643, NDCG@10: 0.4043, HR@10: 0.5472, MRR: 0.3934
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0721
epoch=47, loss=0.0724
epoch=48, loss=0.0725
epoch=49, loss=0.0726
epoch=50, loss=0.0724
valid [full], NDCG@5: 0.7188, HR@5: 0.8456, NDCG@10: 0.7557, HR@10: 0.9612, MRR: 0.6954
valid [sampled], NDCG@5: 0.5964, HR@5: 0.6122, NDCG@10: 0.6201, HR@10: 0.6864, MRR: 0.6131
test [full], NDCG@5: 0.8202, HR@5: 0.9997, NDCG@10: 0.8203, HR@10: 1.0000, MRR: 0.7600
test [sampled], NDCG@5: 0.3076, HR@5: 0.3223, NDCG@10: 0.3551, HR@10: 0.4734, MRR: 0.3551
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b8_s7/sasrec_last.pth

### timeaware_refine_ml50_do035_b9_s42

In [13]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b9_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42
epoch=1, loss=0.5811
epoch=2, loss=0.2632
epoch=3, loss=0.1985
epoch=4, loss=0.1625
epoch=5, loss=0.1395
valid [full], NDCG@5: 0.6291, HR@5: 0.7182, NDCG@10: 0.6887, HR@10: 0.9047, MRR: 0.6329
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5632, NDCG@10: 0.5672, HR@10: 0.5920, MRR: 0.5722
test [full], NDCG@5: 0.5805, HR@5: 0.7521, NDCG@10: 0.6231, HR@10: 0.8896, MRR: 0.5485
test [sampled], NDCG@5: 0.2080, HR@5: 0.2099, NDCG@10: 0.2296, HR@10: 0.2808, MRR: 0.2495
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=6, loss=0.1235
epoch=7, loss=0.1146
epoch=8, loss=0.1070
epoch=9, loss=0.1016
epoch=10, loss=0.0996
valid [full], NDCG@5: 0.6432, HR@5: 0.7484, NDCG@10: 0.7146, HR@10: 0.9681, MRR: 0.6415
valid [sampled], NDCG@5: 0.5557, HR@5: 0.5696, NDCG@10: 0.5699, HR@10: 0.6135, MRR: 0.5696
test [full], NDCG@5: 0.7065, HR@5: 0.9387, NDCG@10: 0.7274, HR@10: 0.9999, MRR: 0.6363
test [sampled], NDCG@5: 0.1790, HR@5: 0.1952, NDCG@10: 0.2407, HR@10: 0.3938, MRR: 0.2338
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=11, loss=0.0969
epoch=12, loss=0.0938
epoch=13, loss=0.0907
epoch=14, loss=0.0900
epoch=15, loss=0.0886
valid [full], NDCG@5: 0.6716, HR@5: 0.8148, NDCG@10: 0.7217, HR@10: 0.9703, MRR: 0.6480
valid [sampled], NDCG@5: 0.5478, HR@5: 0.5602, NDCG@10: 0.5665, HR@10: 0.6187, MRR: 0.5658
test [full], NDCG@5: 0.7073, HR@5: 0.9497, NDCG@10: 0.7246, HR@10: 1.0000, MRR: 0.6312
test [sampled], NDCG@5: 0.1540, HR@5: 0.1785, NDCG@10: 0.2320, HR@10: 0.4273, MRR: 0.2122
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=16, loss=0.0861
epoch=17, loss=0.0828
epoch=18, loss=0.0831
epoch=19, loss=0.0824
epoch=20, loss=0.0829
valid [full], NDCG@5: 0.6853, HR@5: 0.8272, NDCG@10: 0.7323, HR@10: 0.9707, MRR: 0.6622
valid [sampled], NDCG@5: 0.5658, HR@5: 0.5766, NDCG@10: 0.5794, HR@10: 0.6186, MRR: 0.5819
test [full], NDCG@5: 0.7384, HR@5: 0.9594, NDCG@10: 0.7521, HR@10: 1.0000, MRR: 0.6678
test [sampled], NDCG@5: 0.1978, HR@5: 0.2219, NDCG@10: 0.2708, HR@10: 0.4554, MRR: 0.2517
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=21, loss=0.0799
epoch=22, loss=0.0796
epoch=23, loss=0.0800
epoch=24, loss=0.0787
epoch=25, loss=0.0799
valid [full], NDCG@5: 0.6599, HR@5: 0.7751, NDCG@10: 0.7236, HR@10: 0.9696, MRR: 0.6522
valid [sampled], NDCG@5: 0.5551, HR@5: 0.5661, NDCG@10: 0.5702, HR@10: 0.6127, MRR: 0.5705
test [full], NDCG@5: 0.7386, HR@5: 0.9540, NDCG@10: 0.7542, HR@10: 1.0000, MRR: 0.6727
test [sampled], NDCG@5: 0.1879, HR@5: 0.2164, NDCG@10: 0.2436, HR@10: 0.3917, MRR: 0.2374
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0776
epoch=27, loss=0.0802
epoch=28, loss=0.0772
epoch=29, loss=0.0784
epoch=30, loss=0.0777
valid [full], NDCG@5: 0.6704, HR@5: 0.7905, NDCG@10: 0.7285, HR@10: 0.9710, MRR: 0.6582
valid [sampled], NDCG@5: 0.5637, HR@5: 0.5736, NDCG@10: 0.5776, HR@10: 0.6164, MRR: 0.5792
test [full], NDCG@5: 0.7488, HR@5: 0.9640, NDCG@10: 0.7614, HR@10: 1.0000, MRR: 0.6833
test [sampled], NDCG@5: 0.2440, HR@5: 0.2691, NDCG@10: 0.2837, HR@10: 0.3951, MRR: 0.2869
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0777
epoch=32, loss=0.0763
epoch=33, loss=0.0768
epoch=34, loss=0.0758
epoch=35, loss=0.0748
valid [full], NDCG@5: 0.6582, HR@5: 0.7837, NDCG@10: 0.7127, HR@10: 0.9525, MRR: 0.6442
valid [sampled], NDCG@5: 0.5530, HR@5: 0.5658, NDCG@10: 0.5705, HR@10: 0.6203, MRR: 0.5685
test [full], NDCG@5: 0.7403, HR@5: 0.9477, NDCG@10: 0.7566, HR@10: 1.0000, MRR: 0.6767
test [sampled], NDCG@5: 0.1815, HR@5: 0.2139, NDCG@10: 0.2380, HR@10: 0.3930, MRR: 0.2297
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0753
epoch=37, loss=0.0741
epoch=38, loss=0.0745
epoch=39, loss=0.0750
epoch=40, loss=0.0753
valid [full], NDCG@5: 0.6680, HR@5: 0.7903, NDCG@10: 0.7254, HR@10: 0.9720, MRR: 0.6538
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5705, NDCG@10: 0.5797, HR@10: 0.6214, MRR: 0.5809
test [full], NDCG@5: 0.7356, HR@5: 0.9588, NDCG@10: 0.7485, HR@10: 1.0000, MRR: 0.6675
test [sampled], NDCG@5: 0.1991, HR@5: 0.2267, NDCG@10: 0.2434, HR@10: 0.3660, MRR: 0.2436
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0751
epoch=42, loss=0.0758
epoch=43, loss=0.0759
epoch=44, loss=0.0738
epoch=45, loss=0.0745
valid [full], NDCG@5: 0.6665, HR@5: 0.7788, NDCG@10: 0.7237, HR@10: 0.9540, MRR: 0.6579
valid [sampled], NDCG@5: 0.5683, HR@5: 0.5807, NDCG@10: 0.5810, HR@10: 0.6199, MRR: 0.5819
test [full], NDCG@5: 0.7943, HR@5: 0.9423, NDCG@10: 0.8129, HR@10: 1.0000, MRR: 0.7507
test [sampled], NDCG@5: 0.2576, HR@5: 0.2998, NDCG@10: 0.3285, HR@10: 0.5228, MRR: 0.3008
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0721
epoch=47, loss=0.0727
epoch=48, loss=0.0725
epoch=49, loss=0.0724
epoch=50, loss=0.0734
valid [full], NDCG@5: 0.6635, HR@5: 0.7655, NDCG@10: 0.7301, HR@10: 0.9712, MRR: 0.6604
valid [sampled], NDCG@5: 0.5622, HR@5: 0.5737, NDCG@10: 0.5793, HR@10: 0.6269, MRR: 0.5774
test [full], NDCG@5: 0.8046, HR@5: 0.9679, NDCG@10: 0.8151, HR@10: 1.0000, MRR: 0.7525
test [sampled], NDCG@5: 0.2461, HR@5: 0.2969, NDCG@10: 0.3270, HR@10: 0.5508, MRR: 0.2901
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s42/sasrec_last.pth

### timeaware_refine_ml50_do035_b9_s2024

In [14]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b9_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024
epoch=1, loss=0.6064
epoch=2, loss=0.2697
epoch=3, loss=0.1967
epoch=4, loss=0.1575
epoch=5, loss=0.1370
valid [full], NDCG@5: 0.7001, HR@5: 0.8924, NDCG@10: 0.7348, HR@10: 0.9924, MRR: 0.6552
valid [sampled], NDCG@5: 0.5457, HR@5: 0.5543, NDCG@10: 0.5581, HR@10: 0.5935, MRR: 0.5643
test [full], NDCG@5: 0.7559, HR@5: 0.8925, NDCG@10: 0.7916, HR@10: 1.0000, MRR: 0.7266
test [sampled], NDCG@5: 0.2105, HR@5: 0.2729, NDCG@10: 0.2679, HR@10: 0.4498, MRR: 0.2422
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1209
epoch=7, loss=0.1125
epoch=8, loss=0.1073
epoch=9, loss=0.0995
epoch=10, loss=0.0979
valid [full], NDCG@5: 0.6709, HR@5: 0.8137, NDCG@10: 0.7223, HR@10: 0.9703, MRR: 0.6495
valid [sampled], NDCG@5: 0.5434, HR@5: 0.5535, NDCG@10: 0.5560, HR@10: 0.5928, MRR: 0.5597
test [full], NDCG@5: 0.8123, HR@5: 0.9269, NDCG@10: 0.8344, HR@10: 0.9999, MRR: 0.7812
test [sampled], NDCG@5: 0.1551, HR@5: 0.2364, NDCG@10: 0.2431, HR@10: 0.5101, MRR: 0.1931
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0944
epoch=12, loss=0.0917
epoch=13, loss=0.0893
epoch=14, loss=0.0881
epoch=15, loss=0.0875
valid [full], NDCG@5: 0.6788, HR@5: 0.8415, NDCG@10: 0.7178, HR@10: 0.9651, MRR: 0.6459
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5583, NDCG@10: 0.5605, HR@10: 0.5886, MRR: 0.5674
test [full], NDCG@5: 0.7798, HR@5: 0.9336, NDCG@10: 0.8007, HR@10: 1.0000, MRR: 0.7348
test [sampled], NDCG@5: 0.1720, HR@5: 0.2102, NDCG@10: 0.2569, HR@10: 0.4799, MRR: 0.2240
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0839
epoch=17, loss=0.0840
epoch=18, loss=0.0830
epoch=19, loss=0.0829
epoch=20, loss=0.0828
valid [full], NDCG@5: 0.6865, HR@5: 0.8453, NDCG@10: 0.7181, HR@10: 0.9462, MRR: 0.6528
valid [sampled], NDCG@5: 0.5510, HR@5: 0.5559, NDCG@10: 0.5611, HR@10: 0.5875, MRR: 0.5689
test [full], NDCG@5: 0.7700, HR@5: 0.9474, NDCG@10: 0.7872, HR@10: 0.9999, MRR: 0.7163
test [sampled], NDCG@5: 0.1858, HR@5: 0.2152, NDCG@10: 0.2583, HR@10: 0.4458, MRR: 0.2376
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0801
epoch=22, loss=0.0798
epoch=23, loss=0.0790
epoch=24, loss=0.0803
epoch=25, loss=0.0791
valid [full], NDCG@5: 0.6910, HR@5: 0.8548, NDCG@10: 0.7251, HR@10: 0.9645, MRR: 0.6544
valid [sampled], NDCG@5: 0.5430, HR@5: 0.5560, NDCG@10: 0.5567, HR@10: 0.5983, MRR: 0.5601
test [full], NDCG@5: 0.7455, HR@5: 0.9355, NDCG@10: 0.7657, HR@10: 0.9999, MRR: 0.6881
test [sampled], NDCG@5: 0.1672, HR@5: 0.2053, NDCG@10: 0.2389, HR@10: 0.4318, MRR: 0.2157
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0765
epoch=27, loss=0.0764
epoch=28, loss=0.0764
epoch=29, loss=0.0798
epoch=30, loss=0.0764
valid [full], NDCG@5: 0.6886, HR@5: 0.8539, NDCG@10: 0.7188, HR@10: 0.9499, MRR: 0.6518
valid [sampled], NDCG@5: 0.5409, HR@5: 0.5520, NDCG@10: 0.5549, HR@10: 0.5958, MRR: 0.5584
test [full], NDCG@5: 0.7470, HR@5: 0.9382, NDCG@10: 0.7664, HR@10: 1.0000, MRR: 0.6885
test [sampled], NDCG@5: 0.1541, HR@5: 0.1877, NDCG@10: 0.2275, HR@10: 0.4199, MRR: 0.2061
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0767
epoch=32, loss=0.0754
epoch=33, loss=0.0748
epoch=34, loss=0.0762
epoch=35, loss=0.0745
valid [full], NDCG@5: 0.6806, HR@5: 0.8527, NDCG@10: 0.7188, HR@10: 0.9733, MRR: 0.6421
valid [sampled], NDCG@5: 0.5208, HR@5: 0.5338, NDCG@10: 0.5388, HR@10: 0.5908, MRR: 0.5407
test [full], NDCG@5: 0.7609, HR@5: 0.9548, NDCG@10: 0.7760, HR@10: 0.9999, MRR: 0.7004
test [sampled], NDCG@5: 0.1738, HR@5: 0.2121, NDCG@10: 0.2486, HR@10: 0.4479, MRR: 0.2238
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0761
epoch=37, loss=0.0743
epoch=38, loss=0.0735
epoch=39, loss=0.0745
epoch=40, loss=0.0729
valid [full], NDCG@5: 0.7057, HR@5: 0.8692, NDCG@10: 0.7387, HR@10: 0.9736, MRR: 0.6672
valid [sampled], NDCG@5: 0.5404, HR@5: 0.5536, NDCG@10: 0.5660, HR@10: 0.6346, MRR: 0.5628
test [full], NDCG@5: 0.7895, HR@5: 0.9495, NDCG@10: 0.8052, HR@10: 0.9999, MRR: 0.7395
test [sampled], NDCG@5: 0.2554, HR@5: 0.2838, NDCG@10: 0.3154, HR@10: 0.4747, MRR: 0.3014
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=41, loss=0.0740
epoch=42, loss=0.0746
epoch=43, loss=0.0742
epoch=44, loss=0.0724
epoch=45, loss=0.0730
valid [full], NDCG@5: 0.6761, HR@5: 0.8310, NDCG@10: 0.7170, HR@10: 0.9584, MRR: 0.6460
valid [sampled], NDCG@5: 0.5371, HR@5: 0.5448, NDCG@10: 0.5512, HR@10: 0.5898, MRR: 0.5566
test [full], NDCG@5: 0.7535, HR@5: 0.9496, NDCG@10: 0.7700, HR@10: 0.9999, MRR: 0.6944
test [sampled], NDCG@5: 0.2704, HR@5: 0.2943, NDCG@10: 0.3131, HR@10: 0.4297, MRR: 0.3127
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0716
epoch=47, loss=0.0731
epoch=48, loss=0.0739
epoch=49, loss=0.0709
epoch=50, loss=0.0736
valid [full], NDCG@5: 0.6792, HR@5: 0.8361, NDCG@10: 0.7238, HR@10: 0.9746, MRR: 0.6484
valid [sampled], NDCG@5: 0.5231, HR@5: 0.5299, NDCG@10: 0.5394, HR@10: 0.5821, MRR: 0.5454
test [full], NDCG@5: 0.7749, HR@5: 0.9346, NDCG@10: 0.7952, HR@10: 0.9999, MRR: 0.7272
test [sampled], NDCG@5: 0.3257, HR@5: 0.3480, NDCG@10: 0.3879, HR@10: 0.5465, MRR: 0.3694
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s2024/sasrec_last.pth

### timeaware_refine_ml50_do035_b9_s7

In [15]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b9_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7
epoch=1, loss=0.5822
epoch=2, loss=0.2708
epoch=3, loss=0.2024
epoch=4, loss=0.1677
epoch=5, loss=0.1449
valid [full], NDCG@5: 0.6688, HR@5: 0.8131, NDCG@10: 0.7220, HR@10: 0.9727, MRR: 0.6481
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5635, NDCG@10: 0.5691, HR@10: 0.5833, MRR: 0.5807
test [full], NDCG@5: 0.6522, HR@5: 0.8841, NDCG@10: 0.6811, HR@10: 0.9731, MRR: 0.5887
test [sampled], NDCG@5: 0.1896, HR@5: 0.1951, NDCG@10: 0.2325, HR@10: 0.3341, MRR: 0.2387
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=6, loss=0.1262
epoch=7, loss=0.1148
epoch=8, loss=0.1084
epoch=9, loss=0.1038
epoch=10, loss=0.0981
valid [full], NDCG@5: 0.6648, HR@5: 0.7954, NDCG@10: 0.7107, HR@10: 0.9351, MRR: 0.6482
valid [sampled], NDCG@5: 0.5602, HR@5: 0.5633, NDCG@10: 0.5662, HR@10: 0.5824, MRR: 0.5754
test [full], NDCG@5: 0.7454, HR@5: 0.9959, NDCG@10: 0.7468, HR@10: 1.0000, MRR: 0.6605
test [sampled], NDCG@5: 0.1159, HR@5: 0.1264, NDCG@10: 0.1908, HR@10: 0.3681, MRR: 0.1824
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0956
epoch=12, loss=0.0928
epoch=13, loss=0.0905
epoch=14, loss=0.0866
epoch=15, loss=0.0873
valid [full], NDCG@5: 0.6823, HR@5: 0.8288, NDCG@10: 0.7227, HR@10: 0.9542, MRR: 0.6552
valid [sampled], NDCG@5: 0.5578, HR@5: 0.5599, NDCG@10: 0.5688, HR@10: 0.5958, MRR: 0.5777
test [full], NDCG@5: 0.7855, HR@5: 0.9946, NDCG@10: 0.7874, HR@10: 1.0000, MRR: 0.7132
test [sampled], NDCG@5: 0.1611, HR@5: 0.1729, NDCG@10: 0.2450, HR@10: 0.4442, MRR: 0.2282
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=16, loss=0.0860
epoch=17, loss=0.0830
epoch=18, loss=0.0820
epoch=19, loss=0.0809
epoch=20, loss=0.0812
valid [full], NDCG@5: 0.6800, HR@5: 0.8155, NDCG@10: 0.7241, HR@10: 0.9542, MRR: 0.6576
valid [sampled], NDCG@5: 0.5630, HR@5: 0.5741, NDCG@10: 0.5787, HR@10: 0.6228, MRR: 0.5797
test [full], NDCG@5: 0.8981, HR@5: 0.9999, NDCG@10: 0.8981, HR@10: 1.0000, MRR: 0.8625
test [sampled], NDCG@5: 0.2242, HR@5: 0.3046, NDCG@10: 0.3241, HR@10: 0.6152, MRR: 0.2655
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=21, loss=0.0815
epoch=22, loss=0.0783
epoch=23, loss=0.0798
epoch=24, loss=0.0785
epoch=25, loss=0.0766
valid [full], NDCG@5: 0.6952, HR@5: 0.8282, NDCG@10: 0.7375, HR@10: 0.9571, MRR: 0.6726
valid [sampled], NDCG@5: 0.5665, HR@5: 0.5801, NDCG@10: 0.5844, HR@10: 0.6362, MRR: 0.5839
test [full], NDCG@5: 0.9185, HR@5: 0.9988, NDCG@10: 0.9189, HR@10: 1.0000, MRR: 0.8909
test [sampled], NDCG@5: 0.3284, HR@5: 0.4190, NDCG@10: 0.4201, HR@10: 0.7018, MRR: 0.3572
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=26, loss=0.0777
epoch=27, loss=0.0765
epoch=28, loss=0.0767
epoch=29, loss=0.0767
epoch=30, loss=0.0738
valid [full], NDCG@5: 0.6964, HR@5: 0.8187, NDCG@10: 0.7427, HR@10: 0.9585, MRR: 0.6789
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5716, NDCG@10: 0.5806, HR@10: 0.6384, MRR: 0.5789
test [full], NDCG@5: 0.9342, HR@5: 0.9996, NDCG@10: 0.9344, HR@10: 1.0000, MRR: 0.9116
test [sampled], NDCG@5: 0.4046, HR@5: 0.4794, NDCG@10: 0.4789, HR@10: 0.7088, MRR: 0.4303
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=31, loss=0.0760
epoch=32, loss=0.0750
epoch=33, loss=0.0752
epoch=34, loss=0.0743
epoch=35, loss=0.0758
valid [full], NDCG@5: 0.6883, HR@5: 0.8259, NDCG@10: 0.7299, HR@10: 0.9562, MRR: 0.6636
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5716, NDCG@10: 0.5768, HR@10: 0.6279, MRR: 0.5763
test [full], NDCG@5: 0.8305, HR@5: 0.9991, NDCG@10: 0.8308, HR@10: 1.0000, MRR: 0.7735
test [sampled], NDCG@5: 0.4177, HR@5: 0.4332, NDCG@10: 0.4538, HR@10: 0.5479, MRR: 0.4553
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0740
epoch=37, loss=0.0744
epoch=38, loss=0.0739
epoch=39, loss=0.0744
epoch=40, loss=0.0741
valid [full], NDCG@5: 0.7088, HR@5: 0.8594, NDCG@10: 0.7398, HR@10: 0.9593, MRR: 0.6743
valid [sampled], NDCG@5: 0.5431, HR@5: 0.5574, NDCG@10: 0.5748, HR@10: 0.6579, MRR: 0.5658
test [full], NDCG@5: 0.8620, HR@5: 0.9997, NDCG@10: 0.8621, HR@10: 1.0000, MRR: 0.8139
test [sampled], NDCG@5: 0.4279, HR@5: 0.4445, NDCG@10: 0.4889, HR@10: 0.6399, MRR: 0.4707
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0767
epoch=42, loss=0.0725
epoch=43, loss=0.0736
epoch=44, loss=0.0722
epoch=45, loss=0.0731
valid [full], NDCG@5: 0.7170, HR@5: 0.8646, NDCG@10: 0.7477, HR@10: 0.9613, MRR: 0.6830
valid [sampled], NDCG@5: 0.5490, HR@5: 0.5650, NDCG@10: 0.5832, HR@10: 0.6730, MRR: 0.5723
test [full], NDCG@5: 0.8216, HR@5: 0.9999, NDCG@10: 0.8216, HR@10: 1.0000, MRR: 0.7612
test [sampled], NDCG@5: 0.3777, HR@5: 0.3938, NDCG@10: 0.4162, HR@10: 0.5162, MRR: 0.4184
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=46, loss=0.0721
epoch=47, loss=0.0725
epoch=48, loss=0.0725
epoch=49, loss=0.0727
epoch=50, loss=0.0725
valid [full], NDCG@5: 0.7103, HR@5: 0.8254, NDCG@10: 0.7541, HR@10: 0.9607, MRR: 0.6935
valid [sampled], NDCG@5: 0.5936, HR@5: 0.6082, NDCG@10: 0.6175, HR@10: 0.6834, MRR: 0.6109
test [full], NDCG@5: 0.8357, HR@5: 0.9997, NDCG@10: 0.8358, HR@10: 0.9999, MRR: 0.7823
test [sampled], NDCG@5: 0.4377, HR@5: 0.4518, NDCG@10: 0.4762, HR@10: 0.5730, MRR: 0.4735
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10/timeaware_refine_ml50_do035_b9_s7/sasrec_last.pth

## Train time-aware runs for `NDCG@5`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_refine_ml50_do035_b8_s42

In [16]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b8_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42
epoch=1, loss=0.5829
epoch=2, loss=0.2632
epoch=3, loss=0.1991
epoch=4, loss=0.1635
epoch=5, loss=0.1403
valid [full], NDCG@5: 0.6186, HR@5: 0.6949, NDCG@10: 0.6822, HR@10: 0.8911, MRR: 0.6297
valid [sampled], NDCG@5: 0.5559, HR@5: 0.5598, NDCG@10: 0.5643, HR@10: 0.5868, MRR: 0.5701
test [full], NDCG@5: 0.5853, HR@5: 0.7508, NDCG@10: 0.6262, HR@10: 0.8816, MRR: 0.5557
test [sampled], NDCG@5: 0.2091, HR@5: 0.2126, NDCG@10: 0.2428, HR@10: 0.3219, MRR: 0.2514
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=6, loss=0.1243
epoch=7, loss=0.1149
epoch=8, loss=0.1071
epoch=9, loss=0.1018
epoch=10, loss=0.0998
valid [full], NDCG@5: 0.6446, HR@5: 0.7495, NDCG@10: 0.7148, HR@10: 0.9682, MRR: 0.6417
valid [sampled], NDCG@5: 0.5537, HR@5: 0.5680, NDCG@10: 0.5694, HR@10: 0.6170, MRR: 0.5682
test [full], NDCG@5: 0.6912, HR@5: 0.9186, NDCG@10: 0.7181, HR@10: 0.9999, MRR: 0.6248
test [sampled], NDCG@5: 0.1718, HR@5: 0.1864, NDCG@10: 0.2263, HR@10: 0.3620, MRR: 0.2261
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=11, loss=0.0970
epoch=12, loss=0.0937
epoch=13, loss=0.0909
epoch=14, loss=0.0899
epoch=15, loss=0.0887
valid [full], NDCG@5: 0.6778, HR@5: 0.8228, NDCG@10: 0.7262, HR@10: 0.9707, MRR: 0.6532
valid [sampled], NDCG@5: 0.5514, HR@5: 0.5644, NDCG@10: 0.5709, HR@10: 0.6256, MRR: 0.5697
test [full], NDCG@5: 0.7943, HR@5: 0.9552, NDCG@10: 0.8098, HR@10: 1.0000, MRR: 0.7459
test [sampled], NDCG@5: 0.2110, HR@5: 0.2795, NDCG@10: 0.2945, HR@10: 0.5402, MRR: 0.2506
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=16, loss=0.0862
epoch=17, loss=0.0829
epoch=18, loss=0.0832
epoch=19, loss=0.0825
epoch=20, loss=0.0829
valid [full], NDCG@5: 0.6884, HR@5: 0.8326, NDCG@10: 0.7338, HR@10: 0.9710, MRR: 0.6637
valid [sampled], NDCG@5: 0.5652, HR@5: 0.5765, NDCG@10: 0.5808, HR@10: 0.6248, MRR: 0.5818
test [full], NDCG@5: 0.7169, HR@5: 0.9421, NDCG@10: 0.7363, HR@10: 1.0000, MRR: 0.6478
test [sampled], NDCG@5: 0.1288, HR@5: 0.1645, NDCG@10: 0.2147, HR@10: 0.4379, MRR: 0.1850
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=21, loss=0.0799
epoch=22, loss=0.0799
epoch=23, loss=0.0803
epoch=24, loss=0.0786
epoch=25, loss=0.0798
valid [full], NDCG@5: 0.6816, HR@5: 0.8238, NDCG@10: 0.7207, HR@10: 0.9481, MRR: 0.6561
valid [sampled], NDCG@5: 0.5558, HR@5: 0.5667, NDCG@10: 0.5717, HR@10: 0.6161, MRR: 0.5720
test [full], NDCG@5: 0.7712, HR@5: 0.9605, NDCG@10: 0.7841, HR@10: 1.0000, MRR: 0.7115
test [sampled], NDCG@5: 0.1818, HR@5: 0.2177, NDCG@10: 0.2633, HR@10: 0.4748, MRR: 0.2345
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0776
epoch=27, loss=0.0801
epoch=28, loss=0.0774
epoch=29, loss=0.0786
epoch=30, loss=0.0777
valid [full], NDCG@5: 0.6871, HR@5: 0.8241, NDCG@10: 0.7278, HR@10: 0.9542, MRR: 0.6627
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5710, NDCG@10: 0.5781, HR@10: 0.6259, MRR: 0.5778
test [full], NDCG@5: 0.7620, HR@5: 0.9415, NDCG@10: 0.7817, HR@10: 0.9999, MRR: 0.7094
test [sampled], NDCG@5: 0.2771, HR@5: 0.3031, NDCG@10: 0.3286, HR@10: 0.4669, MRR: 0.3207
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0776
epoch=32, loss=0.0764
epoch=33, loss=0.0768
epoch=34, loss=0.0759
epoch=35, loss=0.0749
valid [full], NDCG@5: 0.6770, HR@5: 0.8321, NDCG@10: 0.7139, HR@10: 0.9496, MRR: 0.6452
valid [sampled], NDCG@5: 0.5384, HR@5: 0.5512, NDCG@10: 0.5593, HR@10: 0.6165, MRR: 0.5571
test [full], NDCG@5: 0.7277, HR@5: 0.9393, NDCG@10: 0.7463, HR@10: 1.0000, MRR: 0.6650
test [sampled], NDCG@5: 0.2538, HR@5: 0.2716, NDCG@10: 0.2924, HR@10: 0.3947, MRR: 0.2963
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0752
epoch=37, loss=0.0743
epoch=38, loss=0.0742
epoch=39, loss=0.0751
epoch=40, loss=0.0753
valid [full], NDCG@5: 0.6791, HR@5: 0.8317, NDCG@10: 0.7222, HR@10: 0.9709, MRR: 0.6490
valid [sampled], NDCG@5: 0.5473, HR@5: 0.5548, NDCG@10: 0.5641, HR@10: 0.6079, MRR: 0.5666
test [full], NDCG@5: 0.7400, HR@5: 0.9425, NDCG@10: 0.7577, HR@10: 1.0000, MRR: 0.6797
test [sampled], NDCG@5: 0.2778, HR@5: 0.2967, NDCG@10: 0.3108, HR@10: 0.4011, MRR: 0.3182
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0752
epoch=42, loss=0.0758
epoch=43, loss=0.0758
epoch=44, loss=0.0738
epoch=45, loss=0.0744
valid [full], NDCG@5: 0.6904, HR@5: 0.8272, NDCG@10: 0.7300, HR@10: 0.9503, MRR: 0.6659
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5753, NDCG@10: 0.5813, HR@10: 0.6325, MRR: 0.5805
test [full], NDCG@5: 0.7902, HR@5: 0.9343, NDCG@10: 0.8116, HR@10: 1.0000, MRR: 0.7493
test [sampled], NDCG@5: 0.3208, HR@5: 0.3470, NDCG@10: 0.3758, HR@10: 0.5212, MRR: 0.3622
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
epoch=46, loss=0.0722
epoch=47, loss=0.0732
epoch=48, loss=0.0726
epoch=49, loss=0.0723
epoch=50, loss=0.0736
valid [full], NDCG@5: 0.6994, HR@5: 0.8346, NDCG@10: 0.7359, HR@10: 0.9502, MRR: 0.6734
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5716, NDCG@10: 0.5817, HR@10: 0.6472, MRR: 0.5763
test [full], NDCG@5: 0.8079, HR@5: 0.9437, NDCG@10: 0.8254, HR@10: 1.0000, MRR: 0.7673
test [sampled], NDCG@5: 0.3415, HR@5: 0.3694, NDCG@10: 0.3980, HR@10: 0.5480, MRR: 0.3820
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s42/sasrec_last.pth

### timeaware_refine_ml50_do035_b8_s2024

In [17]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b8_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024
epoch=1, loss=0.6099
epoch=2, loss=0.2708
epoch=3, loss=0.1978
epoch=4, loss=0.1583
epoch=5, loss=0.1377
valid [full], NDCG@5: 0.7021, HR@5: 0.8905, NDCG@10: 0.7366, HR@10: 0.9919, MRR: 0.6577
valid [sampled], NDCG@5: 0.5478, HR@5: 0.5585, NDCG@10: 0.5607, HR@10: 0.5989, MRR: 0.5657
test [full], NDCG@5: 0.7724, HR@5: 0.9148, NDCG@10: 0.8008, HR@10: 1.0000, MRR: 0.7379
test [sampled], NDCG@5: 0.2150, HR@5: 0.2771, NDCG@10: 0.2735, HR@10: 0.4577, MRR: 0.2478
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/sasrec_best.pth
epoch=6, loss=0.1215
epoch=7, loss=0.1128
epoch=8, loss=0.1073
epoch=9, loss=0.0995
epoch=10, loss=0.0981
valid [full], NDCG@5: 0.7047, HR@5: 0.8713, NDCG@10: 0.7355, HR@10: 0.9704, MRR: 0.6649
valid [sampled], NDCG@5: 0.5418, HR@5: 0.5525, NDCG@10: 0.5596, HR@10: 0.6083, MRR: 0.5624
test [full], NDCG@5: 0.8062, HR@5: 0.9404, NDCG@10: 0.8241, HR@10: 0.9999, MRR: 0.7663
test [sampled], NDCG@5: 0.2274, HR@5: 0.2825, NDCG@10: 0.3037, HR@10: 0.5217, MRR: 0.2688
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/sasrec_best.pth
epoch=11, loss=0.0943
epoch=12, loss=0.0916
epoch=13, loss=0.0894
epoch=14, loss=0.0879
epoch=15, loss=0.0874
valid [full], NDCG@5: 0.7071, HR@5: 0.8889, NDCG@10: 0.7324, HR@10: 0.9714, MRR: 0.6609
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5640, NDCG@10: 0.5662, HR@10: 0.6089, MRR: 0.5700
test [full], NDCG@5: 0.7876, HR@5: 0.9523, NDCG@10: 0.8030, HR@10: 1.0000, MRR: 0.7362
test [sampled], NDCG@5: 0.1695, HR@5: 0.2071, NDCG@10: 0.2536, HR@10: 0.4743, MRR: 0.2238
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/sasrec_best.pth
epoch=16, loss=0.0841
epoch=17, loss=0.0838
epoch=18, loss=0.0829
epoch=19, loss=0.0826
epoch=20, loss=0.0827
valid [full], NDCG@5: 0.6866, HR@5: 0.8518, NDCG@10: 0.7146, HR@10: 0.9416, MRR: 0.6493
valid [sampled], NDCG@5: 0.5419, HR@5: 0.5478, NDCG@10: 0.5537, HR@10: 0.5846, MRR: 0.5604
test [full], NDCG@5: 0.8038, HR@5: 0.9982, NDCG@10: 0.8044, HR@10: 0.9999, MRR: 0.7379
test [sampled], NDCG@5: 0.1805, HR@5: 0.2211, NDCG@10: 0.2574, HR@10: 0.4640, MRR: 0.2305
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0804
epoch=22, loss=0.0798
epoch=23, loss=0.0792
epoch=24, loss=0.0806
epoch=25, loss=0.0791
valid [full], NDCG@5: 0.6960, HR@5: 0.8641, NDCG@10: 0.7196, HR@10: 0.9410, MRR: 0.6556
valid [sampled], NDCG@5: 0.5462, HR@5: 0.5586, NDCG@10: 0.5595, HR@10: 0.5998, MRR: 0.5630
test [full], NDCG@5: 0.7598, HR@5: 0.9791, NDCG@10: 0.7669, HR@10: 0.9999, MRR: 0.6880
test [sampled], NDCG@5: 0.1598, HR@5: 0.1956, NDCG@10: 0.2302, HR@10: 0.4184, MRR: 0.2105
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0764
epoch=27, loss=0.0765
epoch=28, loss=0.0766
epoch=29, loss=0.0798
epoch=30, loss=0.0761
valid [full], NDCG@5: 0.6775, HR@5: 0.8226, NDCG@10: 0.7175, HR@10: 0.9466, MRR: 0.6522
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5679, NDCG@10: 0.5693, HR@10: 0.6064, MRR: 0.5714
test [full], NDCG@5: 0.7488, HR@5: 0.9483, NDCG@10: 0.7649, HR@10: 1.0000, MRR: 0.6863
test [sampled], NDCG@5: 0.1478, HR@5: 0.1814, NDCG@10: 0.2225, HR@10: 0.4177, MRR: 0.2003
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0766
epoch=32, loss=0.0757
epoch=33, loss=0.0750
epoch=34, loss=0.0764
epoch=35, loss=0.0746
valid [full], NDCG@5: 0.6768, HR@5: 0.8626, NDCG@10: 0.7118, HR@10: 0.9730, MRR: 0.6336
valid [sampled], NDCG@5: 0.5194, HR@5: 0.5318, NDCG@10: 0.5344, HR@10: 0.5787, MRR: 0.5376
test [full], NDCG@5: 0.7868, HR@5: 0.9880, NDCG@10: 0.7909, HR@10: 0.9999, MRR: 0.7204
test [sampled], NDCG@5: 0.1789, HR@5: 0.2246, NDCG@10: 0.2546, HR@10: 0.4624, MRR: 0.2261
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0761
epoch=37, loss=0.0742
epoch=38, loss=0.0737
epoch=39, loss=0.0748
epoch=40, loss=0.0730
valid [full], NDCG@5: 0.7039, HR@5: 0.8695, NDCG@10: 0.7376, HR@10: 0.9752, MRR: 0.6654
valid [sampled], NDCG@5: 0.5416, HR@5: 0.5557, NDCG@10: 0.5643, HR@10: 0.6270, MRR: 0.5624
test [full], NDCG@5: 0.7933, HR@5: 0.9739, NDCG@10: 0.8023, HR@10: 0.9999, MRR: 0.7373
test [sampled], NDCG@5: 0.2547, HR@5: 0.2822, NDCG@10: 0.3002, HR@10: 0.4263, MRR: 0.2976
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0743
epoch=42, loss=0.0744
epoch=43, loss=0.0744
epoch=44, loss=0.0722
epoch=45, loss=0.0734
valid [full], NDCG@5: 0.6822, HR@5: 0.8370, NDCG@10: 0.7261, HR@10: 0.9759, MRR: 0.6520
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5585, NDCG@10: 0.5637, HR@10: 0.5993, MRR: 0.5689
test [full], NDCG@5: 0.7707, HR@5: 0.9573, NDCG@10: 0.7851, HR@10: 0.9999, MRR: 0.7164
test [sampled], NDCG@5: 0.2547, HR@5: 0.2793, NDCG@10: 0.2955, HR@10: 0.4080, MRR: 0.2956
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0717
epoch=47, loss=0.0733
epoch=48, loss=0.0737
epoch=49, loss=0.0709
epoch=50, loss=0.0737
valid [full], NDCG@5: 0.6864, HR@5: 0.8322, NDCG@10: 0.7308, HR@10: 0.9719, MRR: 0.6595
valid [sampled], NDCG@5: 0.5531, HR@5: 0.5610, NDCG@10: 0.5703, HR@10: 0.6151, MRR: 0.5724
test [full], NDCG@5: 0.7616, HR@5: 0.9356, NDCG@10: 0.7819, HR@10: 0.9999, MRR: 0.7096
test [sampled], NDCG@5: 0.2761, HR@5: 0.3040, NDCG@10: 0.3449, HR@10: 0.5230, MRR: 0.3216
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s2024/sasrec_last.pth

### timeaware_refine_ml50_do035_b8_s7

In [18]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b8_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7
epoch=1, loss=0.5810
epoch=2, loss=0.2715
epoch=3, loss=0.2022
epoch=4, loss=0.1681
epoch=5, loss=0.1452
valid [full], NDCG@5: 0.6743, HR@5: 0.8234, NDCG@10: 0.7235, HR@10: 0.9740, MRR: 0.6495
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5622, NDCG@10: 0.5672, HR@10: 0.5800, MRR: 0.5797
test [full], NDCG@5: 0.6352, HR@5: 0.8429, NDCG@10: 0.6734, HR@10: 0.9623, MRR: 0.5850
test [sampled], NDCG@5: 0.1949, HR@5: 0.2005, NDCG@10: 0.2382, HR@10: 0.3405, MRR: 0.2418
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=6, loss=0.1259
epoch=7, loss=0.1143
epoch=8, loss=0.1080
epoch=9, loss=0.1037
epoch=10, loss=0.0980
valid [full], NDCG@5: 0.6726, HR@5: 0.8102, NDCG@10: 0.7198, HR@10: 0.9579, MRR: 0.6518
valid [sampled], NDCG@5: 0.5645, HR@5: 0.5723, NDCG@10: 0.5735, HR@10: 0.6002, MRR: 0.5784
test [full], NDCG@5: 0.7233, HR@5: 0.9620, NDCG@10: 0.7360, HR@10: 1.0000, MRR: 0.6470
test [sampled], NDCG@5: 0.1002, HR@5: 0.1130, NDCG@10: 0.1777, HR@10: 0.3626, MRR: 0.1665
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0947
epoch=12, loss=0.0926
epoch=13, loss=0.0903
epoch=14, loss=0.0865
epoch=15, loss=0.0870
valid [full], NDCG@5: 0.6880, HR@5: 0.8429, NDCG@10: 0.7234, HR@10: 0.9540, MRR: 0.6562
valid [sampled], NDCG@5: 0.5585, HR@5: 0.5613, NDCG@10: 0.5701, HR@10: 0.5989, MRR: 0.5782
test [full], NDCG@5: 0.7767, HR@5: 0.9848, NDCG@10: 0.7820, HR@10: 1.0000, MRR: 0.7061
test [sampled], NDCG@5: 0.1442, HR@5: 0.1543, NDCG@10: 0.2270, HR@10: 0.4221, MRR: 0.2124
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=16, loss=0.0859
epoch=17, loss=0.0830
epoch=18, loss=0.0820
epoch=19, loss=0.0808
epoch=20, loss=0.0813
valid [full], NDCG@5: 0.6807, HR@5: 0.8006, NDCG@10: 0.7312, HR@10: 0.9549, MRR: 0.6661
valid [sampled], NDCG@5: 0.5660, HR@5: 0.5791, NDCG@10: 0.5872, HR@10: 0.6454, MRR: 0.5836
test [full], NDCG@5: 0.8288, HR@5: 0.9997, NDCG@10: 0.8289, HR@10: 1.0000, MRR: 0.7685
test [sampled], NDCG@5: 0.1945, HR@5: 0.2300, NDCG@10: 0.2903, HR@10: 0.5344, MRR: 0.2539
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0819
epoch=22, loss=0.0787
epoch=23, loss=0.0799
epoch=24, loss=0.0787
epoch=25, loss=0.0767
valid [full], NDCG@5: 0.7088, HR@5: 0.8501, NDCG@10: 0.7433, HR@10: 0.9571, MRR: 0.6798
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5815, NDCG@10: 0.5896, HR@10: 0.6525, MRR: 0.5862
test [full], NDCG@5: 0.8514, HR@5: 0.9995, NDCG@10: 0.8516, HR@10: 1.0000, MRR: 0.7997
test [sampled], NDCG@5: 0.3657, HR@5: 0.3932, NDCG@10: 0.4382, HR@10: 0.6230, MRR: 0.4112
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=26, loss=0.0779
epoch=27, loss=0.0768
epoch=28, loss=0.0768
epoch=29, loss=0.0771
epoch=30, loss=0.0740
valid [full], NDCG@5: 0.7095, HR@5: 0.8402, NDCG@10: 0.7479, HR@10: 0.9585, MRR: 0.6855
valid [sampled], NDCG@5: 0.5607, HR@5: 0.5742, NDCG@10: 0.5882, HR@10: 0.6600, MRR: 0.5817
test [full], NDCG@5: 0.9017, HR@5: 0.9989, NDCG@10: 0.9021, HR@10: 1.0000, MRR: 0.8685
test [sampled], NDCG@5: 0.3797, HR@5: 0.4475, NDCG@10: 0.4386, HR@10: 0.6292, MRR: 0.4055
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
epoch=31, loss=0.0761
epoch=32, loss=0.0750
epoch=33, loss=0.0751
epoch=34, loss=0.0743
epoch=35, loss=0.0757
valid [full], NDCG@5: 0.6900, HR@5: 0.8218, NDCG@10: 0.7329, HR@10: 0.9581, MRR: 0.6673
valid [sampled], NDCG@5: 0.5598, HR@5: 0.5743, NDCG@10: 0.5832, HR@10: 0.6470, MRR: 0.5776
test [full], NDCG@5: 0.7991, HR@5: 0.9989, NDCG@10: 0.7995, HR@10: 1.0000, MRR: 0.7314
test [sampled], NDCG@5: 0.3348, HR@5: 0.3535, NDCG@10: 0.3663, HR@10: 0.4536, MRR: 0.3751
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0737
epoch=37, loss=0.0750
epoch=38, loss=0.0741
epoch=39, loss=0.0743
epoch=40, loss=0.0741
valid [full], NDCG@5: 0.6932, HR@5: 0.8424, NDCG@10: 0.7299, HR@10: 0.9606, MRR: 0.6620
valid [sampled], NDCG@5: 0.5375, HR@5: 0.5435, NDCG@10: 0.5610, HR@10: 0.6192, MRR: 0.5609
test [full], NDCG@5: 0.8419, HR@5: 0.9997, NDCG@10: 0.8420, HR@10: 1.0000, MRR: 0.7876
test [sampled], NDCG@5: 0.3709, HR@5: 0.3801, NDCG@10: 0.4291, HR@10: 0.5674, MRR: 0.4189
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0765
epoch=42, loss=0.0726
epoch=43, loss=0.0738
epoch=44, loss=0.0725
epoch=45, loss=0.0730
valid [full], NDCG@5: 0.7045, HR@5: 0.8489, NDCG@10: 0.7401, HR@10: 0.9611, MRR: 0.6740
valid [sampled], NDCG@5: 0.5447, HR@5: 0.5599, NDCG@10: 0.5745, HR@10: 0.6537, MRR: 0.5664
test [full], NDCG@5: 0.8413, HR@5: 0.9999, NDCG@10: 0.8413, HR@10: 1.0000, MRR: 0.7864
test [sampled], NDCG@5: 0.3470, HR@5: 0.3643, NDCG@10: 0.4043, HR@10: 0.5472, MRR: 0.3934
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0721
epoch=47, loss=0.0724
epoch=48, loss=0.0725
epoch=49, loss=0.0726
epoch=50, loss=0.0724
valid [full], NDCG@5: 0.7188, HR@5: 0.8456, NDCG@10: 0.7557, HR@10: 0.9612, MRR: 0.6954
valid [sampled], NDCG@5: 0.5964, HR@5: 0.6122, NDCG@10: 0.6201, HR@10: 0.6864, MRR: 0.6131
test [full], NDCG@5: 0.8202, HR@5: 0.9997, NDCG@10: 0.8203, HR@10: 1.0000, MRR: 0.7600
test [sampled], NDCG@5: 0.3076, HR@5: 0.3223, NDCG@10: 0.3551, HR@10: 0.4734, MRR: 0.3551
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b8_s7/sasrec_last.pth

### timeaware_refine_ml50_do035_b9_s42

In [19]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b9_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42
epoch=1, loss=0.5811
epoch=2, loss=0.2632
epoch=3, loss=0.1985
epoch=4, loss=0.1625
epoch=5, loss=0.1395
valid [full], NDCG@5: 0.6291, HR@5: 0.7182, NDCG@10: 0.6887, HR@10: 0.9047, MRR: 0.6329
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5632, NDCG@10: 0.5672, HR@10: 0.5920, MRR: 0.5722
test [full], NDCG@5: 0.5805, HR@5: 0.7521, NDCG@10: 0.6231, HR@10: 0.8896, MRR: 0.5485
test [sampled], NDCG@5: 0.2080, HR@5: 0.2099, NDCG@10: 0.2296, HR@10: 0.2808, MRR: 0.2495
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=6, loss=0.1235
epoch=7, loss=0.1146
epoch=8, loss=0.1070
epoch=9, loss=0.1016
epoch=10, loss=0.0996
valid [full], NDCG@5: 0.6432, HR@5: 0.7484, NDCG@10: 0.7146, HR@10: 0.9681, MRR: 0.6415
valid [sampled], NDCG@5: 0.5557, HR@5: 0.5696, NDCG@10: 0.5699, HR@10: 0.6135, MRR: 0.5696
test [full], NDCG@5: 0.7065, HR@5: 0.9387, NDCG@10: 0.7274, HR@10: 0.9999, MRR: 0.6363
test [sampled], NDCG@5: 0.1790, HR@5: 0.1952, NDCG@10: 0.2407, HR@10: 0.3938, MRR: 0.2338
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=11, loss=0.0969
epoch=12, loss=0.0938
epoch=13, loss=0.0907
epoch=14, loss=0.0900
epoch=15, loss=0.0886
valid [full], NDCG@5: 0.6716, HR@5: 0.8148, NDCG@10: 0.7217, HR@10: 0.9703, MRR: 0.6480
valid [sampled], NDCG@5: 0.5478, HR@5: 0.5602, NDCG@10: 0.5665, HR@10: 0.6187, MRR: 0.5658
test [full], NDCG@5: 0.7073, HR@5: 0.9497, NDCG@10: 0.7246, HR@10: 1.0000, MRR: 0.6312
test [sampled], NDCG@5: 0.1540, HR@5: 0.1785, NDCG@10: 0.2320, HR@10: 0.4273, MRR: 0.2122
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=16, loss=0.0861
epoch=17, loss=0.0828
epoch=18, loss=0.0831
epoch=19, loss=0.0824
epoch=20, loss=0.0829
valid [full], NDCG@5: 0.6853, HR@5: 0.8272, NDCG@10: 0.7323, HR@10: 0.9707, MRR: 0.6622
valid [sampled], NDCG@5: 0.5658, HR@5: 0.5766, NDCG@10: 0.5794, HR@10: 0.6186, MRR: 0.5819
test [full], NDCG@5: 0.7384, HR@5: 0.9594, NDCG@10: 0.7521, HR@10: 1.0000, MRR: 0.6678
test [sampled], NDCG@5: 0.1978, HR@5: 0.2219, NDCG@10: 0.2708, HR@10: 0.4554, MRR: 0.2517
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=21, loss=0.0799
epoch=22, loss=0.0796
epoch=23, loss=0.0800
epoch=24, loss=0.0787
epoch=25, loss=0.0799
valid [full], NDCG@5: 0.6599, HR@5: 0.7751, NDCG@10: 0.7236, HR@10: 0.9696, MRR: 0.6522
valid [sampled], NDCG@5: 0.5551, HR@5: 0.5661, NDCG@10: 0.5702, HR@10: 0.6127, MRR: 0.5705
test [full], NDCG@5: 0.7386, HR@5: 0.9540, NDCG@10: 0.7542, HR@10: 1.0000, MRR: 0.6727
test [sampled], NDCG@5: 0.1879, HR@5: 0.2164, NDCG@10: 0.2436, HR@10: 0.3917, MRR: 0.2374
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0776
epoch=27, loss=0.0802
epoch=28, loss=0.0772
epoch=29, loss=0.0784
epoch=30, loss=0.0777
valid [full], NDCG@5: 0.6704, HR@5: 0.7905, NDCG@10: 0.7285, HR@10: 0.9710, MRR: 0.6582
valid [sampled], NDCG@5: 0.5637, HR@5: 0.5736, NDCG@10: 0.5776, HR@10: 0.6164, MRR: 0.5792
test [full], NDCG@5: 0.7488, HR@5: 0.9640, NDCG@10: 0.7614, HR@10: 1.0000, MRR: 0.6833
test [sampled], NDCG@5: 0.2440, HR@5: 0.2691, NDCG@10: 0.2837, HR@10: 0.3951, MRR: 0.2869
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0777
epoch=32, loss=0.0763
epoch=33, loss=0.0768
epoch=34, loss=0.0758
epoch=35, loss=0.0748
valid [full], NDCG@5: 0.6582, HR@5: 0.7837, NDCG@10: 0.7127, HR@10: 0.9525, MRR: 0.6442
valid [sampled], NDCG@5: 0.5530, HR@5: 0.5658, NDCG@10: 0.5705, HR@10: 0.6203, MRR: 0.5685
test [full], NDCG@5: 0.7403, HR@5: 0.9477, NDCG@10: 0.7566, HR@10: 1.0000, MRR: 0.6767
test [sampled], NDCG@5: 0.1815, HR@5: 0.2139, NDCG@10: 0.2380, HR@10: 0.3930, MRR: 0.2297
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0753
epoch=37, loss=0.0741
epoch=38, loss=0.0745
epoch=39, loss=0.0750
epoch=40, loss=0.0753
valid [full], NDCG@5: 0.6680, HR@5: 0.7903, NDCG@10: 0.7254, HR@10: 0.9720, MRR: 0.6538
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5705, NDCG@10: 0.5797, HR@10: 0.6214, MRR: 0.5809
test [full], NDCG@5: 0.7356, HR@5: 0.9588, NDCG@10: 0.7485, HR@10: 1.0000, MRR: 0.6675
test [sampled], NDCG@5: 0.1991, HR@5: 0.2267, NDCG@10: 0.2434, HR@10: 0.3660, MRR: 0.2436
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0751
epoch=42, loss=0.0758
epoch=43, loss=0.0759
epoch=44, loss=0.0738
epoch=45, loss=0.0745
valid [full], NDCG@5: 0.6665, HR@5: 0.7788, NDCG@10: 0.7237, HR@10: 0.9540, MRR: 0.6579
valid [sampled], NDCG@5: 0.5683, HR@5: 0.5807, NDCG@10: 0.5810, HR@10: 0.6199, MRR: 0.5819
test [full], NDCG@5: 0.7943, HR@5: 0.9423, NDCG@10: 0.8129, HR@10: 1.0000, MRR: 0.7507
test [sampled], NDCG@5: 0.2576, HR@5: 0.2998, NDCG@10: 0.3285, HR@10: 0.5228, MRR: 0.3008
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0721
epoch=47, loss=0.0727
epoch=48, loss=0.0725
epoch=49, loss=0.0724
epoch=50, loss=0.0734
valid [full], NDCG@5: 0.6635, HR@5: 0.7655, NDCG@10: 0.7301, HR@10: 0.9712, MRR: 0.6604
valid [sampled], NDCG@5: 0.5622, HR@5: 0.5737, NDCG@10: 0.5793, HR@10: 0.6269, MRR: 0.5774
test [full], NDCG@5: 0.8046, HR@5: 0.9679, NDCG@10: 0.8151, HR@10: 1.0000, MRR: 0.7525
test [sampled], NDCG@5: 0.2461, HR@5: 0.2969, NDCG@10: 0.3270, HR@10: 0.5508, MRR: 0.2901
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s42/sasrec_last.pth

### timeaware_refine_ml50_do035_b9_s2024

In [20]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b9_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024
epoch=1, loss=0.6064
epoch=2, loss=0.2697
epoch=3, loss=0.1967
epoch=4, loss=0.1575
epoch=5, loss=0.1370
valid [full], NDCG@5: 0.7001, HR@5: 0.8924, NDCG@10: 0.7348, HR@10: 0.9924, MRR: 0.6552
valid [sampled], NDCG@5: 0.5457, HR@5: 0.5543, NDCG@10: 0.5581, HR@10: 0.5935, MRR: 0.5643
test [full], NDCG@5: 0.7559, HR@5: 0.8925, NDCG@10: 0.7916, HR@10: 1.0000, MRR: 0.7266
test [sampled], NDCG@5: 0.2105, HR@5: 0.2729, NDCG@10: 0.2679, HR@10: 0.4498, MRR: 0.2422
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1209
epoch=7, loss=0.1125
epoch=8, loss=0.1073
epoch=9, loss=0.0995
epoch=10, loss=0.0979
valid [full], NDCG@5: 0.6709, HR@5: 0.8137, NDCG@10: 0.7223, HR@10: 0.9703, MRR: 0.6495
valid [sampled], NDCG@5: 0.5434, HR@5: 0.5535, NDCG@10: 0.5560, HR@10: 0.5928, MRR: 0.5597
test [full], NDCG@5: 0.8123, HR@5: 0.9269, NDCG@10: 0.8344, HR@10: 0.9999, MRR: 0.7812
test [sampled], NDCG@5: 0.1551, HR@5: 0.2364, NDCG@10: 0.2431, HR@10: 0.5101, MRR: 0.1931
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0944
epoch=12, loss=0.0917
epoch=13, loss=0.0893
epoch=14, loss=0.0881
epoch=15, loss=0.0875
valid [full], NDCG@5: 0.6788, HR@5: 0.8415, NDCG@10: 0.7178, HR@10: 0.9651, MRR: 0.6459
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5583, NDCG@10: 0.5605, HR@10: 0.5886, MRR: 0.5674
test [full], NDCG@5: 0.7798, HR@5: 0.9336, NDCG@10: 0.8007, HR@10: 1.0000, MRR: 0.7348
test [sampled], NDCG@5: 0.1720, HR@5: 0.2102, NDCG@10: 0.2569, HR@10: 0.4799, MRR: 0.2240
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0839
epoch=17, loss=0.0840
epoch=18, loss=0.0830
epoch=19, loss=0.0829
epoch=20, loss=0.0828
valid [full], NDCG@5: 0.6865, HR@5: 0.8453, NDCG@10: 0.7181, HR@10: 0.9462, MRR: 0.6528
valid [sampled], NDCG@5: 0.5510, HR@5: 0.5559, NDCG@10: 0.5611, HR@10: 0.5875, MRR: 0.5689
test [full], NDCG@5: 0.7700, HR@5: 0.9474, NDCG@10: 0.7872, HR@10: 0.9999, MRR: 0.7163
test [sampled], NDCG@5: 0.1858, HR@5: 0.2152, NDCG@10: 0.2583, HR@10: 0.4458, MRR: 0.2376
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0801
epoch=22, loss=0.0798
epoch=23, loss=0.0790
epoch=24, loss=0.0803
epoch=25, loss=0.0791
valid [full], NDCG@5: 0.6910, HR@5: 0.8548, NDCG@10: 0.7251, HR@10: 0.9645, MRR: 0.6544
valid [sampled], NDCG@5: 0.5430, HR@5: 0.5560, NDCG@10: 0.5567, HR@10: 0.5983, MRR: 0.5601
test [full], NDCG@5: 0.7455, HR@5: 0.9355, NDCG@10: 0.7657, HR@10: 0.9999, MRR: 0.6881
test [sampled], NDCG@5: 0.1672, HR@5: 0.2053, NDCG@10: 0.2389, HR@10: 0.4318, MRR: 0.2157
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0765
epoch=27, loss=0.0764
epoch=28, loss=0.0764
epoch=29, loss=0.0798
epoch=30, loss=0.0764
valid [full], NDCG@5: 0.6886, HR@5: 0.8539, NDCG@10: 0.7188, HR@10: 0.9499, MRR: 0.6518
valid [sampled], NDCG@5: 0.5409, HR@5: 0.5520, NDCG@10: 0.5549, HR@10: 0.5958, MRR: 0.5584
test [full], NDCG@5: 0.7470, HR@5: 0.9382, NDCG@10: 0.7664, HR@10: 1.0000, MRR: 0.6885
test [sampled], NDCG@5: 0.1541, HR@5: 0.1877, NDCG@10: 0.2275, HR@10: 0.4199, MRR: 0.2061
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0767
epoch=32, loss=0.0754
epoch=33, loss=0.0748
epoch=34, loss=0.0762
epoch=35, loss=0.0745
valid [full], NDCG@5: 0.6806, HR@5: 0.8527, NDCG@10: 0.7188, HR@10: 0.9733, MRR: 0.6421
valid [sampled], NDCG@5: 0.5208, HR@5: 0.5338, NDCG@10: 0.5388, HR@10: 0.5908, MRR: 0.5407
test [full], NDCG@5: 0.7609, HR@5: 0.9548, NDCG@10: 0.7760, HR@10: 0.9999, MRR: 0.7004
test [sampled], NDCG@5: 0.1738, HR@5: 0.2121, NDCG@10: 0.2486, HR@10: 0.4479, MRR: 0.2238
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0761
epoch=37, loss=0.0743
epoch=38, loss=0.0735
epoch=39, loss=0.0745
epoch=40, loss=0.0729
valid [full], NDCG@5: 0.7057, HR@5: 0.8692, NDCG@10: 0.7387, HR@10: 0.9736, MRR: 0.6672
valid [sampled], NDCG@5: 0.5404, HR@5: 0.5536, NDCG@10: 0.5660, HR@10: 0.6346, MRR: 0.5628
test [full], NDCG@5: 0.7895, HR@5: 0.9495, NDCG@10: 0.8052, HR@10: 0.9999, MRR: 0.7395
test [sampled], NDCG@5: 0.2554, HR@5: 0.2838, NDCG@10: 0.3154, HR@10: 0.4747, MRR: 0.3014
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=41, loss=0.0740
epoch=42, loss=0.0746
epoch=43, loss=0.0742
epoch=44, loss=0.0724
epoch=45, loss=0.0730
valid [full], NDCG@5: 0.6761, HR@5: 0.8310, NDCG@10: 0.7170, HR@10: 0.9584, MRR: 0.6460
valid [sampled], NDCG@5: 0.5371, HR@5: 0.5448, NDCG@10: 0.5512, HR@10: 0.5898, MRR: 0.5566
test [full], NDCG@5: 0.7535, HR@5: 0.9496, NDCG@10: 0.7700, HR@10: 0.9999, MRR: 0.6944
test [sampled], NDCG@5: 0.2704, HR@5: 0.2943, NDCG@10: 0.3131, HR@10: 0.4297, MRR: 0.3127
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0716
epoch=47, loss=0.0731
epoch=48, loss=0.0739
epoch=49, loss=0.0709
epoch=50, loss=0.0736
valid [full], NDCG@5: 0.6792, HR@5: 0.8361, NDCG@10: 0.7238, HR@10: 0.9746, MRR: 0.6484
valid [sampled], NDCG@5: 0.5231, HR@5: 0.5299, NDCG@10: 0.5394, HR@10: 0.5821, MRR: 0.5454
test [full], NDCG@5: 0.7749, HR@5: 0.9346, NDCG@10: 0.7952, HR@10: 0.9999, MRR: 0.7272
test [sampled], NDCG@5: 0.3257, HR@5: 0.3480, NDCG@10: 0.3879, HR@10: 0.5465, MRR: 0.3694
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s2024/sasrec_last.pth

### timeaware_refine_ml50_do035_b9_s7

In [21]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_ml50_do035_b9_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7
epoch=1, loss=0.5822
epoch=2, loss=0.2708
epoch=3, loss=0.2024
epoch=4, loss=0.1677
epoch=5, loss=0.1449
valid [full], NDCG@5: 0.6688, HR@5: 0.8131, NDCG@10: 0.7220, HR@10: 0.9727, MRR: 0.6481
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5635, NDCG@10: 0.5691, HR@10: 0.5833, MRR: 0.5807
test [full], NDCG@5: 0.6522, HR@5: 0.8841, NDCG@10: 0.6811, HR@10: 0.9731, MRR: 0.5887
test [sampled], NDCG@5: 0.1896, HR@5: 0.1951, NDCG@10: 0.2325, HR@10: 0.3341, MRR: 0.2387
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=6, loss=0.1262
epoch=7, loss=0.1148
epoch=8, loss=0.1084
epoch=9, loss=0.1038
epoch=10, loss=0.0981
valid [full], NDCG@5: 0.6648, HR@5: 0.7954, NDCG@10: 0.7107, HR@10: 0.9351, MRR: 0.6482
valid [sampled], NDCG@5: 0.5602, HR@5: 0.5633, NDCG@10: 0.5662, HR@10: 0.5824, MRR: 0.5754
test [full], NDCG@5: 0.7454, HR@5: 0.9959, NDCG@10: 0.7468, HR@10: 1.0000, MRR: 0.6605
test [sampled], NDCG@5: 0.1159, HR@5: 0.1264, NDCG@10: 0.1908, HR@10: 0.3681, MRR: 0.1824
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0956
epoch=12, loss=0.0928
epoch=13, loss=0.0905
epoch=14, loss=0.0866
epoch=15, loss=0.0873
valid [full], NDCG@5: 0.6823, HR@5: 0.8288, NDCG@10: 0.7227, HR@10: 0.9542, MRR: 0.6552
valid [sampled], NDCG@5: 0.5578, HR@5: 0.5599, NDCG@10: 0.5688, HR@10: 0.5958, MRR: 0.5777
test [full], NDCG@5: 0.7855, HR@5: 0.9946, NDCG@10: 0.7874, HR@10: 1.0000, MRR: 0.7132
test [sampled], NDCG@5: 0.1611, HR@5: 0.1729, NDCG@10: 0.2450, HR@10: 0.4442, MRR: 0.2282
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=16, loss=0.0860
epoch=17, loss=0.0830
epoch=18, loss=0.0820
epoch=19, loss=0.0809
epoch=20, loss=0.0812
valid [full], NDCG@5: 0.6800, HR@5: 0.8155, NDCG@10: 0.7241, HR@10: 0.9542, MRR: 0.6576
valid [sampled], NDCG@5: 0.5630, HR@5: 0.5741, NDCG@10: 0.5787, HR@10: 0.6228, MRR: 0.5797
test [full], NDCG@5: 0.8981, HR@5: 0.9999, NDCG@10: 0.8981, HR@10: 1.0000, MRR: 0.8625
test [sampled], NDCG@5: 0.2242, HR@5: 0.3046, NDCG@10: 0.3241, HR@10: 0.6152, MRR: 0.2655
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0815
epoch=22, loss=0.0783
epoch=23, loss=0.0798
epoch=24, loss=0.0785
epoch=25, loss=0.0766
valid [full], NDCG@5: 0.6952, HR@5: 0.8282, NDCG@10: 0.7375, HR@10: 0.9571, MRR: 0.6726
valid [sampled], NDCG@5: 0.5665, HR@5: 0.5801, NDCG@10: 0.5844, HR@10: 0.6362, MRR: 0.5839
test [full], NDCG@5: 0.9185, HR@5: 0.9988, NDCG@10: 0.9189, HR@10: 1.0000, MRR: 0.8909
test [sampled], NDCG@5: 0.3284, HR@5: 0.4190, NDCG@10: 0.4201, HR@10: 0.7018, MRR: 0.3572
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=26, loss=0.0777
epoch=27, loss=0.0765
epoch=28, loss=0.0767
epoch=29, loss=0.0767
epoch=30, loss=0.0738
valid [full], NDCG@5: 0.6964, HR@5: 0.8187, NDCG@10: 0.7427, HR@10: 0.9585, MRR: 0.6789
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5716, NDCG@10: 0.5806, HR@10: 0.6384, MRR: 0.5789
test [full], NDCG@5: 0.9342, HR@5: 0.9996, NDCG@10: 0.9344, HR@10: 1.0000, MRR: 0.9116
test [sampled], NDCG@5: 0.4046, HR@5: 0.4794, NDCG@10: 0.4789, HR@10: 0.7088, MRR: 0.4303
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=31, loss=0.0760
epoch=32, loss=0.0750
epoch=33, loss=0.0752
epoch=34, loss=0.0743
epoch=35, loss=0.0758
valid [full], NDCG@5: 0.6883, HR@5: 0.8259, NDCG@10: 0.7299, HR@10: 0.9562, MRR: 0.6636
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5716, NDCG@10: 0.5768, HR@10: 0.6279, MRR: 0.5763
test [full], NDCG@5: 0.8305, HR@5: 0.9991, NDCG@10: 0.8308, HR@10: 1.0000, MRR: 0.7735
test [sampled], NDCG@5: 0.4177, HR@5: 0.4332, NDCG@10: 0.4538, HR@10: 0.5479, MRR: 0.4553
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0740
epoch=37, loss=0.0744
epoch=38, loss=0.0739
epoch=39, loss=0.0744
epoch=40, loss=0.0741
valid [full], NDCG@5: 0.7088, HR@5: 0.8594, NDCG@10: 0.7398, HR@10: 0.9593, MRR: 0.6743
valid [sampled], NDCG@5: 0.5431, HR@5: 0.5574, NDCG@10: 0.5748, HR@10: 0.6579, MRR: 0.5658
test [full], NDCG@5: 0.8620, HR@5: 0.9997, NDCG@10: 0.8621, HR@10: 1.0000, MRR: 0.8139
test [sampled], NDCG@5: 0.4279, HR@5: 0.4445, NDCG@10: 0.4889, HR@10: 0.6399, MRR: 0.4707
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=41, loss=0.0767
epoch=42, loss=0.0725
epoch=43, loss=0.0736
epoch=44, loss=0.0722
epoch=45, loss=0.0731
valid [full], NDCG@5: 0.7170, HR@5: 0.8646, NDCG@10: 0.7477, HR@10: 0.9613, MRR: 0.6830
valid [sampled], NDCG@5: 0.5490, HR@5: 0.5650, NDCG@10: 0.5832, HR@10: 0.6730, MRR: 0.5723
test [full], NDCG@5: 0.8216, HR@5: 0.9999, NDCG@10: 0.8216, HR@10: 1.0000, MRR: 0.7612
test [sampled], NDCG@5: 0.3777, HR@5: 0.3938, NDCG@10: 0.4162, HR@10: 0.5162, MRR: 0.4184
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=46, loss=0.0721
epoch=47, loss=0.0725
epoch=48, loss=0.0725
epoch=49, loss=0.0727
epoch=50, loss=0.0725
valid [full], NDCG@5: 0.7103, HR@5: 0.8254, NDCG@10: 0.7541, HR@10: 0.9607, MRR: 0.6935
valid [sampled], NDCG@5: 0.5936, HR@5: 0.6082, NDCG@10: 0.6175, HR@10: 0.6834, MRR: 0.6109
test [full], NDCG@5: 0.8357, HR@5: 0.9997, NDCG@10: 0.8358, HR@10: 0.9999, MRR: 0.7823
test [sampled], NDCG@5: 0.4377, HR@5: 0.4518, NDCG@10: 0.4762, HR@10: 0.5730, MRR: 0.4735
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg5/timeaware_refine_ml50_do035_b9_s7/sasrec_last.pth

## Rebuild result tables from run folders

This avoids schema issues and lets us combine existing baseline runs with new time-aware runs safely.

In [22]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'time_bucket_boundaries': ','.join(str(x) for x in config.get('time_bucket_boundaries', [])),
            'time_bucket_count': config.get('time_bucket_count'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [23]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## NDCG@10 comparison summary

In [24]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
timeaware_runs = [
    'timeaware_refine_ml50_do035_b8_s42',
    'timeaware_refine_ml50_do035_b8_s2024',
    'timeaware_refine_ml50_do035_b8_s7',
    'timeaware_refine_ml50_do035_b9_s42',
    'timeaware_refine_ml50_do035_b9_s2024',
    'timeaware_refine_ml50_do035_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['bucket_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['bucket_variant'] = timeaware_subset['run_name'].apply(lambda x: 'b8' if '_b8_' in x else 'b9')

df_ndcg10 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['bucket_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'bucket_variant', 'use_time_embedding', 'time_bucket_boundaries',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                               run_name  seed bucket_variant  use_time_embedding                           time_bucket_boundaries  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     timeaware_refine_ml50_do035_b8_s7     7             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.755675               0.961206                0.718767              0.845634             0.695393                0.820329              1.000000               0.820236             0.999729            0.760042                    0.620062                  0.686413                   0.596447                 0.612228                0.613063                   0.355101                 0.473449                  0.307582                0.322270               0.355078
1    timeaware_refine_ml50_do035_b8_s42    42             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.735872               0.950223                0.699404              0.834573             0.673375                0.825379              1.000000               0.807890             0.943658            0.767326                    0.581745                  0.647243                   0.557606                 0.571643                0.576266                   0.398008                 0.547966                  0.341492                0.369438               0.381958
2  timeaware_refine_ml50_do035_b8_s2024  2024             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.737589               0.975212                0.703871              0.869460             0.665396                0.802276              0.999865               0.793266             0.973869            0.737286                    0.564312                  0.626979                   0.541552                 0.555676                0.562416                   0.300249                 0.426269                  0.254670                0.282194               0.297626
3     timeaware_refine_ml50_do035_b9_s7     7             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.754079               0.960665                0.710260              0.825358             0.693503                0.835758              0.999865               0.835715             0.999729            0.782300                    0.617529                  0.683424                   0.593645                 0.608152                0.610860                   0.476189                 0.573015                  0.437701                0.451775               0.473501
4    timeaware_refine_ml50_do035_b9_s42    42             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.732318               0.970700                0.685321              0.827184             0.662175                0.752063              1.000000               0.738352             0.959405            0.667788                    0.579360                  0.618615                   0.565768                 0.576616                0.581879                   0.270763                 0.455421                  0.197753                0.221875               0.251691
5  timeaware_refine_ml50_do035_b9_s2024  2024             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.738726               0.973596                0.705716              0.869190             0.667216                0.805208              0.999865               0.789474             0.949499            0.739477                    0.566021                  0.634556                   0.540436                 0.553646                0.562766                   0.315404                 0.474746                  0.255381                0.283819               0.301400
6                  refine_ml50_do035_s7     7       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
7                 refine_ml50_do035_s42    42       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
8               refine_ml50_do035_s2024  2024       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183

In [25]:
summary_ndcg10 = df_ndcg10.groupby('bucket_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

               best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                  mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
bucket_variant
b8                            0.743045  0.010971              0.962214  0.012525               0.707348  0.010139             0.849889  0.017828            0.678055  0.015536               0.815995  0.012146             0.999955  0.000078              0.807131  0.013501            0.972419  0.028064           0.754885  0.015670                   0.588706  0.028520                 0.653545  0.030214                  0.565201  0.028225                0.579849  0.029156               0.583915  0.026175                  0.351119  0.049001                0.482561  0.061358                 0.301248  0.043756               0.324634  0.043670              0.344887  0.043079
b9                            0.741707  0.011182              0.968320  0.006786               0.700432  0.013283             0.840577  0.024796            0.674298  0.016822               0.797676  0.042353             0.999910  0.000078              0.787847  0.048702            0.969544  0.026606           0.729855  0.057859                   0.587637  0.026733                 0.645532  0.033770                  0.566616  0.026614                0.579471  0.027365               0.585168  0.024215                  0.354119  0.108046                0.501061  0.063059                 0.296945  0.125257               0.319156  0.118954              0.342198  0.116397
baseline                      0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175

Interpretation guide for NDCG@10:
- first compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` across `baseline`, `b8`, and `b9`
- then check whether sampled metrics and MRR show a similar trend
- baseline is reused from the completed sanity-check candidate; only time-aware runs are newly trained here

## NDCG@5 comparison summary

In [26]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
timeaware_runs = [
    'timeaware_refine_ml50_do035_b8_s42',
    'timeaware_refine_ml50_do035_b8_s2024',
    'timeaware_refine_ml50_do035_b8_s7',
    'timeaware_refine_ml50_do035_b9_s42',
    'timeaware_refine_ml50_do035_b9_s2024',
    'timeaware_refine_ml50_do035_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['bucket_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['bucket_variant'] = timeaware_subset['run_name'].apply(lambda x: 'b8' if '_b8_' in x else 'b9')

df_ndcg5 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['bucket_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'bucket_variant', 'use_time_embedding', 'time_bucket_boundaries',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                               run_name  seed bucket_variant  use_time_embedding                           time_bucket_boundaries  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     timeaware_refine_ml50_do035_b8_s7     7             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.755675               0.961206                0.718767              0.845634             0.695393                0.820329              1.000000               0.820236             0.999729            0.760042                    0.620062                  0.686413                   0.596447                 0.612228                0.613063                   0.355101                 0.473449                  0.307582                0.322270               0.355078
1    timeaware_refine_ml50_do035_b8_s42    42             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.735872               0.950223                0.699404              0.834573             0.673375                0.825379              1.000000               0.807890             0.943658            0.767326                    0.581745                  0.647243                   0.557606                 0.571643                0.576266                   0.398008                 0.547966                  0.341492                0.369438               0.381958
2  timeaware_refine_ml50_do035_b8_s2024  2024             b8                True                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.732427               0.971374                0.707124              0.888889             0.660945                0.802967              1.000000               0.787603             0.952297            0.736190                    0.566173                  0.608890                   0.551806                 0.564033                0.569987                   0.253582                 0.474312                  0.169535                0.207130               0.223758
3     timeaware_refine_ml50_do035_b9_s7     7             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.747653               0.961280                0.717019              0.864614             0.683025                0.821596              1.000000               0.821551             0.999864            0.761243                    0.583207                  0.673001                   0.548985                 0.564952                0.572282                   0.416175                 0.516190                  0.377707                0.393849               0.418359
4    timeaware_refine_ml50_do035_b9_s42    42             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.732318               0.970700                0.685321              0.827184             0.662175                0.752063              1.000000               0.738352             0.959405            0.667788                    0.579360                  0.618615                   0.565768                 0.576616                0.581879                   0.270763                 0.455421                  0.197753                0.221875               0.251691
5  timeaware_refine_ml50_do035_b9_s2024  2024             b9                True  6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0                 0.738726               0.973596                0.705716              0.869190             0.667216                0.805208              0.999865               0.789474             0.949499            0.739477                    0.566021                  0.634556                   0.540436                 0.553646                0.562766                   0.315404                 0.474746                  0.255381                0.283819               0.301400
6                  refine_ml50_do035_s7     7       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
7                 refine_ml50_do035_s42    42       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
8               refine_ml50_do035_s2024  2024       baseline               False                6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183

In [27]:
summary_ndcg5 = df_ndcg5.groupby('bucket_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

               best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                  mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
bucket_variant
b8                            0.741325  0.012546              0.960934  0.010578               0.708432  0.009748             0.856365  0.028704            0.676571  0.017445               0.816225  0.011757             1.000000  0.000000              0.805243  0.016477            0.965228  0.030189           0.754519  0.016286                   0.589327  0.027733                 0.647516  0.038762                  0.568620  0.024273                0.582635  0.025910               0.586438  0.023270                  0.335564  0.074169                0.498576  0.042775                 0.272870  0.091082               0.299613  0.083492              0.320265  0.084651
b9                            0.739566  0.007702              0.968525  0.006439               0.702685  0.016065             0.853663  0.023045            0.670805  0.010879               0.792956  0.036350             0.999955  0.000078              0.783126  0.041961            0.969589  0.026683           0.722836  0.048900                   0.576196  0.009019                 0.642057  0.027958                  0.551730  0.012887                0.565071  0.011485               0.572309  0.009557                  0.334114  0.074490                0.482119  0.031048                 0.276947  0.091895               0.299848  0.087100              0.323817  0.085565
baseline                      0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175

Interpretation guide for NDCG@5:
- first compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` across `baseline`, `b8`, and `b9`
- then check whether sampled metrics and MRR show a similar trend
- baseline is reused from the completed sanity-check candidate; only time-aware runs are newly trained here