# SASRec BPI2012 Colab Sanity Check (Eval Fix)

Colab notebook for sanity checking the two selected post-fix baseline candidates.

Goals:
- reuse already completed runs instead of retraining them
- train only the missing seeds for the two selected candidate settings
- summarize mean/std and valid-test trends separately for `NDCG@10` and `NDCG@5` model-selection criteria

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('NDCG10_OUTPUT_DIR:', NDCG10_OUTPUT_DIR)
print('NDCG5_OUTPUT_DIR:', NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$NDCG10_OUTPUT_DIR"
!mkdir -p "$NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Candidate settings

Selected candidates for sanity check:
- `anchor_ml20` (`hidden_units=32, maxlen=20, dropout=0.2`)
- `refine_ml50_do035` (`hidden_units=50, maxlen=50, dropout=0.35`)

We will evaluate them under two model-selection criteria separately:
- `full_valid_ndcg@10`
- `full_valid_ndcg@5`

## Check existing completed runs

These runs should already exist and **must not be retrained**.

In [10]:
from pathlib import Path

existing_ndcg10 = [
    'anchor_ml20_s42',
    'refine_ml50_do035_s42',
]
existing_ndcg5 = [
    'anchor_ml20_s42',
    'refine_ml50_do035_s42',
]

for label, output_dir, run_names in [
    ('NDCG@10', Path(NDCG10_OUTPUT_DIR), existing_ndcg10),
    ('NDCG@5', Path(NDCG5_OUTPUT_DIR), existing_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
NDCG@10
anchor_ml20_s42 EXISTS
refine_ml50_do035_s42 EXISTS
================================================================================
NDCG@5
anchor_ml20_s42 EXISTS
refine_ml50_do035_s42 EXISTS

## Train only missing seeds for `NDCG@10`

Run these cells only if the corresponding run directory does not already exist.

### anchor_ml20_s2024

In [11]:
!python src/train_sasrec.py \
  --run_name anchor_ml20_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024
epoch=1, loss=0.6261
epoch=2, loss=0.3053
epoch=3, loss=0.2087
epoch=4, loss=0.1653
epoch=5, loss=0.1432
valid [full], NDCG@5: 0.6528, HR@5: 0.7732, NDCG@10: 0.7159, HR@10: 0.9707, MRR: 0.6426
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5593, NDCG@10: 0.5623, HR@10: 0.5710, MRR: 0.5754
test [full], NDCG@5: 0.7080, HR@5: 0.8769, NDCG@10: 0.7503, HR@10: 1.0000, MRR: 0.6720
test [sampled], NDCG@5: 0.2013, HR@5: 0.2642, NDCG@10: 0.2488, HR@10: 0.4097, MRR: 0.2276
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/sasrec_best.pth
epoch=6, loss=0.1312
epoch=7, loss=0.1202
epoch=8, loss=0.1152
epoch=9, loss=0.1106
epoch=10, loss=0.1084
valid [full], NDCG@5: 0.6829, HR@5: 0.8445, NDCG@10: 0.7212, HR@10: 0.9653, MRR: 0.6504
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5584, NDCG@10: 0.5614, HR@10: 0.5698, MRR: 0.5753
test [full], NDCG@5: 0.7187, HR@5: 0.9027, NDCG@10: 0.7528, HR@10: 0.9999, MRR: 0.6740
test [sampled], NDCG@5: 0.2217, HR@5: 0.2913, NDCG@10: 0.2804, HR@10: 0.4715, MRR: 0.2468
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/sasrec_best.pth
epoch=11, loss=0.1065
epoch=12, loss=0.1033
epoch=13, loss=0.1031
epoch=14, loss=0.1008
epoch=15, loss=0.0989
valid [full], NDCG@5: 0.6843, HR@5: 0.8429, NDCG@10: 0.7249, HR@10: 0.9711, MRR: 0.6529
valid [sampled], NDCG@5: 0.5633, HR@5: 0.5659, NDCG@10: 0.5705, HR@10: 0.5888, MRR: 0.5807
test [full], NDCG@5: 0.7761, HR@5: 0.9144, NDCG@10: 0.8054, HR@10: 1.0000, MRR: 0.7431
test [sampled], NDCG@5: 0.2772, HR@5: 0.3489, NDCG@10: 0.3365, HR@10: 0.5312, MRR: 0.3001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/sasrec_best.pth
epoch=16, loss=0.0973
epoch=17, loss=0.0975
epoch=18, loss=0.0964
epoch=19, loss=0.0957
epoch=20, loss=0.0938
valid [full], NDCG@5: 0.6826, HR@5: 0.8432, NDCG@10: 0.7158, HR@10: 0.9473, MRR: 0.6496
valid [sampled], NDCG@5: 0.5466, HR@5: 0.5495, NDCG@10: 0.5550, HR@10: 0.5761, MRR: 0.5649
test [full], NDCG@5: 0.8066, HR@5: 0.9174, NDCG@10: 0.8346, HR@10: 0.9999, MRR: 0.7822
test [sampled], NDCG@5: 0.2912, HR@5: 0.3598, NDCG@10: 0.3483, HR@10: 0.5354, MRR: 0.3160
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0928
epoch=22, loss=0.0924
epoch=23, loss=0.0937
epoch=24, loss=0.0916
epoch=25, loss=0.0922
valid [full], NDCG@5: 0.7003, HR@5: 0.8502, NDCG@10: 0.7368, HR@10: 0.9674, MRR: 0.6685
valid [sampled], NDCG@5: 0.5578, HR@5: 0.5632, NDCG@10: 0.5743, HR@10: 0.6161, MRR: 0.5786
test [full], NDCG@5: 0.8194, HR@5: 0.9378, NDCG@10: 0.8406, HR@10: 0.9999, MRR: 0.7891
test [sampled], NDCG@5: 0.2611, HR@5: 0.3268, NDCG@10: 0.3231, HR@10: 0.5185, MRR: 0.2925
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/sasrec_best.pth
epoch=26, loss=0.0901
epoch=27, loss=0.0910
epoch=28, loss=0.0894
epoch=29, loss=0.0936
epoch=30, loss=0.0877
valid [full], NDCG@5: 0.6924, HR@5: 0.8461, NDCG@10: 0.7261, HR@10: 0.9522, MRR: 0.6604
valid [sampled], NDCG@5: 0.5513, HR@5: 0.5562, NDCG@10: 0.5684, HR@10: 0.6107, MRR: 0.5721
test [full], NDCG@5: 0.8315, HR@5: 0.9467, NDCG@10: 0.8492, HR@10: 1.0000, MRR: 0.8002
test [sampled], NDCG@5: 0.2816, HR@5: 0.3508, NDCG@10: 0.3417, HR@10: 0.5363, MRR: 0.3098
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0912
epoch=32, loss=0.0922
epoch=33, loss=0.0901
epoch=34, loss=0.0911
epoch=35, loss=0.0897
valid [full], NDCG@5: 0.6996, HR@5: 0.8521, NDCG@10: 0.7285, HR@10: 0.9441, MRR: 0.6661
valid [sampled], NDCG@5: 0.5629, HR@5: 0.5692, NDCG@10: 0.5816, HR@10: 0.6285, MRR: 0.5836
test [full], NDCG@5: 0.8673, HR@5: 0.9469, NDCG@10: 0.8848, HR@10: 0.9999, MRR: 0.8486
test [sampled], NDCG@5: 0.2967, HR@5: 0.3792, NDCG@10: 0.3692, HR@10: 0.6015, MRR: 0.3218
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0892
epoch=37, loss=0.0890
epoch=38, loss=0.0889
epoch=39, loss=0.0883
epoch=40, loss=0.0866
valid [full], NDCG@5: 0.6922, HR@5: 0.8455, NDCG@10: 0.7256, HR@10: 0.9503, MRR: 0.6603
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5624, NDCG@10: 0.5736, HR@10: 0.6125, MRR: 0.5780
test [full], NDCG@5: 0.8070, HR@5: 0.9502, NDCG@10: 0.8229, HR@10: 0.9999, MRR: 0.7642
test [sampled], NDCG@5: 0.2589, HR@5: 0.2990, NDCG@10: 0.3327, HR@10: 0.5312, MRR: 0.3031
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0883
epoch=42, loss=0.0912
epoch=43, loss=0.0877
epoch=44, loss=0.0872
epoch=45, loss=0.0854
valid [full], NDCG@5: 0.6819, HR@5: 0.8059, NDCG@10: 0.7292, HR@10: 0.9501, MRR: 0.6651
valid [sampled], NDCG@5: 0.5629, HR@5: 0.5713, NDCG@10: 0.5813, HR@10: 0.6294, MRR: 0.5818
test [full], NDCG@5: 0.8801, HR@5: 0.9516, NDCG@10: 0.8955, HR@10: 0.9999, MRR: 0.8621
test [sampled], NDCG@5: 0.3077, HR@5: 0.3908, NDCG@10: 0.3860, HR@10: 0.6304, MRR: 0.3343
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0880
epoch=47, loss=0.0883
epoch=48, loss=0.0876
epoch=49, loss=0.0857
epoch=50, loss=0.0866
valid [full], NDCG@5: 0.6902, HR@5: 0.8443, NDCG@10: 0.7237, HR@10: 0.9485, MRR: 0.6581
valid [sampled], NDCG@5: 0.5472, HR@5: 0.5541, NDCG@10: 0.5658, HR@10: 0.6132, MRR: 0.5679
test [full], NDCG@5: 0.8848, HR@5: 0.9586, NDCG@10: 0.8977, HR@10: 0.9999, MRR: 0.8652
test [sampled], NDCG@5: 0.3095, HR@5: 0.3999, NDCG@10: 0.3874, HR@10: 0.6373, MRR: 0.3328
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s2024/sasrec_last.pth

### anchor_ml20_s7

In [12]:
!python src/train_sasrec.py \
  --run_name anchor_ml20_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7
epoch=1, loss=0.6517
epoch=2, loss=0.3093
epoch=3, loss=0.2163
epoch=4, loss=0.1750
epoch=5, loss=0.1489
valid [full], NDCG@5: 0.6739, HR@5: 0.8165, NDCG@10: 0.7175, HR@10: 0.9552, MRR: 0.6484
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5575, NDCG@10: 0.5649, HR@10: 0.5880, MRR: 0.5741
test [full], NDCG@5: 0.7164, HR@5: 0.8798, NDCG@10: 0.7520, HR@10: 0.9839, MRR: 0.6805
test [sampled], NDCG@5: 0.2192, HR@5: 0.2812, NDCG@10: 0.2711, HR@10: 0.4401, MRR: 0.2470
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/sasrec_best.pth
epoch=6, loss=0.1367
epoch=7, loss=0.1275
epoch=8, loss=0.1193
epoch=9, loss=0.1166
epoch=10, loss=0.1113
valid [full], NDCG@5: 0.6978, HR@5: 0.8457, NDCG@10: 0.7309, HR@10: 0.9486, MRR: 0.6675
valid [sampled], NDCG@5: 0.5638, HR@5: 0.5729, NDCG@10: 0.5775, HR@10: 0.6156, MRR: 0.5812
test [full], NDCG@5: 0.8079, HR@5: 0.9780, NDCG@10: 0.8156, HR@10: 0.9999, MRR: 0.7541
test [sampled], NDCG@5: 0.2354, HR@5: 0.3082, NDCG@10: 0.3066, HR@10: 0.5278, MRR: 0.2673
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/sasrec_best.pth
epoch=11, loss=0.1091
epoch=12, loss=0.1071
epoch=13, loss=0.1029
epoch=14, loss=0.1028
epoch=15, loss=0.1023
valid [full], NDCG@5: 0.7148, HR@5: 0.8801, NDCG@10: 0.7370, HR@10: 0.9533, MRR: 0.6732
valid [sampled], NDCG@5: 0.5705, HR@5: 0.5820, NDCG@10: 0.5878, HR@10: 0.6357, MRR: 0.5887
test [full], NDCG@5: 0.8818, HR@5: 0.9930, NDCG@10: 0.8842, HR@10: 0.9999, MRR: 0.8457
test [sampled], NDCG@5: 0.3610, HR@5: 0.4351, NDCG@10: 0.4230, HR@10: 0.6255, MRR: 0.3836
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/sasrec_best.pth
epoch=16, loss=0.1010
epoch=17, loss=0.0981
epoch=18, loss=0.0961
epoch=19, loss=0.0960
epoch=20, loss=0.0971
valid [full], NDCG@5: 0.6861, HR@5: 0.8364, NDCG@10: 0.7240, HR@10: 0.9543, MRR: 0.6569
valid [sampled], NDCG@5: 0.5645, HR@5: 0.5757, NDCG@10: 0.5803, HR@10: 0.6248, MRR: 0.5814
test [full], NDCG@5: 0.8699, HR@5: 0.9617, NDCG@10: 0.8829, HR@10: 1.0000, MRR: 0.8449
test [sampled], NDCG@5: 0.4236, HR@5: 0.4785, NDCG@10: 0.4725, HR@10: 0.6284, MRR: 0.4457
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0947
epoch=22, loss=0.0947
epoch=23, loss=0.0950
epoch=24, loss=0.0928
epoch=25, loss=0.0941
valid [full], NDCG@5: 0.7202, HR@5: 0.8900, NDCG@10: 0.7405, HR@10: 0.9570, MRR: 0.6759
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5707, NDCG@10: 0.5834, HR@10: 0.6349, MRR: 0.5849
test [full], NDCG@5: 0.9011, HR@5: 0.9729, NDCG@10: 0.9102, HR@10: 1.0000, MRR: 0.8809
test [sampled], NDCG@5: 0.4042, HR@5: 0.4591, NDCG@10: 0.4593, HR@10: 0.6295, MRR: 0.4306
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/sasrec_best.pth
epoch=26, loss=0.0925
epoch=27, loss=0.0932
epoch=28, loss=0.0912
epoch=29, loss=0.0906
epoch=30, loss=0.0901
valid [full], NDCG@5: 0.7292, HR@5: 0.8839, NDCG@10: 0.7533, HR@10: 0.9619, MRR: 0.6912
valid [sampled], NDCG@5: 0.5800, HR@5: 0.5946, NDCG@10: 0.6012, HR@10: 0.6611, MRR: 0.5979
test [full], NDCG@5: 0.9039, HR@5: 0.9719, NDCG@10: 0.9136, HR@10: 1.0000, MRR: 0.8855
test [sampled], NDCG@5: 0.4209, HR@5: 0.4842, NDCG@10: 0.4802, HR@10: 0.6674, MRR: 0.4437
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/sasrec_best.pth
epoch=31, loss=0.0923
epoch=32, loss=0.0881
epoch=33, loss=0.0911
epoch=34, loss=0.0883
epoch=35, loss=0.0906
valid [full], NDCG@5: 0.7238, HR@5: 0.8909, NDCG@10: 0.7448, HR@10: 0.9603, MRR: 0.6808
valid [sampled], NDCG@5: 0.5753, HR@5: 0.5832, NDCG@10: 0.5926, HR@10: 0.6378, MRR: 0.5954
test [full], NDCG@5: 0.8255, HR@5: 0.9514, NDCG@10: 0.8401, HR@10: 1.0000, MRR: 0.7872
test [sampled], NDCG@5: 0.3482, HR@5: 0.3697, NDCG@10: 0.4081, HR@10: 0.5603, MRR: 0.3912
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0908
epoch=37, loss=0.0896
epoch=38, loss=0.0881
epoch=39, loss=0.0870
epoch=40, loss=0.0897
valid [full], NDCG@5: 0.7287, HR@5: 0.8912, NDCG@10: 0.7500, HR@10: 0.9609, MRR: 0.6868
valid [sampled], NDCG@5: 0.5704, HR@5: 0.5853, NDCG@10: 0.5900, HR@10: 0.6468, MRR: 0.5891
test [full], NDCG@5: 0.8308, HR@5: 0.9574, NDCG@10: 0.8441, HR@10: 1.0000, MRR: 0.7918
test [sampled], NDCG@5: 0.3303, HR@5: 0.3525, NDCG@10: 0.3962, HR@10: 0.5624, MRR: 0.3758
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0900
epoch=42, loss=0.0878
epoch=43, loss=0.0876
epoch=44, loss=0.0897
epoch=45, loss=0.0866
valid [full], NDCG@5: 0.7192, HR@5: 0.8735, NDCG@10: 0.7473, HR@10: 0.9628, MRR: 0.6825
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5770, NDCG@10: 0.5890, HR@10: 0.6608, MRR: 0.5830
test [full], NDCG@5: 0.7784, HR@5: 0.9492, NDCG@10: 0.7943, HR@10: 1.0000, MRR: 0.7269
test [sampled], NDCG@5: 0.3359, HR@5: 0.3471, NDCG@10: 0.3683, HR@10: 0.4509, MRR: 0.3771
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0871
epoch=47, loss=0.0870
epoch=48, loss=0.0865
epoch=49, loss=0.0862
epoch=50, loss=0.0873
valid [full], NDCG@5: 0.7250, HR@5: 0.8882, NDCG@10: 0.7472, HR@10: 0.9605, MRR: 0.6832
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5705, NDCG@10: 0.5907, HR@10: 0.6611, MRR: 0.5866
test [full], NDCG@5: 0.8221, HR@5: 0.9567, NDCG@10: 0.8356, HR@10: 1.0000, MRR: 0.7804
test [sampled], NDCG@5: 0.3633, HR@5: 0.3811, NDCG@10: 0.4145, HR@10: 0.5448, MRR: 0.4053
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/anchor_ml20_s7/sasrec_last.pth

### refine_ml50_do035_s2024

In [13]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024
epoch=1, loss=0.6319
epoch=2, loss=0.2738
epoch=3, loss=0.2028
epoch=4, loss=0.1663
epoch=5, loss=0.1459
valid [full], NDCG@5: 0.7132, HR@5: 0.9064, NDCG@10: 0.7416, HR@10: 0.9930, MRR: 0.6644
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5671, NDCG@10: 0.5730, HR@10: 0.5970, MRR: 0.5830
test [full], NDCG@5: 0.7275, HR@5: 0.8502, NDCG@10: 0.7759, HR@10: 1.0000, MRR: 0.7072
test [sampled], NDCG@5: 0.2035, HR@5: 0.2645, NDCG@10: 0.2580, HR@10: 0.4318, MRR: 0.2342
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1287
epoch=7, loss=0.1189
epoch=8, loss=0.1141
epoch=9, loss=0.1072
epoch=10, loss=0.1057
valid [full], NDCG@5: 0.6664, HR@5: 0.7870, NDCG@10: 0.7297, HR@10: 0.9773, MRR: 0.6565
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5664, NDCG@10: 0.5740, HR@10: 0.6249, MRR: 0.5723
test [full], NDCG@5: 0.6817, HR@5: 0.8860, NDCG@10: 0.7197, HR@10: 1.0000, MRR: 0.6269
test [sampled], NDCG@5: 0.0739, HR@5: 0.1023, NDCG@10: 0.1607, HR@10: 0.3792, MRR: 0.1346
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1016
epoch=12, loss=0.0988
epoch=13, loss=0.0966
epoch=14, loss=0.0960
epoch=15, loss=0.0957
valid [full], NDCG@5: 0.6885, HR@5: 0.8753, NDCG@10: 0.7191, HR@10: 0.9737, MRR: 0.6420
valid [sampled], NDCG@5: 0.5144, HR@5: 0.5223, NDCG@10: 0.5340, HR@10: 0.5852, MRR: 0.5377
test [full], NDCG@5: 0.8154, HR@5: 0.9459, NDCG@10: 0.8339, HR@10: 1.0000, MRR: 0.7797
test [sampled], NDCG@5: 0.1981, HR@5: 0.2719, NDCG@10: 0.2764, HR@10: 0.5153, MRR: 0.2341
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0930
epoch=17, loss=0.0921
epoch=18, loss=0.0918
epoch=19, loss=0.0910
epoch=20, loss=0.0897
valid [full], NDCG@5: 0.6492, HR@5: 0.8587, NDCG@10: 0.6859, HR@10: 0.9742, MRR: 0.5983
valid [sampled], NDCG@5: 0.4490, HR@5: 0.4524, NDCG@10: 0.4672, HR@10: 0.5109, MRR: 0.4750
test [full], NDCG@5: 0.8955, HR@5: 0.9842, NDCG@10: 0.9011, HR@10: 1.0000, MRR: 0.8690
test [sampled], NDCG@5: 0.3711, HR@5: 0.4388, NDCG@10: 0.4341, HR@10: 0.6322, MRR: 0.3961
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0905
epoch=22, loss=0.0890
epoch=23, loss=0.0884
epoch=24, loss=0.0900
epoch=25, loss=0.0889
valid [full], NDCG@5: 0.6350, HR@5: 0.8249, NDCG@10: 0.6829, HR@10: 0.9743, MRR: 0.5953
valid [sampled], NDCG@5: 0.4632, HR@5: 0.4704, NDCG@10: 0.4791, HR@10: 0.5205, MRR: 0.4853
test [full], NDCG@5: 0.8533, HR@5: 0.9235, NDCG@10: 0.8797, HR@10: 1.0000, MRR: 0.8418
test [sampled], NDCG@5: 0.3831, HR@5: 0.4458, NDCG@10: 0.4401, HR@10: 0.6213, MRR: 0.4055
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0858
epoch=27, loss=0.0862
epoch=28, loss=0.0858
epoch=29, loss=0.0881
epoch=30, loss=0.0849
valid [full], NDCG@5: 0.6264, HR@5: 0.8207, NDCG@10: 0.6702, HR@10: 0.9558, MRR: 0.5858
valid [sampled], NDCG@5: 0.4560, HR@5: 0.4667, NDCG@10: 0.4721, HR@10: 0.5167, MRR: 0.4761
test [full], NDCG@5: 0.8719, HR@5: 0.9447, NDCG@10: 0.8905, HR@10: 1.0000, MRR: 0.8558
test [sampled], NDCG@5: 0.4199, HR@5: 0.4813, NDCG@10: 0.4711, HR@10: 0.6385, MRR: 0.4396
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0859
epoch=32, loss=0.0861
epoch=33, loss=0.0839
epoch=34, loss=0.0845
epoch=35, loss=0.0831
valid [full], NDCG@5: 0.6332, HR@5: 0.8451, NDCG@10: 0.6674, HR@10: 0.9545, MRR: 0.5820
valid [sampled], NDCG@5: 0.4386, HR@5: 0.4422, NDCG@10: 0.4489, HR@10: 0.4751, MRR: 0.4633
test [full], NDCG@5: 0.8789, HR@5: 0.9712, NDCG@10: 0.8891, HR@10: 1.0000, MRR: 0.8539
test [sampled], NDCG@5: 0.4208, HR@5: 0.4734, NDCG@10: 0.4652, HR@10: 0.6098, MRR: 0.4428
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0858
epoch=37, loss=0.0842
epoch=38, loss=0.0843
epoch=39, loss=0.0842
epoch=40, loss=0.0824
valid [full], NDCG@5: 0.6246, HR@5: 0.8286, NDCG@10: 0.6711, HR@10: 0.9752, MRR: 0.5807
valid [sampled], NDCG@5: 0.4608, HR@5: 0.4637, NDCG@10: 0.4688, HR@10: 0.4895, MRR: 0.4816
test [full], NDCG@5: 0.8885, HR@5: 0.9781, NDCG@10: 0.8962, HR@10: 1.0000, MRR: 0.8634
test [sampled], NDCG@5: 0.5810, HR@5: 0.5825, NDCG@10: 0.5938, HR@10: 0.6242, MRR: 0.6050
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0835
epoch=42, loss=0.0835
epoch=43, loss=0.0840
epoch=44, loss=0.0806
epoch=45, loss=0.0830
valid [full], NDCG@5: 0.6708, HR@5: 0.8432, NDCG@10: 0.7130, HR@10: 0.9767, MRR: 0.6341
valid [sampled], NDCG@5: 0.5185, HR@5: 0.5267, NDCG@10: 0.5312, HR@10: 0.5673, MRR: 0.5387
test [full], NDCG@5: 0.8855, HR@5: 0.9667, NDCG@10: 0.8972, HR@10: 1.0000, MRR: 0.8646
test [sampled], NDCG@5: 0.4397, HR@5: 0.4925, NDCG@10: 0.4859, HR@10: 0.6350, MRR: 0.4613
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0810
epoch=47, loss=0.0819
epoch=48, loss=0.0818
epoch=49, loss=0.0803
epoch=50, loss=0.0820
valid [full], NDCG@5: 0.6292, HR@5: 0.8374, NDCG@10: 0.6742, HR@10: 0.9745, MRR: 0.5835
valid [sampled], NDCG@5: 0.4499, HR@5: 0.4599, NDCG@10: 0.4645, HR@10: 0.5053, MRR: 0.4711
test [full], NDCG@5: 0.8802, HR@5: 0.9514, NDCG@10: 0.8964, HR@10: 1.0000, MRR: 0.8636
test [sampled], NDCG@5: 0.4406, HR@5: 0.4997, NDCG@10: 0.4920, HR@10: 0.6576, MRR: 0.4605
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s2024/sasrec_last.pth

### refine_ml50_do035_s7

In [14]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7
epoch=1, loss=0.5747
epoch=2, loss=0.2861
epoch=3, loss=0.2143
epoch=4, loss=0.1756
epoch=5, loss=0.1523
valid [full], NDCG@5: 0.6363, HR@5: 0.7473, NDCG@10: 0.7124, HR@10: 0.9714, MRR: 0.6369
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5622, NDCG@10: 0.5638, HR@10: 0.5688, MRR: 0.5767
test [full], NDCG@5: 0.5313, HR@5: 0.6785, NDCG@10: 0.5777, HR@10: 0.8147, MRR: 0.5182
test [sampled], NDCG@5: 0.1716, HR@5: 0.1724, NDCG@10: 0.1867, HR@10: 0.2223, MRR: 0.2107
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1368
epoch=7, loss=0.1246
epoch=8, loss=0.1189
epoch=9, loss=0.1142
epoch=10, loss=0.1080
valid [full], NDCG@5: 0.6772, HR@5: 0.8320, NDCG@10: 0.7154, HR@10: 0.9499, MRR: 0.6484
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5608, NDCG@10: 0.5653, HR@10: 0.5802, MRR: 0.5757
test [full], NDCG@5: 0.6655, HR@5: 0.9216, NDCG@10: 0.6926, HR@10: 0.9999, MRR: 0.5928
test [sampled], NDCG@5: 0.1597, HR@5: 0.1658, NDCG@10: 0.2048, HR@10: 0.3116, MRR: 0.2125
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=0.1058
epoch=12, loss=0.1036
epoch=13, loss=0.1011
epoch=14, loss=0.0969
epoch=15, loss=0.0977
valid [full], NDCG@5: 0.6902, HR@5: 0.8465, NDCG@10: 0.7233, HR@10: 0.9498, MRR: 0.6573
valid [sampled], NDCG@5: 0.5610, HR@5: 0.5705, NDCG@10: 0.5746, HR@10: 0.6129, MRR: 0.5782
test [full], NDCG@5: 0.6595, HR@5: 0.9423, NDCG@10: 0.6782, HR@10: 0.9999, MRR: 0.5711
test [sampled], NDCG@5: 0.1528, HR@5: 0.1624, NDCG@10: 0.2087, HR@10: 0.3426, MRR: 0.2067
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=0.0973
epoch=17, loss=0.0925
epoch=18, loss=0.0929
epoch=19, loss=0.0919
epoch=20, loss=0.0916
valid [full], NDCG@5: 0.6893, HR@5: 0.8511, NDCG@10: 0.7228, HR@10: 0.9596, MRR: 0.6536
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5702, NDCG@10: 0.5740, HR@10: 0.6070, MRR: 0.5793
test [full], NDCG@5: 0.7025, HR@5: 0.9462, NDCG@10: 0.7201, HR@10: 1.0000, MRR: 0.6258
test [sampled], NDCG@5: 0.1733, HR@5: 0.1892, NDCG@10: 0.2448, HR@10: 0.4189, MRR: 0.2290
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0906
epoch=22, loss=0.0889
epoch=23, loss=0.0891
epoch=24, loss=0.0893
epoch=25, loss=0.0860
valid [full], NDCG@5: 0.6962, HR@5: 0.8573, NDCG@10: 0.7288, HR@10: 0.9617, MRR: 0.6605
valid [sampled], NDCG@5: 0.5658, HR@5: 0.5753, NDCG@10: 0.5773, HR@10: 0.6110, MRR: 0.5820
test [full], NDCG@5: 0.8590, HR@5: 0.9577, NDCG@10: 0.8724, HR@10: 1.0000, MRR: 0.8312
test [sampled], NDCG@5: 0.3248, HR@5: 0.4175, NDCG@10: 0.4030, HR@10: 0.6569, MRR: 0.3458
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/sasrec_best.pth
epoch=26, loss=0.0883
epoch=27, loss=0.0877
epoch=28, loss=0.0869
epoch=29, loss=0.0867
epoch=30, loss=0.0846
valid [full], NDCG@5: 0.6480, HR@5: 0.8529, NDCG@10: 0.6838, HR@10: 0.9644, MRR: 0.5997
valid [sampled], NDCG@5: 0.4631, HR@5: 0.4708, NDCG@10: 0.4748, HR@10: 0.5072, MRR: 0.4842
test [full], NDCG@5: 0.8413, HR@5: 0.9464, NDCG@10: 0.8585, HR@10: 1.0000, MRR: 0.8131
test [sampled], NDCG@5: 0.3484, HR@5: 0.4377, NDCG@10: 0.4212, HR@10: 0.6605, MRR: 0.3669
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0855
epoch=32, loss=0.0844
epoch=33, loss=0.0853
epoch=34, loss=0.0825
epoch=35, loss=0.0868
valid [full], NDCG@5: 0.6689, HR@5: 0.8447, NDCG@10: 0.7055, HR@10: 0.9616, MRR: 0.6290
valid [sampled], NDCG@5: 0.5084, HR@5: 0.5213, NDCG@10: 0.5261, HR@10: 0.5760, MRR: 0.5279
test [full], NDCG@5: 0.8267, HR@5: 0.9502, NDCG@10: 0.8426, HR@10: 1.0000, MRR: 0.7912
test [sampled], NDCG@5: 0.2515, HR@5: 0.3449, NDCG@10: 0.3383, HR@10: 0.6130, MRR: 0.2782
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0846
epoch=37, loss=0.0848
epoch=38, loss=0.0833
epoch=39, loss=0.0845
epoch=40, loss=0.0836
valid [full], NDCG@5: 0.6822, HR@5: 0.8859, NDCG@10: 0.7058, HR@10: 0.9620, MRR: 0.6281
valid [sampled], NDCG@5: 0.4910, HR@5: 0.5016, NDCG@10: 0.5127, HR@10: 0.5705, MRR: 0.5141
test [full], NDCG@5: 0.8749, HR@5: 0.9480, NDCG@10: 0.8913, HR@10: 1.0000, MRR: 0.8570
test [sampled], NDCG@5: 0.4703, HR@5: 0.5343, NDCG@10: 0.5265, HR@10: 0.7064, MRR: 0.4884
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0867
epoch=42, loss=0.0826
epoch=43, loss=0.0836
epoch=44, loss=0.0824
epoch=45, loss=0.0833
valid [full], NDCG@5: 0.6894, HR@5: 0.8557, NDCG@10: 0.7228, HR@10: 0.9624, MRR: 0.6513
valid [sampled], NDCG@5: 0.5340, HR@5: 0.5468, NDCG@10: 0.5539, HR@10: 0.6093, MRR: 0.5533
test [full], NDCG@5: 0.8496, HR@5: 0.9523, NDCG@10: 0.8656, HR@10: 1.0000, MRR: 0.8224
test [sampled], NDCG@5: 0.4289, HR@5: 0.4991, NDCG@10: 0.4895, HR@10: 0.6849, MRR: 0.4468
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0826
epoch=47, loss=0.0815
epoch=48, loss=0.0817
epoch=49, loss=0.0817
epoch=50, loss=0.0823
valid [full], NDCG@5: 0.6793, HR@5: 0.8637, NDCG@10: 0.7105, HR@10: 0.9616, MRR: 0.6343
valid [sampled], NDCG@5: 0.4947, HR@5: 0.5099, NDCG@10: 0.5203, HR@10: 0.5910, MRR: 0.5174
test [full], NDCG@5: 0.8722, HR@5: 0.9997, NDCG@10: 0.8722, HR@10: 1.0000, MRR: 0.8292
test [sampled], NDCG@5: 0.4080, HR@5: 0.4837, NDCG@10: 0.4692, HR@10: 0.6715, MRR: 0.4271
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10/refine_ml50_do035_s7/sasrec_last.pth

## Train only missing seeds for `NDCG@5`

Run these cells only if the corresponding run directory does not already exist.

### anchor_ml20_s2024

In [15]:
!python src/train_sasrec.py \
  --run_name anchor_ml20_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024
epoch=1, loss=0.6261
epoch=2, loss=0.3053
epoch=3, loss=0.2087
epoch=4, loss=0.1653
epoch=5, loss=0.1432
valid [full], NDCG@5: 0.6528, HR@5: 0.7732, NDCG@10: 0.7159, HR@10: 0.9707, MRR: 0.6426
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5593, NDCG@10: 0.5623, HR@10: 0.5710, MRR: 0.5754
test [full], NDCG@5: 0.7080, HR@5: 0.8769, NDCG@10: 0.7503, HR@10: 1.0000, MRR: 0.6720
test [sampled], NDCG@5: 0.2013, HR@5: 0.2642, NDCG@10: 0.2488, HR@10: 0.4097, MRR: 0.2276
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/sasrec_best.pth
epoch=6, loss=0.1312
epoch=7, loss=0.1202
epoch=8, loss=0.1152
epoch=9, loss=0.1106
epoch=10, loss=0.1084
valid [full], NDCG@5: 0.6829, HR@5: 0.8445, NDCG@10: 0.7212, HR@10: 0.9653, MRR: 0.6504
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5584, NDCG@10: 0.5614, HR@10: 0.5698, MRR: 0.5753
test [full], NDCG@5: 0.7187, HR@5: 0.9027, NDCG@10: 0.7528, HR@10: 0.9999, MRR: 0.6740
test [sampled], NDCG@5: 0.2217, HR@5: 0.2913, NDCG@10: 0.2804, HR@10: 0.4715, MRR: 0.2468
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/sasrec_best.pth
epoch=11, loss=0.1065
epoch=12, loss=0.1033
epoch=13, loss=0.1031
epoch=14, loss=0.1008
epoch=15, loss=0.0989
valid [full], NDCG@5: 0.6843, HR@5: 0.8429, NDCG@10: 0.7249, HR@10: 0.9711, MRR: 0.6529
valid [sampled], NDCG@5: 0.5633, HR@5: 0.5659, NDCG@10: 0.5705, HR@10: 0.5888, MRR: 0.5807
test [full], NDCG@5: 0.7761, HR@5: 0.9144, NDCG@10: 0.8054, HR@10: 1.0000, MRR: 0.7431
test [sampled], NDCG@5: 0.2772, HR@5: 0.3489, NDCG@10: 0.3365, HR@10: 0.5312, MRR: 0.3001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/sasrec_best.pth
epoch=16, loss=0.0973
epoch=17, loss=0.0975
epoch=18, loss=0.0964
epoch=19, loss=0.0957
epoch=20, loss=0.0938
valid [full], NDCG@5: 0.6826, HR@5: 0.8432, NDCG@10: 0.7158, HR@10: 0.9473, MRR: 0.6496
valid [sampled], NDCG@5: 0.5466, HR@5: 0.5495, NDCG@10: 0.5550, HR@10: 0.5761, MRR: 0.5649
test [full], NDCG@5: 0.8066, HR@5: 0.9174, NDCG@10: 0.8346, HR@10: 0.9999, MRR: 0.7822
test [sampled], NDCG@5: 0.2912, HR@5: 0.3598, NDCG@10: 0.3483, HR@10: 0.5354, MRR: 0.3160
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0928
epoch=22, loss=0.0924
epoch=23, loss=0.0937
epoch=24, loss=0.0916
epoch=25, loss=0.0922
valid [full], NDCG@5: 0.7003, HR@5: 0.8502, NDCG@10: 0.7368, HR@10: 0.9674, MRR: 0.6685
valid [sampled], NDCG@5: 0.5578, HR@5: 0.5632, NDCG@10: 0.5743, HR@10: 0.6161, MRR: 0.5786
test [full], NDCG@5: 0.8194, HR@5: 0.9378, NDCG@10: 0.8406, HR@10: 0.9999, MRR: 0.7891
test [sampled], NDCG@5: 0.2611, HR@5: 0.3268, NDCG@10: 0.3231, HR@10: 0.5185, MRR: 0.2925
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/sasrec_best.pth
epoch=26, loss=0.0901
epoch=27, loss=0.0910
epoch=28, loss=0.0894
epoch=29, loss=0.0936
epoch=30, loss=0.0877
valid [full], NDCG@5: 0.6924, HR@5: 0.8461, NDCG@10: 0.7261, HR@10: 0.9522, MRR: 0.6604
valid [sampled], NDCG@5: 0.5513, HR@5: 0.5562, NDCG@10: 0.5684, HR@10: 0.6107, MRR: 0.5721
test [full], NDCG@5: 0.8315, HR@5: 0.9467, NDCG@10: 0.8492, HR@10: 1.0000, MRR: 0.8002
test [sampled], NDCG@5: 0.2816, HR@5: 0.3508, NDCG@10: 0.3417, HR@10: 0.5363, MRR: 0.3098
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0912
epoch=32, loss=0.0922
epoch=33, loss=0.0901
epoch=34, loss=0.0911
epoch=35, loss=0.0897
valid [full], NDCG@5: 0.6996, HR@5: 0.8521, NDCG@10: 0.7285, HR@10: 0.9441, MRR: 0.6661
valid [sampled], NDCG@5: 0.5629, HR@5: 0.5692, NDCG@10: 0.5816, HR@10: 0.6285, MRR: 0.5836
test [full], NDCG@5: 0.8673, HR@5: 0.9469, NDCG@10: 0.8848, HR@10: 0.9999, MRR: 0.8486
test [sampled], NDCG@5: 0.2967, HR@5: 0.3792, NDCG@10: 0.3692, HR@10: 0.6015, MRR: 0.3218
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0892
epoch=37, loss=0.0890
epoch=38, loss=0.0889
epoch=39, loss=0.0883
epoch=40, loss=0.0866
valid [full], NDCG@5: 0.6922, HR@5: 0.8455, NDCG@10: 0.7256, HR@10: 0.9503, MRR: 0.6603
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5624, NDCG@10: 0.5736, HR@10: 0.6125, MRR: 0.5780
test [full], NDCG@5: 0.8070, HR@5: 0.9502, NDCG@10: 0.8229, HR@10: 0.9999, MRR: 0.7642
test [sampled], NDCG@5: 0.2589, HR@5: 0.2990, NDCG@10: 0.3327, HR@10: 0.5312, MRR: 0.3031
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0883
epoch=42, loss=0.0912
epoch=43, loss=0.0877
epoch=44, loss=0.0872
epoch=45, loss=0.0854
valid [full], NDCG@5: 0.6819, HR@5: 0.8059, NDCG@10: 0.7292, HR@10: 0.9501, MRR: 0.6651
valid [sampled], NDCG@5: 0.5629, HR@5: 0.5713, NDCG@10: 0.5813, HR@10: 0.6294, MRR: 0.5818
test [full], NDCG@5: 0.8801, HR@5: 0.9516, NDCG@10: 0.8955, HR@10: 0.9999, MRR: 0.8621
test [sampled], NDCG@5: 0.3077, HR@5: 0.3908, NDCG@10: 0.3860, HR@10: 0.6304, MRR: 0.3343
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0880
epoch=47, loss=0.0883
epoch=48, loss=0.0876
epoch=49, loss=0.0857
epoch=50, loss=0.0866
valid [full], NDCG@5: 0.6902, HR@5: 0.8443, NDCG@10: 0.7237, HR@10: 0.9485, MRR: 0.6581
valid [sampled], NDCG@5: 0.5472, HR@5: 0.5541, NDCG@10: 0.5658, HR@10: 0.6132, MRR: 0.5679
test [full], NDCG@5: 0.8848, HR@5: 0.9586, NDCG@10: 0.8977, HR@10: 0.9999, MRR: 0.8652
test [sampled], NDCG@5: 0.3095, HR@5: 0.3999, NDCG@10: 0.3874, HR@10: 0.6373, MRR: 0.3328
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s2024/sasrec_last.pth

### anchor_ml20_s7

In [16]:
!python src/train_sasrec.py \
  --run_name anchor_ml20_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7
epoch=1, loss=0.6517
epoch=2, loss=0.3093
epoch=3, loss=0.2163
epoch=4, loss=0.1750
epoch=5, loss=0.1489
valid [full], NDCG@5: 0.6739, HR@5: 0.8165, NDCG@10: 0.7175, HR@10: 0.9552, MRR: 0.6484
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5575, NDCG@10: 0.5649, HR@10: 0.5880, MRR: 0.5741
test [full], NDCG@5: 0.7164, HR@5: 0.8798, NDCG@10: 0.7520, HR@10: 0.9839, MRR: 0.6805
test [sampled], NDCG@5: 0.2192, HR@5: 0.2812, NDCG@10: 0.2711, HR@10: 0.4401, MRR: 0.2470
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/sasrec_best.pth
epoch=6, loss=0.1367
epoch=7, loss=0.1275
epoch=8, loss=0.1193
epoch=9, loss=0.1166
epoch=10, loss=0.1113
valid [full], NDCG@5: 0.6978, HR@5: 0.8457, NDCG@10: 0.7309, HR@10: 0.9486, MRR: 0.6675
valid [sampled], NDCG@5: 0.5638, HR@5: 0.5729, NDCG@10: 0.5775, HR@10: 0.6156, MRR: 0.5812
test [full], NDCG@5: 0.8079, HR@5: 0.9780, NDCG@10: 0.8156, HR@10: 0.9999, MRR: 0.7541
test [sampled], NDCG@5: 0.2354, HR@5: 0.3082, NDCG@10: 0.3066, HR@10: 0.5278, MRR: 0.2673
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/sasrec_best.pth
epoch=11, loss=0.1091
epoch=12, loss=0.1071
epoch=13, loss=0.1029
epoch=14, loss=0.1028
epoch=15, loss=0.1023
valid [full], NDCG@5: 0.7148, HR@5: 0.8801, NDCG@10: 0.7370, HR@10: 0.9533, MRR: 0.6732
valid [sampled], NDCG@5: 0.5705, HR@5: 0.5820, NDCG@10: 0.5878, HR@10: 0.6357, MRR: 0.5887
test [full], NDCG@5: 0.8818, HR@5: 0.9930, NDCG@10: 0.8842, HR@10: 0.9999, MRR: 0.8457
test [sampled], NDCG@5: 0.3610, HR@5: 0.4351, NDCG@10: 0.4230, HR@10: 0.6255, MRR: 0.3836
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/sasrec_best.pth
epoch=16, loss=0.1010
epoch=17, loss=0.0981
epoch=18, loss=0.0961
epoch=19, loss=0.0960
epoch=20, loss=0.0971
valid [full], NDCG@5: 0.6861, HR@5: 0.8364, NDCG@10: 0.7240, HR@10: 0.9543, MRR: 0.6569
valid [sampled], NDCG@5: 0.5645, HR@5: 0.5757, NDCG@10: 0.5803, HR@10: 0.6248, MRR: 0.5814
test [full], NDCG@5: 0.8699, HR@5: 0.9617, NDCG@10: 0.8829, HR@10: 1.0000, MRR: 0.8449
test [sampled], NDCG@5: 0.4236, HR@5: 0.4785, NDCG@10: 0.4725, HR@10: 0.6284, MRR: 0.4457
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0947
epoch=22, loss=0.0947
epoch=23, loss=0.0950
epoch=24, loss=0.0928
epoch=25, loss=0.0941
valid [full], NDCG@5: 0.7202, HR@5: 0.8900, NDCG@10: 0.7405, HR@10: 0.9570, MRR: 0.6759
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5707, NDCG@10: 0.5834, HR@10: 0.6349, MRR: 0.5849
test [full], NDCG@5: 0.9011, HR@5: 0.9729, NDCG@10: 0.9102, HR@10: 1.0000, MRR: 0.8809
test [sampled], NDCG@5: 0.4042, HR@5: 0.4591, NDCG@10: 0.4593, HR@10: 0.6295, MRR: 0.4306
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/sasrec_best.pth
epoch=26, loss=0.0925
epoch=27, loss=0.0932
epoch=28, loss=0.0912
epoch=29, loss=0.0906
epoch=30, loss=0.0901
valid [full], NDCG@5: 0.7292, HR@5: 0.8839, NDCG@10: 0.7533, HR@10: 0.9619, MRR: 0.6912
valid [sampled], NDCG@5: 0.5800, HR@5: 0.5946, NDCG@10: 0.6012, HR@10: 0.6611, MRR: 0.5979
test [full], NDCG@5: 0.9039, HR@5: 0.9719, NDCG@10: 0.9136, HR@10: 1.0000, MRR: 0.8855
test [sampled], NDCG@5: 0.4209, HR@5: 0.4842, NDCG@10: 0.4802, HR@10: 0.6674, MRR: 0.4437
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/sasrec_best.pth
epoch=31, loss=0.0923
epoch=32, loss=0.0881
epoch=33, loss=0.0911
epoch=34, loss=0.0883
epoch=35, loss=0.0906
valid [full], NDCG@5: 0.7238, HR@5: 0.8909, NDCG@10: 0.7448, HR@10: 0.9603, MRR: 0.6808
valid [sampled], NDCG@5: 0.5753, HR@5: 0.5832, NDCG@10: 0.5926, HR@10: 0.6378, MRR: 0.5954
test [full], NDCG@5: 0.8255, HR@5: 0.9514, NDCG@10: 0.8401, HR@10: 1.0000, MRR: 0.7872
test [sampled], NDCG@5: 0.3482, HR@5: 0.3697, NDCG@10: 0.4081, HR@10: 0.5603, MRR: 0.3912
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0908
epoch=37, loss=0.0896
epoch=38, loss=0.0881
epoch=39, loss=0.0870
epoch=40, loss=0.0897
valid [full], NDCG@5: 0.7287, HR@5: 0.8912, NDCG@10: 0.7500, HR@10: 0.9609, MRR: 0.6868
valid [sampled], NDCG@5: 0.5704, HR@5: 0.5853, NDCG@10: 0.5900, HR@10: 0.6468, MRR: 0.5891
test [full], NDCG@5: 0.8308, HR@5: 0.9574, NDCG@10: 0.8441, HR@10: 1.0000, MRR: 0.7918
test [sampled], NDCG@5: 0.3303, HR@5: 0.3525, NDCG@10: 0.3962, HR@10: 0.5624, MRR: 0.3758
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0900
epoch=42, loss=0.0878
epoch=43, loss=0.0876
epoch=44, loss=0.0897
epoch=45, loss=0.0866
valid [full], NDCG@5: 0.7192, HR@5: 0.8735, NDCG@10: 0.7473, HR@10: 0.9628, MRR: 0.6825
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5770, NDCG@10: 0.5890, HR@10: 0.6608, MRR: 0.5830
test [full], NDCG@5: 0.7784, HR@5: 0.9492, NDCG@10: 0.7943, HR@10: 1.0000, MRR: 0.7269
test [sampled], NDCG@5: 0.3359, HR@5: 0.3471, NDCG@10: 0.3683, HR@10: 0.4509, MRR: 0.3771
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0871
epoch=47, loss=0.0870
epoch=48, loss=0.0865
epoch=49, loss=0.0862
epoch=50, loss=0.0873
valid [full], NDCG@5: 0.7250, HR@5: 0.8882, NDCG@10: 0.7472, HR@10: 0.9605, MRR: 0.6832
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5705, NDCG@10: 0.5907, HR@10: 0.6611, MRR: 0.5866
test [full], NDCG@5: 0.8221, HR@5: 0.9567, NDCG@10: 0.8356, HR@10: 1.0000, MRR: 0.7804
test [sampled], NDCG@5: 0.3633, HR@5: 0.3811, NDCG@10: 0.4145, HR@10: 0.5448, MRR: 0.4053
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/anchor_ml20_s7/sasrec_last.pth

### refine_ml50_do035_s2024

In [17]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024
epoch=1, loss=0.6319
epoch=2, loss=0.2738
epoch=3, loss=0.2028
epoch=4, loss=0.1663
epoch=5, loss=0.1459
valid [full], NDCG@5: 0.7132, HR@5: 0.9064, NDCG@10: 0.7416, HR@10: 0.9930, MRR: 0.6644
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5671, NDCG@10: 0.5730, HR@10: 0.5970, MRR: 0.5830
test [full], NDCG@5: 0.7275, HR@5: 0.8502, NDCG@10: 0.7759, HR@10: 1.0000, MRR: 0.7072
test [sampled], NDCG@5: 0.2035, HR@5: 0.2645, NDCG@10: 0.2580, HR@10: 0.4318, MRR: 0.2342
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1287
epoch=7, loss=0.1189
epoch=8, loss=0.1141
epoch=9, loss=0.1072
epoch=10, loss=0.1057
valid [full], NDCG@5: 0.6664, HR@5: 0.7870, NDCG@10: 0.7297, HR@10: 0.9773, MRR: 0.6565
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5664, NDCG@10: 0.5740, HR@10: 0.6249, MRR: 0.5723
test [full], NDCG@5: 0.6817, HR@5: 0.8860, NDCG@10: 0.7197, HR@10: 1.0000, MRR: 0.6269
test [sampled], NDCG@5: 0.0739, HR@5: 0.1023, NDCG@10: 0.1607, HR@10: 0.3792, MRR: 0.1346
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1016
epoch=12, loss=0.0988
epoch=13, loss=0.0966
epoch=14, loss=0.0960
epoch=15, loss=0.0957
valid [full], NDCG@5: 0.6885, HR@5: 0.8753, NDCG@10: 0.7191, HR@10: 0.9737, MRR: 0.6420
valid [sampled], NDCG@5: 0.5144, HR@5: 0.5223, NDCG@10: 0.5340, HR@10: 0.5852, MRR: 0.5377
test [full], NDCG@5: 0.8154, HR@5: 0.9459, NDCG@10: 0.8339, HR@10: 1.0000, MRR: 0.7797
test [sampled], NDCG@5: 0.1981, HR@5: 0.2719, NDCG@10: 0.2764, HR@10: 0.5153, MRR: 0.2341
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0930
epoch=17, loss=0.0921
epoch=18, loss=0.0918
epoch=19, loss=0.0910
epoch=20, loss=0.0897
valid [full], NDCG@5: 0.6492, HR@5: 0.8587, NDCG@10: 0.6859, HR@10: 0.9742, MRR: 0.5983
valid [sampled], NDCG@5: 0.4490, HR@5: 0.4524, NDCG@10: 0.4672, HR@10: 0.5109, MRR: 0.4750
test [full], NDCG@5: 0.8955, HR@5: 0.9842, NDCG@10: 0.9011, HR@10: 1.0000, MRR: 0.8690
test [sampled], NDCG@5: 0.3711, HR@5: 0.4388, NDCG@10: 0.4341, HR@10: 0.6322, MRR: 0.3961
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0905
epoch=22, loss=0.0890
epoch=23, loss=0.0884
epoch=24, loss=0.0900
epoch=25, loss=0.0889
valid [full], NDCG@5: 0.6350, HR@5: 0.8249, NDCG@10: 0.6829, HR@10: 0.9743, MRR: 0.5953
valid [sampled], NDCG@5: 0.4632, HR@5: 0.4704, NDCG@10: 0.4791, HR@10: 0.5205, MRR: 0.4853
test [full], NDCG@5: 0.8533, HR@5: 0.9235, NDCG@10: 0.8797, HR@10: 1.0000, MRR: 0.8418
test [sampled], NDCG@5: 0.3831, HR@5: 0.4458, NDCG@10: 0.4401, HR@10: 0.6213, MRR: 0.4055
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0858
epoch=27, loss=0.0862
epoch=28, loss=0.0858
epoch=29, loss=0.0881
epoch=30, loss=0.0849
valid [full], NDCG@5: 0.6264, HR@5: 0.8207, NDCG@10: 0.6702, HR@10: 0.9558, MRR: 0.5858
valid [sampled], NDCG@5: 0.4560, HR@5: 0.4667, NDCG@10: 0.4721, HR@10: 0.5167, MRR: 0.4761
test [full], NDCG@5: 0.8719, HR@5: 0.9447, NDCG@10: 0.8905, HR@10: 1.0000, MRR: 0.8558
test [sampled], NDCG@5: 0.4199, HR@5: 0.4813, NDCG@10: 0.4711, HR@10: 0.6385, MRR: 0.4396
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0859
epoch=32, loss=0.0861
epoch=33, loss=0.0839
epoch=34, loss=0.0845
epoch=35, loss=0.0831
valid [full], NDCG@5: 0.6332, HR@5: 0.8451, NDCG@10: 0.6674, HR@10: 0.9545, MRR: 0.5820
valid [sampled], NDCG@5: 0.4386, HR@5: 0.4422, NDCG@10: 0.4489, HR@10: 0.4751, MRR: 0.4633
test [full], NDCG@5: 0.8789, HR@5: 0.9712, NDCG@10: 0.8891, HR@10: 1.0000, MRR: 0.8539
test [sampled], NDCG@5: 0.4208, HR@5: 0.4734, NDCG@10: 0.4652, HR@10: 0.6098, MRR: 0.4428
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0858
epoch=37, loss=0.0842
epoch=38, loss=0.0843
epoch=39, loss=0.0842
epoch=40, loss=0.0824
valid [full], NDCG@5: 0.6246, HR@5: 0.8286, NDCG@10: 0.6711, HR@10: 0.9752, MRR: 0.5807
valid [sampled], NDCG@5: 0.4608, HR@5: 0.4637, NDCG@10: 0.4688, HR@10: 0.4895, MRR: 0.4816
test [full], NDCG@5: 0.8885, HR@5: 0.9781, NDCG@10: 0.8962, HR@10: 1.0000, MRR: 0.8634
test [sampled], NDCG@5: 0.5810, HR@5: 0.5825, NDCG@10: 0.5938, HR@10: 0.6242, MRR: 0.6050
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0835
epoch=42, loss=0.0835
epoch=43, loss=0.0840
epoch=44, loss=0.0806
epoch=45, loss=0.0830
valid [full], NDCG@5: 0.6708, HR@5: 0.8432, NDCG@10: 0.7130, HR@10: 0.9767, MRR: 0.6341
valid [sampled], NDCG@5: 0.5185, HR@5: 0.5267, NDCG@10: 0.5312, HR@10: 0.5673, MRR: 0.5387
test [full], NDCG@5: 0.8855, HR@5: 0.9667, NDCG@10: 0.8972, HR@10: 1.0000, MRR: 0.8646
test [sampled], NDCG@5: 0.4397, HR@5: 0.4925, NDCG@10: 0.4859, HR@10: 0.6350, MRR: 0.4613
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0810
epoch=47, loss=0.0819
epoch=48, loss=0.0818
epoch=49, loss=0.0803
epoch=50, loss=0.0820
valid [full], NDCG@5: 0.6292, HR@5: 0.8374, NDCG@10: 0.6742, HR@10: 0.9745, MRR: 0.5835
valid [sampled], NDCG@5: 0.4499, HR@5: 0.4599, NDCG@10: 0.4645, HR@10: 0.5053, MRR: 0.4711
test [full], NDCG@5: 0.8802, HR@5: 0.9514, NDCG@10: 0.8964, HR@10: 1.0000, MRR: 0.8636
test [sampled], NDCG@5: 0.4406, HR@5: 0.4997, NDCG@10: 0.4920, HR@10: 0.6576, MRR: 0.4605
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s2024/sasrec_last.pth

### refine_ml50_do035_s7

In [18]:
!python src/train_sasrec.py \
  --run_name refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7
epoch=1, loss=0.5747
epoch=2, loss=0.2861
epoch=3, loss=0.2143
epoch=4, loss=0.1756
epoch=5, loss=0.1523
valid [full], NDCG@5: 0.6363, HR@5: 0.7473, NDCG@10: 0.7124, HR@10: 0.9714, MRR: 0.6369
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5622, NDCG@10: 0.5638, HR@10: 0.5688, MRR: 0.5767
test [full], NDCG@5: 0.5313, HR@5: 0.6785, NDCG@10: 0.5777, HR@10: 0.8147, MRR: 0.5182
test [sampled], NDCG@5: 0.1716, HR@5: 0.1724, NDCG@10: 0.1867, HR@10: 0.2223, MRR: 0.2107
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1368
epoch=7, loss=0.1246
epoch=8, loss=0.1189
epoch=9, loss=0.1142
epoch=10, loss=0.1080
valid [full], NDCG@5: 0.6772, HR@5: 0.8320, NDCG@10: 0.7154, HR@10: 0.9499, MRR: 0.6484
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5608, NDCG@10: 0.5653, HR@10: 0.5802, MRR: 0.5757
test [full], NDCG@5: 0.6655, HR@5: 0.9216, NDCG@10: 0.6926, HR@10: 0.9999, MRR: 0.5928
test [sampled], NDCG@5: 0.1597, HR@5: 0.1658, NDCG@10: 0.2048, HR@10: 0.3116, MRR: 0.2125
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=0.1058
epoch=12, loss=0.1036
epoch=13, loss=0.1011
epoch=14, loss=0.0969
epoch=15, loss=0.0977
valid [full], NDCG@5: 0.6902, HR@5: 0.8465, NDCG@10: 0.7233, HR@10: 0.9498, MRR: 0.6573
valid [sampled], NDCG@5: 0.5610, HR@5: 0.5705, NDCG@10: 0.5746, HR@10: 0.6129, MRR: 0.5782
test [full], NDCG@5: 0.6595, HR@5: 0.9423, NDCG@10: 0.6782, HR@10: 0.9999, MRR: 0.5711
test [sampled], NDCG@5: 0.1528, HR@5: 0.1624, NDCG@10: 0.2087, HR@10: 0.3426, MRR: 0.2067
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=0.0973
epoch=17, loss=0.0925
epoch=18, loss=0.0929
epoch=19, loss=0.0919
epoch=20, loss=0.0916
valid [full], NDCG@5: 0.6893, HR@5: 0.8511, NDCG@10: 0.7228, HR@10: 0.9596, MRR: 0.6536
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5702, NDCG@10: 0.5740, HR@10: 0.6070, MRR: 0.5793
test [full], NDCG@5: 0.7025, HR@5: 0.9462, NDCG@10: 0.7201, HR@10: 1.0000, MRR: 0.6258
test [sampled], NDCG@5: 0.1733, HR@5: 0.1892, NDCG@10: 0.2448, HR@10: 0.4189, MRR: 0.2290
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0906
epoch=22, loss=0.0889
epoch=23, loss=0.0891
epoch=24, loss=0.0893
epoch=25, loss=0.0860
valid [full], NDCG@5: 0.6962, HR@5: 0.8573, NDCG@10: 0.7288, HR@10: 0.9617, MRR: 0.6605
valid [sampled], NDCG@5: 0.5658, HR@5: 0.5753, NDCG@10: 0.5773, HR@10: 0.6110, MRR: 0.5820
test [full], NDCG@5: 0.8590, HR@5: 0.9577, NDCG@10: 0.8724, HR@10: 1.0000, MRR: 0.8312
test [sampled], NDCG@5: 0.3248, HR@5: 0.4175, NDCG@10: 0.4030, HR@10: 0.6569, MRR: 0.3458
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/sasrec_best.pth
epoch=26, loss=0.0883
epoch=27, loss=0.0877
epoch=28, loss=0.0869
epoch=29, loss=0.0867
epoch=30, loss=0.0846
valid [full], NDCG@5: 0.6480, HR@5: 0.8529, NDCG@10: 0.6838, HR@10: 0.9644, MRR: 0.5997
valid [sampled], NDCG@5: 0.4631, HR@5: 0.4708, NDCG@10: 0.4748, HR@10: 0.5072, MRR: 0.4842
test [full], NDCG@5: 0.8413, HR@5: 0.9464, NDCG@10: 0.8585, HR@10: 1.0000, MRR: 0.8131
test [sampled], NDCG@5: 0.3484, HR@5: 0.4377, NDCG@10: 0.4212, HR@10: 0.6605, MRR: 0.3669
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0855
epoch=32, loss=0.0844
epoch=33, loss=0.0853
epoch=34, loss=0.0825
epoch=35, loss=0.0868
valid [full], NDCG@5: 0.6689, HR@5: 0.8447, NDCG@10: 0.7055, HR@10: 0.9616, MRR: 0.6290
valid [sampled], NDCG@5: 0.5084, HR@5: 0.5213, NDCG@10: 0.5261, HR@10: 0.5760, MRR: 0.5279
test [full], NDCG@5: 0.8267, HR@5: 0.9502, NDCG@10: 0.8426, HR@10: 1.0000, MRR: 0.7912
test [sampled], NDCG@5: 0.2515, HR@5: 0.3449, NDCG@10: 0.3383, HR@10: 0.6130, MRR: 0.2782
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0846
epoch=37, loss=0.0848
epoch=38, loss=0.0833
epoch=39, loss=0.0845
epoch=40, loss=0.0836
valid [full], NDCG@5: 0.6822, HR@5: 0.8859, NDCG@10: 0.7058, HR@10: 0.9620, MRR: 0.6281
valid [sampled], NDCG@5: 0.4910, HR@5: 0.5016, NDCG@10: 0.5127, HR@10: 0.5705, MRR: 0.5141
test [full], NDCG@5: 0.8749, HR@5: 0.9480, NDCG@10: 0.8913, HR@10: 1.0000, MRR: 0.8570
test [sampled], NDCG@5: 0.4703, HR@5: 0.5343, NDCG@10: 0.5265, HR@10: 0.7064, MRR: 0.4884
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0867
epoch=42, loss=0.0826
epoch=43, loss=0.0836
epoch=44, loss=0.0824
epoch=45, loss=0.0833
valid [full], NDCG@5: 0.6894, HR@5: 0.8557, NDCG@10: 0.7228, HR@10: 0.9624, MRR: 0.6513
valid [sampled], NDCG@5: 0.5340, HR@5: 0.5468, NDCG@10: 0.5539, HR@10: 0.6093, MRR: 0.5533
test [full], NDCG@5: 0.8496, HR@5: 0.9523, NDCG@10: 0.8656, HR@10: 1.0000, MRR: 0.8224
test [sampled], NDCG@5: 0.4289, HR@5: 0.4991, NDCG@10: 0.4895, HR@10: 0.6849, MRR: 0.4468
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0826
epoch=47, loss=0.0815
epoch=48, loss=0.0817
epoch=49, loss=0.0817
epoch=50, loss=0.0823
valid [full], NDCG@5: 0.6793, HR@5: 0.8637, NDCG@10: 0.7105, HR@10: 0.9616, MRR: 0.6343
valid [sampled], NDCG@5: 0.4947, HR@5: 0.5099, NDCG@10: 0.5203, HR@10: 0.5910, MRR: 0.5174
test [full], NDCG@5: 0.8722, HR@5: 0.9997, NDCG@10: 0.8722, HR@10: 1.0000, MRR: 0.8292
test [sampled], NDCG@5: 0.4080, HR@5: 0.4837, NDCG@10: 0.4692, HR@10: 0.6715, MRR: 0.4271
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5/refine_ml50_do035_s7/sasrec_last.pth

## Rebuild result table from run folders

This avoids schema issues in `experiment_index.csv` and lets us combine existing and newly added runs safely.

In [19]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [20]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## `NDCG@10` sanity check summary

In [21]:
ndcg10_targets = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

df10 = rebuild_df(NDCG10_OUTPUT_DIR)
df10_sc = df10[df10['run_name'].isin(ndcg10_targets)].copy()
df10_sc = df10_sc.sort_values(['run_name']).reset_index(drop=True)
df10_sc[[
    'run_name', 'seed',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                  run_name  seed  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0        anchor_ml20_s2024  2024                 0.736821               0.967429                0.700301              0.850202             0.668534                0.840611              0.999865               0.819421             0.937829            0.789072                    0.574314                  0.616064                   0.557801                 0.563197                0.578608                   0.323103                 0.518524                  0.261120                0.326822               0.292464
1          anchor_ml20_s42    42                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296              1.000000               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
2           anchor_ml20_s7     7                 0.753294               0.961857                0.729167              0.883942             0.691225                0.913637              1.000000               0.903861             0.971918            0.885501                    0.601240                  0.661113                   0.580044                 0.594609                0.597937                   0.480200                 0.667438                  0.420861                0.484209               0.443705
3  refine_ml50_do035_s2024  2024                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183
4    refine_ml50_do035_s42    42                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
5     refine_ml50_do035_s7     7                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750

In [22]:
df10_sc['candidate'] = df10_sc['run_name'].apply(
    lambda x: 'anchor_ml20' if 'anchor_ml20' in x else 'refine_ml50_do035'
)
summary10 = df10_sc.groupby('candidate')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary10

                  best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                     mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
candidate
anchor_ml20                      0.746827  0.008788              0.968944  0.007954               0.712751  0.014836             0.860883  0.019988            0.680520  0.011400               0.889848  0.042649             0.999955  0.000078              0.879032  0.051864            0.968510  0.029126           0.853805  0.056064                   0.586415  0.013668                 0.643839  0.024291                  0.564734  0.013279                0.575209  0.016959               0.584993  0.011211                  0.422731  0.086620                0.612810  0.081997                 0.362874  0.088408               0.428098  0.087878              0.388797  0.083699
refine_ml50_do035                0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175

Interpretation guide for `NDCG@10`:
- compare mean/std of `best_valid_full_ndcg@10` and `best_test_full_ndcg@10`
- then check whether `@5`, sampled, and MRR show a similar trend

## `NDCG@5` sanity check summary

In [23]:
ndcg5_targets = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

df5 = rebuild_df(NDCG5_OUTPUT_DIR)
df5_sc = df5[df5['run_name'].isin(ndcg5_targets)].copy()
df5_sc = df5_sc.sort_values(['run_name']).reset_index(drop=True)
df5_sc[[
    'run_name', 'seed',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                  run_name  seed  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0        anchor_ml20_s2024  2024                 0.736821               0.967429                0.700301              0.850202             0.668534                0.840611              0.999865               0.819421             0.937829            0.789072                    0.574314                  0.616064                   0.557801                 0.563197                0.578608                   0.323103                 0.518524                  0.261120                0.326822               0.292464
1          anchor_ml20_s42    42                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296              1.000000               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
2           anchor_ml20_s7     7                 0.753294               0.961857                0.729167              0.883942             0.691225                0.913637              1.000000               0.903861             0.971918            0.885501                    0.601240                  0.661113                   0.580044                 0.594609                0.597937                   0.480200                 0.667438                  0.420861                0.484209               0.443705
3  refine_ml50_do035_s2024  2024                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183
4    refine_ml50_do035_s42    42                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
5     refine_ml50_do035_s7     7                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750

In [24]:
df5_sc['candidate'] = df5_sc['run_name'].apply(
    lambda x: 'anchor_ml20' if 'anchor_ml20' in x else 'refine_ml50_do035'
)
summary5 = df5_sc.groupby('candidate')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary5

                  best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                     mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
candidate
anchor_ml20                      0.746827  0.008788              0.968944  0.007954               0.712751  0.014836             0.860883  0.019988            0.680520  0.011400               0.889848  0.042649             0.999955  0.000078              0.879032  0.051864            0.968510  0.029126           0.853805  0.056064                   0.586415  0.013668                 0.643839  0.024291                  0.564734  0.013279                0.575209  0.016959               0.584993  0.011211                  0.422731  0.086620                0.612810  0.081997                 0.362874  0.088408               0.428098  0.087878              0.388797  0.083699
refine_ml50_do035                0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175

Interpretation guide for `NDCG@5`:
- compare mean/std of `best_valid_full_ndcg@5` and `best_test_full_ndcg@5`
- then check whether `@10`, sampled, and MRR show a similar trend