# SASRec Delta-Start Time-Aware BPI2012 Colab Train Combo (`refine_ml50_do035` baseline)

Colab notebook for comparing two `delta_start_seconds` time-aware variants on top of `refine_ml50_do035`:
- `delta_start_seconds + 9-bucket`
- `delta_start_seconds + continuous`

Both are evaluated under `NDCG@10` and `NDCG@5` model-selection criteria.

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
BUCKET_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10'
BUCKET_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5'
CONT_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10'
CONT_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('BUCKET_NDCG10_OUTPUT_DIR:', BUCKET_NDCG10_OUTPUT_DIR)
print('BUCKET_NDCG5_OUTPUT_DIR:', BUCKET_NDCG5_OUTPUT_DIR)
print('CONT_NDCG10_OUTPUT_DIR:', CONT_NDCG10_OUTPUT_DIR)
print('CONT_NDCG5_OUTPUT_DIR:', CONT_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
BUCKET_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10
BUCKET_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5
CONT_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10
CONT_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$BUCKET_NDCG10_OUTPUT_DIR"
!mkdir -p "$BUCKET_NDCG5_OUTPUT_DIR"
!mkdir -p "$CONT_NDCG10_OUTPUT_DIR"
!mkdir -p "$CONT_NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `refine_ml50_do035`
- `hidden_units=50, num_blocks=2, num_heads=1, maxlen=50, lr=0.001, dropout=0.35`
- seeds: `42`, `2024`, `7`

Time-aware variants:
- `delta_start_seconds + 9-bucket`
- `delta_start_seconds + continuous`

## Check baseline runs

In [10]:
from pathlib import Path

baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]

for label, output_dir in [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR)),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR)),
]:
    print('=' * 80)
    print(label)
    for run_name in baseline_runs:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS
================================================================================
Baseline NDCG@5
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS

## Check planned new runs

In [11]:
planned_bucket_ndcg10 = [
    'timeaware_dstart_refine_ml50_do035_b9_s42',
    'timeaware_dstart_refine_ml50_do035_b9_s2024',
    'timeaware_dstart_refine_ml50_do035_b9_s7',
]
planned_bucket_ndcg5 = [
    'timeaware_dstart_refine_ml50_do035_b9_s42',
    'timeaware_dstart_refine_ml50_do035_b9_s2024',
    'timeaware_dstart_refine_ml50_do035_b9_s7',
]
planned_cont_ndcg10 = [
    'timeaware_dstart_conti_refine_ml50_do035_s42',
    'timeaware_dstart_conti_refine_ml50_do035_s2024',
    'timeaware_dstart_conti_refine_ml50_do035_s7',
]
planned_cont_ndcg5 = [
    'timeaware_dstart_conti_refine_ml50_do035_s42',
    'timeaware_dstart_conti_refine_ml50_do035_s2024',
    'timeaware_dstart_conti_refine_ml50_do035_s7',
]

for label, output_dir, run_names in [
    ('Bucket NDCG@10', Path(BUCKET_NDCG10_OUTPUT_DIR), planned_bucket_ndcg10),
    ('Bucket NDCG@5', Path(BUCKET_NDCG5_OUTPUT_DIR), planned_bucket_ndcg5),
    ('Continuous NDCG@10', Path(CONT_NDCG10_OUTPUT_DIR), planned_cont_ndcg10),
    ('Continuous NDCG@5', Path(CONT_NDCG5_OUTPUT_DIR), planned_cont_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Bucket NDCG@10
timeaware_dstart_refine_ml50_do035_b9_s42 OK
timeaware_dstart_refine_ml50_do035_b9_s2024 OK
timeaware_dstart_refine_ml50_do035_b9_s7 OK
================================================================================
Bucket NDCG@5
timeaware_dstart_refine_ml50_do035_b9_s42 OK
timeaware_dstart_refine_ml50_do035_b9_s2024 OK
timeaware_dstart_refine_ml50_do035_b9_s7 OK
================================================================================
Continuous NDCG@10
timeaware_dstart_conti_refine_ml50_do035_s42 OK
timeaware_dstart_conti_refine_ml50_do035_s2024 OK
timeaware_dstart_conti_refine_ml50_do035_s7 OK
================================================================================
Continuous NDCG@5
timeaware_dstart_conti_refine_ml50_do035_s42 OK
timeaware_dstart_conti_refine_ml50_do035_s2024 OK
timeaware_dstart_conti_refine_ml50_do035_s7 OK

## Train `delta_start + 9-bucket` for `NDCG@10`

### timeaware_dstart_refine_ml50_do035_b9_s42

In [12]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_refine_ml50_do035_b9_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42
epoch=1, loss=0.5836
epoch=2, loss=0.2676
epoch=3, loss=0.2017
epoch=4, loss=0.1652
epoch=5, loss=0.1407
valid [full], NDCG@5: 0.6477, HR@5: 0.7565, NDCG@10: 0.6925, HR@10: 0.8994, MRR: 0.6391
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5685, NDCG@10: 0.5716, HR@10: 0.6080, MRR: 0.5732
test [full], NDCG@5: 0.5774, HR@5: 0.7196, NDCG@10: 0.6227, HR@10: 0.8644, MRR: 0.5576
test [sampled], NDCG@5: 0.1890, HR@5: 0.1942, NDCG@10: 0.2341, HR@10: 0.3400, MRR: 0.2338
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=6, loss=0.1247
epoch=7, loss=0.1155
epoch=8, loss=0.1074
epoch=9, loss=0.1023
epoch=10, loss=0.1004
valid [full], NDCG@5: 0.6523, HR@5: 0.7570, NDCG@10: 0.7205, HR@10: 0.9670, MRR: 0.6492
valid [sampled], NDCG@5: 0.5616, HR@5: 0.5745, NDCG@10: 0.5788, HR@10: 0.6285, MRR: 0.5768
test [full], NDCG@5: 0.6401, HR@5: 0.9016, NDCG@10: 0.6716, HR@10: 0.9985, MRR: 0.5666
test [sampled], NDCG@5: 0.1508, HR@5: 0.1619, NDCG@10: 0.1766, HR@10: 0.2447, MRR: 0.1985
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=11, loss=0.0970
epoch=12, loss=0.0944
epoch=13, loss=0.0912
epoch=14, loss=0.0906
epoch=15, loss=0.0898
valid [full], NDCG@5: 0.6818, HR@5: 0.8205, NDCG@10: 0.7286, HR@10: 0.9644, MRR: 0.6594
valid [sampled], NDCG@5: 0.5730, HR@5: 0.5844, NDCG@10: 0.5886, HR@10: 0.6330, MRR: 0.5890
test [full], NDCG@5: 0.6492, HR@5: 0.9585, NDCG@10: 0.6630, HR@10: 1.0000, MRR: 0.5499
test [sampled], NDCG@5: 0.1251, HR@5: 0.1355, NDCG@10: 0.1819, HR@10: 0.3183, MRR: 0.1811
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=16, loss=0.0867
epoch=17, loss=0.0840
epoch=18, loss=0.0839
epoch=19, loss=0.0828
epoch=20, loss=0.0825
valid [full], NDCG@5: 0.6534, HR@5: 0.7497, NDCG@10: 0.7214, HR@10: 0.9574, MRR: 0.6538
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5723, NDCG@10: 0.5788, HR@10: 0.6261, MRR: 0.5771
test [full], NDCG@5: 0.7403, HR@5: 0.9459, NDCG@10: 0.7577, HR@10: 0.9999, MRR: 0.6777
test [sampled], NDCG@5: 0.2137, HR@5: 0.2736, NDCG@10: 0.2792, HR@10: 0.4778, MRR: 0.2474
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0794
epoch=22, loss=0.0802
epoch=23, loss=0.0803
epoch=24, loss=0.0796
epoch=25, loss=0.0797
valid [full], NDCG@5: 0.6879, HR@5: 0.8308, NDCG@10: 0.7213, HR@10: 0.9360, MRR: 0.6605
valid [sampled], NDCG@5: 0.5598, HR@5: 0.5697, NDCG@10: 0.5779, HR@10: 0.6266, MRR: 0.5768
test [full], NDCG@5: 0.7021, HR@5: 0.9640, NDCG@10: 0.7134, HR@10: 0.9999, MRR: 0.6176
test [sampled], NDCG@5: 0.1664, HR@5: 0.1776, NDCG@10: 0.2149, HR@10: 0.3336, MRR: 0.2208
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0773
epoch=27, loss=0.0796
epoch=28, loss=0.0774
epoch=29, loss=0.0786
epoch=30, loss=0.0776
valid [full], NDCG@5: 0.6805, HR@5: 0.8109, NDCG@10: 0.7229, HR@10: 0.9413, MRR: 0.6608
valid [sampled], NDCG@5: 0.5646, HR@5: 0.5751, NDCG@10: 0.5811, HR@10: 0.6264, MRR: 0.5805
test [full], NDCG@5: 0.7211, HR@5: 0.9607, NDCG@10: 0.7333, HR@10: 1.0000, MRR: 0.6449
test [sampled], NDCG@5: 0.1925, HR@5: 0.2193, NDCG@10: 0.2402, HR@10: 0.3705, MRR: 0.2389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0770
epoch=32, loss=0.0761
epoch=33, loss=0.0769
epoch=34, loss=0.0758
epoch=35, loss=0.0745
valid [full], NDCG@5: 0.6681, HR@5: 0.8271, NDCG@10: 0.7045, HR@10: 0.9413, MRR: 0.6359
valid [sampled], NDCG@5: 0.5321, HR@5: 0.5403, NDCG@10: 0.5502, HR@10: 0.5974, MRR: 0.5517
test [full], NDCG@5: 0.7678, HR@5: 0.9624, NDCG@10: 0.7795, HR@10: 0.9999, MRR: 0.7058
test [sampled], NDCG@5: 0.2467, HR@5: 0.2633, NDCG@10: 0.3066, HR@10: 0.4555, MRR: 0.2978
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0757
epoch=37, loss=0.0741
epoch=38, loss=0.0739
epoch=39, loss=0.0748
epoch=40, loss=0.0759
valid [full], NDCG@5: 0.6482, HR@5: 0.8091, NDCG@10: 0.6914, HR@10: 0.9433, MRR: 0.6188
valid [sampled], NDCG@5: 0.5113, HR@5: 0.5166, NDCG@10: 0.5231, HR@10: 0.5540, MRR: 0.5302
test [full], NDCG@5: 0.7514, HR@5: 0.9619, NDCG@10: 0.7631, HR@10: 1.0000, MRR: 0.6858
test [sampled], NDCG@5: 0.2527, HR@5: 0.2668, NDCG@10: 0.2910, HR@10: 0.3891, MRR: 0.2992
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0748
epoch=42, loss=0.0749
epoch=43, loss=0.0758
epoch=44, loss=0.0737
epoch=45, loss=0.0743
valid [full], NDCG@5: 0.6514, HR@5: 0.8015, NDCG@10: 0.6963, HR@10: 0.9438, MRR: 0.6245
valid [sampled], NDCG@5: 0.5037, HR@5: 0.5129, NDCG@10: 0.5217, HR@10: 0.5700, MRR: 0.5238
test [full], NDCG@5: 0.8539, HR@5: 0.9639, NDCG@10: 0.8653, HR@10: 1.0000, MRR: 0.8210
test [sampled], NDCG@5: 0.3230, HR@5: 0.3850, NDCG@10: 0.3879, HR@10: 0.5858, MRR: 0.3544
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0723
epoch=47, loss=0.0727
epoch=48, loss=0.0724
epoch=49, loss=0.0727
epoch=50, loss=0.0734
valid [full], NDCG@5: 0.6405, HR@5: 0.7729, NDCG@10: 0.6946, HR@10: 0.9401, MRR: 0.6244
valid [sampled], NDCG@5: 0.5111, HR@5: 0.5206, NDCG@10: 0.5239, HR@10: 0.5603, MRR: 0.5284
test [full], NDCG@5: 0.7793, HR@5: 0.9532, NDCG@10: 0.7940, HR@10: 1.0000, MRR: 0.7258
test [sampled], NDCG@5: 0.2835, HR@5: 0.3059, NDCG@10: 0.3431, HR@10: 0.4963, MRR: 0.3292
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_last.pth

### timeaware_dstart_refine_ml50_do035_b9_s2024

In [13]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_refine_ml50_do035_b9_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024
epoch=1, loss=0.6049
epoch=2, loss=0.2704
epoch=3, loss=0.1983
epoch=4, loss=0.1600
epoch=5, loss=0.1394
valid [full], NDCG@5: 0.7006, HR@5: 0.8868, NDCG@10: 0.7361, HR@10: 0.9909, MRR: 0.6582
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5649, NDCG@10: 0.5684, HR@10: 0.5942, MRR: 0.5768
test [full], NDCG@5: 0.7452, HR@5: 0.8726, NDCG@10: 0.7861, HR@10: 1.0000, MRR: 0.7202
test [sampled], NDCG@5: 0.2070, HR@5: 0.2670, NDCG@10: 0.2638, HR@10: 0.4422, MRR: 0.2392
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1229
epoch=7, loss=0.1140
epoch=8, loss=0.1088
epoch=9, loss=0.1015
epoch=10, loss=0.0992
valid [full], NDCG@5: 0.6798, HR@5: 0.8386, NDCG@10: 0.7226, HR@10: 0.9715, MRR: 0.6494
valid [sampled], NDCG@5: 0.5432, HR@5: 0.5531, NDCG@10: 0.5560, HR@10: 0.5930, MRR: 0.5597
test [full], NDCG@5: 0.8178, HR@5: 0.9261, NDCG@10: 0.8400, HR@10: 0.9999, MRR: 0.7898
test [sampled], NDCG@5: 0.2053, HR@5: 0.2921, NDCG@10: 0.2857, HR@10: 0.5407, MRR: 0.2355
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0949
epoch=12, loss=0.0921
epoch=13, loss=0.0897
epoch=14, loss=0.0887
epoch=15, loss=0.0877
valid [full], NDCG@5: 0.6860, HR@5: 0.8391, NDCG@10: 0.7236, HR@10: 0.9594, MRR: 0.6555
valid [sampled], NDCG@5: 0.5656, HR@5: 0.5770, NDCG@10: 0.5769, HR@10: 0.6119, MRR: 0.5799
test [full], NDCG@5: 0.7739, HR@5: 0.9459, NDCG@10: 0.7900, HR@10: 1.0000, MRR: 0.7208
test [sampled], NDCG@5: 0.1843, HR@5: 0.2127, NDCG@10: 0.2606, HR@10: 0.4557, MRR: 0.2376
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0844
epoch=17, loss=0.0840
epoch=18, loss=0.0837
epoch=19, loss=0.0834
epoch=20, loss=0.0824
valid [full], NDCG@5: 0.6904, HR@5: 0.8161, NDCG@10: 0.7302, HR@10: 0.9386, MRR: 0.6704
valid [sampled], NDCG@5: 0.5571, HR@5: 0.5625, NDCG@10: 0.5756, HR@10: 0.6213, MRR: 0.5780
test [full], NDCG@5: 0.8554, HR@5: 0.9423, NDCG@10: 0.8731, HR@10: 0.9999, MRR: 0.8328
test [sampled], NDCG@5: 0.3044, HR@5: 0.3692, NDCG@10: 0.3728, HR@10: 0.5813, MRR: 0.3352
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0802
epoch=22, loss=0.0791
epoch=23, loss=0.0786
epoch=24, loss=0.0808
epoch=25, loss=0.0789
valid [full], NDCG@5: 0.7075, HR@5: 0.8476, NDCG@10: 0.7363, HR@10: 0.9398, MRR: 0.6776
valid [sampled], NDCG@5: 0.5635, HR@5: 0.5779, NDCG@10: 0.5844, HR@10: 0.6435, MRR: 0.5820
test [full], NDCG@5: 0.8009, HR@5: 0.9459, NDCG@10: 0.8174, HR@10: 0.9999, MRR: 0.7565
test [sampled], NDCG@5: 0.2257, HR@5: 0.2618, NDCG@10: 0.3056, HR@10: 0.5150, MRR: 0.2749
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=26, loss=0.0767
epoch=27, loss=0.0766
epoch=28, loss=0.0769
epoch=29, loss=0.0797
epoch=30, loss=0.0763
valid [full], NDCG@5: 0.6677, HR@5: 0.7796, NDCG@10: 0.7209, HR@10: 0.9437, MRR: 0.6575
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5649, NDCG@10: 0.5709, HR@10: 0.6140, MRR: 0.5717
test [full], NDCG@5: 0.7876, HR@5: 0.9358, NDCG@10: 0.8073, HR@10: 0.9993, MRR: 0.7445
test [sampled], NDCG@5: 0.2506, HR@5: 0.2651, NDCG@10: 0.3146, HR@10: 0.4696, MRR: 0.3021
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0763
epoch=32, loss=0.0761
epoch=33, loss=0.0749
epoch=34, loss=0.0768
epoch=35, loss=0.0750
valid [full], NDCG@5: 0.7198, HR@5: 0.8610, NDCG@10: 0.7519, HR@10: 0.9651, MRR: 0.6880
valid [sampled], NDCG@5: 0.5659, HR@5: 0.5822, NDCG@10: 0.5977, HR@10: 0.6831, MRR: 0.5874
test [full], NDCG@5: 0.8300, HR@5: 0.9427, NDCG@10: 0.8473, HR@10: 0.9999, MRR: 0.7971
test [sampled], NDCG@5: 0.3378, HR@5: 0.3812, NDCG@10: 0.3967, HR@10: 0.5657, MRR: 0.3729
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=36, loss=0.0762
epoch=37, loss=0.0745
epoch=38, loss=0.0739
epoch=39, loss=0.0742
epoch=40, loss=0.0732
valid [full], NDCG@5: 0.7216, HR@5: 0.8731, NDCG@10: 0.7530, HR@10: 0.9728, MRR: 0.6863
valid [sampled], NDCG@5: 0.5606, HR@5: 0.5761, NDCG@10: 0.5929, HR@10: 0.6781, MRR: 0.5827
test [full], NDCG@5: 0.8117, HR@5: 0.9484, NDCG@10: 0.8277, HR@10: 0.9999, MRR: 0.7703
test [sampled], NDCG@5: 0.3067, HR@5: 0.3270, NDCG@10: 0.3664, HR@10: 0.5179, MRR: 0.3526
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=41, loss=0.0747
epoch=42, loss=0.0745
epoch=43, loss=0.0740
epoch=44, loss=0.0728
epoch=45, loss=0.0730
valid [full], NDCG@5: 0.6941, HR@5: 0.8355, NDCG@10: 0.7346, HR@10: 0.9646, MRR: 0.6671
valid [sampled], NDCG@5: 0.5571, HR@5: 0.5662, NDCG@10: 0.5773, HR@10: 0.6302, MRR: 0.5770
test [full], NDCG@5: 0.8041, HR@5: 0.9469, NDCG@10: 0.8213, HR@10: 0.9999, MRR: 0.7622
test [sampled], NDCG@5: 0.2939, HR@5: 0.3091, NDCG@10: 0.3533, HR@10: 0.4994, MRR: 0.3425
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0719
epoch=47, loss=0.0738
epoch=48, loss=0.0734
epoch=49, loss=0.0715
epoch=50, loss=0.0738
valid [full], NDCG@5: 0.6616, HR@5: 0.7832, NDCG@10: 0.7165, HR@10: 0.9564, MRR: 0.6482
valid [sampled], NDCG@5: 0.5485, HR@5: 0.5516, NDCG@10: 0.5596, HR@10: 0.5871, MRR: 0.5669
test [full], NDCG@5: 0.7922, HR@5: 0.9397, NDCG@10: 0.8108, HR@10: 0.9999, MRR: 0.7489
test [sampled], NDCG@5: 0.3252, HR@5: 0.3400, NDCG@10: 0.3775, HR@10: 0.5079, MRR: 0.3692
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_last.pth

### timeaware_dstart_refine_ml50_do035_b9_s7

In [14]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_refine_ml50_do035_b9_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7
epoch=1, loss=0.5819
epoch=2, loss=0.2724
epoch=3, loss=0.2027
epoch=4, loss=0.1694
epoch=5, loss=0.1482
valid [full], NDCG@5: 0.6387, HR@5: 0.7412, NDCG@10: 0.6910, HR@10: 0.9039, MRR: 0.6356
valid [sampled], NDCG@5: 0.5609, HR@5: 0.5617, NDCG@10: 0.5681, HR@10: 0.5849, MRR: 0.5771
test [full], NDCG@5: 0.6286, HR@5: 0.8319, NDCG@10: 0.6540, HR@10: 0.9095, MRR: 0.5786
test [sampled], NDCG@5: 0.2090, HR@5: 0.2122, NDCG@10: 0.2408, HR@10: 0.3155, MRR: 0.2545
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=6, loss=0.1290
epoch=7, loss=0.1153
epoch=8, loss=0.1092
epoch=9, loss=0.1039
epoch=10, loss=0.0984
valid [full], NDCG@5: 0.6410, HR@5: 0.7417, NDCG@10: 0.7095, HR@10: 0.9503, MRR: 0.6422
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5650, NDCG@10: 0.5654, HR@10: 0.5843, MRR: 0.5724
test [full], NDCG@5: 0.6987, HR@5: 0.9548, NDCG@10: 0.7143, HR@10: 1.0000, MRR: 0.6188
test [sampled], NDCG@5: 0.1035, HR@5: 0.1127, NDCG@10: 0.1698, HR@10: 0.3265, MRR: 0.1663
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=11, loss=0.0955
epoch=12, loss=0.0937
epoch=13, loss=0.0905
epoch=14, loss=0.0870
epoch=15, loss=0.0874
valid [full], NDCG@5: 0.6908, HR@5: 0.8452, NDCG@10: 0.7250, HR@10: 0.9544, MRR: 0.6582
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5672, NDCG@10: 0.5740, HR@10: 0.6101, MRR: 0.5789
test [full], NDCG@5: 0.7366, HR@5: 0.9735, NDCG@10: 0.7458, HR@10: 1.0000, MRR: 0.6591
test [sampled], NDCG@5: 0.0898, HR@5: 0.1019, NDCG@10: 0.1693, HR@10: 0.3590, MRR: 0.1570
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=16, loss=0.0860
epoch=17, loss=0.0836
epoch=18, loss=0.0823
epoch=19, loss=0.0809
epoch=20, loss=0.0820
valid [full], NDCG@5: 0.6851, HR@5: 0.8141, NDCG@10: 0.7261, HR@10: 0.9434, MRR: 0.6635
valid [sampled], NDCG@5: 0.5625, HR@5: 0.5749, NDCG@10: 0.5838, HR@10: 0.6416, MRR: 0.5804
test [full], NDCG@5: 0.8292, HR@5: 0.9953, NDCG@10: 0.8308, HR@10: 1.0000, MRR: 0.7717
test [sampled], NDCG@5: 0.2505, HR@5: 0.2879, NDCG@10: 0.3364, HR@10: 0.5596, MRR: 0.3020
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=21, loss=0.0816
epoch=22, loss=0.0783
epoch=23, loss=0.0798
epoch=24, loss=0.0795
epoch=25, loss=0.0766
valid [full], NDCG@5: 0.7149, HR@5: 0.8596, NDCG@10: 0.7413, HR@10: 0.9460, MRR: 0.6816
valid [sampled], NDCG@5: 0.5653, HR@5: 0.5809, NDCG@10: 0.5929, HR@10: 0.6677, MRR: 0.5852
test [full], NDCG@5: 0.9468, HR@5: 0.9947, NDCG@10: 0.9486, HR@10: 1.0000, MRR: 0.9308
test [sampled], NDCG@5: 0.3887, HR@5: 0.4718, NDCG@10: 0.4675, HR@10: 0.7149, MRR: 0.4135
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=26, loss=0.0780
epoch=27, loss=0.0770
epoch=28, loss=0.0776
epoch=29, loss=0.0767
epoch=30, loss=0.0741
valid [full], NDCG@5: 0.7072, HR@5: 0.8534, NDCG@10: 0.7352, HR@10: 0.9441, MRR: 0.6746
valid [sampled], NDCG@5: 0.5581, HR@5: 0.5709, NDCG@10: 0.5791, HR@10: 0.6365, MRR: 0.5771
test [full], NDCG@5: 0.8686, HR@5: 0.9672, NDCG@10: 0.8801, HR@10: 1.0000, MRR: 0.8401
test [sampled], NDCG@5: 0.3337, HR@5: 0.4057, NDCG@10: 0.3949, HR@10: 0.5942, MRR: 0.3587
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0760
epoch=32, loss=0.0756
epoch=33, loss=0.0751
epoch=34, loss=0.0743
epoch=35, loss=0.0755
valid [full], NDCG@5: 0.7040, HR@5: 0.8420, NDCG@10: 0.7354, HR@10: 0.9432, MRR: 0.6751
valid [sampled], NDCG@5: 0.5597, HR@5: 0.5747, NDCG@10: 0.5890, HR@10: 0.6664, MRR: 0.5799
test [full], NDCG@5: 0.9114, HR@5: 0.9953, NDCG@10: 0.9130, HR@10: 1.0000, MRR: 0.8835
test [sampled], NDCG@5: 0.3650, HR@5: 0.4397, NDCG@10: 0.4357, HR@10: 0.6582, MRR: 0.3912
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0746
epoch=37, loss=0.0748
epoch=38, loss=0.0738
epoch=39, loss=0.0745
epoch=40, loss=0.0740
valid [full], NDCG@5: 0.7176, HR@5: 0.8657, NDCG@10: 0.7451, HR@10: 0.9577, MRR: 0.6825
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5726, NDCG@10: 0.5902, HR@10: 0.6718, MRR: 0.5807
test [full], NDCG@5: 0.9137, HR@5: 0.9993, NDCG@10: 0.9139, HR@10: 1.0000, MRR: 0.8847
test [sampled], NDCG@5: 0.3596, HR@5: 0.4240, NDCG@10: 0.4308, HR@10: 0.6448, MRR: 0.3908
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=41, loss=0.0767
epoch=42, loss=0.0726
epoch=43, loss=0.0741
epoch=44, loss=0.0725
epoch=45, loss=0.0729
valid [full], NDCG@5: 0.7187, HR@5: 0.8635, NDCG@10: 0.7446, HR@10: 0.9482, MRR: 0.6845
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5787, NDCG@10: 0.5939, HR@10: 0.6738, MRR: 0.5843
test [full], NDCG@5: 0.9089, HR@5: 0.9928, NDCG@10: 0.9114, HR@10: 1.0000, MRR: 0.8814
test [sampled], NDCG@5: 0.3416, HR@5: 0.4135, NDCG@10: 0.4121, HR@10: 0.6314, MRR: 0.3698
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0726
epoch=47, loss=0.0723
epoch=48, loss=0.0722
epoch=49, loss=0.0724
epoch=50, loss=0.0726
valid [full], NDCG@5: 0.7184, HR@5: 0.8610, NDCG@10: 0.7449, HR@10: 0.9473, MRR: 0.6852
valid [sampled], NDCG@5: 0.5700, HR@5: 0.5867, NDCG@10: 0.6013, HR@10: 0.6859, MRR: 0.5901
test [full], NDCG@5: 0.9151, HR@5: 0.9973, NDCG@10: 0.9160, HR@10: 1.0000, MRR: 0.8873
test [sampled], NDCG@5: 0.3488, HR@5: 0.4226, NDCG@10: 0.4203, HR@10: 0.6435, MRR: 0.3763
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_last.pth

## Train `delta_start + continuous` for `NDCG@10`

### timeaware_dstart_conti_refine_ml50_do035_s42

In [15]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_conti_refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42
epoch=1, loss=0.6435
epoch=2, loss=0.3108
epoch=3, loss=0.2256
epoch=4, loss=0.1818
epoch=5, loss=0.1542
valid [full], NDCG@5: 0.5792, HR@5: 0.6165, NDCG@10: 0.6660, HR@10: 0.8930, MRR: 0.6096
valid [sampled], NDCG@5: 0.5436, HR@5: 0.5451, NDCG@10: 0.5508, HR@10: 0.5682, MRR: 0.5565
test [full], NDCG@5: 0.5982, HR@5: 0.7511, NDCG@10: 0.6383, HR@10: 0.8839, MRR: 0.5684
test [sampled], NDCG@5: 0.1847, HR@5: 0.1933, NDCG@10: 0.2183, HR@10: 0.3020, MRR: 0.2273
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1365
epoch=7, loss=0.1258
epoch=8, loss=0.1144
epoch=9, loss=0.1081
epoch=10, loss=0.1042
valid [full], NDCG@5: 0.6397, HR@5: 0.7302, NDCG@10: 0.7125, HR@10: 0.9540, MRR: 0.6444
valid [sampled], NDCG@5: 0.5641, HR@5: 0.5784, NDCG@10: 0.5774, HR@10: 0.6194, MRR: 0.5770
test [full], NDCG@5: 0.5922, HR@5: 0.8665, NDCG@10: 0.6380, HR@10: 1.0000, MRR: 0.5207
test [sampled], NDCG@5: 0.1646, HR@5: 0.1789, NDCG@10: 0.2092, HR@10: 0.3221, MRR: 0.2104
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=0.1007
epoch=12, loss=0.0971
epoch=13, loss=0.0941
epoch=14, loss=0.0939
epoch=15, loss=0.0920
valid [full], NDCG@5: 0.7089, HR@5: 0.8777, NDCG@10: 0.7379, HR@10: 0.9712, MRR: 0.6685
valid [sampled], NDCG@5: 0.5786, HR@5: 0.5911, NDCG@10: 0.5962, HR@10: 0.6463, MRR: 0.5955
test [full], NDCG@5: 0.6925, HR@5: 0.9681, NDCG@10: 0.7033, HR@10: 1.0000, MRR: 0.6044
test [sampled], NDCG@5: 0.1750, HR@5: 0.2123, NDCG@10: 0.2342, HR@10: 0.3987, MRR: 0.2174
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0900
epoch=17, loss=0.0859
epoch=18, loss=0.0870
epoch=19, loss=0.0857
epoch=20, loss=0.0840
valid [full], NDCG@5: 0.6500, HR@5: 0.8363, NDCG@10: 0.6934, HR@10: 0.9704, MRR: 0.6101
valid [sampled], NDCG@5: 0.4740, HR@5: 0.4834, NDCG@10: 0.4914, HR@10: 0.5383, MRR: 0.4962
test [full], NDCG@5: 0.7014, HR@5: 0.9548, NDCG@10: 0.7157, HR@10: 1.0000, MRR: 0.6220
test [sampled], NDCG@5: 0.1694, HR@5: 0.2230, NDCG@10: 0.2301, HR@10: 0.4124, MRR: 0.2061
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0824
epoch=22, loss=0.0831
epoch=23, loss=0.0827
epoch=24, loss=0.0805
epoch=25, loss=0.0806
valid [full], NDCG@5: 0.6793, HR@5: 0.8129, NDCG@10: 0.7268, HR@10: 0.9604, MRR: 0.6589
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5629, NDCG@10: 0.5701, HR@10: 0.6112, MRR: 0.5726
test [full], NDCG@5: 0.7134, HR@5: 0.9692, NDCG@10: 0.7236, HR@10: 1.0000, MRR: 0.6298
test [sampled], NDCG@5: 0.2004, HR@5: 0.2200, NDCG@10: 0.2707, HR@10: 0.4444, MRR: 0.2525
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0787
epoch=27, loss=0.0819
epoch=28, loss=0.0794
epoch=29, loss=0.0804
epoch=30, loss=0.0797
valid [full], NDCG@5: 0.6871, HR@5: 0.8286, NDCG@10: 0.7326, HR@10: 0.9727, MRR: 0.6623
valid [sampled], NDCG@5: 0.5621, HR@5: 0.5690, NDCG@10: 0.5742, HR@10: 0.6066, MRR: 0.5795
test [full], NDCG@5: 0.7807, HR@5: 0.9585, NDCG@10: 0.7934, HR@10: 1.0000, MRR: 0.7246
test [sampled], NDCG@5: 0.2415, HR@5: 0.2859, NDCG@10: 0.3185, HR@10: 0.5285, MRR: 0.2862
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0785
epoch=32, loss=0.0783
epoch=33, loss=0.0796
epoch=34, loss=0.0778
epoch=35, loss=0.0767
valid [full], NDCG@5: 0.6551, HR@5: 0.8604, NDCG@10: 0.6909, HR@10: 0.9739, MRR: 0.6046
valid [sampled], NDCG@5: 0.4631, HR@5: 0.4709, NDCG@10: 0.4809, HR@10: 0.5271, MRR: 0.4880
test [full], NDCG@5: 0.7717, HR@5: 0.9478, NDCG@10: 0.7879, HR@10: 1.0000, MRR: 0.7179
test [sampled], NDCG@5: 0.2465, HR@5: 0.3250, NDCG@10: 0.3207, HR@10: 0.5544, MRR: 0.2753
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0772
epoch=37, loss=0.0757
epoch=38, loss=0.0755
epoch=39, loss=0.0763
epoch=40, loss=0.0766
valid [full], NDCG@5: 0.6546, HR@5: 0.8614, NDCG@10: 0.6871, HR@10: 0.9670, MRR: 0.6029
valid [sampled], NDCG@5: 0.4637, HR@5: 0.4706, NDCG@10: 0.4794, HR@10: 0.5200, MRR: 0.4874
test [full], NDCG@5: 0.7297, HR@5: 0.9474, NDCG@10: 0.7457, HR@10: 1.0000, MRR: 0.6607
test [sampled], NDCG@5: 0.2015, HR@5: 0.2344, NDCG@10: 0.2834, HR@10: 0.4942, MRR: 0.2538
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0762
epoch=42, loss=0.0770
epoch=43, loss=0.0768
epoch=44, loss=0.0755
epoch=45, loss=0.0763
valid [full], NDCG@5: 0.6369, HR@5: 0.8327, NDCG@10: 0.6835, HR@10: 0.9764, MRR: 0.5953
valid [sampled], NDCG@5: 0.4617, HR@5: 0.4721, NDCG@10: 0.4771, HR@10: 0.5205, MRR: 0.4828
test [full], NDCG@5: 0.8192, HR@5: 0.9452, NDCG@10: 0.8369, HR@10: 1.0000, MRR: 0.7842
test [sampled], NDCG@5: 0.2497, HR@5: 0.3352, NDCG@10: 0.3393, HR@10: 0.6117, MRR: 0.2805
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0735
epoch=47, loss=0.0744
epoch=48, loss=0.0738
epoch=49, loss=0.0744
epoch=50, loss=0.0750
valid [full], NDCG@5: 0.6744, HR@5: 0.8626, NDCG@10: 0.7097, HR@10: 0.9754, MRR: 0.6283
valid [sampled], NDCG@5: 0.4659, HR@5: 0.4769, NDCG@10: 0.4931, HR@10: 0.5632, MRR: 0.4925
test [full], NDCG@5: 0.7952, HR@5: 0.9457, NDCG@10: 0.8116, HR@10: 1.0000, MRR: 0.7493
test [sampled], NDCG@5: 0.2445, HR@5: 0.2939, NDCG@10: 0.3196, HR@10: 0.5300, MRR: 0.2868
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_last.pth

### timeaware_dstart_conti_refine_ml50_do035_s2024

In [16]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_conti_refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024
epoch=1, loss=0.6747
epoch=2, loss=0.3270
epoch=3, loss=0.2288
epoch=4, loss=0.1837
epoch=5, loss=0.1540
valid [full], NDCG@5: 0.6732, HR@5: 0.7996, NDCG@10: 0.7262, HR@10: 0.9722, MRR: 0.6549
valid [sampled], NDCG@5: 0.5662, HR@5: 0.5775, NDCG@10: 0.5785, HR@10: 0.6155, MRR: 0.5806
test [full], NDCG@5: 0.7545, HR@5: 0.8810, NDCG@10: 0.7927, HR@10: 1.0000, MRR: 0.7281
test [sampled], NDCG@5: 0.1394, HR@5: 0.2107, NDCG@10: 0.2161, HR@10: 0.4479, MRR: 0.1762
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1315
epoch=7, loss=0.1204
epoch=8, loss=0.1133
epoch=9, loss=0.1052
epoch=10, loss=0.1022
valid [full], NDCG@5: 0.7007, HR@5: 0.8716, NDCG@10: 0.7324, HR@10: 0.9711, MRR: 0.6613
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5631, NDCG@10: 0.5670, HR@10: 0.6011, MRR: 0.5731
test [full], NDCG@5: 0.7613, HR@5: 0.9204, NDCG@10: 0.7854, HR@10: 1.0000, MRR: 0.7164
test [sampled], NDCG@5: 0.1394, HR@5: 0.2215, NDCG@10: 0.2206, HR@10: 0.4732, MRR: 0.1726
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=11, loss=0.0982
epoch=12, loss=0.0944
epoch=13, loss=0.0918
epoch=14, loss=0.0910
epoch=15, loss=0.0906
valid [full], NDCG@5: 0.6970, HR@5: 0.8601, NDCG@10: 0.7320, HR@10: 0.9702, MRR: 0.6617
valid [sampled], NDCG@5: 0.5672, HR@5: 0.5791, NDCG@10: 0.5789, HR@10: 0.6149, MRR: 0.5827
test [full], NDCG@5: 0.7446, HR@5: 0.9341, NDCG@10: 0.7651, HR@10: 1.0000, MRR: 0.6879
test [sampled], NDCG@5: 0.1748, HR@5: 0.2090, NDCG@10: 0.2316, HR@10: 0.3885, MRR: 0.2211
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0873
epoch=17, loss=0.0862
epoch=18, loss=0.0864
epoch=19, loss=0.0856
epoch=20, loss=0.0851
valid [full], NDCG@5: 0.6699, HR@5: 0.7938, NDCG@10: 0.7191, HR@10: 0.9458, MRR: 0.6547
valid [sampled], NDCG@5: 0.5560, HR@5: 0.5600, NDCG@10: 0.5671, HR@10: 0.5953, MRR: 0.5736
test [full], NDCG@5: 0.8249, HR@5: 0.9348, NDCG@10: 0.8445, HR@10: 0.9999, MRR: 0.7950
test [sampled], NDCG@5: 0.2799, HR@5: 0.3405, NDCG@10: 0.3375, HR@10: 0.5179, MRR: 0.3101
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0830
epoch=22, loss=0.0819
epoch=23, loss=0.0809
epoch=24, loss=0.0827
epoch=25, loss=0.0812
valid [full], NDCG@5: 0.6966, HR@5: 0.8490, NDCG@10: 0.7261, HR@10: 0.9431, MRR: 0.6632
valid [sampled], NDCG@5: 0.5508, HR@5: 0.5574, NDCG@10: 0.5680, HR@10: 0.6119, MRR: 0.5717
test [full], NDCG@5: 0.8160, HR@5: 0.9345, NDCG@10: 0.8360, HR@10: 1.0000, MRR: 0.7836
test [sampled], NDCG@5: 0.2336, HR@5: 0.3111, NDCG@10: 0.3011, HR@10: 0.5187, MRR: 0.2614
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0786
epoch=27, loss=0.0781
epoch=28, loss=0.0785
epoch=29, loss=0.0819
epoch=30, loss=0.0775
valid [full], NDCG@5: 0.6931, HR@5: 0.8539, NDCG@10: 0.7207, HR@10: 0.9418, MRR: 0.6568
valid [sampled], NDCG@5: 0.5529, HR@5: 0.5584, NDCG@10: 0.5639, HR@10: 0.5933, MRR: 0.5713
test [full], NDCG@5: 0.7609, HR@5: 0.9449, NDCG@10: 0.7774, HR@10: 1.0000, MRR: 0.7048
test [sampled], NDCG@5: 0.2869, HR@5: 0.3091, NDCG@10: 0.3333, HR@10: 0.4563, MRR: 0.3258
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0781
epoch=32, loss=0.0777
epoch=33, loss=0.0761
epoch=34, loss=0.0781
epoch=35, loss=0.0762
valid [full], NDCG@5: 0.6918, HR@5: 0.8458, NDCG@10: 0.7229, HR@10: 0.9459, MRR: 0.6586
valid [sampled], NDCG@5: 0.5555, HR@5: 0.5599, NDCG@10: 0.5695, HR@10: 0.6045, MRR: 0.5759
test [full], NDCG@5: 0.8228, HR@5: 0.9438, NDCG@10: 0.8401, HR@10: 0.9999, MRR: 0.7891
test [sampled], NDCG@5: 0.3303, HR@5: 0.3801, NDCG@10: 0.3786, HR@10: 0.5296, MRR: 0.3584
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0765
epoch=37, loss=0.0757
epoch=38, loss=0.0752
epoch=39, loss=0.0763
epoch=40, loss=0.0742
valid [full], NDCG@5: 0.6873, HR@5: 0.8703, NDCG@10: 0.7208, HR@10: 0.9759, MRR: 0.6441
valid [sampled], NDCG@5: 0.5263, HR@5: 0.5321, NDCG@10: 0.5403, HR@10: 0.5769, MRR: 0.5479
test [full], NDCG@5: 0.7980, HR@5: 0.9536, NDCG@10: 0.8126, HR@10: 1.0000, MRR: 0.7509
test [sampled], NDCG@5: 0.3155, HR@5: 0.3453, NDCG@10: 0.3695, HR@10: 0.5173, MRR: 0.3545
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0757
epoch=42, loss=0.0757
epoch=43, loss=0.0756
epoch=44, loss=0.0739
epoch=45, loss=0.0739
valid [full], NDCG@5: 0.6642, HR@5: 0.8363, NDCG@10: 0.7056, HR@10: 0.9682, MRR: 0.6283
valid [sampled], NDCG@5: 0.5163, HR@5: 0.5196, NDCG@10: 0.5263, HR@10: 0.5517, MRR: 0.5368
test [full], NDCG@5: 0.8310, HR@5: 0.9730, NDCG@10: 0.8403, HR@10: 1.0000, MRR: 0.7878
test [sampled], NDCG@5: 0.3670, HR@5: 0.3955, NDCG@10: 0.4160, HR@10: 0.5505, MRR: 0.4028
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0725
epoch=47, loss=0.0747
epoch=48, loss=0.0741
epoch=49, loss=0.0726
epoch=50, loss=0.0751
valid [full], NDCG@5: 0.6918, HR@5: 0.8697, NDCG@10: 0.7225, HR@10: 0.9683, MRR: 0.6489
valid [sampled], NDCG@5: 0.5274, HR@5: 0.5333, NDCG@10: 0.5408, HR@10: 0.5763, MRR: 0.5495
test [full], NDCG@5: 0.8641, HR@5: 0.9660, NDCG@10: 0.8753, HR@10: 1.0000, MRR: 0.8346
test [sampled], NDCG@5: 0.3385, HR@5: 0.4077, NDCG@10: 0.4030, HR@10: 0.6064, MRR: 0.3644
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s2024/sasrec_last.pth

### timeaware_dstart_conti_refine_ml50_do035_s7

In [17]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_conti_refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7
epoch=1, loss=0.6368
epoch=2, loss=0.3261
epoch=3, loss=0.2338
epoch=4, loss=0.1884
epoch=5, loss=0.1637
valid [full], NDCG@5: 0.6210, HR@5: 0.7248, NDCG@10: 0.6889, HR@10: 0.9404, MRR: 0.6202
valid [sampled], NDCG@5: 0.5455, HR@5: 0.5473, NDCG@10: 0.5513, HR@10: 0.5656, MRR: 0.5609
test [full], NDCG@5: 0.5974, HR@5: 0.6974, NDCG@10: 0.6735, HR@10: 0.9348, MRR: 0.5999
test [sampled], NDCG@5: 0.1973, HR@5: 0.2229, NDCG@10: 0.2381, HR@10: 0.3519, MRR: 0.2324
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1404
epoch=7, loss=0.1240
epoch=8, loss=0.1135
epoch=9, loss=0.1085
epoch=10, loss=0.1020
valid [full], NDCG@5: 0.6580, HR@5: 0.7667, NDCG@10: 0.7227, HR@10: 0.9684, MRR: 0.6521
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5676, NDCG@10: 0.5715, HR@10: 0.6066, MRR: 0.5745
test [full], NDCG@5: 0.6925, HR@5: 0.9705, NDCG@10: 0.7028, HR@10: 0.9999, MRR: 0.6037
test [sampled], NDCG@5: 0.0894, HR@5: 0.0987, NDCG@10: 0.1554, HR@10: 0.3113, MRR: 0.1522
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=0.0999
epoch=12, loss=0.0962
epoch=13, loss=0.0932
epoch=14, loss=0.0904
epoch=15, loss=0.0907
valid [full], NDCG@5: 0.6978, HR@5: 0.8227, NDCG@10: 0.7428, HR@10: 0.9651, MRR: 0.6769
valid [sampled], NDCG@5: 0.5610, HR@5: 0.5720, NDCG@10: 0.5901, HR@10: 0.6643, MRR: 0.5828
test [full], NDCG@5: 0.6663, HR@5: 0.9974, NDCG@10: 0.6672, HR@10: 0.9999, MRR: 0.5541
test [sampled], NDCG@5: 0.0765, HR@5: 0.0849, NDCG@10: 0.1382, HR@10: 0.2839, MRR: 0.1383
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=0.0899
epoch=17, loss=0.0856
epoch=18, loss=0.0850
epoch=19, loss=0.0842
epoch=20, loss=0.0851
valid [full], NDCG@5: 0.6953, HR@5: 0.8224, NDCG@10: 0.7334, HR@10: 0.9457, MRR: 0.6720
valid [sampled], NDCG@5: 0.5656, HR@5: 0.5779, NDCG@10: 0.5942, HR@10: 0.6679, MRR: 0.5856
test [full], NDCG@5: 0.8113, HR@5: 0.9962, NDCG@10: 0.8125, HR@10: 1.0000, MRR: 0.7494
test [sampled], NDCG@5: 0.1480, HR@5: 0.2274, NDCG@10: 0.2337, HR@10: 0.4934, MRR: 0.1865
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0840
epoch=22, loss=0.0804
epoch=23, loss=0.0822
epoch=24, loss=0.0822
epoch=25, loss=0.0786
valid [full], NDCG@5: 0.6993, HR@5: 0.8228, NDCG@10: 0.7404, HR@10: 0.9543, MRR: 0.6780
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5763, NDCG@10: 0.5919, HR@10: 0.6675, MRR: 0.5835
test [full], NDCG@5: 0.8298, HR@5: 0.9967, NDCG@10: 0.8308, HR@10: 0.9999, MRR: 0.7729
test [sampled], NDCG@5: 0.1385, HR@5: 0.2119, NDCG@10: 0.2270, HR@10: 0.4878, MRR: 0.1828
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0801
epoch=27, loss=0.0796
epoch=28, loss=0.0799
epoch=29, loss=0.0784
epoch=30, loss=0.0767
valid [full], NDCG@5: 0.6752, HR@5: 0.8020, NDCG@10: 0.7208, HR@10: 0.9461, MRR: 0.6557
valid [sampled], NDCG@5: 0.5226, HR@5: 0.5320, NDCG@10: 0.5510, HR@10: 0.6220, MRR: 0.5458
test [full], NDCG@5: 0.8513, HR@5: 0.9949, NDCG@10: 0.8530, HR@10: 0.9999, MRR: 0.8034
test [sampled], NDCG@5: 0.1731, HR@5: 0.2599, NDCG@10: 0.2649, HR@10: 0.5449, MRR: 0.2100
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0782
epoch=32, loss=0.0775
epoch=33, loss=0.0767
epoch=34, loss=0.0761
epoch=35, loss=0.0788
valid [full], NDCG@5: 0.6392, HR@5: 0.7536, NDCG@10: 0.6947, HR@10: 0.9289, MRR: 0.6293
valid [sampled], NDCG@5: 0.5224, HR@5: 0.5356, NDCG@10: 0.5431, HR@10: 0.5997, MRR: 0.5393
test [full], NDCG@5: 0.8853, HR@5: 0.9943, NDCG@10: 0.8872, HR@10: 0.9999, MRR: 0.8498
test [sampled], NDCG@5: 0.3555, HR@5: 0.4204, NDCG@10: 0.4158, HR@10: 0.6067, MRR: 0.3818
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0768
epoch=37, loss=0.0779
epoch=38, loss=0.0771
epoch=39, loss=0.0765
epoch=40, loss=0.0759
valid [full], NDCG@5: 0.6844, HR@5: 0.8258, NDCG@10: 0.7232, HR@10: 0.9490, MRR: 0.6570
valid [sampled], NDCG@5: 0.5289, HR@5: 0.5405, NDCG@10: 0.5560, HR@10: 0.6265, MRR: 0.5507
test [full], NDCG@5: 0.9076, HR@5: 0.9982, NDCG@10: 0.9082, HR@10: 1.0000, MRR: 0.8774
test [sampled], NDCG@5: 0.3779, HR@5: 0.4404, NDCG@10: 0.4359, HR@10: 0.6183, MRR: 0.4048
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0792
epoch=42, loss=0.0748
epoch=43, loss=0.0757
epoch=44, loss=0.0749
epoch=45, loss=0.0758
valid [full], NDCG@5: 0.6776, HR@5: 0.8104, NDCG@10: 0.7200, HR@10: 0.9468, MRR: 0.6537
valid [sampled], NDCG@5: 0.5234, HR@5: 0.5389, NDCG@10: 0.5533, HR@10: 0.6327, MRR: 0.5445
test [full], NDCG@5: 0.8844, HR@5: 0.9835, NDCG@10: 0.8902, HR@10: 1.0000, MRR: 0.8534
test [sampled], NDCG@5: 0.3825, HR@5: 0.4552, NDCG@10: 0.4426, HR@10: 0.6392, MRR: 0.4036
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0746
epoch=47, loss=0.0749
epoch=48, loss=0.0735
epoch=49, loss=0.0743
epoch=50, loss=0.0745
valid [full], NDCG@5: 0.6569, HR@5: 0.8106, NDCG@10: 0.6997, HR@10: 0.9453, MRR: 0.6273
valid [sampled], NDCG@5: 0.4908, HR@5: 0.5064, NDCG@10: 0.5184, HR@10: 0.5935, MRR: 0.5125
test [full], NDCG@5: 0.8696, HR@5: 0.9578, NDCG@10: 0.8844, HR@10: 1.0000, MRR: 0.8463
test [sampled], NDCG@5: 0.3300, HR@5: 0.4133, NDCG@10: 0.3951, HR@10: 0.6128, MRR: 0.3510
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_last.pth

## Train `delta_start + 9-bucket` for `NDCG@5`

### timeaware_dstart_refine_ml50_do035_b9_s42

In [18]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_refine_ml50_do035_b9_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42
epoch=1, loss=0.5836
epoch=2, loss=0.2676
epoch=3, loss=0.2017
epoch=4, loss=0.1652
epoch=5, loss=0.1407
valid [full], NDCG@5: 0.6477, HR@5: 0.7565, NDCG@10: 0.6925, HR@10: 0.8994, MRR: 0.6391
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5685, NDCG@10: 0.5716, HR@10: 0.6080, MRR: 0.5732
test [full], NDCG@5: 0.5774, HR@5: 0.7196, NDCG@10: 0.6227, HR@10: 0.8644, MRR: 0.5576
test [sampled], NDCG@5: 0.1890, HR@5: 0.1942, NDCG@10: 0.2341, HR@10: 0.3400, MRR: 0.2338
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=6, loss=0.1247
epoch=7, loss=0.1155
epoch=8, loss=0.1074
epoch=9, loss=0.1023
epoch=10, loss=0.1004
valid [full], NDCG@5: 0.6523, HR@5: 0.7570, NDCG@10: 0.7205, HR@10: 0.9670, MRR: 0.6492
valid [sampled], NDCG@5: 0.5616, HR@5: 0.5745, NDCG@10: 0.5788, HR@10: 0.6285, MRR: 0.5768
test [full], NDCG@5: 0.6401, HR@5: 0.9016, NDCG@10: 0.6716, HR@10: 0.9985, MRR: 0.5666
test [sampled], NDCG@5: 0.1508, HR@5: 0.1619, NDCG@10: 0.1766, HR@10: 0.2447, MRR: 0.1985
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=11, loss=0.0970
epoch=12, loss=0.0944
epoch=13, loss=0.0912
epoch=14, loss=0.0906
epoch=15, loss=0.0898
valid [full], NDCG@5: 0.6818, HR@5: 0.8205, NDCG@10: 0.7286, HR@10: 0.9644, MRR: 0.6594
valid [sampled], NDCG@5: 0.5730, HR@5: 0.5844, NDCG@10: 0.5886, HR@10: 0.6330, MRR: 0.5890
test [full], NDCG@5: 0.6492, HR@5: 0.9585, NDCG@10: 0.6630, HR@10: 1.0000, MRR: 0.5499
test [sampled], NDCG@5: 0.1251, HR@5: 0.1355, NDCG@10: 0.1819, HR@10: 0.3183, MRR: 0.1811
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=16, loss=0.0867
epoch=17, loss=0.0840
epoch=18, loss=0.0839
epoch=19, loss=0.0828
epoch=20, loss=0.0825
valid [full], NDCG@5: 0.6534, HR@5: 0.7497, NDCG@10: 0.7214, HR@10: 0.9574, MRR: 0.6538
valid [sampled], NDCG@5: 0.5617, HR@5: 0.5723, NDCG@10: 0.5788, HR@10: 0.6261, MRR: 0.5771
test [full], NDCG@5: 0.7403, HR@5: 0.9459, NDCG@10: 0.7577, HR@10: 0.9999, MRR: 0.6777
test [sampled], NDCG@5: 0.2137, HR@5: 0.2736, NDCG@10: 0.2792, HR@10: 0.4778, MRR: 0.2474
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0794
epoch=22, loss=0.0802
epoch=23, loss=0.0803
epoch=24, loss=0.0796
epoch=25, loss=0.0797
valid [full], NDCG@5: 0.6879, HR@5: 0.8308, NDCG@10: 0.7213, HR@10: 0.9360, MRR: 0.6605
valid [sampled], NDCG@5: 0.5598, HR@5: 0.5697, NDCG@10: 0.5779, HR@10: 0.6266, MRR: 0.5768
test [full], NDCG@5: 0.7021, HR@5: 0.9640, NDCG@10: 0.7134, HR@10: 0.9999, MRR: 0.6176
test [sampled], NDCG@5: 0.1664, HR@5: 0.1776, NDCG@10: 0.2149, HR@10: 0.3336, MRR: 0.2208
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_best.pth
epoch=26, loss=0.0773
epoch=27, loss=0.0796
epoch=28, loss=0.0774
epoch=29, loss=0.0786
epoch=30, loss=0.0776
valid [full], NDCG@5: 0.6805, HR@5: 0.8109, NDCG@10: 0.7229, HR@10: 0.9413, MRR: 0.6608
valid [sampled], NDCG@5: 0.5646, HR@5: 0.5751, NDCG@10: 0.5811, HR@10: 0.6264, MRR: 0.5805
test [full], NDCG@5: 0.7211, HR@5: 0.9607, NDCG@10: 0.7333, HR@10: 1.0000, MRR: 0.6449
test [sampled], NDCG@5: 0.1925, HR@5: 0.2193, NDCG@10: 0.2402, HR@10: 0.3705, MRR: 0.2389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0770
epoch=32, loss=0.0761
epoch=33, loss=0.0769
epoch=34, loss=0.0758
epoch=35, loss=0.0745
valid [full], NDCG@5: 0.6681, HR@5: 0.8271, NDCG@10: 0.7045, HR@10: 0.9413, MRR: 0.6359
valid [sampled], NDCG@5: 0.5321, HR@5: 0.5403, NDCG@10: 0.5502, HR@10: 0.5974, MRR: 0.5517
test [full], NDCG@5: 0.7678, HR@5: 0.9624, NDCG@10: 0.7795, HR@10: 0.9999, MRR: 0.7058
test [sampled], NDCG@5: 0.2467, HR@5: 0.2633, NDCG@10: 0.3066, HR@10: 0.4555, MRR: 0.2978
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0757
epoch=37, loss=0.0741
epoch=38, loss=0.0739
epoch=39, loss=0.0748
epoch=40, loss=0.0759
valid [full], NDCG@5: 0.6482, HR@5: 0.8091, NDCG@10: 0.6914, HR@10: 0.9433, MRR: 0.6188
valid [sampled], NDCG@5: 0.5113, HR@5: 0.5166, NDCG@10: 0.5231, HR@10: 0.5540, MRR: 0.5302
test [full], NDCG@5: 0.7514, HR@5: 0.9619, NDCG@10: 0.7631, HR@10: 1.0000, MRR: 0.6858
test [sampled], NDCG@5: 0.2527, HR@5: 0.2668, NDCG@10: 0.2910, HR@10: 0.3891, MRR: 0.2992
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0748
epoch=42, loss=0.0749
epoch=43, loss=0.0758
epoch=44, loss=0.0737
epoch=45, loss=0.0743
valid [full], NDCG@5: 0.6514, HR@5: 0.8015, NDCG@10: 0.6963, HR@10: 0.9438, MRR: 0.6245
valid [sampled], NDCG@5: 0.5037, HR@5: 0.5129, NDCG@10: 0.5217, HR@10: 0.5700, MRR: 0.5238
test [full], NDCG@5: 0.8539, HR@5: 0.9639, NDCG@10: 0.8653, HR@10: 1.0000, MRR: 0.8210
test [sampled], NDCG@5: 0.3230, HR@5: 0.3850, NDCG@10: 0.3879, HR@10: 0.5858, MRR: 0.3544
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0723
epoch=47, loss=0.0727
epoch=48, loss=0.0724
epoch=49, loss=0.0727
epoch=50, loss=0.0734
valid [full], NDCG@5: 0.6405, HR@5: 0.7729, NDCG@10: 0.6946, HR@10: 0.9401, MRR: 0.6244
valid [sampled], NDCG@5: 0.5111, HR@5: 0.5206, NDCG@10: 0.5239, HR@10: 0.5603, MRR: 0.5284
test [full], NDCG@5: 0.7793, HR@5: 0.9532, NDCG@10: 0.7940, HR@10: 1.0000, MRR: 0.7258
test [sampled], NDCG@5: 0.2835, HR@5: 0.3059, NDCG@10: 0.3431, HR@10: 0.4963, MRR: 0.3292
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s42/sasrec_last.pth

### timeaware_dstart_refine_ml50_do035_b9_s2024

In [19]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_refine_ml50_do035_b9_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024
epoch=1, loss=0.6049
epoch=2, loss=0.2704
epoch=3, loss=0.1983
epoch=4, loss=0.1600
epoch=5, loss=0.1394
valid [full], NDCG@5: 0.7006, HR@5: 0.8868, NDCG@10: 0.7361, HR@10: 0.9909, MRR: 0.6582
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5649, NDCG@10: 0.5684, HR@10: 0.5942, MRR: 0.5768
test [full], NDCG@5: 0.7452, HR@5: 0.8726, NDCG@10: 0.7861, HR@10: 1.0000, MRR: 0.7202
test [sampled], NDCG@5: 0.2070, HR@5: 0.2670, NDCG@10: 0.2638, HR@10: 0.4422, MRR: 0.2392
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1229
epoch=7, loss=0.1140
epoch=8, loss=0.1088
epoch=9, loss=0.1015
epoch=10, loss=0.0992
valid [full], NDCG@5: 0.6798, HR@5: 0.8386, NDCG@10: 0.7226, HR@10: 0.9715, MRR: 0.6494
valid [sampled], NDCG@5: 0.5432, HR@5: 0.5531, NDCG@10: 0.5560, HR@10: 0.5930, MRR: 0.5597
test [full], NDCG@5: 0.8178, HR@5: 0.9261, NDCG@10: 0.8400, HR@10: 0.9999, MRR: 0.7898
test [sampled], NDCG@5: 0.2053, HR@5: 0.2921, NDCG@10: 0.2857, HR@10: 0.5407, MRR: 0.2355
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0949
epoch=12, loss=0.0921
epoch=13, loss=0.0897
epoch=14, loss=0.0887
epoch=15, loss=0.0877
valid [full], NDCG@5: 0.6860, HR@5: 0.8391, NDCG@10: 0.7236, HR@10: 0.9594, MRR: 0.6555
valid [sampled], NDCG@5: 0.5656, HR@5: 0.5770, NDCG@10: 0.5769, HR@10: 0.6119, MRR: 0.5799
test [full], NDCG@5: 0.7739, HR@5: 0.9459, NDCG@10: 0.7900, HR@10: 1.0000, MRR: 0.7208
test [sampled], NDCG@5: 0.1843, HR@5: 0.2127, NDCG@10: 0.2606, HR@10: 0.4557, MRR: 0.2376
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0844
epoch=17, loss=0.0840
epoch=18, loss=0.0837
epoch=19, loss=0.0834
epoch=20, loss=0.0824
valid [full], NDCG@5: 0.6904, HR@5: 0.8161, NDCG@10: 0.7302, HR@10: 0.9386, MRR: 0.6704
valid [sampled], NDCG@5: 0.5571, HR@5: 0.5625, NDCG@10: 0.5756, HR@10: 0.6213, MRR: 0.5780
test [full], NDCG@5: 0.8554, HR@5: 0.9423, NDCG@10: 0.8731, HR@10: 0.9999, MRR: 0.8328
test [sampled], NDCG@5: 0.3044, HR@5: 0.3692, NDCG@10: 0.3728, HR@10: 0.5813, MRR: 0.3352
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0802
epoch=22, loss=0.0791
epoch=23, loss=0.0786
epoch=24, loss=0.0808
epoch=25, loss=0.0789
valid [full], NDCG@5: 0.7075, HR@5: 0.8476, NDCG@10: 0.7363, HR@10: 0.9398, MRR: 0.6776
valid [sampled], NDCG@5: 0.5635, HR@5: 0.5779, NDCG@10: 0.5844, HR@10: 0.6435, MRR: 0.5820
test [full], NDCG@5: 0.8009, HR@5: 0.9459, NDCG@10: 0.8174, HR@10: 0.9999, MRR: 0.7565
test [sampled], NDCG@5: 0.2257, HR@5: 0.2618, NDCG@10: 0.3056, HR@10: 0.5150, MRR: 0.2749
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=26, loss=0.0767
epoch=27, loss=0.0766
epoch=28, loss=0.0769
epoch=29, loss=0.0797
epoch=30, loss=0.0763
valid [full], NDCG@5: 0.6677, HR@5: 0.7796, NDCG@10: 0.7209, HR@10: 0.9437, MRR: 0.6575
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5649, NDCG@10: 0.5709, HR@10: 0.6140, MRR: 0.5717
test [full], NDCG@5: 0.7876, HR@5: 0.9358, NDCG@10: 0.8073, HR@10: 0.9993, MRR: 0.7445
test [sampled], NDCG@5: 0.2506, HR@5: 0.2651, NDCG@10: 0.3146, HR@10: 0.4696, MRR: 0.3021
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0763
epoch=32, loss=0.0761
epoch=33, loss=0.0749
epoch=34, loss=0.0768
epoch=35, loss=0.0750
valid [full], NDCG@5: 0.7198, HR@5: 0.8610, NDCG@10: 0.7519, HR@10: 0.9651, MRR: 0.6880
valid [sampled], NDCG@5: 0.5659, HR@5: 0.5822, NDCG@10: 0.5977, HR@10: 0.6831, MRR: 0.5874
test [full], NDCG@5: 0.8300, HR@5: 0.9427, NDCG@10: 0.8473, HR@10: 0.9999, MRR: 0.7971
test [sampled], NDCG@5: 0.3378, HR@5: 0.3812, NDCG@10: 0.3967, HR@10: 0.5657, MRR: 0.3729
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=36, loss=0.0762
epoch=37, loss=0.0745
epoch=38, loss=0.0739
epoch=39, loss=0.0742
epoch=40, loss=0.0732
valid [full], NDCG@5: 0.7216, HR@5: 0.8731, NDCG@10: 0.7530, HR@10: 0.9728, MRR: 0.6863
valid [sampled], NDCG@5: 0.5606, HR@5: 0.5761, NDCG@10: 0.5929, HR@10: 0.6781, MRR: 0.5827
test [full], NDCG@5: 0.8117, HR@5: 0.9484, NDCG@10: 0.8277, HR@10: 0.9999, MRR: 0.7703
test [sampled], NDCG@5: 0.3067, HR@5: 0.3270, NDCG@10: 0.3664, HR@10: 0.5179, MRR: 0.3526
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_best.pth
epoch=41, loss=0.0747
epoch=42, loss=0.0745
epoch=43, loss=0.0740
epoch=44, loss=0.0728
epoch=45, loss=0.0730
valid [full], NDCG@5: 0.6941, HR@5: 0.8355, NDCG@10: 0.7346, HR@10: 0.9646, MRR: 0.6671
valid [sampled], NDCG@5: 0.5571, HR@5: 0.5662, NDCG@10: 0.5773, HR@10: 0.6302, MRR: 0.5770
test [full], NDCG@5: 0.8041, HR@5: 0.9469, NDCG@10: 0.8213, HR@10: 0.9999, MRR: 0.7622
test [sampled], NDCG@5: 0.2939, HR@5: 0.3091, NDCG@10: 0.3533, HR@10: 0.4994, MRR: 0.3425
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0719
epoch=47, loss=0.0738
epoch=48, loss=0.0734
epoch=49, loss=0.0715
epoch=50, loss=0.0738
valid [full], NDCG@5: 0.6616, HR@5: 0.7832, NDCG@10: 0.7165, HR@10: 0.9564, MRR: 0.6482
valid [sampled], NDCG@5: 0.5485, HR@5: 0.5516, NDCG@10: 0.5596, HR@10: 0.5871, MRR: 0.5669
test [full], NDCG@5: 0.7922, HR@5: 0.9397, NDCG@10: 0.8108, HR@10: 0.9999, MRR: 0.7489
test [sampled], NDCG@5: 0.3252, HR@5: 0.3400, NDCG@10: 0.3775, HR@10: 0.5079, MRR: 0.3692
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s2024/sasrec_last.pth

### timeaware_dstart_refine_ml50_do035_b9_s7

In [20]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_refine_ml50_do035_b9_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7
epoch=1, loss=0.5819
epoch=2, loss=0.2724
epoch=3, loss=0.2027
epoch=4, loss=0.1694
epoch=5, loss=0.1482
valid [full], NDCG@5: 0.6387, HR@5: 0.7412, NDCG@10: 0.6910, HR@10: 0.9039, MRR: 0.6356
valid [sampled], NDCG@5: 0.5609, HR@5: 0.5617, NDCG@10: 0.5681, HR@10: 0.5849, MRR: 0.5771
test [full], NDCG@5: 0.6286, HR@5: 0.8319, NDCG@10: 0.6540, HR@10: 0.9095, MRR: 0.5786
test [sampled], NDCG@5: 0.2090, HR@5: 0.2122, NDCG@10: 0.2408, HR@10: 0.3155, MRR: 0.2545
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=6, loss=0.1290
epoch=7, loss=0.1153
epoch=8, loss=0.1092
epoch=9, loss=0.1039
epoch=10, loss=0.0984
valid [full], NDCG@5: 0.6410, HR@5: 0.7417, NDCG@10: 0.7095, HR@10: 0.9503, MRR: 0.6422
valid [sampled], NDCG@5: 0.5592, HR@5: 0.5650, NDCG@10: 0.5654, HR@10: 0.5843, MRR: 0.5724
test [full], NDCG@5: 0.6987, HR@5: 0.9548, NDCG@10: 0.7143, HR@10: 1.0000, MRR: 0.6188
test [sampled], NDCG@5: 0.1035, HR@5: 0.1127, NDCG@10: 0.1698, HR@10: 0.3265, MRR: 0.1663
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=11, loss=0.0955
epoch=12, loss=0.0937
epoch=13, loss=0.0905
epoch=14, loss=0.0870
epoch=15, loss=0.0874
valid [full], NDCG@5: 0.6908, HR@5: 0.8452, NDCG@10: 0.7250, HR@10: 0.9544, MRR: 0.6582
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5672, NDCG@10: 0.5740, HR@10: 0.6101, MRR: 0.5789
test [full], NDCG@5: 0.7366, HR@5: 0.9735, NDCG@10: 0.7458, HR@10: 1.0000, MRR: 0.6591
test [sampled], NDCG@5: 0.0898, HR@5: 0.1019, NDCG@10: 0.1693, HR@10: 0.3590, MRR: 0.1570
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=16, loss=0.0860
epoch=17, loss=0.0836
epoch=18, loss=0.0823
epoch=19, loss=0.0809
epoch=20, loss=0.0820
valid [full], NDCG@5: 0.6851, HR@5: 0.8141, NDCG@10: 0.7261, HR@10: 0.9434, MRR: 0.6635
valid [sampled], NDCG@5: 0.5625, HR@5: 0.5749, NDCG@10: 0.5838, HR@10: 0.6416, MRR: 0.5804
test [full], NDCG@5: 0.8292, HR@5: 0.9953, NDCG@10: 0.8308, HR@10: 1.0000, MRR: 0.7717
test [sampled], NDCG@5: 0.2505, HR@5: 0.2879, NDCG@10: 0.3364, HR@10: 0.5596, MRR: 0.3020
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0816
epoch=22, loss=0.0783
epoch=23, loss=0.0798
epoch=24, loss=0.0795
epoch=25, loss=0.0766
valid [full], NDCG@5: 0.7149, HR@5: 0.8596, NDCG@10: 0.7413, HR@10: 0.9460, MRR: 0.6816
valid [sampled], NDCG@5: 0.5653, HR@5: 0.5809, NDCG@10: 0.5929, HR@10: 0.6677, MRR: 0.5852
test [full], NDCG@5: 0.9468, HR@5: 0.9947, NDCG@10: 0.9486, HR@10: 1.0000, MRR: 0.9308
test [sampled], NDCG@5: 0.3887, HR@5: 0.4718, NDCG@10: 0.4675, HR@10: 0.7149, MRR: 0.4135
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=26, loss=0.0780
epoch=27, loss=0.0770
epoch=28, loss=0.0776
epoch=29, loss=0.0767
epoch=30, loss=0.0741
valid [full], NDCG@5: 0.7072, HR@5: 0.8534, NDCG@10: 0.7352, HR@10: 0.9441, MRR: 0.6746
valid [sampled], NDCG@5: 0.5581, HR@5: 0.5709, NDCG@10: 0.5791, HR@10: 0.6365, MRR: 0.5771
test [full], NDCG@5: 0.8686, HR@5: 0.9672, NDCG@10: 0.8801, HR@10: 1.0000, MRR: 0.8401
test [sampled], NDCG@5: 0.3337, HR@5: 0.4057, NDCG@10: 0.3949, HR@10: 0.5942, MRR: 0.3587
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0760
epoch=32, loss=0.0756
epoch=33, loss=0.0751
epoch=34, loss=0.0743
epoch=35, loss=0.0755
valid [full], NDCG@5: 0.7040, HR@5: 0.8420, NDCG@10: 0.7354, HR@10: 0.9432, MRR: 0.6751
valid [sampled], NDCG@5: 0.5597, HR@5: 0.5747, NDCG@10: 0.5890, HR@10: 0.6664, MRR: 0.5799
test [full], NDCG@5: 0.9114, HR@5: 0.9953, NDCG@10: 0.9130, HR@10: 1.0000, MRR: 0.8835
test [sampled], NDCG@5: 0.3650, HR@5: 0.4397, NDCG@10: 0.4357, HR@10: 0.6582, MRR: 0.3912
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0746
epoch=37, loss=0.0748
epoch=38, loss=0.0738
epoch=39, loss=0.0745
epoch=40, loss=0.0740
valid [full], NDCG@5: 0.7176, HR@5: 0.8657, NDCG@10: 0.7451, HR@10: 0.9577, MRR: 0.6825
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5726, NDCG@10: 0.5902, HR@10: 0.6718, MRR: 0.5807
test [full], NDCG@5: 0.9137, HR@5: 0.9993, NDCG@10: 0.9139, HR@10: 1.0000, MRR: 0.8847
test [sampled], NDCG@5: 0.3596, HR@5: 0.4240, NDCG@10: 0.4308, HR@10: 0.6448, MRR: 0.3908
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=41, loss=0.0767
epoch=42, loss=0.0726
epoch=43, loss=0.0741
epoch=44, loss=0.0725
epoch=45, loss=0.0729
valid [full], NDCG@5: 0.7187, HR@5: 0.8635, NDCG@10: 0.7446, HR@10: 0.9482, MRR: 0.6845
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5787, NDCG@10: 0.5939, HR@10: 0.6738, MRR: 0.5843
test [full], NDCG@5: 0.9089, HR@5: 0.9928, NDCG@10: 0.9114, HR@10: 1.0000, MRR: 0.8814
test [sampled], NDCG@5: 0.3416, HR@5: 0.4135, NDCG@10: 0.4121, HR@10: 0.6314, MRR: 0.3698
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_best.pth
epoch=46, loss=0.0726
epoch=47, loss=0.0723
epoch=48, loss=0.0722
epoch=49, loss=0.0724
epoch=50, loss=0.0726
valid [full], NDCG@5: 0.7184, HR@5: 0.8610, NDCG@10: 0.7449, HR@10: 0.9473, MRR: 0.6852
valid [sampled], NDCG@5: 0.5700, HR@5: 0.5867, NDCG@10: 0.6013, HR@10: 0.6859, MRR: 0.5901
test [full], NDCG@5: 0.9151, HR@5: 0.9973, NDCG@10: 0.9160, HR@10: 1.0000, MRR: 0.8873
test [sampled], NDCG@5: 0.3488, HR@5: 0.4226, NDCG@10: 0.4203, HR@10: 0.6435, MRR: 0.3763
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg5/timeaware_dstart_refine_ml50_do035_b9_s7/sasrec_last.pth

## Train `delta_start + continuous` for `NDCG@5`

### timeaware_dstart_conti_refine_ml50_do035_s42

In [21]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_conti_refine_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42
epoch=1, loss=0.6435
epoch=2, loss=0.3108
epoch=3, loss=0.2256
epoch=4, loss=0.1818
epoch=5, loss=0.1542
valid [full], NDCG@5: 0.5792, HR@5: 0.6165, NDCG@10: 0.6660, HR@10: 0.8930, MRR: 0.6096
valid [sampled], NDCG@5: 0.5436, HR@5: 0.5451, NDCG@10: 0.5508, HR@10: 0.5682, MRR: 0.5565
test [full], NDCG@5: 0.5982, HR@5: 0.7511, NDCG@10: 0.6383, HR@10: 0.8839, MRR: 0.5684
test [sampled], NDCG@5: 0.1847, HR@5: 0.1933, NDCG@10: 0.2183, HR@10: 0.3020, MRR: 0.2273
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1365
epoch=7, loss=0.1258
epoch=8, loss=0.1144
epoch=9, loss=0.1081
epoch=10, loss=0.1042
valid [full], NDCG@5: 0.6397, HR@5: 0.7302, NDCG@10: 0.7125, HR@10: 0.9540, MRR: 0.6444
valid [sampled], NDCG@5: 0.5641, HR@5: 0.5784, NDCG@10: 0.5774, HR@10: 0.6194, MRR: 0.5770
test [full], NDCG@5: 0.5922, HR@5: 0.8665, NDCG@10: 0.6380, HR@10: 1.0000, MRR: 0.5207
test [sampled], NDCG@5: 0.1646, HR@5: 0.1789, NDCG@10: 0.2092, HR@10: 0.3221, MRR: 0.2104
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=0.1007
epoch=12, loss=0.0971
epoch=13, loss=0.0941
epoch=14, loss=0.0939
epoch=15, loss=0.0920
valid [full], NDCG@5: 0.7089, HR@5: 0.8777, NDCG@10: 0.7379, HR@10: 0.9712, MRR: 0.6685
valid [sampled], NDCG@5: 0.5786, HR@5: 0.5911, NDCG@10: 0.5962, HR@10: 0.6463, MRR: 0.5955
test [full], NDCG@5: 0.6925, HR@5: 0.9681, NDCG@10: 0.7033, HR@10: 1.0000, MRR: 0.6044
test [sampled], NDCG@5: 0.1750, HR@5: 0.2123, NDCG@10: 0.2342, HR@10: 0.3987, MRR: 0.2174
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0900
epoch=17, loss=0.0859
epoch=18, loss=0.0870
epoch=19, loss=0.0857
epoch=20, loss=0.0840
valid [full], NDCG@5: 0.6500, HR@5: 0.8363, NDCG@10: 0.6934, HR@10: 0.9704, MRR: 0.6101
valid [sampled], NDCG@5: 0.4740, HR@5: 0.4834, NDCG@10: 0.4914, HR@10: 0.5383, MRR: 0.4962
test [full], NDCG@5: 0.7014, HR@5: 0.9548, NDCG@10: 0.7157, HR@10: 1.0000, MRR: 0.6220
test [sampled], NDCG@5: 0.1694, HR@5: 0.2230, NDCG@10: 0.2301, HR@10: 0.4124, MRR: 0.2061
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0824
epoch=22, loss=0.0831
epoch=23, loss=0.0827
epoch=24, loss=0.0805
epoch=25, loss=0.0806
valid [full], NDCG@5: 0.6793, HR@5: 0.8129, NDCG@10: 0.7268, HR@10: 0.9604, MRR: 0.6589
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5629, NDCG@10: 0.5701, HR@10: 0.6112, MRR: 0.5726
test [full], NDCG@5: 0.7134, HR@5: 0.9692, NDCG@10: 0.7236, HR@10: 1.0000, MRR: 0.6298
test [sampled], NDCG@5: 0.2004, HR@5: 0.2200, NDCG@10: 0.2707, HR@10: 0.4444, MRR: 0.2525
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0787
epoch=27, loss=0.0819
epoch=28, loss=0.0794
epoch=29, loss=0.0804
epoch=30, loss=0.0797
valid [full], NDCG@5: 0.6871, HR@5: 0.8286, NDCG@10: 0.7326, HR@10: 0.9727, MRR: 0.6623
valid [sampled], NDCG@5: 0.5621, HR@5: 0.5690, NDCG@10: 0.5742, HR@10: 0.6066, MRR: 0.5795
test [full], NDCG@5: 0.7807, HR@5: 0.9585, NDCG@10: 0.7934, HR@10: 1.0000, MRR: 0.7246
test [sampled], NDCG@5: 0.2415, HR@5: 0.2859, NDCG@10: 0.3185, HR@10: 0.5285, MRR: 0.2862
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0785
epoch=32, loss=0.0783
epoch=33, loss=0.0796
epoch=34, loss=0.0778
epoch=35, loss=0.0767
valid [full], NDCG@5: 0.6551, HR@5: 0.8604, NDCG@10: 0.6909, HR@10: 0.9739, MRR: 0.6046
valid [sampled], NDCG@5: 0.4631, HR@5: 0.4709, NDCG@10: 0.4809, HR@10: 0.5271, MRR: 0.4880
test [full], NDCG@5: 0.7717, HR@5: 0.9478, NDCG@10: 0.7879, HR@10: 1.0000, MRR: 0.7179
test [sampled], NDCG@5: 0.2465, HR@5: 0.3250, NDCG@10: 0.3207, HR@10: 0.5544, MRR: 0.2753
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0772
epoch=37, loss=0.0757
epoch=38, loss=0.0755
epoch=39, loss=0.0763
epoch=40, loss=0.0766
valid [full], NDCG@5: 0.6546, HR@5: 0.8614, NDCG@10: 0.6871, HR@10: 0.9670, MRR: 0.6029
valid [sampled], NDCG@5: 0.4637, HR@5: 0.4706, NDCG@10: 0.4794, HR@10: 0.5200, MRR: 0.4874
test [full], NDCG@5: 0.7297, HR@5: 0.9474, NDCG@10: 0.7457, HR@10: 1.0000, MRR: 0.6607
test [sampled], NDCG@5: 0.2015, HR@5: 0.2344, NDCG@10: 0.2834, HR@10: 0.4942, MRR: 0.2538
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0762
epoch=42, loss=0.0770
epoch=43, loss=0.0768
epoch=44, loss=0.0755
epoch=45, loss=0.0763
valid [full], NDCG@5: 0.6369, HR@5: 0.8327, NDCG@10: 0.6835, HR@10: 0.9764, MRR: 0.5953
valid [sampled], NDCG@5: 0.4617, HR@5: 0.4721, NDCG@10: 0.4771, HR@10: 0.5205, MRR: 0.4828
test [full], NDCG@5: 0.8192, HR@5: 0.9452, NDCG@10: 0.8369, HR@10: 1.0000, MRR: 0.7842
test [sampled], NDCG@5: 0.2497, HR@5: 0.3352, NDCG@10: 0.3393, HR@10: 0.6117, MRR: 0.2805
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0735
epoch=47, loss=0.0744
epoch=48, loss=0.0738
epoch=49, loss=0.0744
epoch=50, loss=0.0750
valid [full], NDCG@5: 0.6744, HR@5: 0.8626, NDCG@10: 0.7097, HR@10: 0.9754, MRR: 0.6283
valid [sampled], NDCG@5: 0.4659, HR@5: 0.4769, NDCG@10: 0.4931, HR@10: 0.5632, MRR: 0.4925
test [full], NDCG@5: 0.7952, HR@5: 0.9457, NDCG@10: 0.8116, HR@10: 1.0000, MRR: 0.7493
test [sampled], NDCG@5: 0.2445, HR@5: 0.2939, NDCG@10: 0.3196, HR@10: 0.5300, MRR: 0.2868
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s42/sasrec_last.pth

### timeaware_dstart_conti_refine_ml50_do035_s2024

In [22]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_conti_refine_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024
epoch=1, loss=0.6747
epoch=2, loss=0.3270
epoch=3, loss=0.2288
epoch=4, loss=0.1837
epoch=5, loss=0.1540
valid [full], NDCG@5: 0.6732, HR@5: 0.7996, NDCG@10: 0.7262, HR@10: 0.9722, MRR: 0.6549
valid [sampled], NDCG@5: 0.5662, HR@5: 0.5775, NDCG@10: 0.5785, HR@10: 0.6155, MRR: 0.5806
test [full], NDCG@5: 0.7545, HR@5: 0.8810, NDCG@10: 0.7927, HR@10: 1.0000, MRR: 0.7281
test [sampled], NDCG@5: 0.1394, HR@5: 0.2107, NDCG@10: 0.2161, HR@10: 0.4479, MRR: 0.1762
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1315
epoch=7, loss=0.1204
epoch=8, loss=0.1133
epoch=9, loss=0.1052
epoch=10, loss=0.1022
valid [full], NDCG@5: 0.7007, HR@5: 0.8716, NDCG@10: 0.7324, HR@10: 0.9711, MRR: 0.6613
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5631, NDCG@10: 0.5670, HR@10: 0.6011, MRR: 0.5731
test [full], NDCG@5: 0.7613, HR@5: 0.9204, NDCG@10: 0.7854, HR@10: 1.0000, MRR: 0.7164
test [sampled], NDCG@5: 0.1394, HR@5: 0.2215, NDCG@10: 0.2206, HR@10: 0.4732, MRR: 0.1726
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/sasrec_best.pth
epoch=11, loss=0.0982
epoch=12, loss=0.0944
epoch=13, loss=0.0918
epoch=14, loss=0.0910
epoch=15, loss=0.0906
valid [full], NDCG@5: 0.6970, HR@5: 0.8601, NDCG@10: 0.7320, HR@10: 0.9702, MRR: 0.6617
valid [sampled], NDCG@5: 0.5672, HR@5: 0.5791, NDCG@10: 0.5789, HR@10: 0.6149, MRR: 0.5827
test [full], NDCG@5: 0.7446, HR@5: 0.9341, NDCG@10: 0.7651, HR@10: 1.0000, MRR: 0.6879
test [sampled], NDCG@5: 0.1748, HR@5: 0.2090, NDCG@10: 0.2316, HR@10: 0.3885, MRR: 0.2211
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0873
epoch=17, loss=0.0862
epoch=18, loss=0.0864
epoch=19, loss=0.0856
epoch=20, loss=0.0851
valid [full], NDCG@5: 0.6699, HR@5: 0.7938, NDCG@10: 0.7191, HR@10: 0.9458, MRR: 0.6547
valid [sampled], NDCG@5: 0.5560, HR@5: 0.5600, NDCG@10: 0.5671, HR@10: 0.5953, MRR: 0.5736
test [full], NDCG@5: 0.8249, HR@5: 0.9348, NDCG@10: 0.8445, HR@10: 0.9999, MRR: 0.7950
test [sampled], NDCG@5: 0.2799, HR@5: 0.3405, NDCG@10: 0.3375, HR@10: 0.5179, MRR: 0.3101
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0830
epoch=22, loss=0.0819
epoch=23, loss=0.0809
epoch=24, loss=0.0827
epoch=25, loss=0.0812
valid [full], NDCG@5: 0.6966, HR@5: 0.8490, NDCG@10: 0.7261, HR@10: 0.9431, MRR: 0.6632
valid [sampled], NDCG@5: 0.5508, HR@5: 0.5574, NDCG@10: 0.5680, HR@10: 0.6119, MRR: 0.5717
test [full], NDCG@5: 0.8160, HR@5: 0.9345, NDCG@10: 0.8360, HR@10: 1.0000, MRR: 0.7836
test [sampled], NDCG@5: 0.2336, HR@5: 0.3111, NDCG@10: 0.3011, HR@10: 0.5187, MRR: 0.2614
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0786
epoch=27, loss=0.0781
epoch=28, loss=0.0785
epoch=29, loss=0.0819
epoch=30, loss=0.0775
valid [full], NDCG@5: 0.6931, HR@5: 0.8539, NDCG@10: 0.7207, HR@10: 0.9418, MRR: 0.6568
valid [sampled], NDCG@5: 0.5529, HR@5: 0.5584, NDCG@10: 0.5639, HR@10: 0.5933, MRR: 0.5713
test [full], NDCG@5: 0.7609, HR@5: 0.9449, NDCG@10: 0.7774, HR@10: 1.0000, MRR: 0.7048
test [sampled], NDCG@5: 0.2869, HR@5: 0.3091, NDCG@10: 0.3333, HR@10: 0.4563, MRR: 0.3258
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0781
epoch=32, loss=0.0777
epoch=33, loss=0.0761
epoch=34, loss=0.0781
epoch=35, loss=0.0762
valid [full], NDCG@5: 0.6918, HR@5: 0.8458, NDCG@10: 0.7229, HR@10: 0.9459, MRR: 0.6586
valid [sampled], NDCG@5: 0.5555, HR@5: 0.5599, NDCG@10: 0.5695, HR@10: 0.6045, MRR: 0.5759
test [full], NDCG@5: 0.8228, HR@5: 0.9438, NDCG@10: 0.8401, HR@10: 0.9999, MRR: 0.7891
test [sampled], NDCG@5: 0.3303, HR@5: 0.3801, NDCG@10: 0.3786, HR@10: 0.5296, MRR: 0.3584
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0765
epoch=37, loss=0.0757
epoch=38, loss=0.0752
epoch=39, loss=0.0763
epoch=40, loss=0.0742
valid [full], NDCG@5: 0.6873, HR@5: 0.8703, NDCG@10: 0.7208, HR@10: 0.9759, MRR: 0.6441
valid [sampled], NDCG@5: 0.5263, HR@5: 0.5321, NDCG@10: 0.5403, HR@10: 0.5769, MRR: 0.5479
test [full], NDCG@5: 0.7980, HR@5: 0.9536, NDCG@10: 0.8126, HR@10: 1.0000, MRR: 0.7509
test [sampled], NDCG@5: 0.3155, HR@5: 0.3453, NDCG@10: 0.3695, HR@10: 0.5173, MRR: 0.3545
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0757
epoch=42, loss=0.0757
epoch=43, loss=0.0756
epoch=44, loss=0.0739
epoch=45, loss=0.0739
valid [full], NDCG@5: 0.6642, HR@5: 0.8363, NDCG@10: 0.7056, HR@10: 0.9682, MRR: 0.6283
valid [sampled], NDCG@5: 0.5163, HR@5: 0.5196, NDCG@10: 0.5263, HR@10: 0.5517, MRR: 0.5368
test [full], NDCG@5: 0.8310, HR@5: 0.9730, NDCG@10: 0.8403, HR@10: 1.0000, MRR: 0.7878
test [sampled], NDCG@5: 0.3670, HR@5: 0.3955, NDCG@10: 0.4160, HR@10: 0.5505, MRR: 0.4028
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0725
epoch=47, loss=0.0747
epoch=48, loss=0.0741
epoch=49, loss=0.0726
epoch=50, loss=0.0751
valid [full], NDCG@5: 0.6918, HR@5: 0.8697, NDCG@10: 0.7225, HR@10: 0.9683, MRR: 0.6489
valid [sampled], NDCG@5: 0.5274, HR@5: 0.5333, NDCG@10: 0.5408, HR@10: 0.5763, MRR: 0.5495
test [full], NDCG@5: 0.8641, HR@5: 0.9660, NDCG@10: 0.8753, HR@10: 1.0000, MRR: 0.8346
test [sampled], NDCG@5: 0.3385, HR@5: 0.4077, NDCG@10: 0.4030, HR@10: 0.6064, MRR: 0.3644
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s2024/sasrec_last.pth

### timeaware_dstart_conti_refine_ml50_do035_s7

In [23]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_conti_refine_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_delta_column delta_start_seconds \
  --time_encoding continuous \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7
epoch=1, loss=0.6368
epoch=2, loss=0.3261
epoch=3, loss=0.2338
epoch=4, loss=0.1884
epoch=5, loss=0.1637
valid [full], NDCG@5: 0.6210, HR@5: 0.7248, NDCG@10: 0.6889, HR@10: 0.9404, MRR: 0.6202
valid [sampled], NDCG@5: 0.5455, HR@5: 0.5473, NDCG@10: 0.5513, HR@10: 0.5656, MRR: 0.5609
test [full], NDCG@5: 0.5974, HR@5: 0.6974, NDCG@10: 0.6735, HR@10: 0.9348, MRR: 0.5999
test [sampled], NDCG@5: 0.1973, HR@5: 0.2229, NDCG@10: 0.2381, HR@10: 0.3519, MRR: 0.2324
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1404
epoch=7, loss=0.1240
epoch=8, loss=0.1135
epoch=9, loss=0.1085
epoch=10, loss=0.1020
valid [full], NDCG@5: 0.6580, HR@5: 0.7667, NDCG@10: 0.7227, HR@10: 0.9684, MRR: 0.6521
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5676, NDCG@10: 0.5715, HR@10: 0.6066, MRR: 0.5745
test [full], NDCG@5: 0.6925, HR@5: 0.9705, NDCG@10: 0.7028, HR@10: 0.9999, MRR: 0.6037
test [sampled], NDCG@5: 0.0894, HR@5: 0.0987, NDCG@10: 0.1554, HR@10: 0.3113, MRR: 0.1522
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=0.0999
epoch=12, loss=0.0962
epoch=13, loss=0.0932
epoch=14, loss=0.0904
epoch=15, loss=0.0907
valid [full], NDCG@5: 0.6978, HR@5: 0.8227, NDCG@10: 0.7428, HR@10: 0.9651, MRR: 0.6769
valid [sampled], NDCG@5: 0.5610, HR@5: 0.5720, NDCG@10: 0.5901, HR@10: 0.6643, MRR: 0.5828
test [full], NDCG@5: 0.6663, HR@5: 0.9974, NDCG@10: 0.6672, HR@10: 0.9999, MRR: 0.5541
test [sampled], NDCG@5: 0.0765, HR@5: 0.0849, NDCG@10: 0.1382, HR@10: 0.2839, MRR: 0.1383
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=0.0899
epoch=17, loss=0.0856
epoch=18, loss=0.0850
epoch=19, loss=0.0842
epoch=20, loss=0.0851
valid [full], NDCG@5: 0.6953, HR@5: 0.8224, NDCG@10: 0.7334, HR@10: 0.9457, MRR: 0.6720
valid [sampled], NDCG@5: 0.5656, HR@5: 0.5779, NDCG@10: 0.5942, HR@10: 0.6679, MRR: 0.5856
test [full], NDCG@5: 0.8113, HR@5: 0.9962, NDCG@10: 0.8125, HR@10: 1.0000, MRR: 0.7494
test [sampled], NDCG@5: 0.1480, HR@5: 0.2274, NDCG@10: 0.2337, HR@10: 0.4934, MRR: 0.1865
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0840
epoch=22, loss=0.0804
epoch=23, loss=0.0822
epoch=24, loss=0.0822
epoch=25, loss=0.0786
valid [full], NDCG@5: 0.6993, HR@5: 0.8228, NDCG@10: 0.7404, HR@10: 0.9543, MRR: 0.6780
valid [sampled], NDCG@5: 0.5631, HR@5: 0.5763, NDCG@10: 0.5919, HR@10: 0.6675, MRR: 0.5835
test [full], NDCG@5: 0.8298, HR@5: 0.9967, NDCG@10: 0.8308, HR@10: 0.9999, MRR: 0.7729
test [sampled], NDCG@5: 0.1385, HR@5: 0.2119, NDCG@10: 0.2270, HR@10: 0.4878, MRR: 0.1828
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_best.pth
epoch=26, loss=0.0801
epoch=27, loss=0.0796
epoch=28, loss=0.0799
epoch=29, loss=0.0784
epoch=30, loss=0.0767
valid [full], NDCG@5: 0.6752, HR@5: 0.8020, NDCG@10: 0.7208, HR@10: 0.9461, MRR: 0.6557
valid [sampled], NDCG@5: 0.5226, HR@5: 0.5320, NDCG@10: 0.5510, HR@10: 0.6220, MRR: 0.5458
test [full], NDCG@5: 0.8513, HR@5: 0.9949, NDCG@10: 0.8530, HR@10: 0.9999, MRR: 0.8034
test [sampled], NDCG@5: 0.1731, HR@5: 0.2599, NDCG@10: 0.2649, HR@10: 0.5449, MRR: 0.2100
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0782
epoch=32, loss=0.0775
epoch=33, loss=0.0767
epoch=34, loss=0.0761
epoch=35, loss=0.0788
valid [full], NDCG@5: 0.6392, HR@5: 0.7536, NDCG@10: 0.6947, HR@10: 0.9289, MRR: 0.6293
valid [sampled], NDCG@5: 0.5224, HR@5: 0.5356, NDCG@10: 0.5431, HR@10: 0.5997, MRR: 0.5393
test [full], NDCG@5: 0.8853, HR@5: 0.9943, NDCG@10: 0.8872, HR@10: 0.9999, MRR: 0.8498
test [sampled], NDCG@5: 0.3555, HR@5: 0.4204, NDCG@10: 0.4158, HR@10: 0.6067, MRR: 0.3818
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0768
epoch=37, loss=0.0779
epoch=38, loss=0.0771
epoch=39, loss=0.0765
epoch=40, loss=0.0759
valid [full], NDCG@5: 0.6844, HR@5: 0.8258, NDCG@10: 0.7232, HR@10: 0.9490, MRR: 0.6570
valid [sampled], NDCG@5: 0.5289, HR@5: 0.5405, NDCG@10: 0.5560, HR@10: 0.6265, MRR: 0.5507
test [full], NDCG@5: 0.9076, HR@5: 0.9982, NDCG@10: 0.9082, HR@10: 1.0000, MRR: 0.8774
test [sampled], NDCG@5: 0.3779, HR@5: 0.4404, NDCG@10: 0.4359, HR@10: 0.6183, MRR: 0.4048
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0792
epoch=42, loss=0.0748
epoch=43, loss=0.0757
epoch=44, loss=0.0749
epoch=45, loss=0.0758
valid [full], NDCG@5: 0.6776, HR@5: 0.8104, NDCG@10: 0.7200, HR@10: 0.9468, MRR: 0.6537
valid [sampled], NDCG@5: 0.5234, HR@5: 0.5389, NDCG@10: 0.5533, HR@10: 0.6327, MRR: 0.5445
test [full], NDCG@5: 0.8844, HR@5: 0.9835, NDCG@10: 0.8902, HR@10: 1.0000, MRR: 0.8534
test [sampled], NDCG@5: 0.3825, HR@5: 0.4552, NDCG@10: 0.4426, HR@10: 0.6392, MRR: 0.4036
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0746
epoch=47, loss=0.0749
epoch=48, loss=0.0735
epoch=49, loss=0.0743
epoch=50, loss=0.0745
valid [full], NDCG@5: 0.6569, HR@5: 0.8106, NDCG@10: 0.6997, HR@10: 0.9453, MRR: 0.6273
valid [sampled], NDCG@5: 0.4908, HR@5: 0.5064, NDCG@10: 0.5184, HR@10: 0.5935, MRR: 0.5125
test [full], NDCG@5: 0.8696, HR@5: 0.9578, NDCG@10: 0.8844, HR@10: 1.0000, MRR: 0.8463
test [sampled], NDCG@5: 0.3300, HR@5: 0.4133, NDCG@10: 0.3951, HR@10: 0.6128, MRR: 0.3510
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg5/timeaware_dstart_conti_refine_ml50_do035_s7/sasrec_last.pth

## Rebuild result tables

In [24]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'time_encoding': config.get('time_encoding'),
            'time_delta_column': config.get('time_delta_column'),
            'time_bucket_boundaries_parsed': config.get('time_bucket_boundaries_parsed'),
            'time_feature_dim': config.get('time_feature_dim'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [30]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## NDCG@10 comparison summary

In [31]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
bucket_runs = [
    'timeaware_dstart_refine_ml50_do035_b9_s42',
    'timeaware_dstart_refine_ml50_do035_b9_s2024',
    'timeaware_dstart_refine_ml50_do035_b9_s7',
]
continuous_runs = [
    'timeaware_dstart_conti_refine_ml50_do035_s42',
    'timeaware_dstart_conti_refine_ml50_do035_s2024',
    'timeaware_dstart_conti_refine_ml50_do035_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
bucket_df = rebuild_df(BUCKET_NDCG10_OUTPUT_DIR)
continuous_df = rebuild_df(CONT_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['time_variant'] = 'baseline'

bucket_subset = bucket_df[bucket_df['run_name'].isin(bucket_runs)].copy()
bucket_subset['time_variant'] = 'delta_start_b9'

continuous_subset = continuous_df[continuous_df['run_name'].isin(continuous_runs)].copy()
continuous_subset['time_variant'] = 'delta_start_continuous'

df_ndcg10 = pd.concat([baseline_subset, bucket_subset, continuous_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'time_variant', 'time_encoding', 'time_delta_column', 'time_bucket_boundaries_parsed', 'time_feature_dim',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                                         run_name  seed            time_variant time_encoding    time_delta_column             time_bucket_boundaries_parsed time_feature_dim  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0                            refine_ml50_do035_s7     7                baseline          None   delta_prev_seconds                                      None             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
1                           refine_ml50_do035_s42    42                baseline          None   delta_prev_seconds                                      None             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
2                         refine_ml50_do035_s2024  2024                baseline          None   delta_prev_seconds                                      None             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183
3        timeaware_dstart_refine_ml50_do035_b9_s7     7          delta_start_b9        bucket  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                1                 0.745142               0.957660                0.717650              0.865653             0.682456                0.913922              1.000000               0.913685             0.999321            0.884692                    0.590203                  0.671790                   0.558999                 0.572633                0.580722                   0.430771                 0.644776                  0.359573                0.424016               0.390789
4       timeaware_dstart_refine_ml50_do035_b9_s42    42          delta_start_b9        bucket  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                1                 0.728625               0.964446                0.681780              0.820464             0.659430                0.663047              1.000000               0.649231             0.958485            0.549901                    0.588615                  0.633023                   0.572991                 0.584380                0.589039                   0.181912                 0.318336                  0.125099                0.135517               0.181054
5     timeaware_dstart_refine_ml50_do035_b9_s2024  2024          delta_start_b9        bucket  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                1                 0.752983               0.972787                0.721568              0.873097             0.686346                0.827690              0.999865               0.811716             0.948416            0.770331                    0.592942                  0.678122                   0.560615                 0.576106                0.582732                   0.366431                 0.517942                  0.306744                0.327014               0.352601
6     timeaware_dstart_conti_refine_ml50_do035_s7     7  delta_start_continuous    continuous  delta_start_seconds            [60.0, 600.0, 3600.0, 86400.0]                2                 0.742792               0.965143                0.697805              0.822732             0.676947                0.667157              0.999865               0.666316             0.997428            0.554053                    0.590123                  0.664322                   0.561008                 0.571950                0.582827                   0.138163                 0.283937                  0.076503                0.084911               0.138319
7    timeaware_dstart_conti_refine_ml50_do035_s42    42  delta_start_continuous    continuous  delta_start_seconds            [60.0, 600.0, 3600.0, 86400.0]                2                 0.737949               0.971231                0.708916              0.877731             0.668492                0.703322              1.000000               0.692492             0.968087            0.604422                    0.596241                  0.646264                   0.578629                 0.591136                0.595470                   0.234225                 0.398668                  0.174982                0.212315               0.217385
8  timeaware_dstart_conti_refine_ml50_do035_s2024  2024  delta_start_continuous    continuous  delta_start_seconds            [60.0, 600.0, 3600.0, 86400.0]                2                 0.732435               0.971097                0.700672              0.871556             0.661297                0.785443              1.000000               0.761312             0.920419            0.716429                    0.566956                  0.601116                   0.554750                 0.563146                0.573079                   0.220623                 0.473166                  0.139440                0.221548               0.172588

In [32]:
summary_ndcg10 = df_ndcg10.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

                       best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                          mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
time_variant
baseline                              0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175
delta_start_b9                        0.742250  0.012434              0.964964  0.007577               0.706999  0.021928             0.853072  0.028483            0.676078  0.014548               0.801553  0.127464             0.999955  0.000078              0.791544  0.133376            0.968741  0.026958           0.734975  0.170173                   0.590587  0.002189                 0.660978  0.024416                  0.564202  0.007655                0.577707  0.006035               0.584164  0.004340                  0.326371  0.129175                0.493685  0.164566                 0.263805  0.122993               0.295516  0.146806              0.308148  0.111710
delta_start_continuous                0.737725  0.005182              0.969157  0.003477               0.702464  0.005768             0.857340  0.030130            0.668912  0.007834               0.718641  0.060612             0.999955  0.000078              0.706706  0.049067            0.961978  0.038866           0.624968  0.083115                   0.584440  0.015447                 0.637234  0.032556                  0.564796  0.012382                0.575411  0.014312               0.583792  0.011227                  0.197670  0.051982                0.385257  0.095325                 0.130308  0.049871               0.172925  0.076362              0.176097  0.039650

Interpretation guide for NDCG@10:
- compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` first
- then check whether sampled and MRR move in the same direction
- this notebook compares `delta_start_seconds + 9-bucket` vs `delta_start_seconds + continuous` under the same baseline

## NDCG@5 comparison summary

In [33]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
bucket_runs = [
    'timeaware_dstart_refine_ml50_do035_b9_s42',
    'timeaware_dstart_refine_ml50_do035_b9_s2024',
    'timeaware_dstart_refine_ml50_do035_b9_s7',
]
continuous_runs = [
    'timeaware_dstart_conti_refine_ml50_do035_s42',
    'timeaware_dstart_conti_refine_ml50_do035_s2024',
    'timeaware_dstart_conti_refine_ml50_do035_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
bucket_df = rebuild_df(BUCKET_NDCG5_OUTPUT_DIR)
continuous_df = rebuild_df(CONT_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['time_variant'] = 'baseline'

bucket_subset = bucket_df[bucket_df['run_name'].isin(bucket_runs)].copy()
bucket_subset['time_variant'] = 'delta_start_b9'

continuous_subset = continuous_df[continuous_df['run_name'].isin(continuous_runs)].copy()
continuous_subset['time_variant'] = 'delta_start_continuous'

df_ndcg5 = pd.concat([baseline_subset, bucket_subset, continuous_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'time_variant', 'time_encoding', 'time_delta_column', 'time_bucket_boundaries_parsed', 'time_feature_dim',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                                         run_name  seed            time_variant time_encoding    time_delta_column             time_bucket_boundaries_parsed time_feature_dim  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0                            refine_ml50_do035_s7     7                baseline          None   delta_prev_seconds                                      None             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
1                           refine_ml50_do035_s42    42                baseline          None   delta_prev_seconds                                      None             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
2                         refine_ml50_do035_s2024  2024                baseline          None   delta_prev_seconds                                      None             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183
3        timeaware_dstart_refine_ml50_do035_b9_s7     7          delta_start_b9        bucket  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                1                 0.744562               0.948239                0.718698              0.863539             0.684462                0.911379              1.000000               0.908915             0.992815            0.881427                    0.593869                  0.673816                   0.563615                 0.578662                0.584333                   0.412148                 0.631351                  0.341570                0.413494               0.369849
4       timeaware_dstart_refine_ml50_do035_b9_s42    42          delta_start_b9        bucket  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                1                 0.721305               0.936017                0.687943              0.830826             0.660536                0.713420              0.999865               0.702081             0.964030            0.617557                    0.577894                  0.626563                   0.559777                 0.569739                0.576792                   0.214884                 0.333649                  0.166365                0.177576               0.220794
5     timeaware_dstart_refine_ml50_do035_b9_s2024  2024          delta_start_b9        bucket  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                1                 0.752983               0.972787                0.721568              0.873097             0.686346                0.827690              0.999865               0.811716             0.948416            0.770331                    0.592942                  0.678122                   0.560615                 0.576106                0.582732                   0.366431                 0.517942                  0.306744                0.327014               0.352601
6     timeaware_dstart_conti_refine_ml50_do035_s7     7  delta_start_continuous    continuous  delta_start_seconds            [60.0, 600.0, 3600.0, 86400.0]                2                 0.740357               0.954274                0.699253              0.822795             0.678027                0.830831              0.999864               0.829786             0.996744            0.772888                    0.591938                  0.667479                   0.563096                 0.576262                0.583469                   0.227032                 0.487845                  0.138473                0.211870               0.182775
7    timeaware_dstart_conti_refine_ml50_do035_s42    42  delta_start_continuous    continuous  delta_start_seconds            [60.0, 600.0, 3600.0, 86400.0]                2                 0.737949               0.971231                0.708916              0.877731             0.668492                0.703322              1.000000               0.692492             0.968087            0.604422                    0.596241                  0.646264                   0.578629                 0.591136                0.595470                   0.234225                 0.398668                  0.174982                0.212315               0.217385
8  timeaware_dstart_conti_refine_ml50_do035_s2024  2024  delta_start_continuous    continuous  delta_start_seconds            [60.0, 600.0, 3600.0, 86400.0]                2                 0.732435               0.971097                0.700672              0.871556             0.661297                0.785443              1.000000               0.761312             0.920419            0.716429                    0.566956                  0.601116                   0.554750                 0.563146                0.573079                   0.220623                 0.473166                  0.139440                0.221548               0.172588

In [34]:
summary_ndcg5 = df_ndcg5.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

                       best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                          mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
time_variant
baseline                              0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175
delta_start_b9                        0.739616  0.016408              0.952348  0.018726               0.709403  0.018640             0.855820  0.022168            0.677115  0.014388               0.817496  0.099373             0.999910  0.000078              0.807570  0.103479            0.968420  0.022523           0.756439  0.132482                   0.588235  0.008967                 0.659500  0.028605                  0.561336  0.002018                0.574836  0.004595               0.581286  0.003973                  0.331154  0.103255                0.494314  0.150251                 0.271559  0.092751               0.306028  0.119351              0.314415  0.081535
delta_start_continuous                0.736914  0.004061              0.965534  0.009751               0.702947  0.005218             0.857361  0.030093            0.669272  0.008392               0.773199  0.064631             0.999955  0.000078              0.761196  0.068647            0.961750  0.038555           0.697913  0.085746                   0.585045  0.015812                 0.638286  0.033893                  0.565492  0.012119                0.576848  0.014004               0.584006  0.011205                  0.227293  0.006805                0.453226  0.047815                 0.150965  0.020805               0.215244  0.005464              0.190916  0.023482

Interpretation guide for NDCG@5:
- compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` first
- then check whether sampled and MRR move in the same direction
- this notebook compares `delta_start_seconds + 9-bucket` vs `delta_start_seconds + continuous` under the same baseline