# SASRec Attention-Bias Refinement BPI2012 Colab Train (`refine_ml50_do035` baseline)

Refinement notebook for the most promising time-aware direction so far: attention bias.

This notebook keeps the same setting as the previous attention-bias experiment, except for one change:
- bucket boundaries are refined to make short time gaps more granular.

Comparison targets:
- baseline `refine_ml50_do035`
- previous attention-bias setting (`60,600,3600,86400,604800`)
- refined attention-bias setting (`10,60,600,3600,86400,604800`)

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
BASE_ATTN_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10'
BASE_ATTN_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5'
REFINE_ATTN_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10'
REFINE_ATTN_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('BASE_ATTN_NDCG10_OUTPUT_DIR:', BASE_ATTN_NDCG10_OUTPUT_DIR)
print('BASE_ATTN_NDCG5_OUTPUT_DIR:', BASE_ATTN_NDCG5_OUTPUT_DIR)
print('REFINE_ATTN_NDCG10_OUTPUT_DIR:', REFINE_ATTN_NDCG10_OUTPUT_DIR)
print('REFINE_ATTN_NDCG5_OUTPUT_DIR:', REFINE_ATTN_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
BASE_ATTN_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10
BASE_ATTN_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5
REFINE_ATTN_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10
REFINE_ATTN_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$BASE_ATTN_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASE_ATTN_NDCG5_OUTPUT_DIR"
!mkdir -p "$REFINE_ATTN_NDCG10_OUTPUT_DIR"
!mkdir -p "$REFINE_ATTN_NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `refine_ml50_do035`
- `hidden_units=50, num_blocks=2, num_heads=1, maxlen=50, lr=0.001, dropout=0.35`
- seeds: `42`, `2024`, `7`

Attention-bias design:
- `delta_start_seconds`
- causal pairwise gap
- refined boundaries: `10,60,600,3600,86400,604800`
- objective: check whether finer short-term buckets improve over the original attention-bias setting

## Check prerequisite runs

In [10]:
from pathlib import Path

checks = [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR), [
        'refine_ml50_do035_s42',
        'refine_ml50_do035_s2024',
        'refine_ml50_do035_s7',
    ]),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR), [
        'refine_ml50_do035_s42',
        'refine_ml50_do035_s2024',
        'refine_ml50_do035_s7',
    ]),
    ('Base attention-bias NDCG@10', Path(BASE_ATTN_NDCG10_OUTPUT_DIR), [
        'attnbias_dstart_ml50_do035_b9_s42',
        'attnbias_dstart_ml50_do035_b9_s2024',
        'attnbias_dstart_ml50_do035_b9_s7',
    ]),
    ('Base attention-bias NDCG@5', Path(BASE_ATTN_NDCG5_OUTPUT_DIR), [
        'attnbias_dstart_ml50_do035_b9_s42',
        'attnbias_dstart_ml50_do035_b9_s2024',
        'attnbias_dstart_ml50_do035_b9_s7',
    ]),
]

for label, output_dir, run_names in checks:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS
================================================================================
Baseline NDCG@5
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS
================================================================================
Base attention-bias NDCG@10
attnbias_dstart_ml50_do035_b9_s42 EXISTS
attnbias_dstart_ml50_do035_b9_s2024 EXISTS
attnbias_dstart_ml50_do035_b9_s7 EXISTS
================================================================================
Base attention-bias NDCG@5
attnbias_dstart_ml50_do035_b9_s42 EXISTS
attnbias_dstart_ml50_do035_b9_s2024 EXISTS
attnbias_dstart_ml50_do035_b9_s7 EXISTS

## Check planned refinement runs

In [11]:
planned_ndcg10 = [
    'attnbias_dstart_ml50_do035_b10_s42',
    'attnbias_dstart_ml50_do035_b10_s2024',
    'attnbias_dstart_ml50_do035_b10_s7',
]
planned_ndcg5 = [
    'attnbias_dstart_ml50_do035_b10_s42',
    'attnbias_dstart_ml50_do035_b10_s2024',
    'attnbias_dstart_ml50_do035_b10_s7',
]

for label, output_dir, run_names in [
    ('Refined attention-bias NDCG@10', Path(REFINE_ATTN_NDCG10_OUTPUT_DIR), planned_ndcg10),
    ('Refined attention-bias NDCG@5', Path(REFINE_ATTN_NDCG5_OUTPUT_DIR), planned_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Refined attention-bias NDCG@10
attnbias_dstart_ml50_do035_b10_s42 OK
attnbias_dstart_ml50_do035_b10_s2024 OK
attnbias_dstart_ml50_do035_b10_s7 OK
================================================================================
Refined attention-bias NDCG@5
attnbias_dstart_ml50_do035_b10_s42 OK
attnbias_dstart_ml50_do035_b10_s2024 OK
attnbias_dstart_ml50_do035_b10_s7 OK

## Train refined attention-bias runs for `NDCG@10`

### attnbias_dstart_ml50_do035_b10_s42

In [12]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b10_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 10,60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42
epoch=1, loss=0.5885
epoch=2, loss=0.2657
epoch=3, loss=0.2038
epoch=4, loss=0.1698
epoch=5, loss=0.1461
valid [full], NDCG@5: 0.6390, HR@5: 0.7473, NDCG@10: 0.6837, HR@10: 0.8904, MRR: 0.6315
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5570, NDCG@10: 0.5634, HR@10: 0.5806, MRR: 0.5720
test [full], NDCG@5: 0.5939, HR@5: 0.7428, NDCG@10: 0.6336, HR@10: 0.8731, MRR: 0.5682
test [sampled], NDCG@5: 0.2043, HR@5: 0.2093, NDCG@10: 0.2483, HR@10: 0.3516, MRR: 0.2488
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/sasrec_best.pth
epoch=6, loss=0.1315
epoch=7, loss=0.1217
epoch=8, loss=0.1136
epoch=9, loss=0.1089
epoch=10, loss=0.1069
valid [full], NDCG@5: 0.6768, HR@5: 0.8167, NDCG@10: 0.7232, HR@10: 0.9623, MRR: 0.6535
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5730, NDCG@10: 0.5776, HR@10: 0.6319, MRR: 0.5752
test [full], NDCG@5: 0.7030, HR@5: 0.9376, NDCG@10: 0.7238, HR@10: 0.9999, MRR: 0.6335
test [sampled], NDCG@5: 0.1871, HR@5: 0.2107, NDCG@10: 0.2433, HR@10: 0.3899, MRR: 0.2353
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/sasrec_best.pth
epoch=11, loss=0.1046
epoch=12, loss=0.1016
epoch=13, loss=0.0978
epoch=14, loss=0.0981
epoch=15, loss=0.0975
valid [full], NDCG@5: 0.7064, HR@5: 0.8670, NDCG@10: 0.7384, HR@10: 0.9706, MRR: 0.6688
valid [sampled], NDCG@5: 0.5687, HR@5: 0.5809, NDCG@10: 0.5880, HR@10: 0.6414, MRR: 0.5877
test [full], NDCG@5: 0.7365, HR@5: 0.9473, NDCG@10: 0.7537, HR@10: 1.0000, MRR: 0.6710
test [sampled], NDCG@5: 0.1410, HR@5: 0.2141, NDCG@10: 0.2204, HR@10: 0.4601, MRR: 0.1795
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/sasrec_best.pth
epoch=16, loss=0.0943
epoch=17, loss=0.0908
epoch=18, loss=0.0915
epoch=19, loss=0.0906
epoch=20, loss=0.0909
valid [full], NDCG@5: 0.6780, HR@5: 0.8068, NDCG@10: 0.7302, HR@10: 0.9711, MRR: 0.6596
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5728, NDCG@10: 0.5780, HR@10: 0.6220, MRR: 0.5791
test [full], NDCG@5: 0.7825, HR@5: 0.9211, NDCG@10: 0.8068, HR@10: 0.9999, MRR: 0.7443
test [sampled], NDCG@5: 0.1741, HR@5: 0.2688, NDCG@10: 0.2626, HR@10: 0.5413, MRR: 0.2034
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0885
epoch=22, loss=0.0883
epoch=23, loss=0.0880
epoch=24, loss=0.0875
epoch=25, loss=0.0872
valid [full], NDCG@5: 0.6976, HR@5: 0.8531, NDCG@10: 0.7302, HR@10: 0.9557, MRR: 0.6645
valid [sampled], NDCG@5: 0.5558, HR@5: 0.5663, NDCG@10: 0.5754, HR@10: 0.6278, MRR: 0.5747
test [full], NDCG@5: 0.8298, HR@5: 0.9437, NDCG@10: 0.8472, HR@10: 0.9999, MRR: 0.7979
test [sampled], NDCG@5: 0.2133, HR@5: 0.2975, NDCG@10: 0.2942, HR@10: 0.5461, MRR: 0.2451
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0860
epoch=27, loss=0.0871
epoch=28, loss=0.0861
epoch=29, loss=0.0870
epoch=30, loss=0.0863
valid [full], NDCG@5: 0.6753, HR@5: 0.8349, NDCG@10: 0.7189, HR@10: 0.9723, MRR: 0.6427
valid [sampled], NDCG@5: 0.5103, HR@5: 0.5223, NDCG@10: 0.5340, HR@10: 0.5966, MRR: 0.5325
test [full], NDCG@5: 0.8721, HR@5: 0.9385, NDCG@10: 0.8910, HR@10: 1.0000, MRR: 0.8563
test [sampled], NDCG@5: 0.3375, HR@5: 0.4167, NDCG@10: 0.4081, HR@10: 0.6339, MRR: 0.3614
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0864
epoch=32, loss=0.0850
epoch=33, loss=0.0854
epoch=34, loss=0.0841
epoch=35, loss=0.0827
valid [full], NDCG@5: 0.6914, HR@5: 0.8427, NDCG@10: 0.7344, HR@10: 0.9754, MRR: 0.6620
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5666, NDCG@10: 0.5755, HR@10: 0.6315, MRR: 0.5743
test [full], NDCG@5: 0.8700, HR@5: 0.9402, NDCG@10: 0.8889, HR@10: 1.0000, MRR: 0.8535
test [sampled], NDCG@5: 0.3607, HR@5: 0.4341, NDCG@10: 0.4243, HR@10: 0.6303, MRR: 0.3840
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0829
epoch=37, loss=0.0819
epoch=38, loss=0.0818
epoch=39, loss=0.0826
epoch=40, loss=0.0836
valid [full], NDCG@5: 0.6412, HR@5: 0.8253, NDCG@10: 0.6898, HR@10: 0.9759, MRR: 0.6036
valid [sampled], NDCG@5: 0.4713, HR@5: 0.4818, NDCG@10: 0.4888, HR@10: 0.5369, MRR: 0.4926
test [full], NDCG@5: 0.8724, HR@5: 0.9426, NDCG@10: 0.8900, HR@10: 1.0000, MRR: 0.8558
test [sampled], NDCG@5: 0.4208, HR@5: 0.4808, NDCG@10: 0.4702, HR@10: 0.6327, MRR: 0.4412
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0831
epoch=42, loss=0.0837
epoch=43, loss=0.0839
epoch=44, loss=0.0815
epoch=45, loss=0.0820
valid [full], NDCG@5: 0.6466, HR@5: 0.8424, NDCG@10: 0.6842, HR@10: 0.9610, MRR: 0.6009
valid [sampled], NDCG@5: 0.4568, HR@5: 0.4684, NDCG@10: 0.4742, HR@10: 0.5229, MRR: 0.4793
test [full], NDCG@5: 0.8869, HR@5: 0.9590, NDCG@10: 0.9006, HR@10: 1.0000, MRR: 0.8688
test [sampled], NDCG@5: 0.4055, HR@5: 0.4743, NDCG@10: 0.4635, HR@10: 0.6521, MRR: 0.4267
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0794
epoch=47, loss=0.0798
epoch=48, loss=0.0786
epoch=49, loss=0.0796
epoch=50, loss=0.0793
valid [full], NDCG@5: 0.6857, HR@5: 0.8348, NDCG@10: 0.7251, HR@10: 0.9600, MRR: 0.6555
valid [sampled], NDCG@5: 0.5233, HR@5: 0.5356, NDCG@10: 0.5480, HR@10: 0.6139, MRR: 0.5455
test [full], NDCG@5: 0.8977, HR@5: 0.9661, NDCG@10: 0.9093, HR@10: 1.0000, MRR: 0.8795
test [sampled], NDCG@5: 0.3781, HR@5: 0.4549, NDCG@10: 0.4441, HR@10: 0.6575, MRR: 0.4013
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s42/sasrec_last.pth

### attnbias_dstart_ml50_do035_b10_s2024

In [13]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b10_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 10,60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024
epoch=1, loss=0.6100
epoch=2, loss=0.2722
epoch=3, loss=0.1996
epoch=4, loss=0.1620
epoch=5, loss=0.1431
valid [full], NDCG@5: 0.6673, HR@5: 0.8155, NDCG@10: 0.7273, HR@10: 0.9900, MRR: 0.6480
valid [sampled], NDCG@5: 0.5491, HR@5: 0.5583, NDCG@10: 0.5606, HR@10: 0.5939, MRR: 0.5652
test [full], NDCG@5: 0.7594, HR@5: 0.9086, NDCG@10: 0.7896, HR@10: 1.0000, MRR: 0.7240
test [sampled], NDCG@5: 0.2071, HR@5: 0.2694, NDCG@10: 0.2644, HR@10: 0.4459, MRR: 0.2391
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/sasrec_best.pth
epoch=6, loss=0.1282
epoch=7, loss=0.1199
epoch=8, loss=0.1156
epoch=9, loss=0.1089
epoch=10, loss=0.1064
valid [full], NDCG@5: 0.6903, HR@5: 0.8648, NDCG@10: 0.7241, HR@10: 0.9714, MRR: 0.6510
valid [sampled], NDCG@5: 0.5445, HR@5: 0.5539, NDCG@10: 0.5565, HR@10: 0.5915, MRR: 0.5616
test [full], NDCG@5: 0.8345, HR@5: 0.9357, NDCG@10: 0.8541, HR@10: 1.0000, MRR: 0.8083
test [sampled], NDCG@5: 0.2321, HR@5: 0.3227, NDCG@10: 0.3105, HR@10: 0.5647, MRR: 0.2589
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1030
epoch=12, loss=0.0997
epoch=13, loss=0.0973
epoch=14, loss=0.0967
epoch=15, loss=0.0960
valid [full], NDCG@5: 0.6647, HR@5: 0.8099, NDCG@10: 0.7158, HR@10: 0.9700, MRR: 0.6420
valid [sampled], NDCG@5: 0.5502, HR@5: 0.5609, NDCG@10: 0.5615, HR@10: 0.5959, MRR: 0.5650
test [full], NDCG@5: 0.8703, HR@5: 0.9382, NDCG@10: 0.8899, HR@10: 1.0000, MRR: 0.8562
test [sampled], NDCG@5: 0.2225, HR@5: 0.3123, NDCG@10: 0.3133, HR@10: 0.5928, MRR: 0.2529
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0929
epoch=17, loss=0.0916
epoch=18, loss=0.0922
epoch=19, loss=0.0914
epoch=20, loss=0.0902
valid [full], NDCG@5: 0.7019, HR@5: 0.8513, NDCG@10: 0.7310, HR@10: 0.9458, MRR: 0.6687
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5657, NDCG@10: 0.5748, HR@10: 0.6188, MRR: 0.5773
test [full], NDCG@5: 0.8777, HR@5: 0.9417, NDCG@10: 0.8965, HR@10: 0.9999, MRR: 0.8640
test [sampled], NDCG@5: 0.3517, HR@5: 0.4072, NDCG@10: 0.4156, HR@10: 0.6058, MRR: 0.3819
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/sasrec_best.pth
epoch=21, loss=0.0885
epoch=22, loss=0.0861
epoch=23, loss=0.0861
epoch=24, loss=0.0875
epoch=25, loss=0.0857
valid [full], NDCG@5: 0.6870, HR@5: 0.8341, NDCG@10: 0.7222, HR@10: 0.9435, MRR: 0.6589
valid [sampled], NDCG@5: 0.5645, HR@5: 0.5781, NDCG@10: 0.5760, HR@10: 0.6133, MRR: 0.5778
test [full], NDCG@5: 0.8697, HR@5: 0.9370, NDCG@10: 0.8904, HR@10: 0.9999, MRR: 0.8563
test [sampled], NDCG@5: 0.3528, HR@5: 0.4252, NDCG@10: 0.4165, HR@10: 0.6219, MRR: 0.3753
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0827
epoch=27, loss=0.0819
epoch=28, loss=0.0816
epoch=29, loss=0.0836
epoch=30, loss=0.0798
valid [full], NDCG@5: 0.6895, HR@5: 0.8142, NDCG@10: 0.7234, HR@10: 0.9243, MRR: 0.6679
valid [sampled], NDCG@5: 0.5746, HR@5: 0.5860, NDCG@10: 0.5876, HR@10: 0.6261, MRR: 0.5884
test [full], NDCG@5: 0.8862, HR@5: 0.9470, NDCG@10: 0.9036, HR@10: 1.0000, MRR: 0.8733
test [sampled], NDCG@5: 0.3688, HR@5: 0.4349, NDCG@10: 0.4319, HR@10: 0.6296, MRR: 0.3936
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0802
epoch=32, loss=0.0797
epoch=33, loss=0.0779
epoch=34, loss=0.0792
epoch=35, loss=0.0773
valid [full], NDCG@5: 0.6937, HR@5: 0.8331, NDCG@10: 0.7179, HR@10: 0.9116, MRR: 0.6648
valid [sampled], NDCG@5: 0.5837, HR@5: 0.5955, NDCG@10: 0.5956, HR@10: 0.6324, MRR: 0.5966
test [full], NDCG@5: 0.8774, HR@5: 0.9404, NDCG@10: 0.8969, HR@10: 0.9999, MRR: 0.8645
test [sampled], NDCG@5: 0.3950, HR@5: 0.4624, NDCG@10: 0.4528, HR@10: 0.6393, MRR: 0.4162
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0786
epoch=37, loss=0.0769
epoch=38, loss=0.0758
epoch=39, loss=0.0766
epoch=40, loss=0.0750
valid [full], NDCG@5: 0.6930, HR@5: 0.8251, NDCG@10: 0.7236, HR@10: 0.9244, MRR: 0.6670
valid [sampled], NDCG@5: 0.5666, HR@5: 0.5775, NDCG@10: 0.5837, HR@10: 0.6313, MRR: 0.5831
test [full], NDCG@5: 0.8796, HR@5: 0.9430, NDCG@10: 0.8983, HR@10: 1.0000, MRR: 0.8664
test [sampled], NDCG@5: 0.3533, HR@5: 0.4175, NDCG@10: 0.4142, HR@10: 0.6062, MRR: 0.3793
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0760
epoch=42, loss=0.0767
epoch=43, loss=0.0759
epoch=44, loss=0.0740
epoch=45, loss=0.0748
valid [full], NDCG@5: 0.6690, HR@5: 0.7800, NDCG@10: 0.7134, HR@10: 0.9158, MRR: 0.6573
valid [sampled], NDCG@5: 0.5620, HR@5: 0.5755, NDCG@10: 0.5765, HR@10: 0.6203, MRR: 0.5764
test [full], NDCG@5: 0.7955, HR@5: 0.9492, NDCG@10: 0.8122, HR@10: 1.0000, MRR: 0.7492
test [sampled], NDCG@5: 0.3263, HR@5: 0.3367, NDCG@10: 0.3820, HR@10: 0.5153, MRR: 0.3735
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0734
epoch=47, loss=0.0752
epoch=48, loss=0.0745
epoch=49, loss=0.0733
epoch=50, loss=0.0758
valid [full], NDCG@5: 0.6908, HR@5: 0.8023, NDCG@10: 0.7299, HR@10: 0.9247, MRR: 0.6756
valid [sampled], NDCG@5: 0.5800, HR@5: 0.5928, NDCG@10: 0.5970, HR@10: 0.6456, MRR: 0.5951
test [full], NDCG@5: 0.8714, HR@5: 0.9327, NDCG@10: 0.8935, HR@10: 1.0000, MRR: 0.8597
test [sampled], NDCG@5: 0.3988, HR@5: 0.4665, NDCG@10: 0.4560, HR@10: 0.6417, MRR: 0.4197
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s2024/sasrec_last.pth

### attnbias_dstart_ml50_do035_b10_s7

In [14]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b10_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 10,60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7
epoch=1, loss=0.5907
epoch=2, loss=0.2821
epoch=3, loss=0.2070
epoch=4, loss=0.1717
epoch=5, loss=0.1501
valid [full], NDCG@5: 0.6362, HR@5: 0.7450, NDCG@10: 0.7027, HR@10: 0.9483, MRR: 0.6341
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5587, NDCG@10: 0.5621, HR@10: 0.5722, MRR: 0.5735
test [full], NDCG@5: 0.6338, HR@5: 0.7886, NDCG@10: 0.6792, HR@10: 0.9297, MRR: 0.6052
test [sampled], NDCG@5: 0.2451, HR@5: 0.2508, NDCG@10: 0.2872, HR@10: 0.3868, MRR: 0.2892
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=6, loss=0.1325
epoch=7, loss=0.1209
epoch=8, loss=0.1137
epoch=9, loss=0.1091
epoch=10, loss=0.1043
valid [full], NDCG@5: 0.6677, HR@5: 0.8071, NDCG@10: 0.7159, HR@10: 0.9563, MRR: 0.6471
valid [sampled], NDCG@5: 0.5557, HR@5: 0.5614, NDCG@10: 0.5636, HR@10: 0.5859, MRR: 0.5714
test [full], NDCG@5: 0.8419, HR@5: 0.9859, NDCG@10: 0.8468, HR@10: 1.0000, MRR: 0.7957
test [sampled], NDCG@5: 0.2684, HR@5: 0.3327, NDCG@10: 0.3345, HR@10: 0.5393, MRR: 0.3029
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=11, loss=0.1007
epoch=12, loss=0.0990
epoch=13, loss=0.0948
epoch=14, loss=0.0912
epoch=15, loss=0.0909
valid [full], NDCG@5: 0.6853, HR@5: 0.8589, NDCG@10: 0.7197, HR@10: 0.9685, MRR: 0.6467
valid [sampled], NDCG@5: 0.5550, HR@5: 0.5573, NDCG@10: 0.5619, HR@10: 0.5797, MRR: 0.5734
test [full], NDCG@5: 0.8273, HR@5: 0.9904, NDCG@10: 0.8307, HR@10: 1.0000, MRR: 0.7728
test [sampled], NDCG@5: 0.1972, HR@5: 0.2489, NDCG@10: 0.2772, HR@10: 0.5005, MRR: 0.2446
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=16, loss=0.0895
epoch=17, loss=0.0864
epoch=18, loss=0.0845
epoch=19, loss=0.0834
epoch=20, loss=0.0844
valid [full], NDCG@5: 0.7075, HR@5: 0.8500, NDCG@10: 0.7444, HR@10: 0.9686, MRR: 0.6775
valid [sampled], NDCG@5: 0.5637, HR@5: 0.5778, NDCG@10: 0.5941, HR@10: 0.6736, MRR: 0.5847
test [full], NDCG@5: 0.9490, HR@5: 0.9992, NDCG@10: 0.9493, HR@10: 1.0000, MRR: 0.9317
test [sampled], NDCG@5: 0.4222, HR@5: 0.5012, NDCG@10: 0.4973, HR@10: 0.7324, MRR: 0.4458
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=21, loss=0.0840
epoch=22, loss=0.0802
epoch=23, loss=0.0820
epoch=24, loss=0.0809
epoch=25, loss=0.0788
valid [full], NDCG@5: 0.7094, HR@5: 0.8438, NDCG@10: 0.7469, HR@10: 0.9666, MRR: 0.6820
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5809, NDCG@10: 0.5965, HR@10: 0.6740, MRR: 0.5872
test [full], NDCG@5: 0.9059, HR@5: 0.9942, NDCG@10: 0.9079, HR@10: 1.0000, MRR: 0.8765
test [sampled], NDCG@5: 0.3813, HR@5: 0.4481, NDCG@10: 0.4455, HR@10: 0.6469, MRR: 0.4082
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=26, loss=0.0796
epoch=27, loss=0.0789
epoch=28, loss=0.0792
epoch=29, loss=0.0781
epoch=30, loss=0.0756
valid [full], NDCG@5: 0.7055, HR@5: 0.8310, NDCG@10: 0.7474, HR@10: 0.9661, MRR: 0.6828
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5708, NDCG@10: 0.5881, HR@10: 0.6672, MRR: 0.5790
test [full], NDCG@5: 0.9005, HR@5: 0.9949, NDCG@10: 0.9022, HR@10: 1.0000, MRR: 0.8691
test [sampled], NDCG@5: 0.3780, HR@5: 0.4387, NDCG@10: 0.4422, HR@10: 0.6382, MRR: 0.4072
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=31, loss=0.0774
epoch=32, loss=0.0768
epoch=33, loss=0.0767
epoch=34, loss=0.0755
epoch=35, loss=0.0766
valid [full], NDCG@5: 0.6953, HR@5: 0.8187, NDCG@10: 0.7328, HR@10: 0.9391, MRR: 0.6737
valid [sampled], NDCG@5: 0.5603, HR@5: 0.5760, NDCG@10: 0.5906, HR@10: 0.6706, MRR: 0.5798
test [full], NDCG@5: 0.9135, HR@5: 0.9984, NDCG@10: 0.9141, HR@10: 1.0000, MRR: 0.8847
test [sampled], NDCG@5: 0.3771, HR@5: 0.4506, NDCG@10: 0.4472, HR@10: 0.6673, MRR: 0.4033
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0759
epoch=37, loss=0.0761
epoch=38, loss=0.0753
epoch=39, loss=0.0763
epoch=40, loss=0.0749
valid [full], NDCG@5: 0.7080, HR@5: 0.8469, NDCG@10: 0.7485, HR@10: 0.9754, MRR: 0.6803
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5725, NDCG@10: 0.5879, HR@10: 0.6593, MRR: 0.5818
test [full], NDCG@5: 0.9140, HR@5: 0.9996, NDCG@10: 0.9142, HR@10: 1.0000, MRR: 0.8850
test [sampled], NDCG@5: 0.3685, HR@5: 0.4307, NDCG@10: 0.4395, HR@10: 0.6512, MRR: 0.4000
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=41, loss=0.0783
epoch=42, loss=0.0737
epoch=43, loss=0.0751
epoch=44, loss=0.0742
epoch=45, loss=0.0741
valid [full], NDCG@5: 0.7197, HR@5: 0.8652, NDCG@10: 0.7533, HR@10: 0.9759, MRR: 0.6860
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5783, NDCG@10: 0.5945, HR@10: 0.6756, MRR: 0.5852
test [full], NDCG@5: 0.9210, HR@5: 0.9997, NDCG@10: 0.9211, HR@10: 1.0000, MRR: 0.8939
test [sampled], NDCG@5: 0.4350, HR@5: 0.5048, NDCG@10: 0.4934, HR@10: 0.6839, MRR: 0.4564
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=46, loss=0.0736
epoch=47, loss=0.0737
epoch=48, loss=0.0736
epoch=49, loss=0.0732
epoch=50, loss=0.0738
valid [full], NDCG@5: 0.7328, HR@5: 0.8604, NDCG@10: 0.7680, HR@10: 0.9749, MRR: 0.7065
valid [sampled], NDCG@5: 0.6109, HR@5: 0.6261, NDCG@10: 0.6333, HR@10: 0.6965, MRR: 0.6273
test [full], NDCG@5: 0.8482, HR@5: 0.9993, NDCG@10: 0.8484, HR@10: 1.0000, MRR: 0.7958
test [sampled], NDCG@5: 0.3938, HR@5: 0.4110, NDCG@10: 0.4611, HR@10: 0.6254, MRR: 0.4389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10/attnbias_dstart_ml50_do035_b10_s7/sasrec_last.pth

## Train refined attention-bias runs for `NDCG@5`

### attnbias_dstart_ml50_do035_b10_s42

In [15]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b10_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 10,60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42
epoch=1, loss=0.5885
epoch=2, loss=0.2657
epoch=3, loss=0.2038
epoch=4, loss=0.1698
epoch=5, loss=0.1461
valid [full], NDCG@5: 0.6390, HR@5: 0.7473, NDCG@10: 0.6837, HR@10: 0.8904, MRR: 0.6315
valid [sampled], NDCG@5: 0.5562, HR@5: 0.5570, NDCG@10: 0.5634, HR@10: 0.5806, MRR: 0.5720
test [full], NDCG@5: 0.5939, HR@5: 0.7428, NDCG@10: 0.6336, HR@10: 0.8731, MRR: 0.5682
test [sampled], NDCG@5: 0.2043, HR@5: 0.2093, NDCG@10: 0.2483, HR@10: 0.3516, MRR: 0.2488
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/sasrec_best.pth
epoch=6, loss=0.1315
epoch=7, loss=0.1217
epoch=8, loss=0.1136
epoch=9, loss=0.1089
epoch=10, loss=0.1069
valid [full], NDCG@5: 0.6768, HR@5: 0.8167, NDCG@10: 0.7232, HR@10: 0.9623, MRR: 0.6535
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5730, NDCG@10: 0.5776, HR@10: 0.6319, MRR: 0.5752
test [full], NDCG@5: 0.7030, HR@5: 0.9376, NDCG@10: 0.7238, HR@10: 0.9999, MRR: 0.6335
test [sampled], NDCG@5: 0.1871, HR@5: 0.2107, NDCG@10: 0.2433, HR@10: 0.3899, MRR: 0.2353
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/sasrec_best.pth
epoch=11, loss=0.1046
epoch=12, loss=0.1016
epoch=13, loss=0.0978
epoch=14, loss=0.0981
epoch=15, loss=0.0975
valid [full], NDCG@5: 0.7064, HR@5: 0.8670, NDCG@10: 0.7384, HR@10: 0.9706, MRR: 0.6688
valid [sampled], NDCG@5: 0.5687, HR@5: 0.5809, NDCG@10: 0.5880, HR@10: 0.6414, MRR: 0.5877
test [full], NDCG@5: 0.7365, HR@5: 0.9473, NDCG@10: 0.7537, HR@10: 1.0000, MRR: 0.6710
test [sampled], NDCG@5: 0.1410, HR@5: 0.2141, NDCG@10: 0.2204, HR@10: 0.4601, MRR: 0.1795
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/sasrec_best.pth
epoch=16, loss=0.0943
epoch=17, loss=0.0908
epoch=18, loss=0.0915
epoch=19, loss=0.0906
epoch=20, loss=0.0909
valid [full], NDCG@5: 0.6780, HR@5: 0.8068, NDCG@10: 0.7302, HR@10: 0.9711, MRR: 0.6596
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5728, NDCG@10: 0.5780, HR@10: 0.6220, MRR: 0.5791
test [full], NDCG@5: 0.7825, HR@5: 0.9211, NDCG@10: 0.8068, HR@10: 0.9999, MRR: 0.7443
test [sampled], NDCG@5: 0.1741, HR@5: 0.2688, NDCG@10: 0.2626, HR@10: 0.5413, MRR: 0.2034
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0885
epoch=22, loss=0.0883
epoch=23, loss=0.0880
epoch=24, loss=0.0875
epoch=25, loss=0.0872
valid [full], NDCG@5: 0.6976, HR@5: 0.8531, NDCG@10: 0.7302, HR@10: 0.9557, MRR: 0.6645
valid [sampled], NDCG@5: 0.5558, HR@5: 0.5663, NDCG@10: 0.5754, HR@10: 0.6278, MRR: 0.5747
test [full], NDCG@5: 0.8298, HR@5: 0.9437, NDCG@10: 0.8472, HR@10: 0.9999, MRR: 0.7979
test [sampled], NDCG@5: 0.2133, HR@5: 0.2975, NDCG@10: 0.2942, HR@10: 0.5461, MRR: 0.2451
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0860
epoch=27, loss=0.0871
epoch=28, loss=0.0861
epoch=29, loss=0.0870
epoch=30, loss=0.0863
valid [full], NDCG@5: 0.6753, HR@5: 0.8349, NDCG@10: 0.7189, HR@10: 0.9723, MRR: 0.6427
valid [sampled], NDCG@5: 0.5103, HR@5: 0.5223, NDCG@10: 0.5340, HR@10: 0.5966, MRR: 0.5325
test [full], NDCG@5: 0.8721, HR@5: 0.9385, NDCG@10: 0.8910, HR@10: 1.0000, MRR: 0.8563
test [sampled], NDCG@5: 0.3375, HR@5: 0.4167, NDCG@10: 0.4081, HR@10: 0.6339, MRR: 0.3614
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0864
epoch=32, loss=0.0850
epoch=33, loss=0.0854
epoch=34, loss=0.0841
epoch=35, loss=0.0827
valid [full], NDCG@5: 0.6914, HR@5: 0.8427, NDCG@10: 0.7344, HR@10: 0.9754, MRR: 0.6620
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5666, NDCG@10: 0.5755, HR@10: 0.6315, MRR: 0.5743
test [full], NDCG@5: 0.8700, HR@5: 0.9402, NDCG@10: 0.8889, HR@10: 1.0000, MRR: 0.8535
test [sampled], NDCG@5: 0.3607, HR@5: 0.4341, NDCG@10: 0.4243, HR@10: 0.6303, MRR: 0.3840
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0829
epoch=37, loss=0.0819
epoch=38, loss=0.0818
epoch=39, loss=0.0826
epoch=40, loss=0.0836
valid [full], NDCG@5: 0.6412, HR@5: 0.8253, NDCG@10: 0.6898, HR@10: 0.9759, MRR: 0.6036
valid [sampled], NDCG@5: 0.4713, HR@5: 0.4818, NDCG@10: 0.4888, HR@10: 0.5369, MRR: 0.4926
test [full], NDCG@5: 0.8724, HR@5: 0.9426, NDCG@10: 0.8900, HR@10: 1.0000, MRR: 0.8558
test [sampled], NDCG@5: 0.4208, HR@5: 0.4808, NDCG@10: 0.4702, HR@10: 0.6327, MRR: 0.4412
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0831
epoch=42, loss=0.0837
epoch=43, loss=0.0839
epoch=44, loss=0.0815
epoch=45, loss=0.0820
valid [full], NDCG@5: 0.6466, HR@5: 0.8424, NDCG@10: 0.6842, HR@10: 0.9610, MRR: 0.6009
valid [sampled], NDCG@5: 0.4568, HR@5: 0.4684, NDCG@10: 0.4742, HR@10: 0.5229, MRR: 0.4793
test [full], NDCG@5: 0.8869, HR@5: 0.9590, NDCG@10: 0.9006, HR@10: 1.0000, MRR: 0.8688
test [sampled], NDCG@5: 0.4055, HR@5: 0.4743, NDCG@10: 0.4635, HR@10: 0.6521, MRR: 0.4267
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0794
epoch=47, loss=0.0798
epoch=48, loss=0.0786
epoch=49, loss=0.0796
epoch=50, loss=0.0793
valid [full], NDCG@5: 0.6857, HR@5: 0.8348, NDCG@10: 0.7251, HR@10: 0.9600, MRR: 0.6555
valid [sampled], NDCG@5: 0.5233, HR@5: 0.5356, NDCG@10: 0.5480, HR@10: 0.6139, MRR: 0.5455
test [full], NDCG@5: 0.8977, HR@5: 0.9661, NDCG@10: 0.9093, HR@10: 1.0000, MRR: 0.8795
test [sampled], NDCG@5: 0.3781, HR@5: 0.4549, NDCG@10: 0.4441, HR@10: 0.6575, MRR: 0.4013
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s42/sasrec_last.pth

### attnbias_dstart_ml50_do035_b10_s2024

In [16]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b10_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 10,60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024
epoch=1, loss=0.6100
epoch=2, loss=0.2722
epoch=3, loss=0.1996
epoch=4, loss=0.1620
epoch=5, loss=0.1431
valid [full], NDCG@5: 0.6673, HR@5: 0.8155, NDCG@10: 0.7273, HR@10: 0.9900, MRR: 0.6480
valid [sampled], NDCG@5: 0.5491, HR@5: 0.5583, NDCG@10: 0.5606, HR@10: 0.5939, MRR: 0.5652
test [full], NDCG@5: 0.7594, HR@5: 0.9086, NDCG@10: 0.7896, HR@10: 1.0000, MRR: 0.7240
test [sampled], NDCG@5: 0.2071, HR@5: 0.2694, NDCG@10: 0.2644, HR@10: 0.4459, MRR: 0.2391
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/sasrec_best.pth
epoch=6, loss=0.1282
epoch=7, loss=0.1199
epoch=8, loss=0.1156
epoch=9, loss=0.1089
epoch=10, loss=0.1064
valid [full], NDCG@5: 0.6903, HR@5: 0.8648, NDCG@10: 0.7241, HR@10: 0.9714, MRR: 0.6510
valid [sampled], NDCG@5: 0.5445, HR@5: 0.5539, NDCG@10: 0.5565, HR@10: 0.5915, MRR: 0.5616
test [full], NDCG@5: 0.8345, HR@5: 0.9357, NDCG@10: 0.8541, HR@10: 1.0000, MRR: 0.8083
test [sampled], NDCG@5: 0.2321, HR@5: 0.3227, NDCG@10: 0.3105, HR@10: 0.5647, MRR: 0.2589
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/sasrec_best.pth
epoch=11, loss=0.1030
epoch=12, loss=0.0997
epoch=13, loss=0.0973
epoch=14, loss=0.0967
epoch=15, loss=0.0960
valid [full], NDCG@5: 0.6647, HR@5: 0.8099, NDCG@10: 0.7158, HR@10: 0.9700, MRR: 0.6420
valid [sampled], NDCG@5: 0.5502, HR@5: 0.5609, NDCG@10: 0.5615, HR@10: 0.5959, MRR: 0.5650
test [full], NDCG@5: 0.8703, HR@5: 0.9382, NDCG@10: 0.8899, HR@10: 1.0000, MRR: 0.8562
test [sampled], NDCG@5: 0.2225, HR@5: 0.3123, NDCG@10: 0.3133, HR@10: 0.5928, MRR: 0.2529
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0929
epoch=17, loss=0.0916
epoch=18, loss=0.0922
epoch=19, loss=0.0914
epoch=20, loss=0.0902
valid [full], NDCG@5: 0.7019, HR@5: 0.8513, NDCG@10: 0.7310, HR@10: 0.9458, MRR: 0.6687
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5657, NDCG@10: 0.5748, HR@10: 0.6188, MRR: 0.5773
test [full], NDCG@5: 0.8777, HR@5: 0.9417, NDCG@10: 0.8965, HR@10: 0.9999, MRR: 0.8640
test [sampled], NDCG@5: 0.3517, HR@5: 0.4072, NDCG@10: 0.4156, HR@10: 0.6058, MRR: 0.3819
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/sasrec_best.pth
epoch=21, loss=0.0885
epoch=22, loss=0.0861
epoch=23, loss=0.0861
epoch=24, loss=0.0875
epoch=25, loss=0.0857
valid [full], NDCG@5: 0.6870, HR@5: 0.8341, NDCG@10: 0.7222, HR@10: 0.9435, MRR: 0.6589
valid [sampled], NDCG@5: 0.5645, HR@5: 0.5781, NDCG@10: 0.5760, HR@10: 0.6133, MRR: 0.5778
test [full], NDCG@5: 0.8697, HR@5: 0.9370, NDCG@10: 0.8904, HR@10: 0.9999, MRR: 0.8563
test [sampled], NDCG@5: 0.3528, HR@5: 0.4252, NDCG@10: 0.4165, HR@10: 0.6219, MRR: 0.3753
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0827
epoch=27, loss=0.0819
epoch=28, loss=0.0816
epoch=29, loss=0.0836
epoch=30, loss=0.0798
valid [full], NDCG@5: 0.6895, HR@5: 0.8142, NDCG@10: 0.7234, HR@10: 0.9243, MRR: 0.6679
valid [sampled], NDCG@5: 0.5746, HR@5: 0.5860, NDCG@10: 0.5876, HR@10: 0.6261, MRR: 0.5884
test [full], NDCG@5: 0.8862, HR@5: 0.9470, NDCG@10: 0.9036, HR@10: 1.0000, MRR: 0.8733
test [sampled], NDCG@5: 0.3688, HR@5: 0.4349, NDCG@10: 0.4319, HR@10: 0.6296, MRR: 0.3936
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0802
epoch=32, loss=0.0797
epoch=33, loss=0.0779
epoch=34, loss=0.0792
epoch=35, loss=0.0773
valid [full], NDCG@5: 0.6937, HR@5: 0.8331, NDCG@10: 0.7179, HR@10: 0.9116, MRR: 0.6648
valid [sampled], NDCG@5: 0.5837, HR@5: 0.5955, NDCG@10: 0.5956, HR@10: 0.6324, MRR: 0.5966
test [full], NDCG@5: 0.8774, HR@5: 0.9404, NDCG@10: 0.8969, HR@10: 0.9999, MRR: 0.8645
test [sampled], NDCG@5: 0.3950, HR@5: 0.4624, NDCG@10: 0.4528, HR@10: 0.6393, MRR: 0.4162
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0786
epoch=37, loss=0.0769
epoch=38, loss=0.0758
epoch=39, loss=0.0766
epoch=40, loss=0.0750
valid [full], NDCG@5: 0.6930, HR@5: 0.8251, NDCG@10: 0.7236, HR@10: 0.9244, MRR: 0.6670
valid [sampled], NDCG@5: 0.5666, HR@5: 0.5775, NDCG@10: 0.5837, HR@10: 0.6313, MRR: 0.5831
test [full], NDCG@5: 0.8796, HR@5: 0.9430, NDCG@10: 0.8983, HR@10: 1.0000, MRR: 0.8664
test [sampled], NDCG@5: 0.3533, HR@5: 0.4175, NDCG@10: 0.4142, HR@10: 0.6062, MRR: 0.3793
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0760
epoch=42, loss=0.0767
epoch=43, loss=0.0759
epoch=44, loss=0.0740
epoch=45, loss=0.0748
valid [full], NDCG@5: 0.6690, HR@5: 0.7800, NDCG@10: 0.7134, HR@10: 0.9158, MRR: 0.6573
valid [sampled], NDCG@5: 0.5620, HR@5: 0.5755, NDCG@10: 0.5765, HR@10: 0.6203, MRR: 0.5764
test [full], NDCG@5: 0.7955, HR@5: 0.9492, NDCG@10: 0.8122, HR@10: 1.0000, MRR: 0.7492
test [sampled], NDCG@5: 0.3263, HR@5: 0.3367, NDCG@10: 0.3820, HR@10: 0.5153, MRR: 0.3735
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0734
epoch=47, loss=0.0752
epoch=48, loss=0.0745
epoch=49, loss=0.0733
epoch=50, loss=0.0758
valid [full], NDCG@5: 0.6908, HR@5: 0.8023, NDCG@10: 0.7299, HR@10: 0.9247, MRR: 0.6756
valid [sampled], NDCG@5: 0.5800, HR@5: 0.5928, NDCG@10: 0.5970, HR@10: 0.6456, MRR: 0.5951
test [full], NDCG@5: 0.8714, HR@5: 0.9327, NDCG@10: 0.8935, HR@10: 1.0000, MRR: 0.8597
test [sampled], NDCG@5: 0.3988, HR@5: 0.4665, NDCG@10: 0.4560, HR@10: 0.6417, MRR: 0.4197
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s2024/sasrec_last.pth

### attnbias_dstart_ml50_do035_b10_s7

In [17]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml50_do035_b10_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 10,60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7
epoch=1, loss=0.5907
epoch=2, loss=0.2821
epoch=3, loss=0.2070
epoch=4, loss=0.1717
epoch=5, loss=0.1501
valid [full], NDCG@5: 0.6362, HR@5: 0.7450, NDCG@10: 0.7027, HR@10: 0.9483, MRR: 0.6341
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5587, NDCG@10: 0.5621, HR@10: 0.5722, MRR: 0.5735
test [full], NDCG@5: 0.6338, HR@5: 0.7886, NDCG@10: 0.6792, HR@10: 0.9297, MRR: 0.6052
test [sampled], NDCG@5: 0.2451, HR@5: 0.2508, NDCG@10: 0.2872, HR@10: 0.3868, MRR: 0.2892
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=6, loss=0.1325
epoch=7, loss=0.1209
epoch=8, loss=0.1137
epoch=9, loss=0.1091
epoch=10, loss=0.1043
valid [full], NDCG@5: 0.6677, HR@5: 0.8071, NDCG@10: 0.7159, HR@10: 0.9563, MRR: 0.6471
valid [sampled], NDCG@5: 0.5557, HR@5: 0.5614, NDCG@10: 0.5636, HR@10: 0.5859, MRR: 0.5714
test [full], NDCG@5: 0.8419, HR@5: 0.9859, NDCG@10: 0.8468, HR@10: 1.0000, MRR: 0.7957
test [sampled], NDCG@5: 0.2684, HR@5: 0.3327, NDCG@10: 0.3345, HR@10: 0.5393, MRR: 0.3029
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=11, loss=0.1007
epoch=12, loss=0.0990
epoch=13, loss=0.0948
epoch=14, loss=0.0912
epoch=15, loss=0.0909
valid [full], NDCG@5: 0.6853, HR@5: 0.8589, NDCG@10: 0.7197, HR@10: 0.9685, MRR: 0.6467
valid [sampled], NDCG@5: 0.5550, HR@5: 0.5573, NDCG@10: 0.5619, HR@10: 0.5797, MRR: 0.5734
test [full], NDCG@5: 0.8273, HR@5: 0.9904, NDCG@10: 0.8307, HR@10: 1.0000, MRR: 0.7728
test [sampled], NDCG@5: 0.1972, HR@5: 0.2489, NDCG@10: 0.2772, HR@10: 0.5005, MRR: 0.2446
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=16, loss=0.0895
epoch=17, loss=0.0864
epoch=18, loss=0.0845
epoch=19, loss=0.0834
epoch=20, loss=0.0844
valid [full], NDCG@5: 0.7075, HR@5: 0.8500, NDCG@10: 0.7444, HR@10: 0.9686, MRR: 0.6775
valid [sampled], NDCG@5: 0.5637, HR@5: 0.5778, NDCG@10: 0.5941, HR@10: 0.6736, MRR: 0.5847
test [full], NDCG@5: 0.9490, HR@5: 0.9992, NDCG@10: 0.9493, HR@10: 1.0000, MRR: 0.9317
test [sampled], NDCG@5: 0.4222, HR@5: 0.5012, NDCG@10: 0.4973, HR@10: 0.7324, MRR: 0.4458
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=21, loss=0.0840
epoch=22, loss=0.0802
epoch=23, loss=0.0820
epoch=24, loss=0.0809
epoch=25, loss=0.0788
valid [full], NDCG@5: 0.7094, HR@5: 0.8438, NDCG@10: 0.7469, HR@10: 0.9666, MRR: 0.6820
valid [sampled], NDCG@5: 0.5670, HR@5: 0.5809, NDCG@10: 0.5965, HR@10: 0.6740, MRR: 0.5872
test [full], NDCG@5: 0.9059, HR@5: 0.9942, NDCG@10: 0.9079, HR@10: 1.0000, MRR: 0.8765
test [sampled], NDCG@5: 0.3813, HR@5: 0.4481, NDCG@10: 0.4455, HR@10: 0.6469, MRR: 0.4082
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=26, loss=0.0796
epoch=27, loss=0.0789
epoch=28, loss=0.0792
epoch=29, loss=0.0781
epoch=30, loss=0.0756
valid [full], NDCG@5: 0.7055, HR@5: 0.8310, NDCG@10: 0.7474, HR@10: 0.9661, MRR: 0.6828
valid [sampled], NDCG@5: 0.5576, HR@5: 0.5708, NDCG@10: 0.5881, HR@10: 0.6672, MRR: 0.5790
test [full], NDCG@5: 0.9005, HR@5: 0.9949, NDCG@10: 0.9022, HR@10: 1.0000, MRR: 0.8691
test [sampled], NDCG@5: 0.3780, HR@5: 0.4387, NDCG@10: 0.4422, HR@10: 0.6382, MRR: 0.4072
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0774
epoch=32, loss=0.0768
epoch=33, loss=0.0767
epoch=34, loss=0.0755
epoch=35, loss=0.0766
valid [full], NDCG@5: 0.6953, HR@5: 0.8187, NDCG@10: 0.7328, HR@10: 0.9391, MRR: 0.6737
valid [sampled], NDCG@5: 0.5603, HR@5: 0.5760, NDCG@10: 0.5906, HR@10: 0.6706, MRR: 0.5798
test [full], NDCG@5: 0.9135, HR@5: 0.9984, NDCG@10: 0.9141, HR@10: 1.0000, MRR: 0.8847
test [sampled], NDCG@5: 0.3771, HR@5: 0.4506, NDCG@10: 0.4472, HR@10: 0.6673, MRR: 0.4033
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0759
epoch=37, loss=0.0761
epoch=38, loss=0.0753
epoch=39, loss=0.0763
epoch=40, loss=0.0749
valid [full], NDCG@5: 0.7080, HR@5: 0.8469, NDCG@10: 0.7485, HR@10: 0.9754, MRR: 0.6803
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5725, NDCG@10: 0.5879, HR@10: 0.6593, MRR: 0.5818
test [full], NDCG@5: 0.9140, HR@5: 0.9996, NDCG@10: 0.9142, HR@10: 1.0000, MRR: 0.8850
test [sampled], NDCG@5: 0.3685, HR@5: 0.4307, NDCG@10: 0.4395, HR@10: 0.6512, MRR: 0.4000
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0783
epoch=42, loss=0.0737
epoch=43, loss=0.0751
epoch=44, loss=0.0742
epoch=45, loss=0.0741
valid [full], NDCG@5: 0.7197, HR@5: 0.8652, NDCG@10: 0.7533, HR@10: 0.9759, MRR: 0.6860
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5783, NDCG@10: 0.5945, HR@10: 0.6756, MRR: 0.5852
test [full], NDCG@5: 0.9210, HR@5: 0.9997, NDCG@10: 0.9211, HR@10: 1.0000, MRR: 0.8939
test [sampled], NDCG@5: 0.4350, HR@5: 0.5048, NDCG@10: 0.4934, HR@10: 0.6839, MRR: 0.4564
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
epoch=46, loss=0.0736
epoch=47, loss=0.0737
epoch=48, loss=0.0736
epoch=49, loss=0.0732
epoch=50, loss=0.0738
valid [full], NDCG@5: 0.7328, HR@5: 0.8604, NDCG@10: 0.7680, HR@10: 0.9749, MRR: 0.7065
valid [sampled], NDCG@5: 0.6109, HR@5: 0.6261, NDCG@10: 0.6333, HR@10: 0.6965, MRR: 0.6273
test [full], NDCG@5: 0.8482, HR@5: 0.9993, NDCG@10: 0.8484, HR@10: 1.0000, MRR: 0.7958
test [sampled], NDCG@5: 0.3938, HR@5: 0.4110, NDCG@10: 0.4611, HR@10: 0.6254, MRR: 0.4389
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg5/attnbias_dstart_ml50_do035_b10_s7/sasrec_last.pth

## Rebuild result tables

In [18]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'use_time_attention_bias': config.get('use_time_attention_bias', False),
            'time_modeling_mode': config.get('time_modeling_mode'),
            'time_encoding': config.get('time_encoding'),
            'time_delta_column': config.get('time_delta_column'),
            'time_bucket_boundaries_parsed': config.get('time_bucket_boundaries_parsed'),
            'time_attention_bias_bucket_count': config.get('time_attention_bias_bucket_count'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [19]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## NDCG@10 comparison summary

In [20]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
base_attn_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]
refine_attn_runs = [
    'attnbias_dstart_ml50_do035_b10_s42',
    'attnbias_dstart_ml50_do035_b10_s2024',
    'attnbias_dstart_ml50_do035_b10_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
base_attn_df = rebuild_df(BASE_ATTN_NDCG10_OUTPUT_DIR)
refine_attn_df = rebuild_df(REFINE_ATTN_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['time_variant'] = 'baseline'

base_attn_subset = base_attn_df[base_attn_df['run_name'].isin(base_attn_runs)].copy()
base_attn_subset['time_variant'] = 'attention_bias_b9_base'

refine_attn_subset = refine_attn_df[refine_attn_df['run_name'].isin(refine_attn_runs)].copy()
refine_attn_subset['time_variant'] = 'attention_bias_b10'

df_ndcg10 = pd.concat([baseline_subset, base_attn_subset, refine_attn_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'time_variant', 'time_delta_column', 'time_bucket_boundaries_parsed', 'time_attention_bias_bucket_count',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                               run_name  seed            time_variant    time_delta_column                   time_bucket_boundaries_parsed time_attention_bias_bucket_count  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     attnbias_dstart_ml50_do035_b10_s7     7      attention_bias_b10  delta_start_seconds  [10.0, 60.0, 600.0, 3600.0, 86400.0, 604800.0]                                8                 0.767971               0.974858                0.732792              0.860368             0.706519                0.848382              1.000000               0.848158             0.999323            0.795808                    0.633300                  0.696467                   0.610889                 0.626087                0.627294                   0.461120                 0.625440                  0.393811                0.411000               0.438855
1    attnbias_dstart_ml50_do035_b10_s42    42      attention_bias_b10  delta_start_seconds  [10.0, 60.0, 600.0, 3600.0, 86400.0, 604800.0]                                8                 0.738445               0.970552                0.706377              0.867010             0.668807                0.753725              1.000000               0.736480             0.947262            0.671027                    0.588010                  0.641400                   0.568729                 0.580867                0.587662                   0.220428                 0.460106                  0.141005                0.214082               0.179538
2  attnbias_dstart_ml50_do035_b10_s2024  2024      attention_bias_b10  delta_start_seconds  [10.0, 60.0, 600.0, 3600.0, 86400.0, 604800.0]                                8                 0.730977               0.945803                0.701896              0.851263             0.668709                0.896548              0.999865               0.877658             0.941724            0.863958                    0.574793                  0.618808                   0.558018                 0.565732                0.577309                   0.415633                 0.605827                  0.351656                0.407182               0.381936
3      attnbias_dstart_ml50_do035_b9_s7     7  attention_bias_b9_base  delta_start_seconds        [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.755366               0.953861                0.714870              0.824671             0.699184                0.846762              1.000000               0.846665             0.999728            0.793978                    0.623265                  0.666077                   0.607399                 0.615479                0.623619                   0.497216                 0.628223                  0.442098                0.450204               0.485290
4     attnbias_dstart_ml50_do035_b9_s42    42  attention_bias_b9_base  delta_start_seconds        [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.741856               0.969750                0.709565              0.864487             0.673783                0.785724              0.999865               0.764719             0.935724            0.714860                    0.585005                  0.635957                   0.566501                 0.577970                0.585189                   0.199334                 0.453522                  0.115783                0.193920               0.156593
5   attnbias_dstart_ml50_do035_b9_s2024  2024  attention_bias_b9_base  delta_start_seconds        [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.735385               0.971475                0.702964              0.865254             0.665031                0.885738              0.999865               0.863911             0.928234            0.850981                    0.566216                  0.612548                   0.548977                 0.558247                0.568592                   0.428086                 0.626287                  0.366083                0.436179               0.388188
6                  refine_ml50_do035_s7     7                baseline   delta_prev_seconds                                            None                             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
7                 refine_ml50_do035_s42    42                baseline   delta_prev_seconds                                            None                             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
8               refine_ml50_do035_s2024  2024                baseline   delta_prev_seconds                                            None                             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183

In [21]:
summary_ndcg10 = df_ndcg10.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

                       best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                          mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
time_variant
attention_bias_b10                    0.745798  0.019562              0.963738  0.015681               0.713688  0.016695             0.859547  0.007906            0.681345  0.021801               0.832885  0.072662             0.999955  0.000078              0.820765  0.074469            0.962770  0.031777           0.776931  0.097841                   0.598701  0.030684                 0.652225  0.039945                  0.579212  0.027951                0.590896  0.031402               0.597422  0.026383                  0.365727  0.127871                0.563791  0.090328                 0.295491  0.135439               0.344088  0.112605              0.333443  0.136290
attention_bias_b9_base                0.744203  0.010195              0.965029  0.009710               0.709133  0.005965             0.851471  0.023212            0.679333  0.017740               0.839408  0.050411             0.999910  0.000078              0.825099  0.052996            0.954562  0.039294           0.786607  0.068359                   0.591495  0.029073                 0.638194  0.026835                  0.574292  0.029980                0.583899  0.029073               0.592467  0.028226                  0.374879  0.155906                0.569344  0.100310                 0.307988  0.170739               0.360101  0.144087              0.343357  0.168872
baseline                              0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175

Interpretation guide for NDCG@10:
- compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` first
- then check whether the refined attention-bias boundaries improve over the original attention-bias run
- sampled and MRR are supplementary

## NDCG@5 comparison summary

In [22]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
base_attn_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]
refine_attn_runs = [
    'attnbias_dstart_ml50_do035_b10_s42',
    'attnbias_dstart_ml50_do035_b10_s2024',
    'attnbias_dstart_ml50_do035_b10_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
base_attn_df = rebuild_df(BASE_ATTN_NDCG5_OUTPUT_DIR)
refine_attn_df = rebuild_df(REFINE_ATTN_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['time_variant'] = 'baseline'

base_attn_subset = base_attn_df[base_attn_df['run_name'].isin(base_attn_runs)].copy()
base_attn_subset['time_variant'] = 'attention_bias_b9_base'

refine_attn_subset = refine_attn_df[refine_attn_df['run_name'].isin(refine_attn_runs)].copy()
refine_attn_subset['time_variant'] = 'attention_bias_b10'

df_ndcg5 = pd.concat([baseline_subset, base_attn_subset, refine_attn_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'time_variant', 'time_delta_column', 'time_bucket_boundaries_parsed', 'time_attention_bias_bucket_count',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                               run_name  seed            time_variant    time_delta_column                   time_bucket_boundaries_parsed time_attention_bias_bucket_count  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     attnbias_dstart_ml50_do035_b10_s7     7      attention_bias_b10  delta_start_seconds  [10.0, 60.0, 600.0, 3600.0, 86400.0, 604800.0]                                8                 0.767971               0.974858                0.732792              0.860368             0.706519                0.848382              1.000000               0.848158             0.999323            0.795808                    0.633300                  0.696467                   0.610889                 0.626087                0.627294                   0.461120                 0.625440                  0.393811                0.411000               0.438855
1    attnbias_dstart_ml50_do035_b10_s42    42      attention_bias_b10  delta_start_seconds  [10.0, 60.0, 600.0, 3600.0, 86400.0, 604800.0]                                8                 0.738445               0.970552                0.706377              0.867010             0.668807                0.753725              1.000000               0.736480             0.947262            0.671027                    0.588010                  0.641400                   0.568729                 0.580867                0.587662                   0.220428                 0.460106                  0.141005                0.214082               0.179538
2  attnbias_dstart_ml50_do035_b10_s2024  2024      attention_bias_b10  delta_start_seconds  [10.0, 60.0, 600.0, 3600.0, 86400.0, 604800.0]                                8                 0.730977               0.945803                0.701896              0.851263             0.668709                0.896548              0.999865               0.877658             0.941724            0.863958                    0.574793                  0.618808                   0.558018                 0.565732                0.577309                   0.415633                 0.605827                  0.351656                0.407182               0.381936
3      attnbias_dstart_ml50_do035_b9_s7     7  attention_bias_b9_base  delta_start_seconds        [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.765708               0.975845                0.728865              0.854661             0.703877                0.847794              1.000000               0.847697             0.999728            0.795264                    0.625614                  0.676007                   0.606813                 0.616159                0.624051                   0.500175                 0.632429                  0.444546                0.452782               0.487732
4     attnbias_dstart_ml50_do035_b9_s42    42  attention_bias_b9_base  delta_start_seconds        [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.741824               0.969750                0.709060              0.862317             0.673822                0.783187              0.999865               0.763183             0.935995            0.711912                    0.585252                  0.636770                   0.566501                 0.577970                0.585234                   0.194366                 0.445244                  0.112266                0.190256               0.152804
5   attnbias_dstart_ml50_do035_b9_s2024  2024  attention_bias_b9_base  delta_start_seconds        [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.741407               0.975616                0.712340              0.881719             0.670798                0.894503              0.999865               0.878950             0.952884            0.861072                    0.572542                  0.619131                   0.554208                 0.560547                0.576476                   0.456145                 0.618822                  0.406179                0.464726               0.428497
6                  refine_ml50_do035_s7     7                baseline   delta_prev_seconds                                            None                             None                 0.728826               0.961737                0.696223              0.857259             0.660451                0.872416              1.000000               0.859037             0.957678            0.831208                    0.577254                  0.611043                   0.565802                 0.575315                0.581977                   0.403018                 0.656933                  0.324827                0.417493               0.345750
7                 refine_ml50_do035_s42    42                baseline   delta_prev_seconds                                            None                             None                 0.735378               0.977276                0.697410              0.854186             0.663510                0.891774              1.000000               0.868726             0.926375            0.858375                    0.568693                  0.606441                   0.555385                 0.565093                0.572753                   0.456024                 0.640631                  0.399455                0.467411               0.419230
8               refine_ml50_do035_s2024  2024                baseline   delta_prev_seconds                                            None                             None                 0.741573               0.992973                0.713154              0.906351             0.664353                0.775861              1.000000               0.727453             0.850196            0.707187                    0.572972                  0.597043                   0.563603                 0.567069                0.582973                   0.257972                 0.431769                  0.203548                0.264514               0.234183

In [23]:
summary_ndcg5 = df_ndcg5.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

                       best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                          mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
time_variant
attention_bias_b10                    0.745798  0.019562              0.963738  0.015681               0.713688  0.016695             0.859547  0.007906            0.681345  0.021801               0.832885  0.072662             0.999955  0.000078              0.820765  0.074469            0.962770  0.031777           0.776931  0.097841                   0.598701  0.030684                 0.652225  0.039945                  0.579212  0.027951                0.590896  0.031402               0.597422  0.026383                  0.365727  0.127871                0.563791  0.090328                 0.295491  0.135439               0.344088  0.112605              0.333443  0.136290
attention_bias_b9_base                0.749646  0.013911              0.973737  0.003455               0.716755  0.010615             0.866232  0.013947            0.682833  0.018287               0.841828  0.055897             0.999910  0.000078              0.829944  0.059891            0.962869  0.033019           0.789416  0.074752                   0.594469  0.027711                 0.643969  0.029113                  0.575841  0.027518                0.584892  0.028445               0.595254  0.025321                  0.383562  0.165321                0.565498  0.104365                 0.320997  0.181781               0.369255  0.155132              0.356344  0.178742
baseline                              0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053               0.846684  0.062093             1.000000  0.000000              0.818405  0.078916            0.911416  0.055280           0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                  0.372338  0.102528                0.576445  0.125558                 0.309277  0.098875               0.383139  0.105721              0.333054  0.093175

Interpretation guide for NDCG@5:
- compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` first
- then check whether the refined attention-bias boundaries improve over the original attention-bias run
- sampled and MRR are supplementary