# SASRec Stage 3 Refine Sinusoidal Multi-Task BPI2012 Colab Train 10

This notebook tests Stage 3 multi-task learning with the
`refine_ml50_do035 + delta_start + sinusoidal` time-aware setting.

New experiments:
- `refine_sinusoidal_multi_task_w1.0`
- `refine_sinusoidal_multi_task_w0.1`

Main comparison groups:
- `refine_baseline`
- `refine_attnbias_single_task`
- `refine_sinusoidal_single_task`
- `refine_multi_task_w1.0`
- `refine_attnbias_multi_task_w1.0`
- `refine_sinusoidal_multi_task_w1.0`
- `refine_sinusoidal_multi_task_w0.1`

Main comparison metric:
- `full ranking + NDCG@10`

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.11.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only_stage3_v2'
BASELINE_NDCG10_OUTPUT_DIR = f'{DRIVE_ROOT}/outputs/sasrec_bpi2012_ndcg10'
SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR = f'{DRIVE_ROOT}/outputs/sasrec_timeaware_attention_bias_ndcg10'
SINGLE_TASK_SINUSOIDAL_NDCG10_OUTPUT_DIR = f'{DRIVE_ROOT}/outputs/sasrec_timeaware_sinusoidal_ndcg10'
MULTITASK_BASELINE_OUTPUT_DIR = f'{DRIVE_ROOT}/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2'
MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR = f'{DRIVE_ROOT}/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2'
MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR = f'{DRIVE_ROOT}/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1'
MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR = f'{DRIVE_ROOT}/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR:', SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR)
print('SINGLE_TASK_SINUSOIDAL_NDCG10_OUTPUT_DIR:', SINGLE_TASK_SINUSOIDAL_NDCG10_OUTPUT_DIR)
print('MULTITASK_BASELINE_OUTPUT_DIR:', MULTITASK_BASELINE_OUTPUT_DIR)
print('MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR:', MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR)
print('MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR:', MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR)
print('MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR:', MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR)
print('NOTEBOOK_DIR:', NOTEBOOK_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10
SINGLE_TASK_SINUSOIDAL_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10
MULTITASK_BASELINE_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_baseline_multitask_ndcg10_v2
MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_attention_bias_multitask_ndcg10_v2
MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1
MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1
NOTEBOOK_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/notebooks

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR"
!mkdir -p "$SINGLE_TASK_SINUSOIDAL_NDCG10_OUTPUT_DIR"
!mkdir -p "$MULTITASK_BASELINE_OUTPUT_DIR"
!mkdir -p "$MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR"
!mkdir -p "$MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR"
!mkdir -p "$MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.11.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.5)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

## Prepare Stage 3 processed dataset

This notebook regenerates the Stage 3 dataset into the versioned Drive folder
before training, so the run does not depend on any stale local processed files.

In [8]:
%cd /content/time-aware-behavior-prediction
!python scripts/regenerate_stage3_processed_dataset.py --output-dir "$DATA_DIR" --backup-existing
!ls "$DATA_DIR"

/content/time-aware-behavior-prediction
[info] moved existing output to backup: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2__backup_20260614_055854
[ok] regenerated Stage 3 processed dataset at: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2
[ok] metadata written to: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only_stage3_v2/stage3_dataset_metadata.json
{
  "timestamp": 0,
  "delta_prev_seconds": 0,
  "delta_start_seconds": 0,
  "delta_next_seconds": 0
}
events_complete_only_filtered.csv  sasrec_interactions.csv	 user_map.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   stage3_dataset_metadata.json

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!rm -rf data/processed/bpi2012_complete_only_stage3_v2
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only_stage3_v2

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv	 user_map.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   stage3_dataset_metadata.json

In [10]:
import pandas as pd

time_features_path = 'data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv'
df = pd.read_csv(time_features_path)
required_cols = ['delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds']
missing = [c for c in required_cols if c not in df.columns]

if missing:
    raise ValueError(f'Missing required Stage 3 columns: {missing}')

print('Stage 3 processed file is ready.')
print(df.columns.tolist())
df[['user_id', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds']].head()

Stage 3 processed file is ready.
['case_id', 'activity', 'lifecycle', 'timestamp', 'event_idx', 'delta_prev_seconds', 'delta_start_seconds', 'delta_next_seconds', 'user_id', 'item_id']

,user_id,event_idx,delta_prev_seconds,delta_start_seconds,delta_next_seconds
0,1,0,0.000,0.000,0.334
1,1,1,0.334,0.334,53.026
2,1,2,53.026,53.360,39785.402
3,1,3,39785.402,39838.762,145.935
4,1,4,145.935,39984.697,-0.000

## Experiment design

This notebook tests the `refine_ml50_do035 + sinusoidal + delta_start_seconds` setting with:
- multi-task `time_loss_weight=1.0`
- multi-task `time_loss_weight=0.1`

Fixed settings:
- backbone: `refine_ml50_do035`
- time-aware input: `delta_start_seconds`
- time encoding: `sinusoidal`
- multi-task outputs: `next activity + next time`
- time target: `delta_next_seconds`
- time target transform: `log1p`
- time loss: `huber`
- best epoch criterion: `full_valid_ndcg@10`
- final comparison uses all 3 seeds: `42`, `2024`, `7`

## Check prerequisite reference runs

In [11]:
from pathlib import Path

baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
single_task_attnbias_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]
single_task_sinusoidal_runs = [
    'timeaware_dstart_sinusoidal_ml50_do035_s42',
    'timeaware_dstart_sinusoidal_ml50_do035_s2024',
    'timeaware_dstart_sinusoidal_ml50_do035_s7',
]
multitask_baseline_runs = [
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]
multitask_attnbias_runs = [
    'multitask_attnbias_dstart_ml50_do035_b9_s42',
    'multitask_attnbias_dstart_ml50_do035_b9_s2024',
    'multitask_attnbias_dstart_ml50_do035_b9_s7',
]

checks = [
    ('baseline', BASELINE_NDCG10_OUTPUT_DIR, baseline_runs),
    ('single-task attention bias', SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR, single_task_attnbias_runs),
    ('single-task sinusoidal', SINGLE_TASK_SINUSOIDAL_NDCG10_OUTPUT_DIR, single_task_sinusoidal_runs),
    ('multi-task baseline', MULTITASK_BASELINE_OUTPUT_DIR, multitask_baseline_runs),
    ('multi-task attention bias', MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR, multitask_attnbias_runs),
]

print('=' * 80)
for label, output_dir, run_names in checks:
    print(label)
    base = Path(output_dir)
    for run_name in run_names:
        run_dir = base / run_name
        print(' ', run_name, 'EXISTS' if run_dir.exists() else 'MISSING')
    print('-' * 80)

================================================================================
baseline
  refine_ml50_do035_s42 EXISTS
  refine_ml50_do035_s2024 EXISTS
  refine_ml50_do035_s7 EXISTS
--------------------------------------------------------------------------------
single-task attention bias
  attnbias_dstart_ml50_do035_b9_s42 EXISTS
  attnbias_dstart_ml50_do035_b9_s2024 EXISTS
  attnbias_dstart_ml50_do035_b9_s7 EXISTS
--------------------------------------------------------------------------------
single-task sinusoidal
  timeaware_dstart_sinusoidal_ml50_do035_s42 EXISTS
  timeaware_dstart_sinusoidal_ml50_do035_s2024 EXISTS
  timeaware_dstart_sinusoidal_ml50_do035_s7 EXISTS
--------------------------------------------------------------------------------
multi-task baseline
  multitask_refine_ml50_do035_s42 EXISTS
  multitask_refine_ml50_do035_s2024 EXISTS
  multitask_refine_ml50_do035_s7 EXISTS
--------------------------------------------------------------------------------
multi-task attention bias
  multitask_attnbias_dstart_ml50_do035_b9_s42 EXISTS
  multitask_attnbias_dstart_ml50_do035_b9_s2024 EXISTS
  multitask_attnbias_dstart_ml50_do035_b9_s7 EXISTS
--------------------------------------------------------------------------------

## Check planned refine sinusoidal multi-task runs

In [12]:
planned_sinusoidal_multitask_runs = [
    'multitask_sinusoidal_dstart_ml50_do035_s42',
    'multitask_sinusoidal_dstart_ml50_do035_s2024',
    'multitask_sinusoidal_dstart_ml50_do035_s7',
    'multitask_sinusoidal_dstart_ml50_do035_w01_s42',
    'multitask_sinusoidal_dstart_ml50_do035_w01_s2024',
    'multitask_sinusoidal_dstart_ml50_do035_w01_s7',
]

checks = [
    ('w1.0', MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR),
    ('w0.1', MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR),
]

for label, output_dir in checks:
    base = Path(output_dir)
    print('=' * 80)
    print(f'Stage 3 refine sinusoidal multi-task runs ({label})')
    for run_name in planned_sinusoidal_multitask_runs:
        if (label == 'w1.0' and '_w01_' in run_name) or (label == 'w0.1' and '_w01_' not in run_name):
            continue
        run_dir = base / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Stage 3 refine sinusoidal multi-task runs (w1.0)
multitask_sinusoidal_dstart_ml50_do035_s42 OK
multitask_sinusoidal_dstart_ml50_do035_s2024 OK
multitask_sinusoidal_dstart_ml50_do035_s7 OK
================================================================================
Stage 3 refine sinusoidal multi-task runs (w0.1)
multitask_sinusoidal_dstart_ml50_do035_w01_s42 OK
multitask_sinusoidal_dstart_ml50_do035_w01_s2024 OK
multitask_sinusoidal_dstart_ml50_do035_w01_s7 OK

## Train refine sinusoidal multi-task w1.0 runs

### `multitask_sinusoidal_dstart_ml50_do035_s42`

In [13]:
!python src/train_sasrec.py \
  --run_name multitask_sinusoidal_dstart_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42
epoch=1, loss=3.0630
epoch=2, loss=1.7418
epoch=3, loss=1.5198
epoch=4, loss=1.4067
epoch=5, loss=1.3391
valid [task], Top5Acc: 0.4277, Top10Acc: 0.7182, Acc: 0.0517, MacroF1: 0.0710, TimeMAE: 69017.3724, TimeRMSE: 276935.1032, TimeMedAE: 1538.7991
valid [full], NDCG@5: 0.5866, HR@5: 0.6815, NDCG@10: 0.6812, HR@10: 0.9735, MRR: 0.5978
valid [sampled], NDCG@5: 0.5042, HR@5: 0.5063, NDCG@10: 0.5092, HR@10: 0.5219, MRR: 0.5197
test [task], Top5Acc: 0.1981, Top10Acc: 0.5458, Acc: 0.0116, MacroF1: 0.0115, TimeMAE: 11707.1033, TimeRMSE: 83386.5128, TimeMedAE: 7.5330
test [full], NDCG@5: 0.6804, HR@5: 0.8687, NDCG@10: 0.6979, HR@10: 0.9220, MRR: 0.6315
test [sampled], NDCG@5: 0.1078, HR@5: 0.1256, NDCG@10: 0.1505, HR@10: 0.2606, MRR: 0.1566
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=1.2996
epoch=7, loss=1.2591
epoch=8, loss=1.2435
epoch=9, loss=1.2311
epoch=10, loss=1.1994
valid [task], Top5Acc: 0.3974, Top10Acc: 0.7776, Acc: 0.0587, MacroF1: 0.1255, TimeMAE: 70237.3520, TimeRMSE: 282713.7139, TimeMedAE: 1246.7069
valid [full], NDCG@5: 0.6508, HR@5: 0.7655, NDCG@10: 0.7164, HR@10: 0.9713, MRR: 0.6431
valid [sampled], NDCG@5: 0.5529, HR@5: 0.5553, NDCG@10: 0.5593, HR@10: 0.5755, MRR: 0.5684
test [task], Top5Acc: 0.0447, Top10Acc: 0.4064, Acc: 0.0118, MacroF1: 0.0131, TimeMAE: 12015.1020, TimeRMSE: 80836.2323, TimeMedAE: 8.3435
test [full], NDCG@5: 0.5614, HR@5: 0.7626, NDCG@10: 0.6384, HR@10: 1.0000, MRR: 0.5278
test [sampled], NDCG@5: 0.0686, HR@5: 0.0725, NDCG@10: 0.0929, HR@10: 0.1509, MRR: 0.1154
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=1.1856
epoch=12, loss=1.1792
epoch=13, loss=1.1674
epoch=14, loss=1.1664
epoch=15, loss=1.1578
valid [task], Top5Acc: 0.4574, Top10Acc: 0.7879, Acc: 0.0530, MacroF1: 0.0899, TimeMAE: 72056.1756, TimeRMSE: 282909.3738, TimeMedAE: 803.4192
valid [full], NDCG@5: 0.6854, HR@5: 0.7917, NDCG@10: 0.7370, HR@10: 0.9620, MRR: 0.6744
valid [sampled], NDCG@5: 0.6033, HR@5: 0.6048, NDCG@10: 0.6066, HR@10: 0.6149, MRR: 0.6156
test [task], Top5Acc: 0.3125, Top10Acc: 0.5472, Acc: 0.0111, MacroF1: 0.0125, TimeMAE: 11341.9503, TimeRMSE: 74731.8295, TimeMedAE: 8.7000
test [full], NDCG@5: 0.7504, HR@5: 0.9417, NDCG@10: 0.7688, HR@10: 1.0000, MRR: 0.6932
test [sampled], NDCG@5: 0.1423, HR@5: 0.1573, NDCG@10: 0.1953, HR@10: 0.3256, MRR: 0.1962
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=1.1467
epoch=17, loss=1.1397
epoch=18, loss=1.1439
epoch=19, loss=1.1308
epoch=20, loss=1.1259
valid [task], Top5Acc: 0.4428, Top10Acc: 0.7500, Acc: 0.0533, MacroF1: 0.0921, TimeMAE: 71636.3838, TimeRMSE: 281997.8520, TimeMedAE: 1265.6190
valid [full], NDCG@5: 0.6910, HR@5: 0.8053, NDCG@10: 0.7398, HR@10: 0.9621, MRR: 0.6770
valid [sampled], NDCG@5: 0.5992, HR@5: 0.6001, NDCG@10: 0.6020, HR@10: 0.6092, MRR: 0.6126
test [task], Top5Acc: 0.3271, Top10Acc: 0.6213, Acc: 0.0120, MacroF1: 0.0116, TimeMAE: 12457.2024, TimeRMSE: 73800.8119, TimeMedAE: 37.2097
test [full], NDCG@5: 0.8261, HR@5: 0.9714, NDCG@10: 0.8353, HR@10: 1.0000, MRR: 0.7814
test [sampled], NDCG@5: 0.1996, HR@5: 0.2398, NDCG@10: 0.2643, HR@10: 0.4420, MRR: 0.2433
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/sasrec_best.pth
epoch=21, loss=1.1279
epoch=22, loss=1.1263
epoch=23, loss=1.1115
epoch=24, loss=1.1097
epoch=25, loss=1.1077
valid [task], Top5Acc: 0.4438, Top10Acc: 0.7224, Acc: 0.0565, MacroF1: 0.0648, TimeMAE: 72724.4567, TimeRMSE: 293682.4449, TimeMedAE: 1369.6380
valid [full], NDCG@5: 0.6967, HR@5: 0.8148, NDCG@10: 0.7384, HR@10: 0.9482, MRR: 0.6798
valid [sampled], NDCG@5: 0.5981, HR@5: 0.5990, NDCG@10: 0.6027, HR@10: 0.6137, MRR: 0.6123
test [task], Top5Acc: 0.3972, Top10Acc: 0.6683, Acc: 0.0134, MacroF1: 0.0111, TimeMAE: 12025.6411, TimeRMSE: 76891.0790, TimeMedAE: 37.4996
test [full], NDCG@5: 0.8437, HR@5: 0.9819, NDCG@10: 0.8500, HR@10: 0.9999, MRR: 0.8010
test [sampled], NDCG@5: 0.2524, HR@5: 0.2902, NDCG@10: 0.3115, HR@10: 0.4756, MRR: 0.2923
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1009
epoch=27, loss=1.1015
epoch=28, loss=1.1001
epoch=29, loss=1.1000
epoch=30, loss=1.0961
valid [task], Top5Acc: 0.3991, Top10Acc: 0.6576, Acc: 0.0581, MacroF1: 0.0765, TimeMAE: 72522.9985, TimeRMSE: 282452.1149, TimeMedAE: 1592.1552
valid [full], NDCG@5: 0.7126, HR@5: 0.8742, NDCG@10: 0.7399, HR@10: 0.9631, MRR: 0.6740
valid [sampled], NDCG@5: 0.5658, HR@5: 0.5681, NDCG@10: 0.5742, HR@10: 0.5947, MRR: 0.5835
test [task], Top5Acc: 0.4080, Top10Acc: 0.7464, Acc: 0.0197, MacroF1: 0.0167, TimeMAE: 12800.0944, TimeRMSE: 79250.0261, TimeMedAE: 50.3665
test [full], NDCG@5: 0.8563, HR@5: 0.9999, NDCG@10: 0.8564, HR@10: 1.0000, MRR: 0.8078
test [sampled], NDCG@5: 0.2516, HR@5: 0.2799, NDCG@10: 0.3171, HR@10: 0.4859, MRR: 0.2986
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/sasrec_best.pth
epoch=31, loss=1.0969
epoch=32, loss=1.0909
epoch=33, loss=1.0924
epoch=34, loss=1.0857
epoch=35, loss=1.0892
valid [task], Top5Acc: 0.3694, Top10Acc: 0.6106, Acc: 0.0567, MacroF1: 0.0784, TimeMAE: 69075.5512, TimeRMSE: 280043.2974, TimeMedAE: 1401.0829
valid [full], NDCG@5: 0.6851, HR@5: 0.8387, NDCG@10: 0.7185, HR@10: 0.9476, MRR: 0.6518
valid [sampled], NDCG@5: 0.5333, HR@5: 0.5370, NDCG@10: 0.5420, HR@10: 0.5643, MRR: 0.5516
test [task], Top5Acc: 0.4262, Top10Acc: 0.7055, Acc: 0.0165, MacroF1: 0.0154, TimeMAE: 11455.2809, TimeRMSE: 71251.6210, TimeMedAE: 50.7236
test [full], NDCG@5: 0.8715, HR@5: 0.9996, NDCG@10: 0.8717, HR@10: 1.0000, MRR: 0.8284
test [sampled], NDCG@5: 0.2832, HR@5: 0.3174, NDCG@10: 0.3449, HR@10: 0.5119, MRR: 0.3249
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.0871
epoch=37, loss=1.0822
epoch=38, loss=1.0754
epoch=39, loss=1.0927
epoch=40, loss=1.0763
valid [task], Top5Acc: 0.3567, Top10Acc: 0.6161, Acc: 0.0540, MacroF1: 0.0765, TimeMAE: 67688.3859, TimeRMSE: 268008.2090, TimeMedAE: 1495.6247
valid [full], NDCG@5: 0.6973, HR@5: 0.8664, NDCG@10: 0.7204, HR@10: 0.9415, MRR: 0.6560
valid [sampled], NDCG@5: 0.5396, HR@5: 0.5433, NDCG@10: 0.5492, HR@10: 0.5735, MRR: 0.5583
test [task], Top5Acc: 0.4115, Top10Acc: 0.7029, Acc: 0.0267, MacroF1: 0.0182, TimeMAE: 11035.0730, TimeRMSE: 64376.8964, TimeMedAE: 46.1426
test [full], NDCG@5: 0.8621, HR@5: 1.0000, NDCG@10: 0.8621, HR@10: 1.0000, MRR: 0.8152
test [sampled], NDCG@5: 0.2878, HR@5: 0.3186, NDCG@10: 0.3448, HR@10: 0.4982, MRR: 0.3299
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.0829
epoch=42, loss=1.0811
epoch=43, loss=1.0875
epoch=44, loss=1.0853
epoch=45, loss=1.0820
valid [task], Top5Acc: 0.4208, Top10Acc: 0.6939, Acc: 0.0552, MacroF1: 0.0667, TimeMAE: 72837.3616, TimeRMSE: 281468.8257, TimeMedAE: 4678.9436
valid [full], NDCG@5: 0.7104, HR@5: 0.8794, NDCG@10: 0.7300, HR@10: 0.9450, MRR: 0.6674
valid [sampled], NDCG@5: 0.5531, HR@5: 0.5567, NDCG@10: 0.5628, HR@10: 0.5872, MRR: 0.5714
test [task], Top5Acc: 0.5000, Top10Acc: 0.7254, Acc: 0.0163, MacroF1: 0.0124, TimeMAE: 13317.3671, TimeRMSE: 71428.7927, TimeMedAE: 67.6651
test [full], NDCG@5: 0.8782, HR@5: 1.0000, NDCG@10: 0.8782, HR@10: 1.0000, MRR: 0.8368
test [sampled], NDCG@5: 0.2904, HR@5: 0.3267, NDCG@10: 0.3526, HR@10: 0.5219, MRR: 0.3316
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.0714
epoch=47, loss=1.0782
epoch=48, loss=1.0713
epoch=49, loss=1.0729
epoch=50, loss=1.0641
valid [task], Top5Acc: 0.3596, Top10Acc: 0.6059, Acc: 0.0527, MacroF1: 0.0677, TimeMAE: 68153.5247, TimeRMSE: 278272.4872, TimeMedAE: 1510.0506
valid [full], NDCG@5: 0.7132, HR@5: 0.8803, NDCG@10: 0.7333, HR@10: 0.9473, MRR: 0.6704
valid [sampled], NDCG@5: 0.5463, HR@5: 0.5508, NDCG@10: 0.5604, HR@10: 0.5954, MRR: 0.5666
test [task], Top5Acc: 0.3883, Top10Acc: 0.7514, Acc: 0.0128, MacroF1: 0.0104, TimeMAE: 11656.8210, TimeRMSE: 67214.3908, TimeMedAE: 42.3041
test [full], NDCG@5: 0.8685, HR@5: 0.9824, NDCG@10: 0.8747, HR@10: 0.9999, MRR: 0.8325
test [sampled], NDCG@5: 0.2866, HR@5: 0.3227, NDCG@10: 0.3472, HR@10: 0.5131, MRR: 0.3276
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s42/sasrec_last.pth

### `multitask_sinusoidal_dstart_ml50_do035_s2024`

In [14]:
!python src/train_sasrec.py \
  --run_name multitask_sinusoidal_dstart_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024
epoch=1, loss=2.9345
epoch=2, loss=1.7528
epoch=3, loss=1.5236
epoch=4, loss=1.4194
epoch=5, loss=1.3497
valid [task], Top5Acc: 0.3670, Top10Acc: 0.7876, Acc: 0.0591, MacroF1: 0.0826, TimeMAE: 75569.1216, TimeRMSE: 292474.2494, TimeMedAE: 3374.3318
valid [full], NDCG@5: 0.5725, HR@5: 0.7269, NDCG@10: 0.6378, HR@10: 0.9312, MRR: 0.5527
valid [sampled], NDCG@5: 0.3955, HR@5: 0.4235, NDCG@10: 0.4341, HR@10: 0.5432, MRR: 0.4179
test [task], Top5Acc: 0.3659, Top10Acc: 0.6782, Acc: 0.0891, MacroF1: 0.0471, TimeMAE: 14709.3910, TimeRMSE: 83095.3876, TimeMedAE: 31.8681
test [full], NDCG@5: 0.7767, HR@5: 0.9851, NDCG@10: 0.7820, HR@10: 1.0000, MRR: 0.7087
test [sampled], NDCG@5: 0.2314, HR@5: 0.2353, NDCG@10: 0.2659, HR@10: 0.3467, MRR: 0.2813
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=1.3000
epoch=7, loss=1.2728
epoch=8, loss=1.2412
epoch=9, loss=1.2177
epoch=10, loss=1.2127
valid [task], Top5Acc: 0.4285, Top10Acc: 0.7515, Acc: 0.0500, MacroF1: 0.0746, TimeMAE: 68093.3507, TimeRMSE: 275716.6055, TimeMedAE: 1906.0250
valid [full], NDCG@5: 0.6548, HR@5: 0.7446, NDCG@10: 0.7177, HR@10: 0.9445, MRR: 0.6556
valid [sampled], NDCG@5: 0.5787, HR@5: 0.5803, NDCG@10: 0.5838, HR@10: 0.5962, MRR: 0.5913
test [task], Top5Acc: 0.1319, Top10Acc: 0.5723, Acc: 0.0098, MacroF1: 0.0067, TimeMAE: 13247.3642, TimeRMSE: 79633.4010, TimeMedAE: 40.5897
test [full], NDCG@5: 0.6087, HR@5: 0.8418, NDCG@10: 0.6625, HR@10: 1.0000, MRR: 0.5572
test [sampled], NDCG@5: 0.1655, HR@5: 0.1681, NDCG@10: 0.1817, HR@10: 0.2204, MRR: 0.2062
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/sasrec_best.pth
epoch=11, loss=1.1963
epoch=12, loss=1.1870
epoch=13, loss=1.1823
epoch=14, loss=1.1651
epoch=15, loss=1.1640
valid [task], Top5Acc: 0.5325, Top10Acc: 0.7505, Acc: 0.0535, MacroF1: 0.1011, TimeMAE: 74117.5070, TimeRMSE: 284897.4127, TimeMedAE: 4603.9167
valid [full], NDCG@5: 0.7031, HR@5: 0.8281, NDCG@10: 0.7408, HR@10: 0.9453, MRR: 0.6830
valid [sampled], NDCG@5: 0.5930, HR@5: 0.5944, NDCG@10: 0.5995, HR@10: 0.6148, MRR: 0.6077
test [task], Top5Acc: 0.1455, Top10Acc: 0.6655, Acc: 0.0174, MacroF1: 0.0135, TimeMAE: 15770.5692, TimeRMSE: 83099.2843, TimeMedAE: 91.1730
test [full], NDCG@5: 0.6831, HR@5: 0.9370, NDCG@10: 0.7055, HR@10: 1.0000, MRR: 0.6112
test [sampled], NDCG@5: 0.1819, HR@5: 0.1926, NDCG@10: 0.2013, HR@10: 0.2538, MRR: 0.2227
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/sasrec_best.pth
epoch=16, loss=1.1552
epoch=17, loss=1.1451
epoch=18, loss=1.1441
epoch=19, loss=1.1439
epoch=20, loss=1.1384
valid [task], Top5Acc: 0.5425, Top10Acc: 0.7334, Acc: 0.0594, MacroF1: 0.1110, TimeMAE: 75335.4690, TimeRMSE: 292231.0917, TimeMedAE: 4797.9276
valid [full], NDCG@5: 0.7073, HR@5: 0.8342, NDCG@10: 0.7422, HR@10: 0.9438, MRR: 0.6857
valid [sampled], NDCG@5: 0.6051, HR@5: 0.6062, NDCG@10: 0.6097, HR@10: 0.6209, MRR: 0.6183
test [task], Top5Acc: 0.3915, Top10Acc: 0.5723, Acc: 0.0179, MacroF1: 0.0173, TimeMAE: 15567.5205, TimeRMSE: 79060.5935, TimeMedAE: 64.2162
test [full], NDCG@5: 0.7038, HR@5: 0.9392, NDCG@10: 0.7255, HR@10: 1.0000, MRR: 0.6328
test [sampled], NDCG@5: 0.0984, HR@5: 0.1137, NDCG@10: 0.1504, HR@10: 0.2789, MRR: 0.1536
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/sasrec_best.pth
epoch=21, loss=1.1288
epoch=22, loss=1.1240
epoch=23, loss=1.1151
epoch=24, loss=1.1239
epoch=25, loss=1.1195
valid [task], Top5Acc: 0.5306, Top10Acc: 0.7505, Acc: 0.0579, MacroF1: 0.0712, TimeMAE: 75646.7478, TimeRMSE: 287397.4104, TimeMedAE: 5024.9735
valid [full], NDCG@5: 0.6977, HR@5: 0.8246, NDCG@10: 0.7383, HR@10: 0.9524, MRR: 0.6776
valid [sampled], NDCG@5: 0.5851, HR@5: 0.5876, NDCG@10: 0.5925, HR@10: 0.6112, MRR: 0.6001
test [task], Top5Acc: 0.4079, Top10Acc: 0.6319, Acc: 0.0234, MacroF1: 0.0198, TimeMAE: 16558.3487, TimeRMSE: 81983.7525, TimeMedAE: 71.9104
test [full], NDCG@5: 0.7485, HR@5: 0.9387, NDCG@10: 0.7697, HR@10: 1.0000, MRR: 0.6929
test [sampled], NDCG@5: 0.1889, HR@5: 0.2308, NDCG@10: 0.2517, HR@10: 0.4262, MRR: 0.2276
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1122
epoch=27, loss=1.1094
epoch=28, loss=1.1089
epoch=29, loss=1.1064
epoch=30, loss=1.0950
valid [task], Top5Acc: 0.5436, Top10Acc: 0.7649, Acc: 0.0661, MacroF1: 0.1112, TimeMAE: 84777.0514, TimeRMSE: 294980.1863, TimeMedAE: 6278.0403
valid [full], NDCG@5: 0.7028, HR@5: 0.8275, NDCG@10: 0.7408, HR@10: 0.9461, MRR: 0.6829
valid [sampled], NDCG@5: 0.5976, HR@5: 0.6005, NDCG@10: 0.6054, HR@10: 0.6247, MRR: 0.6117
test [task], Top5Acc: 0.4605, Top10Acc: 0.6649, Acc: 0.0450, MacroF1: 0.0274, TimeMAE: 17542.1271, TimeRMSE: 81540.6938, TimeMedAE: 96.2162
test [full], NDCG@5: 0.7911, HR@5: 0.9397, NDCG@10: 0.8125, HR@10: 1.0000, MRR: 0.7511
test [sampled], NDCG@5: 0.3446, HR@5: 0.3787, NDCG@10: 0.3930, HR@10: 0.5289, MRR: 0.3724
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.1068
epoch=32, loss=1.0932
epoch=33, loss=1.1037
epoch=34, loss=1.0907
epoch=35, loss=1.1005
valid [task], Top5Acc: 0.5262, Top10Acc: 0.7613, Acc: 0.0603, MacroF1: 0.0828, TimeMAE: 88262.6185, TimeRMSE: 292930.4313, TimeMedAE: 8167.6568
valid [full], NDCG@5: 0.6987, HR@5: 0.8146, NDCG@10: 0.7399, HR@10: 0.9439, MRR: 0.6816
valid [sampled], NDCG@5: 0.5730, HR@5: 0.5780, NDCG@10: 0.5881, HR@10: 0.6255, MRR: 0.5907
test [task], Top5Acc: 0.4575, Top10Acc: 0.6426, Acc: 0.0450, MacroF1: 0.0288, TimeMAE: 19712.4613, TimeRMSE: 87084.1628, TimeMedAE: 152.7670
test [full], NDCG@5: 0.8107, HR@5: 0.9894, NDCG@10: 0.8143, HR@10: 1.0000, MRR: 0.7524
test [sampled], NDCG@5: 0.3147, HR@5: 0.3515, NDCG@10: 0.3677, HR@10: 0.5159, MRR: 0.3451
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.0946
epoch=37, loss=1.0899
epoch=38, loss=1.0920
epoch=39, loss=1.0846
epoch=40, loss=1.0828
valid [task], Top5Acc: 0.4096, Top10Acc: 0.7575, Acc: 0.0654, MacroF1: 0.0765, TimeMAE: 100208.1160, TimeRMSE: 303373.8318, TimeMedAE: 9104.8181
valid [full], NDCG@5: 0.6968, HR@5: 0.8107, NDCG@10: 0.7391, HR@10: 0.9450, MRR: 0.6801
valid [sampled], NDCG@5: 0.5639, HR@5: 0.5691, NDCG@10: 0.5809, HR@10: 0.6227, MRR: 0.5831
test [task], Top5Acc: 0.4477, Top10Acc: 0.6751, Acc: 0.0484, MacroF1: 0.0324, TimeMAE: 23511.3776, TimeRMSE: 84046.5275, TimeMedAE: 109.6580
test [full], NDCG@5: 0.8117, HR@5: 0.9847, NDCG@10: 0.8169, HR@10: 1.0000, MRR: 0.7561
test [sampled], NDCG@5: 0.2724, HR@5: 0.3240, NDCG@10: 0.3371, HR@10: 0.5245, MRR: 0.3026
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=1.0895
epoch=42, loss=1.0827
epoch=43, loss=1.0876
epoch=44, loss=1.0811
epoch=45, loss=1.0740
valid [task], Top5Acc: 0.4125, Top10Acc: 0.7191, Acc: 0.0598, MacroF1: 0.0547, TimeMAE: 106433.1338, TimeRMSE: 303214.1268, TimeMedAE: 5773.3706
valid [full], NDCG@5: 0.7013, HR@5: 0.8186, NDCG@10: 0.7405, HR@10: 0.9432, MRR: 0.6828
valid [sampled], NDCG@5: 0.5693, HR@5: 0.5744, NDCG@10: 0.5862, HR@10: 0.6279, MRR: 0.5881
test [task], Top5Acc: 0.4392, Top10Acc: 0.6714, Acc: 0.0315, MacroF1: 0.0232, TimeMAE: 24957.7041, TimeRMSE: 87379.0502, TimeMedAE: 131.8726
test [full], NDCG@5: 0.7860, HR@5: 0.9602, NDCG@10: 0.8002, HR@10: 1.0000, MRR: 0.7340
test [sampled], NDCG@5: 0.2418, HR@5: 0.2883, NDCG@10: 0.3078, HR@10: 0.4929, MRR: 0.2760
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.0751
epoch=47, loss=1.0740
epoch=48, loss=1.0788
epoch=49, loss=1.0693
epoch=50, loss=1.0726
valid [task], Top5Acc: 0.3623, Top10Acc: 0.6906, Acc: 0.0611, MacroF1: 0.0504, TimeMAE: 92632.3659, TimeRMSE: 297187.7980, TimeMedAE: 6940.0290
valid [full], NDCG@5: 0.7066, HR@5: 0.8321, NDCG@10: 0.7423, HR@10: 0.9450, MRR: 0.6840
valid [sampled], NDCG@5: 0.5666, HR@5: 0.5726, NDCG@10: 0.5837, HR@10: 0.6267, MRR: 0.5857
test [task], Top5Acc: 0.4544, Top10Acc: 0.6739, Acc: 0.0265, MacroF1: 0.0189, TimeMAE: 19409.8977, TimeRMSE: 76996.8944, TimeMedAE: 100.6775
test [full], NDCG@5: 0.8095, HR@5: 0.9624, NDCG@10: 0.8227, HR@10: 1.0000, MRR: 0.7636
test [sampled], NDCG@5: 0.2743, HR@5: 0.3261, NDCG@10: 0.3387, HR@10: 0.5254, MRR: 0.3043
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s2024/sasrec_last.pth

### `multitask_sinusoidal_dstart_ml50_do035_s7`

In [15]:
!python src/train_sasrec.py \
  --run_name multitask_sinusoidal_dstart_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 1.0 \
  --output_dir "$MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7
epoch=1, loss=3.4360
epoch=2, loss=1.7939
epoch=3, loss=1.5688
epoch=4, loss=1.4338
epoch=5, loss=1.3712
valid [task], Top5Acc: 0.3716, Top10Acc: 0.6634, Acc: 0.0151, MacroF1: 0.0686, TimeMAE: 70794.8963, TimeRMSE: 291115.4016, TimeMedAE: 886.9716
valid [full], NDCG@5: 0.5348, HR@5: 0.6536, NDCG@10: 0.6347, HR@10: 0.9795, MRR: 0.5348
valid [sampled], NDCG@5: 0.4060, HR@5: 0.4222, NDCG@10: 0.4314, HR@10: 0.5015, MRR: 0.4256
test [task], Top5Acc: 0.0937, Top10Acc: 0.5623, Acc: 0.0364, MacroF1: 0.0351, TimeMAE: 12620.1618, TimeRMSE: 87698.3537, TimeMedAE: 4.6991
test [full], NDCG@5: 0.5361, HR@5: 0.7188, NDCG@10: 0.6130, HR@10: 0.9594, MRR: 0.5105
test [sampled], NDCG@5: 0.1238, HR@5: 0.1278, NDCG@10: 0.1428, HR@10: 0.1890, MRR: 0.1653
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=1.3282
epoch=7, loss=1.3002
epoch=8, loss=1.2721
epoch=9, loss=1.2544
epoch=10, loss=1.2450
valid [task], Top5Acc: 0.4565, Top10Acc: 0.7276, Acc: 0.0548, MacroF1: 0.0844, TimeMAE: 70753.2906, TimeRMSE: 291395.9319, TimeMedAE: 684.8447
valid [full], NDCG@5: 0.6095, HR@5: 0.7065, NDCG@10: 0.6983, HR@10: 0.9876, MRR: 0.6143
valid [sampled], NDCG@5: 0.5171, HR@5: 0.5209, NDCG@10: 0.5260, HR@10: 0.5490, MRR: 0.5331
test [task], Top5Acc: 0.0513, Top10Acc: 0.4105, Acc: 0.0185, MacroF1: 0.0135, TimeMAE: 12447.3706, TimeRMSE: 83571.4501, TimeMedAE: 8.5640
test [full], NDCG@5: 0.4474, HR@5: 0.6398, NDCG@10: 0.5657, HR@10: 0.9982, MRR: 0.4353
test [sampled], NDCG@5: 0.0458, HR@5: 0.0489, NDCG@10: 0.0566, HR@10: 0.0836, MRR: 0.0856
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=1.2319
epoch=12, loss=1.2158
epoch=13, loss=1.1975
epoch=14, loss=1.1936
epoch=15, loss=1.1842
valid [task], Top5Acc: 0.4900, Top10Acc: 0.6841, Acc: 0.0505, MacroF1: 0.0482, TimeMAE: 70081.4670, TimeRMSE: 282083.8100, TimeMedAE: 781.5639
valid [full], NDCG@5: 0.6589, HR@5: 0.7377, NDCG@10: 0.7386, HR@10: 0.9870, MRR: 0.6672
valid [sampled], NDCG@5: 0.5946, HR@5: 0.5960, NDCG@10: 0.5988, HR@10: 0.6093, MRR: 0.6065
test [task], Top5Acc: 0.0903, Top10Acc: 0.6281, Acc: 0.0099, MacroF1: 0.0089, TimeMAE: 12165.8219, TimeRMSE: 81919.0726, TimeMedAE: 8.3415
test [full], NDCG@5: 0.5840, HR@5: 0.7928, NDCG@10: 0.6516, HR@10: 0.9948, MRR: 0.5444
test [sampled], NDCG@5: 0.1482, HR@5: 0.1494, NDCG@10: 0.1620, HR@10: 0.1939, MRR: 0.1914
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=1.1667
epoch=17, loss=1.1647
epoch=18, loss=1.1527
epoch=19, loss=1.1556
epoch=20, loss=1.1530
valid [task], Top5Acc: 0.4470, Top10Acc: 0.6852, Acc: 0.0542, MacroF1: 0.0737, TimeMAE: 70668.3774, TimeRMSE: 292361.2988, TimeMedAE: 977.2287
valid [full], NDCG@5: 0.6662, HR@5: 0.7549, NDCG@10: 0.7254, HR@10: 0.9428, MRR: 0.6661
valid [sampled], NDCG@5: 0.5980, HR@5: 0.5990, NDCG@10: 0.6005, HR@10: 0.6069, MRR: 0.6092
test [task], Top5Acc: 0.3795, Top10Acc: 0.5158, Acc: 0.0121, MacroF1: 0.0126, TimeMAE: 13122.5386, TimeRMSE: 85904.1527, TimeMedAE: 8.8220
test [full], NDCG@5: 0.6169, HR@5: 0.8668, NDCG@10: 0.6610, HR@10: 0.9982, MRR: 0.5504
test [sampled], NDCG@5: 0.0797, HR@5: 0.0837, NDCG@10: 0.1166, HR@10: 0.2028, MRR: 0.1349
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=1.1461
epoch=22, loss=1.1370
epoch=23, loss=1.1396
epoch=24, loss=1.1332
epoch=25, loss=1.1339
valid [task], Top5Acc: 0.4340, Top10Acc: 0.7134, Acc: 0.0526, MacroF1: 0.0787, TimeMAE: 67642.9161, TimeRMSE: 281269.1486, TimeMedAE: 2099.4725
valid [full], NDCG@5: 0.6675, HR@5: 0.7688, NDCG@10: 0.7232, HR@10: 0.9430, MRR: 0.6628
valid [sampled], NDCG@5: 0.5890, HR@5: 0.5912, NDCG@10: 0.5932, HR@10: 0.6045, MRR: 0.6010
test [task], Top5Acc: 0.1701, Top10Acc: 0.5169, Acc: 0.0135, MacroF1: 0.0149, TimeMAE: 11856.6390, TimeRMSE: 76399.5117, TimeMedAE: 11.8101
test [full], NDCG@5: 0.6110, HR@5: 0.8800, NDCG@10: 0.6511, HR@10: 1.0000, MRR: 0.5377
test [sampled], NDCG@5: 0.0768, HR@5: 0.0795, NDCG@10: 0.1018, HR@10: 0.1607, MRR: 0.1298
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=1.1262
epoch=27, loss=1.1376
epoch=28, loss=1.1127
epoch=29, loss=1.1203
epoch=30, loss=1.1140
valid [task], Top5Acc: 0.4391, Top10Acc: 0.7034, Acc: 0.0535, MacroF1: 0.0727, TimeMAE: 69119.7288, TimeRMSE: 282995.8944, TimeMedAE: 1560.7994
valid [full], NDCG@5: 0.6644, HR@5: 0.7615, NDCG@10: 0.7237, HR@10: 0.9425, MRR: 0.6629
valid [sampled], NDCG@5: 0.5866, HR@5: 0.5896, NDCG@10: 0.5920, HR@10: 0.6067, MRR: 0.5988
test [task], Top5Acc: 0.1514, Top10Acc: 0.5200, Acc: 0.0123, MacroF1: 0.0132, TimeMAE: 12162.6956, TimeRMSE: 80988.7886, TimeMedAE: 8.7150
test [full], NDCG@5: 0.5372, HR@5: 0.8786, NDCG@10: 0.5784, HR@10: 0.9999, MRR: 0.4405
test [sampled], NDCG@5: 0.0609, HR@5: 0.0635, NDCG@10: 0.0809, HR@10: 0.1283, MRR: 0.1074
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=1.1167
epoch=32, loss=1.1177
epoch=33, loss=1.1072
epoch=34, loss=1.1091
epoch=35, loss=1.1033
valid [task], Top5Acc: 0.4289, Top10Acc: 0.6690, Acc: 0.0586, MacroF1: 0.0658, TimeMAE: 69055.2520, TimeRMSE: 278158.6210, TimeMedAE: 2096.0137
valid [full], NDCG@5: 0.6789, HR@5: 0.7978, NDCG@10: 0.7263, HR@10: 0.9423, MRR: 0.6653
valid [sampled], NDCG@5: 0.5817, HR@5: 0.5839, NDCG@10: 0.5883, HR@10: 0.6047, MRR: 0.5957
test [task], Top5Acc: 0.1580, Top10Acc: 0.5211, Acc: 0.0206, MacroF1: 0.0165, TimeMAE: 13000.1802, TimeRMSE: 77336.6925, TimeMedAE: 13.8957
test [full], NDCG@5: 0.5334, HR@5: 0.8474, NDCG@10: 0.5841, HR@10: 0.9982, MRR: 0.4531
test [sampled], NDCG@5: 0.0722, HR@5: 0.0744, NDCG@10: 0.0877, HR@10: 0.1244, MRR: 0.1151
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=1.1072
epoch=37, loss=1.1005
epoch=38, loss=1.1080
epoch=39, loss=1.0984
epoch=40, loss=1.1039
valid [task], Top5Acc: 0.4337, Top10Acc: 0.6416, Acc: 0.0609, MacroF1: 0.0731, TimeMAE: 74713.9240, TimeRMSE: 282533.8829, TimeMedAE: 2654.4407
valid [full], NDCG@5: 0.7253, HR@5: 0.8684, NDCG@10: 0.7481, HR@10: 0.9425, MRR: 0.6914
valid [sampled], NDCG@5: 0.5847, HR@5: 0.5883, NDCG@10: 0.5954, HR@10: 0.6220, MRR: 0.6024
test [task], Top5Acc: 0.1919, Top10Acc: 0.5356, Acc: 0.0209, MacroF1: 0.0183, TimeMAE: 13484.5469, TimeRMSE: 71447.1914, TimeMedAE: 583.6429
test [full], NDCG@5: 0.6043, HR@5: 0.9086, NDCG@10: 0.6324, HR@10: 0.9984, MRR: 0.5143
test [sampled], NDCG@5: 0.0783, HR@5: 0.0827, NDCG@10: 0.1042, HR@10: 0.1660, MRR: 0.1269
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/sasrec_best.pth
epoch=41, loss=1.1000
epoch=42, loss=1.0978
epoch=43, loss=1.0851
epoch=44, loss=1.0945
epoch=45, loss=1.0821
valid [task], Top5Acc: 0.4334, Top10Acc: 0.6254, Acc: 0.0574, MacroF1: 0.0889, TimeMAE: 74182.8560, TimeRMSE: 286736.2696, TimeMedAE: 8348.3693
valid [full], NDCG@5: 0.7129, HR@5: 0.8532, NDCG@10: 0.7412, HR@10: 0.9455, MRR: 0.6823
valid [sampled], NDCG@5: 0.5873, HR@5: 0.5905, NDCG@10: 0.5954, HR@10: 0.6159, MRR: 0.6027
test [task], Top5Acc: 0.2693, Top10Acc: 0.5478, Acc: 0.0173, MacroF1: 0.0175, TimeMAE: 17180.6470, TimeRMSE: 71583.7887, TimeMedAE: 2258.8518
test [full], NDCG@5: 0.5671, HR@5: 0.9100, NDCG@10: 0.5953, HR@10: 1.0000, MRR: 0.4635
test [sampled], NDCG@5: 0.0842, HR@5: 0.0908, NDCG@10: 0.1037, HR@10: 0.1532, MRR: 0.1264
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=1.0961
epoch=47, loss=1.0905
epoch=48, loss=1.0869
epoch=49, loss=1.0824
epoch=50, loss=1.0876
valid [task], Top5Acc: 0.4186, Top10Acc: 0.6199, Acc: 0.0619, MacroF1: 0.0767, TimeMAE: 75494.8788, TimeRMSE: 286360.9417, TimeMedAE: 7531.4005
valid [full], NDCG@5: 0.7036, HR@5: 0.8450, NDCG@10: 0.7348, HR@10: 0.9440, MRR: 0.6745
valid [sampled], NDCG@5: 0.5796, HR@5: 0.5837, NDCG@10: 0.5871, HR@10: 0.6070, MRR: 0.5949
test [task], Top5Acc: 0.2529, Top10Acc: 0.6271, Acc: 0.0235, MacroF1: 0.0192, TimeMAE: 15049.2335, TimeRMSE: 65358.7937, TimeMedAE: 1299.0741
test [full], NDCG@5: 0.6767, HR@5: 0.9229, NDCG@10: 0.7017, HR@10: 1.0000, MRR: 0.6060
test [sampled], NDCG@5: 0.2682, HR@5: 0.2769, NDCG@10: 0.2931, HR@10: 0.3564, MRR: 0.3060
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_s7/sasrec_last.pth

## Train refine sinusoidal multi-task w0.1 runs

### `multitask_sinusoidal_dstart_ml50_do035_w01_s42`

In [16]:
!python src/train_sasrec.py \
  --run_name multitask_sinusoidal_dstart_ml50_do035_w01_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 0.1 \
  --output_dir "$MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42
epoch=1, loss=0.9068
epoch=2, loss=0.4368
epoch=3, loss=0.3487
epoch=4, loss=0.3058
epoch=5, loss=0.2774
valid [task], Top5Acc: 0.5048, Top10Acc: 0.7791, Acc: 0.0623, MacroF1: 0.0958, TimeMAE: 79929.9066, TimeRMSE: 285208.0534, TimeMedAE: 1119.9765
valid [full], NDCG@5: 0.6554, HR@5: 0.7747, NDCG@10: 0.7251, HR@10: 0.9946, MRR: 0.6459
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5621, NDCG@10: 0.5657, HR@10: 0.5806, MRR: 0.5747
test [task], Top5Acc: 0.2884, Top10Acc: 0.4475, Acc: 0.0137, MacroF1: 0.0138, TimeMAE: 10621.8369, TimeRMSE: 76113.1914, TimeMedAE: 20.0550
test [full], NDCG@5: 0.6016, HR@5: 0.6771, NDCG@10: 0.6798, HR@10: 0.9229, MRR: 0.6133
test [sampled], NDCG@5: 0.1438, HR@5: 0.1691, NDCG@10: 0.1885, HR@10: 0.3092, MRR: 0.1823
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/sasrec_best.pth
epoch=6, loss=0.2582
epoch=7, loss=0.2407
epoch=8, loss=0.2302
epoch=9, loss=0.2239
epoch=10, loss=0.2166
valid [task], Top5Acc: 0.5072, Top10Acc: 0.7476, Acc: 0.0579, MacroF1: 0.0813, TimeMAE: 76170.2345, TimeRMSE: 285770.0792, TimeMedAE: 985.3943
valid [full], NDCG@5: 0.7053, HR@5: 0.8702, NDCG@10: 0.7381, HR@10: 0.9736, MRR: 0.6688
valid [sampled], NDCG@5: 0.5768, HR@5: 0.5818, NDCG@10: 0.5848, HR@10: 0.6069, MRR: 0.5918
test [task], Top5Acc: 0.2848, Top10Acc: 0.5351, Acc: 0.0108, MacroF1: 0.0102, TimeMAE: 11876.2479, TimeRMSE: 79610.8928, TimeMedAE: 10.1476
test [full], NDCG@5: 0.7257, HR@5: 0.9304, NDCG@10: 0.7486, HR@10: 1.0000, MRR: 0.6684
test [sampled], NDCG@5: 0.0894, HR@5: 0.1318, NDCG@10: 0.1587, HR@10: 0.3489, MRR: 0.1364
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/sasrec_best.pth
epoch=11, loss=0.2133
epoch=12, loss=0.2091
epoch=13, loss=0.2043
epoch=14, loss=0.2051
epoch=15, loss=0.2030
valid [task], Top5Acc: 0.4098, Top10Acc: 0.7845, Acc: 0.0508, MacroF1: 0.0570, TimeMAE: 74352.2736, TimeRMSE: 283917.1912, TimeMedAE: 888.2873
valid [full], NDCG@5: 0.7051, HR@5: 0.8782, NDCG@10: 0.7345, HR@10: 0.9707, MRR: 0.6645
valid [sampled], NDCG@5: 0.5639, HR@5: 0.5682, NDCG@10: 0.5740, HR@10: 0.5997, MRR: 0.5808
test [task], Top5Acc: 0.2877, Top10Acc: 0.5441, Acc: 0.0096, MacroF1: 0.0090, TimeMAE: 11476.3119, TimeRMSE: 75566.6326, TimeMedAE: 26.1610
test [full], NDCG@5: 0.7348, HR@5: 0.9314, NDCG@10: 0.7573, HR@10: 1.0000, MRR: 0.6791
test [sampled], NDCG@5: 0.0972, HR@5: 0.1412, NDCG@10: 0.1686, HR@10: 0.3646, MRR: 0.1446
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.1995
epoch=17, loss=0.1967
epoch=18, loss=0.1962
epoch=19, loss=0.1947
epoch=20, loss=0.1922
valid [task], Top5Acc: 0.3938, Top10Acc: 0.7859, Acc: 0.0532, MacroF1: 0.0728, TimeMAE: 79208.2384, TimeRMSE: 290956.5909, TimeMedAE: 2637.6569
valid [full], NDCG@5: 0.7177, HR@5: 0.9036, NDCG@10: 0.7381, HR@10: 0.9709, MRR: 0.6678
valid [sampled], NDCG@5: 0.5539, HR@5: 0.5600, NDCG@10: 0.5667, HR@10: 0.6003, MRR: 0.5729
test [task], Top5Acc: 0.3531, Top10Acc: 0.6404, Acc: 0.0119, MacroF1: 0.0118, TimeMAE: 11308.9658, TimeRMSE: 71976.7304, TimeMedAE: 50.2058
test [full], NDCG@5: 0.8328, HR@5: 0.9562, NDCG@10: 0.8472, HR@10: 1.0000, MRR: 0.7973
test [sampled], NDCG@5: 0.2082, HR@5: 0.2586, NDCG@10: 0.2839, HR@10: 0.4940, MRR: 0.2507
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.1918
epoch=22, loss=0.1927
epoch=23, loss=0.1899
epoch=24, loss=0.1892
epoch=25, loss=0.1880
valid [task], Top5Acc: 0.3998, Top10Acc: 0.7224, Acc: 0.0544, MacroF1: 0.0428, TimeMAE: 76587.7425, TimeRMSE: 295228.5764, TimeMedAE: 1404.4726
valid [full], NDCG@5: 0.7071, HR@5: 0.8728, NDCG@10: 0.7389, HR@10: 0.9722, MRR: 0.6688
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5662, NDCG@10: 0.5707, HR@10: 0.6029, MRR: 0.5765
test [task], Top5Acc: 0.4214, Top10Acc: 0.6842, Acc: 0.0113, MacroF1: 0.0091, TimeMAE: 11933.0792, TimeRMSE: 76226.2627, TimeMedAE: 47.0066
test [full], NDCG@5: 0.8485, HR@5: 0.9592, NDCG@10: 0.8627, HR@10: 0.9999, MRR: 0.8176
test [sampled], NDCG@5: 0.2588, HR@5: 0.3136, NDCG@10: 0.3392, HR@10: 0.5637, MRR: 0.2977
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/sasrec_best.pth
epoch=26, loss=0.1874
epoch=27, loss=0.1873
epoch=28, loss=0.1860
epoch=29, loss=0.1868
epoch=30, loss=0.1849
valid [task], Top5Acc: 0.4026, Top10Acc: 0.6316, Acc: 0.0553, MacroF1: 0.0899, TimeMAE: 75884.0719, TimeRMSE: 287019.6196, TimeMedAE: 1220.7277
valid [full], NDCG@5: 0.6990, HR@5: 0.8577, NDCG@10: 0.7359, HR@10: 0.9728, MRR: 0.6638
valid [sampled], NDCG@5: 0.5305, HR@5: 0.5368, NDCG@10: 0.5466, HR@10: 0.5876, MRR: 0.5518
test [task], Top5Acc: 0.4022, Top10Acc: 0.7859, Acc: 0.0261, MacroF1: 0.0194, TimeMAE: 12007.7238, TimeRMSE: 79181.0159, TimeMedAE: 36.3811
test [full], NDCG@5: 0.8740, HR@5: 0.9992, NDCG@10: 0.8742, HR@10: 0.9999, MRR: 0.8315
test [sampled], NDCG@5: 0.3090, HR@5: 0.3567, NDCG@10: 0.3848, HR@10: 0.5918, MRR: 0.3487
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.1864
epoch=32, loss=0.1835
epoch=33, loss=0.1853
epoch=34, loss=0.1817
epoch=35, loss=0.1825
valid [task], Top5Acc: 0.3962, Top10Acc: 0.6428, Acc: 0.0545, MacroF1: 0.0898, TimeMAE: 76651.7008, TimeRMSE: 287133.0627, TimeMedAE: 1402.7520
valid [full], NDCG@5: 0.7054, HR@5: 0.8713, NDCG@10: 0.7374, HR@10: 0.9718, MRR: 0.6660
valid [sampled], NDCG@5: 0.5337, HR@5: 0.5404, NDCG@10: 0.5490, HR@10: 0.5886, MRR: 0.5547
test [task], Top5Acc: 0.4029, Top10Acc: 0.7015, Acc: 0.0138, MacroF1: 0.0144, TimeMAE: 10488.5211, TimeRMSE: 70288.3690, TimeMedAE: 40.4741
test [full], NDCG@5: 0.8601, HR@5: 0.9982, NDCG@10: 0.8607, HR@10: 1.0000, MRR: 0.8136
test [sampled], NDCG@5: 0.2750, HR@5: 0.3245, NDCG@10: 0.3445, HR@10: 0.5406, MRR: 0.3136
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.1815
epoch=37, loss=0.1814
epoch=38, loss=0.1802
epoch=39, loss=0.1842
epoch=40, loss=0.1798
valid [task], Top5Acc: 0.3923, Top10Acc: 0.6065, Acc: 0.0514, MacroF1: 0.0814, TimeMAE: 70712.5783, TimeRMSE: 274351.4980, TimeMedAE: 962.0846
valid [full], NDCG@5: 0.6923, HR@5: 0.8633, NDCG@10: 0.7261, HR@10: 0.9709, MRR: 0.6520
valid [sampled], NDCG@5: 0.5234, HR@5: 0.5296, NDCG@10: 0.5398, HR@10: 0.5811, MRR: 0.5441
test [task], Top5Acc: 0.4258, Top10Acc: 0.7183, Acc: 0.0119, MacroF1: 0.0117, TimeMAE: 10436.1121, TimeRMSE: 68050.8702, TimeMedAE: 26.8012
test [full], NDCG@5: 0.8666, HR@5: 0.9723, NDCG@10: 0.8764, HR@10: 1.0000, MRR: 0.8351
test [sampled], NDCG@5: 0.2980, HR@5: 0.3517, NDCG@10: 0.3719, HR@10: 0.5814, MRR: 0.3347
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.1808
epoch=42, loss=0.1809
epoch=43, loss=0.1824
epoch=44, loss=0.1816
epoch=45, loss=0.1811
valid [task], Top5Acc: 0.4059, Top10Acc: 0.6588, Acc: 0.0554, MacroF1: 0.0805, TimeMAE: 76692.5799, TimeRMSE: 289611.4878, TimeMedAE: 2202.9072
valid [full], NDCG@5: 0.7076, HR@5: 0.8699, NDCG@10: 0.7400, HR@10: 0.9706, MRR: 0.6698
valid [sampled], NDCG@5: 0.5381, HR@5: 0.5449, NDCG@10: 0.5554, HR@10: 0.5990, MRR: 0.5594
test [task], Top5Acc: 0.4663, Top10Acc: 0.6819, Acc: 0.0158, MacroF1: 0.0151, TimeMAE: 11567.7505, TimeRMSE: 73124.4305, TimeMedAE: 46.3972
test [full], NDCG@5: 0.8788, HR@5: 0.9984, NDCG@10: 0.8793, HR@10: 1.0000, MRR: 0.8381
test [sampled], NDCG@5: 0.2876, HR@5: 0.3386, NDCG@10: 0.3637, HR@10: 0.5757, MRR: 0.3269
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/sasrec_best.pth
epoch=46, loss=0.1770
epoch=47, loss=0.1808
epoch=48, loss=0.1785
epoch=49, loss=0.1797
epoch=50, loss=0.1771
valid [task], Top5Acc: 0.3918, Top10Acc: 0.5997, Acc: 0.0508, MacroF1: 0.0648, TimeMAE: 70649.7034, TimeRMSE: 283042.4943, TimeMedAE: 885.8166
valid [full], NDCG@5: 0.6618, HR@5: 0.8234, NDCG@10: 0.7080, HR@10: 0.9673, MRR: 0.6300
valid [sampled], NDCG@5: 0.4848, HR@5: 0.4891, NDCG@10: 0.5014, HR@10: 0.5417, MRR: 0.5078
test [task], Top5Acc: 0.4723, Top10Acc: 0.7825, Acc: 0.0246, MacroF1: 0.0166, TimeMAE: 10943.9084, TimeRMSE: 70571.3077, TimeMedAE: 22.1322
test [full], NDCG@5: 0.8949, HR@5: 0.9991, NDCG@10: 0.8952, HR@10: 1.0000, MRR: 0.8590
test [sampled], NDCG@5: 0.3612, HR@5: 0.4080, NDCG@10: 0.4278, HR@10: 0.6156, MRR: 0.3966
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s42/sasrec_last.pth

### `multitask_sinusoidal_dstart_ml50_do035_w01_s2024`

In [17]:
!python src/train_sasrec.py \
  --run_name multitask_sinusoidal_dstart_ml50_do035_w01_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 0.1 \
  --output_dir "$MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024
epoch=1, loss=0.8974
epoch=2, loss=0.4363
epoch=3, loss=0.3457
epoch=4, loss=0.3012
epoch=5, loss=0.2756
valid [task], Top5Acc: 0.4869, Top10Acc: 0.6866, Acc: 0.0549, MacroF1: 0.0826, TimeMAE: 80505.4291, TimeRMSE: 295100.8333, TimeMedAE: 1018.7337
valid [full], NDCG@5: 0.6336, HR@5: 0.7181, NDCG@10: 0.7148, HR@10: 0.9714, MRR: 0.6420
valid [sampled], NDCG@5: 0.5580, HR@5: 0.5632, NDCG@10: 0.5667, HR@10: 0.5903, MRR: 0.5716
test [task], Top5Acc: 0.3052, Top10Acc: 0.6540, Acc: 0.0144, MacroF1: 0.0147, TimeMAE: 11857.5787, TimeRMSE: 76729.1749, TimeMedAE: 34.4061
test [full], NDCG@5: 0.7983, HR@5: 0.9472, NDCG@10: 0.8153, HR@10: 1.0000, MRR: 0.7558
test [sampled], NDCG@5: 0.2061, HR@5: 0.2407, NDCG@10: 0.2626, HR@10: 0.4175, MRR: 0.2495
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/sasrec_best.pth
epoch=6, loss=0.2538
epoch=7, loss=0.2405
epoch=8, loss=0.2301
epoch=9, loss=0.2222
epoch=10, loss=0.2207
valid [task], Top5Acc: 0.5048, Top10Acc: 0.7620, Acc: 0.0502, MacroF1: 0.1063, TimeMAE: 74036.0283, TimeRMSE: 272522.2701, TimeMedAE: 6198.8671
valid [full], NDCG@5: 0.7017, HR@5: 0.8625, NDCG@10: 0.7362, HR@10: 0.9693, MRR: 0.6672
valid [sampled], NDCG@5: 0.5633, HR@5: 0.5675, NDCG@10: 0.5754, HR@10: 0.6054, MRR: 0.5806
test [task], Top5Acc: 0.3563, Top10Acc: 0.6712, Acc: 0.0408, MacroF1: 0.0168, TimeMAE: 13355.4957, TimeRMSE: 72205.4725, TimeMedAE: 102.1494
test [full], NDCG@5: 0.8699, HR@5: 0.9539, NDCG@10: 0.8851, HR@10: 1.0000, MRR: 0.8481
test [sampled], NDCG@5: 0.2705, HR@5: 0.3231, NDCG@10: 0.3396, HR@10: 0.5380, MRR: 0.3067
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/sasrec_best.pth
epoch=11, loss=0.2148
epoch=12, loss=0.2118
epoch=13, loss=0.2086
epoch=14, loss=0.2035
epoch=15, loss=0.2025
valid [task], Top5Acc: 0.4989, Top10Acc: 0.8015, Acc: 0.0529, MacroF1: 0.0777, TimeMAE: 80058.1100, TimeRMSE: 283119.2913, TimeMedAE: 8025.2502
valid [full], NDCG@5: 0.7113, HR@5: 0.8405, NDCG@10: 0.7531, HR@10: 0.9696, MRR: 0.6889
valid [sampled], NDCG@5: 0.5771, HR@5: 0.5821, NDCG@10: 0.5926, HR@10: 0.6305, MRR: 0.5957
test [task], Top5Acc: 0.4434, Top10Acc: 0.6766, Acc: 0.1132, MacroF1: 0.0401, TimeMAE: 16409.6256, TimeRMSE: 78202.8917, TimeMedAE: 108.1926
test [full], NDCG@5: 0.9067, HR@5: 0.9910, NDCG@10: 0.9096, HR@10: 1.0000, MRR: 0.8796
test [sampled], NDCG@5: 0.3444, HR@5: 0.3894, NDCG@10: 0.4047, HR@10: 0.5776, MRR: 0.3784
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/sasrec_best.pth
epoch=16, loss=0.2014
epoch=17, loss=0.1975
epoch=18, loss=0.1977
epoch=19, loss=0.1972
epoch=20, loss=0.1961
valid [task], Top5Acc: 0.5052, Top10Acc: 0.8419, Acc: 0.0536, MacroF1: 0.0538, TimeMAE: 93893.9310, TimeRMSE: 295681.7475, TimeMedAE: 12270.9973
valid [full], NDCG@5: 0.7188, HR@5: 0.8678, NDCG@10: 0.7516, HR@10: 0.9695, MRR: 0.6859
valid [sampled], NDCG@5: 0.5583, HR@5: 0.5651, NDCG@10: 0.5762, HR@10: 0.6211, MRR: 0.5789
test [task], Top5Acc: 0.4364, Top10Acc: 0.6679, Acc: 0.1228, MacroF1: 0.0375, TimeMAE: 20332.0977, TimeRMSE: 79537.6812, TimeMedAE: 169.9988
test [full], NDCG@5: 0.9157, HR@5: 0.9907, NDCG@10: 0.9189, HR@10: 1.0000, MRR: 0.8909
test [sampled], NDCG@5: 0.2763, HR@5: 0.3193, NDCG@10: 0.3528, HR@10: 0.5585, MRR: 0.3211
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.1937
epoch=22, loss=0.1916
epoch=23, loss=0.1903
epoch=24, loss=0.1922
epoch=25, loss=0.1918
valid [task], Top5Acc: 0.4082, Top10Acc: 0.8244, Acc: 0.0581, MacroF1: 0.0737, TimeMAE: 90911.3181, TimeRMSE: 292673.1604, TimeMedAE: 13582.2150
valid [full], NDCG@5: 0.7059, HR@5: 0.8770, NDCG@10: 0.7353, HR@10: 0.9693, MRR: 0.6642
valid [sampled], NDCG@5: 0.5243, HR@5: 0.5302, NDCG@10: 0.5422, HR@10: 0.5862, MRR: 0.5466
test [task], Top5Acc: 0.4517, Top10Acc: 0.5920, Acc: 0.1531, MacroF1: 0.0494, TimeMAE: 20512.3480, TimeRMSE: 84334.8455, TimeMedAE: 209.2060
test [full], NDCG@5: 0.8972, HR@5: 0.9748, NDCG@10: 0.9057, HR@10: 1.0000, MRR: 0.8747
test [sampled], NDCG@5: 0.2817, HR@5: 0.3257, NDCG@10: 0.3494, HR@10: 0.5369, MRR: 0.3215
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.1884
epoch=27, loss=0.1886
epoch=28, loss=0.1867
epoch=29, loss=0.1881
epoch=30, loss=0.1835
valid [task], Top5Acc: 0.4037, Top10Acc: 0.7859, Acc: 0.0541, MacroF1: 0.0683, TimeMAE: 88361.0615, TimeRMSE: 296303.2964, TimeMedAE: 9890.6931
valid [full], NDCG@5: 0.7174, HR@5: 0.8668, NDCG@10: 0.7502, HR@10: 0.9707, MRR: 0.6838
valid [sampled], NDCG@5: 0.5572, HR@5: 0.5631, NDCG@10: 0.5753, HR@10: 0.6200, MRR: 0.5780
test [task], Top5Acc: 0.4559, Top10Acc: 0.5906, Acc: 0.1614, MacroF1: 0.0439, TimeMAE: 17406.9584, TimeRMSE: 78523.2030, TimeMedAE: 160.3041
test [full], NDCG@5: 0.8921, HR@5: 0.9661, NDCG@10: 0.9034, HR@10: 1.0000, MRR: 0.8720
test [sampled], NDCG@5: 0.3159, HR@5: 0.3469, NDCG@10: 0.3778, HR@10: 0.5409, MRR: 0.3565
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.1858
epoch=32, loss=0.1844
epoch=33, loss=0.1840
epoch=34, loss=0.1832
epoch=35, loss=0.1839
valid [task], Top5Acc: 0.4032, Top10Acc: 0.7794, Acc: 0.0523, MacroF1: 0.0706, TimeMAE: 86721.4200, TimeRMSE: 292868.8233, TimeMedAE: 6668.8100
valid [full], NDCG@5: 0.7028, HR@5: 0.8627, NDCG@10: 0.7369, HR@10: 0.9701, MRR: 0.6669
valid [sampled], NDCG@5: 0.5489, HR@5: 0.5543, NDCG@10: 0.5626, HR@10: 0.5974, MRR: 0.5680
test [task], Top5Acc: 0.4525, Top10Acc: 0.5761, Acc: 0.1406, MacroF1: 0.0462, TimeMAE: 17520.4342, TimeRMSE: 81150.6257, TimeMedAE: 92.8738
test [full], NDCG@5: 0.8749, HR@5: 0.9532, NDCG@10: 0.8907, HR@10: 1.0000, MRR: 0.8556
test [sampled], NDCG@5: 0.2802, HR@5: 0.3209, NDCG@10: 0.3478, HR@10: 0.5323, MRR: 0.3195
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.1828
epoch=37, loss=0.1825
epoch=38, loss=0.1813
epoch=39, loss=0.1816
epoch=40, loss=0.1798
valid [task], Top5Acc: 0.4015, Top10Acc: 0.6963, Acc: 0.0531, MacroF1: 0.0650, TimeMAE: 91257.5813, TimeRMSE: 303413.9585, TimeMedAE: 9429.6417
valid [full], NDCG@5: 0.7066, HR@5: 0.8631, NDCG@10: 0.7395, HR@10: 0.9701, MRR: 0.6712
valid [sampled], NDCG@5: 0.5633, HR@5: 0.5670, NDCG@10: 0.5739, HR@10: 0.6003, MRR: 0.5812
test [task], Top5Acc: 0.4648, Top10Acc: 0.6520, Acc: 0.1675, MacroF1: 0.0364, TimeMAE: 17121.7910, TimeRMSE: 74300.8969, TimeMedAE: 321.9951
test [full], NDCG@5: 0.8786, HR@5: 0.9432, NDCG@10: 0.8976, HR@10: 1.0000, MRR: 0.8648
test [sampled], NDCG@5: 0.2876, HR@5: 0.3328, NDCG@10: 0.3574, HR@10: 0.5509, MRR: 0.3256
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.1807
epoch=42, loss=0.1823
epoch=43, loss=0.1811
epoch=44, loss=0.1791
epoch=45, loss=0.1791
valid [task], Top5Acc: 0.4054, Top10Acc: 0.7781, Acc: 0.0524, MacroF1: 0.0617, TimeMAE: 90075.8359, TimeRMSE: 296814.2310, TimeMedAE: 8060.9008
valid [full], NDCG@5: 0.7126, HR@5: 0.8653, NDCG@10: 0.7455, HR@10: 0.9688, MRR: 0.6782
valid [sampled], NDCG@5: 0.5539, HR@5: 0.5608, NDCG@10: 0.5712, HR@10: 0.6152, MRR: 0.5744
test [task], Top5Acc: 0.5409, Top10Acc: 0.6882, Acc: 0.1687, MacroF1: 0.0422, TimeMAE: 15530.2212, TimeRMSE: 71181.4207, TimeMedAE: 266.6293
test [full], NDCG@5: 0.8694, HR@5: 0.9301, NDCG@10: 0.8932, HR@10: 1.0000, MRR: 0.8590
test [sampled], NDCG@5: 0.3404, HR@5: 0.3795, NDCG@10: 0.3985, HR@10: 0.5598, MRR: 0.3748
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.1785
epoch=47, loss=0.1780
epoch=48, loss=0.1786
epoch=49, loss=0.1757
epoch=50, loss=0.1779
valid [task], Top5Acc: 0.4006, Top10Acc: 0.7000, Acc: 0.0527, MacroF1: 0.0657, TimeMAE: 85400.4906, TimeRMSE: 293670.5837, TimeMedAE: 9211.8019
valid [full], NDCG@5: 0.6953, HR@5: 0.8734, NDCG@10: 0.7255, HR@10: 0.9697, MRR: 0.6514
valid [sampled], NDCG@5: 0.5230, HR@5: 0.5266, NDCG@10: 0.5343, HR@10: 0.5620, MRR: 0.5442
test [task], Top5Acc: 0.4738, Top10Acc: 0.6799, Acc: 0.1595, MacroF1: 0.0393, TimeMAE: 17032.5551, TimeRMSE: 71060.3913, TimeMedAE: 303.5691
test [full], NDCG@5: 0.8544, HR@5: 0.9406, NDCG@10: 0.8742, HR@10: 1.0000, MRR: 0.8332
test [sampled], NDCG@5: 0.2804, HR@5: 0.3248, NDCG@10: 0.3427, HR@10: 0.5188, MRR: 0.3168
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s2024/sasrec_last.pth

### `multitask_sinusoidal_dstart_ml50_do035_w01_s7`

In [18]:
!python src/train_sasrec.py \
  --run_name multitask_sinusoidal_dstart_ml50_do035_w01_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only_stage3_v2/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --enable_time_prediction \
  --time_prediction_target delta_next_seconds \
  --time_target_transform log1p \
  --time_loss_type huber \
  --time_loss_weight 0.1 \
  --output_dir "$MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only_stage3_v2/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7
epoch=1, loss=0.9279
epoch=2, loss=0.4477
epoch=3, loss=0.3558
epoch=4, loss=0.3173
epoch=5, loss=0.2914
valid [task], Top5Acc: 0.4535, Top10Acc: 0.7107, Acc: 0.0713, MacroF1: 0.1047, TimeMAE: 81441.6608, TimeRMSE: 300714.1305, TimeMedAE: 801.4105
valid [full], NDCG@5: 0.6386, HR@5: 0.7661, NDCG@10: 0.7078, HR@10: 0.9921, MRR: 0.6244
valid [sampled], NDCG@5: 0.5209, HR@5: 0.5238, NDCG@10: 0.5311, HR@10: 0.5559, MRR: 0.5385
test [task], Top5Acc: 0.2020, Top10Acc: 0.5105, Acc: 0.0392, MacroF1: 0.0355, TimeMAE: 11404.6986, TimeRMSE: 81788.3224, TimeMedAE: 31.6006
test [full], NDCG@5: 0.5962, HR@5: 0.7539, NDCG@10: 0.6389, HR@10: 0.8905, MRR: 0.5693
test [sampled], NDCG@5: 0.1788, HR@5: 0.1855, NDCG@10: 0.1971, HR@10: 0.2435, MRR: 0.2185
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/sasrec_best.pth
epoch=6, loss=0.2673
epoch=7, loss=0.2500
epoch=8, loss=0.2365
epoch=9, loss=0.2278
epoch=10, loss=0.2222
valid [task], Top5Acc: 0.4165, Top10Acc: 0.6514, Acc: 0.0671, MacroF1: 0.0693, TimeMAE: 74211.4444, TimeRMSE: 294642.1489, TimeMedAE: 819.8141
valid [full], NDCG@5: 0.6972, HR@5: 0.8202, NDCG@10: 0.7514, HR@10: 0.9884, MRR: 0.6804
valid [sampled], NDCG@5: 0.5818, HR@5: 0.5856, NDCG@10: 0.5914, HR@10: 0.6158, MRR: 0.5981
test [task], Top5Acc: 0.0843, Top10Acc: 0.6952, Acc: 0.0310, MacroF1: 0.0214, TimeMAE: 11999.7019, TimeRMSE: 82089.2267, TimeMedAE: 9.8120
test [full], NDCG@5: 0.6602, HR@5: 0.9184, NDCG@10: 0.6881, HR@10: 1.0000, MRR: 0.5867
test [sampled], NDCG@5: 0.2055, HR@5: 0.2099, NDCG@10: 0.2207, HR@10: 0.2582, MRR: 0.2477
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/sasrec_best.pth
epoch=11, loss=0.2177
epoch=12, loss=0.2118
epoch=13, loss=0.2073
epoch=14, loss=0.2053
epoch=15, loss=0.2020
valid [task], Top5Acc: 0.4034, Top10Acc: 0.6172, Acc: 0.0646, MacroF1: 0.0657, TimeMAE: 75843.0167, TimeRMSE: 285911.5438, TimeMedAE: 803.7405
valid [full], NDCG@5: 0.6912, HR@5: 0.8229, NDCG@10: 0.7392, HR@10: 0.9700, MRR: 0.6710
valid [sampled], NDCG@5: 0.5675, HR@5: 0.5728, NDCG@10: 0.5796, HR@10: 0.6107, MRR: 0.5847
test [task], Top5Acc: 0.2440, Top10Acc: 0.6914, Acc: 0.0227, MacroF1: 0.0185, TimeMAE: 11780.4982, TimeRMSE: 79043.0284, TimeMedAE: 9.5770
test [full], NDCG@5: 0.7079, HR@5: 0.9861, NDCG@10: 0.7126, HR@10: 1.0000, MRR: 0.6167
test [sampled], NDCG@5: 0.2496, HR@5: 0.2542, NDCG@10: 0.2831, HR@10: 0.3622, MRR: 0.2961
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.2013
epoch=17, loss=0.1971
epoch=18, loss=0.1957
epoch=19, loss=0.1955
epoch=20, loss=0.1936
valid [task], Top5Acc: 0.4032, Top10Acc: 0.6191, Acc: 0.0591, MacroF1: 0.0678, TimeMAE: 73701.6821, TimeRMSE: 294982.1153, TimeMedAE: 1149.2120
valid [full], NDCG@5: 0.7019, HR@5: 0.8623, NDCG@10: 0.7369, HR@10: 0.9730, MRR: 0.6669
valid [sampled], NDCG@5: 0.5652, HR@5: 0.5693, NDCG@10: 0.5765, HR@10: 0.6044, MRR: 0.5823
test [task], Top5Acc: 0.2427, Top10Acc: 0.6933, Acc: 0.0182, MacroF1: 0.0147, TimeMAE: 12280.7838, TimeRMSE: 83498.9362, TimeMedAE: 30.0436
test [full], NDCG@5: 0.6897, HR@5: 0.9890, NDCG@10: 0.6934, HR@10: 1.0000, MRR: 0.5924
test [sampled], NDCG@5: 0.2459, HR@5: 0.2508, NDCG@10: 0.2726, HR@10: 0.3365, MRR: 0.2887
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.1922
epoch=22, loss=0.1896
epoch=23, loss=0.1907
epoch=24, loss=0.1896
epoch=25, loss=0.1873
valid [task], Top5Acc: 0.4008, Top10Acc: 0.7053, Acc: 0.0616, MacroF1: 0.0756, TimeMAE: 71647.7982, TimeRMSE: 283219.5807, TimeMedAE: 1880.6394
valid [full], NDCG@5: 0.7189, HR@5: 0.8733, NDCG@10: 0.7497, HR@10: 0.9719, MRR: 0.6827
valid [sampled], NDCG@5: 0.5637, HR@5: 0.5698, NDCG@10: 0.5788, HR@10: 0.6175, MRR: 0.5835
test [task], Top5Acc: 0.2388, Top10Acc: 0.7375, Acc: 0.0256, MacroF1: 0.0243, TimeMAE: 11737.6497, TimeRMSE: 74608.4848, TimeMedAE: 43.4971
test [full], NDCG@5: 0.7097, HR@5: 0.9912, NDCG@10: 0.7126, HR@10: 1.0000, MRR: 0.6174
test [sampled], NDCG@5: 0.2528, HR@5: 0.2621, NDCG@10: 0.2791, HR@10: 0.3460, MRR: 0.2949
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.1875
epoch=27, loss=0.1878
epoch=28, loss=0.1844
epoch=29, loss=0.1866
epoch=30, loss=0.1834
valid [task], Top5Acc: 0.4055, Top10Acc: 0.6581, Acc: 0.0586, MacroF1: 0.0875, TimeMAE: 74719.7668, TimeRMSE: 288203.0026, TimeMedAE: 2176.8529
valid [full], NDCG@5: 0.6905, HR@5: 0.8812, NDCG@10: 0.7180, HR@10: 0.9708, MRR: 0.6410
valid [sampled], NDCG@5: 0.4962, HR@5: 0.5009, NDCG@10: 0.5096, HR@10: 0.5432, MRR: 0.5189
test [task], Top5Acc: 0.2355, Top10Acc: 0.6579, Acc: 0.0193, MacroF1: 0.0186, TimeMAE: 11564.2221, TimeRMSE: 80238.1432, TimeMedAE: 31.5489
test [full], NDCG@5: 0.7190, HR@5: 0.9877, NDCG@10: 0.7231, HR@10: 0.9999, MRR: 0.6324
test [sampled], NDCG@5: 0.2515, HR@5: 0.2665, NDCG@10: 0.2788, HR@10: 0.3522, MRR: 0.2914
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.1846
epoch=32, loss=0.1845
epoch=33, loss=0.1826
epoch=34, loss=0.1825
epoch=35, loss=0.1831
valid [task], Top5Acc: 0.3952, Top10Acc: 0.7136, Acc: 0.0598, MacroF1: 0.0639, TimeMAE: 74871.7620, TimeRMSE: 285759.0747, TimeMedAE: 5728.9446
valid [full], NDCG@5: 0.7029, HR@5: 0.8608, NDCG@10: 0.7334, HR@10: 0.9578, MRR: 0.6651
valid [sampled], NDCG@5: 0.5077, HR@5: 0.5143, NDCG@10: 0.5302, HR@10: 0.5850, MRR: 0.5333
test [task], Top5Acc: 0.2356, Top10Acc: 0.6728, Acc: 0.0224, MacroF1: 0.0235, TimeMAE: 12726.1429, TimeRMSE: 77252.1786, TimeMedAE: 65.1496
test [full], NDCG@5: 0.7150, HR@5: 0.9921, NDCG@10: 0.7177, HR@10: 1.0000, MRR: 0.6244
test [sampled], NDCG@5: 0.2447, HR@5: 0.2553, NDCG@10: 0.2756, HR@10: 0.3535, MRR: 0.2876
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.1834
epoch=37, loss=0.1822
epoch=38, loss=0.1831
epoch=39, loss=0.1811
epoch=40, loss=0.1804
valid [task], Top5Acc: 0.4013, Top10Acc: 0.7089, Acc: 0.0609, MacroF1: 0.0817, TimeMAE: 73292.6226, TimeRMSE: 287418.5267, TimeMedAE: 4480.8596
valid [full], NDCG@5: 0.7124, HR@5: 0.8882, NDCG@10: 0.7344, HR@10: 0.9607, MRR: 0.6659
valid [sampled], NDCG@5: 0.5273, HR@5: 0.5338, NDCG@10: 0.5452, HR@10: 0.5902, MRR: 0.5497
test [task], Top5Acc: 0.2394, Top10Acc: 0.6709, Acc: 0.0191, MacroF1: 0.0216, TimeMAE: 12730.9825, TimeRMSE: 71152.1690, TimeMedAE: 89.0766
test [full], NDCG@5: 0.7053, HR@5: 0.9907, NDCG@10: 0.7086, HR@10: 0.9999, MRR: 0.6126
test [sampled], NDCG@5: 0.2439, HR@5: 0.2541, NDCG@10: 0.2721, HR@10: 0.3439, MRR: 0.2862
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.1822
epoch=42, loss=0.1810
epoch=43, loss=0.1798
epoch=44, loss=0.1808
epoch=45, loss=0.1787
valid [task], Top5Acc: 0.4012, Top10Acc: 0.7187, Acc: 0.0567, MacroF1: 0.0679, TimeMAE: 75061.2632, TimeRMSE: 292012.3237, TimeMedAE: 4561.2995
valid [full], NDCG@5: 0.7262, HR@5: 0.8946, NDCG@10: 0.7479, HR@10: 0.9670, MRR: 0.6815
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5631, NDCG@10: 0.5721, HR@10: 0.6113, MRR: 0.5776
test [task], Top5Acc: 0.2329, Top10Acc: 0.6702, Acc: 0.0188, MacroF1: 0.0202, TimeMAE: 13016.3917, TimeRMSE: 69321.7211, TimeMedAE: 171.1543
test [full], NDCG@5: 0.7131, HR@5: 0.9961, NDCG@10: 0.7144, HR@10: 1.0000, MRR: 0.6197
test [sampled], NDCG@5: 0.2509, HR@5: 0.2590, NDCG@10: 0.2788, HR@10: 0.3478, MRR: 0.2942
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.1788
epoch=47, loss=0.1790
epoch=48, loss=0.1781
epoch=49, loss=0.1781
epoch=50, loss=0.1787
valid [task], Top5Acc: 0.4010, Top10Acc: 0.6945, Acc: 0.0601, MacroF1: 0.0960, TimeMAE: 78277.7686, TimeRMSE: 290895.1961, TimeMedAE: 5011.8487
valid [full], NDCG@5: 0.7014, HR@5: 0.8633, NDCG@10: 0.7311, HR@10: 0.9578, MRR: 0.6631
valid [sampled], NDCG@5: 0.5298, HR@5: 0.5357, NDCG@10: 0.5454, HR@10: 0.5846, MRR: 0.5515
test [task], Top5Acc: 0.2363, Top10Acc: 0.6664, Acc: 0.0206, MacroF1: 0.0210, TimeMAE: 11828.2704, TimeRMSE: 65809.4012, TimeMedAE: 123.5452
test [full], NDCG@5: 0.7105, HR@5: 0.9977, NDCG@10: 0.7113, HR@10: 1.0000, MRR: 0.6165
test [sampled], NDCG@5: 0.2518, HR@5: 0.2602, NDCG@10: 0.2764, HR@10: 0.3391, MRR: 0.2934
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_stage3_refine_sinusoidal_multitask_w01_ndcg10_v1/multitask_sinusoidal_dstart_ml50_do035_w01_s7/sasrec_last.pth

## Load run summaries

In [19]:
import json
from pathlib import Path
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in sorted(output_path.iterdir()):
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'use_time_attention_bias': config.get('use_time_attention_bias', False),
            'enable_time_prediction': config.get('enable_time_prediction', False),
            'time_delta_column': config.get('time_delta_column'),
            'time_encoding': config.get('time_encoding'),
            'time_prediction_target': config.get('time_prediction_target'),
            'time_loss_weight': config.get('time_loss_weight'),
            'time_loss_type': config.get('time_loss_type'),
            'time_target_transform': config.get('time_target_transform'),
            'time_modeling_mode': config.get('time_modeling_mode'),
            'time_sinusoidal_base': config.get('time_sinusoidal_base'),
        }
        for group_name in ['best_valid', 'best_test_at_best_valid', 'last_valid', 'last_test']:
            group = summary.get(group_name) or {}
            for mode, metrics in group.items():
                for key, value in metrics.items():
                    row[f'{group_name}_{mode}_{key}'] = value
        rows.append(row)
    return pd.DataFrame(rows)

In [20]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2400)
pd.set_option('display.max_colwidth', None)

## Compare refine baseline / single-task time-aware / multi-task time-aware

In [21]:
baseline_runs = [
    'refine_ml50_do035_s42',
    'refine_ml50_do035_s2024',
    'refine_ml50_do035_s7',
]
single_task_attnbias_runs = [
    'attnbias_dstart_ml50_do035_b9_s42',
    'attnbias_dstart_ml50_do035_b9_s2024',
    'attnbias_dstart_ml50_do035_b9_s7',
]
single_task_sinusoidal_runs = [
    'timeaware_dstart_sinusoidal_ml50_do035_s42',
    'timeaware_dstart_sinusoidal_ml50_do035_s2024',
    'timeaware_dstart_sinusoidal_ml50_do035_s7',
]
multitask_baseline_runs = [
    'multitask_refine_ml50_do035_s42',
    'multitask_refine_ml50_do035_s2024',
    'multitask_refine_ml50_do035_s7',
]
multitask_attnbias_runs = [
    'multitask_attnbias_dstart_ml50_do035_b9_s42',
    'multitask_attnbias_dstart_ml50_do035_b9_s2024',
    'multitask_attnbias_dstart_ml50_do035_b9_s7',
]
multitask_sinusoidal_runs = [
    'multitask_sinusoidal_dstart_ml50_do035_s42',
    'multitask_sinusoidal_dstart_ml50_do035_s2024',
    'multitask_sinusoidal_dstart_ml50_do035_s7',
]
multitask_sinusoidal_w01_runs = [
    'multitask_sinusoidal_dstart_ml50_do035_w01_s42',
    'multitask_sinusoidal_dstart_ml50_do035_w01_s2024',
    'multitask_sinusoidal_dstart_ml50_do035_w01_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
single_task_attnbias_df = rebuild_df(SINGLE_TASK_ATTNBIAS_NDCG10_OUTPUT_DIR)
single_task_sinusoidal_df = rebuild_df(SINGLE_TASK_SINUSOIDAL_NDCG10_OUTPUT_DIR)
multitask_baseline_df = rebuild_df(MULTITASK_BASELINE_OUTPUT_DIR)
multitask_attnbias_df = rebuild_df(MULTITASK_REFINE_ATTNBIAS_OUTPUT_DIR)
multitask_sinusoidal_df = rebuild_df(MULTITASK_REFINE_SINUSOIDAL_OUTPUT_DIR)
multitask_sinusoidal_w01_df = rebuild_df(MULTITASK_REFINE_SINUSOIDAL_W01_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['variant'] = 'refine_baseline'

single_task_attnbias_subset = single_task_attnbias_df[single_task_attnbias_df['run_name'].isin(single_task_attnbias_runs)].copy()
single_task_attnbias_subset['variant'] = 'refine_attnbias_single_task'

single_task_sinusoidal_subset = single_task_sinusoidal_df[single_task_sinusoidal_df['run_name'].isin(single_task_sinusoidal_runs)].copy()
single_task_sinusoidal_subset['variant'] = 'refine_sinusoidal_single_task'

multitask_baseline_subset = multitask_baseline_df[multitask_baseline_df['run_name'].isin(multitask_baseline_runs)].copy()
multitask_baseline_subset['variant'] = 'refine_multi_task_w1.0'

multitask_attnbias_subset = multitask_attnbias_df[multitask_attnbias_df['run_name'].isin(multitask_attnbias_runs)].copy()
multitask_attnbias_subset['variant'] = 'refine_attnbias_multi_task_w1.0'

multitask_sinusoidal_subset = multitask_sinusoidal_df[multitask_sinusoidal_df['run_name'].isin(multitask_sinusoidal_runs)].copy()
multitask_sinusoidal_subset['variant'] = 'refine_sinusoidal_multi_task_w1.0'

multitask_sinusoidal_w01_subset = multitask_sinusoidal_w01_df[multitask_sinusoidal_w01_df['run_name'].isin(multitask_sinusoidal_w01_runs)].copy()
multitask_sinusoidal_w01_subset['variant'] = 'refine_sinusoidal_multi_task_w0.1'

df_compare = pd.concat(
    [
        baseline_subset,
        single_task_attnbias_subset,
        single_task_sinusoidal_subset,
        multitask_baseline_subset,
        multitask_attnbias_subset,
        multitask_sinusoidal_subset,
        multitask_sinusoidal_w01_subset,
    ],
    ignore_index=True,
)
df_compare = df_compare.sort_values(['variant', 'seed', 'run_name']).reset_index(drop=True)

display_cols = [
    'run_name', 'seed', 'variant', 'maxlen', 'dropout_rate', 'selection_metric', 'best_epoch',
    'time_encoding', 'time_delta_column', 'time_loss_weight', 'time_prediction_target',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10', 'best_valid_full_mrr',
    'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5',
    'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10', 'best_test_at_best_valid_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10', 'best_valid_sampled_mrr',
    'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5',
    'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10', 'best_test_at_best_valid_sampled_mrr',
    'best_valid_task_accuracy', 'best_valid_task_macro_f1',
    'best_valid_task_top5_accuracy', 'best_valid_task_top10_accuracy',
    'best_valid_task_time_mae', 'best_valid_task_time_rmse', 'best_valid_task_time_median_ae',
    'best_test_at_best_valid_task_accuracy', 'best_test_at_best_valid_task_macro_f1',
    'best_test_at_best_valid_task_top5_accuracy', 'best_test_at_best_valid_task_top10_accuracy',
    'best_test_at_best_valid_task_time_mae', 'best_test_at_best_valid_task_time_rmse', 'best_test_at_best_valid_task_time_median_ae',
]
existing_display_cols = [c for c in display_cols if c in df_compare.columns]
df_compare[existing_display_cols]

                                            run_name  seed                            variant  maxlen  dropout_rate    selection_metric  best_epoch time_encoding    time_delta_column time_loss_weight time_prediction_target  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_mrr  best_test_at_best_valid_full_ndcg@5  best_test_at_best_valid_full_hr@5  best_test_at_best_valid_full_ndcg@10  best_test_at_best_valid_full_hr@10  best_test_at_best_valid_full_mrr  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_mrr  best_test_at_best_valid_sampled_ndcg@5  best_test_at_best_valid_sampled_hr@5  best_test_at_best_valid_sampled_ndcg@10  best_test_at_best_valid_sampled_hr@10  best_test_at_best_valid_sampled_mrr  best_valid_task_accuracy  best_valid_task_macro_f1  best_valid_task_top5_accuracy  best_valid_task_top10_accuracy  best_valid_task_time_mae  best_valid_task_time_rmse  best_valid_task_time_median_ae  best_test_at_best_valid_task_accuracy  best_test_at_best_valid_task_macro_f1  best_test_at_best_valid_task_top5_accuracy  best_test_at_best_valid_task_top10_accuracy  best_test_at_best_valid_task_time_mae  best_test_at_best_valid_task_time_rmse  best_test_at_best_valid_task_time_median_ae
0         multitask_attnbias_dstart_ml50_do035_b9_s7     7    refine_attnbias_multi_task_w1.0      50          0.35  full_valid_ndcg@10          25           raw  delta_start_seconds              1.0     delta_next_seconds                0.701169              0.841042                 0.741140               0.968127             0.674917                             0.724066                           0.978226                              0.729992                            0.995266                          0.640692                   0.584575                 0.587549                    0.589915                  0.604232                0.599089                                0.161131                              0.165134                                 0.197971                               0.283338                             0.214905                  0.064153                  0.054342                       0.394005                        0.606402              69849.790407              280340.108895                     2552.965280                               0.027996                               0.022689                                    0.382878                                     0.617663                           12280.778068                            76506.943274                                   301.367851
1        multitask_attnbias_dstart_ml50_do035_b9_s42    42    refine_attnbias_multi_task_w1.0      50          0.35  full_valid_ndcg@10          35           raw  delta_start_seconds              1.0     delta_next_seconds                0.705553              0.836408                 0.748445               0.968937             0.684121                             0.779972                           0.975749                              0.788496                            1.000000                          0.719152                   0.597182                 0.599023                    0.602575                  0.615979                0.611855                                0.210614                              0.246850                                 0.264049                               0.413901                             0.249278                  0.061856                  0.079921                       0.456593                        0.641888              70299.450571              281214.731226                     1427.825244                               0.023574                               0.019707                                    0.318521                                     0.667254                           11338.988327                            72120.057406                                    75.289802
2      multitask_attnbias_dstart_ml50_do035_b9_s2024  2024    refine_attnbias_multi_task_w1.0      50          0.35  full_valid_ndcg@10          30           raw  delta_start_seconds              1.0     delta_next_seconds                0.688210              0.807562                 0.739497               0.969508             0.672990                             0.774766                           0.953504                              0.790523                            0.999864                          0.721091                   0.584314                 0.588291                    0.592206                  0.612956                0.598530                                0.223472                              0.271520                                 0.297880                               0.502508                             0.259729                  0.059900                  0.039673                       0.451281                        0.707955              78572.105940              291972.478347                    10619.751266                               0.117256                               0.046148                                    0.608920                                     0.633455                           15157.516227                            76170.374705                                   108.494928
3                   attnbias_dstart_ml50_do035_b9_s7     7        refine_attnbias_single_task      50          0.35  full_valid_ndcg@10          40           raw  delta_start_seconds             None                   None                0.714870              0.824671                 0.755366               0.953861             0.699184                             0.846665                           0.999728                              0.846762                            1.000000                          0.793978                   0.607399                 0.615479                    0.623265                  0.666077                0.623619                                0.442098                              0.450204                                 0.497216                               0.628223                             0.485290                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
4                  attnbias_dstart_ml50_do035_b9_s42    42        refine_attnbias_single_task      50          0.35  full_valid_ndcg@10          20           raw  delta_start_seconds             None                   None                0.709565              0.864487                 0.741856               0.969750             0.673783                             0.764719                           0.935724                              0.785724                            0.999865                          0.714860                   0.566501                 0.577970                    0.585005                  0.635957                0.585189                                0.115783                              0.193920                                 0.199334                               0.453522                             0.156593                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
5                attnbias_dstart_ml50_do035_b9_s2024  2024        refine_attnbias_single_task      50          0.35  full_valid_ndcg@10          20           raw  delta_start_seconds             None                   None                0.702964              0.865254                 0.735385               0.971475             0.665031                             0.863911                           0.928234                              0.885738                            0.999865                          0.850981                   0.548977                 0.558247                    0.566216                  0.612548                0.568592                                0.366083                              0.436179                                 0.428086                               0.626287                             0.388188                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
6                               refine_ml50_do035_s7     7                    refine_baseline      50          0.35  full_valid_ndcg@10          25          None   delta_prev_seconds             None                   None                0.696223              0.857259                 0.728826               0.961737             0.660451                             0.859037                           0.957678                              0.872416                            1.000000                          0.831208                   0.565802                 0.575315                    0.577254                  0.611043                0.581977                                0.324827                              0.417493                                 0.403018                               0.656933                             0.345750                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
7                              refine_ml50_do035_s42    42                    refine_baseline      50          0.35  full_valid_ndcg@10          50          None   delta_prev_seconds             None                   None                0.697410              0.854186                 0.735378               0.977276             0.663510                             0.868726                           0.926375                              0.891774                            1.000000                          0.858375                   0.555385                 0.565093                    0.568693                  0.606441                0.572753                                0.399455                              0.467411                                 0.456024                               0.640631                             0.419230                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
8                            refine_ml50_do035_s2024  2024                    refine_baseline      50          0.35  full_valid_ndcg@10           5          None   delta_prev_seconds             None                   None                0.713154              0.906351                 0.741573               0.992973             0.664353                             0.727453                           0.850196                              0.775861                            1.000000                          0.707187                   0.563603                 0.567069                    0.572972                  0.597043                0.582973                                0.203548                              0.264514                                 0.257972                               0.431769                             0.234183                       NaN                       NaN                            NaN                             NaN                       NaN                        NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN                                    NaN                                     NaN                                          NaN
9                     multitask_refine_ml50_do035_s7     7             refine_multi_task_w1.0      50          0.35  full_valid_ndcg@10          15        bucket   delta_prev_seconds              1.0     delta_next_seconds                0.655287              0.712502                 0.732565               0.956292             0.670971                             0.657646                           0.838091                              0.711474                            1.000000                          0.619819                   0.601089                 0.601466                    0.604692                  0.612868                0.613268                                0.173962                              0.185291                                 0.200368                               0.268896                             0.217592                  0.067056                  0.094597                       0.450387                        0.769105              71791.261270              279170.227263                      814.182786                               0.026237                               0.022837                                    0.305193                                     0.615960                           12867.716649                            79895.493810                                     8.677288
10                   multitask_refine_ml50_do035_s42    42             refine_multi_task_w1.0      50          0.35  full_valid_ndcg@10          15        bucket   delta_prev_seconds              1.0     delta_next_seconds                0.666060              0.751256                 0.733665               0.968635             0.668249                             0.653704                           0.939640                              0.673060                            1.000000                          0.565251                   0.603242                 0.603530                    0.604295                  0.606925                0.614372                                0.082418                              0.084585                                 0.113424                               0.184599                             0.136265                  0.060692                  0.075838                       0.451052                        0.705092              74687.149202              283050.310794                      698.975902                               0.023007                               0.016782                                    0.315469                                     0.519827                           11669.578547                            73839.383908                                    58.406232
11                 multitask_refine_ml50_do035_s2024  2024             refine_multi_task_w1.0      50          0.35  full_valid_ndcg@10          30        bucket   delta_prev_seconds              1.0     delta_next_seconds                0.692600              0.805665                 0.737569               0.941862             0.680081                             0.739492                           0.973295                              0.749001                            1.000000                          0.666433                   0.601399                 0.604011                    0.606361                  0.619596                0.614094                                0.119428                              0.161312                                 0.182997                               0.359089                             0.163382                  0.065185                  0.111175                       0.456701                        0.599946              76760.182247              292111.312040                     4485.440184                               0.032805                               0.026196                                    0.420767                                     0.609055                           13892.641159                            76083.712405                                   142.218559
12     multitask_sinusoidal_dstart_ml50_do035_w01_s7     7  refine_sinusoidal_multi_task_w0.1      50          0.35  full_valid_ndcg@10          10    sinusoidal  delta_start_seconds              0.1     delta_next_seconds                0.697228              0.820185                 0.751395               0.988439             0.680374                             0.660200                           0.918398                              0.688060                            1.000000                          0.586685                   0.581809                 0.585555                    0.591365                  0.615751                0.598094                                0.205537                              0.209912                                 0.220664                               0.258248                             0.247732                  0.067057                  0.069294                       0.416485                        0.651387              74211.444408              294642.148926                      819.814076                               0.030957                               0.021433                                    0.084318                                     0.695180                           11999.701927                            82089.226652                                     9.812000

In [22]:
summary_metric_cols = [
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10', 'best_valid_full_mrr',
    'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5',
    'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10', 'best_test_at_best_valid_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10', 'best_valid_sampled_mrr',
    'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5',
    'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10', 'best_test_at_best_valid_sampled_mrr',
    'best_valid_task_accuracy', 'best_valid_task_macro_f1',
    'best_valid_task_top5_accuracy', 'best_valid_task_top10_accuracy',
    'best_valid_task_time_mae', 'best_valid_task_time_rmse', 'best_valid_task_time_median_ae',
    'best_test_at_best_valid_task_accuracy', 'best_test_at_best_valid_task_macro_f1',
    'best_test_at_best_valid_task_top5_accuracy', 'best_test_at_best_valid_task_top10_accuracy',
    'best_test_at_best_valid_task_time_mae', 'best_test_at_best_valid_task_time_rmse', 'best_test_at_best_valid_task_time_median_ae',
]
summary_metric_cols = [c for c in summary_metric_cols if c in df_compare.columns]
summary_compare = df_compare.groupby('variant')[summary_metric_cols].agg(['mean', 'std'])
summary_compare

                                  best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_mrr           best_test_at_best_valid_full_ndcg@5           best_test_at_best_valid_full_hr@5           best_test_at_best_valid_full_ndcg@10           best_test_at_best_valid_full_hr@10           best_test_at_best_valid_full_mrr           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_mrr           best_test_at_best_valid_sampled_ndcg@5           best_test_at_best_valid_sampled_hr@5           best_test_at_best_valid_sampled_ndcg@10           best_test_at_best_valid_sampled_hr@10           best_test_at_best_valid_sampled_mrr           best_valid_task_accuracy           best_valid_task_macro_f1           best_valid_task_top5_accuracy           best_valid_task_top10_accuracy           best_valid_task_time_mae               best_valid_task_time_rmse              best_valid_task_time_median_ae              best_test_at_best_valid_task_accuracy           best_test_at_best_valid_task_macro_f1           best_test_at_best_valid_task_top5_accuracy           best_test_at_best_valid_task_top10_accuracy           best_test_at_best_valid_task_time_mae              best_test_at_best_valid_task_time_rmse              best_test_at_best_valid_task_time_median_ae
                                                    mean       std                 mean       std                    mean       std                  mean       std                mean       std                                mean       std                              mean       std                                 mean       std                               mean       std                             mean       std                      mean       std                    mean       std                       mean       std                     mean       std                   mean       std                                   mean       std                                 mean       std                                    mean       std                                  mean       std                                mean       std                     mean       std                     mean       std                          mean       std                           mean       std                     mean           std                      mean          std                           mean          std                                  mean       std                                  mean       std                                       mean       std                                        mean       std                                  mean          std                                   mean          std                                        mean         std
variant
refine_attnbias_multi_task_w1.0                 0.698311  0.009018             0.828337  0.018140                0.743028  0.004763              0.968857  0.000694            0.677342  0.005949                            0.759601  0.030885                          0.969159  0.013614                             0.769670  0.034377                           0.998377  0.002695                         0.693645  0.045869                  0.588691  0.007355                0.591621  0.006421                   0.594899  0.006746                 0.611056  0.006100               0.603158  0.007537                               0.198406  0.032915                             0.227835  0.055684                                0.253300  0.050815                              0.399915  0.110252                            0.241304  0.023452                 0.061969  0.002129                 0.057979  0.020369                      0.433959  0.034703                       0.652082  0.051538             72907.115639   4911.174492             284509.106156  6478.247016                    4866.847263  5013.822232                              0.056275  0.052857                              0.029515  0.014482                                   0.436773  0.152517                                    0.639457  0.025334                          12925.760874  1989.294082                           74932.458462  2441.417493                                  161.717527  122.074997
refine_attnbias_single_task                     0.709133  0.005965             0.851471  0.023212                0.744203  0.010195              0.965029  0.009710            0.679333  0.017740                            0.825099  0.052996                          0.954562  0.039294                             0.839408  0.050411                           0.999910  0.000078                         0.786607  0.068359                  0.574292  0.029980                0.583899  0.029073                   0.591495  0.029073                 0.638194  0.026835               0.592467  0.028226                               0.307988  0.170739                             0.360101  0.144087                                0.374879  0.155906                              0.569344  0.100310                            0.343357  0.168872                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                      NaN           NaN                       NaN          NaN                            NaN          NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN                                   NaN          NaN                                    NaN          NaN                                         NaN         NaN
refine_baseline                                 0.702263  0.009451             0.872599  0.029271                0.735259  0.006374              0.977329  0.015618            0.662771  0.002053                            0.818405  0.078916                          0.911416  0.055280                             0.846684  0.062093                           1.000000  0.000000                         0.798923  0.080599                  0.561597  0.005491                0.569159  0.005422                   0.572973  0.004280                 0.604843  0.007136               0.579235  0.005635                               0.309277  0.098875                             0.383139  0.105721                                0.372338  0.102528                              0.576445  0.125558                            0.333054  0.093175                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                      NaN           NaN                       NaN          NaN                            NaN          NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN                                   NaN          NaN                                    NaN          NaN                                         NaN         NaN
refine_multi_task_w1.0                          0.671316  0.019204             0.756474  0.046800                0.734600  0.002629              0.955596  0.013400            0.673100  0.006196                            0.683614  0.048432                          0.917009  0.070386                             0.711178  0.037972                           1.000000  0.000000                         0.617168  0.050643                  0.601910  0.001164                0.603003  0.001352                   0.605116  0.001097                 0.613130  0.006340               0.613911  0.000574                               0.125269  0.046051                             0.143729  0.052605                                0.165596  0.046010                              0.270861  0.087262                            0.172413  0.041409                 0.064311  0.003270                 0.093870  0.017680                      0.452714  0.003470                       0.691381  0.085409             74412.864240   2495.790075             284777.283366  6641.140301                    1999.532957  2153.629311                              0.027350  0.004993                              0.021938  0.004771                                   0.347143  0.063967                                    0.581614  0.053620                          12809.978785  1112.655423                           76606.196708  3061.675876                                   69.767360   67.491660
refine_sinusoidal_multi_task_w0.1               0.705366  0.007280             0.843514  0.024978                0.748167  0.007143              0.976211  0.010600            0.679704  0.009575                            0.815241  0.134995                          0.969261  0.044202                             0.825664  0.120125                           1.000000  0.000000                         0.768117  0.158490                  0.565663  0.023975                0.570870  0.022524                   0.579778  0.021154                 0.615082  0.015734               0.584388  0.021672                               0.279169  0.069807                             0.312635  0.092505                                0.329694  0.096625                              0.470514  0.183829                            0.317658  0.065804                 0.058481  0.007531                 0.075822  0.005824                      0.440420  0.050940                       0.703883  0.084584             76987.378127   2934.459778             289124.309324  5776.856355                    3682.657172  3823.849156                              0.053318  0.052436                              0.025552  0.012974                                   0.331330  0.214225                                    0.684573  0.009553                          13325.692684  2679.482629                           77805.516292  4495.589284                                   54.800592   49.725712
refine_sinusoidal_multi_task_w1.0               0.714810  0.009534             0.858260  0.022808                0.743442  0.004243              0.950178  0.011248            0.683107  0.008701                            0.756677  0.134066                          0.956955  0.045883                             0.770496  0.120772                           0.999458  0.000938                         0.695250  0.158294                  0.572338  0.010698                0.576336  0.010588                   0.584448  0.010651                 0.614473  0.017264               0.590561  0.010343                               0.201396  0.107176                             0.229588  0.129257                                0.253339  0.129578                              0.392453  0.197075                            0.243275  0.100798                 0.060054  0.001653                 0.066678  0.014159                      0.398353  0.035661                       0.663287  0.024996             79956.429495  11032.205645             287391.265274  8484.144754                    3728.874960  2831.209126                              0.022368  0.003657                              0.017962  0.001095                                   0.351449  0.140102                                    0.651944  0.107068                          15231.512973  3634.734213                           75898.037293  4015.802869                                  244.895638  294.440315
refine_sinusoidal_single_task                   0.704937  0.026514             0.859535  0.033082                0.741087  0.013042              0.973023  0.020092            0.671765  0.017617                            0.848106  0.079236                          0.951430  0.063724                             0.864428  0.058680                           1.000000  0.000000                         0.820530  0.075588                  0.560196  0.002588                0.565557  0.003105                   0.573719  0.007604                 0.608104  0.018950               0.578660  0.005863                               0.267901  0.120631                             0.308555  0.121484                                0.330552  0.112064                              0.503836  0.095015                            0.307056  0.113490                 0.132072  0.053034                 0.157268  0.038636                      0.460030  0.046765                       0.688575  0.010945                      NaN           NaN                       NaN          NaN                            NaN          NaN                              0.063762  0.069882                              0.032968  0.025514                                   0.469216  0.076161                                    0.718918  0.031512                                   NaN          NaN                                    NaN          NaN                                         NaN         NaN

## What to look at

Read the results in this order:
- compare `refine_sinusoidal_single_task` vs `refine_sinusoidal_multi_task_w1.0`
- compare `refine_sinusoidal_multi_task_w1.0` vs `refine_sinusoidal_multi_task_w0.1`
- compare `refine_sinusoidal_multi_task_w1.0` vs `refine_attnbias_multi_task_w1.0`
- use `best_test_at_best_valid_full_ndcg@10` as the main ranking metric
- use `best_test_at_best_valid_task_time_mae` as the main next-time metric