# SASRec Time-Aware BPI2012 Colab Train 09 (`Additive_sinusoidal`)

Stage 2 follow-up notebook for the new additive time-aware variant:
`Additive_sinusoidal`.

Goals:
- train `Additive_sinusoidal` with both `delta_prev_seconds` and `delta_start_seconds`
- use both backbones: `anchor_ml20`, `refine_ml50_do035`
- keep the usual 3 seeds: `42`, `2024`, `7`
- compare with completed Stage 2 runs, including `attention bias`
- display not only ranking metrics, but also task metrics such as `accuracy`, `macro_f1`, `top5_accuracy`, `top10_accuracy` when available

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.11.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
OUTPUT_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
ANCHOR_BUCKET_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_anchor_ml20_ndcg10'
REFINE_BUCKET_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_refine_ml50_do035_ndcg10'
REFINE_DSTART_BUCKET_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_refine_ml50_do035_b9_ndcg10'
REFINE_DSTART_CONT_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_deltastart_continuous_refine_ml50_do035_ndcg10'
ANCHOR_ATTN_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10'
REFINE_ATTN_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_refine_ndcg10'
SINUSOIDAL_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('SINUSOIDAL_NDCG10_OUTPUT_DIR:', SINUSOIDAL_NDCG10_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
SINUSOIDAL_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$SINUSOIDAL_NDCG10_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.11.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.5)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!rm -rf data/processed/bpi2012_complete_only
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

New runs to train:

- `anchor_ml20 + Additive_sinusoidal + delta_prev_seconds`
- `anchor_ml20 + Additive_sinusoidal + delta_start_seconds`
- `refine_ml50_do035 + Additive_sinusoidal + delta_prev_seconds`
- `refine_ml50_do035 + Additive_sinusoidal + delta_start_seconds`

Common setting:

- seeds: `42`, `2024`, `7`
- selection metric: `full_valid_ndcg@10`
- eval protocol: `both`

In [10]:
from pathlib import Path

comparison_run_groups = {
    'anchor_baseline': ['anchor_ml20_s42', 'anchor_ml20_s2024', 'anchor_ml20_s7'],
    'anchor_bucket_b9': ['timeaware_anchor_ml20_b9_s42', 'timeaware_anchor_ml20_b9_s2024', 'timeaware_anchor_ml20_b9_s7'],
    'anchor_attnbias_dstart_b9': ['attnbias_dstart_ml20_b9_s42', 'attnbias_dstart_ml20_b9_s2024', 'attnbias_dstart_ml20_b9_s7'],
    'anchor_sinusoidal_dprev': ['timeaware_dprev_sinusoidal_ml20_s42', 'timeaware_dprev_sinusoidal_ml20_s2024', 'timeaware_dprev_sinusoidal_ml20_s7'],
    'anchor_sinusoidal_dstart': ['timeaware_dstart_sinusoidal_ml20_s42', 'timeaware_dstart_sinusoidal_ml20_s2024', 'timeaware_dstart_sinusoidal_ml20_s7'],
    'refine_baseline': ['refine_ml50_do035_s42', 'refine_ml50_do035_s2024', 'refine_ml50_do035_s7'],
    'refine_bucket_b9': ['timeaware_refine_ml50_do035_b9_s42', 'timeaware_refine_ml50_do035_b9_s2024', 'timeaware_refine_ml50_do035_b9_s7'],
    'refine_dstart_bucket_b9': ['timeaware_dstart_refine_ml50_do035_b9_s42', 'timeaware_dstart_refine_ml50_do035_b9_s2024', 'timeaware_dstart_refine_ml50_do035_b9_s7'],
    'refine_dstart_continuous': ['timeaware_dstart_conti_refine_ml50_do035_s42', 'timeaware_dstart_conti_refine_ml50_do035_s2024', 'timeaware_dstart_conti_refine_ml50_do035_s7'],
    'refine_attnbias_dstart_b9': ['attnbias_dstart_ml50_do035_b9_s42', 'attnbias_dstart_ml50_do035_b9_s2024', 'attnbias_dstart_ml50_do035_b9_s7'],
    'refine_sinusoidal_dprev': ['timeaware_dprev_sinusoidal_ml50_do035_s42', 'timeaware_dprev_sinusoidal_ml50_do035_s2024', 'timeaware_dprev_sinusoidal_ml50_do035_s7'],
    'refine_sinusoidal_dstart': ['timeaware_dstart_sinusoidal_ml50_do035_s42', 'timeaware_dstart_sinusoidal_ml50_do035_s2024', 'timeaware_dstart_sinusoidal_ml50_do035_s7'],
}

scan_dirs = [
    Path(BASELINE_NDCG10_OUTPUT_DIR),
    Path(ANCHOR_BUCKET_NDCG10_OUTPUT_DIR),
    Path(REFINE_BUCKET_NDCG10_OUTPUT_DIR),
    Path(REFINE_DSTART_BUCKET_NDCG10_OUTPUT_DIR),
    Path(REFINE_DSTART_CONT_NDCG10_OUTPUT_DIR),
    Path(ANCHOR_ATTN_NDCG10_OUTPUT_DIR),
    Path(REFINE_ATTN_NDCG10_OUTPUT_DIR),
    Path(SINUSOIDAL_NDCG10_OUTPUT_DIR),
]

print('=' * 80)
print('Existing comparison runs')
for group_name, run_names in comparison_run_groups.items():
    print('-' * 80)
    print(group_name)
    for run_name in run_names:
        found = any((output_dir / run_name).exists() for output_dir in scan_dirs)
        print(run_name, 'EXISTS' if found else 'MISSING')

================================================================================
Existing comparison runs
--------------------------------------------------------------------------------
anchor_baseline
anchor_ml20_s42 EXISTS
anchor_ml20_s2024 EXISTS
anchor_ml20_s7 EXISTS
--------------------------------------------------------------------------------
anchor_bucket_b9
timeaware_anchor_ml20_b9_s42 EXISTS
timeaware_anchor_ml20_b9_s2024 EXISTS
timeaware_anchor_ml20_b9_s7 EXISTS
--------------------------------------------------------------------------------
anchor_attnbias_dstart_b9
attnbias_dstart_ml20_b9_s42 EXISTS
attnbias_dstart_ml20_b9_s2024 EXISTS
attnbias_dstart_ml20_b9_s7 EXISTS
--------------------------------------------------------------------------------
anchor_sinusoidal_dprev
timeaware_dprev_sinusoidal_ml20_s42 EXISTS
timeaware_dprev_sinusoidal_ml20_s2024 EXISTS
timeaware_dprev_sinusoidal_ml20_s7 EXISTS
--------------------------------------------------------------------------------
anchor_sinusoidal_dstart
timeaware_dstart_sinusoidal_ml20_s42 EXISTS
timeaware_dstart_sinusoidal_ml20_s2024 MISSING
timeaware_dstart_sinusoidal_ml20_s7 MISSING
--------------------------------------------------------------------------------
refine_baseline
refine_ml50_do035_s42 EXISTS
refine_ml50_do035_s2024 EXISTS
refine_ml50_do035_s7 EXISTS
--------------------------------------------------------------------------------
refine_bucket_b9
timeaware_refine_ml50_do035_b9_s42 EXISTS
timeaware_refine_ml50_do035_b9_s2024 EXISTS
timeaware_refine_ml50_do035_b9_s7 EXISTS
--------------------------------------------------------------------------------
refine_dstart_bucket_b9
timeaware_dstart_refine_ml50_do035_b9_s42 EXISTS
timeaware_dstart_refine_ml50_do035_b9_s2024 EXISTS
timeaware_dstart_refine_ml50_do035_b9_s7 EXISTS
--------------------------------------------------------------------------------
refine_dstart_continuous
timeaware_dstart_conti_refine_ml50_do035_s42 EXISTS
timeaware_dstart_conti_refine_ml50_do035_s2024 EXISTS
timeaware_dstart_conti_refine_ml50_do035_s7 EXISTS
--------------------------------------------------------------------------------
refine_attnbias_dstart_b9
attnbias_dstart_ml50_do035_b9_s42 EXISTS
attnbias_dstart_ml50_do035_b9_s2024 EXISTS
attnbias_dstart_ml50_do035_b9_s7 EXISTS
--------------------------------------------------------------------------------
refine_sinusoidal_dprev
timeaware_dprev_sinusoidal_ml50_do035_s42 MISSING
timeaware_dprev_sinusoidal_ml50_do035_s2024 MISSING
timeaware_dprev_sinusoidal_ml50_do035_s7 MISSING
--------------------------------------------------------------------------------
refine_sinusoidal_dstart
timeaware_dstart_sinusoidal_ml50_do035_s42 MISSING
timeaware_dstart_sinusoidal_ml50_do035_s2024 MISSING
timeaware_dstart_sinusoidal_ml50_do035_s7 MISSING

## Train `anchor_ml20 + Additive_sinusoidal + delta_prev_seconds`

### `timeaware_dprev_sinusoidal_ml20_s42`

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_dprev_sinusoidal_ml20_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_prev_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42
epoch=1, loss=0.5364
epoch=2, loss=0.2320
epoch=3, loss=0.1671
epoch=4, loss=0.1393
epoch=5, loss=0.1207
valid [task], Top5Acc: 0.4868, Top10Acc: 0.7467, Acc: 0.1428, MacroF1: 0.1762
valid [full], NDCG@5: 0.6605, HR@5: 0.7867, NDCG@10: 0.7168, HR@10: 0.9707, MRR: 0.6440
valid [sampled], NDCG@5: 0.5520, HR@5: 0.5570, NDCG@10: 0.5617, HR@10: 0.5875, MRR: 0.5674
test [task], Top5Acc: 0.0925, Top10Acc: 0.6212, Acc: 0.0261, MacroF1: 0.0180
test [full], NDCG@5: 0.5746, HR@5: 0.8199, NDCG@10: 0.6343, HR@10: 0.9999, MRR: 0.5197
test [sampled], NDCG@5: 0.1555, HR@5: 0.1622, NDCG@10: 0.1718, HR@10: 0.2140, MRR: 0.1948
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/sasrec_best.pth
epoch=6, loss=0.1118
epoch=7, loss=0.1034
epoch=8, loss=0.1005
epoch=9, loss=0.0982
epoch=10, loss=0.0942
valid [task], Top5Acc: 0.4886, Top10Acc: 0.7094, Acc: 0.1376, MacroF1: 0.1798
valid [full], NDCG@5: 0.6845, HR@5: 0.8195, NDCG@10: 0.7344, HR@10: 0.9758, MRR: 0.6630
valid [sampled], NDCG@5: 0.5553, HR@5: 0.5615, NDCG@10: 0.5715, HR@10: 0.6124, MRR: 0.5736
test [task], Top5Acc: 0.3992, Top10Acc: 0.7176, Acc: 0.0280, MacroF1: 0.0214
test [full], NDCG@5: 0.8071, HR@5: 0.9837, NDCG@10: 0.8125, HR@10: 1.0000, MRR: 0.7498
test [sampled], NDCG@5: 0.1719, HR@5: 0.2154, NDCG@10: 0.2447, HR@10: 0.4430, MRR: 0.2179
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/sasrec_best.pth
epoch=11, loss=0.0928
epoch=12, loss=0.0902
epoch=13, loss=0.0897
epoch=14, loss=0.0885
epoch=15, loss=0.0877
valid [task], Top5Acc: 0.4456, Top10Acc: 0.7043, Acc: 0.0828, MacroF1: 0.1428
valid [full], NDCG@5: 0.6811, HR@5: 0.8403, NDCG@10: 0.7204, HR@10: 0.9628, MRR: 0.6485
valid [sampled], NDCG@5: 0.5296, HR@5: 0.5336, NDCG@10: 0.5430, HR@10: 0.5761, MRR: 0.5498
test [task], Top5Acc: 0.4914, Top10Acc: 0.6699, Acc: 0.0310, MacroF1: 0.0230
test [full], NDCG@5: 0.8236, HR@5: 0.9801, NDCG@10: 0.8304, HR@10: 1.0000, MRR: 0.7732
test [sampled], NDCG@5: 0.1947, HR@5: 0.2432, NDCG@10: 0.2623, HR@10: 0.4530, MRR: 0.2380
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0861
epoch=17, loss=0.0856
epoch=18, loss=0.0819
epoch=19, loss=0.0843
epoch=20, loss=0.0839
valid [task], Top5Acc: 0.4345, Top10Acc: 0.7123, Acc: 0.1323, MacroF1: 0.1870
valid [full], NDCG@5: 0.6873, HR@5: 0.8240, NDCG@10: 0.7367, HR@10: 0.9765, MRR: 0.6648
valid [sampled], NDCG@5: 0.5505, HR@5: 0.5553, NDCG@10: 0.5662, HR@10: 0.6048, MRR: 0.5705
test [task], Top5Acc: 0.4857, Top10Acc: 0.6484, Acc: 0.0299, MacroF1: 0.0230
test [full], NDCG@5: 0.8010, HR@5: 0.9931, NDCG@10: 0.8034, HR@10: 1.0000, MRR: 0.7359
test [sampled], NDCG@5: 0.1599, HR@5: 0.1976, NDCG@10: 0.2260, HR@10: 0.4049, MRR: 0.2096
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/sasrec_best.pth
epoch=21, loss=0.0796
epoch=22, loss=0.0811
epoch=23, loss=0.0797
epoch=24, loss=0.0811
epoch=25, loss=0.0777
valid [task], Top5Acc: 0.4017, Top10Acc: 0.7015, Acc: 0.1352, MacroF1: 0.1796
valid [full], NDCG@5: 0.6834, HR@5: 0.8372, NDCG@10: 0.7282, HR@10: 0.9776, MRR: 0.6531
valid [sampled], NDCG@5: 0.5312, HR@5: 0.5358, NDCG@10: 0.5453, HR@10: 0.5805, MRR: 0.5517
test [task], Top5Acc: 0.5044, Top10Acc: 0.6748, Acc: 0.0361, MacroF1: 0.0248
test [full], NDCG@5: 0.8238, HR@5: 0.9831, NDCG@10: 0.8294, HR@10: 1.0000, MRR: 0.7712
test [sampled], NDCG@5: 0.2308, HR@5: 0.2674, NDCG@10: 0.2974, HR@10: 0.4757, MRR: 0.2770
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0788
epoch=27, loss=0.0786
epoch=28, loss=0.0803
epoch=29, loss=0.0793
epoch=30, loss=0.0785
valid [task], Top5Acc: 0.3865, Top10Acc: 0.6203, Acc: 0.0654, MacroF1: 0.1515
valid [full], NDCG@5: 0.7200, HR@5: 0.8696, NDCG@10: 0.7537, HR@10: 0.9778, MRR: 0.6853
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5654, NDCG@10: 0.5776, HR@10: 0.6212, MRR: 0.5818
test [task], Top5Acc: 0.5081, Top10Acc: 0.6448, Acc: 0.0281, MacroF1: 0.0241
test [full], NDCG@5: 0.8820, HR@5: 0.9988, NDCG@10: 0.8824, HR@10: 1.0000, MRR: 0.8430
test [sampled], NDCG@5: 0.3493, HR@5: 0.3983, NDCG@10: 0.4165, HR@10: 0.6072, MRR: 0.3830
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/sasrec_best.pth
epoch=31, loss=0.0799
epoch=32, loss=0.0773
epoch=33, loss=0.0791
epoch=34, loss=0.0785
epoch=35, loss=0.0784
valid [task], Top5Acc: 0.4243, Top10Acc: 0.6971, Acc: 0.0781, MacroF1: 0.1488
valid [full], NDCG@5: 0.7073, HR@5: 0.8728, NDCG@10: 0.7393, HR@10: 0.9759, MRR: 0.6670
valid [sampled], NDCG@5: 0.5320, HR@5: 0.5361, NDCG@10: 0.5479, HR@10: 0.5867, MRR: 0.5550
test [task], Top5Acc: 0.4041, Top10Acc: 0.6574, Acc: 0.0686, MacroF1: 0.0387
test [full], NDCG@5: 0.8079, HR@5: 0.9993, NDCG@10: 0.8081, HR@10: 1.0000, MRR: 0.7426
test [sampled], NDCG@5: 0.3168, HR@5: 0.3330, NDCG@10: 0.3525, HR@10: 0.4452, MRR: 0.3583
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0764
epoch=37, loss=0.0772
epoch=38, loss=0.0776
epoch=39, loss=0.0768
epoch=40, loss=0.0761
valid [task], Top5Acc: 0.4949, Top10Acc: 0.7085, Acc: 0.0733, MacroF1: 0.1308
valid [full], NDCG@5: 0.7043, HR@5: 0.8622, NDCG@10: 0.7406, HR@10: 0.9759, MRR: 0.6692
valid [sampled], NDCG@5: 0.5480, HR@5: 0.5520, NDCG@10: 0.5645, HR@10: 0.6045, MRR: 0.5696
test [task], Top5Acc: 0.5020, Top10Acc: 0.6588, Acc: 0.0267, MacroF1: 0.0174
test [full], NDCG@5: 0.8020, HR@5: 0.9851, NDCG@10: 0.8073, HR@10: 1.0000, MRR: 0.7414
test [sampled], NDCG@5: 0.3036, HR@5: 0.3193, NDCG@10: 0.3476, HR@10: 0.4587, MRR: 0.3471
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0774
epoch=42, loss=0.0778
epoch=43, loss=0.0786
epoch=44, loss=0.0759
epoch=45, loss=0.0788
valid [task], Top5Acc: 0.4811, Top10Acc: 0.7080, Acc: 0.0741, MacroF1: 0.1171
valid [full], NDCG@5: 0.7206, HR@5: 0.8769, NDCG@10: 0.7511, HR@10: 0.9749, MRR: 0.6822
valid [sampled], NDCG@5: 0.5402, HR@5: 0.5482, NDCG@10: 0.5611, HR@10: 0.6145, MRR: 0.5637
test [task], Top5Acc: 0.4891, Top10Acc: 0.6921, Acc: 0.0457, MacroF1: 0.0212
test [full], NDCG@5: 0.8562, HR@5: 0.9895, NDCG@10: 0.8600, HR@10: 1.0000, MRR: 0.8121
test [sampled], NDCG@5: 0.3649, HR@5: 0.4042, NDCG@10: 0.4249, HR@10: 0.5912, MRR: 0.4001
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0752
epoch=47, loss=0.0769
epoch=48, loss=0.0746
epoch=49, loss=0.0759
epoch=50, loss=0.0764
valid [task], Top5Acc: 0.3794, Top10Acc: 0.6782, Acc: 0.1289, MacroF1: 0.1476
valid [full], NDCG@5: 0.7234, HR@5: 0.8755, NDCG@10: 0.7550, HR@10: 0.9771, MRR: 0.6869
valid [sampled], NDCG@5: 0.5519, HR@5: 0.5585, NDCG@10: 0.5719, HR@10: 0.6214, MRR: 0.5747
test [task], Top5Acc: 0.3934, Top10Acc: 0.6332, Acc: 0.0748, MacroF1: 0.0309
test [full], NDCG@5: 0.8041, HR@5: 0.9957, NDCG@10: 0.8056, HR@10: 1.0000, MRR: 0.7401
test [sampled], NDCG@5: 0.3761, HR@5: 0.3959, NDCG@10: 0.4072, HR@10: 0.4930, MRR: 0.4103
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s42/sasrec_last.pth

### `timeaware_dprev_sinusoidal_ml20_s2024`

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_dprev_sinusoidal_ml20_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_prev_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024
epoch=1, loss=0.5362
epoch=2, loss=0.2364
epoch=3, loss=0.1722
epoch=4, loss=0.1381
epoch=5, loss=0.1199
valid [task], Top5Acc: 0.5001, Top10Acc: 0.7518, Acc: 0.1401, MacroF1: 0.1546
valid [full], NDCG@5: 0.6790, HR@5: 0.8077, NDCG@10: 0.7287, HR@10: 0.9631, MRR: 0.6603
valid [sampled], NDCG@5: 0.5556, HR@5: 0.5580, NDCG@10: 0.5638, HR@10: 0.5838, MRR: 0.5728
test [task], Top5Acc: 0.3513, Top10Acc: 0.7495, Acc: 0.0297, MacroF1: 0.0204
test [full], NDCG@5: 0.8138, HR@5: 0.9912, NDCG@10: 0.8169, HR@10: 1.0000, MRR: 0.7557
test [sampled], NDCG@5: 0.1951, HR@5: 0.2311, NDCG@10: 0.2481, HR@10: 0.3967, MRR: 0.2393
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/sasrec_best.pth
epoch=6, loss=0.1124
epoch=7, loss=0.1024
epoch=8, loss=0.0974
epoch=9, loss=0.0930
epoch=10, loss=0.0936
valid [task], Top5Acc: 0.5007, Top10Acc: 0.6917, Acc: 0.1433, MacroF1: 0.1638
valid [full], NDCG@5: 0.6969, HR@5: 0.8378, NDCG@10: 0.7390, HR@10: 0.9692, MRR: 0.6703
valid [sampled], NDCG@5: 0.5489, HR@5: 0.5549, NDCG@10: 0.5652, HR@10: 0.6064, MRR: 0.5686
test [task], Top5Acc: 0.3173, Top10Acc: 0.6434, Acc: 0.0346, MacroF1: 0.0235
test [full], NDCG@5: 0.7553, HR@5: 0.9352, NDCG@10: 0.7763, HR@10: 0.9999, MRR: 0.7014
test [sampled], NDCG@5: 0.1709, HR@5: 0.1971, NDCG@10: 0.2195, HR@10: 0.3504, MRR: 0.2189
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/sasrec_best.pth
epoch=11, loss=0.0891
epoch=12, loss=0.0891
epoch=13, loss=0.0891
epoch=14, loss=0.0869
epoch=15, loss=0.0860
valid [task], Top5Acc: 0.4287, Top10Acc: 0.6399, Acc: 0.1425, MacroF1: 0.1487
valid [full], NDCG@5: 0.6687, HR@5: 0.7549, NDCG@10: 0.7320, HR@10: 0.9504, MRR: 0.6697
valid [sampled], NDCG@5: 0.5574, HR@5: 0.5632, NDCG@10: 0.5736, HR@10: 0.6141, MRR: 0.5755
test [task], Top5Acc: 0.1877, Top10Acc: 0.7738, Acc: 0.0450, MacroF1: 0.0280
test [full], NDCG@5: 0.7727, HR@5: 0.9453, NDCG@10: 0.7897, HR@10: 1.0000, MRR: 0.7209
test [sampled], NDCG@5: 0.2078, HR@5: 0.2358, NDCG@10: 0.2507, HR@10: 0.3699, MRR: 0.2512
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0848
epoch=17, loss=0.0850
epoch=18, loss=0.0828
epoch=19, loss=0.0825
epoch=20, loss=0.0818
valid [task], Top5Acc: 0.4243, Top10Acc: 0.6392, Acc: 0.1432, MacroF1: 0.1520
valid [full], NDCG@5: 0.6709, HR@5: 0.7693, NDCG@10: 0.7355, HR@10: 0.9684, MRR: 0.6676
valid [sampled], NDCG@5: 0.5572, HR@5: 0.5625, NDCG@10: 0.5723, HR@10: 0.6104, MRR: 0.5752
test [task], Top5Acc: 0.3699, Top10Acc: 0.6843, Acc: 0.0395, MacroF1: 0.0264
test [full], NDCG@5: 0.7776, HR@5: 0.9345, NDCG@10: 0.7980, HR@10: 1.0000, MRR: 0.7308
test [sampled], NDCG@5: 0.2218, HR@5: 0.2426, NDCG@10: 0.2692, HR@10: 0.3916, MRR: 0.2691
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0811
epoch=22, loss=0.0824
epoch=23, loss=0.0803
epoch=24, loss=0.0803
epoch=25, loss=0.0808
valid [task], Top5Acc: 0.4832, Top10Acc: 0.6444, Acc: 0.1477, MacroF1: 0.1727
valid [full], NDCG@5: 0.6884, HR@5: 0.8065, NDCG@10: 0.7403, HR@10: 0.9700, MRR: 0.6726
valid [sampled], NDCG@5: 0.5564, HR@5: 0.5607, NDCG@10: 0.5728, HR@10: 0.6125, MRR: 0.5763
test [task], Top5Acc: 0.2862, Top10Acc: 0.7161, Acc: 0.0443, MacroF1: 0.0287
test [full], NDCG@5: 0.7547, HR@5: 0.9337, NDCG@10: 0.7752, HR@10: 1.0000, MRR: 0.7009
test [sampled], NDCG@5: 0.1899, HR@5: 0.2120, NDCG@10: 0.2340, HR@10: 0.3506, MRR: 0.2373
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/sasrec_best.pth
epoch=26, loss=0.0804
epoch=27, loss=0.0803
epoch=28, loss=0.0803
epoch=29, loss=0.0807
epoch=30, loss=0.0762
valid [task], Top5Acc: 0.4806, Top10Acc: 0.6536, Acc: 0.1468, MacroF1: 0.1937
valid [full], NDCG@5: 0.7003, HR@5: 0.8290, NDCG@10: 0.7457, HR@10: 0.9719, MRR: 0.6786
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5678, NDCG@10: 0.5792, HR@10: 0.6205, MRR: 0.5817
test [task], Top5Acc: 0.4129, Top10Acc: 0.6776, Acc: 0.0431, MacroF1: 0.0283
test [full], NDCG@5: 0.7740, HR@5: 0.9214, NDCG@10: 0.7981, HR@10: 1.0000, MRR: 0.7314
test [sampled], NDCG@5: 0.1938, HR@5: 0.2245, NDCG@10: 0.2482, HR@10: 0.3951, MRR: 0.2404
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/sasrec_best.pth
epoch=31, loss=0.0784
epoch=32, loss=0.0798
epoch=33, loss=0.0774
epoch=34, loss=0.0788
epoch=35, loss=0.0776
valid [task], Top5Acc: 0.4444, Top10Acc: 0.6851, Acc: 0.1445, MacroF1: 0.1462
valid [full], NDCG@5: 0.7021, HR@5: 0.8462, NDCG@10: 0.7432, HR@10: 0.9731, MRR: 0.6743
valid [sampled], NDCG@5: 0.5585, HR@5: 0.5625, NDCG@10: 0.5727, HR@10: 0.6073, MRR: 0.5784
test [task], Top5Acc: 0.2020, Top10Acc: 0.7006, Acc: 0.0445, MacroF1: 0.0259
test [full], NDCG@5: 0.7410, HR@5: 0.9251, NDCG@10: 0.7638, HR@10: 1.0000, MRR: 0.6868
test [sampled], NDCG@5: 0.1850, HR@5: 0.2111, NDCG@10: 0.2257, HR@10: 0.3389, MRR: 0.2293
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0773
epoch=37, loss=0.0760
epoch=38, loss=0.0786
epoch=39, loss=0.0769
epoch=40, loss=0.0758
valid [task], Top5Acc: 0.4004, Top10Acc: 0.6741, Acc: 0.1465, MacroF1: 0.1446
valid [full], NDCG@5: 0.6848, HR@5: 0.7977, NDCG@10: 0.7428, HR@10: 0.9742, MRR: 0.6741
valid [sampled], NDCG@5: 0.5601, HR@5: 0.5644, NDCG@10: 0.5738, HR@10: 0.6076, MRR: 0.5793
test [task], Top5Acc: 0.4478, Top10Acc: 0.6917, Acc: 0.0553, MacroF1: 0.0339
test [full], NDCG@5: 0.7708, HR@5: 0.9263, NDCG@10: 0.7932, HR@10: 1.0000, MRR: 0.7245
test [sampled], NDCG@5: 0.2385, HR@5: 0.2564, NDCG@10: 0.2814, HR@10: 0.3921, MRR: 0.2847
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0764
epoch=42, loss=0.0781
epoch=43, loss=0.0775
epoch=44, loss=0.0767
epoch=45, loss=0.0772
valid [task], Top5Acc: 0.4720, Top10Acc: 0.7186, Acc: 0.1366, MacroF1: 0.1426
valid [full], NDCG@5: 0.6807, HR@5: 0.8132, NDCG@10: 0.7325, HR@10: 0.9712, MRR: 0.6620
valid [sampled], NDCG@5: 0.5531, HR@5: 0.5583, NDCG@10: 0.5666, HR@10: 0.6008, MRR: 0.5713
test [task], Top5Acc: 0.5148, Top10Acc: 0.7377, Acc: 0.0415, MacroF1: 0.0299
test [full], NDCG@5: 0.7855, HR@5: 0.9262, NDCG@10: 0.8081, HR@10: 1.0000, MRR: 0.7444
test [sampled], NDCG@5: 0.2537, HR@5: 0.2737, NDCG@10: 0.3020, HR@10: 0.4259, MRR: 0.2994
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0752
epoch=47, loss=0.0763
epoch=48, loss=0.0779
epoch=49, loss=0.0755
epoch=50, loss=0.0754
valid [task], Top5Acc: 0.4455, Top10Acc: 0.6840, Acc: 0.1418, MacroF1: 0.1626
valid [full], NDCG@5: 0.6797, HR@5: 0.7984, NDCG@10: 0.7367, HR@10: 0.9732, MRR: 0.6668
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5610, NDCG@10: 0.5705, HR@10: 0.6090, MRR: 0.5735
test [task], Top5Acc: 0.4817, Top10Acc: 0.7298, Acc: 0.0431, MacroF1: 0.0260
test [full], NDCG@5: 0.7953, HR@5: 0.9242, NDCG@10: 0.8185, HR@10: 1.0000, MRR: 0.7587
test [sampled], NDCG@5: 0.2558, HR@5: 0.2840, NDCG@10: 0.3060, HR@10: 0.4413, MRR: 0.2983
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s2024/sasrec_last.pth

### `timeaware_dprev_sinusoidal_ml20_s7`

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_dprev_sinusoidal_ml20_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_prev_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7
epoch=1, loss=0.5064
epoch=2, loss=0.2315
epoch=3, loss=0.1701
epoch=4, loss=0.1361
epoch=5, loss=0.1178
valid [task], Top5Acc: 0.4869, Top10Acc: 0.6618, Acc: 0.0868, MacroF1: 0.1364
valid [full], NDCG@5: 0.6775, HR@5: 0.8294, NDCG@10: 0.7257, HR@10: 0.9780, MRR: 0.6510
valid [sampled], NDCG@5: 0.5540, HR@5: 0.5548, NDCG@10: 0.5599, HR@10: 0.5735, MRR: 0.5705
test [task], Top5Acc: 0.3438, Top10Acc: 0.7684, Acc: 0.0610, MacroF1: 0.0365
test [full], NDCG@5: 0.7837, HR@5: 0.9644, NDCG@10: 0.7936, HR@10: 0.9945, MRR: 0.7293
test [sampled], NDCG@5: 0.2179, HR@5: 0.2534, NDCG@10: 0.2667, HR@10: 0.4048, MRR: 0.2568
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_best.pth
epoch=6, loss=0.1090
epoch=7, loss=0.1047
epoch=8, loss=0.0995
epoch=9, loss=0.0953
epoch=10, loss=0.0945
valid [task], Top5Acc: 0.4954, Top10Acc: 0.7085, Acc: 0.1759, MacroF1: 0.1678
valid [full], NDCG@5: 0.7002, HR@5: 0.8659, NDCG@10: 0.7287, HR@10: 0.9557, MRR: 0.6618
valid [sampled], NDCG@5: 0.5490, HR@5: 0.5539, NDCG@10: 0.5629, HR@10: 0.5973, MRR: 0.5679
test [task], Top5Acc: 0.3413, Top10Acc: 0.7902, Acc: 0.0333, MacroF1: 0.0185
test [full], NDCG@5: 0.7791, HR@5: 0.9931, NDCG@10: 0.7814, HR@10: 1.0000, MRR: 0.7075
test [sampled], NDCG@5: 0.1994, HR@5: 0.2248, NDCG@10: 0.2526, HR@10: 0.3925, MRR: 0.2473
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_best.pth
epoch=11, loss=0.0932
epoch=12, loss=0.0898
epoch=13, loss=0.0874
epoch=14, loss=0.0865
epoch=15, loss=0.0870
valid [task], Top5Acc: 0.4999, Top10Acc: 0.6773, Acc: 0.1873, MacroF1: 0.1877
valid [full], NDCG@5: 0.6922, HR@5: 0.8378, NDCG@10: 0.7231, HR@10: 0.9373, MRR: 0.6624
valid [sampled], NDCG@5: 0.5593, HR@5: 0.5651, NDCG@10: 0.5726, HR@10: 0.6065, MRR: 0.5758
test [task], Top5Acc: 0.4300, Top10Acc: 0.7602, Acc: 0.0345, MacroF1: 0.0246
test [full], NDCG@5: 0.8582, HR@5: 0.9952, NDCG@10: 0.8599, HR@10: 1.0000, MRR: 0.8131
test [sampled], NDCG@5: 0.2381, HR@5: 0.2927, NDCG@10: 0.3145, HR@10: 0.5295, MRR: 0.2784
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0869
epoch=17, loss=0.0844
epoch=18, loss=0.0844
epoch=19, loss=0.0827
epoch=20, loss=0.0807
valid [task], Top5Acc: 0.4942, Top10Acc: 0.6773, Acc: 0.2332, MacroF1: 0.2175
valid [full], NDCG@5: 0.6815, HR@5: 0.8222, NDCG@10: 0.7299, HR@10: 0.9751, MRR: 0.6577
valid [sampled], NDCG@5: 0.5534, HR@5: 0.5606, NDCG@10: 0.5675, HR@10: 0.6048, MRR: 0.5699
test [task], Top5Acc: 0.4762, Top10Acc: 0.7075, Acc: 0.0368, MacroF1: 0.0818
test [full], NDCG@5: 0.8981, HR@5: 0.9969, NDCG@10: 0.8992, HR@10: 1.0000, MRR: 0.8652
test [sampled], NDCG@5: 0.3299, HR@5: 0.3819, NDCG@10: 0.3963, HR@10: 0.5882, MRR: 0.3632
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_best.pth
epoch=21, loss=0.0810
epoch=22, loss=0.0808
epoch=23, loss=0.0795
epoch=24, loss=0.0816
epoch=25, loss=0.0807
valid [task], Top5Acc: 0.4960, Top10Acc: 0.7079, Acc: 0.2331, MacroF1: 0.2414
valid [full], NDCG@5: 0.7037, HR@5: 0.8476, NDCG@10: 0.7373, HR@10: 0.9550, MRR: 0.6740
valid [sampled], NDCG@5: 0.5702, HR@5: 0.5771, NDCG@10: 0.5833, HR@10: 0.6183, MRR: 0.5866
test [task], Top5Acc: 0.4738, Top10Acc: 0.6695, Acc: 0.0759, MacroF1: 0.0994
test [full], NDCG@5: 0.8901, HR@5: 0.9974, NDCG@10: 0.8910, HR@10: 1.0000, MRR: 0.8537
test [sampled], NDCG@5: 0.3930, HR@5: 0.4252, NDCG@10: 0.4433, HR@10: 0.5822, MRR: 0.4269
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_best.pth
epoch=26, loss=0.0788
epoch=27, loss=0.0794
epoch=28, loss=0.0782
epoch=29, loss=0.0788
epoch=30, loss=0.0774
valid [task], Top5Acc: 0.4954, Top10Acc: 0.7231, Acc: 0.1785, MacroF1: 0.1877
valid [full], NDCG@5: 0.6979, HR@5: 0.8259, NDCG@10: 0.7358, HR@10: 0.9453, MRR: 0.6760
valid [sampled], NDCG@5: 0.5765, HR@5: 0.5823, NDCG@10: 0.5883, HR@10: 0.6191, MRR: 0.5927
test [task], Top5Acc: 0.4797, Top10Acc: 0.6636, Acc: 0.0738, MacroF1: 0.0381
test [full], NDCG@5: 0.8884, HR@5: 0.9880, NDCG@10: 0.8926, HR@10: 1.0000, MRR: 0.8572
test [sampled], NDCG@5: 0.5429, HR@5: 0.5558, NDCG@10: 0.5674, HR@10: 0.6328, MRR: 0.5672
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0796
epoch=32, loss=0.0767
epoch=33, loss=0.0782
epoch=34, loss=0.0770
epoch=35, loss=0.0772
valid [task], Top5Acc: 0.4908, Top10Acc: 0.7393, Acc: 0.0946, MacroF1: 0.1386
valid [full], NDCG@5: 0.6899, HR@5: 0.8455, NDCG@10: 0.7310, HR@10: 0.9725, MRR: 0.6589
valid [sampled], NDCG@5: 0.5499, HR@5: 0.5546, NDCG@10: 0.5631, HR@10: 0.5959, MRR: 0.5683
test [task], Top5Acc: 0.4888, Top10Acc: 0.6995, Acc: 0.0374, MacroF1: 0.0312
test [full], NDCG@5: 0.8931, HR@5: 0.9976, NDCG@10: 0.8939, HR@10: 1.0000, MRR: 0.8584
test [sampled], NDCG@5: 0.5110, HR@5: 0.5287, NDCG@10: 0.5415, HR@10: 0.6248, MRR: 0.5371
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0752
epoch=37, loss=0.0784
epoch=38, loss=0.0777
epoch=39, loss=0.0757
epoch=40, loss=0.0766
valid [task], Top5Acc: 0.4996, Top10Acc: 0.7793, Acc: 0.1775, MacroF1: 0.2121
valid [full], NDCG@5: 0.7047, HR@5: 0.8493, NDCG@10: 0.7401, HR@10: 0.9644, MRR: 0.6738
valid [sampled], NDCG@5: 0.5587, HR@5: 0.5649, NDCG@10: 0.5731, HR@10: 0.6099, MRR: 0.5771
test [task], Top5Acc: 0.5168, Top10Acc: 0.7401, Acc: 0.0366, MacroF1: 0.0269
test [full], NDCG@5: 0.9059, HR@5: 0.9986, NDCG@10: 0.9063, HR@10: 1.0000, MRR: 0.8745
test [sampled], NDCG@5: 0.5990, HR@5: 0.6055, NDCG@10: 0.6138, HR@10: 0.6522, MRR: 0.6213
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_best.pth
epoch=41, loss=0.0785
epoch=42, loss=0.0754
epoch=43, loss=0.0767
epoch=44, loss=0.0765
epoch=45, loss=0.0762
valid [task], Top5Acc: 0.5015, Top10Acc: 0.7368, Acc: 0.1664, MacroF1: 0.1737
valid [full], NDCG@5: 0.7124, HR@5: 0.8735, NDCG@10: 0.7440, HR@10: 0.9745, MRR: 0.6750
valid [sampled], NDCG@5: 0.5688, HR@5: 0.5738, NDCG@10: 0.5813, HR@10: 0.6132, MRR: 0.5867
test [task], Top5Acc: 0.5095, Top10Acc: 0.6862, Acc: 0.0372, MacroF1: 0.0298
test [full], NDCG@5: 0.8256, HR@5: 0.9930, NDCG@10: 0.8280, HR@10: 1.0000, MRR: 0.7695
test [sampled], NDCG@5: 0.4438, HR@5: 0.4776, NDCG@10: 0.4919, HR@10: 0.6274, MRR: 0.4721
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_best.pth
epoch=46, loss=0.0756
epoch=47, loss=0.0748
epoch=48, loss=0.0741
epoch=49, loss=0.0768
epoch=50, loss=0.0750
valid [task], Top5Acc: 0.4996, Top10Acc: 0.7817, Acc: 0.1758, MacroF1: 0.2006
valid [full], NDCG@5: 0.7173, HR@5: 0.8630, NDCG@10: 0.7516, HR@10: 0.9744, MRR: 0.6850
valid [sampled], NDCG@5: 0.5732, HR@5: 0.5791, NDCG@10: 0.5875, HR@10: 0.6240, MRR: 0.5919
test [task], Top5Acc: 0.4781, Top10Acc: 0.7223, Acc: 0.0306, MacroF1: 0.0210
test [full], NDCG@5: 0.8181, HR@5: 0.9971, NDCG@10: 0.8191, HR@10: 1.0000, MRR: 0.7568
test [sampled], NDCG@5: 0.4092, HR@5: 0.4500, NDCG@10: 0.4618, HR@10: 0.6136, MRR: 0.4387
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml20_s7/sasrec_last.pth

## Train `anchor_ml20 + Additive_sinusoidal + delta_start_seconds`

### `timeaware_dstart_sinusoidal_ml20_s42`

In [11]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_sinusoidal_ml20_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42
epoch=1, loss=0.5417
epoch=2, loss=0.2377
epoch=3, loss=0.1699
epoch=4, loss=0.1383
epoch=5, loss=0.1200
valid [task], Top5Acc: 0.4897, Top10Acc: 0.6894, Acc: 0.1390, MacroF1: 0.1778
valid [full], NDCG@5: 0.6542, HR@5: 0.7720, NDCG@10: 0.7205, HR@10: 0.9790, MRR: 0.6452
valid [sampled], NDCG@5: 0.5550, HR@5: 0.5562, NDCG@10: 0.5608, HR@10: 0.5747, MRR: 0.5708
test [task], Top5Acc: 0.0767, Top10Acc: 0.6685, Acc: 0.0320, MacroF1: 0.0213
test [full], NDCG@5: 0.5611, HR@5: 0.8458, NDCG@10: 0.6110, HR@10: 0.9999, MRR: 0.4884
test [sampled], NDCG@5: 0.1554, HR@5: 0.1580, NDCG@10: 0.1680, HR@10: 0.1982, MRR: 0.1951
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_best.pth
epoch=6, loss=0.1120
epoch=7, loss=0.1045
epoch=8, loss=0.1006
epoch=9, loss=0.0982
epoch=10, loss=0.0949
valid [task], Top5Acc: 0.4803, Top10Acc: 0.7161, Acc: 0.1456, MacroF1: 0.1489
valid [full], NDCG@5: 0.6970, HR@5: 0.8514, NDCG@10: 0.7374, HR@10: 0.9760, MRR: 0.6662
valid [sampled], NDCG@5: 0.5593, HR@5: 0.5628, NDCG@10: 0.5701, HR@10: 0.5969, MRR: 0.5776
test [task], Top5Acc: 0.3928, Top10Acc: 0.6914, Acc: 0.0363, MacroF1: 0.0277
test [full], NDCG@5: 0.8342, HR@5: 0.9607, NDCG@10: 0.8477, HR@10: 1.0000, MRR: 0.7974
test [sampled], NDCG@5: 0.2418, HR@5: 0.2985, NDCG@10: 0.3193, HR@10: 0.5392, MRR: 0.2791
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_best.pth
epoch=11, loss=0.0925
epoch=12, loss=0.0901
epoch=13, loss=0.0899
epoch=14, loss=0.0885
epoch=15, loss=0.0877
valid [task], Top5Acc: 0.3990, Top10Acc: 0.7017, Acc: 0.1348, MacroF1: 0.1722
valid [full], NDCG@5: 0.6911, HR@5: 0.8638, NDCG@10: 0.7255, HR@10: 0.9750, MRR: 0.6508
valid [sampled], NDCG@5: 0.5317, HR@5: 0.5340, NDCG@10: 0.5419, HR@10: 0.5666, MRR: 0.5517
test [task], Top5Acc: 0.4324, Top10Acc: 0.6886, Acc: 0.0268, MacroF1: 0.0224
test [full], NDCG@5: 0.7921, HR@5: 0.9654, NDCG@10: 0.8033, HR@10: 0.9985, MRR: 0.7382
test [sampled], NDCG@5: 0.2417, HR@5: 0.2634, NDCG@10: 0.2835, HR@10: 0.3948, MRR: 0.2856
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0862
epoch=17, loss=0.0857
epoch=18, loss=0.0824
epoch=19, loss=0.0850
epoch=20, loss=0.0840
valid [task], Top5Acc: 0.4025, Top10Acc: 0.7334, Acc: 0.1346, MacroF1: 0.1878
valid [full], NDCG@5: 0.7044, HR@5: 0.8619, NDCG@10: 0.7413, HR@10: 0.9765, MRR: 0.6702
valid [sampled], NDCG@5: 0.5539, HR@5: 0.5589, NDCG@10: 0.5687, HR@10: 0.6058, MRR: 0.5739
test [task], Top5Acc: 0.4892, Top10Acc: 0.6489, Acc: 0.0244, MacroF1: 0.0211
test [full], NDCG@5: 0.8885, HR@5: 0.9694, NDCG@10: 0.8986, HR@10: 1.0000, MRR: 0.8650
test [sampled], NDCG@5: 0.3349, HR@5: 0.3862, NDCG@10: 0.3992, HR@10: 0.5860, MRR: 0.3668
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_best.pth
epoch=21, loss=0.0801
epoch=22, loss=0.0816
epoch=23, loss=0.0807
epoch=24, loss=0.0812
epoch=25, loss=0.0783
valid [task], Top5Acc: 0.4524, Top10Acc: 0.7424, Acc: 0.1434, MacroF1: 0.1780
valid [full], NDCG@5: 0.7077, HR@5: 0.8616, NDCG@10: 0.7441, HR@10: 0.9777, MRR: 0.6736
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5591, NDCG@10: 0.5691, HR@10: 0.6029, MRR: 0.5758
test [task], Top5Acc: 0.3386, Top10Acc: 0.7000, Acc: 0.0358, MacroF1: 0.0285
test [full], NDCG@5: 0.7889, HR@5: 0.9965, NDCG@10: 0.7901, HR@10: 1.0000, MRR: 0.7221
test [sampled], NDCG@5: 0.3704, HR@5: 0.3727, NDCG@10: 0.3804, HR@10: 0.4047, MRR: 0.4043
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_best.pth
epoch=26, loss=0.0792
epoch=27, loss=0.0790
epoch=28, loss=0.0805
epoch=29, loss=0.0803
epoch=30, loss=0.0789
valid [task], Top5Acc: 0.4945, Top10Acc: 0.7059, Acc: 0.1344, MacroF1: 0.1370
valid [full], NDCG@5: 0.7101, HR@5: 0.8530, NDCG@10: 0.7489, HR@10: 0.9766, MRR: 0.6802
valid [sampled], NDCG@5: 0.5600, HR@5: 0.5639, NDCG@10: 0.5750, HR@10: 0.6114, MRR: 0.5812
test [task], Top5Acc: 0.5625, Top10Acc: 0.6951, Acc: 0.0299, MacroF1: 0.0302
test [full], NDCG@5: 0.9175, HR@5: 0.9989, NDCG@10: 0.9178, HR@10: 0.9999, MRR: 0.8908
test [sampled], NDCG@5: 0.3731, HR@5: 0.4158, NDCG@10: 0.4304, HR@10: 0.5944, MRR: 0.4056
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_best.pth
epoch=31, loss=0.0811
epoch=32, loss=0.0781
epoch=33, loss=0.0797
epoch=34, loss=0.0794
epoch=35, loss=0.0788
valid [task], Top5Acc: 0.4988, Top10Acc: 0.7136, Acc: 0.1313, MacroF1: 0.1642
valid [full], NDCG@5: 0.7136, HR@5: 0.8744, NDCG@10: 0.7452, HR@10: 0.9760, MRR: 0.6746
valid [sampled], NDCG@5: 0.5407, HR@5: 0.5452, NDCG@10: 0.5583, HR@10: 0.6009, MRR: 0.5637
test [task], Top5Acc: 0.4413, Top10Acc: 0.6781, Acc: 0.0649, MacroF1: 0.0335
test [full], NDCG@5: 0.8254, HR@5: 0.9717, NDCG@10: 0.8354, HR@10: 1.0000, MRR: 0.7802
test [sampled], NDCG@5: 0.3716, HR@5: 0.3833, NDCG@10: 0.3991, HR@10: 0.4701, MRR: 0.4085
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0770
epoch=37, loss=0.0782
epoch=38, loss=0.0777
epoch=39, loss=0.0769
epoch=40, loss=0.0775
valid [task], Top5Acc: 0.4901, Top10Acc: 0.7154, Acc: 0.1283, MacroF1: 0.1530
valid [full], NDCG@5: 0.7162, HR@5: 0.8701, NDCG@10: 0.7495, HR@10: 0.9759, MRR: 0.6806
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5578, NDCG@10: 0.5702, HR@10: 0.6074, MRR: 0.5768
test [task], Top5Acc: 0.4051, Top10Acc: 0.7177, Acc: 0.0224, MacroF1: 0.0153
test [full], NDCG@5: 0.7836, HR@5: 0.9661, NDCG@10: 0.7956, HR@10: 1.0000, MRR: 0.7275
test [sampled], NDCG@5: 0.3388, HR@5: 0.3425, NDCG@10: 0.3557, HR@10: 0.3965, MRR: 0.3774
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_best.pth
epoch=41, loss=0.0772
epoch=42, loss=0.0784
epoch=43, loss=0.0790
epoch=44, loss=0.0771
epoch=45, loss=0.0788
valid [task], Top5Acc: 0.5040, Top10Acc: 0.7431, Acc: 0.1251, MacroF1: 0.1515
valid [full], NDCG@5: 0.7233, HR@5: 0.8685, NDCG@10: 0.7570, HR@10: 0.9755, MRR: 0.6905
valid [sampled], NDCG@5: 0.5628, HR@5: 0.5693, NDCG@10: 0.5824, HR@10: 0.6312, MRR: 0.5846
test [task], Top5Acc: 0.3588, Top10Acc: 0.7262, Acc: 0.0483, MacroF1: 0.0219
test [full], NDCG@5: 0.7892, HR@5: 0.9749, NDCG@10: 0.7981, HR@10: 1.0000, MRR: 0.7310
test [sampled], NDCG@5: 0.3545, HR@5: 0.3605, NDCG@10: 0.3702, HR@10: 0.4104, MRR: 0.3911
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_best.pth
epoch=46, loss=0.0759
epoch=47, loss=0.0776
epoch=48, loss=0.0756
epoch=49, loss=0.0762
epoch=50, loss=0.0764
valid [task], Top5Acc: 0.4245, Top10Acc: 0.6897, Acc: 0.1264, MacroF1: 0.1384
valid [full], NDCG@5: 0.7040, HR@5: 0.8372, NDCG@10: 0.7491, HR@10: 0.9776, MRR: 0.6803
valid [sampled], NDCG@5: 0.5572, HR@5: 0.5634, NDCG@10: 0.5743, HR@10: 0.6173, MRR: 0.5775
test [task], Top5Acc: 0.3295, Top10Acc: 0.6910, Acc: 0.1166, MacroF1: 0.0296
test [full], NDCG@5: 0.7924, HR@5: 0.9692, NDCG@10: 0.8032, HR@10: 1.0000, MRR: 0.7379
test [sampled], NDCG@5: 0.3571, HR@5: 0.3627, NDCG@10: 0.3715, HR@10: 0.4087, MRR: 0.3932
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s42/sasrec_last.pth

### `timeaware_dstart_sinusoidal_ml20_s2024`

In [12]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_sinusoidal_ml20_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024
epoch=1, loss=0.5341
epoch=2, loss=0.2353
epoch=3, loss=0.1724
epoch=4, loss=0.1382
epoch=5, loss=0.1198
valid [task], Top5Acc: 0.4919, Top10Acc: 0.6684, Acc: 0.1416, MacroF1: 0.1722
valid [full], NDCG@5: 0.6747, HR@5: 0.8291, NDCG@10: 0.7279, HR@10: 0.9881, MRR: 0.6496
valid [sampled], NDCG@5: 0.5460, HR@5: 0.5495, NDCG@10: 0.5542, HR@10: 0.5751, MRR: 0.5625
test [task], Top5Acc: 0.3301, Top10Acc: 0.7159, Acc: 0.0286, MacroF1: 0.0221
test [full], NDCG@5: 0.8179, HR@5: 0.9953, NDCG@10: 0.8196, HR@10: 1.0000, MRR: 0.7597
test [sampled], NDCG@5: 0.1862, HR@5: 0.2265, NDCG@10: 0.2458, HR@10: 0.4126, MRR: 0.2302
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/sasrec_best.pth
epoch=6, loss=0.1127
epoch=7, loss=0.1027
epoch=8, loss=0.0990
epoch=9, loss=0.0950
epoch=10, loss=0.0949
valid [task], Top5Acc: 0.4042, Top10Acc: 0.6435, Acc: 0.1397, MacroF1: 0.1794
valid [full], NDCG@5: 0.6503, HR@5: 0.7727, NDCG@10: 0.7102, HR@10: 0.9576, MRR: 0.6389
valid [sampled], NDCG@5: 0.5310, HR@5: 0.5367, NDCG@10: 0.5436, HR@10: 0.5764, MRR: 0.5476
test [task], Top5Acc: 0.3121, Top10Acc: 0.6572, Acc: 0.0290, MacroF1: 0.0211
test [full], NDCG@5: 0.7513, HR@5: 0.9763, NDCG@10: 0.7594, HR@10: 0.9999, MRR: 0.6780
test [sampled], NDCG@5: 0.1657, HR@5: 0.1842, NDCG@10: 0.2136, HR@10: 0.3361, MRR: 0.2170
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0902
epoch=12, loss=0.0902
epoch=13, loss=0.0899
epoch=14, loss=0.0885
epoch=15, loss=0.0872
valid [task], Top5Acc: 0.4026, Top10Acc: 0.5582, Acc: 0.1406, MacroF1: 0.1365
valid [full], NDCG@5: 0.6729, HR@5: 0.7970, NDCG@10: 0.7269, HR@10: 0.9665, MRR: 0.6567
valid [sampled], NDCG@5: 0.5418, HR@5: 0.5488, NDCG@10: 0.5577, HR@10: 0.5986, MRR: 0.5598
test [task], Top5Acc: 0.2550, Top10Acc: 0.6580, Acc: 0.0333, MacroF1: 0.0234
test [full], NDCG@5: 0.7569, HR@5: 0.9668, NDCG@10: 0.7685, HR@10: 1.0000, MRR: 0.6915
test [sampled], NDCG@5: 0.1904, HR@5: 0.2128, NDCG@10: 0.2309, HR@10: 0.3400, MRR: 0.2361
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0862
epoch=17, loss=0.0856
epoch=18, loss=0.0843
epoch=19, loss=0.0841
epoch=20, loss=0.0828
valid [task], Top5Acc: 0.4179, Top10Acc: 0.6169, Acc: 0.1392, MacroF1: 0.1309
valid [full], NDCG@5: 0.6573, HR@5: 0.7573, NDCG@10: 0.7218, HR@10: 0.9552, MRR: 0.6553
valid [sampled], NDCG@5: 0.5534, HR@5: 0.5595, NDCG@10: 0.5676, HR@10: 0.6043, MRR: 0.5695
test [task], Top5Acc: 0.4783, Top10Acc: 0.6272, Acc: 0.0371, MacroF1: 0.0268
test [full], NDCG@5: 0.8198, HR@5: 0.9226, NDCG@10: 0.8452, HR@10: 1.0000, MRR: 0.7947
test [sampled], NDCG@5: 0.2186, HR@5: 0.2623, NDCG@10: 0.2893, HR@10: 0.4815, MRR: 0.2617
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0819
epoch=22, loss=0.0835
epoch=23, loss=0.0814
epoch=24, loss=0.0814
epoch=25, loss=0.0821
valid [task], Top5Acc: 0.4249, Top10Acc: 0.6163, Acc: 0.1396, MacroF1: 0.1628
valid [full], NDCG@5: 0.6571, HR@5: 0.7603, NDCG@10: 0.7186, HR@10: 0.9524, MRR: 0.6523
valid [sampled], NDCG@5: 0.5515, HR@5: 0.5572, NDCG@10: 0.5646, HR@10: 0.5982, MRR: 0.5675
test [task], Top5Acc: 0.3898, Top10Acc: 0.6741, Acc: 0.0553, MacroF1: 0.0326
test [full], NDCG@5: 0.7861, HR@5: 0.9450, NDCG@10: 0.8043, HR@10: 0.9999, MRR: 0.7393
test [sampled], NDCG@5: 0.2741, HR@5: 0.2987, NDCG@10: 0.3141, HR@10: 0.4239, MRR: 0.3143
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0809
epoch=27, loss=0.0811
epoch=28, loss=0.0809
epoch=29, loss=0.0816
epoch=30, loss=0.0771
valid [task], Top5Acc: 0.4038, Top10Acc: 0.6277, Acc: 0.1358, MacroF1: 0.1492
valid [full], NDCG@5: 0.6662, HR@5: 0.7630, NDCG@10: 0.7315, HR@10: 0.9646, MRR: 0.6639
valid [sampled], NDCG@5: 0.5545, HR@5: 0.5604, NDCG@10: 0.5700, HR@10: 0.6086, MRR: 0.5721
test [task], Top5Acc: 0.4389, Top10Acc: 0.6382, Acc: 0.0351, MacroF1: 0.0283
test [full], NDCG@5: 0.7786, HR@5: 0.9393, NDCG@10: 0.7989, HR@10: 0.9999, MRR: 0.7317
test [sampled], NDCG@5: 0.2491, HR@5: 0.2734, NDCG@10: 0.2970, HR@10: 0.4242, MRR: 0.2927
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/sasrec_best.pth
epoch=31, loss=0.0794
epoch=32, loss=0.0803
epoch=33, loss=0.0783
epoch=34, loss=0.0798
epoch=35, loss=0.0784
valid [task], Top5Acc: 0.4090, Top10Acc: 0.6013, Acc: 0.1424, MacroF1: 0.1746
valid [full], NDCG@5: 0.6844, HR@5: 0.8181, NDCG@10: 0.7295, HR@10: 0.9598, MRR: 0.6616
valid [sampled], NDCG@5: 0.5413, HR@5: 0.5467, NDCG@10: 0.5573, HR@10: 0.5974, MRR: 0.5608
test [task], Top5Acc: 0.5540, Top10Acc: 0.6266, Acc: 0.0640, MacroF1: 0.0338
test [full], NDCG@5: 0.8133, HR@5: 0.9479, NDCG@10: 0.8303, HR@10: 1.0000, MRR: 0.7735
test [sampled], NDCG@5: 0.3174, HR@5: 0.3382, NDCG@10: 0.3555, HR@10: 0.4577, MRR: 0.3567
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0781
epoch=37, loss=0.0769
epoch=38, loss=0.0790
epoch=39, loss=0.0777
epoch=40, loss=0.0763
valid [task], Top5Acc: 0.3770, Top10Acc: 0.5984, Acc: 0.1403, MacroF1: 0.1544
valid [full], NDCG@5: 0.6738, HR@5: 0.8137, NDCG@10: 0.7202, HR@10: 0.9579, MRR: 0.6503
valid [sampled], NDCG@5: 0.5297, HR@5: 0.5372, NDCG@10: 0.5425, HR@10: 0.5778, MRR: 0.5475
test [task], Top5Acc: 0.5125, Top10Acc: 0.6309, Acc: 0.0440, MacroF1: 0.0276
test [full], NDCG@5: 0.8040, HR@5: 0.9428, NDCG@10: 0.8220, HR@10: 0.9999, MRR: 0.7625
test [sampled], NDCG@5: 0.3216, HR@5: 0.3393, NDCG@10: 0.3569, HR@10: 0.4505, MRR: 0.3611
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0777
epoch=42, loss=0.0789
epoch=43, loss=0.0784
epoch=44, loss=0.0774
epoch=45, loss=0.0779
valid [task], Top5Acc: 0.3844, Top10Acc: 0.6230, Acc: 0.1342, MacroF1: 0.1398
valid [full], NDCG@5: 0.6720, HR@5: 0.8306, NDCG@10: 0.7193, HR@10: 0.9758, MRR: 0.6417
valid [sampled], NDCG@5: 0.5080, HR@5: 0.5149, NDCG@10: 0.5246, HR@10: 0.5669, MRR: 0.5289
test [task], Top5Acc: 0.4719, Top10Acc: 0.6340, Acc: 0.0397, MacroF1: 0.0296
test [full], NDCG@5: 0.8044, HR@5: 0.9375, NDCG@10: 0.8244, HR@10: 0.9999, MRR: 0.7663
test [sampled], NDCG@5: 0.3291, HR@5: 0.3472, NDCG@10: 0.3665, HR@10: 0.4649, MRR: 0.3676
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0757
epoch=47, loss=0.0763
epoch=48, loss=0.0786
epoch=49, loss=0.0755
epoch=50, loss=0.0761
valid [task], Top5Acc: 0.3955, Top10Acc: 0.5852, Acc: 0.1385, MacroF1: 0.1512
valid [full], NDCG@5: 0.6865, HR@5: 0.8484, NDCG@10: 0.7264, HR@10: 0.9750, MRR: 0.6515
valid [sampled], NDCG@5: 0.5203, HR@5: 0.5256, NDCG@10: 0.5348, HR@10: 0.5712, MRR: 0.5409
test [task], Top5Acc: 0.4850, Top10Acc: 0.6469, Acc: 0.1181, MacroF1: 0.0622
test [full], NDCG@5: 0.8128, HR@5: 0.9500, NDCG@10: 0.8296, HR@10: 1.0000, MRR: 0.7726
test [sampled], NDCG@5: 0.3335, HR@5: 0.3491, NDCG@10: 0.3648, HR@10: 0.4477, MRR: 0.3722
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s2024/sasrec_last.pth

### `timeaware_dstart_sinusoidal_ml20_s7`

In [13]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_sinusoidal_ml20_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7
epoch=1, loss=0.5013
epoch=2, loss=0.2301
epoch=3, loss=0.1704
epoch=4, loss=0.1365
epoch=5, loss=0.1181
valid [task], Top5Acc: 0.3909, Top10Acc: 0.5842, Acc: 0.1318, MacroF1: 0.1598
valid [full], NDCG@5: 0.6469, HR@5: 0.7665, NDCG@10: 0.7160, HR@10: 0.9756, MRR: 0.6403
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5552, NDCG@10: 0.5576, HR@10: 0.5629, MRR: 0.5698
test [task], Top5Acc: 0.3368, Top10Acc: 0.6935, Acc: 0.0569, MacroF1: 0.0345
test [full], NDCG@5: 0.6839, HR@5: 0.8908, NDCG@10: 0.7138, HR@10: 0.9801, MRR: 0.6293
test [sampled], NDCG@5: 0.1979, HR@5: 0.2125, NDCG@10: 0.2290, HR@10: 0.3102, MRR: 0.2392
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/sasrec_best.pth
epoch=6, loss=0.1083
epoch=7, loss=0.1049
epoch=8, loss=0.0999
epoch=9, loss=0.0956
epoch=10, loss=0.0943
valid [task], Top5Acc: 0.3991, Top10Acc: 0.6736, Acc: 0.0775, MacroF1: 0.1027
valid [full], NDCG@5: 0.6967, HR@5: 0.8645, NDCG@10: 0.7257, HR@10: 0.9555, MRR: 0.6571
valid [sampled], NDCG@5: 0.5332, HR@5: 0.5379, NDCG@10: 0.5473, HR@10: 0.5822, MRR: 0.5536
test [task], Top5Acc: 0.3963, Top10Acc: 0.7177, Acc: 0.0253, MacroF1: 0.0173
test [full], NDCG@5: 0.7109, HR@5: 0.9894, NDCG@10: 0.7144, HR@10: 1.0000, MRR: 0.6171
test [sampled], NDCG@5: 0.1430, HR@5: 0.1481, NDCG@10: 0.1855, HR@10: 0.2846, MRR: 0.1988
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/sasrec_best.pth
epoch=11, loss=0.0929
epoch=12, loss=0.0912
epoch=13, loss=0.0880
epoch=14, loss=0.0873
epoch=15, loss=0.0877
valid [task], Top5Acc: 0.4037, Top10Acc: 0.5861, Acc: 0.0673, MacroF1: 0.0930
valid [full], NDCG@5: 0.6980, HR@5: 0.8572, NDCG@10: 0.7272, HR@10: 0.9524, MRR: 0.6619
valid [sampled], NDCG@5: 0.5588, HR@5: 0.5616, NDCG@10: 0.5681, HR@10: 0.5910, MRR: 0.5760
test [task], Top5Acc: 0.4744, Top10Acc: 0.6902, Acc: 0.0307, MacroF1: 0.0252
test [full], NDCG@5: 0.7187, HR@5: 0.9553, NDCG@10: 0.7343, HR@10: 1.0000, MRR: 0.6440
test [sampled], NDCG@5: 0.1480, HR@5: 0.1536, NDCG@10: 0.1920, HR@10: 0.2954, MRR: 0.2046
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/sasrec_best.pth
epoch=16, loss=0.0877
epoch=17, loss=0.0843
epoch=18, loss=0.0854
epoch=19, loss=0.0833
epoch=20, loss=0.0815
valid [task], Top5Acc: 0.3863, Top10Acc: 0.5735, Acc: 0.1344, MacroF1: 0.1602
valid [full], NDCG@5: 0.6929, HR@5: 0.8366, NDCG@10: 0.7222, HR@10: 0.9317, MRR: 0.6628
valid [sampled], NDCG@5: 0.5533, HR@5: 0.5599, NDCG@10: 0.5679, HR@10: 0.6058, MRR: 0.5706
test [task], Top5Acc: 0.2640, Top10Acc: 0.6447, Acc: 0.0375, MacroF1: 0.0288
test [full], NDCG@5: 0.7053, HR@5: 0.9358, NDCG@10: 0.7273, HR@10: 1.0000, MRR: 0.6367
test [sampled], NDCG@5: 0.1819, HR@5: 0.2015, NDCG@10: 0.2187, HR@10: 0.3178, MRR: 0.2271
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0822
epoch=22, loss=0.0808
epoch=23, loss=0.0804
epoch=24, loss=0.0820
epoch=25, loss=0.0818
valid [task], Top5Acc: 0.3902, Top10Acc: 0.5767, Acc: 0.1050, MacroF1: 0.1733
valid [full], NDCG@5: 0.6649, HR@5: 0.7975, NDCG@10: 0.7007, HR@10: 0.9127, MRR: 0.6424
valid [sampled], NDCG@5: 0.5386, HR@5: 0.5447, NDCG@10: 0.5503, HR@10: 0.5816, MRR: 0.5544
test [task], Top5Acc: 0.4753, Top10Acc: 0.6561, Acc: 0.0899, MacroF1: 0.0551
test [full], NDCG@5: 0.8021, HR@5: 0.9347, NDCG@10: 0.8241, HR@10: 1.0000, MRR: 0.7656
test [sampled], NDCG@5: 0.3422, HR@5: 0.3576, NDCG@10: 0.3751, HR@10: 0.4608, MRR: 0.3799
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0793
epoch=27, loss=0.0801
epoch=28, loss=0.0786
epoch=29, loss=0.0792
epoch=30, loss=0.0776
valid [task], Top5Acc: 0.4411, Top10Acc: 0.6226, Acc: 0.1109, MacroF1: 0.1584
valid [full], NDCG@5: 0.6723, HR@5: 0.7944, NDCG@10: 0.7057, HR@10: 0.9008, MRR: 0.6534
valid [sampled], NDCG@5: 0.5525, HR@5: 0.5585, NDCG@10: 0.5662, HR@10: 0.6015, MRR: 0.5686
test [task], Top5Acc: 0.2918, Top10Acc: 0.6552, Acc: 0.0818, MacroF1: 0.0485
test [full], NDCG@5: 0.7614, HR@5: 0.9317, NDCG@10: 0.7841, HR@10: 1.0000, MRR: 0.7134
test [sampled], NDCG@5: 0.3217, HR@5: 0.3336, NDCG@10: 0.3445, HR@10: 0.4052, MRR: 0.3582
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0808
epoch=32, loss=0.0772
epoch=33, loss=0.0783
epoch=34, loss=0.0770
epoch=35, loss=0.0787
valid [task], Top5Acc: 0.3910, Top10Acc: 0.6287, Acc: 0.1149, MacroF1: 0.1676
valid [full], NDCG@5: 0.6915, HR@5: 0.8452, NDCG@10: 0.7282, HR@10: 0.9634, MRR: 0.6591
valid [sampled], NDCG@5: 0.5458, HR@5: 0.5512, NDCG@10: 0.5611, HR@10: 0.5993, MRR: 0.5645
test [task], Top5Acc: 0.4821, Top10Acc: 0.6729, Acc: 0.0850, MacroF1: 0.0463
test [full], NDCG@5: 0.8821, HR@5: 0.9497, NDCG@10: 0.8992, HR@10: 1.0000, MRR: 0.8670
test [sampled], NDCG@5: 0.3453, HR@5: 0.3947, NDCG@10: 0.4072, HR@10: 0.5869, MRR: 0.3761
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/sasrec_best.pth
epoch=36, loss=0.0757
epoch=37, loss=0.0789
epoch=38, loss=0.0782
epoch=39, loss=0.0766
epoch=40, loss=0.0773
valid [task], Top5Acc: 0.4253, Top10Acc: 0.6724, Acc: 0.0848, MacroF1: 0.1639
valid [full], NDCG@5: 0.6787, HR@5: 0.8306, NDCG@10: 0.7213, HR@10: 0.9664, MRR: 0.6495
valid [sampled], NDCG@5: 0.5424, HR@5: 0.5456, NDCG@10: 0.5502, HR@10: 0.5704, MRR: 0.5599
test [task], Top5Acc: 0.4779, Top10Acc: 0.6631, Acc: 0.0967, MacroF1: 0.0467
test [full], NDCG@5: 0.8046, HR@5: 0.9410, NDCG@10: 0.8251, HR@10: 1.0000, MRR: 0.7670
test [sampled], NDCG@5: 0.3536, HR@5: 0.3651, NDCG@10: 0.3804, HR@10: 0.4500, MRR: 0.3907
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0788
epoch=42, loss=0.0763
epoch=43, loss=0.0773
epoch=44, loss=0.0772
epoch=45, loss=0.0765
valid [task], Top5Acc: 0.4955, Top10Acc: 0.6505, Acc: 0.1185, MacroF1: 0.1465
valid [full], NDCG@5: 0.6708, HR@5: 0.7891, NDCG@10: 0.7202, HR@10: 0.9427, MRR: 0.6572
valid [sampled], NDCG@5: 0.5591, HR@5: 0.5639, NDCG@10: 0.5700, HR@10: 0.5981, MRR: 0.5750
test [task], Top5Acc: 0.4350, Top10Acc: 0.6591, Acc: 0.2161, MacroF1: 0.0663
test [full], NDCG@5: 0.8031, HR@5: 0.9598, NDCG@10: 0.8172, HR@10: 1.0000, MRR: 0.7558
test [sampled], NDCG@5: 0.3518, HR@5: 0.3590, NDCG@10: 0.3809, HR@10: 0.4519, MRR: 0.3914
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0760
epoch=47, loss=0.0753
epoch=48, loss=0.0747
epoch=49, loss=0.0771
epoch=50, loss=0.0747
valid [task], Top5Acc: 0.4653, Top10Acc: 0.6727, Acc: 0.1232, MacroF1: 0.1520
valid [full], NDCG@5: 0.6865, HR@5: 0.8260, NDCG@10: 0.7262, HR@10: 0.9498, MRR: 0.6616
valid [sampled], NDCG@5: 0.5555, HR@5: 0.5593, NDCG@10: 0.5664, HR@10: 0.5936, MRR: 0.5733
test [task], Top5Acc: 0.4918, Top10Acc: 0.7079, Acc: 0.1668, MacroF1: 0.0610
test [full], NDCG@5: 0.8021, HR@5: 0.9506, NDCG@10: 0.8179, HR@10: 1.0000, MRR: 0.7571
test [sampled], NDCG@5: 0.3533, HR@5: 0.3591, NDCG@10: 0.3819, HR@10: 0.4505, MRR: 0.3935
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml20_s7/sasrec_last.pth

## Train `refine_ml50_do035 + Additive_sinusoidal + delta_prev_seconds`

### `timeaware_dprev_sinusoidal_ml50_do035_s42`

In [14]:
!python src/train_sasrec.py \
  --run_name timeaware_dprev_sinusoidal_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_prev_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42
epoch=1, loss=0.6141
epoch=2, loss=0.2764
epoch=3, loss=0.2091
epoch=4, loss=0.1736
epoch=5, loss=0.1503
valid [task], Top5Acc: 0.4868, Top10Acc: 0.6839, Acc: 0.0672, MacroF1: 0.0903
valid [full], NDCG@5: 0.6233, HR@5: 0.7164, NDCG@10: 0.6778, HR@10: 0.8884, MRR: 0.6252
valid [sampled], NDCG@5: 0.5520, HR@5: 0.5521, NDCG@10: 0.5532, HR@10: 0.5561, MRR: 0.5648
test [task], Top5Acc: 0.1788, Top10Acc: 0.4351, Acc: 0.0363, MacroF1: 0.0301
test [full], NDCG@5: 0.5168, HR@5: 0.6697, NDCG@10: 0.5660, HR@10: 0.8226, MRR: 0.4991
test [sampled], NDCG@5: 0.1012, HR@5: 0.1115, NDCG@10: 0.1309, HR@10: 0.2063, MRR: 0.1423
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1359
epoch=7, loss=0.1206
epoch=8, loss=0.1122
epoch=9, loss=0.1061
epoch=10, loss=0.1017
valid [task], Top5Acc: 0.4040, Top10Acc: 0.6929, Acc: 0.1201, MacroF1: 0.0960
valid [full], NDCG@5: 0.6363, HR@5: 0.7123, NDCG@10: 0.7008, HR@10: 0.9185, MRR: 0.6434
valid [sampled], NDCG@5: 0.5518, HR@5: 0.5577, NDCG@10: 0.5658, HR@10: 0.6015, MRR: 0.5673
test [task], Top5Acc: 0.2789, Top10Acc: 0.6162, Acc: 0.0228, MacroF1: 0.0193
test [full], NDCG@5: 0.7016, HR@5: 0.8853, NDCG@10: 0.7291, HR@10: 0.9684, MRR: 0.6560
test [sampled], NDCG@5: 0.0874, HR@5: 0.1272, NDCG@10: 0.1514, HR@10: 0.3275, MRR: 0.1334
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=0.1009
epoch=12, loss=0.0946
epoch=13, loss=0.0920
epoch=14, loss=0.0913
epoch=15, loss=0.0911
valid [task], Top5Acc: 0.3923, Top10Acc: 0.7103, Acc: 0.1204, MacroF1: 0.1145
valid [full], NDCG@5: 0.6485, HR@5: 0.7695, NDCG@10: 0.7118, HR@10: 0.9666, MRR: 0.6378
valid [sampled], NDCG@5: 0.5302, HR@5: 0.5355, NDCG@10: 0.5433, HR@10: 0.5766, MRR: 0.5479
test [task], Top5Acc: 0.3160, Top10Acc: 0.7565, Acc: 0.0340, MacroF1: 0.0264
test [full], NDCG@5: 0.7509, HR@5: 0.9532, NDCG@10: 0.7653, HR@10: 1.0000, MRR: 0.6887
test [sampled], NDCG@5: 0.0944, HR@5: 0.1351, NDCG@10: 0.1677, HR@10: 0.3654, MRR: 0.1459
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0878
epoch=17, loss=0.0872
epoch=18, loss=0.0861
epoch=19, loss=0.0843
epoch=20, loss=0.0828
valid [task], Top5Acc: 0.3839, Top10Acc: 0.6389, Acc: 0.1191, MacroF1: 0.0883
valid [full], NDCG@5: 0.6583, HR@5: 0.7765, NDCG@10: 0.7158, HR@10: 0.9557, MRR: 0.6466
valid [sampled], NDCG@5: 0.5406, HR@5: 0.5464, NDCG@10: 0.5539, HR@10: 0.5882, MRR: 0.5582
test [task], Top5Acc: 0.3573, Top10Acc: 0.6185, Acc: 0.0328, MacroF1: 0.0278
test [full], NDCG@5: 0.7392, HR@5: 0.9335, NDCG@10: 0.7611, HR@10: 1.0000, MRR: 0.6826
test [sampled], NDCG@5: 0.0801, HR@5: 0.1184, NDCG@10: 0.1585, HR@10: 0.3651, MRR: 0.1340
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=21, loss=0.0826
epoch=22, loss=0.0836
epoch=23, loss=0.0824
epoch=24, loss=0.0804
epoch=25, loss=0.0803
valid [task], Top5Acc: 0.3882, Top10Acc: 0.6408, Acc: 0.1200, MacroF1: 0.0906
valid [full], NDCG@5: 0.6646, HR@5: 0.7793, NDCG@10: 0.7176, HR@10: 0.9476, MRR: 0.6527
valid [sampled], NDCG@5: 0.5574, HR@5: 0.5624, NDCG@10: 0.5681, HR@10: 0.5960, MRR: 0.5732
test [task], Top5Acc: 0.3752, Top10Acc: 0.5771, Acc: 0.0338, MacroF1: 0.0290
test [full], NDCG@5: 0.7310, HR@5: 0.9582, NDCG@10: 0.7441, HR@10: 1.0000, MRR: 0.6586
test [sampled], NDCG@5: 0.0819, HR@5: 0.1120, NDCG@10: 0.1553, HR@10: 0.3437, MRR: 0.1390
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=26, loss=0.0800
epoch=27, loss=0.0813
epoch=28, loss=0.0797
epoch=29, loss=0.0814
epoch=30, loss=0.0773
valid [task], Top5Acc: 0.3913, Top10Acc: 0.5755, Acc: 0.1254, MacroF1: 0.1169
valid [full], NDCG@5: 0.6677, HR@5: 0.8276, NDCG@10: 0.7099, HR@10: 0.9620, MRR: 0.6349
valid [sampled], NDCG@5: 0.5011, HR@5: 0.5067, NDCG@10: 0.5161, HR@10: 0.5542, MRR: 0.5215
test [task], Top5Acc: 0.4791, Top10Acc: 0.5687, Acc: 0.0379, MacroF1: 0.0326
test [full], NDCG@5: 0.8041, HR@5: 0.9189, NDCG@10: 0.8320, HR@10: 1.0000, MRR: 0.7788
test [sampled], NDCG@5: 0.1628, HR@5: 0.2211, NDCG@10: 0.2481, HR@10: 0.4853, MRR: 0.2043
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0800
epoch=32, loss=0.0772
epoch=33, loss=0.0795
epoch=34, loss=0.0760
epoch=35, loss=0.0764
valid [task], Top5Acc: 0.3962, Top10Acc: 0.6144, Acc: 0.1346, MacroF1: 0.1487
valid [full], NDCG@5: 0.7100, HR@5: 0.8928, NDCG@10: 0.7342, HR@10: 0.9727, MRR: 0.6621
valid [sampled], NDCG@5: 0.5387, HR@5: 0.5448, NDCG@10: 0.5521, HR@10: 0.5871, MRR: 0.5585
test [task], Top5Acc: 0.4690, Top10Acc: 0.5544, Acc: 0.0243, MacroF1: 0.0221
test [full], NDCG@5: 0.8340, HR@5: 0.9556, NDCG@10: 0.8491, HR@10: 1.0000, MRR: 0.7999
test [sampled], NDCG@5: 0.2021, HR@5: 0.2512, NDCG@10: 0.2816, HR@10: 0.4995, MRR: 0.2455
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=36, loss=0.0749
epoch=37, loss=0.0760
epoch=38, loss=0.0745
epoch=39, loss=0.0770
epoch=40, loss=0.0751
valid [task], Top5Acc: 0.3909, Top10Acc: 0.6107, Acc: 0.1411, MacroF1: 0.1480
valid [full], NDCG@5: 0.7074, HR@5: 0.8582, NDCG@10: 0.7383, HR@10: 0.9586, MRR: 0.6734
valid [sampled], NDCG@5: 0.5543, HR@5: 0.5567, NDCG@10: 0.5668, HR@10: 0.5966, MRR: 0.5752
test [task], Top5Acc: 0.4621, Top10Acc: 0.5416, Acc: 0.0551, MacroF1: 0.0359
test [full], NDCG@5: 0.8379, HR@5: 0.9427, NDCG@10: 0.8568, HR@10: 1.0000, MRR: 0.8104
test [sampled], NDCG@5: 0.2502, HR@5: 0.2958, NDCG@10: 0.3161, HR@10: 0.5013, MRR: 0.2887
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=41, loss=0.0754
epoch=42, loss=0.0756
epoch=43, loss=0.0763
epoch=44, loss=0.0758
epoch=45, loss=0.0759
valid [task], Top5Acc: 0.4000, Top10Acc: 0.6054, Acc: 0.1204, MacroF1: 0.1027
valid [full], NDCG@5: 0.7015, HR@5: 0.8545, NDCG@10: 0.7386, HR@10: 0.9725, MRR: 0.6691
valid [sampled], NDCG@5: 0.5611, HR@5: 0.5662, NDCG@10: 0.5741, HR@10: 0.6072, MRR: 0.5793
test [task], Top5Acc: 0.4747, Top10Acc: 0.6002, Acc: 0.1482, MacroF1: 0.0718
test [full], NDCG@5: 0.8494, HR@5: 0.9293, NDCG@10: 0.8725, HR@10: 1.0000, MRR: 0.8326
test [sampled], NDCG@5: 0.3629, HR@5: 0.3983, NDCG@10: 0.4136, HR@10: 0.5564, MRR: 0.3944
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=46, loss=0.0730
epoch=47, loss=0.0744
epoch=48, loss=0.0729
epoch=49, loss=0.0752
epoch=50, loss=0.0737
valid [task], Top5Acc: 0.3840, Top10Acc: 0.5945, Acc: 0.1356, MacroF1: 0.1308
valid [full], NDCG@5: 0.7116, HR@5: 0.8721, NDCG@10: 0.7408, HR@10: 0.9667, MRR: 0.6734
valid [sampled], NDCG@5: 0.5546, HR@5: 0.5602, NDCG@10: 0.5705, HR@10: 0.6101, MRR: 0.5747
test [task], Top5Acc: 0.3642, Top10Acc: 0.5377, Acc: 0.1780, MacroF1: 0.0675
test [full], NDCG@5: 0.7401, HR@5: 0.9280, NDCG@10: 0.7629, HR@10: 1.0000, MRR: 0.6853
test [sampled], NDCG@5: 0.2676, HR@5: 0.2752, NDCG@10: 0.2956, HR@10: 0.3645, MRR: 0.3096
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s42/sasrec_last.pth

### `timeaware_dprev_sinusoidal_ml50_do035_s2024`

In [15]:
!python src/train_sasrec.py \
  --run_name timeaware_dprev_sinusoidal_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_prev_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024
epoch=1, loss=0.6150
epoch=2, loss=0.2794
epoch=3, loss=0.2047
epoch=4, loss=0.1658
epoch=5, loss=0.1445
valid [task], Top5Acc: 0.4892, Top10Acc: 0.7099, Acc: 0.0830, MacroF1: 0.1456
valid [full], NDCG@5: 0.7036, HR@5: 0.8896, NDCG@10: 0.7331, HR@10: 0.9827, MRR: 0.6580
valid [sampled], NDCG@5: 0.5585, HR@5: 0.5596, NDCG@10: 0.5625, HR@10: 0.5723, MRR: 0.5747
test [task], Top5Acc: 0.3383, Top10Acc: 0.8051, Acc: 0.0262, MacroF1: 0.0234
test [full], NDCG@5: 0.7766, HR@5: 0.9278, NDCG@10: 0.8012, HR@10: 1.0000, MRR: 0.7377
test [sampled], NDCG@5: 0.1902, HR@5: 0.2239, NDCG@10: 0.2445, HR@10: 0.3935, MRR: 0.2328
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1260
epoch=7, loss=0.1161
epoch=8, loss=0.1103
epoch=9, loss=0.1034
epoch=10, loss=0.1021
valid [task], Top5Acc: 0.5002, Top10Acc: 0.7274, Acc: 0.0848, MacroF1: 0.1300
valid [full], NDCG@5: 0.6755, HR@5: 0.8147, NDCG@10: 0.7268, HR@10: 0.9693, MRR: 0.6560
valid [sampled], NDCG@5: 0.5610, HR@5: 0.5656, NDCG@10: 0.5722, HR@10: 0.6003, MRR: 0.5767
test [task], Top5Acc: 0.3612, Top10Acc: 0.7756, Acc: 0.0178, MacroF1: 0.0158
test [full], NDCG@5: 0.8066, HR@5: 0.9196, NDCG@10: 0.8317, HR@10: 1.0000, MRR: 0.7796
test [sampled], NDCG@5: 0.2528, HR@5: 0.2968, NDCG@10: 0.3099, HR@10: 0.4744, MRR: 0.2877
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0988
epoch=12, loss=0.0963
epoch=13, loss=0.0934
epoch=14, loss=0.0896
epoch=15, loss=0.0898
valid [task], Top5Acc: 0.4946, Top10Acc: 0.7481, Acc: 0.2318, MacroF1: 0.2179
valid [full], NDCG@5: 0.6986, HR@5: 0.8672, NDCG@10: 0.7308, HR@10: 0.9695, MRR: 0.6607
valid [sampled], NDCG@5: 0.5636, HR@5: 0.5681, NDCG@10: 0.5744, HR@10: 0.6017, MRR: 0.5796
test [task], Top5Acc: 0.3446, Top10Acc: 0.7001, Acc: 0.0302, MacroF1: 0.0215
test [full], NDCG@5: 0.8098, HR@5: 0.9335, NDCG@10: 0.8305, HR@10: 1.0000, MRR: 0.7760
test [sampled], NDCG@5: 0.1888, HR@5: 0.2301, NDCG@10: 0.2561, HR@10: 0.4418, MRR: 0.2327
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0878
epoch=17, loss=0.0845
epoch=18, loss=0.0851
epoch=19, loss=0.0853
epoch=20, loss=0.0839
valid [task], Top5Acc: 0.4949, Top10Acc: 0.6881, Acc: 0.1796, MacroF1: 0.1734
valid [full], NDCG@5: 0.6766, HR@5: 0.8151, NDCG@10: 0.7244, HR@10: 0.9634, MRR: 0.6547
valid [sampled], NDCG@5: 0.5564, HR@5: 0.5605, NDCG@10: 0.5642, HR@10: 0.5848, MRR: 0.5723
test [task], Top5Acc: 0.4393, Top10Acc: 0.7122, Acc: 0.0407, MacroF1: 0.0284
test [full], NDCG@5: 0.8018, HR@5: 0.9446, NDCG@10: 0.8186, HR@10: 1.0000, MRR: 0.7593
test [sampled], NDCG@5: 0.2631, HR@5: 0.2903, NDCG@10: 0.3103, HR@10: 0.4381, MRR: 0.3045
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0805
epoch=22, loss=0.0804
epoch=23, loss=0.0803
epoch=24, loss=0.0815
epoch=25, loss=0.0817
valid [task], Top5Acc: 0.4955, Top10Acc: 0.7440, Acc: 0.1777, MacroF1: 0.1711
valid [full], NDCG@5: 0.7171, HR@5: 0.9049, NDCG@10: 0.7368, HR@10: 0.9702, MRR: 0.6667
valid [sampled], NDCG@5: 0.5550, HR@5: 0.5588, NDCG@10: 0.5650, HR@10: 0.5903, MRR: 0.5738
test [task], Top5Acc: 0.4337, Top10Acc: 0.6970, Acc: 0.0781, MacroF1: 0.0414
test [full], NDCG@5: 0.8121, HR@5: 0.9654, NDCG@10: 0.8242, HR@10: 0.9999, MRR: 0.7655
test [sampled], NDCG@5: 0.2344, HR@5: 0.2635, NDCG@10: 0.2857, HR@10: 0.4244, MRR: 0.2785
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/sasrec_best.pth
epoch=26, loss=0.0788
epoch=27, loss=0.0801
epoch=28, loss=0.0781
epoch=29, loss=0.0795
epoch=30, loss=0.0760
valid [task], Top5Acc: 0.4877, Top10Acc: 0.7001, Acc: 0.1866, MacroF1: 0.1723
valid [full], NDCG@5: 0.7027, HR@5: 0.8732, NDCG@10: 0.7342, HR@10: 0.9725, MRR: 0.6634
valid [sampled], NDCG@5: 0.5623, HR@5: 0.5643, NDCG@10: 0.5684, HR@10: 0.5834, MRR: 0.5794
test [task], Top5Acc: 0.2425, Top10Acc: 0.7320, Acc: 0.0468, MacroF1: 0.0321
test [full], NDCG@5: 0.7781, HR@5: 0.9741, NDCG@10: 0.7872, HR@10: 0.9999, MRR: 0.7175
test [sampled], NDCG@5: 0.2578, HR@5: 0.2802, NDCG@10: 0.2907, HR@10: 0.3829, MRR: 0.2969
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0766
epoch=32, loss=0.0769
epoch=33, loss=0.0766
epoch=34, loss=0.0761
epoch=35, loss=0.0755
valid [task], Top5Acc: 0.5000, Top10Acc: 0.7153, Acc: 0.2389, MacroF1: 0.1920
valid [full], NDCG@5: 0.7012, HR@5: 0.8727, NDCG@10: 0.7332, HR@10: 0.9732, MRR: 0.6619
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5615, NDCG@10: 0.5663, HR@10: 0.5856, MRR: 0.5759
test [task], Top5Acc: 0.4608, Top10Acc: 0.7338, Acc: 0.1153, MacroF1: 0.1157
test [full], NDCG@5: 0.8068, HR@5: 0.9552, NDCG@10: 0.8212, HR@10: 1.0000, MRR: 0.7622
test [sampled], NDCG@5: 0.2956, HR@5: 0.3210, NDCG@10: 0.3379, HR@10: 0.4532, MRR: 0.3347
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0759
epoch=37, loss=0.0766
epoch=38, loss=0.0744
epoch=39, loss=0.0760
epoch=40, loss=0.0741
valid [task], Top5Acc: 0.4983, Top10Acc: 0.7124, Acc: 0.2125, MacroF1: 0.1607
valid [full], NDCG@5: 0.7070, HR@5: 0.8566, NDCG@10: 0.7448, HR@10: 0.9737, MRR: 0.6762
valid [sampled], NDCG@5: 0.5615, HR@5: 0.5659, NDCG@10: 0.5737, HR@10: 0.6045, MRR: 0.5806
test [task], Top5Acc: 0.3846, Top10Acc: 0.7404, Acc: 0.1224, MacroF1: 0.1185
test [full], NDCG@5: 0.7921, HR@5: 0.9466, NDCG@10: 0.8101, HR@10: 0.9999, MRR: 0.7478
test [sampled], NDCG@5: 0.3504, HR@5: 0.3630, NDCG@10: 0.3739, HR@10: 0.4377, MRR: 0.3859
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/sasrec_best.pth
epoch=41, loss=0.0742
epoch=42, loss=0.0771
epoch=43, loss=0.0746
epoch=44, loss=0.0737
epoch=45, loss=0.0742
valid [task], Top5Acc: 0.5008, Top10Acc: 0.7301, Acc: 0.2214, MacroF1: 0.1582
valid [full], NDCG@5: 0.7264, HR@5: 0.8970, NDCG@10: 0.7504, HR@10: 0.9743, MRR: 0.6822
valid [sampled], NDCG@5: 0.5608, HR@5: 0.5673, NDCG@10: 0.5766, HR@10: 0.6168, MRR: 0.5811
test [task], Top5Acc: 0.4458, Top10Acc: 0.7336, Acc: 0.0726, MacroF1: 0.0783
test [full], NDCG@5: 0.8047, HR@5: 0.9428, NDCG@10: 0.8243, HR@10: 1.0000, MRR: 0.7656
test [sampled], NDCG@5: 0.2886, HR@5: 0.3182, NDCG@10: 0.3347, HR@10: 0.4621, MRR: 0.3278
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/sasrec_best.pth
epoch=46, loss=0.0739
epoch=47, loss=0.0727
epoch=48, loss=0.0736
epoch=49, loss=0.0727
epoch=50, loss=0.0734
valid [task], Top5Acc: 0.4949, Top10Acc: 0.7239, Acc: 0.2185, MacroF1: 0.1493
valid [full], NDCG@5: 0.7137, HR@5: 0.8997, NDCG@10: 0.7372, HR@10: 0.9757, MRR: 0.6652
valid [sampled], NDCG@5: 0.5550, HR@5: 0.5571, NDCG@10: 0.5631, HR@10: 0.5826, MRR: 0.5745
test [task], Top5Acc: 0.4424, Top10Acc: 0.7335, Acc: 0.1159, MacroF1: 0.0627
test [full], NDCG@5: 0.7919, HR@5: 0.9365, NDCG@10: 0.8116, HR@10: 1.0000, MRR: 0.7500
test [sampled], NDCG@5: 0.2657, HR@5: 0.2941, NDCG@10: 0.3112, HR@10: 0.4366, MRR: 0.3053
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s2024/sasrec_last.pth

### `timeaware_dprev_sinusoidal_ml50_do035_s7`

In [16]:
!python src/train_sasrec.py \
  --run_name timeaware_dprev_sinusoidal_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_prev_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7
epoch=1, loss=0.5913
epoch=2, loss=0.2778
epoch=3, loss=0.2061
epoch=4, loss=0.1739
epoch=5, loss=0.1520
valid [task], Top5Acc: 0.4827, Top10Acc: 0.7249, Acc: 0.0786, MacroF1: 0.1180
valid [full], NDCG@5: 0.6371, HR@5: 0.7505, NDCG@10: 0.7138, HR@10: 0.9782, MRR: 0.6365
valid [sampled], NDCG@5: 0.5512, HR@5: 0.5516, NDCG@10: 0.5529, HR@10: 0.5570, MRR: 0.5654
test [task], Top5Acc: 0.2035, Top10Acc: 0.7309, Acc: 0.0588, MacroF1: 0.0388
test [full], NDCG@5: 0.6391, HR@5: 0.8410, NDCG@10: 0.6861, HR@10: 0.9863, MRR: 0.5927
test [sampled], NDCG@5: 0.2642, HR@5: 0.2649, NDCG@10: 0.2714, HR@10: 0.2884, MRR: 0.3008
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1308
epoch=7, loss=0.1195
epoch=8, loss=0.1098
epoch=9, loss=0.1060
epoch=10, loss=0.1027
valid [task], Top5Acc: 0.4940, Top10Acc: 0.6978, Acc: 0.0668, MacroF1: 0.0844
valid [full], NDCG@5: 0.6725, HR@5: 0.8194, NDCG@10: 0.7150, HR@10: 0.9517, MRR: 0.6474
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5590, NDCG@10: 0.5625, HR@10: 0.5767, MRR: 0.5718
test [task], Top5Acc: 0.4019, Top10Acc: 0.7651, Acc: 0.0577, MacroF1: 0.0327
test [full], NDCG@5: 0.7053, HR@5: 0.9711, NDCG@10: 0.7153, HR@10: 1.0000, MRR: 0.6195
test [sampled], NDCG@5: 0.1191, HR@5: 0.1242, NDCG@10: 0.1584, HR@10: 0.2512, MRR: 0.1750
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=0.0976
epoch=12, loss=0.0948
epoch=13, loss=0.0929
epoch=14, loss=0.0898
epoch=15, loss=0.0884
valid [task], Top5Acc: 0.4995, Top10Acc: 0.6911, Acc: 0.1823, MacroF1: 0.1627
valid [full], NDCG@5: 0.6955, HR@5: 0.8404, NDCG@10: 0.7328, HR@10: 0.9566, MRR: 0.6676
valid [sampled], NDCG@5: 0.5643, HR@5: 0.5671, NDCG@10: 0.5731, HR@10: 0.5950, MRR: 0.5813
test [task], Top5Acc: 0.5351, Top10Acc: 0.7878, Acc: 0.0689, MacroF1: 0.0365
test [full], NDCG@5: 0.7776, HR@5: 0.9965, NDCG@10: 0.7788, HR@10: 1.0000, MRR: 0.7022
test [sampled], NDCG@5: 0.1958, HR@5: 0.2011, NDCG@10: 0.2483, HR@10: 0.3699, MRR: 0.2542
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=0.0883
epoch=17, loss=0.0854
epoch=18, loss=0.0840
epoch=19, loss=0.0843
epoch=20, loss=0.0824
valid [task], Top5Acc: 0.4965, Top10Acc: 0.6731, Acc: 0.1873, MacroF1: 0.1956
valid [full], NDCG@5: 0.6944, HR@5: 0.8334, NDCG@10: 0.7321, HR@10: 0.9542, MRR: 0.6675
valid [sampled], NDCG@5: 0.5616, HR@5: 0.5663, NDCG@10: 0.5740, HR@10: 0.6051, MRR: 0.5790
test [task], Top5Acc: 0.5513, Top10Acc: 0.8044, Acc: 0.0686, MacroF1: 0.0359
test [full], NDCG@5: 0.8124, HR@5: 0.9995, NDCG@10: 0.8126, HR@10: 1.0000, MRR: 0.7470
test [sampled], NDCG@5: 0.3005, HR@5: 0.3164, NDCG@10: 0.3558, HR@10: 0.4927, MRR: 0.3500
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0821
epoch=22, loss=0.0801
epoch=23, loss=0.0803
epoch=24, loss=0.0813
epoch=25, loss=0.0771
valid [task], Top5Acc: 0.4956, Top10Acc: 0.6689, Acc: 0.1859, MacroF1: 0.1919
valid [full], NDCG@5: 0.6971, HR@5: 0.8162, NDCG@10: 0.7329, HR@10: 0.9274, MRR: 0.6778
valid [sampled], NDCG@5: 0.5585, HR@5: 0.5656, NDCG@10: 0.5771, HR@10: 0.6243, MRR: 0.5777
test [task], Top5Acc: 0.4704, Top10Acc: 0.8059, Acc: 0.1194, MacroF1: 0.0556
test [full], NDCG@5: 0.8487, HR@5: 0.9999, NDCG@10: 0.8487, HR@10: 1.0000, MRR: 0.7961
test [sampled], NDCG@5: 0.3276, HR@5: 0.3530, NDCG@10: 0.3859, HR@10: 0.5365, MRR: 0.3724
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=26, loss=0.0795
epoch=27, loss=0.0778
epoch=28, loss=0.0776
epoch=29, loss=0.0784
epoch=30, loss=0.0763
valid [task], Top5Acc: 0.4943, Top10Acc: 0.6875, Acc: 0.1815, MacroF1: 0.1959
valid [full], NDCG@5: 0.7100, HR@5: 0.8568, NDCG@10: 0.7375, HR@10: 0.9473, MRR: 0.6764
valid [sampled], NDCG@5: 0.5547, HR@5: 0.5621, NDCG@10: 0.5737, HR@10: 0.6218, MRR: 0.5746
test [task], Top5Acc: 0.5506, Top10Acc: 0.7204, Acc: 0.0817, MacroF1: 0.0434
test [full], NDCG@5: 0.8436, HR@5: 0.9997, NDCG@10: 0.8436, HR@10: 1.0000, MRR: 0.7889
test [sampled], NDCG@5: 0.2466, HR@5: 0.2819, NDCG@10: 0.3195, HR@10: 0.5108, MRR: 0.2962
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=31, loss=0.0772
epoch=32, loss=0.0773
epoch=33, loss=0.0761
epoch=34, loss=0.0753
epoch=35, loss=0.0768
valid [task], Top5Acc: 0.4935, Top10Acc: 0.6847, Acc: 0.1830, MacroF1: 0.1633
valid [full], NDCG@5: 0.7133, HR@5: 0.8580, NDCG@10: 0.7402, HR@10: 0.9466, MRR: 0.6800
valid [sampled], NDCG@5: 0.5571, HR@5: 0.5633, NDCG@10: 0.5772, HR@10: 0.6264, MRR: 0.5778
test [task], Top5Acc: 0.5389, Top10Acc: 0.7295, Acc: 0.1332, MacroF1: 0.0551
test [full], NDCG@5: 0.9226, HR@5: 0.9997, NDCG@10: 0.9227, HR@10: 1.0000, MRR: 0.8956
test [sampled], NDCG@5: 0.3967, HR@5: 0.4332, NDCG@10: 0.4689, HR@10: 0.6584, MRR: 0.4359
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=36, loss=0.0769
epoch=37, loss=0.0757
epoch=38, loss=0.0756
epoch=39, loss=0.0747
epoch=40, loss=0.0740
valid [task], Top5Acc: 0.4982, Top10Acc: 0.6855, Acc: 0.1871, MacroF1: 0.1492
valid [full], NDCG@5: 0.7109, HR@5: 0.8549, NDCG@10: 0.7411, HR@10: 0.9545, MRR: 0.6785
valid [sampled], NDCG@5: 0.5590, HR@5: 0.5663, NDCG@10: 0.5781, HR@10: 0.6262, MRR: 0.5787
test [task], Top5Acc: 0.5544, Top10Acc: 0.7763, Acc: 0.0756, MacroF1: 0.0340
test [full], NDCG@5: 0.9264, HR@5: 0.9995, NDCG@10: 0.9265, HR@10: 1.0000, MRR: 0.9010
test [sampled], NDCG@5: 0.3252, HR@5: 0.3816, NDCG@10: 0.4147, HR@10: 0.6608, MRR: 0.3651
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=41, loss=0.0777
epoch=42, loss=0.0748
epoch=43, loss=0.0748
epoch=44, loss=0.0748
epoch=45, loss=0.0733
valid [task], Top5Acc: 0.5000, Top10Acc: 0.6749, Acc: 0.1790, MacroF1: 0.1695
valid [full], NDCG@5: 0.7055, HR@5: 0.8331, NDCG@10: 0.7377, HR@10: 0.9343, MRR: 0.6812
valid [sampled], NDCG@5: 0.5597, HR@5: 0.5670, NDCG@10: 0.5801, HR@10: 0.6313, MRR: 0.5796
test [task], Top5Acc: 0.5392, Top10Acc: 0.7396, Acc: 0.0897, MacroF1: 0.0422
test [full], NDCG@5: 0.9336, HR@5: 0.9985, NDCG@10: 0.9341, HR@10: 1.0000, MRR: 0.9113
test [sampled], NDCG@5: 0.3508, HR@5: 0.4045, NDCG@10: 0.4363, HR@10: 0.6702, MRR: 0.3884
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0722
epoch=47, loss=0.0738
epoch=48, loss=0.0728
epoch=49, loss=0.0740
epoch=50, loss=0.0725
valid [task], Top5Acc: 0.5001, Top10Acc: 0.6853, Acc: 0.1807, MacroF1: 0.1432
valid [full], NDCG@5: 0.7111, HR@5: 0.8429, NDCG@10: 0.7406, HR@10: 0.9360, MRR: 0.6845
valid [sampled], NDCG@5: 0.5710, HR@5: 0.5780, NDCG@10: 0.5883, HR@10: 0.6320, MRR: 0.5897
test [task], Top5Acc: 0.5441, Top10Acc: 0.7053, Acc: 0.0856, MacroF1: 0.0374
test [full], NDCG@5: 0.9500, HR@5: 0.9993, NDCG@10: 0.9502, HR@10: 1.0000, MRR: 0.9329
test [sampled], NDCG@5: 0.3765, HR@5: 0.4429, NDCG@10: 0.4640, HR@10: 0.7144, MRR: 0.4093
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dprev_sinusoidal_ml50_do035_s7/sasrec_last.pth

## Train `refine_ml50_do035 + Additive_sinusoidal + delta_start_seconds`

### `timeaware_dstart_sinusoidal_ml50_do035_s42`

In [17]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_sinusoidal_ml50_do035_s42 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 42 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42
epoch=1, loss=0.6154
epoch=2, loss=0.2774
epoch=3, loss=0.2108
epoch=4, loss=0.1742
epoch=5, loss=0.1498
valid [task], Top5Acc: 0.4962, Top10Acc: 0.7045, Acc: 0.0734, MacroF1: 0.0980
valid [full], NDCG@5: 0.6215, HR@5: 0.7058, NDCG@10: 0.6799, HR@10: 0.8882, MRR: 0.6280
valid [sampled], NDCG@5: 0.5575, HR@5: 0.5576, NDCG@10: 0.5579, HR@10: 0.5589, MRR: 0.5699
test [task], Top5Acc: 0.0935, Top10Acc: 0.4476, Acc: 0.0373, MacroF1: 0.0305
test [full], NDCG@5: 0.4981, HR@5: 0.7021, NDCG@10: 0.5290, HR@10: 0.8023, MRR: 0.4585
test [sampled], NDCG@5: 0.1147, HR@5: 0.1177, NDCG@10: 0.1322, HR@10: 0.1742, MRR: 0.1524
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=6, loss=0.1353
epoch=7, loss=0.1204
epoch=8, loss=0.1120
epoch=9, loss=0.1054
epoch=10, loss=0.1022
valid [task], Top5Acc: 0.5001, Top10Acc: 0.7099, Acc: 0.1042, MacroF1: 0.1461
valid [full], NDCG@5: 0.6578, HR@5: 0.7588, NDCG@10: 0.7115, HR@10: 0.9302, MRR: 0.6519
valid [sampled], NDCG@5: 0.5570, HR@5: 0.5635, NDCG@10: 0.5720, HR@10: 0.6106, MRR: 0.5730
test [task], Top5Acc: 0.3046, Top10Acc: 0.6707, Acc: 0.0223, MacroF1: 0.0185
test [full], NDCG@5: 0.6577, HR@5: 0.9244, NDCG@10: 0.6832, HR@10: 0.9996, MRR: 0.5779
test [sampled], NDCG@5: 0.0901, HR@5: 0.0997, NDCG@10: 0.1356, HR@10: 0.2451, MRR: 0.1467
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=11, loss=0.1007
epoch=12, loss=0.0947
epoch=13, loss=0.0915
epoch=14, loss=0.0922
epoch=15, loss=0.0914
valid [task], Top5Acc: 0.4386, Top10Acc: 0.6859, Acc: 0.1388, MacroF1: 0.1112
valid [full], NDCG@5: 0.6968, HR@5: 0.8426, NDCG@10: 0.7318, HR@10: 0.9537, MRR: 0.6673
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5654, NDCG@10: 0.5733, HR@10: 0.6054, MRR: 0.5785
test [task], Top5Acc: 0.3184, Top10Acc: 0.7406, Acc: 0.0325, MacroF1: 0.0208
test [full], NDCG@5: 0.7670, HR@5: 0.9446, NDCG@10: 0.7863, HR@10: 0.9999, MRR: 0.7145
test [sampled], NDCG@5: 0.1170, HR@5: 0.1593, NDCG@10: 0.1923, HR@10: 0.3956, MRR: 0.1679
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=16, loss=0.0878
epoch=17, loss=0.0869
epoch=18, loss=0.0862
epoch=19, loss=0.0848
epoch=20, loss=0.0830
valid [task], Top5Acc: 0.3955, Top10Acc: 0.6257, Acc: 0.1300, MacroF1: 0.1270
valid [full], NDCG@5: 0.6592, HR@5: 0.8131, NDCG@10: 0.7053, HR@10: 0.9569, MRR: 0.6304
valid [sampled], NDCG@5: 0.4934, HR@5: 0.4988, NDCG@10: 0.5064, HR@10: 0.5397, MRR: 0.5139
test [task], Top5Acc: 0.4197, Top10Acc: 0.7492, Acc: 0.0314, MacroF1: 0.0226
test [full], NDCG@5: 0.8067, HR@5: 0.9315, NDCG@10: 0.8305, HR@10: 1.0000, MRR: 0.7748
test [sampled], NDCG@5: 0.1826, HR@5: 0.2324, NDCG@10: 0.2560, HR@10: 0.4604, MRR: 0.2250
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0835
epoch=22, loss=0.0839
epoch=23, loss=0.0824
epoch=24, loss=0.0803
epoch=25, loss=0.0808
valid [task], Top5Acc: 0.3999, Top10Acc: 0.7025, Acc: 0.1360, MacroF1: 0.1326
valid [full], NDCG@5: 0.7196, HR@5: 0.8809, NDCG@10: 0.7437, HR@10: 0.9597, MRR: 0.6790
valid [sampled], NDCG@5: 0.5521, HR@5: 0.5579, NDCG@10: 0.5680, HR@10: 0.6082, MRR: 0.5732
test [task], Top5Acc: 0.4771, Top10Acc: 0.7479, Acc: 0.0327, MacroF1: 0.0224
test [full], NDCG@5: 0.7685, HR@5: 0.9493, NDCG@10: 0.7856, HR@10: 0.9999, MRR: 0.7132
test [sampled], NDCG@5: 0.1912, HR@5: 0.2151, NDCG@10: 0.2443, HR@10: 0.3825, MRR: 0.2403
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=26, loss=0.0801
epoch=27, loss=0.0809
epoch=28, loss=0.0809
epoch=29, loss=0.0816
epoch=30, loss=0.0774
valid [task], Top5Acc: 0.4059, Top10Acc: 0.6233, Acc: 0.1378, MacroF1: 0.1432
valid [full], NDCG@5: 0.6930, HR@5: 0.8753, NDCG@10: 0.7237, HR@10: 0.9728, MRR: 0.6472
valid [sampled], NDCG@5: 0.4963, HR@5: 0.5028, NDCG@10: 0.5160, HR@10: 0.5648, MRR: 0.5197
test [task], Top5Acc: 0.4876, Top10Acc: 0.7390, Acc: 0.0310, MacroF1: 0.0242
test [full], NDCG@5: 0.8918, HR@5: 0.9640, NDCG@10: 0.9038, HR@10: 1.0000, MRR: 0.8726
test [sampled], NDCG@5: 0.3491, HR@5: 0.3902, NDCG@10: 0.4124, HR@10: 0.5861, MRR: 0.3838
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0805
epoch=32, loss=0.0776
epoch=33, loss=0.0795
epoch=34, loss=0.0768
epoch=35, loss=0.0767
valid [task], Top5Acc: 0.4044, Top10Acc: 0.6918, Acc: 0.1325, MacroF1: 0.1391
valid [full], NDCG@5: 0.7296, HR@5: 0.8825, NDCG@10: 0.7530, HR@10: 0.9596, MRR: 0.6909
valid [sampled], NDCG@5: 0.5621, HR@5: 0.5682, NDCG@10: 0.5783, HR@10: 0.6195, MRR: 0.5835
test [task], Top5Acc: 0.4789, Top10Acc: 0.6998, Acc: 0.0219, MacroF1: 0.0183
test [full], NDCG@5: 0.8739, HR@5: 0.9713, NDCG@10: 0.8839, HR@10: 1.0000, MRR: 0.8457
test [sampled], NDCG@5: 0.2441, HR@5: 0.2990, NDCG@10: 0.3213, HR@10: 0.5392, MRR: 0.2832
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_035.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=36, loss=0.0758
epoch=37, loss=0.0760
epoch=38, loss=0.0746
epoch=39, loss=0.0770
epoch=40, loss=0.0754
valid [task], Top5Acc: 0.3980, Top10Acc: 0.6120, Acc: 0.1340, MacroF1: 0.1412
valid [full], NDCG@5: 0.6857, HR@5: 0.8698, NDCG@10: 0.7178, HR@10: 0.9725, MRR: 0.6401
valid [sampled], NDCG@5: 0.4926, HR@5: 0.4955, NDCG@10: 0.5057, HR@10: 0.5371, MRR: 0.5160
test [task], Top5Acc: 0.4758, Top10Acc: 0.6442, Acc: 0.0265, MacroF1: 0.0200
test [full], NDCG@5: 0.8570, HR@5: 0.9460, NDCG@10: 0.8755, HR@10: 1.0000, MRR: 0.8348
test [sampled], NDCG@5: 0.2869, HR@5: 0.3340, NDCG@10: 0.3505, HR@10: 0.5316, MRR: 0.3226
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0751
epoch=42, loss=0.0758
epoch=43, loss=0.0759
epoch=44, loss=0.0750
epoch=45, loss=0.0759
valid [task], Top5Acc: 0.4065, Top10Acc: 0.6992, Acc: 0.1292, MacroF1: 0.1391
valid [full], NDCG@5: 0.7316, HR@5: 0.8945, NDCG@10: 0.7561, HR@10: 0.9736, MRR: 0.6899
valid [sampled], NDCG@5: 0.5626, HR@5: 0.5683, NDCG@10: 0.5805, HR@10: 0.6244, MRR: 0.5845
test [task], Top5Acc: 0.5035, Top10Acc: 0.7178, Acc: 0.0222, MacroF1: 0.0169
test [full], NDCG@5: 0.8958, HR@5: 0.9778, NDCG@10: 0.9037, HR@10: 1.0000, MRR: 0.8723
test [sampled], NDCG@5: 0.3745, HR@5: 0.4130, NDCG@10: 0.4260, HR@10: 0.5730, MRR: 0.4060
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/sasrec_best.pth
epoch=46, loss=0.0728
epoch=47, loss=0.0743
epoch=48, loss=0.0728
epoch=49, loss=0.0756
epoch=50, loss=0.0740
valid [task], Top5Acc: 0.3961, Top10Acc: 0.6966, Acc: 0.1324, MacroF1: 0.1235
valid [full], NDCG@5: 0.7262, HR@5: 0.8888, NDCG@10: 0.7488, HR@10: 0.9629, MRR: 0.6846
valid [sampled], NDCG@5: 0.5570, HR@5: 0.5636, NDCG@10: 0.5760, HR@10: 0.6234, MRR: 0.5784
test [task], Top5Acc: 0.4730, Top10Acc: 0.6724, Acc: 0.0344, MacroF1: 0.0226
test [full], NDCG@5: 0.8873, HR@5: 0.9498, NDCG@10: 0.9045, HR@10: 1.0000, MRR: 0.8738
test [sampled], NDCG@5: 0.3730, HR@5: 0.4124, NDCG@10: 0.4262, HR@10: 0.5776, MRR: 0.4047
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s42/sasrec_last.pth

### `timeaware_dstart_sinusoidal_ml50_do035_s2024`

In [18]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_sinusoidal_ml50_do035_s2024 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 2024 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024
epoch=1, loss=0.6154
epoch=2, loss=0.2754
epoch=3, loss=0.2018
epoch=4, loss=0.1644
epoch=5, loss=0.1434
valid [task], Top5Acc: 0.4804, Top10Acc: 0.6892, Acc: 0.0805, MacroF1: 0.1310
valid [full], NDCG@5: 0.6786, HR@5: 0.8288, NDCG@10: 0.7330, HR@10: 0.9928, MRR: 0.6547
valid [sampled], NDCG@5: 0.5575, HR@5: 0.5622, NDCG@10: 0.5655, HR@10: 0.5873, MRR: 0.5727
test [task], Top5Acc: 0.3819, Top10Acc: 0.7510, Acc: 0.0247, MacroF1: 0.0196
test [full], NDCG@5: 0.7566, HR@5: 0.8787, NDCG@10: 0.7970, HR@10: 1.0000, MRR: 0.7338
test [sampled], NDCG@5: 0.1369, HR@5: 0.1752, NDCG@10: 0.2071, HR@10: 0.3955, MRR: 0.1832
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/sasrec_best.pth
epoch=6, loss=0.1262
epoch=7, loss=0.1165
epoch=8, loss=0.1115
epoch=9, loss=0.1041
epoch=10, loss=0.1026
valid [task], Top5Acc: 0.4997, Top10Acc: 0.7267, Acc: 0.0724, MacroF1: 0.1162
valid [full], NDCG@5: 0.7004, HR@5: 0.8794, NDCG@10: 0.7291, HR@10: 0.9693, MRR: 0.6580
valid [sampled], NDCG@5: 0.5558, HR@5: 0.5604, NDCG@10: 0.5680, HR@10: 0.5984, MRR: 0.5728
test [task], Top5Acc: 0.3631, Top10Acc: 0.6663, Acc: 0.0159, MacroF1: 0.0143
test [full], NDCG@5: 0.8029, HR@5: 0.9211, NDCG@10: 0.8274, HR@10: 1.0000, MRR: 0.7737
test [sampled], NDCG@5: 0.1802, HR@5: 0.2233, NDCG@10: 0.2495, HR@10: 0.4405, MRR: 0.2225
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0992
epoch=12, loss=0.0959
epoch=13, loss=0.0940
epoch=14, loss=0.0892
epoch=15, loss=0.0902
valid [task], Top5Acc: 0.4932, Top10Acc: 0.6992, Acc: 0.1282, MacroF1: 0.1398
valid [full], NDCG@5: 0.6935, HR@5: 0.8489, NDCG@10: 0.7320, HR@10: 0.9699, MRR: 0.6618
valid [sampled], NDCG@5: 0.5595, HR@5: 0.5642, NDCG@10: 0.5709, HR@10: 0.5997, MRR: 0.5763
test [task], Top5Acc: 0.3508, Top10Acc: 0.6391, Acc: 0.0196, MacroF1: 0.0169
test [full], NDCG@5: 0.7169, HR@5: 0.9171, NDCG@10: 0.7432, HR@10: 1.0000, MRR: 0.6589
test [sampled], NDCG@5: 0.1482, HR@5: 0.1569, NDCG@10: 0.1952, HR@10: 0.3077, MRR: 0.2016
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0889
epoch=17, loss=0.0856
epoch=18, loss=0.0854
epoch=19, loss=0.0861
epoch=20, loss=0.0841
valid [task], Top5Acc: 0.4739, Top10Acc: 0.6805, Acc: 0.1403, MacroF1: 0.1438
valid [full], NDCG@5: 0.6475, HR@5: 0.7516, NDCG@10: 0.7110, HR@10: 0.9437, MRR: 0.6459
valid [sampled], NDCG@5: 0.5561, HR@5: 0.5611, NDCG@10: 0.5666, HR@10: 0.5938, MRR: 0.5705
test [task], Top5Acc: 0.4261, Top10Acc: 0.5293, Acc: 0.0311, MacroF1: 0.0276
test [full], NDCG@5: 0.7025, HR@5: 0.9064, NDCG@10: 0.7339, HR@10: 1.0000, MRR: 0.6465
test [sampled], NDCG@5: 0.1398, HR@5: 0.1610, NDCG@10: 0.1872, HR@10: 0.3107, MRR: 0.1874
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0817
epoch=22, loss=0.0806
epoch=23, loss=0.0803
epoch=24, loss=0.0816
epoch=25, loss=0.0818
valid [task], Top5Acc: 0.4649, Top10Acc: 0.6953, Acc: 0.1439, MacroF1: 0.1464
valid [full], NDCG@5: 0.6777, HR@5: 0.8183, NDCG@10: 0.7279, HR@10: 0.9715, MRR: 0.6562
valid [sampled], NDCG@5: 0.5573, HR@5: 0.5621, NDCG@10: 0.5675, HR@10: 0.5942, MRR: 0.5736
test [task], Top5Acc: 0.4441, Top10Acc: 0.6459, Acc: 0.0413, MacroF1: 0.0318
test [full], NDCG@5: 0.7031, HR@5: 0.9108, NDCG@10: 0.7339, HR@10: 0.9999, MRR: 0.6464
test [sampled], NDCG@5: 0.1504, HR@5: 0.1727, NDCG@10: 0.1948, HR@10: 0.3122, MRR: 0.1963
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0794
epoch=27, loss=0.0799
epoch=28, loss=0.0783
epoch=29, loss=0.0800
epoch=30, loss=0.0768
valid [task], Top5Acc: 0.4712, Top10Acc: 0.6893, Acc: 0.1259, MacroF1: 0.1186
valid [full], NDCG@5: 0.6890, HR@5: 0.8486, NDCG@10: 0.7260, HR@10: 0.9661, MRR: 0.6543
valid [sampled], NDCG@5: 0.5276, HR@5: 0.5321, NDCG@10: 0.5400, HR@10: 0.5709, MRR: 0.5475
test [task], Top5Acc: 0.5598, Top10Acc: 0.6242, Acc: 0.1107, MacroF1: 0.0457
test [full], NDCG@5: 0.7676, HR@5: 0.9127, NDCG@10: 0.7963, HR@10: 0.9978, MRR: 0.7304
test [sampled], NDCG@5: 0.2844, HR@5: 0.3005, NDCG@10: 0.3235, HR@10: 0.4244, MRR: 0.3255
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0774
epoch=32, loss=0.0775
epoch=33, loss=0.0766
epoch=34, loss=0.0768
epoch=35, loss=0.0759
valid [task], Top5Acc: 0.3949, Top10Acc: 0.7173, Acc: 0.1395, MacroF1: 0.1475
valid [full], NDCG@5: 0.6442, HR@5: 0.7745, NDCG@10: 0.7091, HR@10: 0.9703, MRR: 0.6325
valid [sampled], NDCG@5: 0.5255, HR@5: 0.5288, NDCG@10: 0.5337, HR@10: 0.5547, MRR: 0.5425
test [task], Top5Acc: 0.5434, Top10Acc: 0.6285, Acc: 0.1067, MacroF1: 0.0452
test [full], NDCG@5: 0.7280, HR@5: 0.8821, NDCG@10: 0.7676, HR@10: 1.0000, MRR: 0.6920
test [sampled], NDCG@5: 0.1992, HR@5: 0.2211, NDCG@10: 0.2510, HR@10: 0.3843, MRR: 0.2458
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0762
epoch=37, loss=0.0768
epoch=38, loss=0.0746
epoch=39, loss=0.0762
epoch=40, loss=0.0744
valid [task], Top5Acc: 0.3951, Top10Acc: 0.6402, Acc: 0.1327, MacroF1: 0.1123
valid [full], NDCG@5: 0.6509, HR@5: 0.8064, NDCG@10: 0.7014, HR@10: 0.9643, MRR: 0.6251
valid [sampled], NDCG@5: 0.5191, HR@5: 0.5217, NDCG@10: 0.5252, HR@10: 0.5405, MRR: 0.5354
test [task], Top5Acc: 0.3407, Top10Acc: 0.6627, Acc: 0.1194, MacroF1: 0.0505
test [full], NDCG@5: 0.7174, HR@5: 0.9114, NDCG@10: 0.7471, HR@10: 0.9995, MRR: 0.6682
test [sampled], NDCG@5: 0.3704, HR@5: 0.3715, NDCG@10: 0.3772, HR@10: 0.3935, MRR: 0.4002
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0749
epoch=42, loss=0.0770
epoch=43, loss=0.0749
epoch=44, loss=0.0736
epoch=45, loss=0.0745
valid [task], Top5Acc: 0.3934, Top10Acc: 0.6287, Acc: 0.1359, MacroF1: 0.1301
valid [full], NDCG@5: 0.6808, HR@5: 0.8580, NDCG@10: 0.7167, HR@10: 0.9697, MRR: 0.6416
valid [sampled], NDCG@5: 0.5275, HR@5: 0.5311, NDCG@10: 0.5375, HR@10: 0.5624, MRR: 0.5464
test [task], Top5Acc: 0.2599, Top10Acc: 0.6568, Acc: 0.1056, MacroF1: 0.0452
test [full], NDCG@5: 0.7256, HR@5: 0.9187, NDCG@10: 0.7535, HR@10: 0.9999, MRR: 0.6747
test [sampled], NDCG@5: 0.3199, HR@5: 0.3259, NDCG@10: 0.3384, HR@10: 0.3846, MRR: 0.3552
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0739
epoch=47, loss=0.0732
epoch=48, loss=0.0741
epoch=49, loss=0.0729
epoch=50, loss=0.0735
valid [task], Top5Acc: 0.3903, Top10Acc: 0.7229, Acc: 0.1211, MacroF1: 0.0963
valid [full], NDCG@5: 0.6921, HR@5: 0.8807, NDCG@10: 0.7216, HR@10: 0.9739, MRR: 0.6457
valid [sampled], NDCG@5: 0.5266, HR@5: 0.5305, NDCG@10: 0.5374, HR@10: 0.5645, MRR: 0.5462
test [task], Top5Acc: 0.5425, Top10Acc: 0.6927, Acc: 0.1111, MacroF1: 0.0463
test [full], NDCG@5: 0.7584, HR@5: 0.9228, NDCG@10: 0.7845, HR@10: 1.0000, MRR: 0.7141
test [sampled], NDCG@5: 0.2938, HR@5: 0.3058, NDCG@10: 0.3294, HR@10: 0.4192, MRR: 0.3347
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s2024/sasrec_last.pth

### `timeaware_dstart_sinusoidal_ml50_do035_s7`

In [19]:
!python src/train_sasrec.py \
  --run_name timeaware_dstart_sinusoidal_ml50_do035_s7 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.35 \
  --seed 7 \
  --use_time_embedding \
  --time_features_path data/processed/bpi2012_complete_only/events_encoded_time_features.csv \
  --time_delta_column delta_start_seconds \
  --time_encoding sinusoidal \
  --time_sinusoidal_base 10000 \
  --output_dir "$SINUSOIDAL_NDCG10_OUTPUT_DIR" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7
epoch=1, loss=0.5832
epoch=2, loss=0.2758
epoch=3, loss=0.2054
epoch=4, loss=0.1747
epoch=5, loss=0.1557
valid [task], Top5Acc: 0.4709, Top10Acc: 0.7359, Acc: 0.0782, MacroF1: 0.1197
valid [full], NDCG@5: 0.6339, HR@5: 0.7392, NDCG@10: 0.6854, HR@10: 0.9030, MRR: 0.6290
valid [sampled], NDCG@5: 0.5418, HR@5: 0.5435, NDCG@10: 0.5479, HR@10: 0.5627, MRR: 0.5569
test [task], Top5Acc: 0.0903, Top10Acc: 0.5773, Acc: 0.0449, MacroF1: 0.0326
test [full], NDCG@5: 0.5646, HR@5: 0.7624, NDCG@10: 0.6104, HR@10: 0.9025, MRR: 0.5269
test [sampled], NDCG@5: 0.1810, HR@5: 0.1819, NDCG@10: 0.1878, HR@10: 0.2042, MRR: 0.2175
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=6, loss=0.1350
epoch=7, loss=0.1236
epoch=8, loss=0.1127
epoch=9, loss=0.1077
epoch=10, loss=0.1040
valid [task], Top5Acc: 0.4933, Top10Acc: 0.7093, Acc: 0.0607, MacroF1: 0.0689
valid [full], NDCG@5: 0.6573, HR@5: 0.7703, NDCG@10: 0.7158, HR@10: 0.9558, MRR: 0.6475
valid [sampled], NDCG@5: 0.5511, HR@5: 0.5560, NDCG@10: 0.5640, HR@10: 0.5966, MRR: 0.5676
test [task], Top5Acc: 0.3439, Top10Acc: 0.7246, Acc: 0.0258, MacroF1: 0.0220
test [full], NDCG@5: 0.6847, HR@5: 0.9234, NDCG@10: 0.7100, HR@10: 1.0000, MRR: 0.6141
test [sampled], NDCG@5: 0.1604, HR@5: 0.1642, NDCG@10: 0.1923, HR@10: 0.2672, MRR: 0.2119
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=11, loss=0.0994
epoch=12, loss=0.0964
epoch=13, loss=0.0941
epoch=14, loss=0.0911
epoch=15, loss=0.0894
valid [task], Top5Acc: 0.4986, Top10Acc: 0.6840, Acc: 0.0738, MacroF1: 0.1018
valid [full], NDCG@5: 0.6647, HR@5: 0.7857, NDCG@10: 0.7238, HR@10: 0.9700, MRR: 0.6526
valid [sampled], NDCG@5: 0.5595, HR@5: 0.5624, NDCG@10: 0.5678, HR@10: 0.5884, MRR: 0.5753
test [task], Top5Acc: 0.4666, Top10Acc: 0.7034, Acc: 0.0413, MacroF1: 0.0289
test [full], NDCG@5: 0.7412, HR@5: 0.9619, NDCG@10: 0.7547, HR@10: 1.0000, MRR: 0.6713
test [sampled], NDCG@5: 0.1346, HR@5: 0.1392, NDCG@10: 0.1838, HR@10: 0.2974, MRR: 0.1950
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=16, loss=0.0897
epoch=17, loss=0.0864
epoch=18, loss=0.0849
epoch=19, loss=0.0847
epoch=20, loss=0.0833
valid [task], Top5Acc: 0.4878, Top10Acc: 0.6757, Acc: 0.1744, MacroF1: 0.1525
valid [full], NDCG@5: 0.6535, HR@5: 0.7636, NDCG@10: 0.7173, HR@10: 0.9654, MRR: 0.6467
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5607, NDCG@10: 0.5652, HR@10: 0.5830, MRR: 0.5732
test [task], Top5Acc: 0.5153, Top10Acc: 0.6723, Acc: 0.0714, MacroF1: 0.0381
test [full], NDCG@5: 0.7846, HR@5: 0.9660, NDCG@10: 0.7963, HR@10: 1.0000, MRR: 0.7272
test [sampled], NDCG@5: 0.1841, HR@5: 0.1999, NDCG@10: 0.2384, HR@10: 0.3725, MRR: 0.2388
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0821
epoch=22, loss=0.0812
epoch=23, loss=0.0809
epoch=24, loss=0.0821
epoch=25, loss=0.0774
valid [task], Top5Acc: 0.4932, Top10Acc: 0.6773, Acc: 0.1865, MacroF1: 0.2016
valid [full], NDCG@5: 0.7047, HR@5: 0.8553, NDCG@10: 0.7341, HR@10: 0.9527, MRR: 0.6706
valid [sampled], NDCG@5: 0.5605, HR@5: 0.5663, NDCG@10: 0.5752, HR@10: 0.6126, MRR: 0.5788
test [task], Top5Acc: 0.5222, Top10Acc: 0.6880, Acc: 0.1444, MacroF1: 0.0624
test [full], NDCG@5: 0.8919, HR@5: 0.9977, NDCG@10: 0.8927, HR@10: 1.0000, MRR: 0.8555
test [sampled], NDCG@5: 0.2923, HR@5: 0.3374, NDCG@10: 0.3585, HR@10: 0.5430, MRR: 0.3320
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/sasrec_best.pth
epoch=26, loss=0.0801
epoch=27, loss=0.0788
epoch=28, loss=0.0774
epoch=29, loss=0.0783
epoch=30, loss=0.0762
valid [task], Top5Acc: 0.4794, Top10Acc: 0.6593, Acc: 0.2343, MacroF1: 0.2213
valid [full], NDCG@5: 0.6629, HR@5: 0.7911, NDCG@10: 0.7091, HR@10: 0.9337, MRR: 0.6467
valid [sampled], NDCG@5: 0.5531, HR@5: 0.5570, NDCG@10: 0.5637, HR@10: 0.5904, MRR: 0.5686
test [task], Top5Acc: 0.5279, Top10Acc: 0.6424, Acc: 0.1618, MacroF1: 0.1166
test [full], NDCG@5: 0.9042, HR@5: 0.9981, NDCG@10: 0.9049, HR@10: 1.0000, MRR: 0.8729
test [sampled], NDCG@5: 0.2993, HR@5: 0.3418, NDCG@10: 0.3690, HR@10: 0.5596, MRR: 0.3404
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0770
epoch=32, loss=0.0777
epoch=33, loss=0.0762
epoch=34, loss=0.0753
epoch=35, loss=0.0766
valid [task], Top5Acc: 0.4788, Top10Acc: 0.6748, Acc: 0.1733, MacroF1: 0.1380
valid [full], NDCG@5: 0.6961, HR@5: 0.8401, NDCG@10: 0.7313, HR@10: 0.9545, MRR: 0.6661
valid [sampled], NDCG@5: 0.5499, HR@5: 0.5542, NDCG@10: 0.5649, HR@10: 0.6015, MRR: 0.5694
test [task], Top5Acc: 0.5207, Top10Acc: 0.6270, Acc: 0.1770, MacroF1: 0.0776
test [full], NDCG@5: 0.9341, HR@5: 0.9984, NDCG@10: 0.9347, HR@10: 1.0000, MRR: 0.9121
test [sampled], NDCG@5: 0.3827, HR@5: 0.4230, NDCG@10: 0.4476, HR@10: 0.6251, MRR: 0.4193
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0770
epoch=37, loss=0.0759
epoch=38, loss=0.0757
epoch=39, loss=0.0750
epoch=40, loss=0.0741
valid [task], Top5Acc: 0.4973, Top10Acc: 0.6856, Acc: 0.1818, MacroF1: 0.1519
valid [full], NDCG@5: 0.6925, HR@5: 0.8494, NDCG@10: 0.7197, HR@10: 0.9373, MRR: 0.6561
valid [sampled], NDCG@5: 0.5172, HR@5: 0.5248, NDCG@10: 0.5366, HR@10: 0.5854, MRR: 0.5388
test [task], Top5Acc: 0.5207, Top10Acc: 0.6874, Acc: 0.2419, MacroF1: 0.0733
test [full], NDCG@5: 0.9436, HR@5: 0.9992, NDCG@10: 0.9439, HR@10: 1.0000, MRR: 0.9242
test [sampled], NDCG@5: 0.3764, HR@5: 0.4191, NDCG@10: 0.4438, HR@10: 0.6299, MRR: 0.4129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0777
epoch=42, loss=0.0754
epoch=43, loss=0.0748
epoch=44, loss=0.0744
epoch=45, loss=0.0733
valid [task], Top5Acc: 0.4860, Top10Acc: 0.6486, Acc: 0.2395, MacroF1: 0.2244
valid [full], NDCG@5: 0.6870, HR@5: 0.8073, NDCG@10: 0.7257, HR@10: 0.9301, MRR: 0.6685
valid [sampled], NDCG@5: 0.5612, HR@5: 0.5676, NDCG@10: 0.5774, HR@10: 0.6187, MRR: 0.5784
test [task], Top5Acc: 0.4895, Top10Acc: 0.5730, Acc: 0.2336, MacroF1: 0.0695
test [full], NDCG@5: 0.9228, HR@5: 0.9947, NDCG@10: 0.9246, HR@10: 1.0000, MRR: 0.8992
test [sampled], NDCG@5: 0.3263, HR@5: 0.3669, NDCG@10: 0.3969, HR@10: 0.5876, MRR: 0.3657
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0723
epoch=47, loss=0.0735
epoch=48, loss=0.0726
epoch=49, loss=0.0739
epoch=50, loss=0.0724
valid [task], Top5Acc: 0.4795, Top10Acc: 0.6848, Acc: 0.2180, MacroF1: 0.1681
valid [full], NDCG@5: 0.6939, HR@5: 0.8382, NDCG@10: 0.7234, HR@10: 0.9307, MRR: 0.6643
valid [sampled], NDCG@5: 0.5554, HR@5: 0.5600, NDCG@10: 0.5661, HR@10: 0.5936, MRR: 0.5731
test [task], Top5Acc: 0.5147, Top10Acc: 0.6324, Acc: 0.2642, MacroF1: 0.1338
test [full], NDCG@5: 0.9428, HR@5: 0.9981, NDCG@10: 0.9434, HR@10: 1.0000, MRR: 0.9242
test [sampled], NDCG@5: 0.3792, HR@5: 0.4221, NDCG@10: 0.4414, HR@10: 0.6163, MRR: 0.4143
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_sinusoidal_ndcg10/timeaware_dstart_sinusoidal_ml50_do035_s7/sasrec_last.pth

## Rebuild result tables

This notebook reads result folders directly from `metrics_summary.json`.
Older Stage 2 runs may not contain all task metrics; in that case the corresponding cells appear as `NaN`.

In [20]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df_from_dirs(output_dirs):
    rows = []
    seen_runs = set()
    for output_dir in output_dirs:
        output_path = Path(output_dir)
        if not output_path.exists():
            continue
        for run_dir in output_path.iterdir():
            if not run_dir.is_dir() or run_dir.name in seen_runs:
                continue
            summary_path = run_dir / 'metrics_summary.json'
            config_path = run_dir / 'config.json'
            if not summary_path.exists() or not config_path.exists():
                continue
            summary = json.loads(summary_path.read_text(encoding='utf-8'))
            config = json.loads(config_path.read_text(encoding='utf-8'))
            row = {
                'run_name': summary.get('run_name'),
                'source_output_dir': str(output_path),
                'run_dir': str(run_dir),
                'completed_at': summary.get('completed_at'),
                'best_epoch': summary.get('best_epoch'),
                'checkpoint_best': summary.get('checkpoint_best'),
                'checkpoint_last': summary.get('checkpoint_last'),
                'metrics_history': summary.get('metrics_history'),
                'config_path': str(config_path),
                'metrics_summary': str(summary_path),
                'maxlen': config.get('maxlen'),
                'dropout_rate': config.get('dropout_rate'),
                'hidden_units': config.get('hidden_units'),
                'seed': config.get('seed'),
                'selection_metric': config.get('selection_metric'),
                'use_time_embedding': config.get('use_time_embedding', False),
                'use_time_attention_bias': config.get('use_time_attention_bias', False),
                'time_modeling_mode': config.get('time_modeling_mode'),
                'time_encoding': config.get('time_encoding'),
                'time_delta_column': config.get('time_delta_column'),
                'time_bucket_boundaries_parsed': config.get('time_bucket_boundaries_parsed'),
                'time_attention_bias_bucket_count': config.get('time_attention_bias_bucket_count'),
                'time_sinusoidal_base': config.get('time_sinusoidal_base'),
            }
            for group_name in ['best_valid', 'best_test_at_best_valid', 'last_valid', 'last_test']:
                group = summary.get(group_name) or {}
                for mode, metrics in group.items():
                    for key, value in metrics.items():
                        row[f'{group_name}_{mode}_{key}'] = value
            rows.append(row)
            seen_runs.add(run_dir.name)
    return pd.DataFrame(rows)

In [21]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_colwidth', None)

## Comparison summary

In [22]:
scan_dirs = [
    BASELINE_NDCG10_OUTPUT_DIR,
    ANCHOR_BUCKET_NDCG10_OUTPUT_DIR,
    REFINE_BUCKET_NDCG10_OUTPUT_DIR,
    REFINE_DSTART_BUCKET_NDCG10_OUTPUT_DIR,
    REFINE_DSTART_CONT_NDCG10_OUTPUT_DIR,
    ANCHOR_ATTN_NDCG10_OUTPUT_DIR,
    REFINE_ATTN_NDCG10_OUTPUT_DIR,
    SINUSOIDAL_NDCG10_OUTPUT_DIR,
]

run_to_variant = {}
for run_name in ['anchor_ml20_s42', 'anchor_ml20_s2024', 'anchor_ml20_s7']:
    run_to_variant[run_name] = 'anchor_baseline'
for run_name in ['timeaware_anchor_ml20_b9_s42', 'timeaware_anchor_ml20_b9_s2024', 'timeaware_anchor_ml20_b9_s7']:
    run_to_variant[run_name] = 'anchor_bucket_b9'
for run_name in ['attnbias_dstart_ml20_b9_s42', 'attnbias_dstart_ml20_b9_s2024', 'attnbias_dstart_ml20_b9_s7']:
    run_to_variant[run_name] = 'anchor_attnbias_dstart_b9'
for run_name in ['timeaware_dprev_sinusoidal_ml20_s42', 'timeaware_dprev_sinusoidal_ml20_s2024', 'timeaware_dprev_sinusoidal_ml20_s7']:
    run_to_variant[run_name] = 'anchor_sinusoidal_dprev'
for run_name in ['timeaware_dstart_sinusoidal_ml20_s42', 'timeaware_dstart_sinusoidal_ml20_s2024', 'timeaware_dstart_sinusoidal_ml20_s7']:
    run_to_variant[run_name] = 'anchor_sinusoidal_dstart'

for run_name in ['refine_ml50_do035_s42', 'refine_ml50_do035_s2024', 'refine_ml50_do035_s7']:
    run_to_variant[run_name] = 'refine_baseline'
for run_name in ['timeaware_refine_ml50_do035_b9_s42', 'timeaware_refine_ml50_do035_b9_s2024', 'timeaware_refine_ml50_do035_b9_s7']:
    run_to_variant[run_name] = 'refine_bucket_b9'
for run_name in ['timeaware_dstart_refine_ml50_do035_b9_s42', 'timeaware_dstart_refine_ml50_do035_b9_s2024', 'timeaware_dstart_refine_ml50_do035_b9_s7']:
    run_to_variant[run_name] = 'refine_dstart_bucket_b9'
for run_name in ['timeaware_dstart_conti_refine_ml50_do035_s42', 'timeaware_dstart_conti_refine_ml50_do035_s2024', 'timeaware_dstart_conti_refine_ml50_do035_s7']:
    run_to_variant[run_name] = 'refine_dstart_continuous'
for run_name in ['attnbias_dstart_ml50_do035_b9_s42', 'attnbias_dstart_ml50_do035_b9_s2024', 'attnbias_dstart_ml50_do035_b9_s7']:
    run_to_variant[run_name] = 'refine_attnbias_dstart_b9'
for run_name in ['timeaware_dprev_sinusoidal_ml50_do035_s42', 'timeaware_dprev_sinusoidal_ml50_do035_s2024', 'timeaware_dprev_sinusoidal_ml50_do035_s7']:
    run_to_variant[run_name] = 'refine_sinusoidal_dprev'
for run_name in ['timeaware_dstart_sinusoidal_ml50_do035_s42', 'timeaware_dstart_sinusoidal_ml50_do035_s2024', 'timeaware_dstart_sinusoidal_ml50_do035_s7']:
    run_to_variant[run_name] = 'refine_sinusoidal_dstart'

df_all = rebuild_df_from_dirs(scan_dirs)
df_compare = df_all[df_all['run_name'].isin(run_to_variant)].copy()
df_compare['variant'] = df_compare['run_name'].map(run_to_variant)
df_compare = df_compare.sort_values(['variant', 'seed', 'run_name']).reset_index(drop=True)

display_cols = [
    'run_name', 'seed', 'variant', 'maxlen', 'dropout_rate', 'selection_metric',
    'time_modeling_mode', 'time_encoding', 'time_delta_column', 'time_attention_bias_bucket_count', 'time_sinusoidal_base',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10', 'best_valid_full_ndcg@5', 'best_valid_full_hr@5', 'best_valid_full_mrr',
    'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10', 'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5', 'best_test_at_best_valid_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10', 'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5', 'best_valid_sampled_mrr',
    'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10', 'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5', 'best_test_at_best_valid_sampled_mrr',
    'best_valid_task_accuracy', 'best_valid_task_macro_f1', 'best_valid_task_top5_accuracy', 'best_valid_task_top10_accuracy',
    'best_test_at_best_valid_task_accuracy', 'best_test_at_best_valid_task_macro_f1', 'best_test_at_best_valid_task_top5_accuracy', 'best_test_at_best_valid_task_top10_accuracy',
]
existing_display_cols = [c for c in display_cols if c in df_compare.columns]
df_compare[existing_display_cols]

                                          run_name  seed                    variant  maxlen  dropout_rate    selection_metric time_modeling_mode time_encoding    time_delta_column  time_attention_bias_bucket_count  time_sinusoidal_base  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_at_best_valid_full_ndcg@10  best_test_at_best_valid_full_hr@10  best_test_at_best_valid_full_ndcg@5  best_test_at_best_valid_full_hr@5  best_test_at_best_valid_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_at_best_valid_sampled_ndcg@10  best_test_at_best_valid_sampled_hr@10  best_test_at_best_valid_sampled_ndcg@5  best_test_at_best_valid_sampled_hr@5  best_test_at_best_valid_sampled_mrr  best_valid_task_accuracy  best_valid_task_macro_f1  best_valid_task_top5_accuracy  best_valid_task_top10_accuracy  best_test_at_best_valid_task_accuracy  best_test_at_best_valid_task_macro_f1  best_test_at_best_valid_task_top5_accuracy  best_test_at_best_valid_task_top10_accuracy
0                       attnbias_dstart_ml20_b9_s7     7  anchor_attnbias_dstart_b9      20          0.20  full_valid_ndcg@10     attention_bias           raw  delta_start_seconds                               7.0                   NaN                 0.731681               0.933234                0.694816              0.812322             0.674079                              0.833933                            1.000000                             0.833460                           0.998642                          0.776636                    0.584594                  0.673558                   0.550907                 0.567329                0.571303                                 0.408188                               0.553189                                0.349894                              0.366486                             0.395330                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
1                      attnbias_dstart_ml20_b9_s42    42  anchor_attnbias_dstart_b9      20          0.20  full_valid_ndcg@10     attention_bias           raw  delta_start_seconds                               7.0                   NaN                 0.731547               0.976377                0.692852              0.854887             0.657784                              0.857427                            1.000000                             0.844950                           0.958941                          0.810092                    0.553607                  0.600217                   0.535631                 0.543183                0.557929                                 0.535711                               0.621374                                0.504964                              0.524491                             0.530831                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
2                    attnbias_dstart_ml20_b9_s2024  2024  anchor_attnbias_dstart_b9      20          0.20  full_valid_ndcg@10     attention_bias           raw  delta_start_seconds                               7.0                   NaN                 0.727796               0.977380                0.682637              0.839902             0.653203                              0.815191                            1.000000                             0.800095                           0.953875                          0.753665                    0.551441                  0.581497                   0.539500                 0.543537                0.560101                                 0.369433                               0.517223                                0.311595                              0.332384                             0.355765                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
3                                   anchor_ml20_s7     7            anchor_baseline      20          0.20  full_valid_ndcg@10                NaN           NaN   delta_prev_seconds                               NaN                   NaN                 0.753294               0.961857                0.729167              0.883942             0.691225                              0.913637                            1.000000                             0.903861                           0.971918                          0.885501                    0.601240                  0.661113                   0.580044                 0.594609                0.597937                                 0.480200                               0.667438                                0.420861                              0.484209                             0.443705                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
4                                  anchor_ml20_s42    42            anchor_baseline      20          0.20  full_valid_ndcg@10                NaN           NaN   delta_prev_seconds                               NaN                   NaN                 0.750367               0.977546                0.708784              0.848505             0.681799                              0.915296                            1.000000                             0.913814                           0.995781                          0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                                 0.464891                               0.652470                                0.406641                              0.473262                             0.430220                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
5                                anchor_ml20_s2024  2024            anchor_baseline      20          0.20  full_valid_ndcg@10                NaN           NaN   delta_prev_seconds                               NaN                   NaN                 0.736821               0.967429                0.700301              0.850202             0.668534                              0.840611                            0.999865                             0.819421                           0.937829                          0.789072                    0.574314                  0.616064                   0.557801                 0.563197                0.578608                                 0.323103                               0.518524                                0.261120                              0.326822                             0.292464                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
6                      timeaware_anchor_ml20_b9_s7     7           anchor_bucket_b9      20          0.20  full_valid_ndcg@10                NaN           NaN   delta_prev_seconds                               NaN                   NaN                 0.743844               0.960530                0.714598              0.867397             0.678884                              0.843990                            1.000000                             0.834025                           0.971564                          0.790520                    0.582482                  0.666984                   0.550773                 0.566848                0.573250                                 0.386793                               0.556218                                0.322537                              0.352208                             0.366348                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
7                     timeaware_anchor_ml20_b9_s42    42           anchor_bucket_b9      20          0.20  full_valid_ndcg@10                NaN           NaN   delta_prev_seconds                               NaN                   NaN                 0.715128               0.981350                0.642260              0.750340             0.638622                              0.813155                            1.000000                             0.778245                           0.893199                          0.753896                    0.565702                  0.581509                   0.559273                 0.560707                0.575554                                 0.269814                               0.520394                                0.187604                              0.266343                             0.220679                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
8                   timeaware_anchor_ml20_b9_s2024  2024           anchor_bucket_b9      20          0.20  full_valid_ndcg@10                NaN           NaN   delta_prev_seconds                               NaN                   NaN                 0.724989               0.975136                0.655030              0.761685             0.651891                              0.810350                            1.000000                             0.777245                           0.897405                          0.749042                    0.572362                  0.618261                   0.556768                 0.569764                0.571922                                 0.426353                               0.538939                                0.380476                              0.391281                             0.420197                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN
9               timeaware_dprev_sinusoidal_ml20_s7     7    anchor_sinusoidal_dprev      20          0.20  full_valid_ndcg@10    input_embedding    sinusoidal   delta_prev_seconds                               0.0               10000.0                 0.751616               0.974362                0.717256              0.862995             0.684983                              0.819125                            1.000000                             0.818127                           0.997148                          0.756838                    0.587517                  0.623983                   0.573241                 0.579083                0.591865                                 0.461806                               0.613609                                0.409177                              0.449952                             0.438701                  0.175800                  0.200631                       0.499593                        0.781742                               0.030558                               0.021004                                    0.478066                                     0.722260
10             timeaware_dprev_sinusoidal_ml20_s42    42    anchor_sinusoidal_dprev      20          0.20  full_valid_ndcg@10    input_embedding    sinusoidal   delta_prev_seconds                               0.0               10000.0                 0.755029               0.977147                0.723441              0.875456             0.686909                              0.805627                            1.000000                             0.804110                           0.995672                          0.740104                    0.571862                  0.621366                   0.551918                 0.558485                0.574735                                 0.407194                               0.492967                                0.376130                              0.395862                             0.410306                  0.128871                  0.147626                       0.379446                        0.678161                               0.074790                               0.030949                                    0.393427                                     0.633216
11           timeaware_dprev_sinusoidal_ml20_s2024  2024    anchor_sinusoidal_dprev      20          0.20  full_valid_ndcg@10    input_embedding    sinusoidal   delta_prev_seconds                               0.0               10000.0                 0.745706               0.971947                0.700253              0.828974             0.678638                              0.798123                            1.000000                             0.774026                           0.921377                          0.731389                    0.579171                  0.620545                   0.562275                 0.567828                0.581723                                 0.248156                               0.395147                                0.193843                              0.224481                             0.240353                  0.146768                  0.193653                       0.480553                        0.653612                               0.043107                               0.028275                                    0.412905                                     0.677647
12             timeaware_dstart_sinusoidal_ml20_s7     7   anchor_sinusoidal_dstart      20          0.20  full_valid_ndcg@10    input_embedding    sinusoidal  delta_start_seconds                               0.0               10000.0                 0.728221               0.963352                0.691475              0.845190             0.659116                              0.899217                            1.000000                             0.882071                           0.949729                          0.866955                    0.561074                  0.599299                   0.545794                 0.551199                0.564547                                 0.407188                               0.586856                                0.345341                              0.394715                             0.376123                  0.114929                  0.167583                       0.391000                        0.628672                               0.084959                               0.046344                                    0.482114                                     0.672900
13            timeaware_dstart_sinusoidal_ml20_s42    42   anchor_sinusoidal_dstart      20          0.20  full_valid_ndcg@10    input_embedding    sinusoidal  delta_start_seconds                               0.0               10000.0                 0.756991               0.975464                0.723345              0.868510             0.690472                              0.798115                            1.000000                             0.789162                           0.974850                          0.730951                    0.582383                  0.631151                   0.562789                 0.569337                0.584593                                 0.370153                               0.410413                                0.354467                              0.360522                             0.391122                  0.125119                  0.151536                       0.503999                        0.743121                               0.048260                               0.021949                                    0.358755                                     0.726210
14          timeaware_dstart_sinusoidal_ml20_s2024  2024   anchor_sinusoidal_dstart      20          0.20  full_valid_ndcg@10    input_embedding    sinusoidal  delta_start_seconds                               0.0               10000.0                 0.731533               0.964629                0.666228              0.762976             0.663942                              0.798868                            0.999864                             0.778566                           0.939271                          0.731661                    0.569963                  0.608619                   0.554477                 0.560374                0.572089                                 0.297029                               0.424156                                0.249107                              0.273417                             0.292730                  0.135791                  0.149232                       0.403849                        0.627727                               0.035109                               0.028287                                    0.438932                                     0.638200
15                attnbias_dstart_ml50_do035_b9_s7     7  refine_attnbias_dstart_b9      50          0.35  full_valid_ndcg@10     attention_bias           raw  delta_start_seconds                               7.0                   NaN                 0.755366               0.953861                0.714870              0.824671             0.699184                              0.846762                            1.000000                             0.846665                           0.999728                          0.793978                    0.623265                  0.666077                   0.607399                 0.615479                0.623619                                 0.497216                               0.628223                                0.442098                              0.450204                             0.485290                       NaN                       NaN                            NaN                             NaN                                    NaN                                    NaN                                         NaN                                          NaN

In [23]:
summary_metric_cols = [
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10', 'best_valid_full_ndcg@5', 'best_valid_full_hr@5', 'best_valid_full_mrr',
    'best_test_at_best_valid_full_ndcg@10', 'best_test_at_best_valid_full_hr@10', 'best_test_at_best_valid_full_ndcg@5', 'best_test_at_best_valid_full_hr@5', 'best_test_at_best_valid_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10', 'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5', 'best_valid_sampled_mrr',
    'best_test_at_best_valid_sampled_ndcg@10', 'best_test_at_best_valid_sampled_hr@10', 'best_test_at_best_valid_sampled_ndcg@5', 'best_test_at_best_valid_sampled_hr@5', 'best_test_at_best_valid_sampled_mrr',
    'best_valid_task_accuracy', 'best_valid_task_macro_f1', 'best_valid_task_top5_accuracy', 'best_valid_task_top10_accuracy',
    'best_test_at_best_valid_task_accuracy', 'best_test_at_best_valid_task_macro_f1', 'best_test_at_best_valid_task_top5_accuracy', 'best_test_at_best_valid_task_top10_accuracy',
]
summary_metric_cols = [c for c in summary_metric_cols if c in df_compare.columns]
summary_compare = df_compare.groupby('variant')[summary_metric_cols].agg(['mean', 'std'])
summary_compare

                          best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_at_best_valid_full_ndcg@10           best_test_at_best_valid_full_hr@10           best_test_at_best_valid_full_ndcg@5           best_test_at_best_valid_full_hr@5           best_test_at_best_valid_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_at_best_valid_sampled_ndcg@10           best_test_at_best_valid_sampled_hr@10           best_test_at_best_valid_sampled_ndcg@5           best_test_at_best_valid_sampled_hr@5           best_test_at_best_valid_sampled_mrr           best_valid_task_accuracy           best_valid_task_macro_f1           best_valid_task_top5_accuracy           best_valid_task_top10_accuracy           best_test_at_best_valid_task_accuracy           best_test_at_best_valid_task_macro_f1           best_test_at_best_valid_task_top5_accuracy           best_test_at_best_valid_task_top10_accuracy
                                             mean       std                  mean       std                   mean       std                 mean       std                mean       std                                 mean       std                               mean       std                                mean       std                              mean       std                             mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                                    mean       std                                  mean       std                                   mean       std                                 mean       std                                mean       std                     mean       std                     mean       std                          mean       std                           mean       std                                  mean       std                                  mean       std                                       mean       std                                        mean       std
variant
anchor_attnbias_dstart_b9                0.730341  0.002206              0.962330  0.025203               0.690102  0.006539             0.835704  0.021591            0.661689  0.010972                             0.835517  0.021162                           1.000000  0.000000                            0.826168  0.023299                          0.970486  0.024515                         0.780131  0.028375                   0.563214  0.018547                 0.618424  0.048656                  0.542013  0.007942                0.551350  0.013839               0.563111  0.007177                                0.437777  0.086999                              0.563928  0.052900                               0.388818  0.102392                             0.407787  0.102497                            0.427309  0.091809                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
anchor_baseline                          0.746827  0.008788              0.968944  0.007954               0.712751  0.014836             0.860883  0.019988            0.680520  0.011400                             0.889848  0.042649                           0.999955  0.000078                            0.879032  0.051864                          0.968510  0.029126                         0.853805  0.056064                   0.586415  0.013668                 0.643839  0.024291                  0.564734  0.013279                0.575209  0.016959               0.584993  0.011211                                0.422731  0.086620                              0.612810  0.081997                               0.362874  0.088408                             0.428098  0.087878                            0.388797  0.083699                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
anchor_bucket_b9                         0.727987  0.014591              0.972339  0.010688               0.670629  0.038609             0.793141  0.064557            0.656466  0.020517                             0.822498  0.018665                           1.000000  0.000000                            0.796505  0.032497                          0.920722  0.044080                         0.764486  0.022676                   0.573515  0.008449                 0.622251  0.042877                  0.555605  0.004368                0.565773  0.004623               0.573575  0.001837                                0.360987  0.081398                              0.538517  0.017915                               0.296873  0.098964                             0.336610  0.063913                            0.335741  0.103220                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
anchor_sinusoidal_dprev                  0.750784  0.004717              0.974486  0.002602               0.713650  0.012007             0.855809  0.024060            0.683510  0.004328                             0.807625  0.010643                           1.000000  0.000000                            0.798754  0.022533                          0.971399  0.043326                         0.742777  0.012933                   0.579517  0.007833                 0.621964  0.001795                  0.562478  0.010663                0.568465  0.010314               0.582774  0.008613                                0.372385  0.110997                              0.500574  0.109429                               0.326383  0.115967                             0.356765  0.117710                            0.363120  0.107263                 0.150480  0.023684                 0.180637  0.028800                      0.453197  0.064576                       0.704505  0.068006                              0.049485  0.022795                              0.026743  0.005146                                   0.428133  0.044327                                    0.677708  0.044522
anchor_sinusoidal_dstart                 0.738915  0.015742              0.967815  0.006655               0.693683  0.028622             0.825559  0.055438            0.671177  0.016884                             0.832067  0.058155                           0.999955  0.000078                            0.816600  0.056946                          0.954617  0.018287                         0.776522  0.078318                   0.571140  0.010704                 0.613023  0.016376                  0.554353  0.008498                0.560303  0.009069               0.573743  0.010125                                0.358123  0.056056                              0.473809  0.098143                               0.316305  0.058374                             0.342885  0.062543                            0.353325  0.053010                 0.125279  0.010432                 0.156117  0.009996                      0.432949  0.061865                       0.666506  0.066351                              0.056109  0.025835                              0.032193  0.012658                                   0.426600  0.062597                                    0.679103  0.044332
refine_attnbias_dstart_b9                0.744203  0.010195              0.965029  0.009710               0.709133  0.005965             0.851471  0.023212            0.679333  0.017740                             0.839408  0.050411                           0.999910  0.000078                            0.825099  0.052996                          0.954562  0.039294                         0.786607  0.068359                   0.591495  0.029073                 0.638194  0.026835                  0.574292  0.029980                0.583899  0.029073               0.592467  0.028226                                0.374879  0.155906                              0.569344  0.100310                               0.307988  0.170739                             0.360101  0.144087                            0.343357  0.168872                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
refine_baseline                          0.735259  0.006374              0.977329  0.015618               0.702263  0.009451             0.872599  0.029271            0.662771  0.002053                             0.846684  0.062093                           1.000000  0.000000                            0.818405  0.078916                          0.911416  0.055280                         0.798923  0.080599                   0.572973  0.004280                 0.604843  0.007136                  0.561597  0.005491                0.569159  0.005422               0.579235  0.005635                                0.372338  0.102528                              0.576445  0.125558                               0.309277  0.098875                             0.383139  0.105721                            0.333054  0.093175                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
refine_bucket_b9                         0.741707  0.011182              0.968320  0.006786               0.700432  0.013283             0.840577  0.024796            0.674298  0.016822                             0.797676  0.042353                           0.999910  0.000078                            0.787847  0.048702                          0.969544  0.026606                         0.729855  0.057859                   0.587637  0.026733                 0.645532  0.033770                  0.566616  0.026614                0.579471  0.027365               0.585168  0.024215                                0.354119  0.108046                              0.501061  0.063059                               0.296945  0.125257                             0.319156  0.118954                            0.342198  0.116397                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
refine_dstart_bucket_b9                  0.742250  0.012434              0.964964  0.007577               0.706999  0.021928             0.853072  0.028483            0.676078  0.014548                             0.801553  0.127464                           0.999955  0.000078                            0.791544  0.133376                          0.968741  0.026958                         0.734975  0.170173                   0.590587  0.002189                 0.660978  0.024416                  0.564202  0.007655                0.577707  0.006035               0.584164  0.004340                                0.326371  0.129175                              0.493685  0.164566                               0.263805  0.122993                             0.295516  0.146806                            0.308148  0.111710                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
refine_dstart_continuous                 0.737725  0.005182              0.969157  0.003477               0.702464  0.005768             0.857340  0.030130            0.668912  0.007834                             0.718641  0.060612                           0.999955  0.000078                            0.706706  0.049067                          0.961978  0.038866                         0.624968  0.083115                   0.584440  0.015447                 0.637234  0.032556                  0.564796  0.012382                0.575411  0.014312               0.583792  0.011227                                0.197670  0.051982                              0.385257  0.095325                               0.130308  0.049871                             0.172925  0.076362                            0.176097  0.039650                      NaN       NaN                      NaN       NaN                           NaN       NaN                            NaN       NaN                                   NaN       NaN                                   NaN       NaN                                        NaN       NaN                                         NaN       NaN
refine_sinusoidal_dprev                  0.744086  0.005437              0.965179  0.009984               0.716297  0.008787             0.874658  0.021208            0.678008  0.004419                             0.837936  0.082648                           1.000000  0.000000                            0.823749  0.094553                          0.956764  0.037701                         0.783944  0.109038                   0.575056  0.004017                 0.617717  0.008059                  0.558142  0.003164                0.564627  0.003826               0.578194  0.003229                                0.348333  0.060692                              0.495773  0.150980                               0.293791  0.029162                             0.325005  0.053536                            0.334154  0.028276                 0.181381  0.043170                 0.146048  0.013968                      0.461030  0.066685                       0.670030  0.069154                              0.108708  0.060012                              0.059912  0.023107                                   0.454810  0.095435                                    0.682543  0.127209
refine_sinusoidal_dstart                 0.741087  0.013042              0.973023  0.020092               0.704937  0.026514             0.859535  0.033082            0.671765  0.017617                             0.864428  0.058680                           1.000000  0.000000                            0.848106  0.079236                          0.951430  0.063724                         0.820530  0.075588                   0.573719  0.007604                 0.608104  0.018950                  0.560196  0.002588                0.565557  0.003105               0.578660  0.005863                                0.330552  0.112064                              0.503836  0.095015                               0.267901  0.120631                             0.308555  0.121484                            0.307056  0.113490                 0.132072  0.053034                 0.157268  0.038636                      0.460030  0.046765                       0.688575  0.010945                              0.063762  0.069882                              0.032968  0.025514                                   0.469216  0.076161                                    0.718918  0.031512

Interpretation guide:

- main comparison metric: `best_test_at_best_valid_full_ndcg@10`
- compare `Additive_sinusoidal` against completed baseline / additive / attention-bias runs
- task metrics (`accuracy`, `macro_f1`, `top5_accuracy`, `top10_accuracy`) are shown when the corresponding run folders already contain them