# SASRec Attention-Bias Time-Aware BPI2012 Colab Train (`anchor_ml20` baseline)

Colab notebook for testing the strongest time-aware candidate so far on top of the final baseline `anchor_ml20`.

Design:
- baseline reuse: `anchor_ml20`
- time source: `delta_start_seconds`
- causal pairwise gap attention bias
- 9-bucket scalar attention bias
- evaluate under both `NDCG@10` and `NDCG@5` model-selection criteria

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
TIMEAWARE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10'
TIMEAWARE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('TIMEAWARE_NDCG10_OUTPUT_DIR:', TIMEAWARE_NDCG10_OUTPUT_DIR)
print('TIMEAWARE_NDCG5_OUTPUT_DIR:', TIMEAWARE_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg10
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
TIMEAWARE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10
TIMEAWARE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG10_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction
!git pull

/content
/content/time-aware-behavior-prediction
Already up to date.

In [6]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [7]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [8]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [9]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `anchor_ml20`
- `hidden_units=32, num_blocks=2, num_heads=1, maxlen=20, lr=0.001, dropout=0.2`
- seeds: `42`, `2024`, `7`

Time-aware design:
- `delta_start_seconds`
- causal pairwise gap attention bias
- 9-bucket scalar bias
- no additive time embedding in this notebook

## Check existing baseline runs

In [10]:
from pathlib import Path

baseline_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
]

for label, output_dir in [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR)),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR)),
]:
    print('=' * 80)
    print(label)
    for run_name in baseline_runs:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
anchor_ml20_s42 EXISTS
anchor_ml20_s2024 EXISTS
anchor_ml20_s7 EXISTS
================================================================================
Baseline NDCG@5
anchor_ml20_s42 EXISTS
anchor_ml20_s2024 EXISTS
anchor_ml20_s7 EXISTS

## Check planned new runs

In [11]:
planned_ndcg10 = [
    'attnbias_dstart_ml20_b9_s42',
    'attnbias_dstart_ml20_b9_s2024',
    'attnbias_dstart_ml20_b9_s7',
]
planned_ndcg5 = [
    'attnbias_dstart_ml20_b9_s42',
    'attnbias_dstart_ml20_b9_s2024',
    'attnbias_dstart_ml20_b9_s7',
]

for label, output_dir, run_names in [
    ('Attention-Bias NDCG@10', Path(TIMEAWARE_NDCG10_OUTPUT_DIR), planned_ndcg10),
    ('Attention-Bias NDCG@5', Path(TIMEAWARE_NDCG5_OUTPUT_DIR), planned_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Attention-Bias NDCG@10
attnbias_dstart_ml20_b9_s42 OK
attnbias_dstart_ml20_b9_s2024 OK
attnbias_dstart_ml20_b9_s7 OK
================================================================================
Attention-Bias NDCG@5
attnbias_dstart_ml20_b9_s42 OK
attnbias_dstart_ml20_b9_s2024 OK
attnbias_dstart_ml20_b9_s7 OK

## Train attention-bias runs for `NDCG@10`

### attnbias_dstart_ml20_b9_s42

In [12]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml20_b9_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42
epoch=1, loss=0.6454
epoch=2, loss=0.3058
epoch=3, loss=0.2128
epoch=4, loss=0.1694
epoch=5, loss=0.1455
valid [full], NDCG@5: 0.6387, HR@5: 0.7449, NDCG@10: 0.7119, HR@10: 0.9805, MRR: 0.6352
valid [sampled], NDCG@5: 0.5574, HR@5: 0.5584, NDCG@10: 0.5635, HR@10: 0.5781, MRR: 0.5734
test [full], NDCG@5: 0.7418, HR@5: 0.8532, NDCG@10: 0.7842, HR@10: 0.9892, MRR: 0.7211
test [sampled], NDCG@5: 0.1339, HR@5: 0.2152, NDCG@10: 0.2214, HR@10: 0.4860, MRR: 0.1696
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=6, loss=0.1294
epoch=7, loss=0.1224
epoch=8, loss=0.1156
epoch=9, loss=0.1110
epoch=10, loss=0.1058
valid [full], NDCG@5: 0.6303, HR@5: 0.7563, NDCG@10: 0.7004, HR@10: 0.9731, MRR: 0.6211
valid [sampled], NDCG@5: 0.5236, HR@5: 0.5274, NDCG@10: 0.5337, HR@10: 0.5595, MRR: 0.5418
test [full], NDCG@5: 0.7740, HR@5: 0.9105, NDCG@10: 0.8022, HR@10: 1.0000, MRR: 0.7386
test [sampled], NDCG@5: 0.2613, HR@5: 0.3241, NDCG@10: 0.3240, HR@10: 0.5183, MRR: 0.2911
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1058
epoch=12, loss=0.1034
epoch=13, loss=0.1012
epoch=14, loss=0.0997
epoch=15, loss=0.0999
valid [full], NDCG@5: 0.6593, HR@5: 0.7867, NDCG@10: 0.7218, HR@10: 0.9773, MRR: 0.6467
valid [sampled], NDCG@5: 0.5564, HR@5: 0.5597, NDCG@10: 0.5676, HR@10: 0.5956, MRR: 0.5754
test [full], NDCG@5: 0.8342, HR@5: 0.9462, NDCG@10: 0.8504, HR@10: 1.0000, MRR: 0.8018
test [sampled], NDCG@5: 0.3472, HR@5: 0.3966, NDCG@10: 0.4055, HR@10: 0.5790, MRR: 0.3786
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=16, loss=0.0979
epoch=17, loss=0.0964
epoch=18, loss=0.0963
epoch=19, loss=0.0933
epoch=20, loss=0.0936
valid [full], NDCG@5: 0.6810, HR@5: 0.8383, NDCG@10: 0.7253, HR@10: 0.9760, MRR: 0.6511
valid [sampled], NDCG@5: 0.5479, HR@5: 0.5507, NDCG@10: 0.5598, HR@10: 0.5885, MRR: 0.5681
test [full], NDCG@5: 0.8309, HR@5: 0.9456, NDCG@10: 0.8473, HR@10: 1.0000, MRR: 0.7980
test [sampled], NDCG@5: 0.4918, HR@5: 0.4971, NDCG@10: 0.5167, HR@10: 0.5766, MRR: 0.5219
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=21, loss=0.0920
epoch=22, loss=0.0930
epoch=23, loss=0.0918
epoch=24, loss=0.0921
epoch=25, loss=0.0897
valid [full], NDCG@5: 0.6593, HR@5: 0.7991, NDCG@10: 0.7110, HR@10: 0.9600, MRR: 0.6392
valid [sampled], NDCG@5: 0.5296, HR@5: 0.5330, NDCG@10: 0.5418, HR@10: 0.5719, MRR: 0.5495
test [full], NDCG@5: 0.8726, HR@5: 0.9597, NDCG@10: 0.8849, HR@10: 1.0000, MRR: 0.8478
test [sampled], NDCG@5: 0.5263, HR@5: 0.5315, NDCG@10: 0.5498, HR@10: 0.6071, MRR: 0.5559
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0889
epoch=27, loss=0.0894
epoch=28, loss=0.0886
epoch=29, loss=0.0893
epoch=30, loss=0.0877
valid [full], NDCG@5: 0.6929, HR@5: 0.8549, NDCG@10: 0.7315, HR@10: 0.9764, MRR: 0.6578
valid [sampled], NDCG@5: 0.5356, HR@5: 0.5432, NDCG@10: 0.5536, HR@10: 0.6002, MRR: 0.5579
test [full], NDCG@5: 0.8449, HR@5: 0.9589, NDCG@10: 0.8574, HR@10: 1.0000, MRR: 0.8101
test [sampled], NDCG@5: 0.5050, HR@5: 0.5245, NDCG@10: 0.5357, HR@10: 0.6214, MRR: 0.5308
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=31, loss=0.0889
epoch=32, loss=0.0857
epoch=33, loss=0.0874
epoch=34, loss=0.0860
epoch=35, loss=0.0844
valid [full], NDCG@5: 0.6670, HR@5: 0.7985, NDCG@10: 0.7192, HR@10: 0.9633, MRR: 0.6478
valid [sampled], NDCG@5: 0.5419, HR@5: 0.5465, NDCG@10: 0.5584, HR@10: 0.5992, MRR: 0.5626
test [full], NDCG@5: 0.8724, HR@5: 0.9640, NDCG@10: 0.8847, HR@10: 1.0000, MRR: 0.8463
test [sampled], NDCG@5: 0.5291, HR@5: 0.5460, NDCG@10: 0.5574, HR@10: 0.6353, MRR: 0.5558
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0836
epoch=37, loss=0.0855
epoch=38, loss=0.0852
epoch=39, loss=0.0851
epoch=40, loss=0.0838
valid [full], NDCG@5: 0.6710, HR@5: 0.7982, NDCG@10: 0.7163, HR@10: 0.9448, MRR: 0.6513
valid [sampled], NDCG@5: 0.5470, HR@5: 0.5505, NDCG@10: 0.5648, HR@10: 0.6074, MRR: 0.5685
test [full], NDCG@5: 0.9034, HR@5: 0.9879, NDCG@10: 0.9077, HR@10: 1.0000, MRR: 0.8769
test [sampled], NDCG@5: 0.5716, HR@5: 0.5750, NDCG@10: 0.5874, HR@10: 0.6259, MRR: 0.5985
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0847
epoch=42, loss=0.0843
epoch=43, loss=0.0858
epoch=44, loss=0.0827
epoch=45, loss=0.0861
valid [full], NDCG@5: 0.6705, HR@5: 0.7941, NDCG@10: 0.7174, HR@10: 0.9433, MRR: 0.6528
valid [sampled], NDCG@5: 0.5423, HR@5: 0.5495, NDCG@10: 0.5601, HR@10: 0.6062, MRR: 0.5620
test [full], NDCG@5: 0.8700, HR@5: 0.9991, NDCG@10: 0.8703, HR@10: 1.0000, MRR: 0.8258
test [sampled], NDCG@5: 0.5620, HR@5: 0.5939, NDCG@10: 0.5987, HR@10: 0.7079, MRR: 0.5843
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0793
epoch=47, loss=0.0842
epoch=48, loss=0.0818
epoch=49, loss=0.0816
epoch=50, loss=0.0823
valid [full], NDCG@5: 0.6955, HR@5: 0.8343, NDCG@10: 0.7283, HR@10: 0.9421, MRR: 0.6671
valid [sampled], NDCG@5: 0.5495, HR@5: 0.5572, NDCG@10: 0.5707, HR@10: 0.6245, MRR: 0.5701
test [full], NDCG@5: 0.9025, HR@5: 0.9971, NDCG@10: 0.9035, HR@10: 1.0000, MRR: 0.8706
test [sampled], NDCG@5: 0.6194, HR@5: 0.6351, NDCG@10: 0.6400, HR@10: 0.7001, MRR: 0.6404
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s42/sasrec_last.pth

### attnbias_dstart_ml20_b9_s2024

In [13]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml20_b9_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024
epoch=1, loss=0.6694
epoch=2, loss=0.3203
epoch=3, loss=0.2175
epoch=4, loss=0.1708
epoch=5, loss=0.1452
valid [full], NDCG@5: 0.6214, HR@5: 0.7297, NDCG@10: 0.6938, HR@10: 0.9642, MRR: 0.6177
valid [sampled], NDCG@5: 0.5274, HR@5: 0.5276, NDCG@10: 0.5337, HR@10: 0.5478, MRR: 0.5453
test [full], NDCG@5: 0.7258, HR@5: 0.8567, NDCG@10: 0.7688, HR@10: 0.9903, MRR: 0.7020
test [sampled], NDCG@5: 0.2071, HR@5: 0.2695, NDCG@10: 0.2550, HR@10: 0.4164, MRR: 0.2343
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1314
epoch=7, loss=0.1206
epoch=8, loss=0.1137
epoch=9, loss=0.1117
epoch=10, loss=0.1080
valid [full], NDCG@5: 0.6462, HR@5: 0.7744, NDCG@10: 0.7102, HR@10: 0.9720, MRR: 0.6344
valid [sampled], NDCG@5: 0.5409, HR@5: 0.5418, NDCG@10: 0.5485, HR@10: 0.5664, MRR: 0.5590
test [full], NDCG@5: 0.6859, HR@5: 0.8942, NDCG@10: 0.7211, HR@10: 0.9996, MRR: 0.6296
test [sampled], NDCG@5: 0.1298, HR@5: 0.1494, NDCG@10: 0.2039, HR@10: 0.3863, MRR: 0.1875
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=11, loss=0.1065
epoch=12, loss=0.1021
epoch=13, loss=0.1023
epoch=14, loss=0.1001
epoch=15, loss=0.0985
valid [full], NDCG@5: 0.6587, HR@5: 0.7851, NDCG@10: 0.7216, HR@10: 0.9759, MRR: 0.6471
valid [sampled], NDCG@5: 0.5565, HR@5: 0.5602, NDCG@10: 0.5655, HR@10: 0.5890, MRR: 0.5741
test [full], NDCG@5: 0.7688, HR@5: 0.9186, NDCG@10: 0.7966, HR@10: 1.0000, MRR: 0.7300
test [sampled], NDCG@5: 0.3109, HR@5: 0.3310, NDCG@10: 0.3671, HR@10: 0.5101, MRR: 0.3537
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=16, loss=0.0971
epoch=17, loss=0.0961
epoch=18, loss=0.0969
epoch=19, loss=0.0963
epoch=20, loss=0.0928
valid [full], NDCG@5: 0.6510, HR@5: 0.7713, NDCG@10: 0.7177, HR@10: 0.9768, MRR: 0.6426
valid [sampled], NDCG@5: 0.5504, HR@5: 0.5521, NDCG@10: 0.5561, HR@10: 0.5704, MRR: 0.5673
test [full], NDCG@5: 0.7689, HR@5: 0.9224, NDCG@10: 0.7951, HR@10: 0.9999, MRR: 0.7280
test [sampled], NDCG@5: 0.3066, HR@5: 0.3287, NDCG@10: 0.3637, HR@10: 0.5108, MRR: 0.3492
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0933
epoch=22, loss=0.0916
epoch=23, loss=0.0927
epoch=24, loss=0.0919
epoch=25, loss=0.0910
valid [full], NDCG@5: 0.6634, HR@5: 0.7929, NDCG@10: 0.7224, HR@10: 0.9759, MRR: 0.6483
valid [sampled], NDCG@5: 0.5483, HR@5: 0.5526, NDCG@10: 0.5610, HR@10: 0.5934, MRR: 0.5667
test [full], NDCG@5: 0.7828, HR@5: 0.9613, NDCG@10: 0.7959, HR@10: 0.9999, MRR: 0.7277
test [sampled], NDCG@5: 0.2805, HR@5: 0.3072, NDCG@10: 0.3449, HR@10: 0.5121, MRR: 0.3262
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=26, loss=0.0876
epoch=27, loss=0.0898
epoch=28, loss=0.0889
epoch=29, loss=0.0915
epoch=30, loss=0.0863
valid [full], NDCG@5: 0.6826, HR@5: 0.8399, NDCG@10: 0.7278, HR@10: 0.9774, MRR: 0.6532
valid [sampled], NDCG@5: 0.5395, HR@5: 0.5435, NDCG@10: 0.5514, HR@10: 0.5815, MRR: 0.5601
test [full], NDCG@5: 0.8001, HR@5: 0.9539, NDCG@10: 0.8152, HR@10: 1.0000, MRR: 0.7537
test [sampled], NDCG@5: 0.3116, HR@5: 0.3324, NDCG@10: 0.3694, HR@10: 0.5172, MRR: 0.3558
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=31, loss=0.0886
epoch=32, loss=0.0891
epoch=33, loss=0.0873
epoch=34, loss=0.0884
epoch=35, loss=0.0864
valid [full], NDCG@5: 0.6170, HR@5: 0.6988, NDCG@10: 0.7059, HR@10: 0.9756, MRR: 0.6293
valid [sampled], NDCG@5: 0.5502, HR@5: 0.5524, NDCG@10: 0.5563, HR@10: 0.5717, MRR: 0.5652
test [full], NDCG@5: 0.7860, HR@5: 0.9613, NDCG@10: 0.7996, HR@10: 0.9999, MRR: 0.7328
test [sampled], NDCG@5: 0.3032, HR@5: 0.3225, NDCG@10: 0.3614, HR@10: 0.5081, MRR: 0.3486
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0862
epoch=37, loss=0.0853
epoch=38, loss=0.0852
epoch=39, loss=0.0839
epoch=40, loss=0.0827
valid [full], NDCG@5: 0.6531, HR@5: 0.7611, NDCG@10: 0.7236, HR@10: 0.9759, MRR: 0.6500
valid [sampled], NDCG@5: 0.5543, HR@5: 0.5643, NDCG@10: 0.5699, HR@10: 0.6126, MRR: 0.5705
test [full], NDCG@5: 0.7783, HR@5: 0.9670, NDCG@10: 0.7900, HR@10: 0.9999, MRR: 0.7211
test [sampled], NDCG@5: 0.3487, HR@5: 0.3647, NDCG@10: 0.3784, HR@10: 0.4586, MRR: 0.3863
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0841
epoch=42, loss=0.0854
epoch=43, loss=0.0836
epoch=44, loss=0.0832
epoch=45, loss=0.0818
valid [full], NDCG@5: 0.6389, HR@5: 0.7215, NDCG@10: 0.7204, HR@10: 0.9774, MRR: 0.6466
valid [sampled], NDCG@5: 0.5567, HR@5: 0.5652, NDCG@10: 0.5731, HR@10: 0.6170, MRR: 0.5721
test [full], NDCG@5: 0.8523, HR@5: 0.9469, NDCG@10: 0.8701, HR@10: 0.9999, MRR: 0.8279
test [sampled], NDCG@5: 0.2596, HR@5: 0.3442, NDCG@10: 0.3448, HR@10: 0.6061, MRR: 0.2899
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0825
epoch=47, loss=0.0836
epoch=48, loss=0.0831
epoch=49, loss=0.0800
epoch=50, loss=0.0829
valid [full], NDCG@5: 0.6416, HR@5: 0.7212, NDCG@10: 0.7181, HR@10: 0.9592, MRR: 0.6499
valid [sampled], NDCG@5: 0.5608, HR@5: 0.5729, NDCG@10: 0.5790, HR@10: 0.6298, MRR: 0.5750
test [full], NDCG@5: 0.8636, HR@5: 0.9534, NDCG@10: 0.8792, HR@10: 1.0000, MRR: 0.8399
test [sampled], NDCG@5: 0.3003, HR@5: 0.3862, NDCG@10: 0.3801, HR@10: 0.6306, MRR: 0.3265
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s2024/sasrec_last.pth

### attnbias_dstart_ml20_b9_s7

In [14]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml20_b9_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7
epoch=1, loss=0.6862
epoch=2, loss=0.3289
epoch=3, loss=0.2388
epoch=4, loss=0.1808
epoch=5, loss=0.1496
valid [full], NDCG@5: 0.6602, HR@5: 0.7985, NDCG@10: 0.7132, HR@10: 0.9634, MRR: 0.6406
valid [sampled], NDCG@5: 0.5497, HR@5: 0.5510, NDCG@10: 0.5556, HR@10: 0.5700, MRR: 0.5674
test [full], NDCG@5: 0.6524, HR@5: 0.8945, NDCG@10: 0.6835, HR@10: 0.9940, MRR: 0.5848
test [sampled], NDCG@5: 0.1813, HR@5: 0.1834, NDCG@10: 0.2007, HR@10: 0.2471, MRR: 0.2284
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=6, loss=0.1345
epoch=7, loss=0.1267
epoch=8, loss=0.1161
epoch=9, loss=0.1129
epoch=10, loss=0.1092
valid [full], NDCG@5: 0.6643, HR@5: 0.8115, NDCG@10: 0.7084, HR@10: 0.9490, MRR: 0.6392
valid [sampled], NDCG@5: 0.5353, HR@5: 0.5405, NDCG@10: 0.5439, HR@10: 0.5677, MRR: 0.5527
test [full], NDCG@5: 0.7078, HR@5: 0.9890, NDCG@10: 0.7117, HR@10: 1.0000, MRR: 0.6161
test [sampled], NDCG@5: 0.1712, HR@5: 0.1795, NDCG@10: 0.2017, HR@10: 0.2784, MRR: 0.2234
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1080
epoch=12, loss=0.1051
epoch=13, loss=0.1005
epoch=14, loss=0.1007
epoch=15, loss=0.1001
valid [full], NDCG@5: 0.6534, HR@5: 0.7881, NDCG@10: 0.6967, HR@10: 0.9242, MRR: 0.6329
valid [sampled], NDCG@5: 0.5354, HR@5: 0.5384, NDCG@10: 0.5460, HR@10: 0.5722, MRR: 0.5538
test [full], NDCG@5: 0.7350, HR@5: 0.9995, NDCG@10: 0.7352, HR@10: 1.0000, MRR: 0.6470
test [sampled], NDCG@5: 0.1792, HR@5: 0.1979, NDCG@10: 0.2243, HR@10: 0.3415, MRR: 0.2310
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0997
epoch=17, loss=0.0969
epoch=18, loss=0.0946
epoch=19, loss=0.0930
epoch=20, loss=0.0938
valid [full], NDCG@5: 0.6680, HR@5: 0.8011, NDCG@10: 0.6902, HR@10: 0.8747, MRR: 0.6423
valid [sampled], NDCG@5: 0.5475, HR@5: 0.5524, NDCG@10: 0.5624, HR@10: 0.6000, MRR: 0.5659
test [full], NDCG@5: 0.7905, HR@5: 0.9984, NDCG@10: 0.7911, HR@10: 1.0000, MRR: 0.7216
test [sampled], NDCG@5: 0.2885, HR@5: 0.3059, NDCG@10: 0.3310, HR@10: 0.4414, MRR: 0.3340
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0915
epoch=22, loss=0.0911
epoch=23, loss=0.0911
epoch=24, loss=0.0905
epoch=25, loss=0.0903
valid [full], NDCG@5: 0.6707, HR@5: 0.7917, NDCG@10: 0.7029, HR@10: 0.8955, MRR: 0.6511
valid [sampled], NDCG@5: 0.5517, HR@5: 0.5566, NDCG@10: 0.5677, HR@10: 0.6077, MRR: 0.5704
test [full], NDCG@5: 0.7835, HR@5: 0.9961, NDCG@10: 0.7848, HR@10: 0.9999, MRR: 0.7130
test [sampled], NDCG@5: 0.2867, HR@5: 0.3027, NDCG@10: 0.3284, HR@10: 0.4361, MRR: 0.3326
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0895
epoch=27, loss=0.0899
epoch=28, loss=0.0877
epoch=29, loss=0.0860
epoch=30, loss=0.0855
valid [full], NDCG@5: 0.6725, HR@5: 0.7785, NDCG@10: 0.7055, HR@10: 0.8835, MRR: 0.6585
valid [sampled], NDCG@5: 0.5470, HR@5: 0.5529, NDCG@10: 0.5679, HR@10: 0.6193, MRR: 0.5664
test [full], NDCG@5: 0.8205, HR@5: 0.9985, NDCG@10: 0.8210, HR@10: 1.0000, MRR: 0.7597
test [sampled], NDCG@5: 0.3276, HR@5: 0.3369, NDCG@10: 0.3883, HR@10: 0.5334, MRR: 0.3781
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0888
epoch=32, loss=0.0846
epoch=33, loss=0.0856
epoch=34, loss=0.0840
epoch=35, loss=0.0850
valid [full], NDCG@5: 0.6613, HR@5: 0.7880, NDCG@10: 0.6866, HR@10: 0.8709, MRR: 0.6385
valid [sampled], NDCG@5: 0.5373, HR@5: 0.5479, NDCG@10: 0.5516, HR@10: 0.5925, MRR: 0.5534
test [full], NDCG@5: 0.8250, HR@5: 0.9946, NDCG@10: 0.8268, HR@10: 1.0000, MRR: 0.7674
test [sampled], NDCG@5: 0.3741, HR@5: 0.3920, NDCG@10: 0.4279, HR@10: 0.5634, MRR: 0.4164
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0863
epoch=37, loss=0.0854
epoch=38, loss=0.0839
epoch=39, loss=0.0830
epoch=40, loss=0.0847
valid [full], NDCG@5: 0.6948, HR@5: 0.8123, NDCG@10: 0.7317, HR@10: 0.9332, MRR: 0.6741
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5673, NDCG@10: 0.5846, HR@10: 0.6736, MRR: 0.5713
test [full], NDCG@5: 0.8335, HR@5: 0.9986, NDCG@10: 0.8339, HR@10: 1.0000, MRR: 0.7766
test [sampled], NDCG@5: 0.3499, HR@5: 0.3665, NDCG@10: 0.4082, HR@10: 0.5532, MRR: 0.3953
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=41, loss=0.0854
epoch=42, loss=0.0825
epoch=43, loss=0.0817
epoch=44, loss=0.0855
epoch=45, loss=0.0822
valid [full], NDCG@5: 0.6745, HR@5: 0.7934, NDCG@10: 0.7101, HR@10: 0.9107, MRR: 0.6554
valid [sampled], NDCG@5: 0.5449, HR@5: 0.5578, NDCG@10: 0.5644, HR@10: 0.6187, MRR: 0.5621
test [full], NDCG@5: 0.8271, HR@5: 0.9989, NDCG@10: 0.8275, HR@10: 1.0000, MRR: 0.7682
test [sampled], NDCG@5: 0.3740, HR@5: 0.3879, NDCG@10: 0.4268, HR@10: 0.5572, MRR: 0.4176
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0816
epoch=47, loss=0.0819
epoch=48, loss=0.0818
epoch=49, loss=0.0811
epoch=50, loss=0.0820
valid [full], NDCG@5: 0.6759, HR@5: 0.7932, NDCG@10: 0.7078, HR@10: 0.8992, MRR: 0.6564
valid [sampled], NDCG@5: 0.5628, HR@5: 0.5762, NDCG@10: 0.5774, HR@10: 0.6217, MRR: 0.5770
test [full], NDCG@5: 0.8343, HR@5: 0.9949, NDCG@10: 0.8361, HR@10: 1.0000, MRR: 0.7797
test [sampled], NDCG@5: 0.3681, HR@5: 0.3831, NDCG@10: 0.4257, HR@10: 0.5680, MRR: 0.4129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg10/attnbias_dstart_ml20_b9_s7/sasrec_last.pth

## Train attention-bias runs for `NDCG@5`

### attnbias_dstart_ml20_b9_s42

In [15]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml20_b9_s42 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 42 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42
epoch=1, loss=0.6454
epoch=2, loss=0.3058
epoch=3, loss=0.2128
epoch=4, loss=0.1694
epoch=5, loss=0.1455
valid [full], NDCG@5: 0.6387, HR@5: 0.7449, NDCG@10: 0.7119, HR@10: 0.9805, MRR: 0.6352
valid [sampled], NDCG@5: 0.5574, HR@5: 0.5584, NDCG@10: 0.5635, HR@10: 0.5781, MRR: 0.5734
test [full], NDCG@5: 0.7418, HR@5: 0.8532, NDCG@10: 0.7842, HR@10: 0.9892, MRR: 0.7211
test [sampled], NDCG@5: 0.1339, HR@5: 0.2152, NDCG@10: 0.2214, HR@10: 0.4860, MRR: 0.1696
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=6, loss=0.1294
epoch=7, loss=0.1224
epoch=8, loss=0.1156
epoch=9, loss=0.1110
epoch=10, loss=0.1058
valid [full], NDCG@5: 0.6303, HR@5: 0.7563, NDCG@10: 0.7004, HR@10: 0.9731, MRR: 0.6211
valid [sampled], NDCG@5: 0.5236, HR@5: 0.5274, NDCG@10: 0.5337, HR@10: 0.5595, MRR: 0.5418
test [full], NDCG@5: 0.7740, HR@5: 0.9105, NDCG@10: 0.8022, HR@10: 1.0000, MRR: 0.7386
test [sampled], NDCG@5: 0.2613, HR@5: 0.3241, NDCG@10: 0.3240, HR@10: 0.5183, MRR: 0.2911
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.1058
epoch=12, loss=0.1034
epoch=13, loss=0.1012
epoch=14, loss=0.0997
epoch=15, loss=0.0999
valid [full], NDCG@5: 0.6593, HR@5: 0.7867, NDCG@10: 0.7218, HR@10: 0.9773, MRR: 0.6467
valid [sampled], NDCG@5: 0.5564, HR@5: 0.5597, NDCG@10: 0.5676, HR@10: 0.5956, MRR: 0.5754
test [full], NDCG@5: 0.8342, HR@5: 0.9462, NDCG@10: 0.8504, HR@10: 1.0000, MRR: 0.8018
test [sampled], NDCG@5: 0.3472, HR@5: 0.3966, NDCG@10: 0.4055, HR@10: 0.5790, MRR: 0.3786
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=16, loss=0.0979
epoch=17, loss=0.0964
epoch=18, loss=0.0963
epoch=19, loss=0.0933
epoch=20, loss=0.0936
valid [full], NDCG@5: 0.6810, HR@5: 0.8383, NDCG@10: 0.7253, HR@10: 0.9760, MRR: 0.6511
valid [sampled], NDCG@5: 0.5479, HR@5: 0.5507, NDCG@10: 0.5598, HR@10: 0.5885, MRR: 0.5681
test [full], NDCG@5: 0.8309, HR@5: 0.9456, NDCG@10: 0.8473, HR@10: 1.0000, MRR: 0.7980
test [sampled], NDCG@5: 0.4918, HR@5: 0.4971, NDCG@10: 0.5167, HR@10: 0.5766, MRR: 0.5219
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=21, loss=0.0920
epoch=22, loss=0.0930
epoch=23, loss=0.0918
epoch=24, loss=0.0921
epoch=25, loss=0.0897
valid [full], NDCG@5: 0.6593, HR@5: 0.7991, NDCG@10: 0.7110, HR@10: 0.9600, MRR: 0.6392
valid [sampled], NDCG@5: 0.5296, HR@5: 0.5330, NDCG@10: 0.5418, HR@10: 0.5719, MRR: 0.5495
test [full], NDCG@5: 0.8726, HR@5: 0.9597, NDCG@10: 0.8849, HR@10: 1.0000, MRR: 0.8478
test [sampled], NDCG@5: 0.5263, HR@5: 0.5315, NDCG@10: 0.5498, HR@10: 0.6071, MRR: 0.5559
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0889
epoch=27, loss=0.0894
epoch=28, loss=0.0886
epoch=29, loss=0.0893
epoch=30, loss=0.0877
valid [full], NDCG@5: 0.6929, HR@5: 0.8549, NDCG@10: 0.7315, HR@10: 0.9764, MRR: 0.6578
valid [sampled], NDCG@5: 0.5356, HR@5: 0.5432, NDCG@10: 0.5536, HR@10: 0.6002, MRR: 0.5579
test [full], NDCG@5: 0.8449, HR@5: 0.9589, NDCG@10: 0.8574, HR@10: 1.0000, MRR: 0.8101
test [sampled], NDCG@5: 0.5050, HR@5: 0.5245, NDCG@10: 0.5357, HR@10: 0.6214, MRR: 0.5308
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
epoch=31, loss=0.0889
epoch=32, loss=0.0857
epoch=33, loss=0.0874
epoch=34, loss=0.0860
epoch=35, loss=0.0844
valid [full], NDCG@5: 0.6670, HR@5: 0.7985, NDCG@10: 0.7192, HR@10: 0.9633, MRR: 0.6478
valid [sampled], NDCG@5: 0.5419, HR@5: 0.5465, NDCG@10: 0.5584, HR@10: 0.5992, MRR: 0.5626
test [full], NDCG@5: 0.8724, HR@5: 0.9640, NDCG@10: 0.8847, HR@10: 1.0000, MRR: 0.8463
test [sampled], NDCG@5: 0.5291, HR@5: 0.5460, NDCG@10: 0.5574, HR@10: 0.6353, MRR: 0.5558
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0836
epoch=37, loss=0.0855
epoch=38, loss=0.0852
epoch=39, loss=0.0851
epoch=40, loss=0.0838
valid [full], NDCG@5: 0.6710, HR@5: 0.7982, NDCG@10: 0.7163, HR@10: 0.9448, MRR: 0.6513
valid [sampled], NDCG@5: 0.5470, HR@5: 0.5505, NDCG@10: 0.5648, HR@10: 0.6074, MRR: 0.5685
test [full], NDCG@5: 0.9034, HR@5: 0.9879, NDCG@10: 0.9077, HR@10: 1.0000, MRR: 0.8769
test [sampled], NDCG@5: 0.5716, HR@5: 0.5750, NDCG@10: 0.5874, HR@10: 0.6259, MRR: 0.5985
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0847
epoch=42, loss=0.0843
epoch=43, loss=0.0858
epoch=44, loss=0.0827
epoch=45, loss=0.0861
valid [full], NDCG@5: 0.6705, HR@5: 0.7941, NDCG@10: 0.7174, HR@10: 0.9433, MRR: 0.6528
valid [sampled], NDCG@5: 0.5423, HR@5: 0.5495, NDCG@10: 0.5601, HR@10: 0.6062, MRR: 0.5620
test [full], NDCG@5: 0.8700, HR@5: 0.9991, NDCG@10: 0.8703, HR@10: 1.0000, MRR: 0.8258
test [sampled], NDCG@5: 0.5620, HR@5: 0.5939, NDCG@10: 0.5987, HR@10: 0.7079, MRR: 0.5843
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0793
epoch=47, loss=0.0842
epoch=48, loss=0.0818
epoch=49, loss=0.0816
epoch=50, loss=0.0823
valid [full], NDCG@5: 0.6955, HR@5: 0.8343, NDCG@10: 0.7283, HR@10: 0.9421, MRR: 0.6671
valid [sampled], NDCG@5: 0.5495, HR@5: 0.5572, NDCG@10: 0.5707, HR@10: 0.6245, MRR: 0.5701
test [full], NDCG@5: 0.9025, HR@5: 0.9971, NDCG@10: 0.9035, HR@10: 1.0000, MRR: 0.8706
test [sampled], NDCG@5: 0.6194, HR@5: 0.6351, NDCG@10: 0.6400, HR@10: 0.7001, MRR: 0.6404
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/sasrec_best.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s42/sasrec_last.pth

### attnbias_dstart_ml20_b9_s2024

In [16]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml20_b9_s2024 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 2024 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024
epoch=1, loss=0.6694
epoch=2, loss=0.3203
epoch=3, loss=0.2175
epoch=4, loss=0.1708
epoch=5, loss=0.1452
valid [full], NDCG@5: 0.6214, HR@5: 0.7297, NDCG@10: 0.6938, HR@10: 0.9642, MRR: 0.6177
valid [sampled], NDCG@5: 0.5274, HR@5: 0.5276, NDCG@10: 0.5337, HR@10: 0.5478, MRR: 0.5453
test [full], NDCG@5: 0.7258, HR@5: 0.8567, NDCG@10: 0.7688, HR@10: 0.9903, MRR: 0.7020
test [sampled], NDCG@5: 0.2071, HR@5: 0.2695, NDCG@10: 0.2550, HR@10: 0.4164, MRR: 0.2343
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=6, loss=0.1314
epoch=7, loss=0.1206
epoch=8, loss=0.1137
epoch=9, loss=0.1117
epoch=10, loss=0.1080
valid [full], NDCG@5: 0.6462, HR@5: 0.7744, NDCG@10: 0.7102, HR@10: 0.9720, MRR: 0.6344
valid [sampled], NDCG@5: 0.5409, HR@5: 0.5418, NDCG@10: 0.5485, HR@10: 0.5664, MRR: 0.5590
test [full], NDCG@5: 0.6859, HR@5: 0.8942, NDCG@10: 0.7211, HR@10: 0.9996, MRR: 0.6296
test [sampled], NDCG@5: 0.1298, HR@5: 0.1494, NDCG@10: 0.2039, HR@10: 0.3863, MRR: 0.1875
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=11, loss=0.1065
epoch=12, loss=0.1021
epoch=13, loss=0.1023
epoch=14, loss=0.1001
epoch=15, loss=0.0985
valid [full], NDCG@5: 0.6587, HR@5: 0.7851, NDCG@10: 0.7216, HR@10: 0.9759, MRR: 0.6471
valid [sampled], NDCG@5: 0.5565, HR@5: 0.5602, NDCG@10: 0.5655, HR@10: 0.5890, MRR: 0.5741
test [full], NDCG@5: 0.7688, HR@5: 0.9186, NDCG@10: 0.7966, HR@10: 1.0000, MRR: 0.7300
test [sampled], NDCG@5: 0.3109, HR@5: 0.3310, NDCG@10: 0.3671, HR@10: 0.5101, MRR: 0.3537
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=16, loss=0.0971
epoch=17, loss=0.0961
epoch=18, loss=0.0969
epoch=19, loss=0.0963
epoch=20, loss=0.0928
valid [full], NDCG@5: 0.6510, HR@5: 0.7713, NDCG@10: 0.7177, HR@10: 0.9768, MRR: 0.6426
valid [sampled], NDCG@5: 0.5504, HR@5: 0.5521, NDCG@10: 0.5561, HR@10: 0.5704, MRR: 0.5673
test [full], NDCG@5: 0.7689, HR@5: 0.9224, NDCG@10: 0.7951, HR@10: 0.9999, MRR: 0.7280
test [sampled], NDCG@5: 0.3066, HR@5: 0.3287, NDCG@10: 0.3637, HR@10: 0.5108, MRR: 0.3492
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0933
epoch=22, loss=0.0916
epoch=23, loss=0.0927
epoch=24, loss=0.0919
epoch=25, loss=0.0910
valid [full], NDCG@5: 0.6634, HR@5: 0.7929, NDCG@10: 0.7224, HR@10: 0.9759, MRR: 0.6483
valid [sampled], NDCG@5: 0.5483, HR@5: 0.5526, NDCG@10: 0.5610, HR@10: 0.5934, MRR: 0.5667
test [full], NDCG@5: 0.7828, HR@5: 0.9613, NDCG@10: 0.7959, HR@10: 0.9999, MRR: 0.7277
test [sampled], NDCG@5: 0.2805, HR@5: 0.3072, NDCG@10: 0.3449, HR@10: 0.5121, MRR: 0.3262
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=26, loss=0.0876
epoch=27, loss=0.0898
epoch=28, loss=0.0889
epoch=29, loss=0.0915
epoch=30, loss=0.0863
valid [full], NDCG@5: 0.6826, HR@5: 0.8399, NDCG@10: 0.7278, HR@10: 0.9774, MRR: 0.6532
valid [sampled], NDCG@5: 0.5395, HR@5: 0.5435, NDCG@10: 0.5514, HR@10: 0.5815, MRR: 0.5601
test [full], NDCG@5: 0.8001, HR@5: 0.9539, NDCG@10: 0.8152, HR@10: 1.0000, MRR: 0.7537
test [sampled], NDCG@5: 0.3116, HR@5: 0.3324, NDCG@10: 0.3694, HR@10: 0.5172, MRR: 0.3558
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/sasrec_best.pth
epoch=31, loss=0.0886
epoch=32, loss=0.0891
epoch=33, loss=0.0873
epoch=34, loss=0.0884
epoch=35, loss=0.0864
valid [full], NDCG@5: 0.6170, HR@5: 0.6988, NDCG@10: 0.7059, HR@10: 0.9756, MRR: 0.6293
valid [sampled], NDCG@5: 0.5502, HR@5: 0.5524, NDCG@10: 0.5563, HR@10: 0.5717, MRR: 0.5652
test [full], NDCG@5: 0.7860, HR@5: 0.9613, NDCG@10: 0.7996, HR@10: 0.9999, MRR: 0.7328
test [sampled], NDCG@5: 0.3032, HR@5: 0.3225, NDCG@10: 0.3614, HR@10: 0.5081, MRR: 0.3486
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0862
epoch=37, loss=0.0853
epoch=38, loss=0.0852
epoch=39, loss=0.0839
epoch=40, loss=0.0827
valid [full], NDCG@5: 0.6531, HR@5: 0.7611, NDCG@10: 0.7236, HR@10: 0.9759, MRR: 0.6500
valid [sampled], NDCG@5: 0.5543, HR@5: 0.5643, NDCG@10: 0.5699, HR@10: 0.6126, MRR: 0.5705
test [full], NDCG@5: 0.7783, HR@5: 0.9670, NDCG@10: 0.7900, HR@10: 0.9999, MRR: 0.7211
test [sampled], NDCG@5: 0.3487, HR@5: 0.3647, NDCG@10: 0.3784, HR@10: 0.4586, MRR: 0.3863
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0841
epoch=42, loss=0.0854
epoch=43, loss=0.0836
epoch=44, loss=0.0832
epoch=45, loss=0.0818
valid [full], NDCG@5: 0.6389, HR@5: 0.7215, NDCG@10: 0.7204, HR@10: 0.9774, MRR: 0.6466
valid [sampled], NDCG@5: 0.5567, HR@5: 0.5652, NDCG@10: 0.5731, HR@10: 0.6170, MRR: 0.5721
test [full], NDCG@5: 0.8523, HR@5: 0.9469, NDCG@10: 0.8701, HR@10: 0.9999, MRR: 0.8279
test [sampled], NDCG@5: 0.2596, HR@5: 0.3442, NDCG@10: 0.3448, HR@10: 0.6061, MRR: 0.2899
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0825
epoch=47, loss=0.0836
epoch=48, loss=0.0831
epoch=49, loss=0.0800
epoch=50, loss=0.0829
valid [full], NDCG@5: 0.6416, HR@5: 0.7212, NDCG@10: 0.7181, HR@10: 0.9592, MRR: 0.6499
valid [sampled], NDCG@5: 0.5608, HR@5: 0.5729, NDCG@10: 0.5790, HR@10: 0.6298, MRR: 0.5750
test [full], NDCG@5: 0.8636, HR@5: 0.9534, NDCG@10: 0.8792, HR@10: 1.0000, MRR: 0.8399
test [sampled], NDCG@5: 0.3003, HR@5: 0.3862, NDCG@10: 0.3801, HR@10: 0.6306, MRR: 0.3265
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s2024/sasrec_last.pth

### attnbias_dstart_ml20_b9_s7

In [17]:
!python src/train_sasrec.py \
  --run_name attnbias_dstart_ml20_b9_s7 \
  --hidden_units 32 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 20 \
  --lr 0.001 \
  --dropout_rate 0.2 \
  --seed 7 \
  --use_time_attention_bias \
  --time_delta_column delta_start_seconds \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7
epoch=1, loss=0.6862
epoch=2, loss=0.3289
epoch=3, loss=0.2388
epoch=4, loss=0.1808
epoch=5, loss=0.1496
valid [full], NDCG@5: 0.6602, HR@5: 0.7985, NDCG@10: 0.7132, HR@10: 0.9634, MRR: 0.6406
valid [sampled], NDCG@5: 0.5497, HR@5: 0.5510, NDCG@10: 0.5556, HR@10: 0.5700, MRR: 0.5674
test [full], NDCG@5: 0.6524, HR@5: 0.8945, NDCG@10: 0.6835, HR@10: 0.9940, MRR: 0.5848
test [sampled], NDCG@5: 0.1813, HR@5: 0.1834, NDCG@10: 0.2007, HR@10: 0.2471, MRR: 0.2284
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=6, loss=0.1345
epoch=7, loss=0.1267
epoch=8, loss=0.1161
epoch=9, loss=0.1129
epoch=10, loss=0.1092
valid [full], NDCG@5: 0.6643, HR@5: 0.8115, NDCG@10: 0.7084, HR@10: 0.9490, MRR: 0.6392
valid [sampled], NDCG@5: 0.5353, HR@5: 0.5405, NDCG@10: 0.5439, HR@10: 0.5677, MRR: 0.5527
test [full], NDCG@5: 0.7078, HR@5: 0.9890, NDCG@10: 0.7117, HR@10: 1.0000, MRR: 0.6161
test [sampled], NDCG@5: 0.1712, HR@5: 0.1795, NDCG@10: 0.2017, HR@10: 0.2784, MRR: 0.2234
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=11, loss=0.1080
epoch=12, loss=0.1051
epoch=13, loss=0.1005
epoch=14, loss=0.1007
epoch=15, loss=0.1001
valid [full], NDCG@5: 0.6534, HR@5: 0.7881, NDCG@10: 0.6967, HR@10: 0.9242, MRR: 0.6329
valid [sampled], NDCG@5: 0.5354, HR@5: 0.5384, NDCG@10: 0.5460, HR@10: 0.5722, MRR: 0.5538
test [full], NDCG@5: 0.7350, HR@5: 0.9995, NDCG@10: 0.7352, HR@10: 1.0000, MRR: 0.6470
test [sampled], NDCG@5: 0.1792, HR@5: 0.1979, NDCG@10: 0.2243, HR@10: 0.3415, MRR: 0.2310
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0997
epoch=17, loss=0.0969
epoch=18, loss=0.0946
epoch=19, loss=0.0930
epoch=20, loss=0.0938
valid [full], NDCG@5: 0.6680, HR@5: 0.8011, NDCG@10: 0.6902, HR@10: 0.8747, MRR: 0.6423
valid [sampled], NDCG@5: 0.5475, HR@5: 0.5524, NDCG@10: 0.5624, HR@10: 0.6000, MRR: 0.5659
test [full], NDCG@5: 0.7905, HR@5: 0.9984, NDCG@10: 0.7911, HR@10: 1.0000, MRR: 0.7216
test [sampled], NDCG@5: 0.2885, HR@5: 0.3059, NDCG@10: 0.3310, HR@10: 0.4414, MRR: 0.3340
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=21, loss=0.0915
epoch=22, loss=0.0911
epoch=23, loss=0.0911
epoch=24, loss=0.0905
epoch=25, loss=0.0903
valid [full], NDCG@5: 0.6707, HR@5: 0.7917, NDCG@10: 0.7029, HR@10: 0.8955, MRR: 0.6511
valid [sampled], NDCG@5: 0.5517, HR@5: 0.5566, NDCG@10: 0.5677, HR@10: 0.6077, MRR: 0.5704
test [full], NDCG@5: 0.7835, HR@5: 0.9961, NDCG@10: 0.7848, HR@10: 0.9999, MRR: 0.7130
test [sampled], NDCG@5: 0.2867, HR@5: 0.3027, NDCG@10: 0.3284, HR@10: 0.4361, MRR: 0.3326
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=26, loss=0.0895
epoch=27, loss=0.0899
epoch=28, loss=0.0877
epoch=29, loss=0.0860
epoch=30, loss=0.0855
valid [full], NDCG@5: 0.6725, HR@5: 0.7785, NDCG@10: 0.7055, HR@10: 0.8835, MRR: 0.6585
valid [sampled], NDCG@5: 0.5470, HR@5: 0.5529, NDCG@10: 0.5679, HR@10: 0.6193, MRR: 0.5664
test [full], NDCG@5: 0.8205, HR@5: 0.9985, NDCG@10: 0.8210, HR@10: 1.0000, MRR: 0.7597
test [sampled], NDCG@5: 0.3276, HR@5: 0.3369, NDCG@10: 0.3883, HR@10: 0.5334, MRR: 0.3781
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=31, loss=0.0888
epoch=32, loss=0.0846
epoch=33, loss=0.0856
epoch=34, loss=0.0840
epoch=35, loss=0.0850
valid [full], NDCG@5: 0.6613, HR@5: 0.7880, NDCG@10: 0.6866, HR@10: 0.8709, MRR: 0.6385
valid [sampled], NDCG@5: 0.5373, HR@5: 0.5479, NDCG@10: 0.5516, HR@10: 0.5925, MRR: 0.5534
test [full], NDCG@5: 0.8250, HR@5: 0.9946, NDCG@10: 0.8268, HR@10: 1.0000, MRR: 0.7674
test [sampled], NDCG@5: 0.3741, HR@5: 0.3920, NDCG@10: 0.4279, HR@10: 0.5634, MRR: 0.4164
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0863
epoch=37, loss=0.0854
epoch=38, loss=0.0839
epoch=39, loss=0.0830
epoch=40, loss=0.0847
valid [full], NDCG@5: 0.6948, HR@5: 0.8123, NDCG@10: 0.7317, HR@10: 0.9332, MRR: 0.6741
valid [sampled], NDCG@5: 0.5509, HR@5: 0.5673, NDCG@10: 0.5846, HR@10: 0.6736, MRR: 0.5713
test [full], NDCG@5: 0.8335, HR@5: 0.9986, NDCG@10: 0.8339, HR@10: 1.0000, MRR: 0.7766
test [sampled], NDCG@5: 0.3499, HR@5: 0.3665, NDCG@10: 0.4082, HR@10: 0.5532, MRR: 0.3953
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/sasrec_best.pth
epoch=41, loss=0.0854
epoch=42, loss=0.0825
epoch=43, loss=0.0817
epoch=44, loss=0.0855
epoch=45, loss=0.0822
valid [full], NDCG@5: 0.6745, HR@5: 0.7934, NDCG@10: 0.7101, HR@10: 0.9107, MRR: 0.6554
valid [sampled], NDCG@5: 0.5449, HR@5: 0.5578, NDCG@10: 0.5644, HR@10: 0.6187, MRR: 0.5621
test [full], NDCG@5: 0.8271, HR@5: 0.9989, NDCG@10: 0.8275, HR@10: 1.0000, MRR: 0.7682
test [sampled], NDCG@5: 0.3740, HR@5: 0.3879, NDCG@10: 0.4268, HR@10: 0.5572, MRR: 0.4176
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0816
epoch=47, loss=0.0819
epoch=48, loss=0.0818
epoch=49, loss=0.0811
epoch=50, loss=0.0820
valid [full], NDCG@5: 0.6759, HR@5: 0.7932, NDCG@10: 0.7078, HR@10: 0.8992, MRR: 0.6564
valid [sampled], NDCG@5: 0.5628, HR@5: 0.5762, NDCG@10: 0.5774, HR@10: 0.6217, MRR: 0.5770
test [full], NDCG@5: 0.8343, HR@5: 0.9949, NDCG@10: 0.8361, HR@10: 1.0000, MRR: 0.7797
test [sampled], NDCG@5: 0.3681, HR@5: 0.3831, NDCG@10: 0.4257, HR@10: 0.5680, MRR: 0.4129
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_attention_bias_ndcg5/attnbias_dstart_ml20_b9_s7/sasrec_last.pth

## Rebuild result tables

In [18]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'use_time_attention_bias': config.get('use_time_attention_bias', False),
            'time_modeling_mode': config.get('time_modeling_mode'),
            'time_encoding': config.get('time_encoding'),
            'time_delta_column': config.get('time_delta_column'),
            'time_bucket_boundaries_parsed': config.get('time_bucket_boundaries_parsed'),
            'time_attention_bias_bucket_count': config.get('time_attention_bias_bucket_count'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

In [19]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)

## NDCG@10 comparison summary

In [20]:
baseline_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
]
timeaware_runs = [
    'attnbias_dstart_ml20_b9_s42',
    'attnbias_dstart_ml20_b9_s2024',
    'attnbias_dstart_ml20_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['time_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['time_variant'] = 'attention_bias_dstart_b9'

df_ndcg10 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'time_variant', 'use_time_embedding', 'use_time_attention_bias', 'time_modeling_mode',
    'time_delta_column', 'time_bucket_boundaries_parsed', 'time_attention_bias_bucket_count',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                        run_name  seed              time_variant  use_time_embedding  use_time_attention_bias time_modeling_mode    time_delta_column             time_bucket_boundaries_parsed time_attention_bias_bucket_count  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     attnbias_dstart_ml20_b9_s7     7  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.731681               0.933234                0.694816              0.812322             0.674079                0.833933              1.000000               0.833460             0.998642            0.776636                    0.584594                  0.673558                   0.550907                 0.567329                0.571303                   0.408188                 0.553189                  0.349894                0.366486               0.395330
1    attnbias_dstart_ml20_b9_s42    42  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.731547               0.976377                0.692852              0.854887             0.657784                0.857427              1.000000               0.844950             0.958941            0.810092                    0.553607                  0.600217                   0.535631                 0.543183                0.557929                   0.535711                 0.621374                  0.504964                0.524491               0.530831
2  attnbias_dstart_ml20_b9_s2024  2024  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.727796               0.977380                0.682637              0.839902             0.653203                0.815191              1.000000               0.800095             0.953875            0.753665                    0.551441                  0.581497                   0.539500                 0.543537                0.560101                   0.369433                 0.517223                  0.311595                0.332384               0.355765
3                 anchor_ml20_s7     7                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.753294               0.961857                0.729167              0.883942             0.691225                0.913637              1.000000               0.903861             0.971918            0.885501                    0.601240                  0.661113                   0.580044                 0.594609                0.597937                   0.480200                 0.667438                  0.420861                0.484209               0.443705
4                anchor_ml20_s42    42                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296              1.000000               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
5              anchor_ml20_s2024  2024                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.736821               0.967429                0.700301              0.850202             0.668534                0.840611              0.999865               0.819421             0.937829            0.789072                    0.574314                  0.616064                   0.557801                 0.563197                0.578608                   0.323103                 0.518524                  0.261120                0.326822               0.292464

In [21]:
summary_ndcg10 = df_ndcg10.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

                         best_valid_full_ndcg@10           best_test_full_ndcg@10           best_valid_full_ndcg@5           best_test_full_ndcg@5           best_valid_full_mrr           best_test_full_mrr           best_valid_sampled_ndcg@10           best_test_sampled_ndcg@10           best_valid_sampled_ndcg@5           best_test_sampled_ndcg@5           best_valid_sampled_mrr           best_test_sampled_mrr
                                            mean       std                   mean       std                   mean       std                  mean       std                mean       std               mean       std                       mean       std                      mean       std                      mean       std                     mean       std                   mean       std                  mean       std
time_variant
attention_bias_dstart_b9                0.730341  0.002206               0.835517  0.021162               0.690102  0.006539              0.826168  0.023299            0.661689  0.010972           0.780131  0.028375                   0.563214  0.018547                  0.437777  0.086999                  0.542013  0.007942                 0.388818  0.102392               0.563111  0.007177              0.427309  0.091809
baseline                                0.746827  0.008788               0.889848  0.042649               0.712751  0.014836              0.879032  0.051864            0.680520  0.011400           0.853805  0.056064                   0.586415  0.013668                  0.422731  0.086620                  0.564734  0.013279                 0.362874  0.088408               0.584993  0.011211              0.388797  0.083699

Interpretation guide for NDCG@10:
- compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` first
- then check whether sampled and MRR move in the same direction
- baseline is reused; only attention-bias runs are newly trained here

## NDCG@5 comparison summary

In [22]:
baseline_runs = [
    'anchor_ml20_s42',
    'anchor_ml20_s2024',
    'anchor_ml20_s7',
]
timeaware_runs = [
    'attnbias_dstart_ml20_b9_s42',
    'attnbias_dstart_ml20_b9_s2024',
    'attnbias_dstart_ml20_b9_s7',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['time_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['time_variant'] = 'attention_bias_dstart_b9'

df_ndcg5 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['time_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'time_variant', 'use_time_embedding', 'use_time_attention_bias', 'time_modeling_mode',
    'time_delta_column', 'time_bucket_boundaries_parsed', 'time_attention_bias_bucket_count',
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]]

                        run_name  seed              time_variant  use_time_embedding  use_time_attention_bias time_modeling_mode    time_delta_column             time_bucket_boundaries_parsed time_attention_bias_bucket_count  best_valid_full_ndcg@10  best_valid_full_hr@10  best_valid_full_ndcg@5  best_valid_full_hr@5  best_valid_full_mrr  best_test_full_ndcg@10  best_test_full_hr@10  best_test_full_ndcg@5  best_test_full_hr@5  best_test_full_mrr  best_valid_sampled_ndcg@10  best_valid_sampled_hr@10  best_valid_sampled_ndcg@5  best_valid_sampled_hr@5  best_valid_sampled_mrr  best_test_sampled_ndcg@10  best_test_sampled_hr@10  best_test_sampled_ndcg@5  best_test_sampled_hr@5  best_test_sampled_mrr
0     attnbias_dstart_ml20_b9_s7     7  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.731681               0.933234                0.694816              0.812322             0.674079                0.833933              1.000000               0.833460             0.998642            0.776636                    0.584594                  0.673558                   0.550907                 0.567329                0.571303                   0.408188                 0.553189                  0.349894                0.366486               0.395330
1    attnbias_dstart_ml20_b9_s42    42  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.728295               0.942107                0.695528              0.834303             0.667054                0.903459              1.000000               0.902459             0.997142            0.870589                    0.570725                  0.624454                   0.549478                 0.557178                0.570069                   0.639984                 0.700095                  0.619380                0.635052               0.640352
2  attnbias_dstart_ml20_b9_s2024  2024  attention_bias_dstart_b9               False                     True     attention_bias  delta_start_seconds  [60.0, 600.0, 3600.0, 86400.0, 604800.0]                                7                 0.727796               0.977380                0.682637              0.839902             0.653203                0.815191              1.000000               0.800095             0.953875            0.753665                    0.551441                  0.581497                   0.539500                 0.543537                0.560101                   0.369433                 0.517223                  0.311595                0.332384               0.355765
3                 anchor_ml20_s7     7                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.753294               0.961857                0.729167              0.883942             0.691225                0.913637              1.000000               0.903861             0.971918            0.885501                    0.601240                  0.661113                   0.580044                 0.594609                0.597937                   0.480200                 0.667438                  0.420861                0.484209               0.443705
4                anchor_ml20_s42    42                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.750367               0.977546                0.708784              0.848505             0.681799                0.915296              1.000000               0.913814             0.995781            0.886842                    0.583692                  0.654340                   0.556357                 0.567822                0.578433                   0.464891                 0.652470                  0.406641                0.473262               0.430220
5              anchor_ml20_s2024  2024                  baseline               False                    False               None   delta_prev_seconds                                      None                             None                 0.736821               0.967429                0.700301              0.850202             0.668534                0.840611              0.999865               0.819421             0.937829            0.789072                    0.574314                  0.616064                   0.557801                 0.563197                0.578608                   0.323103                 0.518524                  0.261120                0.326822               0.292464

In [23]:
summary_ndcg5 = df_ndcg5.groupby('time_variant')[[
    'best_valid_full_ndcg@10', 'best_valid_full_hr@10',
    'best_valid_full_ndcg@5', 'best_valid_full_hr@5',
    'best_valid_full_mrr',
    'best_test_full_ndcg@10', 'best_test_full_hr@10',
    'best_test_full_ndcg@5', 'best_test_full_hr@5',
    'best_test_full_mrr',
    'best_valid_sampled_ndcg@10', 'best_valid_sampled_hr@10',
    'best_valid_sampled_ndcg@5', 'best_valid_sampled_hr@5',
    'best_valid_sampled_mrr',
    'best_test_sampled_ndcg@10', 'best_test_sampled_hr@10',
    'best_test_sampled_ndcg@5', 'best_test_sampled_hr@5',
    'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

                         best_valid_full_ndcg@10           best_valid_full_hr@10           best_valid_full_ndcg@5           best_valid_full_hr@5           best_valid_full_mrr           best_test_full_ndcg@10           best_test_full_hr@10           best_test_full_ndcg@5           best_test_full_hr@5           best_test_full_mrr           best_valid_sampled_ndcg@10           best_valid_sampled_hr@10           best_valid_sampled_ndcg@5           best_valid_sampled_hr@5           best_valid_sampled_mrr           best_test_sampled_ndcg@10           best_test_sampled_hr@10           best_test_sampled_ndcg@5           best_test_sampled_hr@5           best_test_sampled_mrr
                                            mean       std                  mean       std                   mean       std                 mean       std                mean       std                   mean       std                 mean       std                  mean       std                mean       std               mean       std                       mean       std                     mean       std                      mean       std                    mean       std                   mean       std                      mean       std                    mean       std                     mean       std                   mean       std                  mean       std
time_variant
attention_bias_dstart_b9                0.729257  0.002114              0.950907  0.023352               0.690994  0.007246             0.828842  0.014579            0.664779  0.010623               0.850861  0.046505             1.000000  0.000000              0.845338  0.052206             0.98322  0.025424           0.800297  0.061949                   0.568920  0.016650                 0.626503  0.046065                  0.546628  0.006215                0.556015  0.011938               0.567158  0.006142                  0.472535  0.146304                0.590169  0.096883                 0.426956  0.167740               0.444641  0.165781              0.463816  0.154159
baseline                                0.746827  0.008788              0.968944  0.007954               0.712751  0.014836             0.860883  0.019988            0.680520  0.011400               0.889848  0.042649             0.999955  0.000078              0.879032  0.051864             0.96851  0.029126           0.853805  0.056064                   0.586415  0.013668                 0.643839  0.024291                  0.564734  0.013279                0.575209  0.016959               0.584993  0.011211                  0.422731  0.086620                0.612810  0.081997                 0.362874  0.088408               0.428098  0.087878              0.388797  0.083699

Interpretation guide for NDCG@5:
- compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` first
- then check whether sampled and MRR move in the same direction
- baseline is reused; only attention-bias runs are newly trained here