# SASRec Time-Aware BPI2012 Colab Train 01

Colab notebook for the first time-aware SASRec experiment on BPI 2012.

Goals:
- reuse the existing `refine_v3_ml50_do025` baseline results instead of retraining them
- train only the new time-aware runs with time-delta bucket embeddings
- compare baseline vs `8-bucket` vs `9-bucket` under both `NDCG@10` and `NDCG@5` model-selection criteria

In [1]:
import torch

print('torch version:', torch.__version__)
print('cuda available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('gpu name:', torch.cuda.get_device_name(0))

torch version: 2.10.0+cu128
cuda available: True
gpu name: Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
GITHUB_USERNAME = 'hwbuzz'

DRIVE_ROOT = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction'
REPO_DIR = '/content/time-aware-behavior-prediction'

DATA_DIR = f'{DRIVE_ROOT}/data/processed/bpi2012_complete_only'
BASELINE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012'
BASELINE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5'
TIMEAWARE_NDCG10_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012'
TIMEAWARE_NDCG5_OUTPUT_DIR = '/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5'
NOTEBOOK_DIR = f'{DRIVE_ROOT}/notebooks'

print('DATA_DIR:', DATA_DIR)
print('BASELINE_NDCG10_OUTPUT_DIR:', BASELINE_NDCG10_OUTPUT_DIR)
print('BASELINE_NDCG5_OUTPUT_DIR:', BASELINE_NDCG5_OUTPUT_DIR)
print('TIMEAWARE_NDCG10_OUTPUT_DIR:', TIMEAWARE_NDCG10_OUTPUT_DIR)
print('TIMEAWARE_NDCG5_OUTPUT_DIR:', TIMEAWARE_NDCG5_OUTPUT_DIR)

DATA_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/data/processed/bpi2012_complete_only
BASELINE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012
BASELINE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_bpi2012_ndcg5
TIMEAWARE_NDCG10_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012
TIMEAWARE_NDCG5_OUTPUT_DIR: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5

In [4]:
!mkdir -p "$NOTEBOOK_DIR"
!mkdir -p "$DATA_DIR"
!mkdir -p "$BASELINE_NDCG10_OUTPUT_DIR"
!mkdir -p "$BASELINE_NDCG5_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG10_OUTPUT_DIR"
!mkdir -p "$TIMEAWARE_NDCG5_OUTPUT_DIR"

In [5]:
%cd /content
!test -d time-aware-behavior-prediction || git clone https://github.com/$GITHUB_USERNAME/time-aware-behavior-prediction.git
%cd /content/time-aware-behavior-prediction

/content
/content/time-aware-behavior-prediction

In [6]:
# If you need the latest code from GitHub, uncomment below.
# %cd /content/time-aware-behavior-prediction
# !git pull

In [7]:
%cd /content/time-aware-behavior-prediction

skip_packages = ['pywinpty']

with open('requirements.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open('requirements_colab.txt', 'w', encoding='utf-8') as f:
    for line in lines:
        pkg = line.strip().lower()
        if not any(name in pkg for name in skip_packages):
            f.write(line)

print('created requirements_colab.txt')

/content/time-aware-behavior-prediction
created requirements_colab.txt

In [8]:
!pip install -r requirements_colab.txt

Requirement already satisfied: attrs==26.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 1)) (26.1.0)
Requirement already satisfied: fastjsonschema==2.21.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 2)) (2.21.2)
Requirement already satisfied: jsonschema==4.26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 3)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 4)) (2025.9.1)
Requirement already satisfied: jupyterlab_widgets==3.0.16 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 5)) (3.0.16)
Requirement already satisfied: lark==1.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 6)) (1.3.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 7)) (3.0.3)
Requirement already satisfied: mistune==3.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 8)) (3.2.0)
Requirement already satisfied: nbclient==0.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 9)) (0.10.4)
Requirement already satisfied: nbformat==5.10.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 10)) (5.10.4)
Requirement already satisfied: nest-asyncio==1.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 11)) (1.6.0)
Requirement already satisfied: overrides==7.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 12)) (7.7.0)
Requirement already satisfied: packaging==26.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 13)) (26.0)
Requirement already satisfied: pandas==3.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 14)) (3.0.2)
Requirement already satisfied: pandocfilters==1.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 15)) (1.5.1)
Requirement already satisfied: parso==0.8.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 16)) (0.8.6)
Requirement already satisfied: platformdirs==4.9.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 17)) (4.9.4)
Requirement already satisfied: prometheus_client==0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 18)) (0.24.1)
Requirement already satisfied: psutil==7.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 19)) (7.2.2)
Requirement already satisfied: pure_eval==0.2.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 20)) (0.2.3)
Requirement already satisfied: pycparser==3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 21)) (3.0)
Requirement already satisfied: Pygments==2.19.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 22)) (2.19.2)
Requirement already satisfied: python-json-logger==4.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 23)) (4.0.0)
Requirement already satisfied: PyYAML==6.0.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 24)) (6.0.3)
Requirement already satisfied: pyzmq==27.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 25)) (27.1.0)
Requirement already satisfied: referencing==0.37.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 26)) (0.37.0)
Requirement already satisfied: rfc3986-validator==0.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 27)) (0.1.1)
Requirement already satisfied: rpds-py==0.30.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 28)) (0.30.0)
Requirement already satisfied: Send2Trash==2.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 29)) (2.1.0)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 30)) (1.17.0)
Requirement already satisfied: soupsieve==2.8.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 31)) (2.8.3)
Requirement already satisfied: tinycss2==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 32)) (1.4.0)
Requirement already satisfied: tornado==6.5.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 33)) (6.5.5)
Requirement already satisfied: traitlets==5.14.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 34)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 35)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 36)) (2025.3)
Requirement already satisfied: uri-template==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 37)) (1.3.0)
Requirement already satisfied: urllib3==2.6.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 38)) (2.6.3)
Requirement already satisfied: wcwidth==0.6.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 39)) (0.6.0)
Requirement already satisfied: webcolors==25.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 40)) (25.10.0)
Requirement already satisfied: webencodings==0.5.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 41)) (0.5.1)
Requirement already satisfied: websocket-client==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 42)) (1.9.0)
Requirement already satisfied: widgetsnbextension==4.0.15 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 43)) (4.0.15)
Requirement already satisfied: torch>=1.6 in /usr/local/lib/python3.12/dist-packages (from -r requirements_colab.txt (line 44)) (2.10.0+cu128)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbclient==0.10.4->-r requirements_colab.txt (line 9)) (5.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==3.0.2->-r requirements_colab.txt (line 14)) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6->-r requirements_colab.txt (line 44)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6->-r requirements_colab.txt (line 44)) (1.5.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient==0.10.4->-r requirements_colab.txt (line 9)) (0.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6->-r requirements_colab.txt (line 44)) (1.3.0)

In [9]:
!ls "$DATA_DIR"

events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

In [10]:
%cd /content/time-aware-behavior-prediction
!mkdir -p data/processed
!cp -r "$DATA_DIR" data/processed/
!ls data/processed/bpi2012_complete_only

/content/time-aware-behavior-prediction
events_complete_only_filtered.csv  sasrec_interactions.csv
events_encoded_time_features.csv   sasrec_interactions.txt
item_map.csv			   user_map.csv

## Experiment design

Fixed baseline setting:
- `refine_v3_ml50_do025`
- `hidden_units=50, num_blocks=2, num_heads=1, maxlen=50, lr=0.001, dropout=0.25`
- seeds: `42`, `2024`

Comparison targets:
- baseline (reuse existing completed runs)
- time-aware `8-bucket`
- time-aware `9-bucket`

Bucket designs:
- `8-bucket`: `padding`, `first`, `zero-gap`, `(0,1m)`, `[1m,10m)`, `[10m,1h)`, `[1h,1d)`, `[>=1d]`
- `9-bucket`: `padding`, `first`, `zero-gap`, `(0,1m)`, `[1m,10m)`, `[10m,1h)`, `[1h,1d)`, `[1d,7d)`, `[>=7d]`

## Check existing baseline runs

These baseline runs should already exist and must not be retrained.

In [11]:
from pathlib import Path

baseline_ndcg10_runs = [
    'refine_v3_ml50_do025_seed42',
    'refine_v3_ml50_do025_seed2024',
]
baseline_ndcg5_runs = [
    'refine_v3_ml50_do025_seed42_ndcg5',
    'refine_v3_ml50_do025_seed2024_ndcg5',
]

for label, output_dir, run_names in [
    ('Baseline NDCG@10', Path(BASELINE_NDCG10_OUTPUT_DIR), baseline_ndcg10_runs),
    ('Baseline NDCG@5', Path(BASELINE_NDCG5_OUTPUT_DIR), baseline_ndcg5_runs),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'MISSING')

================================================================================
Baseline NDCG@10
refine_v3_ml50_do025_seed42 EXISTS
refine_v3_ml50_do025_seed2024 EXISTS
================================================================================
Baseline NDCG@5
refine_v3_ml50_do025_seed42_ndcg5 EXISTS
refine_v3_ml50_do025_seed2024_ndcg5 EXISTS

## Check planned time-aware runs

Only train runs that are still missing.

In [12]:
planned_ndcg10 = [
    'timeaware_refine_v3_ml50_do025_seed42_b8',
    'timeaware_refine_v3_ml50_do025_seed2024_b8',
    'timeaware_refine_v3_ml50_do025_seed42_b9',
    'timeaware_refine_v3_ml50_do025_seed2024_b9',
]
planned_ndcg5 = [
    'timeaware_refine_v3_ml50_do025_seed42_b8_ndcg5',
    'timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5',
    'timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5',
    'timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5',
]

for label, output_dir, run_names in [
    ('Time-aware NDCG@10', Path(TIMEAWARE_NDCG10_OUTPUT_DIR), planned_ndcg10),
    ('Time-aware NDCG@5', Path(TIMEAWARE_NDCG5_OUTPUT_DIR), planned_ndcg5),
]:
    print('=' * 80)
    print(label)
    for run_name in run_names:
        run_dir = output_dir / run_name
        print(run_name, 'EXISTS' if run_dir.exists() else 'OK')

================================================================================
Time-aware NDCG@10
timeaware_refine_v3_ml50_do025_seed42_b8 EXISTS
timeaware_refine_v3_ml50_do025_seed2024_b8 OK
timeaware_refine_v3_ml50_do025_seed42_b9 OK
timeaware_refine_v3_ml50_do025_seed2024_b9 OK
================================================================================
Time-aware NDCG@5
timeaware_refine_v3_ml50_do025_seed42_b8_ndcg5 OK
timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5 OK
timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5 OK
timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5 OK

## Train time-aware runs for `NDCG@10`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_refine_v3_ml50_do025_seed42_b8

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed42_b8 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8
epoch=1, loss=0.5230
epoch=2, loss=0.2295
epoch=3, loss=0.1714
epoch=4, loss=0.1357
epoch=5, loss=0.1166
valid [full], NDCG@5: 0.3808, HR@5: 0.5651, NDCG@10: 0.4552, HR@10: 0.7840, MRR: 0.3650
valid [sampled], NDCG@5: 0.5471, HR@5: 0.5583, NDCG@10: 0.5616, HR@10: 0.6031, MRR: 0.5610
test [full], NDCG@5: 0.2770, HR@5: 0.4411, NDCG@10: 0.3223, HR@10: 0.5745, MRR: 0.2684
test [sampled], NDCG@5: 0.4086, HR@5: 0.4214, NDCG@10: 0.4495, HR@10: 0.5519, MRR: 0.4423
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/sasrec_best.pth
epoch=6, loss=0.1052
epoch=7, loss=0.0972
epoch=8, loss=0.0942
epoch=9, loss=0.0901
epoch=10, loss=0.0862
valid [full], NDCG@5: 0.3044, HR@5: 0.4288, NDCG@10: 0.4234, HR@10: 0.7908, MRR: 0.3297
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5676, NDCG@10: 0.5743, HR@10: 0.6221, MRR: 0.5726
test [full], NDCG@5: 0.2871, HR@5: 0.5503, NDCG@10: 0.3691, HR@10: 0.8010, MRR: 0.2555
test [sampled], NDCG@5: 0.4635, HR@5: 0.4990, NDCG@10: 0.5317, HR@10: 0.7139, MRR: 0.4963
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0852
epoch=12, loss=0.0831
epoch=13, loss=0.0810
epoch=14, loss=0.0792
epoch=15, loss=0.0807
valid [full], NDCG@5: 0.3119, HR@5: 0.4390, NDCG@10: 0.4232, HR@10: 0.7799, MRR: 0.3337
valid [sampled], NDCG@5: 0.5502, HR@5: 0.5652, NDCG@10: 0.5715, HR@10: 0.6325, MRR: 0.5673
test [full], NDCG@5: 0.2829, HR@5: 0.5216, NDCG@10: 0.4105, HR@10: 0.9145, MRR: 0.2664
test [sampled], NDCG@5: 0.5880, HR@5: 0.6492, NDCG@10: 0.6475, HR@10: 0.8313, MRR: 0.6010
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0796
epoch=17, loss=0.0761
epoch=18, loss=0.0740
epoch=19, loss=0.0748
epoch=20, loss=0.0761
valid [full], NDCG@5: 0.3529, HR@5: 0.5246, NDCG@10: 0.4405, HR@10: 0.7906, MRR: 0.3507
valid [sampled], NDCG@5: 0.5450, HR@5: 0.5526, NDCG@10: 0.5594, HR@10: 0.5982, MRR: 0.5626
test [full], NDCG@5: 0.3662, HR@5: 0.6323, NDCG@10: 0.4836, HR@10: 0.9926, MRR: 0.3297
test [sampled], NDCG@5: 0.4665, HR@5: 0.4740, NDCG@10: 0.5131, HR@10: 0.6251, MRR: 0.5043
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0748
epoch=22, loss=0.0753
epoch=23, loss=0.0751
epoch=24, loss=0.0745
epoch=25, loss=0.0728
valid [full], NDCG@5: 0.3290, HR@5: 0.4887, NDCG@10: 0.4244, HR@10: 0.7704, MRR: 0.3389
valid [sampled], NDCG@5: 0.5515, HR@5: 0.5620, NDCG@10: 0.5707, HR@10: 0.6226, MRR: 0.5694
test [full], NDCG@5: 0.3362, HR@5: 0.5909, NDCG@10: 0.4723, HR@10: 0.9907, MRR: 0.3140
test [sampled], NDCG@5: 0.5321, HR@5: 0.5756, NDCG@10: 0.5911, HR@10: 0.7595, MRR: 0.5548
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0710
epoch=27, loss=0.0736
epoch=28, loss=0.0721
epoch=29, loss=0.0722
epoch=30, loss=0.0718
valid [full], NDCG@5: 0.3664, HR@5: 0.5582, NDCG@10: 0.4988, HR@10: 0.9718, MRR: 0.3609
valid [sampled], NDCG@5: 0.5526, HR@5: 0.5645, NDCG@10: 0.5801, HR@10: 0.6518, MRR: 0.5745
test [full], NDCG@5: 0.4195, HR@5: 0.6569, NDCG@10: 0.5364, HR@10: 0.9929, MRR: 0.3946
test [sampled], NDCG@5: 0.5372, HR@5: 0.5455, NDCG@10: 0.5897, HR@10: 0.7141, MRR: 0.5730
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/sasrec_best.pth
epoch=31, loss=0.0712
epoch=32, loss=0.0700
epoch=33, loss=0.0720
epoch=34, loss=0.0701
epoch=35, loss=0.0708
valid [full], NDCG@5: 0.3272, HR@5: 0.4771, NDCG@10: 0.4322, HR@10: 0.7942, MRR: 0.3407
valid [sampled], NDCG@5: 0.5526, HR@5: 0.5625, NDCG@10: 0.5709, HR@10: 0.6200, MRR: 0.5701
test [full], NDCG@5: 0.3150, HR@5: 0.5806, NDCG@10: 0.4530, HR@10: 0.9905, MRR: 0.2893
test [sampled], NDCG@5: 0.5117, HR@5: 0.5555, NDCG@10: 0.5752, HR@10: 0.7546, MRR: 0.5373
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0706
epoch=37, loss=0.0703
epoch=38, loss=0.0688
epoch=39, loss=0.0712
epoch=40, loss=0.0694
valid [full], NDCG@5: 0.3395, HR@5: 0.5050, NDCG@10: 0.4876, HR@10: 0.9735, MRR: 0.3479
valid [sampled], NDCG@5: 0.5428, HR@5: 0.5513, NDCG@10: 0.5625, HR@10: 0.6137, MRR: 0.5626
test [full], NDCG@5: 0.3992, HR@5: 0.6731, NDCG@10: 0.5104, HR@10: 0.9887, MRR: 0.3615
test [sampled], NDCG@5: 0.5807, HR@5: 0.5874, NDCG@10: 0.6244, HR@10: 0.7279, MRR: 0.6113
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0712
epoch=42, loss=0.0726
epoch=43, loss=0.0701
epoch=44, loss=0.0706
epoch=45, loss=0.0707
valid [full], NDCG@5: 0.3933, HR@5: 0.6116, NDCG@10: 0.5184, HR@10: 0.9837, MRR: 0.3785
valid [sampled], NDCG@5: 0.5424, HR@5: 0.5513, NDCG@10: 0.5588, HR@10: 0.6028, MRR: 0.5591
test [full], NDCG@5: 0.5069, HR@5: 0.8672, NDCG@10: 0.5497, HR@10: 0.9915, MRR: 0.4100
test [sampled], NDCG@5: 0.5919, HR@5: 0.5968, NDCG@10: 0.6146, HR@10: 0.6702, MRR: 0.6168
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/sasrec_best.pth
epoch=46, loss=0.0679
epoch=47, loss=0.0672
epoch=48, loss=0.0685
epoch=49, loss=0.0682
epoch=50, loss=0.0692
valid [full], NDCG@5: 0.3243, HR@5: 0.4704, NDCG@10: 0.4747, HR@10: 0.9524, MRR: 0.3401
valid [sampled], NDCG@5: 0.5411, HR@5: 0.5529, NDCG@10: 0.5625, HR@10: 0.6205, MRR: 0.5621
test [full], NDCG@5: 0.4349, HR@5: 0.7285, NDCG@10: 0.5233, HR@10: 0.9864, MRR: 0.3805
test [sampled], NDCG@5: 0.5837, HR@5: 0.5975, NDCG@10: 0.6320, HR@10: 0.7517, MRR: 0.6123
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware_refine_v3_ml50_do025_seed42_b8/sasrec_last.pth

### timeaware_refine_v3_ml50_do025_seed2024_b8

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed2024_b8 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8
epoch=1, loss=0.5519
epoch=2, loss=0.2364
epoch=3, loss=0.1674
epoch=4, loss=0.1325
epoch=5, loss=0.1179
valid [full], NDCG@5: 0.3085, HR@5: 0.4196, NDCG@10: 0.4362, HR@10: 0.8359, MRR: 0.3342
valid [sampled], NDCG@5: 0.5429, HR@5: 0.5470, NDCG@10: 0.5507, HR@10: 0.5718, MRR: 0.5610
test [full], NDCG@5: 0.1770, HR@5: 0.3432, NDCG@10: 0.3535, HR@10: 0.8840, MRR: 0.2085
test [sampled], NDCG@5: 0.6434, HR@5: 0.6537, NDCG@10: 0.6671, HR@10: 0.7284, MRR: 0.6627
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_best.pth
epoch=6, loss=0.1063
epoch=7, loss=0.0971
epoch=8, loss=0.0929
epoch=9, loss=0.0884
epoch=10, loss=0.0878
valid [full], NDCG@5: 0.3030, HR@5: 0.4150, NDCG@10: 0.4625, HR@10: 0.9295, MRR: 0.3342
valid [sampled], NDCG@5: 0.5316, HR@5: 0.5425, NDCG@10: 0.5462, HR@10: 0.5878, MRR: 0.5478
test [full], NDCG@5: 0.2260, HR@5: 0.4359, NDCG@10: 0.4042, HR@10: 0.9762, MRR: 0.2363
test [sampled], NDCG@5: 0.6723, HR@5: 0.7028, NDCG@10: 0.7090, HR@10: 0.8166, MRR: 0.6851
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_best.pth
epoch=11, loss=0.0851
epoch=12, loss=0.0843
epoch=13, loss=0.0825
epoch=14, loss=0.0805
epoch=15, loss=0.0801
valid [full], NDCG@5: 0.2879, HR@5: 0.3904, NDCG@10: 0.4628, HR@10: 0.9501, MRR: 0.3277
valid [sampled], NDCG@5: 0.5420, HR@5: 0.5509, NDCG@10: 0.5559, HR@10: 0.5940, MRR: 0.5591
test [full], NDCG@5: 0.2746, HR@5: 0.5139, NDCG@10: 0.4314, HR@10: 0.9793, MRR: 0.2674
test [sampled], NDCG@5: 0.5483, HR@5: 0.5716, NDCG@10: 0.6052, HR@10: 0.7513, MRR: 0.5787
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_015.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_best.pth
epoch=16, loss=0.0771
epoch=17, loss=0.0769
epoch=18, loss=0.0762
epoch=19, loss=0.0761
epoch=20, loss=0.0754
valid [full], NDCG@5: 0.2936, HR@5: 0.4110, NDCG@10: 0.4741, HR@10: 0.9779, MRR: 0.3305
valid [sampled], NDCG@5: 0.5468, HR@5: 0.5595, NDCG@10: 0.5636, HR@10: 0.6124, MRR: 0.5656
test [full], NDCG@5: 0.3684, HR@5: 0.7201, NDCG@10: 0.4560, HR@10: 0.9887, MRR: 0.2932
test [sampled], NDCG@5: 0.4776, HR@5: 0.4908, NDCG@10: 0.5199, HR@10: 0.6247, MRR: 0.5127
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_best.pth
epoch=21, loss=0.0741
epoch=22, loss=0.0737
epoch=23, loss=0.0724
epoch=24, loss=0.0737
epoch=25, loss=0.0719
valid [full], NDCG@5: 0.2906, HR@5: 0.3935, NDCG@10: 0.4824, HR@10: 0.9723, MRR: 0.3413
valid [sampled], NDCG@5: 0.5422, HR@5: 0.5569, NDCG@10: 0.5706, HR@10: 0.6471, MRR: 0.5638
test [full], NDCG@5: 0.3781, HR@5: 0.7327, NDCG@10: 0.4661, HR@10: 0.9945, MRR: 0.3030
test [sampled], NDCG@5: 0.5138, HR@5: 0.5240, NDCG@10: 0.5486, HR@10: 0.6353, MRR: 0.5465
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_best.pth
epoch=26, loss=0.0724
epoch=27, loss=0.0710
epoch=28, loss=0.0727
epoch=29, loss=0.0732
epoch=30, loss=0.0711
valid [full], NDCG@5: 0.3193, HR@5: 0.4497, NDCG@10: 0.4950, HR@10: 0.9859, MRR: 0.3520
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5701, NDCG@10: 0.5889, HR@10: 0.6763, MRR: 0.5783
test [full], NDCG@5: 0.4001, HR@5: 0.7761, NDCG@10: 0.4743, HR@10: 0.9965, MRR: 0.3119
test [sampled], NDCG@5: 0.4828, HR@5: 0.4948, NDCG@10: 0.5218, HR@10: 0.6191, MRR: 0.5182
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_best.pth
epoch=31, loss=0.0722
epoch=32, loss=0.0709
epoch=33, loss=0.0712
epoch=34, loss=0.0710
epoch=35, loss=0.0697
valid [full], NDCG@5: 0.3151, HR@5: 0.4381, NDCG@10: 0.4932, HR@10: 0.9830, MRR: 0.3509
valid [sampled], NDCG@5: 0.5598, HR@5: 0.5723, NDCG@10: 0.5946, HR@10: 0.6826, MRR: 0.5851
test [full], NDCG@5: 0.4132, HR@5: 0.7265, NDCG@10: 0.5015, HR@10: 0.9938, MRR: 0.3509
test [sampled], NDCG@5: 0.5087, HR@5: 0.5165, NDCG@10: 0.5422, HR@10: 0.6243, MRR: 0.5426
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0710
epoch=37, loss=0.0679
epoch=38, loss=0.0683
epoch=39, loss=0.0706
epoch=40, loss=0.0692
valid [full], NDCG@5: 0.3433, HR@5: 0.4933, NDCG@10: 0.5042, HR@10: 0.9770, MRR: 0.3650
valid [sampled], NDCG@5: 0.5380, HR@5: 0.5467, NDCG@10: 0.5665, HR@10: 0.6371, MRR: 0.5624
test [full], NDCG@5: 0.4565, HR@5: 0.7608, NDCG@10: 0.5346, HR@10: 0.9916, MRR: 0.3936
test [sampled], NDCG@5: 0.5162, HR@5: 0.5267, NDCG@10: 0.5506, HR@10: 0.6364, MRR: 0.5485
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_best.pth
epoch=41, loss=0.0700
epoch=42, loss=0.0699
epoch=43, loss=0.0701
epoch=44, loss=0.0701
epoch=45, loss=0.0685
valid [full], NDCG@5: 0.3208, HR@5: 0.4500, NDCG@10: 0.4930, HR@10: 0.9831, MRR: 0.3508
valid [sampled], NDCG@5: 0.5292, HR@5: 0.5416, NDCG@10: 0.5564, HR@10: 0.6272, MRR: 0.5529
test [full], NDCG@5: 0.4090, HR@5: 0.7390, NDCG@10: 0.4915, HR@10: 0.9897, MRR: 0.3387
test [sampled], NDCG@5: 0.5143, HR@5: 0.5249, NDCG@10: 0.5501, HR@10: 0.6385, MRR: 0.5469
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0678
epoch=47, loss=0.0682
epoch=48, loss=0.0693
epoch=49, loss=0.0683
epoch=50, loss=0.0694
valid [full], NDCG@5: 0.3245, HR@5: 0.4567, NDCG@10: 0.4969, HR@10: 0.9837, MRR: 0.3547
valid [sampled], NDCG@5: 0.5472, HR@5: 0.5620, NDCG@10: 0.5772, HR@10: 0.6575, MRR: 0.5711
test [full], NDCG@5: 0.4459, HR@5: 0.7371, NDCG@10: 0.5301, HR@10: 0.9916, MRR: 0.3887
test [sampled], NDCG@5: 0.4995, HR@5: 0.5123, NDCG@10: 0.5338, HR@10: 0.6219, MRR: 0.5315
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b8/sasrec_last.pth

### timeaware_refine_v3_ml50_do025_seed42_b9

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed42_b9 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9
epoch=1, loss=0.5209
epoch=2, loss=0.2295
epoch=3, loss=0.1706
epoch=4, loss=0.1350
epoch=5, loss=0.1166
valid [full], NDCG@5: 0.3670, HR@5: 0.5348, NDCG@10: 0.4507, HR@10: 0.7846, MRR: 0.3604
valid [sampled], NDCG@5: 0.5448, HR@5: 0.5564, NDCG@10: 0.5597, HR@10: 0.6023, MRR: 0.5586
test [full], NDCG@5: 0.2480, HR@5: 0.3927, NDCG@10: 0.3059, HR@10: 0.5675, MRR: 0.2506
test [sampled], NDCG@5: 0.3852, HR@5: 0.3956, NDCG@10: 0.4367, HR@10: 0.5608, MRR: 0.4243
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/sasrec_best.pth
epoch=6, loss=0.1054
epoch=7, loss=0.0975
epoch=8, loss=0.0945
epoch=9, loss=0.0902
epoch=10, loss=0.0861
valid [full], NDCG@5: 0.3118, HR@5: 0.4466, NDCG@10: 0.4260, HR@10: 0.7902, MRR: 0.3309
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5688, NDCG@10: 0.5725, HR@10: 0.6127, MRR: 0.5733
test [full], NDCG@5: 0.2622, HR@5: 0.4931, NDCG@10: 0.3592, HR@10: 0.7860, MRR: 0.2477
test [sampled], NDCG@5: 0.4266, HR@5: 0.4684, NDCG@10: 0.5076, HR@10: 0.7235, MRR: 0.4636
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0854
epoch=12, loss=0.0831
epoch=13, loss=0.0809
epoch=14, loss=0.0796
epoch=15, loss=0.0809
valid [full], NDCG@5: 0.3157, HR@5: 0.4429, NDCG@10: 0.4332, HR@10: 0.7931, MRR: 0.3428
valid [sampled], NDCG@5: 0.5549, HR@5: 0.5687, NDCG@10: 0.5750, HR@10: 0.6323, MRR: 0.5719
test [full], NDCG@5: 0.3416, HR@5: 0.5955, NDCG@10: 0.4731, HR@10: 0.9920, MRR: 0.3167
test [sampled], NDCG@5: 0.5751, HR@5: 0.6053, NDCG@10: 0.6301, HR@10: 0.7786, MRR: 0.6004
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0797
epoch=17, loss=0.0762
epoch=18, loss=0.0743
epoch=19, loss=0.0749
epoch=20, loss=0.0762
valid [full], NDCG@5: 0.3376, HR@5: 0.4955, NDCG@10: 0.4897, HR@10: 0.9798, MRR: 0.3489
valid [sampled], NDCG@5: 0.5397, HR@5: 0.5492, NDCG@10: 0.5539, HR@10: 0.5941, MRR: 0.5577
test [full], NDCG@5: 0.3750, HR@5: 0.6445, NDCG@10: 0.4962, HR@10: 0.9915, MRR: 0.3443
test [sampled], NDCG@5: 0.4638, HR@5: 0.4699, NDCG@10: 0.5048, HR@10: 0.6023, MRR: 0.5014
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_020.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/sasrec_best.pth
epoch=21, loss=0.0747
epoch=22, loss=0.0751
epoch=23, loss=0.0753
epoch=24, loss=0.0746
epoch=25, loss=0.0729
valid [full], NDCG@5: 0.3159, HR@5: 0.4579, NDCG@10: 0.4854, HR@10: 0.9669, MRR: 0.3459
valid [sampled], NDCG@5: 0.5618, HR@5: 0.5745, NDCG@10: 0.5789, HR@10: 0.6277, MRR: 0.5774
test [full], NDCG@5: 0.3381, HR@5: 0.5849, NDCG@10: 0.4784, HR@10: 0.9886, MRR: 0.3221
test [sampled], NDCG@5: 0.5577, HR@5: 0.5701, NDCG@10: 0.6060, HR@10: 0.7245, MRR: 0.5894
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0712
epoch=27, loss=0.0740
epoch=28, loss=0.0723
epoch=29, loss=0.0723
epoch=30, loss=0.0717
valid [full], NDCG@5: 0.3509, HR@5: 0.5332, NDCG@10: 0.4926, HR@10: 0.9766, MRR: 0.3520
valid [sampled], NDCG@5: 0.5424, HR@5: 0.5576, NDCG@10: 0.5724, HR@10: 0.6528, MRR: 0.5649
test [full], NDCG@5: 0.4716, HR@5: 0.7943, NDCG@10: 0.5392, HR@10: 0.9930, MRR: 0.3990
test [sampled], NDCG@5: 0.5987, HR@5: 0.6076, NDCG@10: 0.6427, HR@10: 0.7482, MRR: 0.6287
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/sasrec_best.pth
epoch=31, loss=0.0713
epoch=32, loss=0.0701
epoch=33, loss=0.0718
epoch=34, loss=0.0702
epoch=35, loss=0.0708
valid [full], NDCG@5: 0.3301, HR@5: 0.4806, NDCG@10: 0.4853, HR@10: 0.9769, MRR: 0.3446
valid [sampled], NDCG@5: 0.5434, HR@5: 0.5530, NDCG@10: 0.5611, HR@10: 0.6085, MRR: 0.5615
test [full], NDCG@5: 0.3491, HR@5: 0.6008, NDCG@10: 0.4843, HR@10: 0.9922, MRR: 0.3286
test [sampled], NDCG@5: 0.5785, HR@5: 0.5829, NDCG@10: 0.6056, HR@10: 0.6707, MRR: 0.6059
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0710
epoch=37, loss=0.0703
epoch=38, loss=0.0690
epoch=39, loss=0.0713
epoch=40, loss=0.0694
valid [full], NDCG@5: 0.3495, HR@5: 0.5332, NDCG@10: 0.4914, HR@10: 0.9773, MRR: 0.3503
valid [sampled], NDCG@5: 0.5538, HR@5: 0.5620, NDCG@10: 0.5697, HR@10: 0.6124, MRR: 0.5698
test [full], NDCG@5: 0.3836, HR@5: 0.6415, NDCG@10: 0.5035, HR@10: 0.9910, MRR: 0.3529
test [sampled], NDCG@5: 0.6093, HR@5: 0.6159, NDCG@10: 0.6421, HR@10: 0.7212, MRR: 0.6343
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0712
epoch=42, loss=0.0723
epoch=43, loss=0.0700
epoch=44, loss=0.0705
epoch=45, loss=0.0709
valid [full], NDCG@5: 0.4188, HR@5: 0.6645, NDCG@10: 0.5316, HR@10: 0.9875, MRR: 0.3920
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5703, NDCG@10: 0.5756, HR@10: 0.6233, MRR: 0.5745
test [full], NDCG@5: 0.4344, HR@5: 0.6608, NDCG@10: 0.5501, HR@10: 0.9938, MRR: 0.4118
test [sampled], NDCG@5: 0.6417, HR@5: 0.6872, NDCG@10: 0.6841, HR@10: 0.8175, MRR: 0.6520
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/sasrec_best.pth
epoch=46, loss=0.0680
epoch=47, loss=0.0668
epoch=48, loss=0.0687
epoch=49, loss=0.0683
epoch=50, loss=0.0691
valid [full], NDCG@5: 0.2971, HR@5: 0.4115, NDCG@10: 0.4820, HR@10: 0.9888, MRR: 0.3363
valid [sampled], NDCG@5: 0.5603, HR@5: 0.5727, NDCG@10: 0.5814, HR@10: 0.6389, MRR: 0.5802
test [full], NDCG@5: 0.3582, HR@5: 0.5966, NDCG@10: 0.4919, HR@10: 0.9935, MRR: 0.3389
test [sampled], NDCG@5: 0.6271, HR@5: 0.6908, NDCG@10: 0.6827, HR@10: 0.8604, MRR: 0.6356
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed42_b9/sasrec_last.pth

### timeaware_refine_v3_ml50_do025_seed2024_b9

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed2024_b9 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012" \
  --selection_metric full_valid_ndcg@10 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@10
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9
epoch=1, loss=0.5482
epoch=2, loss=0.2356
epoch=3, loss=0.1668
epoch=4, loss=0.1322
epoch=5, loss=0.1178
valid [full], NDCG@5: 0.3212, HR@5: 0.4373, NDCG@10: 0.4419, HR@10: 0.8269, MRR: 0.3438
valid [sampled], NDCG@5: 0.5618, HR@5: 0.5680, NDCG@10: 0.5733, HR@10: 0.6042, MRR: 0.5809
test [full], NDCG@5: 0.2013, HR@5: 0.4035, NDCG@10: 0.3591, HR@10: 0.8761, MRR: 0.2163
test [sampled], NDCG@5: 0.6374, HR@5: 0.6534, NDCG@10: 0.6654, HR@10: 0.7416, MRR: 0.6562
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/sasrec_best.pth
epoch=6, loss=0.1066
epoch=7, loss=0.0974
epoch=8, loss=0.0929
epoch=9, loss=0.0885
epoch=10, loss=0.0875
valid [full], NDCG@5: 0.2984, HR@5: 0.4138, NDCG@10: 0.4688, HR@10: 0.9610, MRR: 0.3311
valid [sampled], NDCG@5: 0.5543, HR@5: 0.5655, NDCG@10: 0.5669, HR@10: 0.6042, MRR: 0.5699
test [full], NDCG@5: 0.2183, HR@5: 0.4307, NDCG@10: 0.3998, HR@10: 0.9822, MRR: 0.2290
test [sampled], NDCG@5: 0.4755, HR@5: 0.5616, NDCG@10: 0.5577, HR@10: 0.8136, MRR: 0.4911
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_010.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/sasrec_best.pth
epoch=11, loss=0.0852
epoch=12, loss=0.0841
epoch=13, loss=0.0823
epoch=14, loss=0.0803
epoch=15, loss=0.0793
valid [full], NDCG@5: 0.2851, HR@5: 0.3853, NDCG@10: 0.4661, HR@10: 0.9579, MRR: 0.3286
valid [sampled], NDCG@5: 0.5627, HR@5: 0.5724, NDCG@10: 0.5752, HR@10: 0.6108, MRR: 0.5786
test [full], NDCG@5: 0.2588, HR@5: 0.5101, NDCG@10: 0.4150, HR@10: 0.9789, MRR: 0.2475
test [sampled], NDCG@5: 0.3306, HR@5: 0.3797, NDCG@10: 0.4268, HR@10: 0.6827, MRR: 0.3731
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0767
epoch=17, loss=0.0766
epoch=18, loss=0.0755
epoch=19, loss=0.0759
epoch=20, loss=0.0748
valid [full], NDCG@5: 0.3053, HR@5: 0.4394, NDCG@10: 0.4680, HR@10: 0.9473, MRR: 0.3331
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5705, NDCG@10: 0.5706, HR@10: 0.6071, MRR: 0.5747
test [full], NDCG@5: 0.3713, HR@5: 0.7278, NDCG@10: 0.4548, HR@10: 0.9788, MRR: 0.2947
test [sampled], NDCG@5: 0.4149, HR@5: 0.4408, NDCG@10: 0.4681, HR@10: 0.6075, MRR: 0.4502
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0740
epoch=22, loss=0.0736
epoch=23, loss=0.0725
epoch=24, loss=0.0736
epoch=25, loss=0.0718
valid [full], NDCG@5: 0.2992, HR@5: 0.4160, NDCG@10: 0.4757, HR@10: 0.9440, MRR: 0.3427
valid [sampled], NDCG@5: 0.5601, HR@5: 0.5745, NDCG@10: 0.5857, HR@10: 0.6555, MRR: 0.5807
test [full], NDCG@5: 0.3962, HR@5: 0.7731, NDCG@10: 0.4692, HR@10: 0.9842, MRR: 0.3103
test [sampled], NDCG@5: 0.5122, HR@5: 0.5235, NDCG@10: 0.5486, HR@10: 0.6396, MRR: 0.5432
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_025.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/sasrec_best.pth
epoch=26, loss=0.0725
epoch=27, loss=0.0705
epoch=28, loss=0.0727
epoch=29, loss=0.0729
epoch=30, loss=0.0710
valid [full], NDCG@5: 0.3345, HR@5: 0.4798, NDCG@10: 0.4963, HR@10: 0.9789, MRR: 0.3559
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5739, NDCG@10: 0.5851, HR@10: 0.6528, MRR: 0.5801
test [full], NDCG@5: 0.4015, HR@5: 0.7692, NDCG@10: 0.4762, HR@10: 0.9943, MRR: 0.3160
test [sampled], NDCG@5: 0.6026, HR@5: 0.6116, NDCG@10: 0.6246, HR@10: 0.6816, MRR: 0.6256
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/sasrec_best.pth
epoch=31, loss=0.0723
epoch=32, loss=0.0707
epoch=33, loss=0.0711
epoch=34, loss=0.0707
epoch=35, loss=0.0695
valid [full], NDCG@5: 0.3216, HR@5: 0.4646, NDCG@10: 0.4896, HR@10: 0.9781, MRR: 0.3479
valid [sampled], NDCG@5: 0.5619, HR@5: 0.5729, NDCG@10: 0.5910, HR@10: 0.6652, MRR: 0.5856
test [full], NDCG@5: 0.4135, HR@5: 0.7248, NDCG@10: 0.5012, HR@10: 0.9921, MRR: 0.3501
test [sampled], NDCG@5: 0.5465, HR@5: 0.5546, NDCG@10: 0.5721, HR@10: 0.6364, MRR: 0.5727
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0710
epoch=37, loss=0.0678
epoch=38, loss=0.0682
epoch=39, loss=0.0705
epoch=40, loss=0.0693
valid [full], NDCG@5: 0.3265, HR@5: 0.4671, NDCG@10: 0.4977, HR@10: 0.9813, MRR: 0.3558
valid [sampled], NDCG@5: 0.5583, HR@5: 0.5676, NDCG@10: 0.5890, HR@10: 0.6653, MRR: 0.5835
test [full], NDCG@5: 0.4504, HR@5: 0.7506, NDCG@10: 0.5316, HR@10: 0.9931, MRR: 0.3889
test [sampled], NDCG@5: 0.5552, HR@5: 0.5647, NDCG@10: 0.5808, HR@10: 0.6456, MRR: 0.5797
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/sasrec_best.pth
epoch=41, loss=0.0699
epoch=42, loss=0.0696
epoch=43, loss=0.0701
epoch=44, loss=0.0700
epoch=45, loss=0.0683
valid [full], NDCG@5: 0.3091, HR@5: 0.4281, NDCG@10: 0.4884, HR@10: 0.9722, MRR: 0.3486
valid [sampled], NDCG@5: 0.5628, HR@5: 0.5766, NDCG@10: 0.5935, HR@10: 0.6733, MRR: 0.5857
test [full], NDCG@5: 0.4417, HR@5: 0.7406, NDCG@10: 0.5255, HR@10: 0.9919, MRR: 0.3827
test [sampled], NDCG@5: 0.5183, HR@5: 0.5300, NDCG@10: 0.5548, HR@10: 0.6456, MRR: 0.5494
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0675
epoch=47, loss=0.0681
epoch=48, loss=0.0693
epoch=49, loss=0.0684
epoch=50, loss=0.0691
valid [full], NDCG@5: 0.3226, HR@5: 0.4609, NDCG@10: 0.4955, HR@10: 0.9849, MRR: 0.3522
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5708, NDCG@10: 0.5886, HR@10: 0.6681, MRR: 0.5824
test [full], NDCG@5: 0.4371, HR@5: 0.7324, NDCG@10: 0.5244, HR@10: 0.9943, MRR: 0.3807
test [sampled], NDCG@5: 0.5043, HR@5: 0.5130, NDCG@10: 0.5386, HR@10: 0.6234, MRR: 0.5360
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012/timeaware01_refine_v3_ml50_do025_seed2024_b9/sasrec_last.pth

## Train time-aware runs for `NDCG@5`

Run these cells only if the corresponding run directory does not already exist.

### timeaware_refine_v3_ml50_do025_seed42_b8_ndcg5

In [ ]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed42_b8_ndcg5 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5
epoch=1, loss=0.5230
epoch=2, loss=0.2295
epoch=3, loss=0.1714
epoch=4, loss=0.1357
epoch=5, loss=0.1166
valid [full], NDCG@5: 0.3808, HR@5: 0.5651, NDCG@10: 0.4552, HR@10: 0.7840, MRR: 0.3650
valid [sampled], NDCG@5: 0.5471, HR@5: 0.5583, NDCG@10: 0.5616, HR@10: 0.6031, MRR: 0.5610
test [full], NDCG@5: 0.2770, HR@5: 0.4411, NDCG@10: 0.3223, HR@10: 0.5745, MRR: 0.2684
test [sampled], NDCG@5: 0.4086, HR@5: 0.4214, NDCG@10: 0.4495, HR@10: 0.5519, MRR: 0.4423
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/sasrec_best.pth
epoch=6, loss=0.1052
epoch=7, loss=0.0972
epoch=8, loss=0.0942
epoch=9, loss=0.0901
epoch=10, loss=0.0862
valid [full], NDCG@5: 0.3044, HR@5: 0.4288, NDCG@10: 0.4234, HR@10: 0.7908, MRR: 0.3297
valid [sampled], NDCG@5: 0.5568, HR@5: 0.5676, NDCG@10: 0.5743, HR@10: 0.6221, MRR: 0.5726
test [full], NDCG@5: 0.2871, HR@5: 0.5503, NDCG@10: 0.3691, HR@10: 0.8010, MRR: 0.2555
test [sampled], NDCG@5: 0.4635, HR@5: 0.4990, NDCG@10: 0.5317, HR@10: 0.7139, MRR: 0.4963
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0852
epoch=12, loss=0.0831
epoch=13, loss=0.0810
epoch=14, loss=0.0792
epoch=15, loss=0.0807
valid [full], NDCG@5: 0.3119, HR@5: 0.4390, NDCG@10: 0.4232, HR@10: 0.7799, MRR: 0.3337
valid [sampled], NDCG@5: 0.5502, HR@5: 0.5652, NDCG@10: 0.5715, HR@10: 0.6325, MRR: 0.5673
test [full], NDCG@5: 0.2829, HR@5: 0.5216, NDCG@10: 0.4105, HR@10: 0.9145, MRR: 0.2664
test [sampled], NDCG@5: 0.5880, HR@5: 0.6492, NDCG@10: 0.6475, HR@10: 0.8313, MRR: 0.6010
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0796
epoch=17, loss=0.0761
epoch=18, loss=0.0740
epoch=19, loss=0.0748
epoch=20, loss=0.0761
valid [full], NDCG@5: 0.3529, HR@5: 0.5246, NDCG@10: 0.4405, HR@10: 0.7906, MRR: 0.3507
valid [sampled], NDCG@5: 0.5450, HR@5: 0.5526, NDCG@10: 0.5594, HR@10: 0.5982, MRR: 0.5626
test [full], NDCG@5: 0.3662, HR@5: 0.6323, NDCG@10: 0.4836, HR@10: 0.9926, MRR: 0.3297
test [sampled], NDCG@5: 0.4665, HR@5: 0.4740, NDCG@10: 0.5131, HR@10: 0.6251, MRR: 0.5043
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0748
epoch=22, loss=0.0753
epoch=23, loss=0.0751
epoch=24, loss=0.0745
epoch=25, loss=0.0728
valid [full], NDCG@5: 0.3290, HR@5: 0.4887, NDCG@10: 0.4244, HR@10: 0.7704, MRR: 0.3389
valid [sampled], NDCG@5: 0.5515, HR@5: 0.5620, NDCG@10: 0.5707, HR@10: 0.6226, MRR: 0.5694
test [full], NDCG@5: 0.3362, HR@5: 0.5909, NDCG@10: 0.4723, HR@10: 0.9907, MRR: 0.3140
test [sampled], NDCG@5: 0.5321, HR@5: 0.5756, NDCG@10: 0.5911, HR@10: 0.7595, MRR: 0.5548
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0710
epoch=27, loss=0.0736
epoch=28, loss=0.0721
epoch=29, loss=0.0722
epoch=30, loss=0.0718
valid [full], NDCG@5: 0.3664, HR@5: 0.5582, NDCG@10: 0.4988, HR@10: 0.9718, MRR: 0.3609
valid [sampled], NDCG@5: 0.5526, HR@5: 0.5645, NDCG@10: 0.5801, HR@10: 0.6518, MRR: 0.5745
test [full], NDCG@5: 0.4195, HR@5: 0.6569, NDCG@10: 0.5364, HR@10: 0.9929, MRR: 0.3946
test [sampled], NDCG@5: 0.5372, HR@5: 0.5455, NDCG@10: 0.5897, HR@10: 0.7141, MRR: 0.5730
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0712
epoch=32, loss=0.0700
epoch=33, loss=0.0720
epoch=34, loss=0.0701
epoch=35, loss=0.0708
valid [full], NDCG@5: 0.3272, HR@5: 0.4771, NDCG@10: 0.4322, HR@10: 0.7942, MRR: 0.3407
valid [sampled], NDCG@5: 0.5526, HR@5: 0.5625, NDCG@10: 0.5709, HR@10: 0.6200, MRR: 0.5701
test [full], NDCG@5: 0.3150, HR@5: 0.5806, NDCG@10: 0.4530, HR@10: 0.9905, MRR: 0.2893
test [sampled], NDCG@5: 0.5117, HR@5: 0.5555, NDCG@10: 0.5752, HR@10: 0.7546, MRR: 0.5373
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0706
epoch=37, loss=0.0703
epoch=38, loss=0.0688
epoch=39, loss=0.0712
epoch=40, loss=0.0694
valid [full], NDCG@5: 0.3395, HR@5: 0.5050, NDCG@10: 0.4876, HR@10: 0.9735, MRR: 0.3479
valid [sampled], NDCG@5: 0.5428, HR@5: 0.5513, NDCG@10: 0.5625, HR@10: 0.6137, MRR: 0.5626
test [full], NDCG@5: 0.3992, HR@5: 0.6731, NDCG@10: 0.5104, HR@10: 0.9887, MRR: 0.3615
test [sampled], NDCG@5: 0.5807, HR@5: 0.5874, NDCG@10: 0.6244, HR@10: 0.7279, MRR: 0.6113
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0712
epoch=42, loss=0.0726
epoch=43, loss=0.0701
epoch=44, loss=0.0706
epoch=45, loss=0.0707
valid [full], NDCG@5: 0.3933, HR@5: 0.6116, NDCG@10: 0.5184, HR@10: 0.9837, MRR: 0.3785
valid [sampled], NDCG@5: 0.5424, HR@5: 0.5513, NDCG@10: 0.5588, HR@10: 0.6028, MRR: 0.5591
test [full], NDCG@5: 0.5069, HR@5: 0.8672, NDCG@10: 0.5497, HR@10: 0.9915, MRR: 0.4100
test [sampled], NDCG@5: 0.5919, HR@5: 0.5968, NDCG@10: 0.6146, HR@10: 0.6702, MRR: 0.6168
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/sasrec_best.pth
epoch=46, loss=0.0679
epoch=47, loss=0.0672
epoch=48, loss=0.0685
epoch=49, loss=0.0682
epoch=50, loss=0.0692
valid [full], NDCG@5: 0.3243, HR@5: 0.4704, NDCG@10: 0.4747, HR@10: 0.9524, MRR: 0.3401
valid [sampled], NDCG@5: 0.5411, HR@5: 0.5529, NDCG@10: 0.5625, HR@10: 0.6205, MRR: 0.5621
test [full], NDCG@5: 0.4349, HR@5: 0.7285, NDCG@10: 0.5233, HR@10: 0.9864, MRR: 0.3805
test [sampled], NDCG@5: 0.5837, HR@5: 0.5975, NDCG@10: 0.6320, HR@10: 0.7517, MRR: 0.6123
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware01_refine_v3_ml50_do025_seed42_b8_ndcg5/sasrec_last.pth

### timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5

In [13]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5
epoch=1, loss=0.5519
epoch=2, loss=0.2364
epoch=3, loss=0.1674
epoch=4, loss=0.1325
epoch=5, loss=0.1179
valid [full], NDCG@5: 0.3085, HR@5: 0.4196, NDCG@10: 0.4362, HR@10: 0.8359, MRR: 0.3342
valid [sampled], NDCG@5: 0.5429, HR@5: 0.5470, NDCG@10: 0.5507, HR@10: 0.5718, MRR: 0.5610
test [full], NDCG@5: 0.1770, HR@5: 0.3432, NDCG@10: 0.3535, HR@10: 0.8840, MRR: 0.2085
test [sampled], NDCG@5: 0.6434, HR@5: 0.6537, NDCG@10: 0.6671, HR@10: 0.7284, MRR: 0.6627
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/sasrec_best.pth
epoch=6, loss=0.1063
epoch=7, loss=0.0971
epoch=8, loss=0.0929
epoch=9, loss=0.0884
epoch=10, loss=0.0878
valid [full], NDCG@5: 0.3030, HR@5: 0.4150, NDCG@10: 0.4625, HR@10: 0.9295, MRR: 0.3342
valid [sampled], NDCG@5: 0.5316, HR@5: 0.5425, NDCG@10: 0.5462, HR@10: 0.5878, MRR: 0.5478
test [full], NDCG@5: 0.2260, HR@5: 0.4359, NDCG@10: 0.4042, HR@10: 0.9762, MRR: 0.2363
test [sampled], NDCG@5: 0.6723, HR@5: 0.7028, NDCG@10: 0.7090, HR@10: 0.8166, MRR: 0.6851
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0851
epoch=12, loss=0.0843
epoch=13, loss=0.0825
epoch=14, loss=0.0805
epoch=15, loss=0.0801
valid [full], NDCG@5: 0.2879, HR@5: 0.3904, NDCG@10: 0.4628, HR@10: 0.9501, MRR: 0.3277
valid [sampled], NDCG@5: 0.5420, HR@5: 0.5509, NDCG@10: 0.5559, HR@10: 0.5940, MRR: 0.5591
test [full], NDCG@5: 0.2746, HR@5: 0.5139, NDCG@10: 0.4314, HR@10: 0.9793, MRR: 0.2674
test [sampled], NDCG@5: 0.5483, HR@5: 0.5716, NDCG@10: 0.6052, HR@10: 0.7513, MRR: 0.5787
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0771
epoch=17, loss=0.0769
epoch=18, loss=0.0762
epoch=19, loss=0.0761
epoch=20, loss=0.0754
valid [full], NDCG@5: 0.2936, HR@5: 0.4110, NDCG@10: 0.4741, HR@10: 0.9779, MRR: 0.3305
valid [sampled], NDCG@5: 0.5468, HR@5: 0.5595, NDCG@10: 0.5636, HR@10: 0.6124, MRR: 0.5656
test [full], NDCG@5: 0.3684, HR@5: 0.7201, NDCG@10: 0.4560, HR@10: 0.9887, MRR: 0.2932
test [sampled], NDCG@5: 0.4776, HR@5: 0.4908, NDCG@10: 0.5199, HR@10: 0.6247, MRR: 0.5127
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0741
epoch=22, loss=0.0737
epoch=23, loss=0.0724
epoch=24, loss=0.0737
epoch=25, loss=0.0719
valid [full], NDCG@5: 0.2906, HR@5: 0.3935, NDCG@10: 0.4824, HR@10: 0.9723, MRR: 0.3413
valid [sampled], NDCG@5: 0.5422, HR@5: 0.5569, NDCG@10: 0.5706, HR@10: 0.6471, MRR: 0.5638
test [full], NDCG@5: 0.3781, HR@5: 0.7327, NDCG@10: 0.4661, HR@10: 0.9945, MRR: 0.3030
test [sampled], NDCG@5: 0.5138, HR@5: 0.5240, NDCG@10: 0.5486, HR@10: 0.6353, MRR: 0.5465
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0724
epoch=27, loss=0.0710
epoch=28, loss=0.0727
epoch=29, loss=0.0732
epoch=30, loss=0.0711
valid [full], NDCG@5: 0.3193, HR@5: 0.4497, NDCG@10: 0.4950, HR@10: 0.9859, MRR: 0.3520
valid [sampled], NDCG@5: 0.5552, HR@5: 0.5701, NDCG@10: 0.5889, HR@10: 0.6763, MRR: 0.5783
test [full], NDCG@5: 0.4001, HR@5: 0.7761, NDCG@10: 0.4743, HR@10: 0.9965, MRR: 0.3119
test [sampled], NDCG@5: 0.4828, HR@5: 0.4948, NDCG@10: 0.5218, HR@10: 0.6191, MRR: 0.5182
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/sasrec_best.pth
epoch=31, loss=0.0722
epoch=32, loss=0.0709
epoch=33, loss=0.0712
epoch=34, loss=0.0710
epoch=35, loss=0.0697
valid [full], NDCG@5: 0.3151, HR@5: 0.4381, NDCG@10: 0.4932, HR@10: 0.9830, MRR: 0.3509
valid [sampled], NDCG@5: 0.5598, HR@5: 0.5723, NDCG@10: 0.5946, HR@10: 0.6826, MRR: 0.5851
test [full], NDCG@5: 0.4132, HR@5: 0.7265, NDCG@10: 0.5015, HR@10: 0.9938, MRR: 0.3509
test [sampled], NDCG@5: 0.5087, HR@5: 0.5165, NDCG@10: 0.5422, HR@10: 0.6243, MRR: 0.5426
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0710
epoch=37, loss=0.0679
epoch=38, loss=0.0683
epoch=39, loss=0.0706
epoch=40, loss=0.0692
valid [full], NDCG@5: 0.3433, HR@5: 0.4933, NDCG@10: 0.5042, HR@10: 0.9770, MRR: 0.3650
valid [sampled], NDCG@5: 0.5380, HR@5: 0.5467, NDCG@10: 0.5665, HR@10: 0.6371, MRR: 0.5624
test [full], NDCG@5: 0.4565, HR@5: 0.7608, NDCG@10: 0.5346, HR@10: 0.9916, MRR: 0.3936
test [sampled], NDCG@5: 0.5162, HR@5: 0.5267, NDCG@10: 0.5506, HR@10: 0.6364, MRR: 0.5485
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_040.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/sasrec_best.pth
epoch=41, loss=0.0700
epoch=42, loss=0.0699
epoch=43, loss=0.0701
epoch=44, loss=0.0701
epoch=45, loss=0.0685
valid [full], NDCG@5: 0.3208, HR@5: 0.4500, NDCG@10: 0.4930, HR@10: 0.9831, MRR: 0.3508
valid [sampled], NDCG@5: 0.5292, HR@5: 0.5416, NDCG@10: 0.5564, HR@10: 0.6272, MRR: 0.5529
test [full], NDCG@5: 0.4090, HR@5: 0.7390, NDCG@10: 0.4915, HR@10: 0.9897, MRR: 0.3387
test [sampled], NDCG@5: 0.5143, HR@5: 0.5249, NDCG@10: 0.5501, HR@10: 0.6385, MRR: 0.5469
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0678
epoch=47, loss=0.0682
epoch=48, loss=0.0693
epoch=49, loss=0.0683
epoch=50, loss=0.0694
valid [full], NDCG@5: 0.3245, HR@5: 0.4567, NDCG@10: 0.4969, HR@10: 0.9837, MRR: 0.3547
valid [sampled], NDCG@5: 0.5472, HR@5: 0.5620, NDCG@10: 0.5772, HR@10: 0.6575, MRR: 0.5711
test [full], NDCG@5: 0.4459, HR@5: 0.7371, NDCG@10: 0.5301, HR@10: 0.9916, MRR: 0.3887
test [sampled], NDCG@5: 0.4995, HR@5: 0.5123, NDCG@10: 0.5338, HR@10: 0.6219, MRR: 0.5315
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5/sasrec_last.pth

### timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5

In [14]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 42 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5
epoch=1, loss=0.5209
epoch=2, loss=0.2295
epoch=3, loss=0.1706
epoch=4, loss=0.1350
epoch=5, loss=0.1166
valid [full], NDCG@5: 0.3670, HR@5: 0.5348, NDCG@10: 0.4507, HR@10: 0.7846, MRR: 0.3604
valid [sampled], NDCG@5: 0.5448, HR@5: 0.5564, NDCG@10: 0.5597, HR@10: 0.6023, MRR: 0.5586
test [full], NDCG@5: 0.2480, HR@5: 0.3927, NDCG@10: 0.3059, HR@10: 0.5675, MRR: 0.2506
test [sampled], NDCG@5: 0.3852, HR@5: 0.3956, NDCG@10: 0.4367, HR@10: 0.5608, MRR: 0.4243
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/sasrec_best.pth
epoch=6, loss=0.1054
epoch=7, loss=0.0975
epoch=8, loss=0.0945
epoch=9, loss=0.0902
epoch=10, loss=0.0861
valid [full], NDCG@5: 0.3118, HR@5: 0.4466, NDCG@10: 0.4260, HR@10: 0.7902, MRR: 0.3309
valid [sampled], NDCG@5: 0.5582, HR@5: 0.5688, NDCG@10: 0.5725, HR@10: 0.6127, MRR: 0.5733
test [full], NDCG@5: 0.2622, HR@5: 0.4931, NDCG@10: 0.3592, HR@10: 0.7860, MRR: 0.2477
test [sampled], NDCG@5: 0.4266, HR@5: 0.4684, NDCG@10: 0.5076, HR@10: 0.7235, MRR: 0.4636
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0854
epoch=12, loss=0.0831
epoch=13, loss=0.0809
epoch=14, loss=0.0796
epoch=15, loss=0.0809
valid [full], NDCG@5: 0.3157, HR@5: 0.4429, NDCG@10: 0.4332, HR@10: 0.7931, MRR: 0.3428
valid [sampled], NDCG@5: 0.5549, HR@5: 0.5687, NDCG@10: 0.5750, HR@10: 0.6323, MRR: 0.5719
test [full], NDCG@5: 0.3416, HR@5: 0.5955, NDCG@10: 0.4731, HR@10: 0.9920, MRR: 0.3167
test [sampled], NDCG@5: 0.5751, HR@5: 0.6053, NDCG@10: 0.6301, HR@10: 0.7786, MRR: 0.6004
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0797
epoch=17, loss=0.0762
epoch=18, loss=0.0743
epoch=19, loss=0.0749
epoch=20, loss=0.0762
valid [full], NDCG@5: 0.3376, HR@5: 0.4955, NDCG@10: 0.4897, HR@10: 0.9798, MRR: 0.3489
valid [sampled], NDCG@5: 0.5397, HR@5: 0.5492, NDCG@10: 0.5539, HR@10: 0.5941, MRR: 0.5577
test [full], NDCG@5: 0.3750, HR@5: 0.6445, NDCG@10: 0.4962, HR@10: 0.9915, MRR: 0.3443
test [sampled], NDCG@5: 0.4638, HR@5: 0.4699, NDCG@10: 0.5048, HR@10: 0.6023, MRR: 0.5014
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0747
epoch=22, loss=0.0751
epoch=23, loss=0.0753
epoch=24, loss=0.0746
epoch=25, loss=0.0729
valid [full], NDCG@5: 0.3159, HR@5: 0.4579, NDCG@10: 0.4854, HR@10: 0.9669, MRR: 0.3459
valid [sampled], NDCG@5: 0.5618, HR@5: 0.5745, NDCG@10: 0.5789, HR@10: 0.6277, MRR: 0.5774
test [full], NDCG@5: 0.3381, HR@5: 0.5849, NDCG@10: 0.4784, HR@10: 0.9886, MRR: 0.3221
test [sampled], NDCG@5: 0.5577, HR@5: 0.5701, NDCG@10: 0.6060, HR@10: 0.7245, MRR: 0.5894
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0712
epoch=27, loss=0.0740
epoch=28, loss=0.0723
epoch=29, loss=0.0723
epoch=30, loss=0.0717
valid [full], NDCG@5: 0.3509, HR@5: 0.5332, NDCG@10: 0.4926, HR@10: 0.9766, MRR: 0.3520
valid [sampled], NDCG@5: 0.5424, HR@5: 0.5576, NDCG@10: 0.5724, HR@10: 0.6528, MRR: 0.5649
test [full], NDCG@5: 0.4716, HR@5: 0.7943, NDCG@10: 0.5392, HR@10: 0.9930, MRR: 0.3990
test [sampled], NDCG@5: 0.5987, HR@5: 0.6076, NDCG@10: 0.6427, HR@10: 0.7482, MRR: 0.6287
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_030.pth
epoch=31, loss=0.0713
epoch=32, loss=0.0701
epoch=33, loss=0.0718
epoch=34, loss=0.0702
epoch=35, loss=0.0708
valid [full], NDCG@5: 0.3301, HR@5: 0.4806, NDCG@10: 0.4853, HR@10: 0.9769, MRR: 0.3446
valid [sampled], NDCG@5: 0.5434, HR@5: 0.5530, NDCG@10: 0.5611, HR@10: 0.6085, MRR: 0.5615
test [full], NDCG@5: 0.3491, HR@5: 0.6008, NDCG@10: 0.4843, HR@10: 0.9922, MRR: 0.3286
test [sampled], NDCG@5: 0.5785, HR@5: 0.5829, NDCG@10: 0.6056, HR@10: 0.6707, MRR: 0.6059
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0710
epoch=37, loss=0.0703
epoch=38, loss=0.0690
epoch=39, loss=0.0713
epoch=40, loss=0.0694
valid [full], NDCG@5: 0.3495, HR@5: 0.5332, NDCG@10: 0.4914, HR@10: 0.9773, MRR: 0.3503
valid [sampled], NDCG@5: 0.5538, HR@5: 0.5620, NDCG@10: 0.5697, HR@10: 0.6124, MRR: 0.5698
test [full], NDCG@5: 0.3836, HR@5: 0.6415, NDCG@10: 0.5035, HR@10: 0.9910, MRR: 0.3529
test [sampled], NDCG@5: 0.6093, HR@5: 0.6159, NDCG@10: 0.6421, HR@10: 0.7212, MRR: 0.6343
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0712
epoch=42, loss=0.0723
epoch=43, loss=0.0700
epoch=44, loss=0.0705
epoch=45, loss=0.0709
valid [full], NDCG@5: 0.4188, HR@5: 0.6645, NDCG@10: 0.5316, HR@10: 0.9875, MRR: 0.3920
valid [sampled], NDCG@5: 0.5586, HR@5: 0.5703, NDCG@10: 0.5756, HR@10: 0.6233, MRR: 0.5745
test [full], NDCG@5: 0.4344, HR@5: 0.6608, NDCG@10: 0.5501, HR@10: 0.9938, MRR: 0.4118
test [sampled], NDCG@5: 0.6417, HR@5: 0.6872, NDCG@10: 0.6841, HR@10: 0.8175, MRR: 0.6520
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_045.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/sasrec_best.pth
epoch=46, loss=0.0680
epoch=47, loss=0.0668
epoch=48, loss=0.0687
epoch=49, loss=0.0683
epoch=50, loss=0.0691
valid [full], NDCG@5: 0.2971, HR@5: 0.4115, NDCG@10: 0.4820, HR@10: 0.9888, MRR: 0.3363
valid [sampled], NDCG@5: 0.5603, HR@5: 0.5727, NDCG@10: 0.5814, HR@10: 0.6389, MRR: 0.5802
test [full], NDCG@5: 0.3582, HR@5: 0.5966, NDCG@10: 0.4919, HR@10: 0.9935, MRR: 0.3389
test [sampled], NDCG@5: 0.6271, HR@5: 0.6908, NDCG@10: 0.6827, HR@10: 0.8604, MRR: 0.6356
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5/sasrec_last.pth

### timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5

In [15]:
!python src/train_sasrec.py \
  --run_name timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5 \
  --hidden_units 50 \
  --num_blocks 2 \
  --num_heads 1 \
  --maxlen 50 \
  --lr 0.001 \
  --dropout_rate 0.25 \
  --seed 2024 \
  --use_time_embedding \
  --time_delta_column delta_prev_seconds \
  --time_bucket_first_event_separate \
  --time_bucket_zero_gap_separate \
  --time_bucket_boundaries 60,600,3600,86400,604800 \
  --output_dir "/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5" \
  --selection_metric full_valid_ndcg@5 \
  --interactions_path data/processed/bpi2012_complete_only/sasrec_interactions.txt \
  --batch_size 128 \
  --num_epochs 50 \
  --eval_every 5 \
  --device cuda \
  --num_negative_samples 100 \
  --eval_protocol both \
  --topk_list 5,10 \
  --save_every_eval

dataset split summary: users=13087, items=23, train_users=13087, valid_users=9658, test_users=9658, train_only_users=3429
interaction split: train=145190 (88.26%), valid=9658 (5.87%), test=9658 (5.87%), total=164506
avg_train_len=11.09, users_with_eval_targets=9658
batches_per_epoch=103
selection_metric=full_valid_ndcg@5
run_dir=/content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5
epoch=1, loss=0.5482
epoch=2, loss=0.2356
epoch=3, loss=0.1668
epoch=4, loss=0.1322
epoch=5, loss=0.1178
valid [full], NDCG@5: 0.3212, HR@5: 0.4373, NDCG@10: 0.4419, HR@10: 0.8269, MRR: 0.3438
valid [sampled], NDCG@5: 0.5618, HR@5: 0.5680, NDCG@10: 0.5733, HR@10: 0.6042, MRR: 0.5809
test [full], NDCG@5: 0.2013, HR@5: 0.4035, NDCG@10: 0.3591, HR@10: 0.8761, MRR: 0.2163
test [sampled], NDCG@5: 0.6374, HR@5: 0.6534, NDCG@10: 0.6654, HR@10: 0.7416, MRR: 0.6562
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_005.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/sasrec_best.pth
epoch=6, loss=0.1066
epoch=7, loss=0.0974
epoch=8, loss=0.0929
epoch=9, loss=0.0885
epoch=10, loss=0.0875
valid [full], NDCG@5: 0.2984, HR@5: 0.4138, NDCG@10: 0.4688, HR@10: 0.9610, MRR: 0.3311
valid [sampled], NDCG@5: 0.5543, HR@5: 0.5655, NDCG@10: 0.5669, HR@10: 0.6042, MRR: 0.5699
test [full], NDCG@5: 0.2183, HR@5: 0.4307, NDCG@10: 0.3998, HR@10: 0.9822, MRR: 0.2290
test [sampled], NDCG@5: 0.4755, HR@5: 0.5616, NDCG@10: 0.5577, HR@10: 0.8136, MRR: 0.4911
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_010.pth
epoch=11, loss=0.0852
epoch=12, loss=0.0841
epoch=13, loss=0.0823
epoch=14, loss=0.0803
epoch=15, loss=0.0793
valid [full], NDCG@5: 0.2851, HR@5: 0.3853, NDCG@10: 0.4661, HR@10: 0.9579, MRR: 0.3286
valid [sampled], NDCG@5: 0.5627, HR@5: 0.5724, NDCG@10: 0.5752, HR@10: 0.6108, MRR: 0.5786
test [full], NDCG@5: 0.2588, HR@5: 0.5101, NDCG@10: 0.4150, HR@10: 0.9789, MRR: 0.2475
test [sampled], NDCG@5: 0.3306, HR@5: 0.3797, NDCG@10: 0.4268, HR@10: 0.6827, MRR: 0.3731
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_015.pth
epoch=16, loss=0.0767
epoch=17, loss=0.0766
epoch=18, loss=0.0755
epoch=19, loss=0.0759
epoch=20, loss=0.0748
valid [full], NDCG@5: 0.3053, HR@5: 0.4394, NDCG@10: 0.4680, HR@10: 0.9473, MRR: 0.3331
valid [sampled], NDCG@5: 0.5589, HR@5: 0.5705, NDCG@10: 0.5706, HR@10: 0.6071, MRR: 0.5747
test [full], NDCG@5: 0.3713, HR@5: 0.7278, NDCG@10: 0.4548, HR@10: 0.9788, MRR: 0.2947
test [sampled], NDCG@5: 0.4149, HR@5: 0.4408, NDCG@10: 0.4681, HR@10: 0.6075, MRR: 0.4502
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_020.pth
epoch=21, loss=0.0740
epoch=22, loss=0.0736
epoch=23, loss=0.0725
epoch=24, loss=0.0736
epoch=25, loss=0.0718
valid [full], NDCG@5: 0.2992, HR@5: 0.4160, NDCG@10: 0.4757, HR@10: 0.9440, MRR: 0.3427
valid [sampled], NDCG@5: 0.5601, HR@5: 0.5745, NDCG@10: 0.5857, HR@10: 0.6555, MRR: 0.5807
test [full], NDCG@5: 0.3962, HR@5: 0.7731, NDCG@10: 0.4692, HR@10: 0.9842, MRR: 0.3103
test [sampled], NDCG@5: 0.5122, HR@5: 0.5235, NDCG@10: 0.5486, HR@10: 0.6396, MRR: 0.5432
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_025.pth
epoch=26, loss=0.0725
epoch=27, loss=0.0705
epoch=28, loss=0.0727
epoch=29, loss=0.0729
epoch=30, loss=0.0710
valid [full], NDCG@5: 0.3345, HR@5: 0.4798, NDCG@10: 0.4963, HR@10: 0.9789, MRR: 0.3559
valid [sampled], NDCG@5: 0.5599, HR@5: 0.5739, NDCG@10: 0.5851, HR@10: 0.6528, MRR: 0.5801
test [full], NDCG@5: 0.4015, HR@5: 0.7692, NDCG@10: 0.4762, HR@10: 0.9943, MRR: 0.3160
test [sampled], NDCG@5: 0.6026, HR@5: 0.6116, NDCG@10: 0.6246, HR@10: 0.6816, MRR: 0.6256
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_030.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/sasrec_best.pth
epoch=31, loss=0.0723
epoch=32, loss=0.0707
epoch=33, loss=0.0711
epoch=34, loss=0.0707
epoch=35, loss=0.0695
valid [full], NDCG@5: 0.3216, HR@5: 0.4646, NDCG@10: 0.4896, HR@10: 0.9781, MRR: 0.3479
valid [sampled], NDCG@5: 0.5619, HR@5: 0.5729, NDCG@10: 0.5910, HR@10: 0.6652, MRR: 0.5856
test [full], NDCG@5: 0.4135, HR@5: 0.7248, NDCG@10: 0.5012, HR@10: 0.9921, MRR: 0.3501
test [sampled], NDCG@5: 0.5465, HR@5: 0.5546, NDCG@10: 0.5721, HR@10: 0.6364, MRR: 0.5727
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_035.pth
epoch=36, loss=0.0710
epoch=37, loss=0.0678
epoch=38, loss=0.0682
epoch=39, loss=0.0705
epoch=40, loss=0.0693
valid [full], NDCG@5: 0.3265, HR@5: 0.4671, NDCG@10: 0.4977, HR@10: 0.9813, MRR: 0.3558
valid [sampled], NDCG@5: 0.5583, HR@5: 0.5676, NDCG@10: 0.5890, HR@10: 0.6653, MRR: 0.5835
test [full], NDCG@5: 0.4504, HR@5: 0.7506, NDCG@10: 0.5316, HR@10: 0.9931, MRR: 0.3889
test [sampled], NDCG@5: 0.5552, HR@5: 0.5647, NDCG@10: 0.5808, HR@10: 0.6456, MRR: 0.5797
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_040.pth
epoch=41, loss=0.0699
epoch=42, loss=0.0696
epoch=43, loss=0.0701
epoch=44, loss=0.0700
epoch=45, loss=0.0683
valid [full], NDCG@5: 0.3091, HR@5: 0.4281, NDCG@10: 0.4884, HR@10: 0.9722, MRR: 0.3486
valid [sampled], NDCG@5: 0.5628, HR@5: 0.5766, NDCG@10: 0.5935, HR@10: 0.6733, MRR: 0.5857
test [full], NDCG@5: 0.4417, HR@5: 0.7406, NDCG@10: 0.5255, HR@10: 0.9919, MRR: 0.3827
test [sampled], NDCG@5: 0.5183, HR@5: 0.5300, NDCG@10: 0.5548, HR@10: 0.6456, MRR: 0.5494
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_045.pth
epoch=46, loss=0.0675
epoch=47, loss=0.0681
epoch=48, loss=0.0693
epoch=49, loss=0.0684
epoch=50, loss=0.0691
valid [full], NDCG@5: 0.3226, HR@5: 0.4609, NDCG@10: 0.4955, HR@10: 0.9849, MRR: 0.3522
valid [sampled], NDCG@5: 0.5579, HR@5: 0.5708, NDCG@10: 0.5886, HR@10: 0.6681, MRR: 0.5824
test [full], NDCG@5: 0.4371, HR@5: 0.7324, NDCG@10: 0.5244, HR@10: 0.9943, MRR: 0.3807
test [sampled], NDCG@5: 0.5043, HR@5: 0.5130, NDCG@10: 0.5386, HR@10: 0.6234, MRR: 0.5360
saved eval checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/checkpoints/sasrec_epoch_050.pth
saved checkpoint: /content/drive/MyDrive/ai-projects/time-aware-behavior-prediction/outputs/sasrec_timeaware_bpi2012_ndcg5/timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5/sasrec_last.pth

## Rebuild result tables from run folders

This avoids schema issues in `experiment_index.csv` and lets us combine old baseline runs with new time-aware runs safely.

In [16]:
from pathlib import Path
import json
import pandas as pd

def rebuild_df(output_dir: str):
    rows = []
    output_path = Path(output_dir)
    if not output_path.exists():
        return pd.DataFrame()
    for run_dir in output_path.iterdir():
        if not run_dir.is_dir():
            continue
        summary_path = run_dir / 'metrics_summary.json'
        config_path = run_dir / 'config.json'
        if not summary_path.exists() or not config_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        config = json.loads(config_path.read_text(encoding='utf-8'))
        row = {
            'run_name': summary.get('run_name'),
            'run_dir': str(run_dir),
            'completed_at': summary.get('completed_at'),
            'best_epoch': summary.get('best_epoch'),
            'checkpoint_best': summary.get('checkpoint_best'),
            'checkpoint_last': summary.get('checkpoint_last'),
            'metrics_history': summary.get('metrics_history'),
            'config_path': str(config_path),
            'metrics_summary': str(summary_path),
            'maxlen': config.get('maxlen'),
            'dropout_rate': config.get('dropout_rate'),
            'hidden_units': config.get('hidden_units'),
            'seed': config.get('seed'),
            'selection_metric': config.get('selection_metric'),
            'use_time_embedding': config.get('use_time_embedding', False),
            'time_bucket_boundaries': ','.join(str(x) for x in config.get('time_bucket_boundaries', [])),
            'time_bucket_count': config.get('time_bucket_count'),
        }
        best_valid = summary.get('best_valid', {})
        best_test = summary.get('best_test_at_best_valid', {})
        def pick(metrics_group, mode, key):
            return metrics_group.get(mode, {}).get(key)
        row.update({
            'best_valid_full_ndcg@10': pick(best_valid, 'full', 'ndcg@10'),
            'best_valid_full_hr@10': pick(best_valid, 'full', 'hr@10'),
            'best_valid_full_ndcg@5': pick(best_valid, 'full', 'ndcg@5'),
            'best_valid_full_hr@5': pick(best_valid, 'full', 'hr@5'),
            'best_valid_full_mrr': pick(best_valid, 'full', 'mrr'),
            'best_test_full_ndcg@10': pick(best_test, 'full', 'ndcg@10'),
            'best_test_full_hr@10': pick(best_test, 'full', 'hr@10'),
            'best_test_full_ndcg@5': pick(best_test, 'full', 'ndcg@5'),
            'best_test_full_hr@5': pick(best_test, 'full', 'hr@5'),
            'best_test_full_mrr': pick(best_test, 'full', 'mrr'),
            'best_valid_sampled_ndcg@10': pick(best_valid, 'sampled', 'ndcg@10'),
            'best_valid_sampled_hr@10': pick(best_valid, 'sampled', 'hr@10'),
            'best_valid_sampled_ndcg@5': pick(best_valid, 'sampled', 'ndcg@5'),
            'best_valid_sampled_hr@5': pick(best_valid, 'sampled', 'hr@5'),
            'best_valid_sampled_mrr': pick(best_valid, 'sampled', 'mrr'),
            'best_test_sampled_ndcg@10': pick(best_test, 'sampled', 'ndcg@10'),
            'best_test_sampled_hr@10': pick(best_test, 'sampled', 'hr@10'),
            'best_test_sampled_ndcg@5': pick(best_test, 'sampled', 'ndcg@5'),
            'best_test_sampled_hr@5': pick(best_test, 'sampled', 'hr@5'),
            'best_test_sampled_mrr': pick(best_test, 'sampled', 'mrr'),
        })
        rows.append(row)
    return pd.DataFrame(rows)

## NDCG@10 comparison summary

In [17]:
ndcg10_baseline_runs = [
    'refine_v3_ml50_do025_seed42',
    'refine_v3_ml50_do025_seed2024',
]
ndcg10_timeaware_runs = [
    'timeaware_refine_v3_ml50_do025_seed42_b8',
    'timeaware_refine_v3_ml50_do025_seed2024_b8',
    'timeaware_refine_v3_ml50_do025_seed42_b9',
    'timeaware_refine_v3_ml50_do025_seed2024_b9',
]

baseline_df = rebuild_df(BASELINE_NDCG10_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG10_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(ndcg10_baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['bucket_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(ndcg10_timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['bucket_variant'] = timeaware_subset['run_name'].apply(lambda x: 'b8' if '_b8' in x else 'b9')

df_ndcg10 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg10 = df_ndcg10.sort_values(['bucket_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg10[[
    'run_name', 'seed', 'bucket_variant', 'use_time_embedding', 'time_bucket_boundaries',
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]]

,run_name,seed,bucket_variant,use_time_embedding,time_bucket_boundaries,best_valid_full_ndcg@5,best_test_full_ndcg@5,best_valid_full_ndcg@10,best_test_full_ndcg@10,best_valid_full_mrr,best_test_full_mrr,best_valid_sampled_ndcg@5,best_test_sampled_ndcg@5,best_valid_sampled_ndcg@10,best_test_sampled_ndcg@10,best_valid_sampled_mrr,best_test_sampled_mrr
0,timeaware_refine_v3_ml50_do025_seed42_b8,42,b8,True,"6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0",0.393344,0.506900,0.518353,0.549708,0.378457,0.410007,0.542432,0.591895,0.558799,0.614605,0.559129,0.616780
1,refine_v3_ml50_do025_seed42,42,baseline,False,,0.387751,0.416791,0.512117,0.546236,0.372049,0.406292,0.541576,0.809862,0.550634,0.820534,0.557796,0.816182
2,refine_v3_ml50_do025_seed2024,2024,baseline,False,,0.376172,0.337719,0.500475,0.460943,0.356303,0.299817,0.553469,0.811153,0.569319,0.821949,0.569866,0.816608

In [18]:
summary_ndcg10 = df_ndcg10.groupby('bucket_variant')[[
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg10

               best_valid_full_ndcg@5           best_test_full_ndcg@5  \
                                 mean       std                  mean
bucket_variant
b8                           0.393344       NaN              0.506900
baseline                     0.381962  0.008188              0.377255

                         best_valid_full_ndcg@10            \
                     std                    mean       std
bucket_variant
b8                   NaN                0.518353       NaN
baseline        0.055912                0.506296  0.008232

               best_test_full_ndcg@10           best_valid_full_mrr            \
                                 mean       std                mean       std
bucket_variant
b8                           0.549708       NaN            0.378457       NaN
baseline                     0.503589  0.060311            0.364176  0.011134

                ... best_test_sampled_ndcg@5            \
                ...                     mean       std
bucket_variant  ...
b8              ...                 0.591895       NaN
baseline        ...                 0.810507  0.000913

               best_valid_sampled_ndcg@10           best_test_sampled_ndcg@10  \
                                     mean       std                      mean
bucket_variant
b8                               0.558799       NaN                  0.614605
baseline                         0.559976  0.013212                  0.821241

                         best_valid_sampled_mrr            \
                     std                   mean       std
bucket_variant
b8                   NaN               0.559129       NaN
baseline        0.001001               0.563831  0.008535

               best_test_sampled_mrr
                                mean       std
bucket_variant
b8                          0.616780       NaN
baseline                    0.816395  0.000301

[2 rows x 24 columns]

Interpretation guide for NDCG@10:
- first compare `best_valid_full_ndcg@10` and `best_test_full_ndcg@10` across `baseline`, `b8`, and `b9`
- then check whether sampled metrics and MRR show a similar trend
- because baseline is reused from existing runs, only the time-aware runs are newly trained here

## NDCG@5 comparison summary

In [19]:
ndcg5_baseline_runs = [
    'refine_v3_ml50_do025_seed42_ndcg5',
    'refine_v3_ml50_do025_seed2024_ndcg5',
]
ndcg5_timeaware_runs = [
    'timeaware_refine_v3_ml50_do025_seed42_b8_ndcg5',
    'timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5',
    'timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5',
    'timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5',
]

baseline_df = rebuild_df(BASELINE_NDCG5_OUTPUT_DIR)
timeaware_df = rebuild_df(TIMEAWARE_NDCG5_OUTPUT_DIR)

baseline_subset = baseline_df[baseline_df['run_name'].isin(ndcg5_baseline_runs)].copy()
baseline_subset['model_variant'] = 'baseline'
baseline_subset['bucket_variant'] = 'baseline'

timeaware_subset = timeaware_df[timeaware_df['run_name'].isin(ndcg5_timeaware_runs)].copy()
timeaware_subset['model_variant'] = 'timeaware'
timeaware_subset['bucket_variant'] = timeaware_subset['run_name'].apply(lambda x: 'b8' if '_b8' in x else 'b9')

df_ndcg5 = pd.concat([baseline_subset, timeaware_subset], ignore_index=True)
df_ndcg5 = df_ndcg5.sort_values(['bucket_variant', 'seed', 'run_name']).reset_index(drop=True)
df_ndcg5[[
    'run_name', 'seed', 'bucket_variant', 'use_time_embedding', 'time_bucket_boundaries',
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]]

,run_name,seed,bucket_variant,use_time_embedding,time_bucket_boundaries,best_valid_full_ndcg@5,best_test_full_ndcg@5,best_valid_full_ndcg@10,best_test_full_ndcg@10,best_valid_full_mrr,best_test_full_mrr,best_valid_sampled_ndcg@5,best_test_sampled_ndcg@5,best_valid_sampled_ndcg@10,best_test_sampled_ndcg@10,best_valid_sampled_mrr,best_test_sampled_mrr
0,timeaware_refine_v3_ml50_do025_seed2024_b8_ndcg5,2024,b8,True,"6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0",0.343342,0.456528,0.504194,0.534630,0.365027,0.393623,0.538029,0.516153,0.566497,0.550565,0.562444,0.548457
1,timeaware_refine_v3_ml50_do025_seed42_b9_ndcg5,42,b9,True,"6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0",0.418780,0.434443,0.531580,0.550074,0.391962,0.411806,0.558631,0.641690,0.575569,0.684092,0.574527,0.652048
2,timeaware_refine_v3_ml50_do025_seed2024_b9_ndcg5,2024,b9,True,"6,0,,,6,0,0,,,3,6,0,0,,,8,6,4,0,0,,,6,0,4,8,0,0",0.334544,0.401456,0.496344,0.476183,0.355911,0.315984,0.559936,0.602599,0.585103,0.624628,0.580096,0.625630
3,refine_v3_ml50_do025_seed42_ndcg5,42,baseline,False,,0.387751,0.416791,0.512117,0.546236,0.372049,0.406292,0.541576,0.809862,0.550634,0.820534,0.557796,0.816182
4,refine_v3_ml50_do025_seed2024_ndcg5,2024,baseline,False,,0.376172,0.337719,0.500475,0.460943,0.356303,0.299817,0.553469,0.811153,0.569319,0.821949,0.569866,0.816608

In [20]:
summary_ndcg5 = df_ndcg5.groupby('bucket_variant')[[
    'best_valid_full_ndcg@5', 'best_test_full_ndcg@5',
    'best_valid_full_ndcg@10', 'best_test_full_ndcg@10',
    'best_valid_full_mrr', 'best_test_full_mrr',
    'best_valid_sampled_ndcg@5', 'best_test_sampled_ndcg@5',
    'best_valid_sampled_ndcg@10', 'best_test_sampled_ndcg@10',
    'best_valid_sampled_mrr', 'best_test_sampled_mrr',
]].agg(['mean', 'std'])
summary_ndcg5

               best_valid_full_ndcg@5           best_test_full_ndcg@5  \
                                 mean       std                  mean
bucket_variant
b8                           0.343342       NaN              0.456528
b9                           0.376662  0.059564              0.417949
baseline                     0.381962  0.008188              0.377255

                         best_valid_full_ndcg@10            \
                     std                    mean       std
bucket_variant
b8                   NaN                0.504194       NaN
b9              0.023326                0.513962  0.024916
baseline        0.055912                0.506296  0.008232

               best_test_full_ndcg@10           best_valid_full_mrr            \
                                 mean       std                mean       std
bucket_variant
b8                           0.534630       NaN            0.365027       NaN
b9                           0.513128  0.052249            0.373936  0.025492
baseline                     0.503589  0.060311            0.364176  0.011134

                ... best_test_sampled_ndcg@5            \
                ...                     mean       std
bucket_variant  ...
b8              ...                 0.516153       NaN
b9              ...                 0.622144  0.027641
baseline        ...                 0.810507  0.000913

               best_valid_sampled_ndcg@10           best_test_sampled_ndcg@10  \
                                     mean       std                      mean
bucket_variant
b8                               0.566497       NaN                  0.550565
b9                               0.580336  0.006741                  0.654360
baseline                         0.559976  0.013212                  0.821241

                         best_valid_sampled_mrr            \
                     std                   mean       std
bucket_variant
b8                   NaN               0.562444       NaN
b9              0.042047               0.577312  0.003938
baseline        0.001001               0.563831  0.008535

               best_test_sampled_mrr
                                mean       std
bucket_variant
b8                          0.548457       NaN
b9                          0.638839  0.018680
baseline                    0.816395  0.000301

[3 rows x 24 columns]

Interpretation guide for NDCG@5:
- first compare `best_valid_full_ndcg@5` and `best_test_full_ndcg@5` across `baseline`, `b8`, and `b9`
- then check whether sampled metrics and MRR show a similar trend
- because baseline is reused from existing runs, only the time-aware runs are newly trained here